function(assert_not_empty param)
  if (NOT DEFINED param)
    error("Parameter is not set.")
  endif ()
  string(STRIP "${param}" param_stripped)
  if ("${param_stripped}" STREQUAL "")
    error("Parameter is empty.")
  endif ()
endfunction()