GLESC: CustomTestingFramework.h File Reference
CustomTestingFramework.h File Reference
@TODO Add description of this file if needed
#include <cmath>
#include <gtest/gtest.h>
#include <iostream>
#include <type_traits>
#include "engine/core/debugger/Stringer.h"
#include "engine/core/math/Math.h"
Macros
#define EXPECT_EQ_CUSTOM(a, b) expectEqCustom(a, b)
#define EXPECT_NE_CUSTOM(a, b) expectNeCustom(a, b)
#define TEST_SECTION(title)
Functions
template<typename Type1 , typename Type2 >
void expectEqCustom (const Type1 &a, const Type2 &b)
template<typename Type1 , typename Type2 >
void expectEqCustomEpsilon (const Type1 &a, const Type2 &b, const Type1 &epsilon)
template<typename Type1 , typename Type2 >
void expectNeCustom (const Type1 &a, const Type2 &b)
Detailed Description
@TODO Add description of this file if needed
Author
Valentin Dumitru
Date
25/01/2024
Copyright (c) 2024 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file CustomTestingFramework.h.
Macro Definition Documentation
EXPECT_EQ_CUSTOM
#define EXPECT_EQ_CUSTOM (a, b) expectEqCustom(a, b)
Definition at line 58 of file CustomTestingFramework.h.
EXPECT_NE_CUSTOM
#define EXPECT_NE_CUSTOM (a, b) expectNeCustom(a, b)
Definition at line 54 of file CustomTestingFramework.h.
TEST_SECTION
#define TEST_SECTION (title)
Value:
    std::cout << "______________________________________________________________________________________________\n"; \
    std::cout << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%" << title << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n"; \
    std::cout << "______________________________________________________________________________________________\n";
Definition at line 62 of file CustomTestingFramework.h.
Function Documentation
expectEqCustom()
template<typename Type1 , typename Type2 > void expectEqCustom (const Type1 & a, const Type2 & b)
Definition at line 22 of file CustomTestingFramework.h.
{
    std::cout << "Comparing values: " << GLESC::Stringer::toString(a) << " and " << GLESC::Stringer::toString(b);
    if constexpr (std::is_floating_point_v<Type1> || std::is_floating_point_v<Type2>) {
        // * 1000 to account for multiple operations
        auto epsilon = GLESC::Math::max(GLESC::Math::epsilon(a), GLESC::Math::epsilon(b)) * 10000;
        std::cout << " with epsilon: " << GLESC::Stringer::toString(epsilon) << "\n";
        EXPECT_NEAR(a, b, epsilon);
    }
    else{
        EXPECT_EQ(a, b);
        std::cout << "\n";
    }
}
References GLESC::Math::epsilon(), GLESC::Math::max(), and GLESC::Stringer::toString().
Referenced by expectEqMat(), and expectEqVec().
expectEqCustomEpsilon()
template<typename Type1 , typename Type2 > void expectEqCustomEpsilon (const Type1 & a, const Type2 & b, const Type1 & epsilon)
Definition at line 37 of file CustomTestingFramework.h.
{
    std::cout << "Comparing values: " << GLESC::Stringer::toString(a) << " and " << GLESC::Stringer::toString(b);
    if constexpr (std::is_floating_point_v<Type1> || std::is_floating_point_v<Type2>) {
        std::cout << " with epsilon: " << GLESC::Stringer::toString(epsilon) << "\n";
        EXPECT_NEAR(a, b, epsilon);
    }
    else{
        EXPECT_EQ(a, b);
        std::cout << "\n";
    }
}
References GLESC::Stringer::toString().
Referenced by expectEqMatEpsilon().
expectNeCustom()
template<typename Type1 , typename Type2 > void expectNeCustom (const Type1 & a, const Type2 & b)
Definition at line 50 of file CustomTestingFramework.h.
{
    EXPECT_FALSE(GLESC::Math::eq(a, b));
}
References GLESC::Math::eq().