GLESC: DebugEntityDataHUD.cpp File Reference
DebugEntityDataHUD.cpp File Reference
@TODO Add description of this file if needed
#include "engine/subsystems/hud/engine-hud/DebugEntityDataHUD.h"
#include "engine/core/math/algebra/matrix/Matrix.h"
#include "engine/core/math/algebra/vector/Vector.h"
#include "engine/subsystems/hud/HUDLookAndFeel.h"
#include "engine/subsystems/ingame-debug/EntityStatsManager.h"
Functions
template<typename InputType >
void input (const std::string &name, InputType *data)
template<typename InputType >
void input (EntityStatsManager::Value &value)
void putInputForType (EntityStatsManager::ValueType type, EntityStatsManager::Value &value)
template<typename InputType >
void slider (const std::string &name, InputType *data, const float &minParam, const float &maxParam)
template<typename InputType >
void text (const std::string &name, InputType *data)
Detailed Description
@TODO Add description of this file if needed
Author
Valentin Dumitru
Date
09/03/2024
Copyright (c) 2024 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file DebugEntityDataHUD.cpp.
Function Documentation
input() [1/2]
template<typename InputType > void input (const std::string & name, InputType * data)
Definition at line 115 of file DebugEntityDataHUD.cpp.
{
    std::string inputName = "##" + name + " -- Input";
    if constexpr (std::is_same_v<InputType, float>) {
        ImGui::InputFloat(inputName.c_str(), data);
    }
    else if constexpr (std::is_same_v<InputType, int>) {
        ImGui::InputInt(inputName.c_str(), data);
    }
    else if constexpr (std::is_same_v<InputType, bool>) {
        ImGui::Checkbox(inputName.c_str(), data);
    }
    else if constexpr (std::is_same_v<InputType, std::string>) {
        ImGui::InputText(inputName.c_str(), data->data(), data->size());
    }
    else if constexpr (std::is_same_v<InputType, Vec2F>) {
        ImGui::InputFloat2(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec3F>) {
        ImGui::InputFloat3(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec4F>) {
        ImGui::InputFloat4(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec2I>) {
        ImGui::InputInt2(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec3I>) {
        ImGui::InputInt3(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec4I>) {
        ImGui::InputInt4(inputName.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec2B>) {
        ImGui::Checkbox(std::string(" - x ").c_str(), &data->x());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - y ").c_str(), &data->y());
    }
    else if constexpr (std::is_same_v<InputType, Vec3B>) {
        ImGui::Checkbox(std::string(" - x ").c_str(), &data->x());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - y ").c_str(), &data->y());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - z ").c_str(), &data->z());
    }
    else if constexpr (std::is_same_v<InputType, Vec4B>) {
        ImGui::Checkbox(std::string(" - x ").c_str(), &data->x());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - y ").c_str(), &data->y());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - z ").c_str(), &data->z());
        ImGui::SameLine();
        ImGui::Checkbox(std::string(" - w ").c_str(), &data->w());
    }
}
References GLESC::isIterable_v.
Referenced by input(), GLESC::EngineCamera::setupCamera(), and GLESC::ECS::InputSystem::update().
input() [2/2]
template<typename InputType > void input (EntityStatsManager::Value & value)
Definition at line 173 of file DebugEntityDataHUD.cpp.
{
    auto inputValue = reinterpret_cast<InputType*>(value.data);
    ImGui::PushItemWidth(-FLT_MIN); // Set the width of the input field to the maximum width of the window
    text(value.name, inputValue);
    if (!value.isModifiable) return;
    if (value.usesSlider) {
        slider(value.name, inputValue, value.min, value.max);
    }
    input(value.name, inputValue);
    ImGui::PopItemWidth();
}
References input(), GLESC::isIterable_v, slider(), and text().
putInputForType()
void putInputForType (EntityStatsManager::ValueType type, EntityStatsManager::Value & value)
Definition at line 186 of file DebugEntityDataHUD.cpp.
{
    switch (type) {
    case EntityStatsManager::ValueType::FLOAT:
        input<float>(value);
        break;
    case EntityStatsManager::ValueType::INT:
        input<int>(value);
        break;
    case EntityStatsManager::ValueType::BOOL:
        input<bool>(value);
        break;
    case EntityStatsManager::ValueType::VEC2B:
        input<Vec2B>(value);
        break;
    case EntityStatsManager::ValueType::VEC3B:
        input<Vec3B>(value);
        break;
    case EntityStatsManager::ValueType::VEC4B:
        input<Vec4B>(value);
        break;
    case EntityStatsManager::ValueType::STRING:
        input<std::string>(value);
        break;
    case EntityStatsManager::ValueType::VEC2F:
        input<Vec2F>(value);
        break;
    case EntityStatsManager::ValueType::VEC3F:
        input<Vec3F>(value);
        break;
    case EntityStatsManager::ValueType::VEC4F:
        input<Vec4F>(value);
        break;
    case EntityStatsManager::ValueType::VEC2I:
        input<Vec2I>(value);
        break;
    case EntityStatsManager::ValueType::VEC3I:
        input<Vec3I>(value);
        break;
    case EntityStatsManager::ValueType::VEC4I:
        input<Vec4I>(value);
        break;
    case EntityStatsManager::ValueType::MAT2F:
        input<Mat2F>(value);
        break;
    case EntityStatsManager::ValueType::MAT3F:
        input<Mat3F>(value);
        break;
    case EntityStatsManager::ValueType::MAT4F:
        input<Mat4F>(value);
        break;
    default: {
        D_ASSERT_TRUE(false, "Unknown value type");
    }
    }
}
References EntityStatsManager::BOOL, D_ASSERT_TRUE, EntityStatsManager::FLOAT, EntityStatsManager::INT, GLESC::isIterable_v, EntityStatsManager::MAT2F, EntityStatsManager::MAT3F, EntityStatsManager::MAT4F, EntityStatsManager::STRING, EntityStatsManager::VEC2B, EntityStatsManager::VEC2F, EntityStatsManager::VEC2I, EntityStatsManager::VEC3B, EntityStatsManager::VEC3F, EntityStatsManager::VEC3I, EntityStatsManager::VEC4B, EntityStatsManager::VEC4F, and EntityStatsManager::VEC4I.
Referenced by GLESC::HUD::DebugEntityData::windowContent().
slider()
template<typename InputType > void slider (const std::string & name, InputType * data, const float & minParam, const float & maxParam)
Definition at line 89 of file DebugEntityDataHUD.cpp.
{
    std::string inputName = "##" + name + " -- Slider";
    if constexpr (std::is_same_v<InputType, float>) {
        ImGui::SliderFloat(inputName.c_str(), data, minParam, maxParam);
    }
    else if constexpr (std::is_same_v<InputType, int>) {
        ImGui::SliderInt(inputName.c_str(), data, minParam, static_cast<int>(maxParam));
    }
    else if constexpr (std::is_same_v<InputType, Vec2F>) {
        ImGui::SliderFloat2(inputName.c_str(), data->data.data(), minParam, maxParam);
    }
    else if constexpr (std::is_same_v<InputType, Vec3F>) {
        ImGui::SliderFloat3(inputName.c_str(), data->data.data(), minParam, maxParam);
    }
    else if constexpr (std::is_same_v<InputType, Vec4F>) {
        ImGui::SliderFloat4(inputName.c_str(), data->data.data(), minParam, maxParam);
    }
    else if constexpr (std::is_same_v<InputType, Vec2I>) {
        ImGui::SliderInt2(inputName.c_str(), data->data.data(), minParam, static_cast<int>(maxParam));
    }
    else if constexpr (std::is_same_v<InputType, Vec3I>) {
        ImGui::SliderInt3(inputName.c_str(), data->data.data(), minParam, static_cast<int>(maxParam));
    }
}
References GLESC::isIterable_v.
Referenced by input().
text()
template<typename InputType > void text (const std::string & name, InputType * data)
Definition at line 38 of file DebugEntityDataHUD.cpp.
{
    if constexpr (std::is_same_v<InputType, float>) {
        ImGui::Text(name.c_str(), *data);
    }
    else if constexpr (std::is_same_v<InputType, int>) {
        ImGui::Text(name.c_str(), *data);
    }
    else if constexpr (std::is_same_v<InputType, bool>) {
        ImGui::Text(name.c_str(), *data ? "true" : "false");
    }
    else if constexpr (std::is_same_v<InputType, std::string>) {
        ImGui::Text(name.c_str(), data->data());
    }
    else if constexpr (std::is_same_v<InputType, Vec2F>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec3F>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec4F>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec2I>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec3I>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec4I>) {
        ImGui::Text(name.c_str(), data->data.data());
    }
    else if constexpr (std::is_same_v<InputType, Vec2B>) {
        ImGui::Text("%s: x: %s, y: %s", name.c_str(), data->x() ? "true" : "false", data->y() ? "true" : "false");
    }
    else if constexpr (std::is_same_v<InputType, Vec3B>) {
        ImGui::Text("%s: x: %s, y: %s, z: %s", name.c_str(), data->x() ? "true" : "false", data->y() ? "true" : "false",
                    data->z() ? "true" : "false");
    }
    else if constexpr (std::is_same_v<InputType, Vec4B>) {
        ImGui::Text("%s: x: %s, y: %s, z: %s, w: %s",
                    name.c_str(), data->x() ? "true" : "false", data->y() ? "true" : "false",
                    data->z() ? "true" : "false", data->w() ? "true" : "false");
    }
    else if constexpr (std::is_same_v<InputType, Mat2F> || std::is_same_v<InputType, Mat3F> ||
        std::is_same_v<InputType, Mat4F>) {
        ImGui::Text("%s: \n", name.c_str());
        ImGui::Text(data->toString().c_str());
    }
}
Referenced by FileLogger::error(), TerminalLogger::error(), GLESC::Logger::error(), GLESC::Logger::executeOnAllInputs(), FileLogger::importantInfo(), TerminalLogger::importantInfo(), GLESC::Logger::importantInfo(), FileLogger::importantInfoBlue(), TerminalLogger::importantInfoBlue(), GLESC::Logger::importantInfoBlue(), FileLogger::importantInfoPurple(), TerminalLogger::importantInfoPurple(), GLESC::Logger::importantInfoPurple(), FileLogger::importantInfoWhite(), TerminalLogger::importantInfoWhite(), GLESC::Logger::importantInfoWhite(), FileLogger::importantSuccess(), TerminalLogger::importantSuccess(), GLESC::Logger::importantSuccess(), FileLogger::info(), TerminalLogger::info(), GLESC::Logger::info(), FileLogger::infoBlue(), TerminalLogger::infoBlue(), GLESC::Logger::infoBlue(), FileLogger::infoPurple(), TerminalLogger::infoPurple(), GLESC::Logger::infoPurple(), input(), FileLogger::log(), TerminalLogger::log(), GLESC::Logger::log(), FileLogger::nonImportantInfo(), TerminalLogger::nonImportantInfo(), GLESC::Logger::nonImportantInfo(), FileLogger::success(), TerminalLogger::success(), GLESC::Logger::success(), FileLogger::warning(), TerminalLogger::warning(), and GLESC::Logger::warning().