GLESC: Debugger.h File Reference
Debugger.h File Reference
A set of macros and functions for debugging and logging.
#include <string>
#include "engine/core/logger/Logger.h"
#include "Stringer.h"
#include <iterator>
#include <sstream>
#include <type_traits>
#include <cstring>
#include <algorithm>
Macros
#define FUNCTION_CALL_STR(FUNCTION_NAME, ...)
Converts the function name and its arguments into a string.
#define LOG(initialMessage, CODE)
#define LOG_BASIC(CODE)
#define postSDLCall
Macro to call after an SDL function to check for errors. It's used instead of SDLCall if the function returns a value.
#define postSDLCall
Macro to call after an SDL function to check for errors. It's used instead of SDLCall if the function returns a value.
#define SDLCall(call) call
Macro to call an SDL function and check for errors.
#define SDLCall(call)
Macro to call an SDL function and check for errors.
Functions
template<typename T >
std::string argsToString (const char *names, T value)
Converts the last argument of a variadic template into a string.
template<typename T , typename... Args>
std::string argsToString (const char *names, T value, Args... args)
Converts each argument of a variadic template into a string.
Detailed Description
A set of macros and functions for debugging and logging.
Author
Valentin Dumitru
Date
2023-09-26
This file contains a set of macros and functions that can be used for debugging and logging purposes. It includes debugging for SDL, LOG, and DEBUG_CODE macros.
Copyright (c) 2023 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file Debugger.h.
Macro Definition Documentation
FUNCTION_CALL_STR
#define FUNCTION_CALL_STR (FUNCTION_NAME, ...)
Value:
        std::string(FUNCTION_NAME) + \
        std::string("(")+                     \
            argsToString(#__VA_ARGS__, __VA_ARGS__)                     \
        +std::string(")")
Converts the function name and its arguments into a string.
This function is used to convert the function name and its arguments into a string format. It is used to log the function name and its arguments when entering a function.
Parameters
FUNCTION_NAME The name of the function.
... The arguments of the function.
Returns
std::string A formatted string representing the function name and its arguments.
Definition at line 136 of file Debugger.h.
LOG
#define LOG (initialMessage, CODE)
Value:
    do{                                      \
    Logger::get().info(initialMessage);      \
        CODE                                 \
    } while(0)
Definition at line 33 of file Debugger.h.
      {                                      \
    Logger::get().info(initialMessage);      \
        CODE                                 \
    } while(0)
LOG_BASIC
#define LOG_BASIC (CODE)
Value:
    do{                                      \
        CODE                                 \
    } while(0)
Definition at line 39 of file Debugger.h.
      {                                      \
        CODE                                 \
    } while(0)
postSDLCall [1/2]
#define postSDLCall
Macro to call after an SDL function to check for errors. It's used instead of SDLCall if the function returns a value.
Definition at line 19 of file Debugger.h.
postSDLCall [2/2]
#define postSDLCall
Value:
    const char* error = SDL_GetError();                              \
    D_ASSERT_TRUE(*error == '\0',                                    \
         "Error post SDL function" + std::string(error));
Macro to call after an SDL function to check for errors. It's used instead of SDLCall if the function returns a value.
Definition at line 19 of file Debugger.h.
SDLCall [1/2]
#define SDLCall (call) call
Macro to call an SDL function and check for errors.
Definition at line 18 of file Debugger.h.
SDLCall [2/2]
#define SDLCall (call)
Value:
    do {                                                              \
        call;                                                         \
        const char* error = SDL_GetError();                           \
        D_ASSERT_TRUE(*error == '\0',                                 \
           "Error when calling SDL function: "                        \
           #call " " + std::string(error));                           \
    } while (0)
Macro to call an SDL function and check for errors.
Definition at line 18 of file Debugger.h.
Function Documentation
argsToString() [1/2]
template<typename T > std::string argsToString (const char * names, T value)
Converts the last argument of a variadic template into a string.
This is the base case for the variadic template recursion. It processes the final argument, extracting its name and converting its value to a string.
Template Parameters
T The type of the argument.
Parameters
names A comma-separated list of argument names as a C-string.
value The value of the argument to be converted to string.
Returns
std::string A formatted string representing the argument's name and value.
Definition at line 79 of file Debugger.h.
{
    std::ostringstream arg;
    const char* nameEnd = std::strchr(names, ',');
    std::string name(names, nameEnd ? nameEnd - names : std::strlen(names));
    arg << name << ": " << GLESC::Stringer::toString(value);
    std::string result = arg.str();
    // Replace '\n' with a space (or any other character/string)
    std::replace(result.begin(), result.end(), '\n', ' ');
    return result;
}
References GLESC::Stringer::toString().
Referenced by argsToString().
argsToString() [2/2]
template<typename T , typename... Args> std::string argsToString (const char * names, T value, Args... args)
Converts each argument of a variadic template into a string.
This function processes each argument of a variadic template, converting them into a string format. It is recursively called for each argument until only one is left, at which point the base case function is invoked.
Template Parameters
T The type of the first argument.
Args The types of the remaining arguments.
Parameters
names A comma-separated list of argument names as a C-string.
value The value of the first argument.
args The remaining arguments.
Returns
std::string A formatted string representing all arguments' names and values.
Definition at line 108 of file Debugger.h.
{
    std::ostringstream arg;
    const char* nameEnd = std::strchr(names, ',');
    std::string name(names, nameEnd ? nameEnd - names : std::strlen(names));
    arg << name << ": " << GLESC::Stringer::toString(value);
    // Proceed to the next argument, if any
    if (nameEnd && *nameEnd == ',') {
        nameEnd++; // Skip the comma
        while (*nameEnd == ' ')
            nameEnd++; // Skip any whitespace after the comma
        // Recursively process the remaining arguments
        return arg.str() + ", " + argsToString(nameEnd, args...);
    }
    return arg.str();
}
References argsToString(), and GLESC::Stringer::toString().