GLESC: MatrixTestsHelper.h File Reference
MatrixTestsHelper.h File Reference
#include <gtest/gtest.h>
#include "engine/core/math/algebra/matrix/Matrix.h"
Classes
struct MatrixType< T, N, M >
Macros
#define PREPARE_TEST()
Typedefs
using MyTypes = ::testing::Types< MatrixType< float, 2, 2 >, MatrixType< double, 2, 2 >, MatrixType< long double, 2, 2 >, MatrixType< float, 3, 3 >, MatrixType< double, 3, 3 >, MatrixType< long double, 3, 3 >, MatrixType< float, 4, 4 >, MatrixType< double, 4, 4 >, MatrixType< long double, 4, 4 >, MatrixType< float, 2, 3 >, MatrixType< double, 2, 3 >, MatrixType< float, 3, 2 >, MatrixType< double, 3, 2 >, MatrixType< float, 4, 3 >, MatrixType< double, 4, 3 > >
Functions
template<class MyType >
MyType generateNextValue (size_t i, size_t j)
Generate next value for the matrix.
template<class MyType , size_t N, size_t M>
void initializeMatrixWithDifferentValues (GLESC::Math::Matrix< MyType, N, M > &matrix)
template<class MyType , size_t N, size_t M>
void initializeMatrixWithDifferentValues (GLESC::Math::MatrixData< MyType, N, M > &matrix)
template<class MyType , size_t N, size_t M>
void initializeMatrixWithValues (GLESC::Math::Matrix< MyType, N, M > &matrix)
template<class MyType , size_t N, size_t M>
void initializeMatrixWithValues (GLESC::Math::MatrixData< MyType, N, M > &matrix)
Macro Definition Documentation
PREPARE_TEST
#define PREPARE_TEST ()
Value:
    using Type = typename TypeParam::ValueType; \
    constexpr size_t N = TypeParam::Rows; \
    constexpr size_t M = TypeParam::Cols; \
    using Mat = GLESC::Math::Matrix<Type, N, M>;
Definition at line 89 of file MatrixTestsHelper.h.
Typedef Documentation
MyTypes
using MyTypes = ::testing::Types< MatrixType<float, 2, 2>, MatrixType<double, 2, 2>, MatrixType<long double, 2, 2>, MatrixType<float, 3, 3>, MatrixType<double, 3, 3>, MatrixType<long double, 3, 3>, MatrixType<float, 4, 4>, MatrixType<double, 4, 4>, MatrixType<long double, 4, 4>, MatrixType<float, 2, 3>, MatrixType<double, 2, 3>, MatrixType<float, 3, 2>, MatrixType<double, 3, 2>, MatrixType<float, 4, 3>, MatrixType<double, 4, 3> >
Definition at line 25 of file MatrixTestsHelper.h.
Function Documentation
generateNextValue()
template<class MyType > MyType generateNextValue (size_t i, size_t j)
Generate next value for the matrix.
It will generate numbers for the matrices for the tests. It ensures that the matrix is either upper or lower triangular with non-zero diagonal elements, thus guaranteeing a non-zero determinant.
Template Parameters
MyType
Parameters
i
j
Returns
The next value for the matrix given the row and column
Definition at line 55 of file MatrixTestsHelper.h.
{
    if (i == j)
        return static_cast<MyType>(i + 1);
    if (i < j)
        return static_cast<MyType>(j + 1);
    return static_cast<MyType>(i + 1);
}
initializeMatrixWithDifferentValues() [1/2]
template<class MyType , size_t N, size_t M> void initializeMatrixWithDifferentValues (GLESC::Math::Matrix< MyType, N, M > & matrix)
Definition at line 84 of file MatrixTestsHelper.h.
{
    initializeMatrixWithDifferentValues(matrix.data);
}
References GLESC::Math::Matrix< Type, N, M >::data, and initializeMatrixWithDifferentValues().
initializeMatrixWithDifferentValues() [2/2]
template<class MyType , size_t N, size_t M> void initializeMatrixWithDifferentValues (GLESC::Math::MatrixData< MyType, N, M > & matrix)
Definition at line 77 of file MatrixTestsHelper.h.
{
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < M; ++j)
            matrix[i][j] = generateNextValue<MyType>(i + 10, j + 10);
}
Referenced by initializeMatrixWithDifferentValues(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
initializeMatrixWithValues() [1/2]
template<class MyType , size_t N, size_t M> void initializeMatrixWithValues (GLESC::Math::Matrix< MyType, N, M > & matrix)
Definition at line 71 of file MatrixTestsHelper.h.
{
    initializeMatrixWithValues(matrix.data);
}
References GLESC::Math::Matrix< Type, N, M >::data, and initializeMatrixWithValues().
initializeMatrixWithValues() [2/2]
template<class MyType , size_t N, size_t M> void initializeMatrixWithValues (GLESC::Math::MatrixData< MyType, N, M > & matrix)
Definition at line 64 of file MatrixTestsHelper.h.
{
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < M; ++j)
            matrix[i][j] = generateNextValue<MyType>(i, j);
}
Referenced by initializeMatrixWithValues(), TEST(), TEST(), textMatrixWithGlm(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().