GLESC: MatrixTests.cpp File Reference
MatrixTests.cpp File Reference
#include "TestsConfig.h"
#include <glm/glm.hpp>
#include <gtest/gtest.h>
#include "engine/core/math/algebra/matrix/MatrixAlgorithms.h"
#include "unit/engine/core/math/MathCustomTestingFramework.h"
#include "unit/engine/core/math/algebra/matrix/MatrixTestsHelper.h"
Functions
TEST (MatrixTests, MulOperatorGLMComparison)
template<class Type , size_t N, size_t M, size_t X>
void textMatrixWithGlm ()
TYPED_TEST (MatrixTests, AddAssignment)
TYPED_TEST (MatrixTests, AddOperator)
TYPED_TEST (MatrixTests, AddScalarAssignment)
TYPED_TEST (MatrixTests, AddScalarOperator)
TYPED_TEST (MatrixTests, ArrayConstructors)
TYPED_TEST (MatrixTests, BracketAccessor)
TYPED_TEST (MatrixTests, CopyAssignment)
TYPED_TEST (MatrixTests, CopyConstructors)
TYPED_TEST (MatrixTests, DefaultConstructors)
TYPED_TEST (MatrixTests, Determinan)
TYPED_TEST (MatrixTests, DiagonalConstructors)
TYPED_TEST (MatrixTests, DivAssignment)
TYPED_TEST (MatrixTests, DivOperator)
TYPED_TEST (MatrixTests, DivScalarAssignment)
TYPED_TEST (MatrixTests, EqualityOperators)
TYPED_TEST (MatrixTests, GetAccessor)
TYPED_TEST (MatrixTests, InequalityOperators)
TYPED_TEST (MatrixTests, Inverse)
TYPED_TEST (MatrixTests, MoveAssignment)
TYPED_TEST (MatrixTests, MoveConstructors)
TYPED_TEST (MatrixTests, MulOperator)
TYPED_TEST (MatrixTests, MulScalarOperator)
TYPED_TEST (MatrixTests, MultAssignment)
TYPED_TEST (MatrixTests, MultScalarAssignment)
TYPED_TEST (MatrixTests, RowsAndColsAccessors)
TYPED_TEST (MatrixTests, SubAssignment)
TYPED_TEST (MatrixTests, SubOperator)
TYPED_TEST (MatrixTests, SubScalarAssignment)
TYPED_TEST (MatrixTests, SubScalarOperator)
TYPED_TEST (MatrixTests, Transpose)
TYPED_TEST (MatrixTests, UnaryMinusOperator)
TYPED_TEST_SUITE (MatrixTests, MyTypes)
Detailed Description
Author
Valentin Dumitru
Date
2023-10-26
Todo:
Add description of this file if needed
Copyright (c) 2023 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file MatrixTests.cpp.
Function Documentation
TEST()
TEST (MatrixTests , MulOperatorGLMComparison)
Definition at line 512 of file MatrixTests.cpp.
{
    // ----------------------------------------- Multiplication ------------------------------------------
    // Multiplication operator (dot product)
    // Only square matrices can be multiplied
    // And only dimensions 2, 3 and 4 are supported due to the implementation of the inverse
    constexpr size_t N = 4;
    constexpr size_t M = 4;
    constexpr size_t X = 4;
    using Type = float;
    textMatrixWithGlm<Type, N, M, X>();
    constexpr size_t N2 = 3;
    constexpr size_t M2 = 4;
    textMatrixWithGlm<Type, N2, M2, X>();
    constexpr size_t N3 = 2;
    constexpr size_t M3 = 3;
    textMatrixWithGlm<Type, N3, M3, X>();
}
textMatrixWithGlm()
template<class Type , size_t N, size_t M, size_t X> void textMatrixWithGlm ()
Definition at line 433 of file MatrixTests.cpp.
{
    if constexpr (GLESC::Math::MatrixAlgorithms::columnMajorMatrix) {
        using MyMatLeft = GLESC::Math::Matrix<Type, M, N>;
        using MyMatRight = GLESC::Math::Matrix<Type, X, M>;
        using MyMatResult = GLESC::Math::Matrix<Type, X, N>;
        using GlmMatLeft = glm::mat<M, N, Type>;
        using GlmMatRight = glm::mat<X, M, Type>;
        using GlmMatResult = glm::mat<X, N, Type>;
        MyMatLeft matrixToMultiplyLeft;
        initializeMatrixWithValues(matrixToMultiplyLeft);
        MyMatRight matrixToMultiplyRight;
        initializeMatrixWithValues(matrixToMultiplyRight);
        MyMatResult actualMultResult;
        actualMultResult = matrixToMultiplyLeft * matrixToMultiplyRight;
        GlmMatLeft glmMatrixToMultiplyLeft{};
        for (int i = 0; i < M; ++i)
            for (int j = 0; j < N; ++j)
                glmMatrixToMultiplyLeft[i][j] = matrixToMultiplyLeft[i][j];
        GlmMatRight glmMatrixToMultiplyRight{};
        for (int i = 0; i < X; ++i)
            for (int j = 0; j < M; ++j)
                glmMatrixToMultiplyRight[i][j] = matrixToMultiplyRight[i][j];
        MyMatResult expectedMultResult;
        GlmMatResult glmExpectedMultResult{};
        glmExpectedMultResult = glmMatrixToMultiplyLeft * glmMatrixToMultiplyRight;
        for (int i = 0; i < X; ++i)
            for (int j = 0; j < N; ++j)
                expectedMultResult[i][j] = glmExpectedMultResult[i][j];
        EXPECT_EQ_MAT(actualMultResult, expectedMultResult);
    }
    else {
        using MyMatLeft = GLESC::Math::Matrix<Type, N, M>;
        using MyMatRight = GLESC::Math::Matrix<Type, M, X>;
        using MyMatResult = GLESC::Math::Matrix<Type, N, X>;
        using GlmMatLeft = glm::mat<N, M, Type>;
        using GlmMatRight = glm::mat<M, X, Type>;
        using GlmMatResult = glm::mat<N, X, Type>;
        MyMatLeft matrixToMultiplyLeft;
        initializeMatrixWithValues(matrixToMultiplyLeft);
        MyMatRight matrixToMultiplyRight;
        initializeMatrixWithValues(matrixToMultiplyRight);
        MyMatResult actualMultResult;
        actualMultResult = matrixToMultiplyLeft * matrixToMultiplyRight;
        MyMatResult expectedMultResult;
        GlmMatLeft glmMatrixToMultiplyLeft{};
        for (int i = 0; i < N; ++i)
            for (int j = 0; j < M; ++j)
                glmMatrixToMultiplyLeft[i][j] = matrixToMultiplyLeft[i][j];
        GlmMatRight glmMatrixToMultiplyRight{};
        for (int i = 0; i < M; ++i)
            for (int j = 0; j < X; ++j)
                glmMatrixToMultiplyRight[i][j] = matrixToMultiplyRight[i][j];
        GlmMatResult glmExpectedMultResult{};
        glmExpectedMultResult = glmMatrixToMultiplyLeft * glmMatrixToMultiplyRight;
        for (int i = 0; i < N; ++i)
            for (int j = 0; j < X; ++j)
                expectedMultResult[i][j] = glmExpectedMultResult[i][j];
        EXPECT_EQ_MAT(actualMultResult, expectedMultResult);
    }
}
References GLESC::Math::MatrixAlgorithms::columnMajorMatrix, EXPECT_EQ_MAT, and initializeMatrixWithValues().
TYPED_TEST() [1/31]
TYPED_TEST (MatrixTests , AddAssignment)
Definition at line 162 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator += with matrix
    Mat matrixPlusEquals;
    initializeMatrixWithValues(matrixPlusEquals);
    matrixPlusEquals += this->matrix;
    EXPECT_EQ_MAT(matrixPlusEquals, (this->matrix + this->matrix));
}
References EXPECT_EQ_MAT, initializeMatrixWithValues(), and PREPARE_TEST.
TYPED_TEST() [2/31]
TYPED_TEST (MatrixTests , AddOperator)
Definition at line 260 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    std::cout <<
        "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Testing + operator with matrix%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
    // Addition operator
    Mat matrixAdditionResult = this->matrix + this->matrix;
    Mat expectedAddition = this->matrix; // Initialize it with identical values to this->matrix
    for (size_t i = 0; i < expectedAddition.rows(); ++i)
        for (size_t j = 0; j < expectedAddition.cols(); ++j)
            expectedAddition[i][j] *= 2; // Double each element
    EXPECT_EQ_MAT(matrixAdditionResult, expectedAddition);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [3/31]
TYPED_TEST (MatrixTests , AddScalarAssignment)
Definition at line 171 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator += with scalar
    Mat matrixPlusScalarEquals = this->matrix;
    Type scalar = Type(2);
    matrixPlusScalarEquals += scalar;
    EXPECT_EQ_MAT(matrixPlusScalarEquals, (this->matrix + scalar));
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [4/31]
TYPED_TEST (MatrixTests , AddScalarOperator)
Definition at line 273 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Addition operator with scalar
    Mat matrixAddScalarResult = this->matrix + 2;
    Mat expectedAddScalar = this->matrix; // Initialize it with identical values to this->matrix
    for (size_t i = 0; i < expectedAddScalar.rows(); ++i)
        for (size_t j = 0; j < expectedAddScalar.cols(); ++j)
            expectedAddScalar[i][j] += 2; // Add 2 to each element
    EXPECT_EQ_MAT(matrixAddScalarResult, expectedAddScalar);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [5/31]
TYPED_TEST (MatrixTests , ArrayConstructors)
Definition at line 62 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Array constructor
    Type arrayValues[N][M];
    for (size_t i = 0; i < N; ++i)
        for (size_t j = 0; j < M; ++j)
            arrayValues[i][j] = this->matrix[i][j];
    Mat matrixArray(arrayValues);
    Mat expectedArray = this->matrix;
    GLESC::Math::MatrixAlgorithms::setMatrix(expectedArray.data, arrayValues);
    EXPECT_EQ_MAT(matrixArray, expectedArray);
}
References EXPECT_EQ_MAT, PREPARE_TEST, and GLESC::Math::MatrixAlgorithms::setMatrix().
TYPED_TEST() [6/31]
TYPED_TEST (MatrixTests , BracketAccessor)
Definition at line 100 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    std::cout << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Testing get over []%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
    // Operator [] ----------------------------------
    for (size_t i = 0; i < this->matrix.rows(); ++i)
        for (size_t j = 0; j < this->matrix.cols(); ++j)
            EXPECT_EQ_CUSTOM(this->matrix[i][j], generateNextValue<Type>(i, j));
    S_ASSERT_TRUE((std::is_same_v<decltype(this->matrix[0][0]), Type &>),
                  "Operator [] must return a reference");
}
References EXPECT_EQ_CUSTOM, PREPARE_TEST, and S_ASSERT_TRUE.
TYPED_TEST() [7/31]
TYPED_TEST (MatrixTests , CopyAssignment)
Definition at line 146 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Copy assignment
    Mat matrixCopyAssign;
    matrixCopyAssign = this->matrix;
    EXPECT_EQ_MAT(matrixCopyAssign, this->matrix);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [8/31]
TYPED_TEST (MatrixTests , CopyConstructors)
Definition at line 76 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Copy constructor
    Mat matrixCopy(this->matrix);
    Mat matrixCopyReference;
    EXPECT_EQ_MAT(matrixCopy, this->matrix);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [9/31]
TYPED_TEST (MatrixTests , DefaultConstructors)
Definition at line 41 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Default constructor
    Mat matrixDefault;
    Mat expectedDefault;
    GLESC::Math::MatrixAlgorithms::setMatrixZero(expectedDefault.data);
    EXPECT_EQ_MAT(matrixDefault, expectedDefault);
}
References EXPECT_EQ_MAT, PREPARE_TEST, and GLESC::Math::MatrixAlgorithms::setMatrixZero().
TYPED_TEST() [10/31]
TYPED_TEST (MatrixTests , Determinan)
Definition at line 395 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Determinant
    if constexpr (N == M) {
        Type matrixDeterminantResult = this->matrix.determinant();
        Type expectedDeterminantResult =
            GLESC::Math::MatrixAlgorithms::laplaceExpansionDeterminant(this->matrix.data);
        EXPECT_EQ_CUSTOM(matrixDeterminantResult, expectedDeterminantResult);
    }
}
References EXPECT_EQ_CUSTOM, GLESC::Math::MatrixAlgorithms::laplaceExpansionDeterminant(), and PREPARE_TEST.
TYPED_TEST() [11/31]
TYPED_TEST (MatrixTests , DiagonalConstructors)
Definition at line 50 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == M) {
        // Diagonal constructor
        Type diagonalValue = 100;
        Mat diagonalMat(diagonalValue);
        Mat expectedDiagonal;
        GLESC::Math::MatrixAlgorithms::setMatrixDiagonal(expectedDiagonal.data, diagonalValue);
        EXPECT_EQ_MAT(diagonalMat, expectedDiagonal);
    }
}
References EXPECT_EQ_MAT, PREPARE_TEST, and GLESC::Math::MatrixAlgorithms::setMatrixDiagonal().
TYPED_TEST() [12/31]
TYPED_TEST (MatrixTests , DivAssignment)
Definition at line 226 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator /= with matrix
    // Only square matrices can be divided in place
    // And only dimensions 2, 3 and 4 are supported due to the implementation of the inverse
    if constexpr (N == M && N <= 4) {
        Mat matrixDivEquals = this->matrix2;
        matrixDivEquals /= this->matrix;
        Mat expectedDivEquals = this->matrix2;
        GLESC::Math::MatrixAlgorithms::matrixMatrixDiv(expectedDivEquals.data, this->matrix.data,
                                                       expectedDivEquals.data);
        EXPECT_EQ_MAT(matrixDivEquals, expectedDivEquals);
        // Dividing by zero
        Mat matrixDivZero = this->matrix;
        EXPECT_THROW(matrixDivZero /= Mat(), MathException);
    }
}
References EXPECT_EQ_MAT, GLESC::Math::MatrixAlgorithms::matrixMatrixDiv(), and PREPARE_TEST.
TYPED_TEST() [13/31]
TYPED_TEST (MatrixTests , DivOperator)
Definition at line 366 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // ----------------------------------------- Division ------------------------------------------
    // Division operator
    // Only square matrices can be divided
    // And only dimensions 2, 3 and 4 are supported due to the implementation of the inverse
    if constexpr (N == M && (N == 2 || N == 3 || N == 4)) {
        Mat matrixDivResult = this->matrix2 / this->matrix;
        Mat expectedDivResult = this->matrix2;
        expectedDivResult *= this->matrix.inverse();
        EXPECT_EQ_MAT(matrixDivResult, expectedDivResult);
        // Division operator with scalar
        Mat matrixDivScalarResult = this->matrix / 2;
        Mat expectedDivScalarResult = this->matrix;
        for (size_t i = 0; i < expectedDivScalarResult.rows(); ++i)
            for (size_t j = 0; j < expectedDivScalarResult.cols(); ++j)
                expectedDivScalarResult[i][j] /= 2; // Divide each element by 2
        EXPECT_EQ_MAT(matrixDivScalarResult, expectedDivScalarResult);
        // Division by zero
        Mat matrixDivZero;
        initializeMatrixWithValues(matrixDivZero);
        Mat zeroMatrix;
        EXPECT_THROW(matrixDivZero / zeroMatrix, MathException);
        EXPECT_THROW(matrixDivZero / Type(0), MathException);
    }
}
References EXPECT_EQ_MAT, initializeMatrixWithValues(), and PREPARE_TEST.
TYPED_TEST() [14/31]
TYPED_TEST (MatrixTests , DivScalarAssignment)
Definition at line 246 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator /= with scalar
    Mat matrixDivScalarEquals;
    initializeMatrixWithValues(matrixDivScalarEquals);
    Type scalarDiv = Type(2);
    matrixDivScalarEquals /= scalarDiv;
    EXPECT_EQ_MAT(matrixDivScalarEquals, (this->matrix / scalarDiv));
    // Dividing by zero
    Mat matrixDivZero = this->matrix;
    EXPECT_THROW(matrixDivZero /= Type(0), MathException);
}
References EXPECT_EQ_MAT, initializeMatrixWithValues(), and PREPARE_TEST.
TYPED_TEST() [15/31]
TYPED_TEST (MatrixTests , EqualityOperators)
Definition at line 129 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Equality operator
    Mat matrixEquals;
    initializeMatrixWithValues(matrixEquals);
    EXPECT_EQ(this->matrix, matrixEquals);
}
References initializeMatrixWithValues(), and PREPARE_TEST.
TYPED_TEST() [16/31]
TYPED_TEST (MatrixTests , GetAccessor)
Definition at line 113 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    std::cout << "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Testing const getters%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n";
    // Const Getters ----------------------------------
    for (size_t i = 0; i < this->matrix.rows(); ++i)
        for (size_t j = 0; j < this->matrix.cols(); ++j)
            EXPECT_EQ_CUSTOM(this->matrix.get(i, j), generateNextValue<Type>(i, j));
    // Getters must return a const reference
    S_ASSERT_TRUE((std::is_same_v<decltype(this->matrix.get(0, 0)), const Type &>),
                  "Getters (index1, index2) must return a const reference to the matrix element");
    S_ASSERT_TRUE((std::is_same_v<decltype(this->matrix.get(0)), const GLESC::Math::MatrixRow<Type, M> &>),
                  "Getter (index) must return a const reference to the matrix row");
}
References EXPECT_EQ_CUSTOM, PREPARE_TEST, and S_ASSERT_TRUE.
TYPED_TEST() [17/31]
TYPED_TEST (MatrixTests , InequalityOperators)
Definition at line 137 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Inequality operator
    Mat matrixNotEquals;
    initializeMatrixWithValues(matrixNotEquals);
    matrixNotEquals[0][0] += Type(1);
    EXPECT_NE(this->matrix, matrixNotEquals);
}
References initializeMatrixWithValues(), and PREPARE_TEST.
TYPED_TEST() [18/31]
TYPED_TEST (MatrixTests , Inverse)
Definition at line 417 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Inverse
    // Only square matrices can be inverted
    // And only dimensions 2, 3 and 4 are supported due to the implementation of the inverse
    if constexpr (N == M && N <= 4) {
        Mat matrixInverseResult = this->matrix.inverse();
        GLESC::Math::MatrixData<Type, N, M> expectedInverseResult{};
        GLESC::Math::MatrixAlgorithms::matrixInverse(this->matrix.data, expectedInverseResult);
        EXPECT_EQ_MAT(matrixInverseResult.data, expectedInverseResult);
    }
}
References EXPECT_EQ_MAT, GLESC::Math::MatrixAlgorithms::matrixInverse(), and PREPARE_TEST.
TYPED_TEST() [19/31]
TYPED_TEST (MatrixTests , MoveAssignment)
Definition at line 154 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Move assignment
    Mat matrixMoveAssign;
    matrixMoveAssign = std::move(this->matrix);
    EXPECT_EQ_MAT(matrixMoveAssign, this->matrix);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [20/31]
TYPED_TEST (MatrixTests , MoveConstructors)
Definition at line 84 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Move constructor
    Mat matrixMove(std::move(this->matrix));
    EXPECT_EQ_MAT(matrixMove, this->matrix);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [21/31]
TYPED_TEST (MatrixTests , MulOperator)
Definition at line 317 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Multiplication operator (dot product)
    constexpr auto X = 4;
    if constexpr (GLESC::Math::MatrixAlgorithms::columnMajorMatrix) {
        GLESC::Math::Matrix<Type, M, N> matrixToMultiplyLeft;
        initializeMatrixWithValues(matrixToMultiplyLeft);
        GLESC::Math::Matrix<Type, X, M> matrixToMultiplyRight;
        initializeMatrixWithValues(matrixToMultiplyRight);
        GLESC::Math::Matrix<Type, X, N> expectedMultResult;
        GLESC::Math::Matrix<Type, X, N> actualMultResult;
        actualMultResult = matrixToMultiplyLeft * matrixToMultiplyRight;
        GLESC::Math::MatrixAlgorithms::matrixMatrixMulColMaj(matrixToMultiplyLeft.data, matrixToMultiplyRight.data,
                                                             expectedMultResult.data);
        EXPECT_EQ_MAT(actualMultResult, expectedMultResult);
    }
    else {
        GLESC::Math::Matrix<Type, N, M> matrixToMultiplyLeft;
        initializeMatrixWithValues(matrixToMultiplyLeft);
        GLESC::Math::Matrix<Type, M, X> matrixToMultiplyRight;
        initializeMatrixWithValues(matrixToMultiplyRight);
        GLESC::Math::Matrix<Type, N, X> expectedMultResult;
        GLESC::Math::Matrix<Type, N, X> actualMultResult;
        actualMultResult = matrixToMultiplyLeft * matrixToMultiplyRight;
        GLESC::Math::MatrixAlgorithms::matrixMatrixMulRowMaj(matrixToMultiplyLeft, matrixToMultiplyRight.data,
                                                             expectedMultResult.data);
        EXPECT_EQ_MAT(actualMultResult, expectedMultResult);
    }
}
References GLESC::Math::MatrixAlgorithms::columnMajorMatrix, GLESC::Math::Matrix< Type, N, M >::data, EXPECT_EQ_MAT, initializeMatrixWithValues(), GLESC::Math::MatrixAlgorithms::matrixMatrixMulColMaj(), GLESC::Math::MatrixAlgorithms::matrixMatrixMulRowMaj(), and PREPARE_TEST.
TYPED_TEST() [22/31]
TYPED_TEST (MatrixTests , MulScalarOperator)
Definition at line 356 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Multiplication operator with scalar
    Type scalar = Type(2);
    Mat matrixMultScalarResult = this->matrix * scalar;
    Mat expectedMultScalar = this->matrix;
    GLESC::Math::MatrixAlgorithms::matrixScalarMul(this->matrix.data, scalar, expectedMultScalar.data);
    EXPECT_EQ_MAT(matrixMultScalarResult, expectedMultScalar);
}
References EXPECT_EQ_MAT, GLESC::Math::MatrixAlgorithms::matrixScalarMul(), and PREPARE_TEST.
TYPED_TEST() [23/31]
TYPED_TEST (MatrixTests , MultAssignment)
Definition at line 201 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == M) {
        Mat matrixToMultiplyWith = this->matrix;
        // Operator *= with matrix
        Mat matrixMultAssign = this->matrix;
        matrixMultAssign *= matrixToMultiplyWith;
        //
        auto expectedMultAssign = this->matrix;
        GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(expectedMultAssign.data, matrixToMultiplyWith.data,
                                                              expectedMultAssign.data);
        EXPECT_EQ_MAT(matrixMultAssign, expectedMultAssign);
    }
}
References EXPECT_EQ_MAT, GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(), and PREPARE_TEST.
TYPED_TEST() [24/31]
TYPED_TEST (MatrixTests , MultScalarAssignment)
Definition at line 217 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator *= with scalar
    Mat matrixMultScalarEquals = this->matrix;
    Type scalarMult = Type(2);
    matrixMultScalarEquals *= scalarMult;
    EXPECT_EQ_MAT(matrixMultScalarEquals, (this->matrix * scalarMult));
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [25/31]
TYPED_TEST (MatrixTests , RowsAndColsAccessors)
Definition at line 91 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Get rows
    EXPECT_EQ_CUSTOM(this->matrix.rows(), N);
    // Get cols
    EXPECT_EQ_CUSTOM(this->matrix.cols(), M);
}
References EXPECT_EQ_CUSTOM, and PREPARE_TEST.
TYPED_TEST() [26/31]
TYPED_TEST (MatrixTests , SubAssignment)
Definition at line 180 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator -= with matrix
    Mat matrixMinusEquals = this->matrix;
    matrixMinusEquals -= this->matrix;
    EXPECT_EQ_MAT(matrixMinusEquals, (this->matrix - this->matrix));
    Mat matrixMinusEquals2 = this->matrix2;
    matrixMinusEquals2 -= this->matrix;
    EXPECT_EQ_MAT(matrixMinusEquals2, (this->matrix2 - this->matrix));
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [27/31]
TYPED_TEST (MatrixTests , SubOperator)
Definition at line 284 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Subtraction operator
    Mat matrixSubstrResult = this->matrix - this->matrix;
    Mat expectedSubstr = this->matrix; // Initialize it with zero values
    for (size_t i = 0; i < expectedSubstr.rows(); ++i)
        for (size_t j = 0; j < expectedSubstr.cols(); ++j)
            expectedSubstr[i][j] = 0; // All elements should be zero
    EXPECT_EQ_MAT(matrixSubstrResult, expectedSubstr);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [28/31]
TYPED_TEST (MatrixTests , SubScalarAssignment)
Definition at line 192 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Operator -= with scalar
    Mat matrixMinusScalarEquals = this->matrix;
    Type scalarMinus = Type(2);
    matrixMinusScalarEquals -= scalarMinus;
    EXPECT_EQ_MAT(matrixMinusScalarEquals, (this->matrix - scalarMinus));
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [29/31]
TYPED_TEST (MatrixTests , SubScalarOperator)
Definition at line 295 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Subtraction operator with scalar
    Mat matrixSubtrScalarResult = this->matrix - 2;
    Mat expectedSubtrScalar = this->matrix;
    for (size_t i = 0; i < expectedSubtrScalar.rows(); ++i)
        for (size_t j = 0; j < expectedSubtrScalar.cols(); ++j)
            expectedSubtrScalar[i][j] -= 2; // Subtract 2 from each element
    EXPECT_EQ_MAT(matrixSubtrScalarResult, expectedSubtrScalar);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST() [30/31]
TYPED_TEST (MatrixTests , Transpose)
Definition at line 406 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Transpose
    GLESC::Math::Matrix<Type, M, N> matrixTransposeResult = this->matrix.transpose();
    GLESC::Math::Matrix<Type, M, N> expectedTransposeResult;
    for (size_t i = 0; i < this->matrix.rows(); ++i)
        for (size_t j = 0; j < this->matrix.cols(); ++j)
            expectedTransposeResult[j][i] = this->matrix[i][j];
    EXPECT_EQ_MAT(matrixTransposeResult, expectedTransposeResult);
}
References EXPECT_EQ_MAT, PREPARE_TEST, and GLESC::Math::Matrix< Type, N, M >::transpose().
TYPED_TEST() [31/31]
TYPED_TEST (MatrixTests , UnaryMinusOperator)
Definition at line 306 of file MatrixTests.cpp.
{
    PREPARE_TEST();
    // Unary minus operator
    Mat matrixUnaryMinusResult = -this->matrix;
    Mat expectedUnaryMinus = this->matrix;
    for (size_t i = 0; i < expectedUnaryMinus.rows(); ++i)
        for (size_t j = 0; j < expectedUnaryMinus.cols(); ++j)
            expectedUnaryMinus[i][j] = -expectedUnaryMinus[i][j]; // Negate each element
    EXPECT_EQ_MAT(matrixUnaryMinusResult, expectedUnaryMinus);
}
References EXPECT_EQ_MAT, and PREPARE_TEST.
TYPED_TEST_SUITE()
TYPED_TEST_SUITE (MatrixTests , MyTypes)