GLESC: MathCustomTestingFramework.h File Reference
MathCustomTestingFramework.h File Reference
#include <iostream>
#include "unit/CustomTestingFramework.h"
#include "engine/core/math/algebra/matrix/Matrix.h"
Macros
#define EXPECT_EQ_MAT(a, b) expectEqMat(a, b)
#define EXPECT_EQ_MAT_EPSILON(a, b, epsilon) expectEqMatEpsilon(a, b, epsilon)
#define EXPECT_EQ_VEC(a, b) expectEqVec(a, b)
#define EXPECT_NE_MAT(a, b) expectNeMat(a, b)
Functions
template<typename T , size_t N, size_t M>
void expectEqMat (const GLESC::Math::Matrix< T, N, M > &a, const GLESC::Math::Matrix< T, N, M > &b)
template<typename T , size_t N, size_t M>
void expectEqMat (const GLESC::Math::MatrixData< T, N, M > &a, const GLESC::Math::MatrixData< T, N, M > &b)
template<typename T , size_t N, size_t M>
void expectEqMatEpsilon (const GLESC::Math::MatrixData< T, N, M > &a, const GLESC::Math::MatrixData< T, N, M > &b, const T &epsilon)
template<typename T , size_t N>
void expectEqVec (const GLESC::Math::Vector< T, N > &a, const GLESC::Math::Vector< T, N > &b)
template<typename T , size_t N>
void expectEqVec (const GLESC::Math::VectorData< T, N > &a, const GLESC::Math::VectorData< T, N > &b)
template<typename T , size_t N, size_t M>
void expectNeMat (const GLESC::Math::Matrix< T, N, M > &a, const GLESC::Math::Matrix< T, N, M > &b)
template<typename T , size_t N, size_t M>
void expectNeMat (const GLESC::Math::MatrixData< T, N, M > &a, const GLESC::Math::MatrixData< T, N, M > &b)
template<typename ValueType , std::size_t N, std::size_t M>
void generateMatrixWithRandomNumbers (GLESC::Math::Matrix< ValueType, N, M > &matrix)
template<typename ValueType , std::size_t N, std::size_t M>
void generateMatrixWithRandomNumbers (GLESC::Math::MatrixData< ValueType, N, M > &matrix)
void postMatCheckPrint ()
template<typename T , size_t N, size_t M>
void preMatCheckPrint (const GLESC::Math::MatrixData< T, N, M > &a, const GLESC::Math::MatrixData< T, N, M > &b)
Detailed Description
Author
Valentin Dumitru
Date
2023-10-26
Todo:
Add description of this file if needed
Copyright (c) 2023 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file MathCustomTestingFramework.h.
Macro Definition Documentation
EXPECT_EQ_MAT
#define EXPECT_EQ_MAT (a, b) expectEqMat(a, b)
Definition at line 121 of file MathCustomTestingFramework.h.
EXPECT_EQ_MAT_EPSILON
#define EXPECT_EQ_MAT_EPSILON (a, b, epsilon) expectEqMatEpsilon(a, b, epsilon)
Definition at line 124 of file MathCustomTestingFramework.h.
EXPECT_EQ_VEC
#define EXPECT_EQ_VEC (a, b) expectEqVec(a, b)
Definition at line 132 of file MathCustomTestingFramework.h.
EXPECT_NE_MAT
#define EXPECT_NE_MAT (a, b) expectNeMat(a, b)
Definition at line 128 of file MathCustomTestingFramework.h.
Function Documentation
expectEqMat() [1/2]
template<typename T , size_t N, size_t M> void expectEqMat (const GLESC::Math::Matrix< T, N, M > & a, const GLESC::Math::Matrix< T, N, M > & b)
Definition at line 89 of file MathCustomTestingFramework.h.
{
    expectEqMat(a.data, b.data);
}
References GLESC::Math::Matrix< Type, N, M >::data, and expectEqMat().
expectEqMat() [2/2]
template<typename T , size_t N, size_t M> void expectEqMat (const GLESC::Math::MatrixData< T, N, M > & a, const GLESC::Math::MatrixData< T, N, M > & b)
Definition at line 47 of file MathCustomTestingFramework.h.
{
    S_ASSERT_TRUE(N > 0 && M > 0, "Matrix dimensions must be positive");
    preMatCheckPrint(a, b);
    for (size_t i = 0; i < N; ++i) {
        for (size_t j = 0; j < M; ++j) {
            std::cout << "Comparing element [" << i << "][" << j << "]\n";
            expectEqCustom(a[i][j], b[i][j]);
        }
    }
    postMatCheckPrint();
}
References expectEqCustom(), postMatCheckPrint(), preMatCheckPrint(), and S_ASSERT_TRUE.
Referenced by expectEqMat().
expectEqMatEpsilon()
template<typename T , size_t N, size_t M> void expectEqMatEpsilon (const GLESC::Math::MatrixData< T, N, M > & a, const GLESC::Math::MatrixData< T, N, M > & b, const T & epsilon)
Definition at line 60 of file MathCustomTestingFramework.h.
{
    S_ASSERT_TRUE(N > 0 && M > 0, "Matrix dimensions must be positive");
    preMatCheckPrint(a, b);
    for (size_t i = 0; i < N; ++i) {
        for (size_t j = 0; j < M; ++j) {
            std::cout << "Comparing element [" << i << "][" << j << "]\n";
            expectEqCustomEpsilon(a[i][j], b[i][j], epsilon);
        }
    }
    postMatCheckPrint();
}
References expectEqCustomEpsilon(), postMatCheckPrint(), preMatCheckPrint(), and S_ASSERT_TRUE.
expectEqVec() [1/2]
template<typename T , size_t N> void expectEqVec (const GLESC::Math::Vector< T, N > & a, const GLESC::Math::Vector< T, N > & b)
Definition at line 115 of file MathCustomTestingFramework.h.
{
    expectEqVec(a.data, b.data);
}
References GLESC::Math::Vector< Type, N >::data, and expectEqVec().
expectEqVec() [2/2]
template<typename T , size_t N> void expectEqVec (const GLESC::Math::VectorData< T, N > & a, const GLESC::Math::VectorData< T, N > & b)
Definition at line 101 of file MathCustomTestingFramework.h.
{
    std::cout << "Comparing vectors:\n";
    // Assuming 'toString' is part of the vector infrastructure
    std::cout << "Left vector: " << GLESC::Stringer::toString(a) << "\n";
    std::cout << "Right vector: " << GLESC::Stringer::toString(b) << "\n";
    std::cout << "------------------ Vector Values comparison: -------------------\n";
    for (size_t i = 0; i < N; ++i) {
        std::cout << "Comparing element [" << i << "]\n";
        expectEqCustom(a[i], b[i]);
    }
    std::cout << "----------------------------------------------------------------\n";
}
References expectEqCustom(), and GLESC::Stringer::toString().
Referenced by expectEqVec().
expectNeMat() [1/2]
template<typename T , size_t N, size_t M> void expectNeMat (const GLESC::Math::Matrix< T, N, M > & a, const GLESC::Math::Matrix< T, N, M > & b)
Definition at line 94 of file MathCustomTestingFramework.h.
{
    expectNeMat(a.data, b.data);
}
References GLESC::Math::Matrix< Type, N, M >::data, and expectNeMat().
expectNeMat() [2/2]
template<typename T , size_t N, size_t M> void expectNeMat (const GLESC::Math::MatrixData< T, N, M > & a, const GLESC::Math::MatrixData< T, N, M > & b)
Definition at line 74 of file MathCustomTestingFramework.h.
{
    S_ASSERT_TRUE(N > 0 && M > 0, "Matrix dimensions must be positive");
    preMatCheckPrint(a, b);
    bool areEqual = true;
    for (size_t i = 0; i < N && areEqual; ++i) {
        for (size_t j = 0; j < M && areEqual; ++j) {
            std::cout << "Comparing element [" << i << "][" << j << "]\n";
            areEqual = GLESC::Math::eq(a[i][j], b[i][j]);
        }
    }
    postMatCheckPrint();
    EXPECT_FALSE(areEqual);
}
References GLESC::Math::eq(), postMatCheckPrint(), preMatCheckPrint(), and S_ASSERT_TRUE.
Referenced by expectNeMat().
generateMatrixWithRandomNumbers() [1/2]
template<typename ValueType , std::size_t N, std::size_t M> void generateMatrixWithRandomNumbers (GLESC::Math::Matrix< ValueType, N, M > & matrix)
Definition at line 26 of file MathCustomTestingFramework.h.
{
    generateMatrixWithRandomNumbers(matrix.data);
}
References GLESC::Math::Matrix< Type, N, M >::data, and generateMatrixWithRandomNumbers().
generateMatrixWithRandomNumbers() [2/2]
template<typename ValueType , std::size_t N, std::size_t M> void generateMatrixWithRandomNumbers (GLESC::Math::MatrixData< ValueType, N, M > & matrix)
Definition at line 17 of file MathCustomTestingFramework.h.
{
    for (auto& row : matrix) {
        for (auto& element : row) {
            element = GLESC::Math::generateRandomNumber<ValueType>(-1000, 1000);
        }
    }
}
Referenced by generateMatrixWithRandomNumbers(), and TYPED_TEST().
postMatCheckPrint()
void postMatCheckPrint () inline
Definition at line 40 of file MathCustomTestingFramework.h.
{
    std::cout << "----------------------------------------------------------------\n";
}
Referenced by expectEqMat(), expectEqMatEpsilon(), and expectNeMat().
preMatCheckPrint()
template<typename T , size_t N, size_t M> void preMatCheckPrint (const GLESC::Math::MatrixData< T, N, M > & a, const GLESC::Math::MatrixData< T, N, M > & b)
Definition at line 32 of file MathCustomTestingFramework.h.
{
    std::cout << "Comparing matrices:\n";
    // Assuming 'toString' is part of the matrix infrastructure
    std::cout << "Left matrix: \n" << GLESC::Stringer::toString(a) << "\n";
    std::cout << "Right matrix: \n" << GLESC::Stringer::toString(b) << "\n";
    std::cout << "------------------ Matrix Values comparison: -------------------\n";
}
References GLESC::Stringer::toString().
Referenced by expectEqMat(), expectEqMatEpsilon(), and expectNeMat().