GLESC: VectorTestsHelper.h File Reference
VectorTestsHelper.h File Reference
#include <gtest/gtest.h>
#include "engine/core/math/algebra/vector/Vector.h"
Classes
struct VectorType< Type, N >
Macros
#define PREPARE_TEST()
Typedefs
using VectorTypes = ::testing::Types< VectorType< float, 2 >, VectorType< double, 2 >, VectorType< long double, 2 >, VectorType< float, 3 >, VectorType< double, 3 >, VectorType< long double, 3 >, VectorType< float, 4 >, VectorType< double, 4 >, VectorType< long double, 4 >, VectorType< float, 5 >, VectorType< double, 5 >, VectorType< long double, 5 >, VectorType< float, 10 >, VectorType< double, 10 >, VectorType< long double, 10 > >
Functions
template<typename Type >
static Type generateNextValue1 (size_t i)
Generate next value for the vector: 1, 2, 3, 4, 5, ...
template<typename Type >
static Type generateNextValue2 (size_t i)
Generate next value for the vector: 11, 22, 33, 44, 55, ...
template<typename Type , size_t N>
void initVector1 (GLESC::Math::VectorData< Type, N > &v)
template<typename Type , size_t N>
void initVector1 (VectorT< Type, N > &v)
template<typename Type , size_t N>
void initVector2 (GLESC::Math::VectorData< Type, N > &v)
template<typename Type , size_t N>
void initVector2 (VectorT< Type, N > &v)
Macro Definition Documentation
PREPARE_TEST
#define PREPARE_TEST ()
Value:
    using Type = typename TypeParam::ValueType; \
    constexpr size_t N = TypeParam::Size; \
    using Vec = VectorT<Type, N>; \
    using VecData = GLESC::Math::VectorData<Type, N>;
Definition at line 93 of file VectorTestsHelper.h.
Typedef Documentation
VectorTypes
using VectorTypes = ::testing::Types< VectorType<float, 2>, VectorType<double, 2>, VectorType<long double, 2>, VectorType<float, 3>, VectorType<double, 3>, VectorType<long double, 3>, VectorType<float, 4>, VectorType<double, 4>, VectorType<long double, 4>, VectorType<float, 5>, VectorType<double, 5>, VectorType<long double, 5>, VectorType<float, 10>, VectorType<double, 10>, VectorType<long double, 10> >
Definition at line 23 of file VectorTestsHelper.h.
Function Documentation
generateNextValue1()
template<typename Type > static Type generateNextValue1 (size_t i) static
Generate next value for the vector: 1, 2, 3, 4, 5, ...
It will generate numbers for the vectors for the tests.
Template Parameters
Type
Parameters
i
Returns
The next value for the vector given the index
Definition at line 50 of file VectorTestsHelper.h.
{
    return Type(i + 1);
}
generateNextValue2()
template<typename Type > static Type generateNextValue2 (size_t i) static
Generate next value for the vector: 11, 22, 33, 44, 55, ...
It will generate numbers for the vectors for the tests.
Template Parameters
Type
Parameters
i
Returns
The next value for the vector given the index
Definition at line 63 of file VectorTestsHelper.h.
{
    return Type(i + 1) * Type(10) + Type(i + 1);
}
initVector1() [1/2]
template<typename Type , size_t N> void initVector1 (GLESC::Math::VectorData< Type, N > & v)
Definition at line 68 of file VectorTestsHelper.h.
{
    for (size_t i = 0; i < N; ++i)
        v[i] = generateNextValue1<Type>(i);
}
Referenced by initVector1(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
initVector1() [2/2]
template<typename Type , size_t N> void initVector1 (VectorT< Type, N > & v)
Definition at line 80 of file VectorTestsHelper.h.
{
    initVector1(v.data);
}
References GLESC::Math::Vector< Type, N >::data, and initVector1().
initVector2() [1/2]
template<typename Type , size_t N> void initVector2 (GLESC::Math::VectorData< Type, N > & v)
Definition at line 74 of file VectorTestsHelper.h.
{
    for (size_t i = 0; i < N; ++i)
        v[i] = generateNextValue2<Type>(i);
}
Referenced by initVector2(), TYPED_TEST(), and TYPED_TEST().
initVector2() [2/2]
template<typename Type , size_t N> void initVector2 (VectorT< Type, N > & v)
Definition at line 85 of file VectorTestsHelper.h.
{
    initVector2(v.data);
}
References GLESC::Math::Vector< Type, N >::data, and initVector2().