GLESC: VectorAlgorithmsTests.cpp File Reference
VectorAlgorithmsTests.cpp File Reference
@TODO Add description of this file if needed
#include "TestsConfig.h"
#include <gtest/gtest.h>
#include "engine/core/math/algebra/vector/VectorAlgorithms.h"
#include "unit/engine/core/math/algebra/vector/VectorTestsHelper.h"
#include "unit/engine/core/math/MathCustomTestingFramework.h"
Functions
TYPED_TEST (VectorAlgorithmsTests, Abs)
TYPED_TEST (VectorAlgorithmsTests, AreOrthogonal)
TYPED_TEST (VectorAlgorithmsTests, AreParallel)
TYPED_TEST (VectorAlgorithmsTests, CopyInitialization)
TYPED_TEST (VectorAlgorithmsTests, CrossProduct)
TYPED_TEST (VectorAlgorithmsTests, Dehomogenize)
TYPED_TEST (VectorAlgorithmsTests, DotProduct)
TYPED_TEST (VectorAlgorithmsTests, FillInitialization)
TYPED_TEST (VectorAlgorithmsTests, GetOrthogonal)
TYPED_TEST (VectorAlgorithmsTests, Homogenize)
TYPED_TEST (VectorAlgorithmsTests, IsHomogeneous)
TYPED_TEST (VectorAlgorithmsTests, MoveInitialization)
TYPED_TEST (VectorAlgorithmsTests, RawArrayInitialization)
TYPED_TEST (VectorAlgorithmsTests, VectorAddition)
TYPED_TEST (VectorAlgorithmsTests, VectorAngle)
TYPED_TEST (VectorAlgorithmsTests, VectorClamp)
TYPED_TEST (VectorAlgorithmsTests, VectorCollinearityArray)
TYPED_TEST (VectorAlgorithmsTests, VectorCollinearityThreePoints)
TYPED_TEST (VectorAlgorithmsTests, VectorDistance)
TYPED_TEST (VectorAlgorithmsTests, VectorDistanceSquared)
TYPED_TEST (VectorAlgorithmsTests, VectorDivision)
TYPED_TEST (VectorAlgorithmsTests, VectorEquality)
TYPED_TEST (VectorAlgorithmsTests, VectorInequality)
TYPED_TEST (VectorAlgorithmsTests, VectorIsZero)
TYPED_TEST (VectorAlgorithmsTests, VectorLength)
TYPED_TEST (VectorAlgorithmsTests, VectorLengthSquared)
TYPED_TEST (VectorAlgorithmsTests, VectorLessThan)
TYPED_TEST (VectorAlgorithmsTests, VectorMultiplication)
TYPED_TEST (VectorAlgorithmsTests, VectorNegation)
TYPED_TEST (VectorAlgorithmsTests, VectorNormalize)
TYPED_TEST (VectorAlgorithmsTests, VectorProjection)
TYPED_TEST (VectorAlgorithmsTests, VectorScalarAddition)
TYPED_TEST (VectorAlgorithmsTests, VectorScalarDivision)
TYPED_TEST (VectorAlgorithmsTests, VectorScalarMultiplication)
TYPED_TEST (VectorAlgorithmsTests, VectorScalarSubtraction)
TYPED_TEST (VectorAlgorithmsTests, VectorSubtraction)
TYPED_TEST (VectorAlgorithmsTests, VectorSum)
TYPED_TEST (VectorAlgorithmsTests, ZeroInitialization)
TYPED_TEST_SUITE (VectorAlgorithmsTests, VectorTypes)
Detailed Description
@TODO Add description of this file if needed
Author
Valentin Dumitru
Date
16/01/2024
Copyright (c) 2024 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file VectorAlgorithmsTests.cpp.
Function Documentation
TYPED_TEST() [1/38]
TYPED_TEST (VectorAlgorithmsTests , Abs)
Definition at line 311 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::abs(this->vecA, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = GLESC::Math::abs(this->vecA[i]);
    }
    EXPECT_EQ_VEC(this->result, this->expected);
    // Test with negative values
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecA, Type(-1));
    GLESC::Math::VectorAlgorithms::abs(this->vecA, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = GLESC::Math::abs(this->vecA[i]);
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References GLESC::Math::abs(), GLESC::Math::VectorAlgorithms::abs(), EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [2/38]
TYPED_TEST (VectorAlgorithmsTests , AreOrthogonal)
Definition at line 500 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Positive case: vectors are orthogonal
    VecData orthogonalVec1;
    VecData orthogonalVec2;
    GLESC::Math::VectorAlgorithms::vectorZero(orthogonalVec1);
    GLESC::Math::VectorAlgorithms::vectorZero(orthogonalVec2);
    orthogonalVec1[0] = Type(1); // First vector is [1, 0, 0, ...]
    if (N > 1) {
        orthogonalVec2[1] = Type(1); // Second vector is [0, 1, 0, ...]
    }
    bool resultPositive = GLESC::Math::VectorAlgorithms::areOrthogonal(orthogonalVec1, orthogonalVec2);
    EXPECT_TRUE(resultPositive);
    // Negative case: vectors are not orthogonal
    VecData notOrthogonalVec1 = orthogonalVec1; // Same as orthogonalVec1
    VecData notOrthogonalVec2 = orthogonalVec1; // Same as orthogonalVec1, hence not orthogonal
    bool resultNegative = GLESC::Math::VectorAlgorithms::areOrthogonal(notOrthogonalVec1, notOrthogonalVec2);
    EXPECT_FALSE(resultNegative);
    // Negative case 2: vectors are not orthogonal (one is a scalar multiple of the other)
    VecData notOrthogonalVec3 = orthogonalVec1; // Same as orthogonalVec1
    // Scalar multiple of orthogonalVec1, hence not orthogonal
    VecData notOrthogonalVec4;
    GLESC::Math::VectorAlgorithms::vectorScalarAdd(notOrthogonalVec3, Type(1), notOrthogonalVec4);
    bool resultNegative2 = GLESC::Math::VectorAlgorithms::areOrthogonal(notOrthogonalVec3, notOrthogonalVec4);
    EXPECT_FALSE(resultNegative2);
}
References GLESC::Math::VectorAlgorithms::areOrthogonal(), PREPARE_TEST, GLESC::Math::VectorAlgorithms::vectorScalarAdd(), and GLESC::Math::VectorAlgorithms::vectorZero().
TYPED_TEST() [3/38]
TYPED_TEST (VectorAlgorithmsTests , AreParallel)
Definition at line 432 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Positive case: vectors are parallel
    VecData parallelVec1;
    VecData parallelVec2;
    Type scalar = Type(2);
    initVector1(parallelVec1);
    initVector1(parallelVec2);
    // parallelVec2 is a scalar multiple of parallelVec1
    GLESC::Math::VectorAlgorithms::vectorScalarMul(parallelVec2, scalar, parallelVec2);
    bool resultPositive = GLESC::Math::VectorAlgorithms::areParallel(parallelVec1, parallelVec2);
    EXPECT_TRUE(resultPositive);
    // Negative case: vectors are not parallel
    VecData notParallelVec1 = parallelVec1; // Same as parallelVec1
    VecData notParallelVec2 = parallelVec2;
    notParallelVec2[0] += Type(100); // Significantly alter the first element
    // Apply a change that alters the direction of the vector significantly
    if (N > 1) {
        notParallelVec2[1] += Type(100); // Also significantly alter the second element
    }
    bool resultNegative = GLESC::Math::VectorAlgorithms::areParallel(notParallelVec1, notParallelVec2);
    EXPECT_FALSE(resultNegative);
}
References GLESC::Math::VectorAlgorithms::areParallel(), initVector1(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [4/38]
TYPED_TEST (VectorAlgorithmsTests , CopyInitialization)
Definition at line 74 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    VecData copySource;
    // Initialize copySource with some values
    GLESC::Math::VectorAlgorithms::vectorCopy(copySource, this->result);
    EXPECT_EQ_VEC(this->result, copySource);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorCopy().
TYPED_TEST() [5/38]
TYPED_TEST (VectorAlgorithmsTests , CrossProduct)
Definition at line 339 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 3) {
        // Assuming vecA and vecB are initialized by initializeVector
        GLESC::Math::VectorAlgorithms::crossProduct(this->vecA, this->vecB, this->result);
        this->expected = {
            this->vecA[1] * this->vecB[2] - this->vecA[2] * this->vecB[1],
            this->vecA[2] * this->vecB[0] - this->vecA[0] * this->vecB[2],
            this->vecA[0] * this->vecB[1] - this->vecA[1] * this->vecB[0]
        };
        EXPECT_EQ_VEC(this->result, this->expected);
    }
}
References GLESC::Math::VectorAlgorithms::crossProduct(), EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [6/38]
TYPED_TEST (VectorAlgorithmsTests , Dehomogenize)
Definition at line 485 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    this->vecA[N - 1] = Type(1); // Ensure the last element (homogeneous coordinate) is not zero
    GLESC::Math::VectorData<Type, N - 1> dehomogenized;
    GLESC::Math::VectorAlgorithms::dehomogenize(this->vecA, dehomogenized);
    GLESC::Math::VectorData<Type, N - 1> expectedDehomogenized;
    Type wComponent = this->vecA[N - 1]; // The last element of the homogeneous vector
    for (size_t i = 0; i < N - 1; ++i) {
        expectedDehomogenized[i] = this->vecA[i] / wComponent;
    }
    EXPECT_EQ_VEC(dehomogenized, expectedDehomogenized);
}
References GLESC::Math::VectorAlgorithms::dehomogenize(), EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [7/38]
TYPED_TEST (VectorAlgorithmsTests , DotProduct)
Definition at line 328 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Assuming vecA and vecB are initialized by initializeVector
    Type result = GLESC::Math::VectorAlgorithms::dotProduct(this->vecA, this->vecB);
    Type expected = Type(0); // Placeholder, compute based on vecA and vecB
    for (size_t i = 0; i < N; ++i) {
        expected += this->vecA[i] * this->vecB[i];
    }
    EXPECT_EQ_CUSTOM(result, expected);
}
References GLESC::Math::VectorAlgorithms::dotProduct(), EXPECT_EQ_CUSTOM, and PREPARE_TEST.
TYPED_TEST() [8/38]
TYPED_TEST (VectorAlgorithmsTests , FillInitialization)
Definition at line 55 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type fillValue = Type(5);
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecA, fillValue);
    for (size_t i = 0; i < N; ++i) {
        EXPECT_EQ(this->vecA[i], fillValue);
    }
}
References PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [9/38]
TYPED_TEST (VectorAlgorithmsTests , GetOrthogonal)
Definition at line 530 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 2 || N == 3 || N == 4) {
        // Assuming vecA is initialized by initializeVector
        GLESC::Math::VectorAlgorithms::getOrthogonal(this->vecA, this->result);
        // As the specific orthogonal vector might depend on the implementation details,
        // you can directly verify if the result vector is indeed orthogonal to vecA.
        EXPECT_TRUE(GLESC::Math::VectorAlgorithms::areOrthogonal(this->vecA, this->result));
    }
}
References GLESC::Math::VectorAlgorithms::areOrthogonal(), GLESC::Math::VectorAlgorithms::getOrthogonal(), and PREPARE_TEST.
TYPED_TEST() [10/38]
TYPED_TEST (VectorAlgorithmsTests , Homogenize)
Definition at line 469 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Test homogenizing a vector
    GLESC::Math::VectorData<Type, N + 1> homogenized;
    GLESC::Math::VectorAlgorithms::homogenize(this->vecA, homogenized);
    GLESC::Math::VectorData<Type, N + 1> expectedHomogenized;
    for (size_t i = 0; i < N; ++i) {
        // Iterate up to N
        expectedHomogenized[i] = this->vecA[i];
    }
    expectedHomogenized[N] = Type(1); // Set index N to 1
    EXPECT_EQ_VEC(homogenized, expectedHomogenized);
}
References EXPECT_EQ_VEC, GLESC::Math::VectorAlgorithms::homogenize(), and PREPARE_TEST.
TYPED_TEST() [11/38]
TYPED_TEST (VectorAlgorithmsTests , IsHomogeneous)
Definition at line 460 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Assuming vecA is initialized by initializeVector
    bool result = GLESC::Math::VectorAlgorithms::isHomogeneous(this->vecA);
    bool expected = (this->vecA[N - 1] == Type(1)); // Change based on expected result
    EXPECT_EQ_CUSTOM(result, expected);
}
References EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::isHomogeneous(), and PREPARE_TEST.
TYPED_TEST() [12/38]
TYPED_TEST (VectorAlgorithmsTests , MoveInitialization)
Definition at line 82 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    VecData vectorToMove;
    initVector1(vectorToMove);
    VecData copySource = vectorToMove;
    // Initialize vectorToMove with some values
    GLESC::Math::VectorAlgorithms::vectorMove(this->result, vectorToMove);
    // Can't really check the state of vectorToMove after move, but can check result
    EXPECT_EQ_VEC(copySource, this->result); // Assuming move keeps the data
}
References EXPECT_EQ_VEC, initVector1(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorMove().
TYPED_TEST() [13/38]
TYPED_TEST (VectorAlgorithmsTests , RawArrayInitialization)
Definition at line 64 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Adjust size as per N
    Type rawArray[N] = {Type(1), Type(2)};
    GLESC::Math::VectorAlgorithms::vectorInitRawArray(this->vecA, rawArray);
    for (size_t i = 0; i < N; ++i) {
        EXPECT_EQ(this->vecA[i], rawArray[i]);
    }
}
References PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorInitRawArray().
TYPED_TEST() [14/38]
TYPED_TEST (VectorAlgorithmsTests , VectorAddition)
Definition at line 97 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::vectorAdd(this->vecA, this->vecB, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] + this->vecB[i];
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorAdd().
TYPED_TEST() [15/38]
TYPED_TEST (VectorAlgorithmsTests , VectorAngle)
Definition at line 410 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type result = GLESC::Math::VectorAlgorithms::angle(this->vecA, this->vecB);
    Type dot = GLESC::Math::VectorAlgorithms::dotProduct(this->vecA, this->vecB);
    Type lenA = GLESC::Math::VectorAlgorithms::length(this->vecA);
    Type lenB = GLESC::Math::VectorAlgorithms::length(this->vecB);
    Type expected = std::acos(dot / (lenA * lenB));
    EXPECT_EQ_CUSTOM(result, expected);
}
References GLESC::Math::VectorAlgorithms::angle(), GLESC::Math::VectorAlgorithms::dotProduct(), EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::length(), and PREPARE_TEST.
TYPED_TEST() [16/38]
TYPED_TEST (VectorAlgorithmsTests , VectorClamp)
Definition at line 278 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    TEST_SECTION("Vector clamp with values");
    Type min = Type(1);
    Type max = Type(5);
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecA, Type(10));
    GLESC::Math::VectorAlgorithms::clampWithValues(this->vecA, min, max, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = GLESC::Math::clamp(this->vecA[i], min, max);
    }
    EXPECT_EQ_VEC(this->result, this->expected);
    TEST_SECTION("Vector clamp with vectors");
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecA, Type(1));
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecB, Type(5));
    GLESC::Math::VectorAlgorithms::clampWithVectors(this->vecA, this->vecB, this->vecB, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = GLESC::Math::clamp(this->vecA[i], this->vecB[i], this->vecB[i]);
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References GLESC::Math::clamp(), GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::VectorAlgorithms::clampWithVectors(), EXPECT_EQ_VEC, PREPARE_TEST, TEST_SECTION, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [17/38]
TYPED_TEST (VectorAlgorithmsTests , VectorCollinearityArray)
Definition at line 541 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 3) {
        // Two vectors are always collinear
        std::vector<const VecData*> collinearVecs = {&this->vecA};
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, collinearVecs));
        // Collinear vectors with a scalar multiple
        collinearVecs.clear();
        VecData collinearVec1 = this->vecA;
        VecData collinearVec2 = this->vecA;
        VecData collinearVec3 = this->vecA;
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearVec1, Type(2), collinearVec1);
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearVec2, Type(0.5), collinearVec2);
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearVec3, Type(-1), collinearVec3);
        collinearVecs.push_back(&collinearVec1);
        collinearVecs.push_back(&collinearVec2);
        collinearVecs.push_back(&collinearVec3);
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, collinearVecs));
        // Two vectors are the same, therefore they are collinear
        VecData nonCollinear = this->vecA;
        nonCollinear[0] += 555;
        std::vector<const VecData*> nonCollinearVecs = {&nonCollinear, &this->vecA};
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, nonCollinearVecs));
        // Non collinear vectors
        VecData nonCollinearVec1 = this->vecA;
        VecData nonCollinearVec2 = this->vecA;
        VecData nonCollinearVec3 = this->vecA;
        nonCollinearVec1[0] += 6;
        nonCollinearVec2[1] += 4;
        nonCollinearVec3[2] += 3;
        nonCollinearVecs = {&nonCollinearVec1, &nonCollinearVec2, &nonCollinearVec3};
        EXPECT_FALSE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, nonCollinearVecs));
    }
}
References GLESC::Math::VectorMixedAlgorithms::areCollinear(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [18/38]
TYPED_TEST (VectorAlgorithmsTests , VectorCollinearityThreePoints)
Definition at line 578 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 3) {
        // Three points are always collinear
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, this->vecB, this->result));
        // Collinear points with a scalar multiple
        VecData collinearPoint1 = this->vecA;
        VecData collinearPoint2 = this->vecA;
        VecData collinearPoint3 = this->vecA;
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearPoint1, Type(2), collinearPoint1);
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearPoint2, Type(0.5), collinearPoint2);
        GLESC::Math::VectorAlgorithms::vectorScalarMul(collinearPoint3, Type(-1), collinearPoint3);
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, collinearPoint1, collinearPoint2));
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(this->vecA, collinearPoint1, collinearPoint3));
        // Two equal, one non equal
        VecData equalPoint1 = this->vecA;
        VecData equalPoint2 = this->vecA;
        VecData nonEqualPoint = this->vecA;
        nonEqualPoint[0] += 555;
        EXPECT_TRUE(GLESC::Math::VectorMixedAlgorithms::areCollinear(equalPoint1, equalPoint2, nonEqualPoint));
        // Non collinear points
        VecData nonCollinearPoint1 = this->vecA;
        VecData nonCollinearPoint2 = this->vecA;
        VecData nonCollinearPoint3 = this->vecA;
        nonCollinearPoint1[0] += 6;
        nonCollinearPoint2[1] += 4;
        nonCollinearPoint3[2] += 3;
        EXPECT_FALSE(
            GLESC::Math::VectorMixedAlgorithms::areCollinear(nonCollinearPoint1, nonCollinearPoint2, nonCollinearPoint3
            ));
    }
}
References GLESC::Math::VectorMixedAlgorithms::areCollinear(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [19/38]
TYPED_TEST (VectorAlgorithmsTests , VectorDistance)
Definition at line 373 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type result = GLESC::Math::VectorAlgorithms::distance(this->vecA, this->vecB);
    VecData diff;
    for (size_t i = 0; i < N; ++i) {
        diff[i] = this->vecA[i] - this->vecB[i];
    }
    Type expected = GLESC::Math::VectorAlgorithms::length(diff);
    EXPECT_EQ_CUSTOM(result, expected);
}
References GLESC::Math::VectorAlgorithms::distance(), EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::length(), and PREPARE_TEST.
TYPED_TEST() [20/38]
TYPED_TEST (VectorAlgorithmsTests , VectorDistanceSquared)
Definition at line 384 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type result = GLESC::Math::VectorAlgorithms::distanceSquared(this->vecA, this->vecB);
    VecData diff;
    for (size_t i = 0; i < N; ++i) {
        diff[i] = this->vecA[i] - this->vecB[i];
    }
    Type expected = GLESC::Math::VectorAlgorithms::lengthSquared(diff);
    EXPECT_EQ_CUSTOM(result, expected);
}
References GLESC::Math::VectorAlgorithms::distanceSquared(), EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::lengthSquared(), and PREPARE_TEST.
TYPED_TEST() [21/38]
TYPED_TEST (VectorAlgorithmsTests , VectorDivision)
Definition at line 163 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Ensure that vecB does not contain zeroes to avoid division by zero
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecB, Type(1)); // Example, replace with suitable values
    GLESC::Math::VectorAlgorithms::vectorDiv(this->vecA, this->vecB, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] / this->vecB[i];
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, GLESC::Math::VectorAlgorithms::vectorDiv(), and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [22/38]
TYPED_TEST (VectorAlgorithmsTests , VectorEquality)
Definition at line 189 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    bool isEqual = GLESC::Math::VectorAlgorithms::eq(this->vecA, this->vecB);
    bool expectedResult = false; // Checking different vectors
    EXPECT_EQ(isEqual, expectedResult);
    isEqual = GLESC::Math::VectorAlgorithms::eq(this->vecA, this->vecA);
    expectedResult = true; // Checking same vectors
    EXPECT_EQ(isEqual, expectedResult);
}
References GLESC::Math::VectorAlgorithms::eq(), and PREPARE_TEST.
TYPED_TEST() [23/38]
TYPED_TEST (VectorAlgorithmsTests , VectorInequality)
Definition at line 200 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Checking different vectors
    bool isNotEqual = GLESC::Math::VectorAlgorithms::neq(this->vecA, this->vecB);
    bool expectedResult = true;
    EXPECT_EQ(isNotEqual, expectedResult);
    // Checking same vectors
    isNotEqual = GLESC::Math::VectorAlgorithms::neq(this->vecA, this->vecA);
    expectedResult = false;
    EXPECT_EQ(isNotEqual, expectedResult);
    // Checking vectors with 1 equal and rest different
    VecData vec1;
    GLESC::Math::VectorAlgorithms::vectorFill(vec1, Type(1));
    VecData vec2;
    GLESC::Math::VectorAlgorithms::vectorFill(vec2, Type(5));
    vec2[0] = Type(1);
    isNotEqual = GLESC::Math::VectorAlgorithms::neq(vec1, vec2);
    expectedResult = true;
    EXPECT_EQ(isNotEqual, expectedResult);
    // Checking vectors with 1 different and rest equal
    GLESC::Math::VectorAlgorithms::vectorFill(vec1, Type(1));
    GLESC::Math::VectorAlgorithms::vectorFill(vec2, Type(1));
    vec2[0] = Type(5);
    isNotEqual = GLESC::Math::VectorAlgorithms::neq(vec1, vec2);
    expectedResult = true;
    EXPECT_EQ(isNotEqual, expectedResult);
}
References GLESC::Math::VectorAlgorithms::neq(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [24/38]
TYPED_TEST (VectorAlgorithmsTests , VectorIsZero)
Definition at line 252 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    bool isZero = GLESC::Math::VectorAlgorithms::isZero(this->vecA);
    bool expectedResult = false; // Assuming vecA is not zero
    EXPECT_EQ(isZero, expectedResult);
    // Test with zero vector
    GLESC::Math::VectorAlgorithms::vectorZero(this->vecA);
    isZero = GLESC::Math::VectorAlgorithms::isZero(this->vecA);
    expectedResult = true; // Assuming vecA is zero
    EXPECT_EQ(isZero, expectedResult);
    // Manually set the first element to a non-zero value
    this->vecA[0] = Type(1);
    isZero = GLESC::Math::VectorAlgorithms::isZero(this->vecA);
    EXPECT_FALSE(isZero);
    // Manually set all the elements to zero
    VecData zeroVec;
    for (size_t i = 0; i < N; ++i) {
        zeroVec[i] = Type(0);
    }
    isZero = GLESC::Math::VectorAlgorithms::isZero(zeroVec);
    EXPECT_TRUE(isZero);
}
References GLESC::Math::VectorAlgorithms::isZero(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorZero().
TYPED_TEST() [25/38]
TYPED_TEST (VectorAlgorithmsTests , VectorLength)
Definition at line 353 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Assuming vecA is initialized by initializeVector
    Type result = GLESC::Math::VectorAlgorithms::length(this->vecA);
    Type expected = GLESC::Math::sqrt(GLESC::Math::VectorAlgorithms::dotProduct(this->vecA, this->vecA));
    EXPECT_EQ_CUSTOM(result, expected);
}
References GLESC::Math::VectorAlgorithms::dotProduct(), EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::length(), PREPARE_TEST, and GLESC::Math::sqrt().
TYPED_TEST() [26/38]
TYPED_TEST (VectorAlgorithmsTests , VectorLengthSquared)
Definition at line 362 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type result = GLESC::Math::VectorAlgorithms::lengthSquared(this->vecA);
    Type expected = Type(0);
    for (size_t i = 0; i < N; ++i) {
        expected += this->vecA[i] * this->vecA[i];
    }
    EXPECT_EQ_CUSTOM(result, expected);
}
References EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::lengthSquared(), and PREPARE_TEST.
TYPED_TEST() [27/38]
TYPED_TEST (VectorAlgorithmsTests , VectorLessThan)
Definition at line 231 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    // Less than checks the lenght of the vectors
    // First we initialize a vector with a lenght of 1
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecA, Type(1));
    // Then we initialize a vector with a lenght of more than 1
    GLESC::Math::VectorAlgorithms::vectorFill(this->vecB, Type(2)); // For example, 2
    bool isLessThan = GLESC::Math::VectorAlgorithms::lt(this->vecA, this->vecB);
    bool expectedResult = true; // A is less than B
    EXPECT_EQ(isLessThan, expectedResult);
    // To check if it works, we swap the vectors and check the negative
    isLessThan = GLESC::Math::VectorAlgorithms::lt(this->vecB, this->vecA);
    expectedResult = false; // B is not less than A
    EXPECT_EQ(isLessThan, expectedResult);
}
References GLESC::Math::VectorAlgorithms::lt(), PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [28/38]
TYPED_TEST (VectorAlgorithmsTests , VectorMultiplication)
Definition at line 144 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::vectorMul(this->vecA, this->vecB, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] * this->vecB[i];
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorMul().
TYPED_TEST() [29/38]
TYPED_TEST (VectorAlgorithmsTests , VectorNegation)
Definition at line 135 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::vectorNegate(this->vecA, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = -this->vecA[i];
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorNegate().
TYPED_TEST() [30/38]
TYPED_TEST (VectorAlgorithmsTests , VectorNormalize)
Definition at line 395 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::normalize(this->vecA, this->result);
    Type len = GLESC::Math::VectorAlgorithms::length(this->vecA);
    if (len != Type(0) && len != Type(1)) {
        for (size_t i = 0; i < N; ++i) {
            this->expected[i] = this->vecA[i] / len;
        }
    }
    else {
        this->expected = this->vecA;
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, GLESC::Math::VectorAlgorithms::length(), GLESC::Math::VectorAlgorithms::normalize(), and PREPARE_TEST.
TYPED_TEST() [31/38]
TYPED_TEST (VectorAlgorithmsTests , VectorProjection)
Definition at line 422 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::project(this->vecA, this->vecB, this->result);
    Type scalarProjection = GLESC::Math::VectorAlgorithms::dotProduct(this->vecA, this->vecB) /
        GLESC::Math::VectorAlgorithms::length(this->vecB);
    GLESC::Math::VectorAlgorithms::vectorScalarMul(this->vecB, scalarProjection, this->expected);
    EXPECT_EQ_VEC(this->result, this->expected);
}
References GLESC::Math::VectorAlgorithms::dotProduct(), EXPECT_EQ_VEC, GLESC::Math::VectorAlgorithms::length(), PREPARE_TEST, GLESC::Math::VectorAlgorithms::project(), and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [32/38]
TYPED_TEST (VectorAlgorithmsTests , VectorScalarAddition)
Definition at line 106 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type scalar = 5;
    GLESC::Math::VectorAlgorithms::vectorScalarAdd(this->vecA, scalar, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] + scalar;
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarAdd().
TYPED_TEST() [33/38]
TYPED_TEST (VectorAlgorithmsTests , VectorScalarDivision)
Definition at line 174 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type scalar = 5;
    // Ensure scalar is not zero to avoid division by zero
    GLESC::Math::VectorAlgorithms::vectorScalarDiv(this->vecA, scalar, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] / scalar;
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarDiv().
TYPED_TEST() [34/38]
TYPED_TEST (VectorAlgorithmsTests , VectorScalarMultiplication)
Definition at line 153 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type scalar = 5;
    GLESC::Math::VectorAlgorithms::vectorScalarMul(this->vecA, scalar, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] * scalar;
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [35/38]
TYPED_TEST (VectorAlgorithmsTests , VectorScalarSubtraction)
Definition at line 125 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type scalar = 5;
    GLESC::Math::VectorAlgorithms::vectorScalarSub(this->vecA, scalar, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] - scalar;
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarSub().
TYPED_TEST() [36/38]
TYPED_TEST (VectorAlgorithmsTests , VectorSubtraction)
Definition at line 116 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::vectorSub(this->vecA, this->vecB, this->result);
    for (size_t i = 0; i < N; ++i) {
        this->expected[i] = this->vecA[i] - this->vecB[i];
    }
    EXPECT_EQ_VEC(this->result, this->expected);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorSub().
TYPED_TEST() [37/38]
TYPED_TEST (VectorAlgorithmsTests , VectorSum)
Definition at line 301 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    Type result = GLESC::Math::VectorAlgorithms::sum(this->vecA);
    Type expected = Type(0);
    for (size_t i = 0; i < N; ++i) {
        expected += this->vecA[i];
    }
    EXPECT_EQ_CUSTOM(result, expected);
}
References EXPECT_EQ_CUSTOM, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::sum().
TYPED_TEST() [38/38]
TYPED_TEST (VectorAlgorithmsTests , ZeroInitialization)
Definition at line 47 of file VectorAlgorithmsTests.cpp.
{
    PREPARE_TEST();
    GLESC::Math::VectorAlgorithms::vectorZero(this->vecA);
    for (size_t i = 0; i < N; ++i) {
        EXPECT_EQ(this->vecA[i], Type(0));
    }
}
References PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorZero().
TYPED_TEST_SUITE()
TYPED_TEST_SUITE (VectorAlgorithmsTests , VectorTypes)