GLESC: VectorTests.cpp File Reference
VectorTests.cpp File Reference
#include "TestsConfig.h"
#include <gtest/gtest.h>
#include <engine/core/math/algebra/vector/VectorMixedAlgorithms.h>
#include "engine/core/math/algebra/matrix/Matrix.h"
#include "engine/subsystems/input/InputKeys.h"
#include "unit/engine/core/math/algebra/vector/VectorTestsHelper.h"
#include "unit/engine/core/math/MathCustomTestingFramework.h"
Functions
TYPED_TEST (VectorTests, Abs)
TYPED_TEST (VectorTests, Accesors)
TYPED_TEST (VectorTests, AddArithmeticOperator)
TYPED_TEST (VectorTests, AdditionAssignment)
TYPED_TEST (VectorTests, AdditionAssignmentScalar)
TYPED_TEST (VectorTests, AddScalarAritmeticOperator)
TYPED_TEST (VectorTests, ArrayAssignment)
TYPED_TEST (VectorTests, Constructors)
TYPED_TEST (VectorTests, CopyAssignment)
TYPED_TEST (VectorTests, DivisionAssignment)
TYPED_TEST (VectorTests, DivisionAssignmentScalar)
TYPED_TEST (VectorTests, DivisionOperators)
TYPED_TEST (VectorTests, DivisionScalarOperators)
TYPED_TEST (VectorTests, EqualityOperator)
TYPED_TEST (VectorTests, GreaterThanOperator)
TYPED_TEST (VectorTests, GreaterThanOrEqualOperator)
TYPED_TEST (VectorTests, InequalityOperator)
TYPED_TEST (VectorTests, InitializerListAssignment)
TYPED_TEST (VectorTests, LessThanOperator)
TYPED_TEST (VectorTests, LessThanOrEqualOperator)
TYPED_TEST (VectorTests, MoveAssignment)
TYPED_TEST (VectorTests, MultiplicationAssignment)
TYPED_TEST (VectorTests, MultiplicationAssignmentScalar)
TYPED_TEST (VectorTests, MultiplicationOperators)
TYPED_TEST (VectorTests, MultiplicationScalarOperators)
TYPED_TEST (VectorTests, SubArithmeticOperator)
TYPED_TEST (VectorTests, SubScalarAritmeticOperator)
TYPED_TEST (VectorTests, SubtractionAssignment)
TYPED_TEST (VectorTests, SubtractionAssignmentScalar)
TYPED_TEST (VectorTests, UnaryMinusOperators)
TYPED_TEST (VectorTests, VectorClamp)
TYPED_TEST (VectorTests, VectorCollinearityOperator)
TYPED_TEST (VectorTests, VectorCross)
TYPED_TEST (VectorTests, VectorDehomogenous)
TYPED_TEST (VectorTests, VectorDistance)
TYPED_TEST (VectorTests, VectorDot)
TYPED_TEST (VectorTests, VectorGetOrthogonal)
TYPED_TEST (VectorTests, VectorHomogenize)
TYPED_TEST (VectorTests, VectorIsHomogenous)
TYPED_TEST (VectorTests, VectorIsOrthogonal)
TYPED_TEST (VectorTests, VectorIsParallel)
TYPED_TEST (VectorTests, VectorIsZero)
TYPED_TEST (VectorTests, VectorLenght)
TYPED_TEST (VectorTests, VectorMultiple)
TYPED_TEST (VectorTests, VectorNormalize)
TYPED_TEST (VectorTests, VectorSize)
TYPED_TEST (VectorTests, VectorSum)
TYPED_TEST (VectorTests, VectorSwap)
TYPED_TEST (VectorTests, VectorToString)
TYPED_TEST_SUITE (VectorTests, VectorTypes)
Function Documentation
TYPED_TEST() [1/49]
TYPED_TEST (VectorTests , Abs)
Definition at line 588 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Give v1 negative values
    Vec abs = -this->v1;
    abs = this->v1.abs();
    EXPECT_EQ_VEC(this->v1.data, abs.data);
    // Give v2 negative values
    abs = -this->v2;
    abs = this->v2.abs();
    EXPECT_EQ_VEC(this->v2.data, abs.data);
    // try with positive values
    abs = this->v1.abs();
    EXPECT_EQ_VEC(this->v1.data, abs.data);
}
References EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [2/49]
TYPED_TEST (VectorTests , Accesors)
Definition at line 44 of file VectorTests.cpp.
{
    PREPARE_TEST();
    TEST_SECTION("Vector Size")
    {
        EXPECT_EQ(this->v1.size(), N);
    }
    TEST_SECTION("Vector get()")
    {
        for (size_t i = 0; i < N; ++i)
            EXPECT_EQ_CUSTOM(this->v1.get(i), generateNextValue1<Type>(i));
    }
    TEST_SECTION("Vector []")
    {
        for (size_t i = 0; i < N; ++i)
            EXPECT_EQ_CUSTOM(this->v1[i], generateNextValue1<Type>(i));
    }
    TEST_SECTION("Vector x(), y(), z(), w()")
    {
        Vec v3;
        initVector1(v3);
        if constexpr (N >= 1) {
            EXPECT_EQ_CUSTOM(this->v1.x(), generateNextValue1<Type>(0));
            EXPECT_EQ_CUSTOM(this->v1.getX(), generateNextValue1<Type>(0));
            v3.x(generateNextValue1<Type>(0) + Type(1));
            EXPECT_EQ_CUSTOM(v3.x(), generateNextValue1<Type>(0) + Type(1));
            v3.setX(generateNextValue1<Type>(0) + Type(2));
            EXPECT_EQ_CUSTOM(v3.x(), generateNextValue1<Type>(0) + Type(2));
        }
        if constexpr (N >= 2) {
            EXPECT_EQ_CUSTOM(this->v1.y(), generateNextValue1<Type>(1));
            EXPECT_EQ_CUSTOM(this->v1.getY(), generateNextValue1<Type>(1));
            v3.y(generateNextValue1<Type>(1) + Type(1));
            EXPECT_EQ_CUSTOM(v3.y(), generateNextValue1<Type>(1) + Type(1));
            v3.setY(generateNextValue1<Type>(1) + Type(2));
            EXPECT_EQ_CUSTOM(v3.y(), generateNextValue1<Type>(1) + Type(2));
        }
        if constexpr (N >= 3) {
            EXPECT_EQ_CUSTOM(this->v1.z(), generateNextValue1<Type>(2));
            EXPECT_EQ_CUSTOM(this->v1.getZ(), generateNextValue1<Type>(2));
            v3.z(generateNextValue1<Type>(2) + Type(1));
            EXPECT_EQ_CUSTOM(v3.z(), generateNextValue1<Type>(2) + Type(1));
            v3.setZ(generateNextValue1<Type>(2) + Type(2));
            EXPECT_EQ_CUSTOM(v3.z(), generateNextValue1<Type>(2) + Type(2));
        }
        if constexpr (N >= 4) {
            EXPECT_EQ_CUSTOM(this->v1.w(), generateNextValue1<Type>(3));
            EXPECT_EQ_CUSTOM(this->v1.getW(), generateNextValue1<Type>(3));
            v3.w(generateNextValue1<Type>(3) + Type(1));
            EXPECT_EQ_CUSTOM(v3.w(), generateNextValue1<Type>(3) + Type(1));
            v3.setW(generateNextValue1<Type>(3) + Type(2));
            EXPECT_EQ_CUSTOM(v3.w(), generateNextValue1<Type>(3) + Type(2));
        }
    }
}
References EXPECT_EQ_CUSTOM, initVector1(), PREPARE_TEST, and TEST_SECTION.
TYPED_TEST() [3/49]
TYPED_TEST (VectorTests , AddArithmeticOperator)
Definition at line 349 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Addition with another vector
    Vec add;
    add = this->v1 + this->v2;
    Vec expectAdd;
    GLESC::Math::VectorAlgorithms::vectorAdd(this->v1.data, this->v2.data, expectAdd.data);
    EXPECT_EQ_VEC(add, expectAdd);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorAdd().
TYPED_TEST() [4/49]
TYPED_TEST (VectorTests , AdditionAssignment)
Definition at line 261 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Addition assignment with another vector
    Vec addAssign = this->v1;
    addAssign += this->v1;
    Vec expectAddAssign;
    GLESC::Math::VectorAlgorithms::vectorAdd(this->v1.data, this->v1.data, expectAddAssign.data);
    EXPECT_EQ_VEC(addAssign, expectAddAssign);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorAdd().
TYPED_TEST() [5/49]
TYPED_TEST (VectorTests , AdditionAssignmentScalar)
Definition at line 271 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Addition assignment with a scalar
    Vec addAssignScalar = this->v1;
    const Type scalarAdd = Type(10);
    addAssignScalar += scalarAdd;
    Vec expectAddAssignScalar = this->v1;
    GLESC::Math::VectorAlgorithms::vectorScalarAdd(this->v1.data, scalarAdd, expectAddAssignScalar.data);
    EXPECT_EQ_VEC(addAssignScalar, expectAddAssignScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarAdd().
TYPED_TEST() [6/49]
TYPED_TEST (VectorTests , AddScalarAritmeticOperator)
Definition at line 361 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Addition with a scalar
    Vec addScalar;
    const Type scalarAdd = Type(10);
    addScalar = this->v1 + scalarAdd;
    Vec expectAddScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarAdd(this->v1.data, scalarAdd, expectAddScalar.data);
    EXPECT_EQ_VEC(addScalar, expectAddScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarAdd().
TYPED_TEST() [7/49]
TYPED_TEST (VectorTests , ArrayAssignment)
Definition at line 218 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Array assignment
    Type arr[N];
    for (size_t i = 0; i < N; ++i)
        arr[i] = generateNextValue1<Type>(i);
    Vec arrayAssign;
    arrayAssign = arr;
    EXPECT_EQ_VEC(arrayAssign, this->v1);
}
References EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [8/49]
TYPED_TEST (VectorTests , Constructors)
Definition at line 110 of file VectorTests.cpp.
{
    PREPARE_TEST();
    TEST_SECTION("Default Constructor")
    {
        Vec defaultConstruct;
        Vec expectDefaultConstruct;
        for (size_t i = 0; i < N; ++i)
            expectDefaultConstruct.set(i, Type());
        EXPECT_EQ_VEC(defaultConstruct, expectDefaultConstruct);
    }
    TEST_SECTION("Variadic Constructor")
    {
        // Variadic constructor
        if constexpr (N == 2) {
            Vec variadicConstruct(generateNextValue1<Type>(0), generateNextValue1<Type>(1));
            EXPECT_EQ_VEC(variadicConstruct, this->v1);
        }
        if constexpr (N == 3) {
            Vec variadicConstruct(generateNextValue1<Type>(0), generateNextValue1<Type>(1),
                                  generateNextValue1<Type>(2));
            EXPECT_EQ_VEC(variadicConstruct, this->v1);
        }
        if constexpr (N == 4) {
            Vec variadicConstruct
            (generateNextValue1<Type>(0), generateNextValue1<Type>(1), generateNextValue1<Type>(2),
             generateNextValue1<Type>(3));
            EXPECT_EQ_VEC(variadicConstruct, this->v1);
        } // Enough with the variadic constructors, it could go on forever
    }
    TEST_SECTION("Array constructor")
    {
        // Array constructor
        Type arr[N];
        for (size_t i = 0; i < N; ++i)
            arr[i] = generateNextValue1<Type>(i);
        Vec arrayConstruct(arr);
        EXPECT_EQ_VEC(arrayConstruct, this->v1);
    }
    TEST_SECTION("Initializer List Constructor")
    {
        // Initializer list constructor
        if constexpr (N == 2) {
            Vec initListConstruct{generateNextValue1<Type>(0), generateNextValue1<Type>(1)};
            EXPECT_EQ_VEC(initListConstruct, this->v1);
        }
        if constexpr (N == 3) {
            Vec initListConstruct{
                generateNextValue1<Type>(0), generateNextValue1<Type>(1),
                generateNextValue1<Type>(2)
            };
            EXPECT_EQ_VEC(initListConstruct, this->v1);
        }
        if constexpr (N == 4) {
            Vec initListConstruct
            {
                generateNextValue1<Type>(0), generateNextValue1<Type>(1), generateNextValue1<Type>(2),
                generateNextValue1<Type>(3)
            };
            EXPECT_EQ_VEC(initListConstruct, this->v1);
        } // Enough with the initializers, it could go on forever
    }
    TEST_SECTION("Fill Constructor")
    {
        // Fill constructor
        Type fillValue = Type(1);
        Vec fillConstruct(fillValue);
        Vec expectFillConstruct;
        GLESC::Math::VectorAlgorithms::vectorFill(expectFillConstruct.data, fillValue);
        EXPECT_EQ_VEC(fillConstruct, expectFillConstruct);
    }
    TEST_SECTION("Copy Constructor")
    {
        // Copy constructor
        Vec copyConstruct;
        initVector1(copyConstruct);
        Vec copyConstruct2(copyConstruct);
        EXPECT_EQ_VEC(copyConstruct2, copyConstruct);
        EXPECT_EQ_VEC(copyConstruct2, this->v1); // Must be equal to the initial vector
    }
    TEST_SECTION("Move Constructor")
    {
        // Move constructor
        Vec moveConstruct;
        initVector1(moveConstruct);
        Vec moveConstruct2(std::move(moveConstruct));
        EXPECT_EQ_VEC(moveConstruct2, this->v1);
    }
}
References EXPECT_EQ_VEC, initVector1(), PREPARE_TEST, TEST_SECTION, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [9/49]
TYPED_TEST (VectorTests , CopyAssignment)
Definition at line 200 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Copy assignment
    Vec copyAssign;
    copyAssign = this->v1;
    EXPECT_EQ_VEC(copyAssign, this->v1); // Must be equal to the initial vector
}
References EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [10/49]
TYPED_TEST (VectorTests , DivisionAssignment)
Definition at line 324 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Division assignment with another vector
    Vec divAssign = this->v1;
    divAssign /= this->v2;
    Vec expectDivAssign;
    GLESC::Math::VectorAlgorithms::vectorDiv(this->v1.data, this->v2.data, expectDivAssign.data);
    EXPECT_EQ_VEC(divAssign, expectDivAssign);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorDiv().
TYPED_TEST() [11/49]
TYPED_TEST (VectorTests , DivisionAssignmentScalar)
Definition at line 335 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Division assignment with a scalar
    Vec divAssignScalar = this->v1;
    const Type scalarDiv = Type(10);
    divAssignScalar /= scalarDiv;
    Vec expectDivAssignScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarDiv(this->v1.data, scalarDiv, expectDivAssignScalar.data);
    EXPECT_EQ_VEC(divAssignScalar, expectDivAssignScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarDiv().
TYPED_TEST() [12/49]
TYPED_TEST (VectorTests , DivisionOperators)
Definition at line 425 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Division with another vector
    Vec div;
    div = this->v1 / this->v2;
    Vec expectDiv;
    GLESC::Math::VectorAlgorithms::vectorDiv(this->v1.data, this->v2.data, expectDiv.data);
    EXPECT_EQ_VEC(div, expectDiv);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorDiv().
TYPED_TEST() [13/49]
TYPED_TEST (VectorTests , DivisionScalarOperators)
Definition at line 435 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Division with a scalar
    Vec divScalar;
    const Type scalarDiv = Type(10);
    divScalar = this->v1 / scalarDiv;
    Vec expectDivScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarDiv(this->v1.data, scalarDiv, expectDivScalar.data);
    EXPECT_EQ_VEC(divScalar, expectDivScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarDiv().
TYPED_TEST() [14/49]
TYPED_TEST (VectorTests , EqualityOperator)
Definition at line 450 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Equality
    Vec eq = this->v1;
    EXPECT_TRUE(eq == this->v1);
    Vec eq2 = this->v2;
    EXPECT_FALSE(eq2 == this->v1);
}
References PREPARE_TEST.
TYPED_TEST() [15/49]
TYPED_TEST (VectorTests , GreaterThanOperator)
Definition at line 501 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Greater than
    Vec gt = this->v1;
    EXPECT_FALSE(gt > this->v1);
    gt += Type(100);
    EXPECT_TRUE(gt > this->v1);
    gt = this->v1;
    gt -= Type(100);
    EXPECT_FALSE(gt > this->v1);
}
References PREPARE_TEST.
TYPED_TEST() [16/49]
TYPED_TEST (VectorTests , GreaterThanOrEqualOperator)
Definition at line 515 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Greater than or equal
    Vec gte = this->v1;
    EXPECT_TRUE(gte >= this->v1);
    gte += Type(100);
    EXPECT_TRUE(gte >= this->v1);
    gte = this->v1;
    gte -= Type(100);
    EXPECT_FALSE(gte >= this->v1);
}
References PREPARE_TEST.
TYPED_TEST() [17/49]
TYPED_TEST (VectorTests , InequalityOperator)
Definition at line 461 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Inequality
    Vec rightNeq = this->v1;
    Vec leftNeq = this->v2;
    EXPECT_TRUE(leftNeq != rightNeq);
    Vec rightNeq2 = this->v2;
    Vec leftNeq2 = this->v2;
    EXPECT_FALSE(leftNeq2 != rightNeq2);
}
References PREPARE_TEST.
TYPED_TEST() [18/49]
TYPED_TEST (VectorTests , InitializerListAssignment)
Definition at line 229 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Initializer list assignment
    if constexpr (N == 2) {
        Vec initListAssign;
        initListAssign = {generateNextValue1<Type>(0), generateNextValue1<Type>(1)};
        EXPECT_EQ_VEC(initListAssign, this->v1);
    }
    if constexpr (N == 3) {
        Vec initListAssign;
        initListAssign = {
            generateNextValue1<Type>(0), generateNextValue1<Type>(1),
            generateNextValue1<Type>(2)
        };
        EXPECT_EQ_VEC(initListAssign, this->v1);
    }
    if constexpr (N == 4) {
        Vec initListAssign;
        initListAssign =
        {
            generateNextValue1<Type>(0), generateNextValue1<Type>(1), generateNextValue1<Type>(2),
            generateNextValue1<Type>(3)
        };
        EXPECT_EQ_VEC(initListAssign, this->v1);
    } // Enough with the initializers, it could go on forever
}
References EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [19/49]
TYPED_TEST (VectorTests , LessThanOperator)
Definition at line 473 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Less than
    Vec lt = this->v1;
    EXPECT_FALSE(lt < this->v1);
    lt -= Type(100);
    EXPECT_TRUE(lt < this->v1);
    lt = this->v1;
    lt += Type(100);
    EXPECT_FALSE(lt < this->v1);
}
References PREPARE_TEST.
TYPED_TEST() [20/49]
TYPED_TEST (VectorTests , LessThanOrEqualOperator)
Definition at line 487 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Less than or equal
    Vec lte = this->v1;
    EXPECT_TRUE(lte <= this->v1);
    lte -= Type(100);
    EXPECT_TRUE(lte <= this->v1);
    lte = this->v1;
    lte += Type(100);
    EXPECT_FALSE(lte <= this->v1);
}
References PREPARE_TEST.
TYPED_TEST() [21/49]
TYPED_TEST (VectorTests , MoveAssignment)
Definition at line 208 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Move assignment
    Vec moveAssign;
    Vec moveAssign2;
    initVector1(moveAssign);
    moveAssign2 = std::move(moveAssign);
    EXPECT_EQ_VEC(moveAssign2, this->v1);
}
References EXPECT_EQ_VEC, initVector1(), and PREPARE_TEST.
TYPED_TEST() [22/49]
TYPED_TEST (VectorTests , MultiplicationAssignment)
Definition at line 303 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Multiplication assignment with another vector
    Vec mulAssign = this->v1;
    mulAssign *= this->v1;
    Vec expectMulAssign;
    GLESC::Math::VectorAlgorithms::vectorMul(this->v1.data, this->v1.data, expectMulAssign.data);
    EXPECT_EQ_VEC(mulAssign, expectMulAssign);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorMul().
TYPED_TEST() [23/49]
TYPED_TEST (VectorTests , MultiplicationAssignmentScalar)
Definition at line 313 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Multiplication assignment with a scalar
    Vec mulAssignScalar = this->v1;
    const Type scalarMul = Type(10);
    mulAssignScalar *= scalarMul;
    Vec expectMulAssignScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarMul(this->v1.data, scalarMul, expectMulAssignScalar.data);
    EXPECT_EQ_VEC(mulAssignScalar, expectMulAssignScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [24/49]
TYPED_TEST (VectorTests , MultiplicationOperators)
Definition at line 404 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Multiplication with another vector
    Vec mul;
    mul = this->v1 * this->v2;
    Vec expectMul;
    GLESC::Math::VectorAlgorithms::vectorMul(this->v1.data, this->v2.data, expectMul.data);
    EXPECT_EQ_VEC(mul, expectMul);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorMul().
TYPED_TEST() [25/49]
TYPED_TEST (VectorTests , MultiplicationScalarOperators)
Definition at line 414 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Multiplication with a scalar
    Vec mulScalar;
    const Type scalarMul = Type(10);
    mulScalar = this->v1 * scalarMul;
    Vec expectMulScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarMul(this->v1.data, scalarMul, expectMulScalar.data);
    EXPECT_EQ_VEC(mulScalar, expectMulScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
TYPED_TEST() [26/49]
TYPED_TEST (VectorTests , SubArithmeticOperator)
Definition at line 373 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Subtraction with another vector
    Vec sub;
    sub = this->v1 - this->v2;
    Vec expectSub;
    GLESC::Math::VectorAlgorithms::vectorSub(this->v1.data, this->v2.data, expectSub.data);
    EXPECT_EQ_VEC(sub, expectSub);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorSub().
TYPED_TEST() [27/49]
TYPED_TEST (VectorTests , SubScalarAritmeticOperator)
Definition at line 383 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Subtraction with a scalar
    Vec subScalar;
    const Type scalarSub = Type(10);
    subScalar = this->v1 - scalarSub;
    Vec expectSubScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarSub(this->v1.data, scalarSub, expectSubScalar.data);
    EXPECT_EQ_VEC(subScalar, expectSubScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarSub().
TYPED_TEST() [28/49]
TYPED_TEST (VectorTests , SubtractionAssignment)
Definition at line 282 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Subtraction assignment with another vector
    Vec subAssign = this->v1;
    subAssign -= this->v2;
    Vec expectSubAssign;
    GLESC::Math::VectorAlgorithms::vectorSub(this->v1.data, this->v2.data, expectSubAssign.data);
    EXPECT_EQ_VEC(subAssign, expectSubAssign);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorSub().
TYPED_TEST() [29/49]
TYPED_TEST (VectorTests , SubtractionAssignmentScalar)
Definition at line 292 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Subtraction assignment with a scalar
    Vec subAssignScalar = this->v1;
    const Type scalarSub = Type(10);
    subAssignScalar -= scalarSub;
    Vec expectSubAssignScalar;
    GLESC::Math::VectorAlgorithms::vectorScalarSub(this->v1.data, scalarSub, expectSubAssignScalar.data);
    EXPECT_EQ_VEC(subAssignScalar, expectSubAssignScalar);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorScalarSub().
TYPED_TEST() [30/49]
TYPED_TEST (VectorTests , UnaryMinusOperators)
Definition at line 394 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Unary minus
    Vec unaryMinus;
    unaryMinus = -this->v1;
    Vec expectUnaryMinus;
    GLESC::Math::VectorAlgorithms::vectorNegate(this->v1.data, expectUnaryMinus.data);
    EXPECT_EQ_VEC(unaryMinus, expectUnaryMinus);
}
References EXPECT_EQ_VEC, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorNegate().
TYPED_TEST() [31/49]
TYPED_TEST (VectorTests , VectorClamp)
Definition at line 545 of file VectorTests.cpp.
{
    PREPARE_TEST();
    TEST_SECTION("Vector clamp with values");
    Type min = Type(1);
    Type max = Type(5);
    this->result = Vec(7);
    this->result = this->result.clamp(min, max);
    this->expected = Vec(7);
    GLESC::Math::VectorAlgorithms::clampWithValues(this->expected.data, min, max, this->expected.data);
    EXPECT_EQ_VEC(this->result, this->expected);
    TEST_SECTION("Vector clamp with vector");
    Vec minVec;
    for (size_t i = 0; i < N; ++i) {
        minVec[i] = Type(i + 1);
    }
    Vec maxVec;
    for (size_t i = 0; i < N; ++i) {
        maxVec[i] = Type(i + 5);
    }
    this->result = this->v1;
    this->result.clamp(minVec, maxVec);
    this->expected = this->v1;
    GLESC::Math::VectorAlgorithms::clampWithVectors(this->expected.data, minVec.data, maxVec.data, this->expected.data);
    EXPECT_EQ_VEC(this->result, this->expected);
}
References GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::VectorAlgorithms::clampWithVectors(), EXPECT_EQ_VEC, PREPARE_TEST, and TEST_SECTION.
TYPED_TEST() [32/49]
TYPED_TEST (VectorTests , VectorCollinearityOperator)
Definition at line 797 of file VectorTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 3) {
        // Two vectors are always collinear
        std::vector<Vec> collinearVecs = {this->v2};
        EXPECT_TRUE(this->v1.isCollinear(collinearVecs));
        // Collinear vectors with a scalar multiple
        collinearVecs.clear();
        collinearVecs.push_back(this->v1 * Type(10));
        collinearVecs.push_back(this->v1 * Type(-20));
        collinearVecs.push_back(this->v1 * Type(0.33));
        EXPECT_TRUE(this->v1.isCollinear(collinearVecs));
        // Two equal, one different, they are collinear
        Vec nonCollinear = this->v1;
        nonCollinear[0] += Type(1); // Make it different
        std::vector<Vec> nonCollinearVecs = {nonCollinear, this->v1};
        EXPECT_TRUE(this->v1.isCollinear(nonCollinearVecs));
        // 3 vectors, all different, not collinear
        Vec nonCollinear2 = this->v1;
        Vec nonCollinear3 = this->v1;
        nonCollinear2[0] += Type(1);
        nonCollinear3[0] += Type(2);
        nonCollinear3[1] += Type(6);
        std::vector<Vec> nonCollinearVecs2 = {nonCollinear2, nonCollinear3};
        EXPECT_FALSE(this->v1.isCollinear(nonCollinearVecs2));
    }
}
References PREPARE_TEST.
TYPED_TEST() [33/49]
TYPED_TEST (VectorTests , VectorCross)
Definition at line 634 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Cross
    if constexpr (N == 3) {
        // Cross product is only defined for 3D vectors
        Vec cross;
        initVector1(cross);
        Vec cross2;
        initVector2(cross2);
        Vec crossResult = cross.cross(cross2);
        Vec expectCrossResult;
        GLESC::Math::VectorAlgorithms::crossProduct(cross.data, cross2.data, expectCrossResult.data);
        EXPECT_EQ_VEC(crossResult, expectCrossResult);
    }
}
References GLESC::Math::VectorAlgorithms::crossProduct(), EXPECT_EQ_VEC, initVector1(), initVector2(), and PREPARE_TEST.
TYPED_TEST() [34/49]
TYPED_TEST (VectorTests , VectorDehomogenous)
Definition at line 737 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Test dehomogenizing a vector
    VectorT<Type, N - 1> dehomogenized;
    dehomogenized = this->v1.dehomogenize();
    VectorT<Type, N - 1> expectedDehomogenized;
    GLESC::Math::VectorAlgorithms::dehomogenize(this->v1.data, expectedDehomogenized.data);
    EXPECT_EQ_VEC(dehomogenized, expectedDehomogenized);
}
References GLESC::Math::VectorAlgorithms::dehomogenize(), EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [35/49]
TYPED_TEST (VectorTests , VectorDistance)
Definition at line 626 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Distance
    Type distance = this->v1.distance(this->v2);
    Type expectDistance = GLESC::Math::VectorAlgorithms::distance(this->v1.data, this->v2.data);
}
References GLESC::Math::VectorAlgorithms::distance(), and PREPARE_TEST.
TYPED_TEST() [36/49]
TYPED_TEST (VectorTests , VectorDot)
Definition at line 617 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Dot product
    Type dot = this->v1.dot(this->v2);
    Type expectDot = GLESC::Math::VectorAlgorithms::dotProduct(this->v1.data, this->v2.data);
    EXPECT_EQ_CUSTOM(dot, expectDot);
}
References GLESC::Math::VectorAlgorithms::dotProduct(), EXPECT_EQ_CUSTOM, and PREPARE_TEST.
TYPED_TEST() [37/49]
TYPED_TEST (VectorTests , VectorGetOrthogonal)
Definition at line 686 of file VectorTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 2 || N == 3 || N == 4) {
        // Orthogonal
        Vec orthogonal;
        initVector1(orthogonal);
        Vec orthogonalResult = orthogonal.getOrthogonal();
        bool isOrthogonal = orthogonalResult.dot(orthogonal) == Type();
        EXPECT_TRUE(isOrthogonal);
    }
}
References initVector1(), and PREPARE_TEST.
TYPED_TEST() [38/49]
TYPED_TEST (VectorTests , VectorHomogenize)
Definition at line 726 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Test homogenizing a vector
    VectorT<Type, N - 1> toHomogenize;
    initVector1(toHomogenize);
    Vec homogenized = toHomogenize.homogenize();
    Vec expectedHomogenized;
    GLESC::Math::VectorAlgorithms::homogenize(toHomogenize.data, expectedHomogenized.data);
    EXPECT_EQ_VEC(homogenized, expectedHomogenized);
}
References EXPECT_EQ_VEC, GLESC::Math::VectorAlgorithms::homogenize(), initVector1(), and PREPARE_TEST.
TYPED_TEST() [39/49]
TYPED_TEST (VectorTests , VectorIsHomogenous)
Definition at line 714 of file VectorTests.cpp.
{
    PREPARE_TEST();
    VectorT<Type, N - 1> dehomogenized;
    GLESC::Math::VectorAlgorithms::dehomogenize(this->v1.data, dehomogenized.data);
    EXPECT_FALSE(dehomogenized.isHomogeneous());
    VectorT<Type, N + 1> homogenized;
    GLESC::Math::VectorAlgorithms::homogenize(this->v1.data, homogenized.data);
    EXPECT_TRUE(homogenized.isHomogeneous());
}
References GLESC::Math::Vector< Type, N >::data, GLESC::Math::VectorAlgorithms::dehomogenize(), GLESC::Math::VectorAlgorithms::homogenize(), GLESC::Math::Vector< Type, N >::isHomogeneous(), and PREPARE_TEST.
TYPED_TEST() [40/49]
TYPED_TEST (VectorTests , VectorIsOrthogonal)
Definition at line 651 of file VectorTests.cpp.
{
    PREPARE_TEST();
    if constexpr (N == 2 || N == 3 || N == 4) {
        // Orthogonal vectors for any dimension N
        Vec orthogonalVec1;
        GLESC::Math::VectorAlgorithms::getOrthogonal(this->v1.data, orthogonalVec1.data);
        // Check if orthogonal
        EXPECT_TRUE(this->v1.isOrthogonal(orthogonalVec1));
    }
}
References GLESC::Math::VectorAlgorithms::getOrthogonal(), and PREPARE_TEST.
TYPED_TEST() [41/49]
TYPED_TEST (VectorTests , VectorIsParallel)
Definition at line 662 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Parallel vectors for any dimension N
    Vec parallelVec1, parallelVec2;
    for (size_t i = 0; i < N; ++i) {
        parallelVec1.set(i, Type(i + 1));
        parallelVec2.set(i, Type((i + 1) * 2)); // Scalar multiple of parallelVec1
    }
    // Check if parallel (one vector is a scalar multiple of the other)
    bool isParallel = true;
    const Type scalar = parallelVec2.get(0) / parallelVec1.get(0);
    for (size_t i = 1; i < N; ++i) {
        if (parallelVec2.get(i) / parallelVec1.get(i) != scalar) {
            isParallel = false;
            break;
        }
    }
    EXPECT_TRUE(isParallel);
}
References PREPARE_TEST.
TYPED_TEST() [42/49]
TYPED_TEST (VectorTests , VectorIsZero)
Definition at line 533 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Zero vector
    Vec zero;
    GLESC::Math::VectorAlgorithms::vectorFill(zero.data, Type());
    EXPECT_TRUE(zero.isZero());
    // Non-zero vector
    Vec nonZero = this->v1;
    EXPECT_FALSE(nonZero.isZero());
}
References PREPARE_TEST, and GLESC::Math::VectorAlgorithms::vectorFill().
TYPED_TEST() [43/49]
TYPED_TEST (VectorTests , VectorLenght)
Definition at line 699 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Length
    Type length = this->v1.length();
    Type expectLength = GLESC::Math::VectorAlgorithms::length(this->v1.data);
    EXPECT_EQ_CUSTOM(length, expectLength);
    // Length squared
    Type lengthSquared = this->v1.lengthSquared();
    Type expectLengthSquared = GLESC::Math::VectorAlgorithms::lengthSquared(this->v1.data);
    EXPECT_EQ_CUSTOM(lengthSquared, expectLengthSquared);
}
References EXPECT_EQ_CUSTOM, GLESC::Math::VectorAlgorithms::length(), GLESC::Math::VectorAlgorithms::lengthSquared(), and PREPARE_TEST.
TYPED_TEST() [44/49]
TYPED_TEST (VectorTests , VectorMultiple)
Definition at line 770 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Vectors are the same
    Vec multiple;
    initVector1(multiple);
    Vec multiple2;
    initVector2(multiple2);
    EXPECT_TRUE(multiple.isMultipleOf(multiple)); // A vector is always a multiple of itself
    // Vectors are multiple
    // Create a vector that is a known multiple of the initial vector
    Vec multiple3;
    const Type scalarMultiple = Type(2); // Example scalar multiple
    for (size_t i = 0; i < N; ++i) {
        multiple3.set(i, this->v1.get(i) * scalarMultiple);
    }
    EXPECT_TRUE(multiple3.isMultipleOf(this->v1));
    // Vectors are not multiple
    Vec notMultiple;
    initVector1(notMultiple);
    notMultiple.set(0, notMultiple.get(0) + Type(1)); // This change makes it not a multiple of v1
    EXPECT_FALSE(notMultiple.isMultipleOf(this->v1));
}
References initVector1(), initVector2(), and PREPARE_TEST.
TYPED_TEST() [45/49]
TYPED_TEST (VectorTests , VectorNormalize)
Definition at line 748 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Normalize
    Vec normalize;
    initVector1(normalize);
    normalize = normalize.normalize();
    Type normalizeLength = normalize.length();
    if constexpr (!std::is_integral_v<Type>)
        EXPECT_EQ_CUSTOM(normalizeLength, Type(1));
    else // If it's integral, it should be 0 due to truncation
        EXPECT_EQ_CUSTOM(normalizeLength, Type(0));
}
References EXPECT_EQ_CUSTOM, initVector1(), and PREPARE_TEST.
TYPED_TEST() [46/49]
TYPED_TEST (VectorTests , VectorSize)
Definition at line 763 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Size
    EXPECT_EQ_CUSTOM(this->v1.size(), N);
}
References EXPECT_EQ_CUSTOM, and PREPARE_TEST.
TYPED_TEST() [47/49]
TYPED_TEST (VectorTests , VectorSum)
Definition at line 579 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Sum
    Type sumVec = this->v1.sum();
    Type expectSumVec = GLESC::Math::VectorAlgorithms::sum(this->v1.data);
    EXPECT_EQ_CUSTOM(sumVec, expectSumVec);
}
References EXPECT_EQ_CUSTOM, PREPARE_TEST, and GLESC::Math::VectorAlgorithms::sum().
TYPED_TEST() [48/49]
TYPED_TEST (VectorTests , VectorSwap)
Definition at line 606 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // Swap
    Vec swap = this->v1;
    Vec swap2 = this->v2;
    swap.swap(swap2);
    EXPECT_EQ_VEC(swap, this->v2);
    EXPECT_EQ_VEC(swap2, this->v1);
}
References EXPECT_EQ_VEC, and PREPARE_TEST.
TYPED_TEST() [49/49]
TYPED_TEST (VectorTests , VectorToString)
Definition at line 827 of file VectorTests.cpp.
{
    PREPARE_TEST();
    // To String
    std::string toString = this->v1.toString();
    std::string expectToString = "[";
    for (size_t i = 0; i < N; ++i) {
        expectToString += std::to_string(generateNextValue1<Type>(i));
        if (i != N - 1)
            expectToString += ", ";
    }
    expectToString += "]";
    EXPECT_EQ(toString, expectToString);
}
References PREPARE_TEST.
TYPED_TEST_SUITE()
TYPED_TEST_SUITE (VectorTests , VectorTypes)