GLESC: GLESC::HUD::DebugEntityData Class Reference
GLESC::HUD::DebugEntityData Class Reference
Class to encapsulate the logic of the debug entity data HUD.
#include <DebugEntityDataHUD.h>
Public Member Functions
DebugEntityData ()
Public Member Functions inherited from GLESC::InGameWindow
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Private Member Functions
void windowContent (float timeOfFrame) override
Additional Inherited Members
Protected Member Functions inherited from GLESC::InGameWindow
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
Protected Attributes inherited from GLESC::InGameWindow
bool isVisible = true
Detailed Description
Class to encapsulate the logic of the debug entity data HUD.
The debug entity data HUD is a window that displays debug information. Allows visualizing the data that is associated with a selected entity.
Definition at line 21 of file DebugEntityDataHUD.h.
Constructor & Destructor Documentation
DebugEntityData()
DebugEntityData::DebugEntityData ()
Definition at line 11 of file DebugEntityDataHUD.cpp.
{
    this->setTitle("Entity Data");
    this->setSizeFraction({0.2f, 1.0f});
    this->setMinSize({300.0f, 0.0f});
    isVisible = true;
    this->setLayoutPosition(LayoutPos::CenterRight);
    this->setCenter(WindowCenter::CenterRight);
    this->addFlag(ImGuiWindowFlags_NoResize);
    this->addFlag(ImGuiWindowFlags_NoMove);
    this->addFlag(ImGuiWindowFlags_NoCollapse);
    this->addFlag(ImGuiWindowFlags_NoTitleBar);
    this->addFlag(ImGuiWindowFlags_NoSavedSettings);
    this->addFlag(ImGuiWindowFlags_NoBringToFrontOnFocus);
    this->addFlag(ImGuiWindowFlags_NoFocusOnAppearing);
    this->addFlag(ImGuiWindowFlags_AlwaysAutoResize);
}
References GLESC::InGameWindow::addFlag(), GLESC::CenterRight, GLESC::isIterable_v, GLESC::InGameWindow::isVisible, GLESC::InGameWindow::setCenter(), GLESC::InGameWindow::setLayoutPosition(), GLESC::InGameWindow::setMinSize(), GLESC::InGameWindow::setSizeFraction(), and GLESC::InGameWindow::setTitle().
Member Function Documentation
windowContent()
void DebugEntityData::windowContent (float timeOfFrame) override private virtual
Implements GLESC::InGameWindow.
Definition at line 248 of file DebugEntityDataHUD.cpp.
{
    EntityStatsManager::EntityData& data = EntityStatsManager::getEntityData();
    // Set a window title with the entity's name
    ImGui::Text("Entity: %s", data.name.c_str());
    ImGui::Separator();
    ImGui::PushFont(HudLookAndFeel::get().getFont(HudLookAndFeel::get().getDefaultFont(), 14.0f));
    for (const EntityStatsManager::ComponentData& stat : data.components) {
        // Dynamically calculate the needed height for each child window based on the number of items
        float childHeight = 15 * ImGui::GetTextLineHeightWithSpacing();
        // Begin a child window with a specific height to enforce stacking
        ImGui::BeginChild(stat.name.c_str(), ImVec2(-1, childHeight), true);
        // Set a title for the component inside its frame
        ImGui::Text("%s", stat.name.c_str());
        ImGui::Separator();
        // Display each attribute of the component
        for (EntityStatsManager::Value& value : *stat.values) {
            if (value.isString) {
                ImGui::Text(value.name.c_str());
                ImGui::Text(value.stringData.c_str());
                continue;
            }
            // While visible the panel of the data, the value is dirty as we want to update it
            if (value.valueDirty != nullptr)
                *value.valueDirty = true;
            putInputForType(value.type, value);
        }
        for (const EntityStatsManager::Value& value : stat.getUpdatedValues()) {
            ImGui::Text(value.name.c_str());
            ImGui::Text(value.stringData.c_str());
        }
        ImGui::EndChild(); // End of component frame
        ImGui::Spacing(); // Add some space between components for better readability
    }
    ImGui::PopFont();
}
References EntityStatsManager::EntityData::components, HudLookAndFeel::get(), EntityStatsManager::getEntityData(), GLESC::isIterable_v, EntityStatsManager::EntityData::name, and putInputForType().
The documentation for this class was generated from the following files:
DebugEntityDataHUD.h
DebugEntityDataHUD.cpp