GLESC: GLESC::EngineCamera Class Reference
GLESC::EngineCamera Class Reference
#include <EngineCamera.h>
Public Member Functions
EngineCamera (ECS::EntityFactory &entityFactory, Input::InputManager &inputManager, WindowManager &windowManager)
~EngineCamera ()=default
ECS::Entity & getEntity ()
void setEngineHuds (HUD::EngineHUDManager *engineHuds)
void setForce (float speed)
void setSensitivity (float sensitivity)
Private Member Functions
void accelerate ()
Accelerates the camera (increases the speed by a factor of 2)
void decelerate ()
Decelerates the camera (decreases the speed by a factor of 2)
void moveBackward ()
Moves the camera backwards.
void moveDown ()
Moves the camera downwards.
void moveForward ()
Moves the camera forwards.
void moveLeft ()
Moves the camera to the left.
void moveRight ()
Moves the camera to the right.
void moveUp ()
Moves the camera upwards.
void rotate (const MousePosition &deltaMouse)
Rotates the camera based on the mouse movement.
void setupCamera ()
Prepares the camera entity with its components and it's initial values.
Private Attributes
ECS::Entity camera
The camera entity.
float cameraPitchConstraint = 45.0f
The camera pitch constraint is 45 degrees.
Render::Intensity< float > cameraSensitivity {1.0f}
The camera sensitivity is 1.0f, is the sensitivity of the mouse movement.
float cameraSpeed = 25.f
The camera speed is 25 units per second.
bool debugHUDActive = false
HUD::EngineHUDManager * engineHuds {}
A reference to the engine huds, the camer allows hide or show them with the input.
ECS::EntityFactory & entityFactory
Input::InputManager & inputManager
WindowManager & windowManager
Static Private Attributes
static constexpr bool defaultCameraAffectedByGravity = false
The camera is not affected by gravity.
static constexpr float defaultCameraAirFriction = 0.1f
Camera friction value is 0.1f, makes the camera move like swimming through air as 0.1 is a relatively big value for a friction.
static constexpr float defaultFarPlane = 1000.f
The far plane is at 1000 units, far enough to see the whole scene.
static constexpr float defaultFov = 45.f
The field of view is 45 degrees.
static constexpr float defaultNearPlane = 0.1f
The near plane is at 0.1 units.
Friends
class GLESC::Engine
Detailed Description
Definition at line 20 of file EngineCamera.h.
Constructor & Destructor Documentation
EngineCamera()
GLESC::EngineCamera::EngineCamera (ECS::EntityFactory & entityFactory, Input::InputManager & inputManager, WindowManager & windowManager) inline
Definition at line 24 of file EngineCamera.h.
                                                   : entityFactory(entityFactory),
                                                     inputManager(inputManager),
                                                     windowManager(windowManager),
                                                     camera(entityFactory.createEntity(
                                                         "camera", {EntityType::Engine})) {
        }
References GLESC::Engine.
~EngineCamera()
GLESC::EngineCamera::~EngineCamera () default
Member Function Documentation
accelerate()
void EngineCamera::accelerate () private
Accelerates the camera (increases the speed by a factor of 2)
Definition at line 40 of file EngineCamera.cpp.
{
    cameraSpeed *= 2;
}
References cameraSpeed.
Referenced by setupCamera().
decelerate()
void EngineCamera::decelerate () private
Decelerates the camera (decreases the speed by a factor of 2)
Definition at line 44 of file EngineCamera.cpp.
{
    cameraSpeed /= 2;
}
References cameraSpeed.
Referenced by setupCamera().
getEntity()
ECS::Entity & GLESC::EngineCamera::getEntity () inline
Definition at line 38 of file EngineCamera.h.
{ return camera; }
References camera.
Referenced by GLESC::Engine::update().
moveBackward()
void EngineCamera::moveBackward () private
Moves the camera backwards.
Note
Camera movement is done with inverse directions, because camera looks at the opposite direction of its forward vector
Definition at line 10 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        camera.getComponent<ECS::TransformComponent>().transform.forward(), cameraSpeed);
}
References camera, cameraSpeed, GLESC::Transform::Transform::forward(), GLESC::ECS::Entity::getComponent(), and GLESC::ECS::TransformComponent::transform.
Referenced by setupCamera().
moveDown()
void EngineCamera::moveDown () private
Moves the camera downwards.
Definition at line 35 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        -Transform::Transform::worldUp, cameraSpeed);
}
References camera, cameraSpeed, GLESC::ECS::Entity::getComponent(), and GLESC::Transform::Transform::worldUp.
Referenced by setupCamera().
moveForward()
void EngineCamera::moveForward () private
Moves the camera forwards.
Note
Camera movement is done with inverse directions, because camera looks at the opposite direction of its forward vector
Definition at line 15 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        camera.getComponent<ECS::TransformComponent>().transform.forward(), -cameraSpeed);
}
References camera, cameraSpeed, GLESC::Transform::Transform::forward(), GLESC::ECS::Entity::getComponent(), and GLESC::ECS::TransformComponent::transform.
Referenced by setupCamera().
moveLeft()
void EngineCamera::moveLeft () private
Moves the camera to the left.
Note
Camera movement is done with inverse directions, because camera looks at the opposite direction of its forward vector
Definition at line 20 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        camera.getComponent<ECS::TransformComponent>().transform.right(), cameraSpeed);
}
References camera, cameraSpeed, GLESC::ECS::Entity::getComponent(), GLESC::Transform::Transform::right(), and GLESC::ECS::TransformComponent::transform.
Referenced by setupCamera().
moveRight()
void EngineCamera::moveRight () private
Moves the camera to the right.
Note
Camera movement is done with inverse directions, because camera looks at the opposite direction of its forward vector
Definition at line 25 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        -camera.getComponent<ECS::TransformComponent>().transform.right(), cameraSpeed);
}
References camera, cameraSpeed, GLESC::ECS::Entity::getComponent(), GLESC::Transform::Transform::right(), and GLESC::ECS::TransformComponent::transform.
Referenced by setupCamera().
moveUp()
void EngineCamera::moveUp () private
Moves the camera upwards.
Definition at line 30 of file EngineCamera.cpp.
{
    camera.getComponent<ECS::PhysicsComponent>().physics.addDirectionalForce(
        Transform::Transform::worldUp, cameraSpeed);
}
References camera, cameraSpeed, GLESC::ECS::Entity::getComponent(), and GLESC::Transform::Transform::worldUp.
Referenced by setupCamera().
rotate()
void EngineCamera::rotate (const MousePosition & deltaMouse) private
Rotates the camera based on the mouse movement.
It adjusts the pitch and yaw of the camera based on the mouse movement The pitch has a constraint of 45 degrees.
Parameters
deltaMouse The mouse movement
Definition at line 49 of file EngineCamera.cpp.
{
    if (!inputManager.isMouseRelative()) return;
    auto& transformComp = camera.getComponent<ECS::TransformComponent>().transform;
    float cameraSensitivityValue = cameraSensitivity.get();
    // Adjust the pitch based on mouse Y movement (up/down)
    float mouseAdditionPitch = -deltaMouse.getY() * cameraSensitivityValue;
    float nextMousePitch = transformComp.getRotation().getX() + mouseAdditionPitch;
    // Only apply pitch rotation if it is within the constraints
    if (nextMousePitch < cameraPitchConstraint &&
        nextMousePitch > -cameraPitchConstraint) {
        transformComp.setRotation(Transform::RotationAxis::Pitch, nextMousePitch);
    }
    // Adjust the yaw based on mouse X movement (left/right)
    float mouseAdditionYaw = -deltaMouse.getX() * cameraSensitivityValue;
    transformComp.addRotation(Transform::RotationAxis::Yaw, mouseAdditionYaw);
}
References camera, cameraPitchConstraint, cameraSensitivity, GLESC::Render::Intensity< IntensityType >::get(), GLESC::ECS::Entity::getComponent(), inputManager, GLESC::isIterable_v, GLESC::Input::InputManager::isMouseRelative(), GLESC::Transform::Pitch, and GLESC::Transform::Yaw.
Referenced by setupCamera().
setEngineHuds()
void GLESC::EngineCamera::setEngineHuds (HUD::EngineHUDManager * engineHuds) inline
Definition at line 35 of file EngineCamera.h.
{
            this->engineHuds = engineHuds;
        }
References engineHuds.
Referenced by GLESC::Engine::Engine().
setForce()
void GLESC::EngineCamera::setForce (float speed) inline
Definition at line 39 of file EngineCamera.h.
{ cameraSpeed = speed; }
References cameraSpeed, and GLESC::isIterable_v.
setSensitivity()
void GLESC::EngineCamera::setSensitivity (float sensitivity) inline
Definition at line 40 of file EngineCamera.h.
{ cameraSensitivity.set(sensitivity); }
References cameraSensitivity, GLESC::isIterable_v, and GLESC::Render::Intensity< IntensityType >::set().
setupCamera()
void EngineCamera::setupCamera () private
Prepares the camera entity with its components and it's initial values.
Definition at line 72 of file EngineCamera.cpp.
{
    camera.addComponent<ECS::CameraComponent>()
          .addComponent<ECS::TransformComponent>()
          .addComponent<ECS::InputComponent>()
          .addComponent<ECS::PhysicsComponent>();
    camera.getComponent<ECS::PhysicsComponent>().physics.setAirFriction(defaultCameraAirFriction);
    camera.getComponent<ECS::PhysicsComponent>().physics.setAffectedByGravity(defaultCameraAffectedByGravity);
    camera.getComponent<ECS::CameraComponent>().perspective.setFarPlane(defaultFarPlane);
    camera.getComponent<ECS::CameraComponent>().perspective.setNearPlane(defaultNearPlane);
    camera.getComponent<ECS::CameraComponent>().perspective.setFovDegrees(defaultFov);
    camera.getComponent<ECS::CameraComponent>().perspective.setViewWidth(
        static_cast<float>(windowManager.getSize().width));
    camera.getComponent<ECS::CameraComponent>().perspective.
           setViewHeight(static_cast<float>(windowManager.getSize().height));
    Input::KeyCommand moveForwardCommand = Input::KeyCommand([&] { moveForward(); });
    Input::KeyCommand moveBackwardCommand = Input::KeyCommand([&] { moveBackward(); });
    Input::KeyCommand moveLeftCommand = Input::KeyCommand([&] { moveLeft(); });
    Input::KeyCommand moveRightCommand = Input::KeyCommand([&] { moveRight(); });
    Input::KeyCommand moveUpCommand = Input::KeyCommand([&] { moveUp(); });
    Input::KeyCommand moveDownCommand = Input::KeyCommand([&] { moveDown(); });
    Input::KeyCommand accelerateCommand = Input::KeyCommand([&] { accelerate(); });
    Input::KeyCommand decelerateCommand = Input::KeyCommand([&] { decelerate(); });
    Input::MouseCommand rotateCommand =
        Input::MouseCommand([&](const MousePosition& deltaMouse) { rotate(deltaMouse); });
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::W, Input::KeyAction::ONGOING_PRESSED}, moveForwardCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::S, Input::KeyAction::ONGOING_PRESSED}, moveBackwardCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::A, Input::KeyAction::ONGOING_PRESSED}, moveLeftCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::D, Input::KeyAction::ONGOING_PRESSED}, moveRightCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::SPACE, Input::KeyAction::ONGOING_PRESSED}, moveUpCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::LEFT_SHIFT, Input::KeyAction::ONGOING_PRESSED}, moveDownCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::LEFT_ALT, Input::KeyAction::ONCE_PRESSED}, accelerateCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::LEFT_ALT, Input::KeyAction::ONCE_RELEASED}, decelerateCommand);
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::ONE, Input::KeyAction::ONCE_PRESSED}, {
            [&] {
                inputManager.setMouseRelative(!inputManager.isMouseRelative());
            }
        });
    Input::KeyCommand toggleDebug = Input::KeyCommand([&] {
        D_ASSERT_NOT_NULLPTR(engineHuds, "Engine HUDs must not be null");
        debugHUDActive = !debugHUDActive;
        engineHuds->toggle();
        inputManager.setMouseRelative(debugHUDActive);
    });
    camera.getComponent<ECS::InputComponent>().input.subscribeKey(
        {Input::Key::LEFT_CTRL, Input::KeyAction::ONCE_PRESSED}, toggleDebug);
    camera.getComponent<ECS::InputComponent>().input.setMouseCommand(rotateCommand);
}
References accelerate(), GLESC::ECS::Entity::addComponent(), camera, decelerate(), defaultCameraAffectedByGravity, defaultCameraAirFriction, defaultFarPlane, defaultFov, defaultNearPlane, GLESC::ECS::Entity::getComponent(), GLESC::WindowManager::getSize(), GLESC::WindowDimensions::height, input(), GLESC::isIterable_v, moveBackward(), moveDown(), moveForward(), moveLeft(), moveRight(), moveUp(), GLESC::Input::ONGOING_PRESSED, rotate(), GLESC::Input::W, GLESC::WindowDimensions::width, and windowManager.
Referenced by GLESC::Engine::Engine().
Friends And Related Symbol Documentation
GLESC::Engine
friend class GLESC::Engine friend
Definition at line 21 of file EngineCamera.h.
Member Data Documentation
camera
ECS::Entity GLESC::EngineCamera::camera private
The camera entity.
Definition at line 134 of file EngineCamera.h.
Referenced by getEntity(), moveBackward(), moveDown(), moveForward(), moveLeft(), moveRight(), moveUp(), rotate(), and setupCamera().
cameraPitchConstraint
float GLESC::EngineCamera::cameraPitchConstraint = 45.0f private
The camera pitch constraint is 45 degrees.
Definition at line 130 of file EngineCamera.h.
Referenced by rotate().
cameraSensitivity
Render::Intensity<float> GLESC::EngineCamera::cameraSensitivity {1.0f} private
The camera sensitivity is 1.0f, is the sensitivity of the mouse movement.
Definition at line 126 of file EngineCamera.h.
{1.0f};
Referenced by rotate(), and setSensitivity().
cameraSpeed
float GLESC::EngineCamera::cameraSpeed = 25.f private
The camera speed is 25 units per second.
Definition at line 122 of file EngineCamera.h.
Referenced by accelerate(), decelerate(), moveBackward(), moveDown(), moveForward(), moveLeft(), moveRight(), moveUp(), and setForce().
debugHUDActive
bool GLESC::EngineCamera::debugHUDActive = false private
Definition at line 142 of file EngineCamera.h.
defaultCameraAffectedByGravity
constexpr bool GLESC::EngineCamera::defaultCameraAffectedByGravity = false static constexpr private
The camera is not affected by gravity.
Definition at line 117 of file EngineCamera.h.
Referenced by setupCamera().
defaultCameraAirFriction
constexpr float GLESC::EngineCamera::defaultCameraAirFriction = 0.1f static constexpr private
Camera friction value is 0.1f, makes the camera move like swimming through air as 0.1 is a relatively big value for a friction.
Definition at line 101 of file EngineCamera.h.
Referenced by setupCamera().
defaultFarPlane
constexpr float GLESC::EngineCamera::defaultFarPlane = 1000.f static constexpr private
The far plane is at 1000 units, far enough to see the whole scene.
Definition at line 105 of file EngineCamera.h.
Referenced by setupCamera().
defaultFov
constexpr float GLESC::EngineCamera::defaultFov = 45.f static constexpr private
The field of view is 45 degrees.
Definition at line 113 of file EngineCamera.h.
Referenced by setupCamera().
defaultNearPlane
constexpr float GLESC::EngineCamera::defaultNearPlane = 0.1f static constexpr private
The near plane is at 0.1 units.
Definition at line 109 of file EngineCamera.h.
Referenced by setupCamera().
engineHuds
HUD::EngineHUDManager* GLESC::EngineCamera::engineHuds {} private
A reference to the engine huds, the camer allows hide or show them with the input.
Definition at line 146 of file EngineCamera.h.
{};
Referenced by setEngineHuds().
entityFactory
ECS::EntityFactory& GLESC::EngineCamera::entityFactory private
Definition at line 137 of file EngineCamera.h.
inputManager
Input::InputManager& GLESC::EngineCamera::inputManager private
Definition at line 138 of file EngineCamera.h.
Referenced by rotate().
windowManager
WindowManager& GLESC::EngineCamera::windowManager private
Definition at line 139 of file EngineCamera.h.
Referenced by setupCamera().
The documentation for this class was generated from the following files:
EngineCamera.h
EngineCamera.cpp