GLESC: GLESC::Render::Intensity< IntensityType > Class Template Reference
GLESC::Render::Intensity< IntensityType > Class Template Reference
Intensity class, to encapsulate values between 0 and 1.
#include <RendererTypes.h>
Public Member Functions
Intensity ()=default
Intensity (const Intensity &other)=default
Intensity (Intensity &&other) noexcept=default
Intensity (IntensityType intensityParam)
~Intensity ()=default
IntensityType get () const
IntensityType & getModifiable ()
IntensityType operator* (const Intensity &other) const
IntensityType operator+ (const Intensity &other) const
IntensityType operator- (const Intensity &other) const
IntensityType operator/ (const Intensity &other) const
bool operator< (const Intensity &other) const
bool operator<= (const Intensity &other) const
Intensity & operator= (const Intensity &other)=default
Intensity & operator= (Intensity &&other) noexcept=default
bool operator== (const Intensity &other) const
bool operator> (const Intensity &other) const
void set (IntensityType intensityParam)
std::string toString () const
Private Attributes
IntensityType intensity = IntensityType(0)
Detailed Description
template<typename IntensityType>
class GLESC::Render::Intensity< IntensityType >
Intensity class, to encapsulate values between 0 and 1.
This ensures values are always between 0 and 1, as are very common in the engine. It has minimum overhead, and only validates in debug mode.
Template Parameters
IntensityType The type of the intensity (float, double, etc)
Definition at line 113 of file RendererTypes.h.
Constructor & Destructor Documentation
Intensity() [1/4]
template<typename IntensityType > GLESC::Render::Intensity< IntensityType >::Intensity () default
Intensity() [2/4]
template<typename IntensityType > GLESC::Render::Intensity< IntensityType >::Intensity (const Intensity< IntensityType > & other) default
Intensity() [3/4]
template<typename IntensityType > GLESC::Render::Intensity< IntensityType >::Intensity (IntensityType intensityParam) inline explicit
Definition at line 119 of file RendererTypes.h.
{
            this->set(intensityParam);
        }
References GLESC::Render::Intensity< IntensityType >::set().
Intensity() [4/4]
template<typename IntensityType > GLESC::Render::Intensity< IntensityType >::Intensity (Intensity< IntensityType > && other) default noexcept
~Intensity()
template<typename IntensityType > GLESC::Render::Intensity< IntensityType >::~Intensity () default
Member Function Documentation
get()
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::get () const inline
Definition at line 162 of file RendererTypes.h.
{
            return intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity.
Referenced by GLESC::Render::Fog::getDensity(), GLESC::Render::Material::getDiffuseIntensity(), GLESC::Render::Material::getEmissionIntensity(), GLESC::Render::GlobalSun::getIntensity(), GLESC::Render::LightPoint::getIntensity(), GLESC::Render::Material::getShininess(), GLESC::Render::Material::getSpecularIntensity(), GLESC::EngineCamera::rotate(), and GLESC::Render::Fog::toString().
getModifiable()
template<typename IntensityType > IntensityType & GLESC::Render::Intensity< IntensityType >::getModifiable () inline
Definition at line 166 of file RendererTypes.h.
{
            return intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity.
Referenced by GLESC::Render::Fog::getDebuggingValues(), GLESC::Render::GlobalSun::getDebuggingValues(), GLESC::Render::LightPoint::getDebuggingValues(), and GLESC::Render::Material::getDebuggingValues().
operator*()
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::operator* (const Intensity< IntensityType > & other) const inline
Definition at line 152 of file RendererTypes.h.
{
            return intensity * other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator+()
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::operator+ (const Intensity< IntensityType > & other) const inline
Definition at line 144 of file RendererTypes.h.
{
            return intensity + other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator-()
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::operator- (const Intensity< IntensityType > & other) const inline
Definition at line 148 of file RendererTypes.h.
{
            return intensity - other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator/()
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::operator/ (const Intensity< IntensityType > & other) const inline
Definition at line 156 of file RendererTypes.h.
{
            return intensity / other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator<()
template<typename IntensityType > bool GLESC::Render::Intensity< IntensityType >::operator< (const Intensity< IntensityType > & other) const inline
Definition at line 132 of file RendererTypes.h.
{
            return intensity < other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator<=()
template<typename IntensityType > bool GLESC::Render::Intensity< IntensityType >::operator<= (const Intensity< IntensityType > & other) const inline
Definition at line 140 of file RendererTypes.h.
{
            return intensity <= other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator=() [1/2]
template<typename IntensityType > Intensity & GLESC::Render::Intensity< IntensityType >::operator= (const Intensity< IntensityType > & other) default
operator=() [2/2]
template<typename IntensityType > Intensity & GLESC::Render::Intensity< IntensityType >::operator= (Intensity< IntensityType > && other) default noexcept
operator==()
template<typename IntensityType > bool GLESC::Render::Intensity< IntensityType >::operator== (const Intensity< IntensityType > & other) const inline
Definition at line 128 of file RendererTypes.h.
{
            return intensity == other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
operator>()
template<typename IntensityType > bool GLESC::Render::Intensity< IntensityType >::operator> (const Intensity< IntensityType > & other) const inline
Definition at line 136 of file RendererTypes.h.
{
            return intensity > other.intensity;
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
set()
template<typename IntensityType > void GLESC::Render::Intensity< IntensityType >::set (IntensityType intensityParam) inline
Definition at line 170 of file RendererTypes.h.
{
            D_ASSERT_GREATER_OR_EQUAL(intensityParam, IntensityType(0), "Intensity must be greater or equal than 0");
            D_ASSERT_LESS_OR_EQUAL(intensityParam, IntensityType(1), "Intensity must be less or equal than 1");
            intensity = intensityParam;
        }
References D_ASSERT_GREATER_OR_EQUAL, D_ASSERT_LESS_OR_EQUAL, GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::isIterable_v.
Referenced by GLESC::Render::Intensity< IntensityType >::Intensity(), GLESC::Render::LightPoint::setIntensity(), and GLESC::EngineCamera::setSensitivity().
toString()
template<typename IntensityType > std::string GLESC::Render::Intensity< IntensityType >::toString () const inline
Definition at line 176 of file RendererTypes.h.
{
            return Stringer::toString(intensity);
        }
References GLESC::Render::Intensity< IntensityType >::intensity, and GLESC::Stringer::toString().
Member Data Documentation
intensity
template<typename IntensityType > IntensityType GLESC::Render::Intensity< IntensityType >::intensity = IntensityType(0) private
Definition at line 181 of file RendererTypes.h.
Referenced by GLESC::Render::Intensity< IntensityType >::get(), GLESC::Render::Intensity< IntensityType >::getModifiable(), GLESC::Render::Intensity< IntensityType >::operator*(), GLESC::Render::Intensity< IntensityType >::operator+(), GLESC::Render::Intensity< IntensityType >::operator-(), GLESC::Render::Intensity< IntensityType >::operator/(), GLESC::Render::Intensity< IntensityType >::operator<(), GLESC::Render::Intensity< IntensityType >::operator<=(), GLESC::Render::Intensity< IntensityType >::operator==(), GLESC::Render::Intensity< IntensityType >::operator>(), GLESC::Render::Intensity< IntensityType >::set(), and GLESC::Render::Intensity< IntensityType >::toString().
The documentation for this class was generated from the following file:
RendererTypes.h