GLESC: EngineComponent Class Reference
EngineComponent Class Reference abstract
Class that represents a component of the engine.
#include <EngineComponent.h>
Public Member Functions
virtual ~EngineComponent ()=default
virtual std::vector< EntityStatsManager::Value > getDebuggingValues ()
Get the debugging values of the component.
const char * getOwnerName () const
Get the owner name of the component for debugging purposes.
virtual std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues ()
Get the updated debugging values of the component.
void setOwnerName (const char *ownerName)
Set the owner name of the component for debugging purposes.
virtual std::string toString () const =0
Private Attributes
const char * entityOwnerName = nullptr
Detailed Description
Class that represents a component of the engine.
A component in the engine is a encapsulated piece of data with functionality that can be attached to an entity. It can be a camera, a physics component, a transform component, etc. This abstraction is useful for, for example, debugging purposes, where we can get all the debugging values as a list and abstrat away the implementation details of the component iterating over all the components. Also allows storing the owner name (the entity name) for debugging purposes.
Definition at line 23 of file EngineComponent.h.
Constructor & Destructor Documentation
~EngineComponent()
virtual EngineComponent::~EngineComponent () virtual default
Member Function Documentation
getDebuggingValues()
virtual std::vector< EntityStatsManager::Value > EngineComponent::getDebuggingValues () inline virtual
Get the debugging values of the component.
This function can be overriden by the derived class to return the debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented in GLESC::Physics::Collider, GLESC::Physics::Physics, and GLESC::Transform::Transform.
Definition at line 75 of file EngineComponent.h.
{
        return {};
    }
Referenced by GLESC::ECS::RenderComponent::setDebuggingValues().
getOwnerName()
const char * EngineComponent::getOwnerName () const inline
Get the owner name of the component for debugging purposes.
Having the owener associated with the component is specially useful when debugging, as it allows to know which entity the component belongs to no matter the context of debugging.
Returns
The name of the owner entity
Definition at line 45 of file EngineComponent.h.
{
        D_ASSERT_NOT_NULLPTR(entityOwnerName, "Owner name not set for EngineComponent");
        return entityOwnerName;
    }
References D_ASSERT_NOT_NULLPTR, and entityOwnerName.
Referenced by GLESC::Physics::Collider::getUpdatedDebuggingValues().
getUpdatedDebuggingValues()
virtual std::vector< EntityStatsManager::Value > EngineComponent::getUpdatedDebuggingValues () inline virtual
Get the updated debugging values of the component.
This function can be overriden by the derived class to return the updated debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented in GLESC::Physics::Collider, and GLESC::Render::Mesh< VertexT >.
Definition at line 88 of file EngineComponent.h.
{
        return {};
    }
Referenced by GLESC::ECS::PhysicsComponent::setUpdatedDebuggingValues().
setOwnerName()
void EngineComponent::setOwnerName (const char * ownerName) inline
Set the owner name of the component for debugging purposes.
Having the owener associated with the component is specially useful when debugging, as it allows to know which entity the component belongs to no matter the context of debugging.
Parameters
ownerName The name of the owner entity
Definition at line 35 of file EngineComponent.h.
{
        entityOwnerName = ownerName;
    }
References entityOwnerName.
toString()
virtual std::string EngineComponent::toString () const pure virtual
Implemented in GLESC::Physics::Collider, GLESC::Physics::Physics, GLESC::Render::Mesh< VertexT >, and GLESC::Transform::Transform.
Member Data Documentation
entityOwnerName
const char* EngineComponent::entityOwnerName = nullptr private
Definition at line 93 of file EngineComponent.h.
Referenced by getOwnerName(), and setOwnerName().
The documentation for this class was generated from the following file:
EngineComponent.h