GLESC: GLESC::GAPI::IndexBuffer Class Reference
GLESC::GAPI::IndexBuffer Class Reference
#include <IndexBuffer.h>
Public Member Functions
IndexBuffer (const std::vector< UInt > &data, Enums::BufferUsages bufferUsage=Enums::BufferUsages::DynamicDraw)
IndexBuffer (const UInt *data, Size count, Enums::BufferUsages bufferUsage=Enums::BufferUsages::DynamicDraw)
~IndexBuffer ()
void bind () const
void destroy ()
UInt getBufferID () const
Size getCount () const
void unbind () const
Private Member Functions
void destroyOnce ()
Private Attributes
Size count {0}
UInt indexBufferID {0}
bool objectAlive = true
Detailed Description
Definition at line 19 of file IndexBuffer.h.
Constructor & Destructor Documentation
IndexBuffer() [1/2]
IndexBuffer::IndexBuffer (const UInt * data, Size count, Enums::BufferUsages bufferUsage = Enums::BufferUsages::DynamicDraw)
Definition at line 15 of file IndexBuffer.cpp.
                                                                                          :
    count(count) {
    getGAPI().genBuffers(1, indexBufferID);
    this->bind();
    getGAPI().setIndexBufferData(data, count, bufferUsage);
}
References bind(), count, getGAPI(), indexBufferID, and GLESC::isIterable_v.
IndexBuffer() [2/2]
IndexBuffer::IndexBuffer (const std::vector< UInt > & data, Enums::BufferUsages bufferUsage = Enums::BufferUsages::DynamicDraw)
Definition at line 22 of file IndexBuffer.cpp.
                                                                                   :
    IndexBuffer(data.data(), static_cast<Size>(data.size()), bufferUsage) {
}
~IndexBuffer()
IndexBuffer::~IndexBuffer ()
Definition at line 26 of file IndexBuffer.cpp.
{
    destroyOnce();
}
References destroyOnce().
Member Function Documentation
bind()
void IndexBuffer::bind () const
Definition at line 35 of file IndexBuffer.cpp.
{
    getGAPI().bindBuffer(Enums::BufferTypes::Index, indexBufferID);
}
References getGAPI(), and indexBufferID.
Referenced by IndexBuffer().
destroy()
void IndexBuffer::destroy ()
Definition at line 30 of file IndexBuffer.cpp.
{
    destroyOnce();
}
References destroyOnce().
destroyOnce()
void IndexBuffer::destroyOnce () private
Definition at line 44 of file IndexBuffer.cpp.
{
    if (objectAlive) {
        std::vector<UInt> ibuData = getGAPI().getBufferDataUI(indexBufferID);
        getGAPI().deleteBuffer(indexBufferID);
        objectAlive = false;
    }
}
References getGAPI(), indexBufferID, GLESC::isIterable_v, and objectAlive.
Referenced by ~IndexBuffer(), and destroy().
getBufferID()
UInt GLESC::GAPI::IndexBuffer::getBufferID () const inline
Definition at line 31 of file IndexBuffer.h.
{ return indexBufferID; }
References indexBufferID.
getCount()
Size GLESC::GAPI::IndexBuffer::getCount () const inline
Definition at line 29 of file IndexBuffer.h.
{ return count; }
References count.
Referenced by GLESC::Render::Renderer::renderMesh().
unbind()
void IndexBuffer::unbind () const
Definition at line 39 of file IndexBuffer.cpp.
{
    getGAPI().unbindBuffer(Enums::BufferTypes::Index);
}
References getGAPI().
Member Data Documentation
count
Size GLESC::GAPI::IndexBuffer::count {0} private
Definition at line 43 of file IndexBuffer.h.
{0};
Referenced by IndexBuffer(), and getCount().
indexBufferID
UInt GLESC::GAPI::IndexBuffer::indexBufferID {0} private
Definition at line 44 of file IndexBuffer.h.
{0};
Referenced by IndexBuffer(), bind(), destroyOnce(), and getBufferID().
objectAlive
bool GLESC::GAPI::IndexBuffer::objectAlive = true private
Definition at line 42 of file IndexBuffer.h.
Referenced by destroyOnce().
The documentation for this class was generated from the following files:
IndexBuffer.h
IndexBuffer.cpp