GLESC: GLESC::Math::MatrixMixedAlgorithms Class Reference
GLESC::Math::MatrixMixedAlgorithms Class Reference
#include <MatrixMixedAlgorithms.h>
Static Public Member Functions
template<typename ModelType , typename TypePos , typename TypeRot , typename TypeScale >
static void calculateModelMatrix (const VectorData< TypePos, 3 > &position, const VectorData< TypeRot, 3 > &rotationRads, const VectorData< TypeScale, 3 > &scale, MatrixData< ModelType, 4, 4 > &model)
Calculate the model matrix from the position, rotation, and scale.
template<typename Type >
static void calculateViewMatrixEye (const VectorData< Type, 3 > &eye, const VectorData< Type, 3 > &target, const VectorData< Type, 3 > &up, MatrixData< Type, 4, 4 > &resMatrix)
template<typename TypePos , typename TypeRot , typename TypeRes >
static void calculateViewMatrixPosRot (const VectorData< TypePos, 3 > &position, const VectorData< TypeRot, 3 > &rotationRads, MatrixData< TypeRes, 4, 4 > &viewMat)
template<typename TypeDgrs , typename TypeRes >
static void getRotate3DMatrix (const VectorData< TypeDgrs, 3 > &rads, MatrixData< TypeRes, 4, 4 > &result)
Calculate the 3D rotation matrix from the rotation angles around the X, Y, and Z axes.
template<typename TypeDgrs , typename TypeRes >
static void getRotate3DMatrixForAxis (TypeDgrs rads, const VectorData< TypeDgrs, 3 > &axisVec, MatrixData< TypeRes, 4, 4 > &result)
Rotate a 3D matrix around the X, Y, and Z axis.
template<typename Type >
static void lookAt3D (const MatrixData< Type, 4, 4 > &transformMatrix, const VectorData< Type, 3 > &targetPos, const VectorData< Type, 3 > &upVector, MatrixData< Type, 4, 4 > &resMatrix)
template<typename TypeMat , typename TypeEye , typename TypeTarget , typename TypeUp >
static void lookAt3D (const VectorData< TypeEye, 3 > &eye, const VectorData< TypeTarget, 3 > &target, const VectorData< TypeUp, 3 > &up, MatrixData< TypeMat, 4, 4 > &resMatrix)
Calculate the view matrix from the eye, target, and up vectors.
template<typename TypeMat , typename Type >
static void matrixToEulerRotation (const MatrixData< TypeMat, 4, 4 > &mat, VectorData< Type, 3 > &result)
Converts a 4x4 rotation matrix to Euler angles.
template<typename Type , size_t N>
static void matrixToVector (const MatrixData< Type, N, 1 > &matrix, VectorData< Type, N > &vector)
Detailed Description
Definition at line 20 of file MatrixMixedAlgorithms.h.
Member Function Documentation
calculateModelMatrix()
template<typename ModelType , typename TypePos , typename TypeRot , typename TypeScale > static void GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix (const VectorData< TypePos, 3 > & position, const VectorData< TypeRot, 3 > & rotationRads, const VectorData< TypeScale, 3 > & scale, MatrixData< ModelType, 4, 4 > & model) inline static
Calculate the model matrix from the position, rotation, and scale.
This function calculates the model matrix from the position, rotation, and scale. The function applies the transformations in the following order: scale, rotation, and translation. The function assumes a specific order of transformations: scale, then rotation, then translation. As we're working with row-major matrices, the order of transformations in matrix multiplications is reversed.
Template Parameters
ModelType The data type of the matrix and vector elements (e.g., float, double).
TypePos The data type of the position vector elements (e.g., float, double).
TypeRot The data type of the rotation vector elements (e.g., float, double).
TypeScale The data type of the scale vector elements (e.g., float, double).
Parameters
position A 3D vector containing the position of the model.
rotationRads A 3D vector containing the rotation angles (in radians) around X, Y, and Z axes respectively.
scale A 3D vector containing the scale factors for the model.
model A 4x4 matrix which will contain the result of the model matrix.
Definition at line 204 of file MatrixMixedAlgorithms.h.
{
            // Initialize matrices
            MatrixData<ModelType, 4, 4> scaleMatrix;
            MatrixData<ModelType, 4, 4> rotationMatrix;
            MatrixData<ModelType, 4, 4> translationMatrix;
            MatrixAlgorithms::setMatrixZero(model);
            MatrixAlgorithms::setMatrixDiagonal(model, ModelType(1));
            // Create the translation matrix
            MatrixAlgorithms::getTranslationMatrix(position, translationMatrix);
            // Create rotation matrices around X, Y, and Z axes
            MatrixMixedAlgorithms::getRotate3DMatrix(rotationRads, rotationMatrix);
            // First, create the scale matrix
            MatrixAlgorithms::getScaleMatrix(scale, scaleMatrix);
            MatrixAlgorithms::matrixMatrixMulInPlace(model, translationMatrix, model);
            MatrixAlgorithms::matrixMatrixMulInPlace(model, rotationMatrix, model);
            MatrixAlgorithms::matrixMatrixMulInPlace(model, scaleMatrix, model);
        }
References getRotate3DMatrix(), GLESC::Math::MatrixAlgorithms::getScaleMatrix(), GLESC::Math::MatrixAlgorithms::getTranslationMatrix(), GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(), GLESC::Math::MatrixAlgorithms::setMatrixDiagonal(), and GLESC::Math::MatrixAlgorithms::setMatrixZero().
Referenced by TEST(), and TEST().
calculateViewMatrixEye()
template<typename Type > static void GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixEye (const VectorData< Type, 3 > & eye, const VectorData< Type, 3 > & target, const VectorData< Type, 3 > & up, MatrixData< Type, 4, 4 > & resMatrix) inline static
Definition at line 280 of file MatrixMixedAlgorithms.h.
{
            MatrixMixedAlgorithms::lookAt3D(eye, target, up, resMatrix);
        }
References GLESC::isIterable_v, and lookAt3D().
Referenced by GLESC::Math::Matrix< Type, N, M >::makeViewMatrixEye(), and TEST().
calculateViewMatrixPosRot()
template<typename TypePos , typename TypeRot , typename TypeRes > static void GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot (const VectorData< TypePos, 3 > & position, const VectorData< TypeRot, 3 > & rotationRads, MatrixData< TypeRes, 4, 4 > & viewMat) inline static
Definition at line 231 of file MatrixMixedAlgorithms.h.
{
            // Negate position for translation
            VectorData<TypePos, 3> negatedPos;
            VectorAlgorithms::vectorNegate(position, negatedPos);
            VectorData<TypeRes, 3> negatedRotationRads;
            VectorAlgorithms::vectorNegate(rotationRads, negatedRotationRads);
            VectorData<TypeRes, 3> scale = {1, 1, 1};
            // Initialize matrices
            MatrixAlgorithms::setMatrixZero(viewMat);
            MatrixAlgorithms::setMatrixDiagonal(viewMat, TypePos(1));
            MatrixData<TypePos, 4, 4> scaleMatrix;
            MatrixData<TypePos, 4, 4> rotationMatrix;
            MatrixData<TypePos, 4, 4> translationMatrix;
            // First, create the scale matrix
            MatrixAlgorithms::getScaleMatrix(scale, scaleMatrix);
            // Create rotation matrices around X, Y, and Z axes
            MatrixAlgorithms::setMatrixZero(rotationMatrix);
            MatrixAlgorithms::setMatrixDiagonal(rotationMatrix, TypePos(1));
            MatrixData<TypeRes, 4, 4> rotX;
            VectorData<TypeRot, 3> rotXAxis = {1, 0, 0};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(negatedRotationRads[0], rotXAxis, rotX);
            MatrixData<TypeRes, 4, 4> rotY;
            VectorData<TypeRot, 3> rotYAxis = {0, 1, 0};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(negatedRotationRads[1], rotYAxis, rotY);
            MatrixData<TypeRes, 4, 4> rotZ;
            VectorData<TypeRot, 3> rotZAxis = {0, 0, 1};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(negatedRotationRads[2], rotZAxis, rotZ);
            MatrixAlgorithms::matrixMatrixMulInPlace(rotationMatrix, rotZ, rotationMatrix);
            MatrixAlgorithms::matrixMatrixMulInPlace(rotationMatrix, rotX, rotationMatrix);
            MatrixAlgorithms::matrixMatrixMulInPlace(rotationMatrix, rotY, rotationMatrix);
            // Create the translation matrix
            MatrixAlgorithms::getTranslationMatrix(negatedPos, translationMatrix);
            MatrixAlgorithms::matrixMatrixMulInPlace(viewMat, scaleMatrix, viewMat);
            MatrixAlgorithms::matrixMatrixMulInPlace(viewMat, rotationMatrix, viewMat);
            MatrixAlgorithms::matrixMatrixMulInPlace(viewMat, translationMatrix, viewMat);
        }
References getRotate3DMatrixForAxis(), GLESC::Math::MatrixAlgorithms::getScaleMatrix(), GLESC::Math::MatrixAlgorithms::getTranslationMatrix(), GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(), GLESC::Math::MatrixAlgorithms::setMatrixDiagonal(), GLESC::Math::MatrixAlgorithms::setMatrixZero(), and GLESC::Math::VectorAlgorithms::vectorNegate().
Referenced by GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot(), TEST(), and TEST().
getRotate3DMatrix()
template<typename TypeDgrs , typename TypeRes > static void GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrix (const VectorData< TypeDgrs, 3 > & rads, MatrixData< TypeRes, 4, 4 > & result) inline static
Calculate the 3D rotation matrix from the rotation angles around the X, Y, and Z axes.
This function calculates the 3D rotation matrix from the rotation angles around the coordinate axes. The function applies the transformations in the following order: rotation around the X, Y, and Z axes.
Template Parameters
TypeDgrs The data type of the rotation angles (e.g., float, double).
TypeRes The data type of the result matrix elements (e.g., float, double).
Parameters
rads A 3D vector containing the rotation angles around the X, Y, and Z axes respectively.
result A 4x4 matrix which will contain the result of the rotation.
Definition at line 166 of file MatrixMixedAlgorithms.h.
{
            MatrixAlgorithms::setMatrixZero(result);
            MatrixAlgorithms::setMatrixDiagonal(result, 1.0f);
            MatrixData<TypeRes, 4, 4> rotX;
            VectorData<TypeDgrs, 3> rotXAxis = {1, 0, 0};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(rads[0], rotXAxis, rotX);
            MatrixData<TypeRes, 4, 4> rotY;
            VectorData<TypeDgrs, 3> rotYAxis = {0, 1, 0};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(rads[1], rotYAxis, rotY);
            MatrixData<TypeRes, 4, 4> rotZ;
            VectorData<TypeDgrs, 3> rotZAxis = {0, 0, 1};
            MatrixMixedAlgorithms::getRotate3DMatrixForAxis(rads[2], rotZAxis, rotZ);
            MatrixAlgorithms::matrixMatrixMulInPlace(result, rotZ, result);
            MatrixAlgorithms::matrixMatrixMulInPlace(result, rotY, result);
            MatrixAlgorithms::matrixMatrixMulInPlace(result, rotX, result);
        }
References getRotate3DMatrixForAxis(), GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(), GLESC::Math::MatrixAlgorithms::setMatrixDiagonal(), and GLESC::Math::MatrixAlgorithms::setMatrixZero().
Referenced by calculateModelMatrix(), and TEST().
getRotate3DMatrixForAxis()
template<typename TypeDgrs , typename TypeRes > static void GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrixForAxis (TypeDgrs rads, const VectorData< TypeDgrs, 3 > & axisVec, MatrixData< TypeRes, 4, 4 > & result) inline static
Rotate a 3D matrix around the X, Y, and Z axis.
This function applies sequential rotations to the input matrix based on the given angles. TODO: Be cautious about gimbal lock when using Euler angles, use quaternions for robustness. It's recommended to use quaternions for robustness.
Template Parameters
TypeDgrs The data type of the rotation angles (e.g., float, double).
TypeRes The data type of the result matrix elements (e.g., float, double).
Parameters
rads A 3D vector containing the rotation angles around the X, Y, and Z axes respectively.
result A 4x4 matrix which will contain the result of the rotation.
Definition at line 121 of file MatrixMixedAlgorithms.h.
{
            const TypeRes c = Math::cos(rads);
            const TypeRes s = Math::sin(rads);
            const TypeRes t = TypeRes(1) - c;
            // Normalized axis vector
            VectorData<TypeDgrs, 3> axis;
            VectorAlgorithms::normalize(axisVec, axis);
            VectorData<TypeRes, 3> temp;
            VectorAlgorithms::vectorScalarMul(axis, t, temp);
            result[0][0] = c + temp[0] * axis[0];
            result[0][1] = temp[0] * axis[1] + s * axis[2];
            result[0][2] = temp[0] * axis[2] - s * axis[1];
            result[0][3] = 0;
            result[1][0] = temp[1] * axis[0] - s * axis[2];
            result[1][1] = c + temp[1] * axis[1];
            result[1][2] = temp[1] * axis[2] + s * axis[0];
            result[1][3] = 0;
            result[2][0] = temp[2] * axis[0] + s * axis[1];
            result[2][1] = temp[2] * axis[1] - s * axis[0];
            result[2][2] = c + temp[2] * axis[2];
            result[2][3] = 0;
            result[3][0] = 0;
            result[3][1] = 0;
            result[3][2] = 0;
            result[3][3] = 1;
        }
References GLESC::Math::cos(), GLESC::isIterable_v, GLESC::Math::VectorAlgorithms::normalize(), GLESC::Math::sin(), and GLESC::Math::VectorAlgorithms::vectorScalarMul().
Referenced by calculateViewMatrixPosRot(), getRotate3DMatrix(), TEST(), TEST(), and TEST().
lookAt3D() [1/2]
template<typename Type > static void GLESC::Math::MatrixMixedAlgorithms::lookAt3D (const MatrixData< Type, 4, 4 > & transformMatrix, const VectorData< Type, 3 > & targetPos, const VectorData< Type, 3 > & upVector, MatrixData< Type, 4, 4 > & resMatrix) inline static
Definition at line 32 of file MatrixMixedAlgorithms.h.
{
            VectorData<Type, 3> eye = {transformMatrix[0][3], transformMatrix[1][3], transformMatrix[2][3]};
            MatrixMixedAlgorithms::lookAt3D(eye, targetPos, upVector, resMatrix);
        }
References GLESC::isIterable_v, and lookAt3D().
Referenced by calculateViewMatrixEye(), lookAt3D(), and TEST().
lookAt3D() [2/2]
template<typename TypeMat , typename TypeEye , typename TypeTarget , typename TypeUp > static void GLESC::Math::MatrixMixedAlgorithms::lookAt3D (const VectorData< TypeEye, 3 > & eye, const VectorData< TypeTarget, 3 > & target, const VectorData< TypeUp, 3 > & up, MatrixData< TypeMat, 4, 4 > & resMatrix) inline static
Calculate the view matrix from the eye, target, and up vectors.
This function calculates the view matrix from the eye, target, and up vectors. The function assumes a specific order of transformations, scale, then rotation, then translation.
Template Parameters
TypeMat The data type of the matrix elements (e.g., float, double).
TypeEye The data type of the eye vector elements (e.g., float, double).
TypeTarget The data type of the target vector elements (e.g., float, double).
TypeUp The data type of the up vector elements (e.g., float, double).
Parameters
eye A 3D vector containing the position of the camera.
target A 3D vector containing the position of the target.
up A 3D vector containing the world's up direction. (usually {0, 1, 0})
resMatrix A 4x4 matrix which will contain the result of the view matrix.
Definition at line 55 of file MatrixMixedAlgorithms.h.
{
            VectorData<TypeMat, 3> f;
            VectorAlgorithms::vectorSub(target, eye, f); // forward = target - eye
            VectorAlgorithms::normalize(f, f);
            VectorData<TypeMat, 3> s; // s = right
            VectorAlgorithms::crossProduct(f, up, s);
            VectorAlgorithms::normalize(s, s);
            VectorData<TypeMat, 3> u; // u = up
            VectorAlgorithms::crossProduct(s, f, u);
            resMatrix = {
                {
                    {s[0], u[0], -f[0], 0},
                    {s[1], u[1], -f[1], 0},
                    {s[2], u[2], -f[2], 0},
                    {
                        -VectorAlgorithms::dotProduct(s, eye),
                        -VectorAlgorithms::dotProduct(u, eye),
                        VectorAlgorithms::dotProduct(f, eye),
                        1
                    }
                }
            };
        }
References GLESC::Math::VectorAlgorithms::crossProduct(), GLESC::Math::VectorAlgorithms::dotProduct(), GLESC::isIterable_v, GLESC::Math::VectorAlgorithms::normalize(), and GLESC::Math::VectorAlgorithms::vectorSub().
matrixToEulerRotation()
template<typename TypeMat , typename Type > static void GLESC::Math::MatrixMixedAlgorithms::matrixToEulerRotation (const MatrixData< TypeMat, 4, 4 > & mat, VectorData< Type, 3 > & result) inline static
Converts a 4x4 rotation matrix to Euler angles.
Parameters
mat A 4x4 rotation matrix.
result A 3D vector to store the Euler angles (pitch, yaw, roll).
Definition at line 91 of file MatrixMixedAlgorithms.h.
{
            Type pitch = std::asin(-mat[2][1]); // Calculate pitch
            Type cosPitch = std::cos(pitch);
            Type yaw, roll;
            if (std::abs(cosPitch) > 1e-6) {
                // Gimbal lock check
                yaw = std::atan2(mat[2][0], mat[2][2]);
                roll = std::atan2(mat[0][1], mat[1][1]);
            }
            else {
                yaw = std::atan2(-mat[0][2], mat[0][0]);
                roll = 0;
            }
            result = {pitch, yaw, roll};
        }
References GLESC::isIterable_v.
matrixToVector()
template<typename Type , size_t N> static void GLESC::Math::MatrixMixedAlgorithms::matrixToVector (const MatrixData< Type, N, 1 > & matrix, VectorData< Type, N > & vector) inline static
Definition at line 24 of file MatrixMixedAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                vector[i] = matrix[i][0];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::toVector().
The documentation for this class was generated from the following file:
MatrixMixedAlgorithms.h