GLESC: GLESC::Math::Sphere Class Reference
GLESC::Math::Sphere Class Reference
#include <Sphere.h>
Public Member Functions
Sphere (Point centerParam, Distance radiusParam)
Creates a sphere with the given center and radius.
bool intersects (const Line &line) const override
Checks if the figure intersects with the given line.
bool intersects (const Plane &plane) const override
Checks if the sphere intersects with the given plane.
bool intersects (const Point &point) const override
Checks if the sphere intersects with the given point.
bool intersects (const Polyhedron &polyhedron) const override
Checks if the sphere intersects with the given figure.
bool intersects (const PolyhedronFace &face) const override
Checks if the sphere intersects with the given face.
Public Member Functions inherited from GLESC::Math::Figure
virtual ~Figure ()=default
Private Member Functions
bool intersects (const Point &startPoint, const Point &endPoint) const
Checks if the sphere intersects with an edge defined by two points.
Private Attributes
Point center
The center of the sphere.
float radius
The radius of the sphere.
Detailed Description
Definition at line 16 of file Sphere.h.
Constructor & Destructor Documentation
Sphere()
Sphere::Sphere (Point centerParam, Distance radiusParam)
Creates a sphere with the given center and radius.
Parameters
centerParam The center of the sphere
radiusParam The radius of the sphere
Definition at line 14 of file Sphere.cpp.
                                                      :
        center(std::move(centerParam)), radius(radiusParam) {}
Member Function Documentation
intersects() [1/6]
bool Sphere::intersects (const Line & line) const override virtual
Checks if the figure intersects with the given line.
Parameters
line The line to check intersection with
Returns
True if the figure intersects with the line, false otherwise
Implements GLESC::Math::Figure.
Definition at line 46 of file Sphere.cpp.
{
    // Find the vector from the line's point to the sphere's center
    Point centerToLine = center - line.getPoint();
    // Project this vector onto the line's direction
    Direction projection = centerToLine.project(line.getDirection());
    // Find the closest point on the line to the sphere's center
    Point closestPoint = line.getPoint() + projection;
    // Check if the closest point is inside the sphere
    return intersects(closestPoint);
}
References center, intersects(), GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::project().
intersects() [2/6]
bool Sphere::intersects (const Plane & plane) const override virtual
Checks if the sphere intersects with the given plane.
Parameters
plane The plane to check intersection with
Returns
True if the sphere intersects with the plane, false otherwise
Implements GLESC::Math::Figure.
Definition at line 18 of file Sphere.cpp.
{
    return plane.distanceToPoint(center) <= radius;
}
References center, GLESC::Math::Plane::distanceToPoint(), and radius.
Referenced by intersects(), intersects(), and intersects().
intersects() [3/6]
bool Sphere::intersects (const Point & point) const override virtual
Checks if the sphere intersects with the given point.
Parameters
point The point to check intersection with
Returns
True if the sphere intersects with the point, false otherwise
Implements GLESC::Math::Figure.
Definition at line 70 of file Sphere.cpp.
{
    return (point - center).length() <= radius;
}
References center, and radius.
intersects() [4/6]
bool Sphere::intersects (const Point & startPoint, const Point & endPoint) const private
Checks if the sphere intersects with an edge defined by two points.
Parameters
startPoint The start point of the edge.
endPoint The end point of the edge.
Returns
True if the sphere intersects with the edge, false otherwise.
Definition at line 75 of file Sphere.cpp.
{
    Direction edge = endPoint - startPoint;
    Direction startToCenter = center - startPoint;
    Distance edgeLengthSquared = edge.lengthSquared();
    Distance t = startToCenter.dot(edge) / edgeLengthSquared;
    // Clamping t to be within [0, 1]
    t = clamp(t, 0, 1);
    Point closestPoint = startPoint + edge * t;
    return (closestPoint - center).lengthSquared() <= radius * radius;
}
References center, GLESC::Math::clamp(), GLESC::isIterable_v, GLESC::Math::Vector< Type, N >::lengthSquared(), and radius.
intersects() [5/6]
bool Sphere::intersects (const Polyhedron & polyhedron) const override virtual
Checks if the sphere intersects with the given figure.
Parameters
polyhedron The figure to check intersection with
Returns
True if the sphere intersects with the figure, false otherwise
Implements GLESC::Math::Figure.
Definition at line 60 of file Sphere.cpp.
{
    for (const auto &face : polyhedron.getFaces()) {
        if (intersects(face)) {
            return true;
        }
    }
    return false;
}
References intersects(), and GLESC::isIterable_v.
intersects() [6/6]
bool Sphere::intersects (const PolyhedronFace & face) const override virtual
Checks if the sphere intersects with the given face.
Parameters
face The face to check intersection with.
Returns
True if the sphere intersects with the face, false otherwise.
Implements GLESC::Math::Figure.
Definition at line 23 of file Sphere.cpp.
{
    std::vector<Point> vertices = face.getPolyhedronVertices();
    // Check if any vertex of the face is inside the sphere.
    for (const auto &index : face.getVertexIndices()) {
        if (this->intersects(vertices[index])) {
            return true;
        }
    }
    // Check for edge-sphere intersection.
    const auto &indices = face.getVertexIndices();
    for (size_t i = 0; i < indices.size(); ++i) {
        const Point &startPoint = vertices[indices[i]];
        const Point &endPoint = vertices[indices[(i + 1) % indices.size()]];
        if (intersects(startPoint, endPoint)) {
            return true;
        }
    }
    return false;
}
References intersects(), and GLESC::isIterable_v.
Member Data Documentation
center
Point GLESC::Math::Sphere::center private
The center of the sphere.
Definition at line 70 of file Sphere.h.
Referenced by intersects(), intersects(), intersects(), and intersects().
radius
float GLESC::Math::Sphere::radius private
The radius of the sphere.
Definition at line 74 of file Sphere.h.
Referenced by intersects(), intersects(), and intersects().
The documentation for this class was generated from the following files:
Sphere.h
Sphere.cpp