GLESC: GLESC::Math::Line Class Reference
GLESC::Math::Line Class Reference
#include <Line.h>
Public Types
enum class Construct { PointPoint , PointDirection }
Public Member Functions
Line ()=default
Line (const Point &pointParam, const Vec3F &pointOrDir, Construct construct=Construct::PointDirection)
Construct a new Line object.
Distance distance (const Point &pointParam) const
Get the distance from a point to the line.
const Direction & getDirection () const
Get the Direction vector.
const Point & getPoint () const
Get the Point object.
bool intersects (const Line &line) const
Check if a line intersects with another line.
bool intersects (const Point &pointParam) const
Check if a line intersects with a point.
void setDirection (const Direction &directionParam)
Set the Direction vector.
void setPoint (const Point &pointParam)
Private Member Functions
void setDirectionFromPoints (const Point &pointParam, const Point &otherPoint)
Set the direction of the line from two points.
Private Attributes
Direction direction {{0, 1}}
The direction of the line.
Point point {{0, 0}}
A point in the line.
Detailed Description
Definition at line 15 of file Line.h.
Member Enumeration Documentation
Construct
enum class GLESC::Math::Line::Construct strong
Enumerator
PointPoint
PointDirection
Definition at line 17 of file Line.h.
{
            PointPoint, PointDirection
        };
Constructor & Destructor Documentation
Line() [1/2]
Line::Line (const Point & pointParam, const Vec3F & pointOrDir, Construct construct = Construct::PointDirection)
Construct a new Line object.
Parameters
pointParam The point in the line
pointOrDir The second point or the direction of the line
construct The type of construction
Definition at line 6 of file Line.cpp.
{
    if (construct == Construct::PointDirection) {
        setPoint(pointParam);
        setDirection(pointOrDir);
    }
    else {
        setPoint(pointParam);
        setDirectionFromPoints(pointParam, pointOrDir);
    }
}
References GLESC::isIterable_v, PointDirection, setDirection(), setDirectionFromPoints(), and setPoint().
Line() [2/2]
GLESC::Math::Line::Line () default
Member Function Documentation
distance()
Distance Line::distance (const Point & pointParam) const
Get the distance from a point to the line.
Parameters
pointParam The point to calculate the distance to.
Returns
Distance The distance from the point to the line.
Definition at line 28 of file Line.cpp.
{
    // Calculate the cross product vector
    auto crossProduct = direction.cross(pointParam - this->point);
    // Return the length of the cross product vector,
    // which represents the area of the parallelogram formed by the two vectors
    // and is equal to the distance times the length of the direction vector
    // Because the direction vector is normalized, its length is 1, and the length of the cross product
    // is the distance from the point to the line.
    return crossProduct.length();
}
References GLESC::Math::Vector< Type, N >::cross(), direction, GLESC::isIterable_v, and point.
Referenced by intersects().
getDirection()
const Direction & GLESC::Math::Line::getDirection () const inline
Get the Direction vector.
This will return the normalized direction vector.
Returns
const Direction&
Definition at line 46 of file Line.h.
{ return direction; }
References direction.
getPoint()
const Point & GLESC::Math::Line::getPoint () const inline
Get the Point object.
Returns
const Point&
Definition at line 52 of file Line.h.
{ return point; }
References point.
intersects() [1/2]
bool Line::intersects (const Line & line) const
Check if a line intersects with another line.
This function checks if the lines intersect by checking if the cross product of the directions is not the zero vector. It also uses an epsilon value to account for floating point errors.
Parameters
line The line to check for intersection.
Returns
true If the lines intersect.
false If the lines do not intersect.
Definition at line 20 of file Line.cpp.
{
    return !eq(direction.cross(line.direction).length(), 0);
}
References GLESC::Math::Vector< Type, N >::cross(), direction, GLESC::Math::eq(), and GLESC::isIterable_v.
intersects() [2/2]
bool Line::intersects (const Point & pointParam) const
Check if a line intersects with a point.
This function checks if the point is on the line by checking if the cross product of the direction of the line and the vector from the point to the line is the zero vector. It uses an epsilon value to account for floating point errors.
Parameters
pointParam The point to check for intersection.
Returns
true If the point is on the line.
false If the point is not on the line.
Definition at line 24 of file Line.cpp.
{
    return eq(distance(pointParam), 0);
}
References distance(), GLESC::Math::eq(), and GLESC::isIterable_v.
setDirection()
void Line::setDirection (const Direction & directionParam)
Set the Direction vector.
This accepts any vector, but it will normalize it.
Parameters
directionParam
Definition at line 44 of file Line.cpp.
{
    D_ASSERT_NOT_EQUAL(directionParam.length(), 0, "Direction cannot be a zero vector");
    direction = directionParam.normalize();
}
References D_ASSERT_NOT_EQUAL, direction, GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::normalize().
Referenced by Line().
setDirectionFromPoints()
void Line::setDirectionFromPoints (const Point & pointParam, const Point & otherPoint) private
Set the direction of the line from two points.
Parameters
pointParam The point in the line
otherPoint The second point
Definition at line 49 of file Line.cpp.
{
    auto dir = otherPoint - pointParam;
    D_ASSERT_NOT_EQUAL(dir.length(), 0, "Direction cannot be a zero vector");
    direction = dir.normalize();
}
References D_ASSERT_NOT_EQUAL, direction, GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::normalize().
Referenced by Line().
setPoint()
void Line::setPoint (const Point & pointParam)
Definition at line 40 of file Line.cpp.
{
    point = pointParam;
}
References GLESC::isIterable_v, and point.
Referenced by Line().
Member Data Documentation
direction
Direction GLESC::Math::Line::direction {{0, 1}} private
The direction of the line.
This is normalized when calculated, set or modified. This way the direction can be get with the getter without having to normalize it every time.
Definition at line 99 of file Line.h.
{{0, 1}};
Referenced by distance(), getDirection(), intersects(), setDirection(), and setDirectionFromPoints().
point
Point GLESC::Math::Line::point {{0, 0}} private
A point in the line.
Definition at line 93 of file Line.h.
{{0, 0}};
Referenced by distance(), getPoint(), and setPoint().
The documentation for this class was generated from the following files:
Line.h
Line.cpp