GLESC: GLESC::HUD::DebugConsoleHUD Class Reference
GLESC::HUD::DebugConsoleHUD Class Reference
Class to encapsulate the logic of the debug console HUD.
#include <DebugConsoleHUD.h>
Public Member Functions
DebugConsoleHUD ()
Public Member Functions inherited from GLESC::InGameWindow
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Private Member Functions
void windowContent (float timeOfFrame) override
Private Attributes
ImVec4 errorColor = ImVec4(1.0f, 0.0f, 0.0f, 1.0f)
ImVec4 infoColor = ImVec4(0.0f, 1.0f, 0.0f, 1.0f)
ImVec4 warningColor = ImVec4(1.0f, 1.0f, 0.0f, 1.0f)
Additional Inherited Members
Protected Member Functions inherited from GLESC::InGameWindow
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
Protected Attributes inherited from GLESC::InGameWindow
bool isVisible = true
Detailed Description
Class to encapsulate the logic of the debug console HUD.
The debug console HUD is a window that displays debug information. Allows visualizing the data contained in the debug console.
Definition at line 20 of file DebugConsoleHUD.h.
Constructor & Destructor Documentation
DebugConsoleHUD()
DebugConsoleHUD::DebugConsoleHUD ()
Definition at line 10 of file DebugConsoleHUD.cpp.
{
    this->setTitle("Console");
    this->setMaxSize({1200.0f, 300.0f});
    this->setMinSize({600.0f, 150.0f});
    this->setSizeFraction({0.4f, 0.2f});
    isVisible = true;
    this->setCenter(WindowCenter::BottomCenter);
    this->setLayoutPosition(LayoutPos::BottomCenter);
    this->addFlag(ImGuiWindowFlags_NoResize);
    this->addFlag(ImGuiWindowFlags_NoMove);
    this->addFlag(ImGuiWindowFlags_NoCollapse);
    this->addFlag(ImGuiWindowFlags_NoTitleBar);
    this->addFlag(ImGuiWindowFlags_NoSavedSettings);
    this->addFlag(ImGuiWindowFlags_NoBringToFrontOnFocus);
    this->addFlag(ImGuiWindowFlags_NoFocusOnAppearing);
}
References GLESC::InGameWindow::addFlag(), GLESC::BottomCenter, GLESC::isIterable_v, GLESC::InGameWindow::isVisible, GLESC::InGameWindow::setCenter(), GLESC::InGameWindow::setLayoutPosition(), GLESC::InGameWindow::setMaxSize(), GLESC::InGameWindow::setMinSize(), GLESC::InGameWindow::setSizeFraction(), and GLESC::InGameWindow::setTitle().
Member Function Documentation
windowContent()
void DebugConsoleHUD::windowContent (float timeOfFrame) override private virtual
Implements GLESC::InGameWindow.
Definition at line 28 of file DebugConsoleHUD.cpp.
{
    static size_t lastMessageCount = 0;
    const auto& messages = GLESC::Console::GetMessages();
    bool shouldScroll = messages.size() != lastMessageCount;
    lastMessageCount = messages.size();
    ImGui::BeginChild("ConsoleRegion", ImVec2(0, 0), true, ImGuiWindowFlags_AlwaysVerticalScrollbar);
    // Iterate through console messages and display them with appropriate color
    for (const auto& entry : messages) {
        ImVec4 color;
        std::string level;
        switch (entry.level) {
        case GLESC::LogLevel::Info:
            color = infoColor;
            level = "Info";
            break;
        case GLESC::LogLevel::Warning:
            color = warningColor;
            level = "Warning";
            break;
        case GLESC::LogLevel::Error:
            color = errorColor;
            level = "Error";
            break;
        default:
            color = infoColor;
            level = "Info";
            break;
        }
        ImGui::PushTextWrapPos(ImGui::GetWindowContentRegionMax().x);
        ImGui::TextColored(color, "( %d ) %s: %s", entry.count, level.c_str(), entry.message.c_str());
        ImGui::PopTextWrapPos();
        ImGui::Separator();
    }
    if (shouldScroll) {
        ImGui::SetScrollHereY(1.0f);
    }
    ImGui::EndChild();
}
References GLESC::Error, errorColor, GLESC::Console::GetMessages(), GLESC::Info, infoColor, GLESC::isIterable_v, GLESC::Warning, and warningColor.
Member Data Documentation
errorColor
ImVec4 GLESC::HUD::DebugConsoleHUD::errorColor = ImVec4(1.0f, 0.0f, 0.0f, 1.0f) private
Definition at line 26 of file DebugConsoleHUD.h.
Referenced by windowContent().
infoColor
ImVec4 GLESC::HUD::DebugConsoleHUD::infoColor = ImVec4(0.0f, 1.0f, 0.0f, 1.0f) private
Definition at line 28 of file DebugConsoleHUD.h.
Referenced by windowContent().
warningColor
ImVec4 GLESC::HUD::DebugConsoleHUD::warningColor = ImVec4(1.0f, 1.0f, 0.0f, 1.0f) private
Definition at line 27 of file DebugConsoleHUD.h.
Referenced by windowContent().
The documentation for this class was generated from the following files:
DebugConsoleHUD.h
DebugConsoleHUD.cpp