GLESC: GLESC::ECS::Entity Class Reference
GLESC::ECS::Entity Class Reference
#include <Entity.h>
Public Member Functions
~Entity ()=default
The entity will not be destroyed if the destructor is called To destroy an entity, use the destroy() method.
template<typename Component >
Entity & addComponent ()
Adds a component to the entity and returns a reference to it The components is registered to the ECSManager The entity signature is updated to reflect the new component.
void destroy ()
template<typename Component >
Component & getComponent () const
Returns a reference to the component.
EntityID getID () const
EntityName getName () const
Returns the entity's name.
template<typename Component >
bool hasComponent () const
Checks if the entity has a component.
bool isAlive () const
Checks if the entity is alive (if the ID of the entity is valid)
template<typename Component >
Entity & removeComponent ()
Removes a component from the entity The entity signature is updated to reflect the removed component.
Private Member Functions
Entity (const EntityName &name, const EntityMetadata &metadata, ECSCoordinator &ecs)
This constructor is internal to the ECS, it is used to create a new Entity.
Entity (ECSCoordinator &ecs)
This constructor is internal to the ECS, it is used to create a new without a name.
Entity (EntityID id, ECSCoordinator &ecs)
This constructor is internal to the ECS, it is used to cast an EntityID to an Entity.
Private Attributes
ECSCoordinator & ecs
const EntityID ID
The entity's ID The ID is used to identify the entity in the ECS.
Friends
class GLESC::ECS::EntityFactory
The EntityFactory class is a friend of the Entity class.
Detailed Description
Definition at line 21 of file Entity.h.
Constructor & Destructor Documentation
~Entity()
GLESC::ECS::Entity::~Entity () default
The entity will not be destroyed if the destructor is called To destroy an entity, use the destroy() method.
Entity() [1/3]
Entity::Entity (const EntityName & name, const EntityMetadata & metadata, ECSCoordinator & ecs) explicit private
This constructor is internal to the ECS, it is used to create a new Entity.
Parameters
name The name of the entity
Definition at line 5 of file Entity.cpp.
    : ID(ecs.createEntity(name, metadata)), ecs(ecs) {
}
Entity() [2/3]
Entity::Entity (ECSCoordinator & ecs) explicit private
This constructor is internal to the ECS, it is used to create a new without a name.
Parameters
ecs The ECSManager
Definition at line 9 of file Entity.cpp.
                                  : ID(ecs.createEntity()), ecs(ecs) {
}
Entity() [3/3]
Entity::Entity (EntityID id, ECSCoordinator & ecs) explicit private
This constructor is internal to the ECS, it is used to cast an EntityID to an Entity.
Parameters
id
Definition at line 12 of file Entity.cpp.
                                               : ID(id), ecs(ecs) {
}
Member Function Documentation
addComponent()
template<typename Component > Entity & GLESC::ECS::Entity::addComponent ()
Adds a component to the entity and returns a reference to it The components is registered to the ECSManager The entity signature is updated to reflect the new component.
Template Parameters
Component The type of the component
Definition at line 113 of file Entity.h.
{
        ecs.addComponent<Component>(ID, Component());
        return *this;
    }
References GLESC::ECS::ECSCoordinator::addComponent(), ecs, ID, and GLESC::isIterable_v.
Referenced by GLESC::Engine::createEngineEntities(), Default::init(), and GLESC::EngineCamera::setupCamera().
destroy()
void Entity::destroy ()
Definition at line 15 of file Entity.cpp.
                     {
    ecs.markForDestruction(ID);
}
References ecs, ID, and GLESC::ECS::ECSCoordinator::markForDestruction().
Referenced by GLESC::Scene::Scene::destroyEntities(), GLESC::Scene::Scene::destroyEntity(), and GLESC::Scene::Scene::destroyEntity().
getComponent()
template<typename Component > Component & GLESC::ECS::Entity::getComponent () const
Returns a reference to the component.
Template Parameters
Component The type of the component
Returns
A reference to the component
Definition at line 125 of file Entity.h.
{
        return ecs.getComponent<Component>(ID);
    }
References ecs, GLESC::ECS::ECSCoordinator::getComponent(), ID, and GLESC::isIterable_v.
Referenced by GLESC::Engine::createEngineEntities(), Default::init(), GLESC::EngineCamera::moveBackward(), GLESC::EngineCamera::moveDown(), GLESC::EngineCamera::moveForward(), GLESC::EngineCamera::moveLeft(), GLESC::EngineCamera::moveRight(), GLESC::EngineCamera::moveUp(), GLESC::EngineCamera::rotate(), GLESC::EngineCamera::setupCamera(), and GLESC::Engine::update().
getID()
EntityID GLESC::ECS::Entity::getID () const inline
Definition at line 34 of file Entity.h.
{ return ID; }
References ID.
getName()
EntityName Entity::getName () const
Returns the entity's name.
Returns
The entity's name
Definition at line 19 of file Entity.cpp.
{
    return ecs.getEntityName(ID);
}
References ecs, GLESC::ECS::ECSCoordinator::getEntityName(), and ID.
hasComponent()
template<typename Component > bool GLESC::ECS::Entity::hasComponent () const
Checks if the entity has a component.
Template Parameters
Component The type of the component
Returns
True if the entity has the component, false otherwise
Definition at line 130 of file Entity.h.
{
        return ecs.hasComponent(ID, ecs.getComponentID<Component>());
    }
References ecs, GLESC::ECS::ECSCoordinator::getComponentID(), GLESC::ECS::ECSCoordinator::hasComponent(), ID, and GLESC::isIterable_v.
isAlive()
bool Entity::isAlive () const
Checks if the entity is alive (if the ID of the entity is valid)
Definition at line 23 of file Entity.cpp.
{
    return ecs.isEntityAlive(ID);
}
References ecs, ID, and GLESC::ECS::ECSCoordinator::isEntityAlive().
removeComponent()
template<typename Component > Entity & GLESC::ECS::Entity::removeComponent ()
Removes a component from the entity The entity signature is updated to reflect the removed component.
Template Parameters
Component
Definition at line 119 of file Entity.h.
{
        ecs.removeComponent<Component>(ID);
        return *this;
    }
References ecs, ID, GLESC::isIterable_v, and GLESC::ECS::ECSCoordinator::removeComponent().
Friends And Related Symbol Documentation
GLESC::ECS::EntityFactory
friend class GLESC::ECS::EntityFactory friend
The EntityFactory class is a friend of the Entity class.
Definition at line 25 of file Entity.h.
Member Data Documentation
ecs
ECSCoordinator& GLESC::ECS::Entity::ecs private
Definition at line 108 of file Entity.h.
Referenced by addComponent(), destroy(), getComponent(), getName(), hasComponent(), isAlive(), and removeComponent().
ID
const EntityID GLESC::ECS::Entity::ID private
The entity's ID The ID is used to identify the entity in the ECS.
Definition at line 106 of file Entity.h.
Referenced by addComponent(), destroy(), getComponent(), getID(), getName(), hasComponent(), isAlive(), and removeComponent().
The documentation for this class was generated from the following files:
Entity.h
Entity.cpp