GLESC: GLESC::SoundPlayer Class Reference
GLESC::SoundPlayer Class Reference
Class that handles sound playing.
#include <SoundPlayer.h>
Static Public Member Functions
static void cleanup ()
Cleanup the sound player.
static void init ()
Initialize the sound player.
static void loadSong (const std::string &filePath, const std::string &name)
Load a song from a file.
static void loadSound (const std::string &filePath, const std::string &name)
Load a sound from a file.
static void play3DSound (const std::string &name, const Vec3F &listenerPos, const Vec3F &soundPos)
Play a 3D sound.
static void playMusic (Loops loops=-1, Volume volume=128)
Play the music.
static Channel playSound (const std::string &name, Volume volume=128, Loops loops=0)
Play a sound.
static void setMusic (const std::string &name)
Set the music to play.
static void setMusicVolume (int volume)
Set the volume of the music.
Private Types
using Channel = int
using Loops = int
using Volume = int
Static Private Attributes
static Mix_Music * currentMusic = nullptr
Pointer to the current music so it can be easily handled by the class.
static constexpr float maxDistance = 1000.0f
Maximum distance for 3D sound.
static SoundLoader soundLoader {}
This handles all the loading and storing of sounds and music.
Detailed Description
Class that handles sound playing.
This class handles all the playing and loading of sounds and music. It provides a general interface for the game to facilitate sound playing.
Definition at line 24 of file SoundPlayer.h.
Member Typedef Documentation
Channel
using GLESC::SoundPlayer::Channel = int private
Definition at line 25 of file SoundPlayer.h.
Loops
using GLESC::SoundPlayer::Loops = int private
Definition at line 27 of file SoundPlayer.h.
Volume
using GLESC::SoundPlayer::Volume = int private
Definition at line 26 of file SoundPlayer.h.
Member Function Documentation
cleanup()
void SoundPlayer::cleanup () static
Cleanup the sound player.
Definition at line 24 of file SoundPlayer.cpp.
{
    soundLoader.cleanup();
}
References GLESC::SoundLoader::cleanup(), and soundLoader.
Referenced by GLESC::Engine::~Engine().
init()
void SoundPlayer::init () static
Initialize the sound player.
Definition at line 20 of file SoundPlayer.cpp.
                       {
    SoundLoader::init();
}
References GLESC::SoundLoader::init().
Referenced by GLESC::Engine::Engine().
loadSong()
void SoundPlayer::loadSong (const std::string & filePath, const std::string & name) static
Load a song from a file.
Parameters
filePath The path to the song file
name The name of the song
Definition at line 28 of file SoundPlayer.cpp.
{
    soundLoader.loadMusic(filePath, name);
}
References GLESC::isIterable_v, GLESC::SoundLoader::loadMusic(), and soundLoader.
loadSound()
void SoundPlayer::loadSound (const std::string & filePath, const std::string & name) static
Load a sound from a file.
Parameters
filePath The path to the sound file
name The name of the sound
Definition at line 32 of file SoundPlayer.cpp.
{
    soundLoader.loadSound(filePath, name);
}
References GLESC::isIterable_v, GLESC::SoundLoader::loadSound(), and soundLoader.
play3DSound()
void SoundPlayer::play3DSound (const std::string & name, const Vec3F & listenerPos, const Vec3F & soundPos) static
Play a 3D sound.
It must be loaded before playing It will be played at the position of the sound and the listener taking advantage of the headphones capabilities of playing sounds left and right
Parameters
name The name of the sound
listenerPos The position of the listener
soundPos The position of the sound
Definition at line 44 of file SoundPlayer.cpp.
{
    // Calculate the distance between the listener and the sound
    Vec3F diff = soundPos - listenerPos;
    float distance = diff.length();
    // Assuming maxDistance is the distance at which the sound is inaudible
    const float maxDistance = 100.0f;
    float volume = (maxDistance - distance) / maxDistance;
    volume = std::max(0.0f, std::min(1.0f, volume));
    // Calculate the panning based on the relative position on the x-axis
    float pan = diff.getX() / maxDistance;
    pan = std::max(-1.0f, std::min(1.0f, pan));
    // Convert volume and pan to SDL_mixer's format
    int sdlVolume = static_cast<int>(volume * MIX_MAX_VOLUME);
    int left = static_cast<int>((1.0f - pan) * static_cast<float>(sdlVolume));
    int right = static_cast<int>((1.0f + pan) * static_cast<float>(sdlVolume));
    Channel channel = playSound(name, sdlVolume);
    Mix_SetPanning(channel, left, right);
}
References GLESC::isIterable_v, GLESC::Math::Vector< Type, N >::length(), maxDistance, and playSound().
playMusic()
void SoundPlayer::playMusic (Loops loops = -1, Volume volume = 128) static
Play the music.
The music must have been loaded and set before playing
Parameters
loops The number of times to loop the music
volume The volume of the music
Definition at line 74 of file SoundPlayer.cpp.
{
    D_ASSERT_NOT_NULLPTR(currentMusic, "No music set to play");
    Mix_PlayMusic(currentMusic, loops);
    setMusicVolume(volume);
}
References currentMusic, D_ASSERT_NOT_NULLPTR, GLESC::isIterable_v, and setMusicVolume().
playSound()
SoundPlayer::Channel SoundPlayer::playSound (const std::string & name, Volume volume = 128, Loops loops = 0) static
Play a sound.
It must be loaded before playing
Parameters
name The name of the sound
volume The volume of the sound
loops The number of times to loop the sound
Returns
The channel the sound is playing on
Definition at line 37 of file SoundPlayer.cpp.
{
    setMusicVolume(volume);
    Mix_Chunk& sound = soundLoader.getSound(name);
    return Mix_PlayChannel(-1, &sound, loops); // Play on the first free channel
}
References GLESC::SoundLoader::getSound(), GLESC::isIterable_v, setMusicVolume(), and soundLoader.
Referenced by play3DSound().
setMusic()
void SoundPlayer::setMusic (const std::string & name) static
Set the music to play.
Parameters
name The name of the music
Definition at line 69 of file SoundPlayer.cpp.
{
    Mix_Music& music = soundLoader.getMusic(name);
    currentMusic = &music;
}
References currentMusic, GLESC::SoundLoader::getMusic(), GLESC::isIterable_v, and soundLoader.
setMusicVolume()
void SoundPlayer::setMusicVolume (int volume) static
Set the volume of the music.
Parameters
volume The volume of the music
Definition at line 80 of file SoundPlayer.cpp.
{
    Mix_VolumeMusic(volume);
}
References GLESC::isIterable_v.
Referenced by playMusic(), and playSound().
Member Data Documentation
currentMusic
Mix_Music * SoundPlayer::currentMusic = nullptr static private
Pointer to the current music so it can be easily handled by the class.
Definition at line 93 of file SoundPlayer.h.
Referenced by playMusic(), and setMusic().
maxDistance
constexpr float GLESC::SoundPlayer::maxDistance = 1000.0f static constexpr private
Maximum distance for 3D sound.
If the distance between the listener and the sound is greater than this, the sound will not be heard
This is to simulate the attenuation of sound in the real world
Definition at line 99 of file SoundPlayer.h.
Referenced by play3DSound().
soundLoader
SoundLoader SoundPlayer::soundLoader {} static private
This handles all the loading and storing of sounds and music.
Definition at line 103 of file SoundPlayer.h.
Referenced by cleanup(), loadSong(), loadSound(), playSound(), and setMusic().
The documentation for this class was generated from the following files:
SoundPlayer.h
SoundPlayer.cpp