GLESC: GLESC::ECS::ECSCoordinator Class Reference
GLESC::ECS::ECSCoordinator Class Reference
#include <ECS.h>
Public Member Functions
ECSCoordinator ()=default
template<class Component >
void addComponent (EntityID entity, const Component &component)
Add a component to an entity.
template<typename Component >
void addComponentRequirementToSystem (const SystemName &name)
Add a component requirement to the system.
EntityID createEntity ()
Create an entity with a default name.
EntityID createEntity (const EntityName &name, const EntityMetadata &metadata)
Create an entity with the given name. The name must be unique.
void destroyEntities ()
Destroy all entities marked for destruction.
bool destroyEntity (EntityID entity)
Destroy an entity, destroying all the components and removing it from the systems.
const std::unordered_map< EntityName, EntityID > & getAllEntities () const
Get all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities (const SystemName &name) const
Get the entities associated with a system.
template<class Component >
Component & getComponent (EntityID entity) const
Get the component of an entity by its Id.
template<class Component >
ComponentID getComponentID () const
Get the ID of a component.
std::vector< IComponent * > getComponents (EntityID entityId) const
Get the components of an entity.
const std::vector< EntityID > & getEntitiesToBeDestroyed () const
EntityID getEntityID (const EntityName &name) const
Get the entity ID from the entity name.
const EntityMetadata & getEntityMetadata (EntityID entity) const
Get the metadata of the entity.
const EntityName & getEntityName (EntityID entity) const
Get the name of the entity given the ID.
const std::vector< EntityID > & getInstancedEntities (const EntityName &name) const
Get the a list of entities that are instanced by the given instance name.
template<typename System >
bool hasComponent (EntityID entity) const
Check if an entity has a component, checking it's signature.
bool isEntityAlive (EntityID entity) const
bool isEntityInstanced (const EntityName &name) const
Check if an entity is instanced.
void markForDestruction (EntityID entity)
Mark entity to be destroyed.
void registerSystem (const SystemName &name)
Registers the system in the system manager so it can be used and updated. If the system is already registered, nothing happens.
template<class Component >
void removeComponent (EntityID entity)
Remove a component from an entity.
EntityID tryGetEntityID (const EntityName &name) const
Tries to get the entity ID from the entity name.
Protected Member Functions
void printEntity (EntityID entity)
Print the status of the entity.
void printStatus (const std::string &contextMessage="")
Print the status of the ECS.
Protected Attributes
ComponentManager componentManager {}
Manager that handles the components.
std::shared_mutex ecsMutex {}
Mutex for the ECS.
std::vector< EntityID > entitiesToDestroy {}
The entities that are marked for destruction.
EntityManager entityManager {}
Manager that handles the entities.
SystemManager systemManager {}
Manager that handles the systems.
Friends
class ::ECSTests
class ECSDebugger
Detailed Description
Definition at line 31 of file ECS.h.
Constructor & Destructor Documentation
ECSCoordinator()
GLESC::ECS::ECSCoordinator::ECSCoordinator () default
Member Function Documentation
addComponent()
template<typename Component > void GLESC::ECS::ECSCoordinator::addComponent (EntityID entity, const Component & component)
Add a component to an entity.
This will store the component in a contiguous memory block and update the entity's signature. If the component is already added to the entity, nothing happens.
Template Parameters
Component The type of the component
Parameters
entity The ID of the entity
component The component to add
Definition at line 249 of file ECS.h.
{
        std::lock_guard<std::shared_mutex> lock(ecsMutex);
        PRINT_ECS_STATUS("Before adding component " + std::string(typeid(Component).name()) +
            "to entity with ID " + std::to_string(entity));
        componentManager.addComponentToEntity<Component>(entity, component);
        entityManager.addComponentToEntity(entity, componentManager.getComponentID<Component>());
        systemManager.entitySignatureChanged(entity,
                                             entityManager.getSignature(entity));
        PRINT_ECS_STATUS("After adding component " + std::string(typeid(Component).name()) +
            " to entity with ID " + std::to_string(entity));
    }
References GLESC::ECS::EntityManager::addComponentToEntity(), GLESC::ECS::ComponentManager::addComponentToEntity(), componentManager, ecsMutex, entityManager, GLESC::ECS::SystemManager::entitySignatureChanged(), GLESC::ECS::ComponentManager::getComponentID(), GLESC::ECS::EntityManager::getSignature(), GLESC::isIterable_v, PRINT_ECS_STATUS, and systemManager.
Referenced by GLESC::ECS::Entity::addComponent().
addComponentRequirementToSystem()
template<typename Component > void GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem (const SystemName & name)
Add a component requirement to the system.
This will add a component requirement to the system, therefore the system will only run on entities that have the required components. This will also update the signature of the system.
Template Parameters
Component The type of the component
Parameters
name The name of the system
Definition at line 286 of file ECS.h.
{
        std::lock_guard<std::shared_mutex> lock(ecsMutex);
        if (!systemManager.isSystemRegistered(name)) {
            Logger::get().warning("System " + name + " is not registered. Cannot add component requirement.");
            return;
        }
        PRINT_ECS_STATUS(
            std::string("Before adding component") + typeid(Component).name() + std::string(" to system ") + name);
        componentManager.registerComponentIfNotRegistered<Component>();
        systemManager.addComponentRequirementToSystem(name, componentManager.getComponentID<Component>());
        PRINT_ECS_STATUS(
            std::string("After adding component") + typeid(Component).name() + std::string(" to system ") + name);
    }
References GLESC::ECS::SystemManager::addComponentRequirementToSystem(), componentManager, ecsMutex, GLESC::Logger::get(), GLESC::ECS::ComponentManager::getComponentID(), GLESC::isIterable_v, GLESC::ECS::SystemManager::isSystemRegistered(), PRINT_ECS_STATUS, GLESC::ECS::ComponentManager::registerComponentIfNotRegistered(), systemManager, and GLESC::Logger::warning().
Referenced by GLESC::ECS::System::addComponentRequirement().
createEntity() [1/2]
EntityID ECSCoordinator::createEntity ()
Create an entity with a default name.
Returns
The ID of the entity
Definition at line 111 of file ECS.cpp.
{
    std::lock_guard lock(ecsMutex);
    std::string name = "Entity" + std::to_string(entityManager.getEntityCounter());
    D_ASSERT_FALSE(entityManager.doesEntityExist(name),
                   "Cannot create entity with name " + name + " because it already exists");
    PRINT_ECS_STATUS("Before creating entity: " + name);
    EntityID id = entityManager.createNextEntity(name,{});
    PRINT_ECS_STATUS("After entity created: " + name);
    return id;
}
References GLESC::ECS::EntityManager::createNextEntity(), D_ASSERT_FALSE, GLESC::ECS::EntityManager::doesEntityExist(), ecsMutex, entityManager, GLESC::ECS::EntityManager::getEntityCounter(), GLESC::isIterable_v, and PRINT_ECS_STATUS.
createEntity() [2/2]
EntityID ECSCoordinator::createEntity (const EntityName & name, const EntityMetadata & metadata)
Create an entity with the given name. The name must be unique.
Parameters
name The name of the entity
Returns
The ID of the entity or NULL_ENTITY if the entity name already exists.
Definition at line 98 of file ECS.cpp.
{
    std::lock_guard lock(ecsMutex);
    D_ASSERT_FALSE(entityManager.doesEntityExist(name),
                   "Cannot create entity with name " + name + " because it already exists");
    PRINT_ECS_STATUS("Before creating entity: " + name);
    EntityID id = entityManager.createNextEntity(name, metadata);
    PRINT_ECS_STATUS("After entity created: " + name);
    return id;
}
References GLESC::ECS::EntityManager::createNextEntity(), D_ASSERT_FALSE, GLESC::ECS::EntityManager::doesEntityExist(), ecsMutex, entityManager, GLESC::isIterable_v, and PRINT_ECS_STATUS.
destroyEntities()
void ECSCoordinator::destroyEntities ()
Destroy all entities marked for destruction.
Definition at line 123 of file ECS.cpp.
{
    for (EntityID entity : entitiesToDestroy) {
        destroyEntity(entity);
    }
    entitiesToDestroy.clear();
}
References destroyEntity(), entitiesToDestroy, and GLESC::isIterable_v.
Referenced by GLESC::Engine::update().
destroyEntity()
bool ECSCoordinator::destroyEntity (EntityID entity)
Destroy an entity, destroying all the components and removing it from the systems.
Parameters
entity The ID of the entity
Returns
True if the entity was destroyed, false if the entity does not exist
Definition at line 135 of file ECS.cpp.
{
    std::lock_guard lock(ecsMutex);
    D_ASSERT_TRUE(entityManager.doesEntityExist(entity), "Entity must exist");
    PRINT_ECS_STATUS("Before destroying entity: " + std::to_string(entity));
    entityManager.destroyEntity(entity);
    componentManager.entityDestroyed(entity);
    systemManager.entityDestroyed(entity);
    PRINT_ECS_STATUS("After entity destroyed: " + std::to_string(entity));
    return true;
}
References componentManager, D_ASSERT_TRUE, GLESC::ECS::EntityManager::destroyEntity(), GLESC::ECS::EntityManager::doesEntityExist(), ecsMutex, GLESC::ECS::ComponentManager::entityDestroyed(), GLESC::ECS::SystemManager::entityDestroyed(), entityManager, GLESC::isIterable_v, PRINT_ECS_STATUS, and systemManager.
Referenced by destroyEntities().
getAllEntities()
const std::unordered_map< EntityName, EntityID > & ECSCoordinator::getAllEntities () const
Get all the entities in the ECS.
Returns
A map of entity names and their IDs
Definition at line 75 of file ECS.cpp.
{
    return entityManager.getEntityNameToID();
}
References entityManager, and GLESC::ECS::EntityManager::getEntityNameToID().
Referenced by GLESC::ECS::System::getAllEntities(), and GLESC::Engine::update().
getAssociatedEntities()
const std::set< EntityID > & ECSCoordinator::getAssociatedEntities (const SystemName & name) const
Get the entities associated with a system.
Parameters
name The name of the system
Returns
A set of entities associated with the system or an empty set if the system does not exist
Definition at line 61 of file ECS.cpp.
{
    if (!systemManager.isSystemRegistered(name))
        return {};
    const auto& set = systemManager.getAssociatedEntitiesOfSystem(name);
#ifndef NDEBUG_GLESC
    for (const auto& entity : set) {
        D_ASSERT_TRUE(entityManager.doesEntityExist(entity), "Entity must exist");
        D_ASSERT_TRUE(systemManager.isEntityAssociatedWithSystem(name, entity),
                      "Entity must be associated with system");
    }
#endif
    return set;
}
References D_ASSERT_TRUE, GLESC::ECS::EntityManager::doesEntityExist(), entityManager, GLESC::ECS::SystemManager::getAssociatedEntitiesOfSystem(), GLESC::ECS::SystemManager::isEntityAssociatedWithSystem(), GLESC::isIterable_v, GLESC::ECS::SystemManager::isSystemRegistered(), and systemManager.
Referenced by GLESC::ECS::System::getAssociatedEntities().
getComponent()
template<class Component > Component & GLESC::ECS::ECSCoordinator::getComponent (EntityID entity) const
Get the component of an entity by its Id.
Template Parameters
Component The type of the component
Parameters
entity The ID of the entity
Returns
The component
Definition at line 275 of file ECS.h.
{
        D_ASSERT_TRUE(entityManager.doesEntityExist(entity), "Entity must exist");
        return componentManager.getComponent<Component>(entity);
    }
References componentManager, D_ASSERT_TRUE, GLESC::ECS::EntityManager::doesEntityExist(), entityManager, GLESC::ECS::ComponentManager::getComponent(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::Entity::getComponent(), GLESC::ECS::System::getComponent(), and GLESC::Engine::update().
getComponentID()
template<class Component > ComponentID GLESC::ECS::ECSCoordinator::getComponentID () const
Get the ID of a component.
Template Parameters
Component The type of the component
Returns
The ID of the component
Definition at line 281 of file ECS.h.
{
        return componentManager.getComponentID<Component>();
    }
References componentManager, GLESC::ECS::ComponentManager::getComponentID(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::Entity::hasComponent().
getComponents()
std::vector< IComponent * > ECSCoordinator::getComponents (EntityID entityId) const
Get the components of an entity.
This will return a vector of components that the entity has. The components are pointers to the actual components stored in the component manager. The pointers point to an interface, so the actual type of the component is unknown.
Parameters
entityId The ID of the entity
Returns
A vector of components
Definition at line 87 of file ECS.cpp.
{
    std::vector<IComponent*> components;
    Signature signature = entityManager.getSignature(entity);
    for (size_t i = 0; i < signature.size(); ++i) {
        if (signature.test(i)) {
            components.push_back(&componentManager.getComponent(entity, i));
        }
    }
    return components;
}
References componentManager, entityManager, GLESC::ECS::ComponentManager::getComponent(), GLESC::ECS::EntityManager::getSignature(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::System::getComponents().
getEntitiesToBeDestroyed()
const std::vector< EntityID > & GLESC::ECS::ECSCoordinator::getEntitiesToBeDestroyed () const inline
Definition at line 58 of file ECS.h.
{
            return entitiesToDestroy;
        }
References entitiesToDestroy.
Referenced by GLESC::Engine::update().
getEntityID()
EntityID ECSCoordinator::getEntityID (const EntityName & name) const
Get the entity ID from the entity name.
Parameters
name The name of the entity
Returns
The ID of the entity with the given name or NULL_ENTITY if the entity does not exist
Definition at line 146 of file ECS.cpp.
{
    return entityManager.getEntityID(name);
}
References entityManager, and GLESC::ECS::EntityManager::getEntityID().
Referenced by GLESC::ECS::System::getEntity(), and GLESC::ECS::EntityFactory::getEntity().
getEntityMetadata()
const EntityMetadata & ECSCoordinator::getEntityMetadata (EntityID entity) const
Get the metadata of the entity.
Parameters
entity The ID of the entity
Returns
The metadata of the entity
Definition at line 170 of file ECS.cpp.
{
    return entityManager.getEntityMetadata(entity);
}
References entityManager, GLESC::ECS::EntityManager::getEntityMetadata(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::System::getEntityMetadata().
getEntityName()
const EntityName & ECSCoordinator::getEntityName (EntityID entity) const
Get the name of the entity given the ID.
Parameters
entity The ID of the entity
Returns
The name of the entity or nullptr if the entity does not exist
Definition at line 150 of file ECS.cpp.
{
    return entityManager.getEntityName(entity);
}
References entityManager, GLESC::ECS::EntityManager::getEntityName(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::System::getEntityName(), GLESC::ECS::Entity::getName(), and GLESC::Engine::update().
getInstancedEntities()
const std::vector< EntityID > & ECSCoordinator::getInstancedEntities (const EntityName & name) const
Get the a list of entities that are instanced by the given instance name.
Parameters
name The name of the instance
Returns
A list of entity IDs that are instanced by the given instance name
Definition at line 166 of file ECS.cpp.
{
    return entityManager.getInstancedEntities(name);
}
References entityManager, and GLESC::ECS::EntityManager::getInstancedEntities().
hasComponent()
template<typename Component > bool GLESC::ECS::ECSCoordinator::hasComponent (EntityID entity) const
Check if an entity has a component, checking it's signature.
Template Parameters
System The type of the system
Parameters
entity The ID of the entity
Returns
True if the entity has the component, false otherwise
Definition at line 301 of file ECS.h.
{
        if (componentManager.isComponentRegistered<Component>()) {
            return entityManager.doesEntityHaveComponent(entity,
                                                         componentManager.getComponentID<Component>());
        }
        return false;
    }
References componentManager, GLESC::ECS::EntityManager::doesEntityHaveComponent(), entityManager, GLESC::ECS::ComponentManager::getComponentID(), GLESC::ECS::ComponentManager::isComponentRegistered(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::Entity::hasComponent(), and GLESC::Engine::update().
isEntityAlive()
bool ECSCoordinator::isEntityAlive (EntityID entity) const
Definition at line 154 of file ECS.cpp.
{
    return entityManager.isEntityAlive(entity);
}
References entityManager, GLESC::ECS::EntityManager::isEntityAlive(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::Entity::isAlive().
isEntityInstanced()
bool ECSCoordinator::isEntityInstanced (const EntityName & name) const
Check if an entity is instanced.
An entity is instanced if it's name is a name followed by a number
Parameters
name The name of the entity
Returns
True if the entity is instanced, false otherwise
Definition at line 162 of file ECS.cpp.
{
    return entityManager.isEntityInstanced(name);
}
References entityManager, and GLESC::ECS::EntityManager::isEntityInstanced().
Referenced by GLESC::Engine::update().
markForDestruction()
void ECSCoordinator::markForDestruction (EntityID entity)
Mark entity to be destroyed.
Destruction in the ECS is deferred to the end of the frame. This is to avoid invalidating iterators while iterating over the entities.
Definition at line 130 of file ECS.cpp.
{
    entitiesToDestroy.push_back(entity);
}
References entitiesToDestroy, and GLESC::isIterable_v.
Referenced by GLESC::ECS::Entity::destroy(), and GLESC::Engine::update().
printEntity()
void ECSCoordinator::printEntity (EntityID entity) protected
Print the status of the entity.
Parameters
entity The ID of the entity
Definition at line 46 of file ECS.cpp.
{
    Logger::get().info("\tEntity Name: " + entityManager.getEntityName(entity));
    Logger::get().info("\tEntityID: " + std::to_string(entity));
    Logger::get().info("\tEntity Signature: " + entityManager.getSignature(entity).to_string());
    Logger::get().info("\tEntity Components: ");
    for (const auto& component : componentManager.getComponentIDs()) {
        ComponentName componentName = component.first;
        ComponentID componentID = component.second;
        if (entityManager.doesEntityHaveComponent(entity, componentID)) {
            IComponent& componentData = componentManager.getComponent(entity, componentID);
            Logger::get().nonImportantInfo(Stringer::replace(componentData.toString(), "\n", "\n\t\t"));
        }
    }
}
References componentManager, GLESC::ECS::EntityManager::doesEntityHaveComponent(), entityManager, GLESC::Logger::get(), GLESC::ECS::ComponentManager::getComponent(), GLESC::ECS::ComponentManager::getComponentIDs(), GLESC::ECS::EntityManager::getEntityName(), GLESC::ECS::EntityManager::getSignature(), GLESC::Logger::info(), GLESC::isIterable_v, GLESC::Logger::nonImportantInfo(), and GLESC::Stringer::replace().
Referenced by printStatus().
printStatus()
void ECSCoordinator::printStatus (const std::string & contextMessage = "") protected
Print the status of the ECS.
Parameters
contextMessage The message to print before the status
Definition at line 12 of file ECS.cpp.
{
    Logger::get().importantInfoBlue("==== ECS print status - context: " + contextMessage + "====");
    Logger::get().importantInfo("Systems with their associated entities: ");
    for (const auto& system : systemManager.getSystemSignatures()) {
        SystemName systemName = system.first;
        Signature signature = system.second;
        Logger::get().info("\tSystem Name: " + systemName + " | Signature: " + signature.to_string());
        Logger::get().info("\tAssociated Entities: ");
        if (systemManager.getAssociatedEntitiesOfSystem(systemName).empty()) {
            Logger::get().info("\t\tNone");
        }
        for (const EntityID& entity : systemManager.getAssociatedEntitiesOfSystem(systemName)) {
            printEntity(entity);
        }
    }
    Logger::get().importantInfoWhite("===============================================");
    Logger::get().importantInfo("Existing entities: ");
    for (const auto& entity : entityManager.getEntityNameToID()) {
        EntityID entityID = entity.second;
        printEntity(entityID);
    }
    Logger::get().importantInfoWhite("===============================================");
    Logger::get().importantInfo("Registered components: ");
    for (const auto& component : componentManager.getComponentIDs()) {
        ComponentName componentName = component.first;
        ComponentID componentID = component.second;
        Logger::get().info(
            "\tComponent Name: " + componentName + " | ComponentID: " + Stringer::toString(componentID));
    }
    Logger::get().importantInfoWhite("===============================================");
}
References componentManager, entityManager, GLESC::Logger::get(), GLESC::ECS::SystemManager::getAssociatedEntitiesOfSystem(), GLESC::ECS::ComponentManager::getComponentIDs(), GLESC::ECS::EntityManager::getEntityNameToID(), GLESC::ECS::SystemManager::getSystemSignatures(), GLESC::Logger::importantInfo(), GLESC::Logger::importantInfoBlue(), GLESC::Logger::importantInfoWhite(), GLESC::Logger::info(), GLESC::isIterable_v, printEntity(), systemManager, and GLESC::Stringer::toString().
registerSystem()
void ECSCoordinator::registerSystem (const SystemName & name)
Registers the system in the system manager so it can be used and updated. If the system is already registered, nothing happens.
Parameters
name The name of the system
Definition at line 79 of file ECS.cpp.
{
    std::lock_guard lock(ecsMutex);
    D_ASSERT_TRUE(!systemManager.isSystemRegistered(name), "System must not be registered");
    PRINT_ECS_STATUS("Before registering system: " + name);
    systemManager.registerSystem(name);
    PRINT_ECS_STATUS("After registering system: " + name);
}
References D_ASSERT_TRUE, ecsMutex, GLESC::isIterable_v, GLESC::ECS::SystemManager::isSystemRegistered(), PRINT_ECS_STATUS, GLESC::ECS::SystemManager::registerSystem(), and systemManager.
Referenced by GLESC::ECS::System::System().
removeComponent()
template<class Component > void GLESC::ECS::ECSCoordinator::removeComponent (EntityID entity)
Remove a component from an entity.
This will remove the component from the entity's signature and from the component array. If the component is not added to the entity, nothing happens.
Template Parameters
Component The type of the component
Parameters
entity The ID of the entity
Definition at line 262 of file ECS.h.
{
        std::lock_guard<std::shared_mutex> lock(ecsMutex);
        PRINT_ECS_STATUS("Before removing component " + std::string(typeid(Component).name()) +
            " from entity with ID " + std::to_string(entity));
        componentManager.removeComponent<Component>(entity);
        entityManager.removeComponentFromEntity(entity, componentManager.getComponentID<Component>());
        systemManager.entitySignatureChanged(entity,
                                             entityManager.getSignature(entity));
        PRINT_ECS_STATUS("After removing component " + std::string(typeid(Component).name()) +
            " from entity with ID " + std::to_string(entity));
    }
References componentManager, ecsMutex, entityManager, GLESC::ECS::SystemManager::entitySignatureChanged(), GLESC::ECS::ComponentManager::getComponentID(), GLESC::ECS::EntityManager::getSignature(), GLESC::isIterable_v, PRINT_ECS_STATUS, GLESC::ECS::ComponentManager::removeComponent(), GLESC::ECS::EntityManager::removeComponentFromEntity(), and systemManager.
Referenced by GLESC::ECS::Entity::removeComponent().
tryGetEntityID()
EntityID ECSCoordinator::tryGetEntityID (const EntityName & name) const
Tries to get the entity ID from the entity name.
This will return the ID of the entity with the given name. If the entity does not exist, it will return NULL_ENTITY.
Parameters
name The name of the entity
Returns
The ID of the entity, or NULL_ENTITY if the entity does not exist
Definition at line 158 of file ECS.cpp.
{
    return entityManager.tryGetEntity(name);
}
References entityManager, and GLESC::ECS::EntityManager::tryGetEntity().
Referenced by GLESC::ECS::EntityFactory::tryGetEntity().
Friends And Related Symbol Documentation
::ECSTests
friend class ::ECSTests friend
Definition at line 32 of file ECS.h.
ECSDebugger
friend class ECSDebugger friend
Definition at line 33 of file ECS.h.
Member Data Documentation
componentManager
ComponentManager GLESC::ECS::ECSCoordinator::componentManager {} protected
Manager that handles the components.
It stores the components in contigous arrays and knows which component is linked to which entity.
Definition at line 222 of file ECS.h.
{};
Referenced by addComponent(), addComponentRequirementToSystem(), destroyEntity(), getComponent(), getComponentID(), getComponents(), hasComponent(), printEntity(), printStatus(), and removeComponent().
ecsMutex
std::shared_mutex GLESC::ECS::ECSCoordinator::ecsMutex {} mutable protected
Mutex for the ECS.
This mutex is used to lock the ECS when adding or removing components, entities or systems. Ths ensures ECS is thread safe.
Definition at line 244 of file ECS.h.
{};
Referenced by addComponent(), addComponentRequirementToSystem(), createEntity(), createEntity(), destroyEntity(), registerSystem(), and removeComponent().
entitiesToDestroy
std::vector<EntityID> GLESC::ECS::ECSCoordinator::entitiesToDestroy {} protected
The entities that are marked for destruction.
Definition at line 238 of file ECS.h.
{};
Referenced by destroyEntities(), getEntitiesToBeDestroyed(), and markForDestruction().
entityManager
EntityManager GLESC::ECS::ECSCoordinator::entityManager {} protected
Manager that handles the entities.
It stores the entities and their signatues. Also knows what entities are available and ensures the entities are unique.
Definition at line 234 of file ECS.h.
{};
Referenced by addComponent(), createEntity(), createEntity(), destroyEntity(), getAllEntities(), getAssociatedEntities(), getComponent(), getComponents(), getEntityID(), getEntityMetadata(), getEntityName(), getInstancedEntities(), hasComponent(), isEntityAlive(), isEntityInstanced(), printEntity(), printStatus(), removeComponent(), and tryGetEntityID().
systemManager
SystemManager GLESC::ECS::ECSCoordinator::systemManager {} protected
Manager that handles the systems.
It stores the systems and their signatures and knows which entities are associated with which system. It also knows which components are required by the system.
Definition at line 228 of file ECS.h.
{};
Referenced by addComponent(), addComponentRequirementToSystem(), destroyEntity(), getAssociatedEntities(), printStatus(), registerSystem(), and removeComponent().
The documentation for this class was generated from the following files:
ECS.h
ECS.cpp