GLESC: GLESC::Physics::PhysicsManager Class Reference
GLESC::Physics::PhysicsManager Class Reference
#include <PhysicsManager.h>
Public Member Functions
void applyForces (Physics &physics) const
void handleCollisions (Collider &collider, Physics &physics) const
Static Public Member Functions
static Transform::Transform updateTransform (const Transform::Transform &transform, const Physics &physics)
Static Private Member Functions
static void executeCallbacks (Collider &collider, const CollisionInformation &collisionInfo)
Private Attributes
Friction airFriction {0.01f}
Bounciness bounciness {0.1f}
float bouncinessThreshold {50.f}
Acceleration gravity {0.f, -8.91f, 0.f}
Static Private Attributes
static constexpr Scalar velocityScalar {0.001f}
This scalar is used to scale the velocity of the object.
Detailed Description
Definition at line 19 of file PhysicsManager.h.
Member Function Documentation
applyForces()
void GLESC::Physics::PhysicsManager::applyForces (Physics & physics) const
Definition at line 5 of file PhysicsManager.cpp.
{
        if (physics.isStatic()) {
            physics.setVelocity({0, 0, 0});
            physics.setAcceleration({0, 0, 0});
            physics.setForce({0, 0, 0});
            return;
        }
        // TODO: Remove magic numbers
        // Calculate acceleration
        physics.addAcceleration(physics.getForce() * 10 / physics.getMass());
        if (physics.isAffectedByGravity())
            physics.addAcceleration(gravity);
        // Calculate velocity
        physics.addVelocity(physics.getAcceleration());
        // Apply friction
        if (physics.getAirFriction() < 0.0f)
            physics.addVelocity(-physics.getVelocity() * airFriction);
        else
            physics.addVelocity(-physics.getVelocity() * physics.getAirFriction());
        // Clear forces
        physics.setForce(Force(0.0F, 0.0F, 0.0F));
        // Clear acceleration
        physics.setAcceleration(Acceleration(0.0F, 0.0F, 0.0F));
    }
References GLESC::Physics::Physics::addAcceleration(), GLESC::Physics::Physics::addVelocity(), airFriction, GLESC::Physics::Physics::getAcceleration(), GLESC::Physics::Physics::getAirFriction(), GLESC::Physics::Physics::getForce(), GLESC::Physics::Physics::getMass(), GLESC::Physics::Physics::getVelocity(), gravity, GLESC::Physics::Physics::isAffectedByGravity(), GLESC::Physics::Physics::isStatic(), GLESC::Physics::Physics::setAcceleration(), GLESC::Physics::Physics::setForce(), and GLESC::Physics::Physics::setVelocity().
Referenced by GLESC::ECS::PhysicsSystem::update().
executeCallbacks()
void GLESC::Physics::PhysicsManager::executeCallbacks (Collider & collider, const CollisionInformation & collisionInfo) static private
Definition at line 42 of file PhysicsManager.cpp.
{
        if (collider.getGeneralCollisionCallback())
            collider.getGeneralCollisionCallback()(*info.getCollidingWithColliders()[0]);
        for (auto& otherCollider : info.getCollidingWithColliders()) {
            // Check if there is a specific callback for this collider
            auto it = collider.getSpecificCollisionCallbacks().find(otherCollider);
            if (it != collider.getSpecificCollisionCallbacks().end()) {
                it->second(*otherCollider);
            }
        }
    }
References GLESC::Physics::CollisionInformation::getCollidingWithColliders(), GLESC::Physics::Collider::getGeneralCollisionCallback(), GLESC::Physics::Collider::getSpecificCollisionCallbacks(), and GLESC::isIterable_v.
Referenced by handleCollisions().
handleCollisions()
void GLESC::Physics::PhysicsManager::handleCollisions (Collider & collider, Physics & physics) const
Definition at line 107 of file PhysicsManager.cpp.
{
        CollisionInformation& info = collider.getCollisionInformation();
        executeCallbacks(collider, info);
        // If the object is static, no new velocity is needed, it will remain 0
        if (physics.isStatic()) return;
        // If the velocity is too small, we consider it as 0 so we don't have jittering
        bool bouncingOccurs = !info.wasOnGroundLastFrame() &&
            physics.getVelocity().length() > bouncinessThreshold;
        Velocity finalVelocity;
        if (bouncingOccurs) {
            // Calculate the collision normal to reflect the velocity
            Vec3F collisionNormal = {
                info.getCollidingAxis().getX(), info.getCollidingAxis().getY(), info.getCollidingAxis().getZ()
            };
            finalVelocity = getBouncingVelocity(physics.getVelocity(), collisionNormal, bounciness);
        }
        else {
            AxisConstraints freeAxis = getAxisFree(collider);
            bool frictionApplied = isFrictionApplied(physics, freeAxis);
            Vec3F velocityWithFriction;
            if (frictionApplied)
                velocityWithFriction = physics.getVelocity();
            else
                velocityWithFriction= getVelocityWithFriction(physics, info.getPhysicsOfCollided());
            for (int i = 0; i < 3; ++i) {
                if (Math::gt(velocityWithFriction[i], 0.0f))
                    velocityWithFriction[i] *= static_cast<float>(freeAxis[i][0]);
                else
                    velocityWithFriction[i] *= static_cast<float>(freeAxis[i][1]);
            }
            finalVelocity = velocityWithFriction;
        }
        physics.setVelocity(finalVelocity);
        //Apply the new velocity to the component
    }
References bounciness, bouncinessThreshold, executeCallbacks(), GLESC::Physics::getAxisFree(), GLESC::Physics::getBouncingVelocity(), GLESC::Physics::CollisionInformation::getCollidingAxis(), GLESC::Physics::Collider::getCollisionInformation(), GLESC::Physics::CollisionInformation::getPhysicsOfCollided(), GLESC::Physics::Physics::getVelocity(), GLESC::Physics::getVelocityWithFriction(), GLESC::Math::Vector< Type, N >::getX(), GLESC::Math::Vector< Type, N >::getY(), GLESC::Math::Vector< Type, N >::getZ(), GLESC::Math::gt(), GLESC::Physics::isFrictionApplied(), GLESC::isIterable_v, GLESC::Physics::Physics::isStatic(), GLESC::Math::Vector< Type, N >::length(), GLESC::Physics::Physics::setVelocity(), and GLESC::Physics::CollisionInformation::wasOnGroundLastFrame().
Referenced by GLESC::ECS::PhysicsCollisionSystem::update().
updateTransform()
Transform::Transform GLESC::Physics::PhysicsManager::updateTransform (const Transform::Transform & transform, const Physics & physics) static
Definition at line 36 of file PhysicsManager.cpp.
{
        Transform::Transform newTransform = transform;
        newTransform.addPosition(physics.getVelocity() * velocityScalar);
        return newTransform;
    }
References GLESC::Transform::Transform::addPosition(), GLESC::Physics::Physics::getVelocity(), GLESC::isIterable_v, and velocityScalar.
Referenced by GLESC::ECS::PhysicsCollisionSystem::update(), and GLESC::ECS::PhysicsSystem::update().
Member Data Documentation
airFriction
Friction GLESC::Physics::PhysicsManager::airFriction {0.01f} private
Definition at line 29 of file PhysicsManager.h.
{0.01f};
Referenced by applyForces().
bounciness
Bounciness GLESC::Physics::PhysicsManager::bounciness {0.1f} private
Definition at line 30 of file PhysicsManager.h.
{0.1f};
Referenced by handleCollisions().
bouncinessThreshold
float GLESC::Physics::PhysicsManager::bouncinessThreshold {50.f} private
Definition at line 31 of file PhysicsManager.h.
{50.f};
Referenced by handleCollisions().
gravity
Acceleration GLESC::Physics::PhysicsManager::gravity {0.f, -8.91f, 0.f} private
Definition at line 28 of file PhysicsManager.h.
{0.f, -8.91f, 0.f};
Referenced by applyForces().
velocityScalar
constexpr Scalar GLESC::Physics::PhysicsManager::velocityScalar {0.001f} static constexpr private
This scalar is used to scale the velocity of the object.
We need this because using fixed update time steps makes normal values too bit, and the object would move too fast. Using a scalar makes the used be able to handle more realistic numbers.
Definition at line 38 of file PhysicsManager.h.
{0.001f};
Referenced by updateTransform().
The documentation for this class was generated from the following files:
PhysicsManager.h
PhysicsManager.cpp