GLESC: FPSManager Class Reference
FPSManager Class Reference
#include <FPSManager.h>
Public Member Functions
FPSManager (FpsRates renderFPS, FpsRates updateFPS=Fps60)
FPSFloatingPoint getAverageRenderTimeMillis () const
Get the average time it took to render the frame.
UIntMillis getCurrentRenderTimeMillis () const
Get the time it took to render the frame.
UIntMillis getLag () const
FPSFloatingPoint getRenderFPS () const
Get the average fps of the last 60 frames.
double getTimeOfFrameAfterUpdate () const
Get the amount of frame it has passed since the beginning. The value is normalized between 0.0 and 1.0. It is used to interpolate rendering to avoid stutter.
FPSFloatingPoint getUpdateFPS () const
Get the fps of the update.
UIntMillis getUpdateTimeMillis () const
Get the constant speed in which our game updates.
bool hasSpiralOfDeathBeenReached () const
bool isUpdateLagged () const
Is the game time behind real time?
void refreshUpdateLag ()
Reduce the accumulated lag by a constant. Must be called each time update is called.
void startFrame ()
measures the frame, remembering the old frame.
Private Member Functions
void delay () const
Private Attributes
UIntMillis current {}
Time recorded at the beginning of the loop iteration.
UIntMillis elapsed {}
The actual time it elapses.
UIntMillis fpsList [averageFpsListSize] {}
List of the last 60 frames to calculate the average fps.
int fpsListIndex {0}
Index of the fpsList.
UIntMillis lag {}
Amount of time game time is behind real time.
const UIntMillis msPerRender
The max time (milliseconds) can elapse between frames.
const UIntMillis msPerUpdate
constant speed (in ms) in which our game updates
UIntMillis previous {}
Time recorded at the end of the loop iteration.
FPSAverager renderFpsAverager
The averager to calculate the average fps.
int updateCounter {}
Counter to check if the game is stuck in a loop.
Static Private Attributes
static constexpr int averageFpsListSize = 60
static constexpr UIntMillis msInASecond {1000}
static constexpr int spiralOfDeathLimit = 500
Threshold to check if the game is stuck in a loop- If the amount of updates is greater than this value, the game is stuck in a loop.
Detailed Description
Definition at line 31 of file FPSManager.h.
Constructor & Destructor Documentation
FPSManager()
FPSManager::FPSManager (FpsRates renderFPS, FpsRates updateFPS = Fps60) explicit
Definition at line 4 of file FPSManager.cpp.
    : msPerRender(renderFPS == Unlimitted ? 0 : msInASecond / static_cast<UIntMillis>(renderFPS)),
      msPerUpdate(msInASecond / static_cast<UIntMillis>(updateFPS)) {
}
Member Function Documentation
delay()
void FPSManager::delay () const private
Definition at line 53 of file FPSManager.cpp.
{
    if (msPerRender > 0) {
        UIntMillis dif = msPerRender - elapsed;
        if (dif > 0)
            SDL_Delay(dif); // Cap the Counter, wait until we get to minimum frame time
    }
}
References elapsed, and msPerRender.
Referenced by startFrame().
getAverageRenderTimeMillis()
FPSFloatingPoint FPSManager::getAverageRenderTimeMillis () const
Get the average time it took to render the frame.
Returns
Uint32
Definition at line 40 of file FPSManager.cpp.
{
    return renderFpsAverager.getAverage();
}
References FPSAverager::getAverage(), and renderFpsAverager.
Referenced by getRenderFPS(), and GLESC::Engine::registerStats().
getCurrentRenderTimeMillis()
UIntMillis FPSManager::getCurrentRenderTimeMillis () const
Get the time it took to render the frame.
Returns
Uint32
Definition at line 36 of file FPSManager.cpp.
{
    return elapsed;
}
References elapsed.
getLag()
UIntMillis FPSManager::getLag () const inline
Definition at line 102 of file FPSManager.h.
{ return lag; }
References lag.
Referenced by GLESC::Engine::registerStats().
getRenderFPS()
FPSFloatingPoint FPSManager::getRenderFPS () const
Get the average fps of the last 60 frames.
Returns
float
Definition at line 48 of file FPSManager.cpp.
{
    return msInASecond / getAverageRenderTimeMillis();
}
References getAverageRenderTimeMillis(), and msInASecond.
Referenced by GLESC::Engine::registerStats().
getTimeOfFrameAfterUpdate()
double FPSManager::getTimeOfFrameAfterUpdate () const
Get the amount of frame it has passed since the beginning. The value is normalized between 0.0 and 1.0. It is used to interpolate rendering to avoid stutter.
Returns
double between 0.0 - 1.0
Definition at line 61 of file FPSManager.cpp.
{
    return static_cast<double>(lag) / static_cast<double>(msPerUpdate);
}
References lag, and msPerUpdate.
Referenced by main(), and GLESC::Engine::registerStats().
getUpdateFPS()
FPSFloatingPoint FPSManager::getUpdateFPS () const
Get the fps of the update.
Returns
float
Definition at line 44 of file FPSManager.cpp.
{
    return static_cast<FPSFloatingPoint>(msInASecond / getUpdateTimeMillis());
}
References getUpdateTimeMillis(), and msInASecond.
Referenced by GLESC::Engine::registerStats().
getUpdateTimeMillis()
UIntMillis FPSManager::getUpdateTimeMillis () const
Get the constant speed in which our game updates.
Returns
Uint32
Definition at line 27 of file FPSManager.cpp.
{
    return msPerUpdate;
}
References msPerUpdate.
Referenced by getUpdateFPS(), and GLESC::Engine::registerStats().
hasSpiralOfDeathBeenReached()
bool FPSManager::hasSpiralOfDeathBeenReached () const
Definition at line 31 of file FPSManager.cpp.
{
    return updateCounter > spiralOfDeathLimit;
}
References spiralOfDeathLimit, and updateCounter.
Referenced by main().
isUpdateLagged()
bool FPSManager::isUpdateLagged () const
Is the game time behind real time?
Returns
true - if accumulated lag is greater than a constant
false - if accumulated lag is not greater than a constant
Definition at line 18 of file FPSManager.cpp.
{
    return lag >= msPerUpdate;
}
References lag, and msPerUpdate.
Referenced by main().
refreshUpdateLag()
void FPSManager::refreshUpdateLag ()
Reduce the accumulated lag by a constant. Must be called each time update is called.
Definition at line 22 of file FPSManager.cpp.
{
    lag -= msPerUpdate;
    updateCounter++;
}
References lag, msPerUpdate, and updateCounter.
Referenced by main().
startFrame()
void FPSManager::startFrame ()
measures the frame, remembering the old frame.
Definition at line 9 of file FPSManager.cpp.
{
    current = static_cast<UIntMillis>(SDL_GetTicks()); // Update the current frame-time
    elapsed = current - previous;
    previous = current; // Updates the previous frame-time
    lag += elapsed; // Accumulate the elapsed time inside lag
    renderFpsAverager.addFrame(elapsed);
    delay();
}
References FPSAverager::addFrame(), current, delay(), elapsed, lag, previous, and renderFpsAverager.
Referenced by main().
Member Data Documentation
averageFpsListSize
constexpr int FPSManager::averageFpsListSize = 60 static constexpr private
Definition at line 149 of file FPSManager.h.
current
UIntMillis FPSManager::current {} private
Time recorded at the beginning of the loop iteration.
Definition at line 122 of file FPSManager.h.
{};
Referenced by startFrame().
elapsed
UIntMillis FPSManager::elapsed {} private
The actual time it elapses.
Definition at line 132 of file FPSManager.h.
{};
Referenced by delay(), getCurrentRenderTimeMillis(), and startFrame().
fpsList
UIntMillis FPSManager::fpsList[averageFpsListSize] {} private
List of the last 60 frames to calculate the average fps.
Definition at line 153 of file FPSManager.h.
{};
fpsListIndex
int FPSManager::fpsListIndex {0} private
Index of the fpsList.
Definition at line 157 of file FPSManager.h.
{0};
lag
UIntMillis FPSManager::lag {} private
Amount of time game time is behind real time.
Definition at line 137 of file FPSManager.h.
{};
Referenced by getLag(), getTimeOfFrameAfterUpdate(), isUpdateLagged(), refreshUpdateLag(), and startFrame().
msInASecond
constexpr UIntMillis FPSManager::msInASecond {1000} static constexpr private
Definition at line 106 of file FPSManager.h.
{1000};
Referenced by getRenderFPS(), and getUpdateFPS().
msPerRender
const UIntMillis FPSManager::msPerRender private
The max time (milliseconds) can elapse between frames.
Definition at line 111 of file FPSManager.h.
Referenced by delay().
msPerUpdate
const UIntMillis FPSManager::msPerUpdate private
constant speed (in ms) in which our game updates
Definition at line 116 of file FPSManager.h.
Referenced by getTimeOfFrameAfterUpdate(), getUpdateTimeMillis(), isUpdateLagged(), and refreshUpdateLag().
previous
UIntMillis FPSManager::previous {} private
Time recorded at the end of the loop iteration.
Definition at line 127 of file FPSManager.h.
{};
Referenced by startFrame().
renderFpsAverager
FPSAverager FPSManager::renderFpsAverager private
The averager to calculate the average fps.
Definition at line 162 of file FPSManager.h.
Referenced by getAverageRenderTimeMillis(), and startFrame().
spiralOfDeathLimit
constexpr int FPSManager::spiralOfDeathLimit = 500 static constexpr private
Threshold to check if the game is stuck in a loop- If the amount of updates is greater than this value, the game is stuck in a loop.
Definition at line 143 of file FPSManager.h.
Referenced by hasSpiralOfDeathBeenReached().
updateCounter
int FPSManager::updateCounter {} private
Counter to check if the game is stuck in a loop.
Definition at line 147 of file FPSManager.h.
{};
Referenced by hasSpiralOfDeathBeenReached(), and refreshUpdateLag().
The documentation for this class was generated from the following files:
FPSManager.h
FPSManager.cpp