GLESC: GLESC::Render::Renderer Class Reference
GLESC::Render::Renderer Class Reference
This is the render engine of the game engine. It is resposable of sending the data to the GPU and render it.
#include <Renderer.h>
Classes
struct Camera
struct FogData
struct Sun
Public Member Functions
Renderer (WindowManager &windowManager)
~Renderer ()
void clearLightData ()
This empties all the light data from the renderer. No lights will be rendered.
void clearMeshData ()
This empties all the data from the renderer. Nothing will be rendered.
Camera getCamera () const
Shader & getDefaultShader ()
Frustum & getFrustum ()
const Frustum & getFrustum () const
float getMeshRenderCount () const
const Projection & getProjection () const
const View & getView () const
WindowDimensions getViewportSize () const
const VP & getViewProjection () const
bool hasRenderBeenCalledThisFrame () const
void remove (const ColorMesh &mesh, const Transform::Transform &transform)
This will remove the mesh and transform from the renderer data structures.
void sendLightPoint (const LightPoint &LightPoint, const Transform::Transform &transform)
This sends the light point reference to the renderer so it can be rendered.
void sendMeshData (const ColorMesh &mesh, const Material &material, const Transform::Transform &transform)
This sends the mesh data to the renderer so it can be rendered.
void setCamera (const CameraPerspective &cameraPerspective, const Transform::Transform &transform)
This sets the camera for the renderer.
void setFog (const Fog &fogParam, const Transform::Transform &transform)
This seets the fog for the renderer.
void setProjection (const Projection &projectionParam)
void setRendererUpdated ()
void setSun (const GlobalSun &sun, const GlobalAmbientLight &ambientLight, const Transform::Transform &transform)
This sets the sun for the renderer.
void setView (const View &viewParam)
Private Types
using LightTransformIndex = size_t
using MeshIndex = size_t
using MeshTransformIndex = size_t
Private Member Functions
void render (double timeOfFrame)
This renders the frame.
void renderLights (const std::vector< const LightPoint * > &lights, const std::vector< const Transform::Transform * > &lightTransforms, double timeOfFrame) const
This encapsulates the rendering of the lights, setting the uniforms.
void start (double timeOfFrame)
This starts the frame of rendering.
void swapBuffers () const
This ends the frame of rendering.
Static Private Member Functions
static void applyAmbientLight (const GlobalAmbientLight &ambientLight)
This encapsulates the application of the ambient light.
static void applyFog (const FogData &fogParam, const Position &cameraPosition)
This encapsulates the application of the fog, setting the uniforms.
static void applyMaterial (const Material &material)
This encapsulates the application of the material, setting all the uniforms of the material shader.
static void applySkybox (const Skybox &skyboxParam, const View &view, const Projection &projection)
This encapsulates the application of the skybox, calling the skybox draw method.
static void applySun (const Sun &sunParam)
This encapsulates the application of the sun, setting the uniforms.
static void applyTransform (const MV &MVMat, const MVP &MVPMat, const NormalMat &normalMat)
This encapsulates the setting of transforms of the transforms of a mesh.
static Projection createProjectionMatrix (const CameraPerspective &camera)
Static method that creates the projection matrix from a camera.
static View createViewMatrix (const Transform::Transform &transform)
Static method that creates the view matrix from a transform (transform of the camera)
static void renderInstances (MeshIndex adaptedInstances)
static void renderMesh (const ColorMesh &mesh)
This encapsulates the rendering of the mesh, calling the draw method from the GAPI with the VAO of the mesh.
Private Attributes
GlobalAmbientLight ambientLight
Camera camera
CameraPerspective defaultCameraPerspective
Transform::Transform defaultCameraTransform
FogData fog
Frustum frustum
std::mutex frustumMutex {}
bool hasRenderBeenCalled = false
std::unordered_map< const ColorMesh *, std::vector< MeshTransformIndex > > instances
std::mutex interpolationMutex {}
std::unordered_map< const Transform::Transform *, Transform::Interpolator > interpolationTransforms
This is the interpolation data structure. It stores the interpolation data for each transform.
std::vector< bool > isContainedInFrustum
std::vector< const LightPoint * > lights
std::vector< const Transform::Transform * > lightTransforms
std::vector< const ColorMesh * > meshesToRender
std::vector< const Material * > meshMaterials
std::vector< const Transform::Transform * > meshTransforms
std::mutex mvMutex {}
std::mutex mvpMutex {}
std::vector< MVP > mvps
std::vector< MV > mvs
std::mutex normalMatMutex {}
std::vector< NormalMat > normalMats
Projection projection
Shader shader
Skybox skybox
Sun sun
View view
VP viewProjection
WindowManager & windowManager
Static Private Attributes
static Counter drawCounter {}
Friends
class ::MeshRenderingTest
class GLESC::Engine
Detailed Description
This is the render engine of the game engine. It is resposable of sending the data to the GPU and render it.
The public methods are the update side of the renderer (with some exceptions). It must be executed in the update loop of the engine. While the private methods are the render side of the renderer. It must be executed in the render loop of the engine.
Definition at line 48 of file Renderer.h.
Class Documentation
GLESC::Render::Renderer::Camera
struct GLESC::Render::Renderer::Camera
Definition at line 52 of file Renderer.h.
Class Members
const CameraPerspective * camera = nullptr
const Transform * transform = nullptr
GLESC::Render::Renderer::FogData
struct GLESC::Render::Renderer::FogData
Definition at line 63 of file Renderer.h.
Class Members
const Fog * fog = nullptr
const Transform * transform = nullptr
GLESC::Render::Renderer::Sun
struct GLESC::Render::Renderer::Sun
Definition at line 57 of file Renderer.h.
Class Members
const GlobalAmbientLight * ambientLight = nullptr
const GlobalSun * sun = nullptr
const Transform * transform = nullptr
Member Typedef Documentation
LightTransformIndex
using GLESC::Render::Renderer::LightTransformIndex = size_t private
Definition at line 161 of file Renderer.h.
MeshIndex
using GLESC::Render::Renderer::MeshIndex = size_t private
Definition at line 159 of file Renderer.h.
MeshTransformIndex
using GLESC::Render::Renderer::MeshTransformIndex = size_t private
Definition at line 160 of file Renderer.h.
Constructor & Destructor Documentation
Renderer()
Renderer::Renderer (WindowManager & windowManager) explicit
Definition at line 25 of file Renderer.cpp.
                                               :
    windowManager(windowManager), shader(Shader("Shader.glsl")),
    camera(),
    projection(createProjectionMatrix(CameraPerspective())),
    view(createViewMatrix(Transform::Transform())),
    viewProjection(projection * view),
    frustum(viewProjection) {
    camera.camera = &defaultCameraPerspective;
    camera.transform = &defaultCameraTransform;
    meshesToRender.reserve(reservedSize);
    meshMaterials.reserve(reservedSize);
    meshTransforms.reserve(reservedSize);
    lights.reserve(reservedSize);
    lightTransforms.reserve(reservedSize);
    interpolationTransforms.reserve(reservedSize);
    mvs.reserve(reservedSize);
    mvps.reserve(reservedSize);
    normalMats.reserve(reservedSize);
    isContainedInFrustum.reserve(reservedSize);
}
References GLESC::Render::Renderer::Camera::camera, camera, defaultCameraPerspective, defaultCameraTransform, interpolationTransforms, isContainedInFrustum, lights, lightTransforms, meshesToRender, meshMaterials, meshTransforms, mvps, mvs, normalMats, reservedSize, and GLESC::Render::Renderer::Camera::transform.
~Renderer()
Renderer::~Renderer ()
Definition at line 256 of file Renderer.cpp.
                    {
    getGAPI().deleteContext();
}
References getGAPI().
Member Function Documentation
applyAmbientLight()
void Renderer::applyAmbientLight (const GlobalAmbientLight & ambientLight) static private
This encapsulates the application of the ambient light.
Parameters
ambientLight The ambient light class
Definition at line 141 of file Renderer.cpp.
{
    if (!ambientLight.isDirty()) return;
    Vec3F ambientColor = ambientLight.getColor().getRGBVec3FNormalized();
    float ambientIntensity = ambientLight.getIntensity();
    Shader::setUniform("uAmbient.color", ambientColor);
    Shader::setUniform("uAmbient.intensity", ambientIntensity);
    ambientLight.setClean();
}
References ambientLight, GLESC::Render::GlobalAmbientLight::getColor(), GLESC::Render::GlobalAmbientLight::getIntensity(), GLESC::Render::ColorRgb::getRGBVec3FNormalized(), GLESC::Render::GlobalAmbientLight::isDirty(), GLESC::isIterable_v, GLESC::Render::GlobalAmbientLight::setClean(), and GLESC::GAPI::Shader::setUniform().
Referenced by applySun().
applyFog()
void Renderer::applyFog (const FogData & fogParam, const Position & cameraPosition) static private
This encapsulates the application of the fog, setting the uniforms.
Parameters
fogParam
cameraPosition
Definition at line 155 of file Renderer.cpp.
{
    if (fogParam.fog == nullptr) return;
    Shader::setUniform("uFog.color", fogParam.fog->getColor().getRGBVec3FNormalized());
    Shader::setUniform("uFog.density", fogParam.fog->getDensity());
    Shader::setUniform("uFog.end", fogParam.fog->getEnd() + cameraPosition.length());
}
References GLESC::isIterable_v, and GLESC::GAPI::Shader::setUniform().
Referenced by render().
applyMaterial()
void Renderer::applyMaterial (const Material & material) static private
This encapsulates the application of the material, setting all the uniforms of the material shader.
Parameters
material
Definition at line 162 of file Renderer.cpp.
{
    //Shader::setUniform("uMaterial.diffuseIntensity",material.getDiffuseIntensity());
    //
    Shader::setUniform("uMaterial.specularColor", material.getSpecularColor().getRGBVec3FNormalized());
    Shader::setUniform("uMaterial.specularIntensity", material.getSpecularIntensity());
    //
    //Shader::setUniform("uMaterial.emissionColor",material.getEmissionColor());
    //Shader::setUniform("uMaterial.emissionIntensity",material.getEmissionIntensity());
    //
    Shader::setUniform("uMaterial.shininess", material.getShininess());
}
References GLESC::Render::ColorRgb::getRGBVec3FNormalized(), GLESC::Render::Material::getShininess(), GLESC::Render::Material::getSpecularColor(), GLESC::Render::Material::getSpecularIntensity(), and GLESC::GAPI::Shader::setUniform().
Referenced by render().
applySkybox()
void Renderer::applySkybox (const Skybox & skyboxParam, const View & view, const Projection & projection) static private
This encapsulates the application of the skybox, calling the skybox draw method.
Parameters
skyboxParam
view
projection
Definition at line 151 of file Renderer.cpp.
{
    skyboxParam.draw(view, projection);
}
References GLESC::isIterable_v, projection, and view.
Referenced by render().
applySun()
void Renderer::applySun (const Sun & sunParam) static private
This encapsulates the application of the sun, setting the uniforms.
Parameters
sunParam
Definition at line 124 of file Renderer.cpp.
{
    if (sunParam.sun == nullptr) return;
    GlobalSun sun = *sunParam.sun;
    if (!sun.isDirty()) applyAmbientLight(*sunParam.ambientLight);
    Vec3F sunColor = sun.getColor().getRGBVec3FNormalized();
    float sunIntensity = sun.getIntensity();
    Math::Direction sunDirection = sun.getDirection();
    Shader::setUniform("uGlobalSun.color", sunColor);
    Shader::setUniform("uGlobalSun.intensity", sunIntensity);
    Shader::setUniform("uSunDirection", sunDirection);
    sun.setClean();
    applyAmbientLight(*sunParam.ambientLight);
}
References applyAmbientLight(), GLESC::isIterable_v, GLESC::GAPI::Shader::setUniform(), GLESC::Render::Renderer::Sun::sun, and sun.
Referenced by render().
applyTransform()
void Renderer::applyTransform (const MV & MVMat, const MVP & MVPMat, const NormalMat & normalMat) static private
This encapsulates the setting of transforms of the transforms of a mesh.
Parameters
MVMat The model view matrix
MVPMat The model view projection matrix
normalMat The normal matrix
Definition at line 174 of file Renderer.cpp.
{
    Shader::setUniform("uMVP", MVPMat);
    Shader::setUniform("uMV", MVMat);
    Shader::setUniform("uNormalMat", normalMat);
}
References GLESC::isIterable_v, and GLESC::GAPI::Shader::setUniform().
Referenced by render().
clearLightData()
void Renderer::clearLightData ()
This empties all the light data from the renderer. No lights will be rendered.
Definition at line 250 of file Renderer.cpp.
{
    lights.clear();
    lightTransforms.clear();
}
References lights, and lightTransforms.
Referenced by GLESC::ECS::LightSystem::update().
clearMeshData()
void Renderer::clearMeshData ()
This empties all the data from the renderer. Nothing will be rendered.
Definition at line 239 of file Renderer.cpp.
{
    meshesToRender.clear();
    meshMaterials.clear();
    meshTransforms.clear();
    instances.clear();
    mvs.clear();
    mvps.clear();
    normalMats.clear();
    isContainedInFrustum.clear();
}
References instances, isContainedInFrustum, meshesToRender, meshMaterials, meshTransforms, mvps, mvs, and normalMats.
Referenced by GLESC::ECS::RenderSystem::update().
createProjectionMatrix()
Projection Renderer::createProjectionMatrix (const CameraPerspective & camera) static private
Static method that creates the projection matrix from a camera.
Parameters
camera
Returns
Definition at line 50 of file Renderer.cpp.
{
    Projection projection;
    projection.makeProjectionMatrix(camera.getFovDegrees(), camera.getNearPlane(),
                                    camera.getFarPlane(),
                                    camera.getViewWidth(),
                                    camera.getViewHeight());
    return projection;
}
References camera, GLESC::Math::Matrix< Type, N, M >::makeProjectionMatrix(), and projection.
createViewMatrix()
View Renderer::createViewMatrix (const Transform::Transform & transform) static private
Static method that creates the view matrix from a transform (transform of the camera)
Parameters
transform
Returns
Definition at line 59 of file Renderer.cpp.
{
    View view;
    view.makeViewMatrixPosRot(transform.getPosition(), transform.getRotation().toRads());
    return view;
}
References GLESC::Transform::Transform::getPosition(), GLESC::Transform::Transform::getRotation(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot(), GLESC::Math::Vector< Type, N >::toRads(), and view.
getCamera()
Camera GLESC::Render::Renderer::getCamera () const inline
Definition at line 83 of file Renderer.h.
{ return this->camera; }
References camera.
getDefaultShader()
Shader & GLESC::Render::Renderer::getDefaultShader () inline
Definition at line 86 of file Renderer.h.
{ return shader; }
References shader.
getFrustum() [1/2]
Frustum & GLESC::Render::Renderer::getFrustum () inline
Definition at line 87 of file Renderer.h.
{ return frustum; }
References frustum.
Referenced by GLESC::HUD::DebugItems::windowContent().
getFrustum() [2/2]
const Frustum & GLESC::Render::Renderer::getFrustum () const inline
Definition at line 88 of file Renderer.h.
{ return frustum; }
References frustum.
getMeshRenderCount()
float GLESC::Render::Renderer::getMeshRenderCount () const inline
Definition at line 89 of file Renderer.h.
{ return drawCounter.getCount(); }
References drawCounter, and Counter::getCount().
Referenced by GLESC::Engine::registerStats().
getProjection()
const Projection & GLESC::Render::Renderer::getProjection () const inline
Definition at line 75 of file Renderer.h.
{ return projection; }
References projection.
Referenced by GLESC::Engine::registerStats(), and render().
getView()
const View & GLESC::Render::Renderer::getView () const inline
Definition at line 72 of file Renderer.h.
{ return view; }
References view.
Referenced by GLESC::Engine::registerStats(), render(), and renderLights().
getViewportSize()
WindowDimensions GLESC::Render::Renderer::getViewportSize () const inline
Definition at line 82 of file Renderer.h.
{ return windowManager.getSize(); }
References GLESC::WindowManager::getSize(), and windowManager.
Referenced by GLESC::HUD::DebugItems::windowContent().
getViewProjection()
const VP & GLESC::Render::Renderer::getViewProjection () const inline
Definition at line 78 of file Renderer.h.
{ return viewProjection; }
References viewProjection.
Referenced by render(), and GLESC::HUD::DebugItems::windowContent().
hasRenderBeenCalledThisFrame()
bool GLESC::Render::Renderer::hasRenderBeenCalledThisFrame () const inline
Definition at line 79 of file Renderer.h.
{ return hasRenderBeenCalled; }
References hasRenderBeenCalled.
Referenced by GLESC::ECS::FogSystem::update(), GLESC::ECS::LightSystem::update(), GLESC::ECS::RenderSystem::update(), and GLESC::ECS::SunSystem::update().
remove()
void Renderer::remove (const ColorMesh & mesh, const Transform::Transform & transform)
This will remove the mesh and transform from the renderer data structures.
Parameters
mesh
transform
Definition at line 338 of file Renderer.cpp.
{
    interpolationTransforms.erase(&transform);
}
References interpolationTransforms.
Referenced by GLESC::Engine::update().
render()
void Renderer::render (double timeOfFrame) private
This renders the frame.
This renders all the elements of the renderer, including meshes, lights, skybox, etc.
Parameters
timeOfFrame The time of the frame in fraction, used for interpolation.
Definition at line 180 of file Renderer.cpp.
{
    drawCounter.startCounter();
    const View& viewMat = getView();
    const Projection& projMat = getProjection();
    const VP& viewProjMat = getViewProjection();
    shader.bind(); // Activate the shader program before transform, material and lighting setup
    frustum.update(viewProjMat);
//#pragma omp parallel for default(shared) schedule(dynamic)
    for (int meshIndex = 0; meshIndex < meshesToRender.size(); meshIndex++) {
        const ColorMesh& mesh = *meshesToRender[meshIndex];
        const Transform::Transform& transform = *meshTransforms[meshIndex];
        Transform::Transform interpolatedTransform =
            interpolationTransforms[&transform].interpolate(static_cast<float>(timeOfFrame));
        Model model = interpolatedTransform.getModelMatrix();
        Math::BoundingVolume transformedBoundingVol =
            Transform::Transformer::transformBoundingVolume(mesh.getBoundingVolume(), interpolatedTransform);
        {
            std::lock_guard lockMutex(frustumMutex);
            isContainedInFrustum.push_back(frustum.contains(transformedBoundingVol));
        }
        MVP MVPMat = viewProjMat * model;
        MV MV = viewMat * model;
        NormalMat normalMat;
        normalMat.makeNormalMatrix(MV);
        {
            std::lock_guard lockMVP(mvpMutex);
            mvs.push_back(MV);
        }
        {
            std::lock_guard lockMV(mvMutex);
            mvps.push_back(MVPMat);
        }
        {
            std::lock_guard lockNormalMat(normalMatMutex);
            normalMats.push_back(normalMat);
        }
    }
    std::string renderedMeshesPtr;
    for (int i = 0; i < meshesToRender.size(); i++) {
        if (!isContainedInFrustum[i]) continue;
        const ColorMesh& mesh = *meshesToRender[i];
        const Material& material = *meshMaterials[i];
        applyTransform(mvs[i], mvps[i], normalMats[i]);
        applyMaterial(material);
        mesh.sendToGpuBuffers();
        renderMesh(mesh);
        renderedMeshesPtr += std::to_string(i) + " ";
    }
    renderLights(lights, lightTransforms, timeOfFrame);
    applySun(sun);
    applyFog(fog, camera.transform->getPosition());
    applySkybox(skybox, viewMat, projMat);
    hasRenderBeenCalled = true;
}
References applyFog(), applyMaterial(), applySkybox(), applySun(), applyTransform(), GLESC::GAPI::Shader::bind(), camera, GLESC::Render::Frustum::contains(), drawCounter, fog, frustum, frustumMutex, GLESC::Render::Mesh< VertexT >::getBoundingVolume(), GLESC::Transform::Transform::getPosition(), getProjection(), getView(), getViewProjection(), hasRenderBeenCalled, interpolationTransforms, isContainedInFrustum, GLESC::isIterable_v, lights, lightTransforms, GLESC::Math::Matrix< Type, N, M >::makeNormalMatrix(), meshesToRender, meshMaterials, meshTransforms, mvMutex, mvpMutex, mvps, mvs, normalMatMutex, normalMats, renderLights(), renderMesh(), GLESC::Render::Mesh< VertexT >::sendToGpuBuffers(), shader, skybox, Counter::startCounter(), sun, GLESC::Render::Renderer::Camera::transform, GLESC::Transform::Transformer::transformBoundingVolume(), and GLESC::Render::Frustum::update().
Referenced by GLESC::Engine::render().
renderInstances()
void Renderer::renderInstances (MeshIndex adaptedInstances) static private
Definition at line 268 of file Renderer.cpp.
{
}
renderLights()
void Renderer::renderLights (const std::vector< const LightPoint * > & lights, const std::vector< const Transform::Transform * > & lightTransforms, double timeOfFrame) const private
This encapsulates the rendering of the lights, setting the uniforms.
Parameters
lights
lightTransforms
timeOfFrame
Definition at line 95 of file Renderer.cpp.
{
    size_t lightCount = static_cast<int>(lights.size());
    Shader::setUniform("uLights.count", lightCount);
    for (size_t lightIndex = 0; lightIndex < lightCount; lightIndex++) {
        const LightPoint& light = *lights[lightIndex];
        std::string iStr = std::to_string(lightIndex);
        const Transform::Transform& transform = *lightTransforms[lightIndex];
        const Transform::Transform& interpolatedTransform =
            interpolationTransforms.at(&transform).interpolate(static_cast<float>(timeOfFrame));
        Position lightPosViewSpace =
            Transform::Transformer::transformVector(interpolatedTransform.getPosition(), getView());
        Shader::setUniform("uLights.posInViewSpace[" + iStr + "]", lightPosViewSpace);
        if (!light.isDirty()) continue;
        Vec3F lightColor = light.getColor().getRGBVec3FNormalized();
        float lightIntensity = light.getIntensity();
        float lightRadius = light.getRadius();
        Shader::setUniform("uLights.color[" + iStr + "]", lightColor);
        Shader::setUniform("uLights.intensity[" + iStr + "]", lightIntensity);
        Shader::setUniform("uLights.radius[" + iStr + "]", lightRadius);
        light.setClean();
    }
}
References GLESC::Render::LightPoint::getColor(), GLESC::Render::LightPoint::getIntensity(), GLESC::Render::LightPoint::getRadius(), GLESC::Render::ColorRgb::getRGBVec3FNormalized(), getView(), interpolationTransforms, GLESC::Render::LightPoint::isDirty(), GLESC::isIterable_v, lights, lightTransforms, GLESC::Render::LightPoint::setClean(), GLESC::GAPI::Shader::setUniform(), and GLESC::Transform::Transformer::transformVector().
Referenced by render().
renderMesh()
void Renderer::renderMesh (const ColorMesh & mesh) static private
This encapsulates the rendering of the mesh, calling the draw method from the GAPI with the VAO of the mesh.
Parameters
mesh
Definition at line 261 of file Renderer.cpp.
{
    // Bind the VAO before drawing
    mesh.getVertexArray().bind();
    getGAPI().drawTrianglesIndexed(mesh.getIndexBuffer().getCount());
    drawCounter.addToCounter(1);
}
References Counter::addToCounter(), GLESC::GAPI::VertexArray::bind(), drawCounter, GLESC::GAPI::IndexBuffer::getCount(), getGAPI(), GLESC::Render::Mesh< VertexT >::getIndexBuffer(), and GLESC::Render::Mesh< VertexT >::getVertexArray().
Referenced by render().
sendLightPoint()
void Renderer::sendLightPoint (const LightPoint & LightPoint, const Transform::Transform & transform)
This sends the light point reference to the renderer so it can be rendered.
Parameters
LightPoint
transform
Definition at line 311 of file Renderer.cpp.
{
    this->lightTransforms.push_back(&transform);
    this->lights.push_back(&light);
    this->interpolationTransforms[&transform].pushTransform(transform);
}
References interpolationTransforms, lights, and lightTransforms.
Referenced by GLESC::ECS::LightSystem::update().
sendMeshData()
void Renderer::sendMeshData (const ColorMesh & mesh, const Material & material, const Transform::Transform & transform)
This sends the mesh data to the renderer so it can be rendered.
Parameters
mesh
material
transform
Definition at line 275 of file Renderer.cpp.
{
    D_ASSERT_TRUE(!mesh.isBeingBuilt(), "Mesh is being built");
    RenderType renderType = mesh.getRenderType();
    interpolationTransforms[&transform].pushTransform(transform);
    if (mesh.getVertices().empty()) {
        Console::warn("Mesh has no vertices");
        return;
    }
    if (renderType == RenderType::SingleDrawStatic) {
        D_ASSERT_TRUE(false, "Static meshes are not supported");
        return;
    }
    if (renderType == RenderType::InstancedStatic) {
        D_ASSERT_TRUE(false, "Instanced static meshes are not supported");
        return;
    }
    if (renderType == RenderType::InstancedDynamic) {
        meshesToRender.push_back(&mesh);
        meshMaterials.push_back(&material);
        meshTransforms.push_back(&transform);
        instances[&mesh].push_back(meshTransforms.size());
        return;
    }
    if (renderType == RenderType::SingleDrawDynamic) {
        meshesToRender.push_back(&mesh);
        meshMaterials.push_back(&material);
        meshTransforms.push_back(&transform);
        return;
    }
    D_ASSERT_TRUE(false, "Unknown render type");
}
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::getRenderType(), GLESC::Render::Mesh< VertexT >::getVertices(), GLESC::Render::InstancedDynamic, GLESC::Render::InstancedStatic, instances, interpolationTransforms, GLESC::Render::Mesh< VertexT >::isBeingBuilt(), meshesToRender, meshMaterials, meshTransforms, GLESC::Render::SingleDrawDynamic, GLESC::Render::SingleDrawStatic, and GLESC::Console::warn().
Referenced by GLESC::ECS::RenderSystem::update().
setCamera()
void Renderer::setCamera (const CameraPerspective & cameraPerspective, const Transform::Transform & transform)
This sets the camera for the renderer.
Parameters
cameraPerspective
transform
Definition at line 331 of file Renderer.cpp.
{
    this->camera.camera = &cameraPerspective;
    this->camera.transform = &transform;
    this->interpolationTransforms[&transform].pushTransform(transform);
}
References GLESC::Render::Renderer::Camera::camera, camera, interpolationTransforms, GLESC::isIterable_v, and GLESC::Render::Renderer::Camera::transform.
Referenced by GLESC::ECS::CameraSystem::update().
setFog()
void Renderer::setFog (const Fog & fogParam, const Transform::Transform & transform)
This seets the fog for the renderer.
Parameters
fogParam
transform
Definition at line 325 of file Renderer.cpp.
{
    this->fog.fog = &fogParam;
    this->fog.transform = &transform;
    this->interpolationTransforms[&transform].pushTransform(transform);
}
References GLESC::Render::Renderer::FogData::fog, fog, interpolationTransforms, GLESC::isIterable_v, and GLESC::Render::Renderer::FogData::transform.
Referenced by GLESC::ECS::FogSystem::update().
setProjection()
void GLESC::Render::Renderer::setProjection (const Projection & projectionParam) inline
Definition at line 76 of file Renderer.h.
{ this->projection = projectionParam; }
References GLESC::isIterable_v, and projection.
Referenced by start().
setRendererUpdated()
void GLESC::Render::Renderer::setRendererUpdated () inline
Definition at line 80 of file Renderer.h.
{ hasRenderBeenCalled = false; }
References hasRenderBeenCalled.
Referenced by GLESC::Engine::update().
setSun()
void Renderer::setSun (const GlobalSun & sun, const GlobalAmbientLight & ambientLight, const Transform::Transform & transform)
This sets the sun for the renderer.
Parameters
sun
ambientLight
transform
Definition at line 317 of file Renderer.cpp.
{
    this->sun.sun = &sun;
    this->sun.ambientLight = &ambientLight;
    this->sun.transform = &transform;
    this->interpolationTransforms[&transform].pushTransform(transform);
}
References ambientLight, interpolationTransforms, and sun.
Referenced by GLESC::ECS::SunSystem::update().
setView()
void GLESC::Render::Renderer::setView (const View & viewParam) inline
Definition at line 73 of file Renderer.h.
{ this->view = viewParam; }
References GLESC::isIterable_v, and view.
Referenced by start().
start()
void Renderer::start (double timeOfFrame) private
This starts the frame of rendering.
This will clear the buffers and prepare the matrices for rendering.
Parameters
timeOfFrame The time of the frame in fraction.
Definition at line 70 of file Renderer.cpp.
{
    getGAPI().clear({
        Enums::ClearBits::Color,
        Enums::ClearBits::Depth,
        Enums::ClearBits::Stencil
    });
    getGAPI().clearColor(0.2f, 0.3f, 0.3f, 1.0f);
    // TODO: Enable the renderer to work with multiple projection and view matrices (multiple cameras)
    Projection projection;
    projection.makeProjectionMatrix(camera.camera->getFovDegrees(), camera.camera->getNearPlane(),
                                    camera.camera->getFarPlane(),
                                    camera.camera->getViewWidth(),
                                    camera.camera->getViewHeight());
    this->setProjection(projection);
    const Transform::Transform interpolatedTransform =
        interpolationTransforms[camera.transform].interpolate(static_cast<float>(timeOfFrame));
    View view;
    view.makeViewMatrixPosRot(interpolatedTransform.getPosition(), interpolatedTransform.getRotation().toRads());
    this->setView(view);
    viewProjection = projection * view;
}
References GLESC::Render::Renderer::Camera::camera, camera, GLESC::Render::CameraPerspective::getFarPlane(), GLESC::Render::CameraPerspective::getFovDegrees(), getGAPI(), GLESC::Render::CameraPerspective::getNearPlane(), GLESC::Render::CameraPerspective::getViewHeight(), GLESC::Render::CameraPerspective::getViewWidth(), interpolationTransforms, GLESC::isIterable_v, GLESC::Math::Matrix< Type, N, M >::makeProjectionMatrix(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot(), projection, setProjection(), setView(), GLESC::Render::Renderer::Camera::transform, view, and viewProjection.
Referenced by GLESC::Engine::render().
swapBuffers()
void Renderer::swapBuffers () const private
This ends the frame of rendering.
This will swap the buffers and clean the renderer data structures.
Definition at line 66 of file Renderer.cpp.
{
    getGAPI().swapBuffers(windowManager.getWindow());
}
References getGAPI(), GLESC::WindowManager::getWindow(), and windowManager.
Referenced by GLESC::Engine::render().
Friends And Related Symbol Documentation
::MeshRenderingTest
friend class ::MeshRenderingTest friend
Definition at line 50 of file Renderer.h.
GLESC::Engine
friend class GLESC::Engine friend
Definition at line 49 of file Renderer.h.
Member Data Documentation
ambientLight
GlobalAmbientLight GLESC::Render::Renderer::ambientLight private
Definition at line 260 of file Renderer.h.
Referenced by applyAmbientLight(), and setSun().
camera
Camera GLESC::Render::Renderer::camera private
Definition at line 262 of file Renderer.h.
Referenced by Renderer(), createProjectionMatrix(), getCamera(), render(), setCamera(), and start().
defaultCameraPerspective
CameraPerspective GLESC::Render::Renderer::defaultCameraPerspective private
Definition at line 255 of file Renderer.h.
Referenced by Renderer().
defaultCameraTransform
Transform::Transform GLESC::Render::Renderer::defaultCameraTransform private
Definition at line 256 of file Renderer.h.
Referenced by Renderer().
drawCounter
Counter Renderer::drawCounter {} static private
Definition at line 268 of file Renderer.h.
Referenced by getMeshRenderCount(), render(), and renderMesh().
fog
FogData GLESC::Render::Renderer::fog private
Definition at line 258 of file Renderer.h.
Referenced by render(), and setFog().
frustum
Frustum GLESC::Render::Renderer::frustum private
Definition at line 266 of file Renderer.h.
Referenced by getFrustum(), getFrustum(), and render().
frustumMutex
std::mutex GLESC::Render::Renderer::frustumMutex {} mutable private
Definition at line 275 of file Renderer.h.
{};
Referenced by render().
hasRenderBeenCalled
bool GLESC::Render::Renderer::hasRenderBeenCalled = false private
Definition at line 251 of file Renderer.h.
Referenced by hasRenderBeenCalledThisFrame(), render(), and setRendererUpdated().
instances
std::unordered_map<const ColorMesh*, std::vector<MeshTransformIndex> > GLESC::Render::Renderer::instances private
Definition at line 236 of file Renderer.h.
Referenced by clearMeshData(), and sendMeshData().
interpolationMutex
std::mutex GLESC::Render::Renderer::interpolationMutex {} mutable private
Definition at line 271 of file Renderer.h.
{};
interpolationTransforms
std::unordered_map<const Transform::Transform*, Transform::Interpolator> GLESC::Render::Renderer::interpolationTransforms private
This is the interpolation data structure. It stores the interpolation data for each transform.
Definition at line 244 of file Renderer.h.
Referenced by Renderer(), remove(), render(), renderLights(), sendLightPoint(), sendMeshData(), setCamera(), setFog(), setSun(), and start().
isContainedInFrustum
std::vector<bool> GLESC::Render::Renderer::isContainedInFrustum private
Definition at line 249 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), and render().
lights
std::vector<const LightPoint*> GLESC::Render::Renderer::lights private
Definition at line 238 of file Renderer.h.
Referenced by Renderer(), clearLightData(), render(), renderLights(), and sendLightPoint().
lightTransforms
std::vector<const Transform::Transform*> GLESC::Render::Renderer::lightTransforms private
Definition at line 239 of file Renderer.h.
Referenced by Renderer(), clearLightData(), render(), renderLights(), and sendLightPoint().
meshesToRender
std::vector<const ColorMesh*> GLESC::Render::Renderer::meshesToRender private
Definition at line 232 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), render(), and sendMeshData().
meshMaterials
std::vector<const Material*> GLESC::Render::Renderer::meshMaterials private
Definition at line 233 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), render(), and sendMeshData().
meshTransforms
std::vector<const Transform::Transform*> GLESC::Render::Renderer::meshTransforms private
Definition at line 234 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), render(), and sendMeshData().
mvMutex
std::mutex GLESC::Render::Renderer::mvMutex {} mutable private
Definition at line 273 of file Renderer.h.
{};
Referenced by render().
mvpMutex
std::mutex GLESC::Render::Renderer::mvpMutex {} mutable private
Definition at line 272 of file Renderer.h.
{};
Referenced by render().
mvps
std::vector<MVP> GLESC::Render::Renderer::mvps private
Definition at line 246 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), and render().
mvs
std::vector<MV> GLESC::Render::Renderer::mvs private
Definition at line 247 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), and render().
normalMatMutex
std::mutex GLESC::Render::Renderer::normalMatMutex {} mutable private
Definition at line 274 of file Renderer.h.
{};
Referenced by render().
normalMats
std::vector<NormalMat> GLESC::Render::Renderer::normalMats private
Definition at line 248 of file Renderer.h.
Referenced by Renderer(), clearMeshData(), and render().
projection
Projection GLESC::Render::Renderer::projection private
Definition at line 263 of file Renderer.h.
Referenced by applySkybox(), createProjectionMatrix(), getProjection(), setProjection(), and start().
shader
Shader GLESC::Render::Renderer::shader private
Definition at line 254 of file Renderer.h.
Referenced by getDefaultShader(), and render().
skybox
Skybox GLESC::Render::Renderer::skybox private
Definition at line 257 of file Renderer.h.
Referenced by render().
sun
Sun GLESC::Render::Renderer::sun private
Definition at line 259 of file Renderer.h.
Referenced by applySun(), render(), and setSun().
view
View GLESC::Render::Renderer::view private
Definition at line 264 of file Renderer.h.
Referenced by applySkybox(), createViewMatrix(), getView(), setView(), and start().
viewProjection
VP GLESC::Render::Renderer::viewProjection private
Definition at line 265 of file Renderer.h.
Referenced by getViewProjection(), and start().
windowManager
WindowManager& GLESC::Render::Renderer::windowManager private
Definition at line 230 of file Renderer.h.
Referenced by getViewportSize(), and swapBuffers().
The documentation for this class was generated from the following files:
Renderer.h
Renderer.cpp