GLESC: GLESC::Input::InputManager Class Reference
GLESC::Input::InputManager Class Reference
The InputManager class handles user input events such as keyboard and mouse events. It provides methods to initialize the input manager, update the input state, and check if a specific key is pressed. The class also handles event handling functions for keyboard and mouse events. The mouse position and key map are stored as private member variables.
#include <InputManager.h>
Public Member Functions
InputManager (HUD::HUDManager &hudManager, WindowManager &windowManager)
Constructs an instance of the InputManager class.
~InputManager ()=default
Nothing to delete, use default destructor.
bool checkKeyAction (const KeyInput &keyInput)
Checks if a specific key is currently pressed.
const MousePosition & getMousePosition () const
Retrieves the current mouse position.
std::vector< Key > getPressedKeys () const
Get the current pressed keys.
bool isMouseRelative ()
Gets whether the mouse is relative or not.
void setMouseRelative (bool enabled)
Enables mouse If enabled mouse is visible and position is absolute (allows moving it across the window) If disabled mouse is hidden and position is relative (stays in center)
void update (bool &running)
Updates the input manager by processing the current input state.
Private Member Functions
void addToBuffer (int posDx, int posDy)
Adds the delta values of the mouse position to the delta buffer.
MousePosition getAvgMousePos () const
Calculates the average postion of the mouse from the delta buffer. If the position is less than the deadzone, it will be set to 0.
void handleKeyEvent (const SDL_Event &event)
Handles the keyboard event by updating the key map with the current key state.
void handleMouseButton (const SDL_Event &event)
Handles the mouse button event by updating the key map with the current key state.
void handleMouseMotion (const SDL_Event &event)
Handles the mouse motion event by updating the mouse position.
void handleWindowEvent (const SDL_Event &event)
void lerpMousePos (MousePosition &oldMousePos, const MousePosition &targetMousePos) const
Linearly interpolates the mouse position to smooth out the mouse movement.
void updateKeyState (Key key, bool pressed)
Updates the state of a specific key in the key map.
Private Attributes
const size_t bufferSize = 5
The size of the buffer used to store the delta values of the mouse position.
const float deadzone = 1
The deadzone used to filter out small mouse movements.
std::deque< Vec2F > deltaBuffer
The buffer used to store the delta values of the mouse position.
HUD::HUDManager & hudManager
The HUDManager instance used to handle HUD events.
KeyMap keyMap {}
The key map used to store the state of each key.
MousePosition mousePos {}
Represents the current mouse position.
float mouseSmoothFactor {0.1f}
The smooth factor used to smooth out the mouse movement.
std::unordered_map< const KeyInput *, bool > pressedOnceDetection
A map of bools used to detect if a key was pressed once. Will be initialized dynamically, if a key is checked and its one time press is not initialized, it will be initialized with true (has been pressed once).
MousePosition targetMousePos {}
The target mouse position used to smooth out the mouse movement.
WindowManager & windowManager
Detailed Description
The InputManager class handles user input events such as keyboard and mouse events. It provides methods to initialize the input manager, update the input state, and check if a specific key is pressed. The class also handles event handling functions for keyboard and mouse events. The mouse position and key map are stored as private member variables.
Definition at line 27 of file InputManager.h.
Constructor & Destructor Documentation
InputManager()
InputManager::InputManager (HUD::HUDManager & hudManager, WindowManager & windowManager)
Constructs an instance of the InputManager class.
Definition at line 10 of file InputManager.cpp.
                                                                                  : hudManager(hudManager),
    windowManager(windowManager) {
}
~InputManager()
GLESC::Input::InputManager::~InputManager () default
Nothing to delete, use default destructor.
Member Function Documentation
addToBuffer()
void InputManager::addToBuffer (int posDx, int posDy) private
Adds the delta values of the mouse position to the delta buffer.
Parameters
posDx - The delta x value of the mouse position.
posDy - The delta y value of the mouse position.
Definition at line 87 of file InputManager.cpp.
{
    if (deltaBuffer.size() >= bufferSize) {
        deltaBuffer.pop_front();
    }
    deltaBuffer.emplace_back(static_cast<float>(posDx) * 0.1f, static_cast<float>(posDy) * 0.1f);
}
References bufferSize, deltaBuffer, and GLESC::isIterable_v.
Referenced by update().
checkKeyAction()
bool InputManager::checkKeyAction (const KeyInput & keyInput)
Checks if a specific key is currently pressed.
Parameters
keyInput - The key to check.
Returns
true if the key is pressed, false otherwise.
Definition at line 152 of file InputManager.cpp.
{
    auto it = keyMap.find(keyInput.key);
    if (it != keyMap.end()) {
        auto& state = it->second;
        switch (keyInput.action) {
        case KeyAction::ONGOING_PRESSED:
            return state.pressed;
        case KeyAction::ONCE_PRESSED:
            if (state.justPressed) {
                state.justPressed = false; // Reset the flag
                return true;
            }
            break;
        case KeyAction::ONCE_RELEASED:
            if (state.justReleased) {
                state.justReleased = false; // Reset the flag
                return true;
            }
            break;
        default:
            break;
        }
    }
    return false;
}
References GLESC::isIterable_v, keyMap, GLESC::Input::ONCE_PRESSED, GLESC::Input::ONCE_RELEASED, and GLESC::Input::ONGOING_PRESSED.
Referenced by GLESC::ECS::InputSystem::update().
getAvgMousePos()
MousePosition InputManager::getAvgMousePos () const private
Calculates the average postion of the mouse from the delta buffer. If the position is less than the deadzone, it will be set to 0.
Returns
the average mouse position of the mouse
Definition at line 127 of file InputManager.cpp.
{
    float sumX = 0, sumY = 0;
    for (const auto& delta : deltaBuffer) {
        sumX += delta.getX();
        sumY += delta.getY();
    }
    if (!deltaBuffer.empty()) {
        float avgX = sumX / static_cast<float>(deltaBuffer.size());
        float avgY = sumY / static_cast<float>(deltaBuffer.size());
        return MousePosition{
            avgX,
            avgY
        };
    }
    return MousePosition{0, 0};
}
References deltaBuffer, GLESC::Math::Vector< Type, N >::getX(), and GLESC::isIterable_v.
Referenced by update().
getMousePosition()
const MousePosition & GLESC::Input::InputManager::getMousePosition () const inline
Retrieves the current mouse position.
Returns
the current mouse position as a MousePosition object.
Definition at line 54 of file InputManager.h.
{ return mousePos; }
References mousePos.
Referenced by GLESC::Engine::registerStats(), and GLESC::ECS::InputSystem::update().
getPressedKeys()
std::vector< Key > InputManager::getPressedKeys () const
Get the current pressed keys.
Returns
A vector of all keys that are currently pressed
Definition at line 117 of file InputManager.cpp.
{
    std::vector<Key> pressedKeys;
    for (const auto& [key, state] : keyMap) {
        if (state.pressed) {
            pressedKeys.push_back(key);
        }
    }
    return pressedKeys;
}
References GLESC::isIterable_v, and keyMap.
Referenced by GLESC::Engine::registerStats().
handleKeyEvent()
void InputManager::handleKeyEvent (const SDL_Event & event) private
Handles the keyboard event by updating the key map with the current key state.
Parameters
event - The keyboard event to handle.
Definition at line 65 of file InputManager.cpp.
{
    auto keycode = static_cast<Key>(event.key.keysym.sym);
    bool pressed = event.type == SDL_KEYDOWN;
    updateKeyState(keycode, pressed);
}
References GLESC::isIterable_v, and updateKeyState().
Referenced by update().
handleMouseButton()
void InputManager::handleMouseButton (const SDL_Event & event) private
Handles the mouse button event by updating the key map with the current key state.
Parameters
event - The mouse button event to handle.
Definition at line 71 of file InputManager.cpp.
{
    D_ASSERT_TRUE(event.type == SDL_MOUSEBUTTONDOWN || event.type == SDL_MOUSEBUTTONUP, "Invalid event type");
    auto mouseButton = static_cast<Key>(event.button.button);
    bool pressed = event.type == SDL_MOUSEBUTTONDOWN;
    updateKeyState(mouseButton, pressed);
}
References D_ASSERT_TRUE, GLESC::isIterable_v, and updateKeyState().
Referenced by update().
handleMouseMotion()
void InputManager::handleMouseMotion (const SDL_Event & event) private
Handles the mouse motion event by updating the mouse position.
Parameters
event - The mouse event to handle.
Definition at line 78 of file InputManager.cpp.
{
    if (SDL_GetRelativeMouseMode() == SDL_FALSE) {
        if (event.type == SDL_MOUSEMOTION) {
            mousePos.x() = static_cast<float>(event.motion.x);
            mousePos.y() = static_cast<float>(event.motion.y);
        }
    }
}
References GLESC::isIterable_v, mousePos, GLESC::Math::Vector< Type, N >::x(), and GLESC::Math::Vector< Type, N >::y().
Referenced by update().
handleWindowEvent()
void InputManager::handleWindowEvent (const SDL_Event & event) private
Definition at line 14 of file InputManager.cpp.
{
    switch (event.window.event) {
    case SDL_WINDOWEVENT_RESIZED:
    case SDL_WINDOWEVENT_SIZE_CHANGED:
        // Update the internal size in the window manager.
        windowManager.setSize(event.window.data1, event.window.data2);
        break;
    default:
        break;
    }
}
References GLESC::isIterable_v, GLESC::WindowManager::setSize(), and windowManager.
Referenced by update().
isMouseRelative()
bool InputManager::isMouseRelative ()
Gets whether the mouse is relative or not.
Returns
true if mouse is relative, false otherwise
Definition at line 190 of file InputManager.cpp.
{
    return SDL_GetRelativeMouseMode() == SDL_TRUE;
}
References GLESC::isIterable_v.
Referenced by GLESC::EngineCamera::rotate().
lerpMousePos()
void InputManager::lerpMousePos (MousePosition & oldMousePos, const MousePosition & targetMousePos) const private
Linearly interpolates the mouse position to smooth out the mouse movement.
Parameters
oldMousePos - The old mouse position to interpolate from. This will get updated, it is not const.
targetMousePos - The target mouse position to interpolate to.
Definition at line 145 of file InputManager.cpp.
{
    oldMousePos = targetMousePos;
    //oldMousePos.setX(Math::lerp(oldMousePos.getX(), targetMousePos.getX(), mouseSmoothFactor));
    //oldMousePos.setY(Math::lerp(oldMousePos.getY(), targetMousePos.getY(), mouseSmoothFactor));
}
References GLESC::isIterable_v, and targetMousePos.
Referenced by update().
setMouseRelative()
void InputManager::setMouseRelative (bool enabled)
Enables mouse If enabled mouse is visible and position is absolute (allows moving it across the window) If disabled mouse is hidden and position is relative (stays in center)
Parameters
enabled true to enable, false to disable
Definition at line 178 of file InputManager.cpp.
{
    if (SDL_SetRelativeMouseMode(static_cast<SDL_bool>(enabled)) != 0) {
        std::string action = enabled ? "enable" : "disable";
        throw EngineException(
            "Unable to " + action + " mouse relative mode: " + std::string(SDL_GetError())
        );
    }
    // Reset the mouse position, looks like it's not done by SDL
    mousePos.x() = 0;
    mousePos.y() = 0;
}
References GLESC::isIterable_v, mousePos, GLESC::Math::Vector< Type, N >::x(), and GLESC::Math::Vector< Type, N >::y().
update()
void InputManager::update (bool & running)
Updates the input manager by processing the current input state.
Definition at line 27 of file InputManager.cpp.
{
    SDL_Point sdlMousePos = {0, 0};
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        hudManager.processInput(event);
        switch (event.type) {
        case SDL_QUIT:
            running = false;
            break;
        case SDL_WINDOWEVENT:
            handleWindowEvent(event);
            break;
        case SDL_KEYDOWN:
        case SDL_KEYUP:
            handleKeyEvent(event);
            break;
        case SDL_MOUSEBUTTONDOWN:
        case SDL_MOUSEBUTTONUP:
            handleMouseButton(event);
            break;
        case SDL_MOUSEMOTION:
            handleMouseMotion(event);
            if (SDL_GetRelativeMouseMode() == SDL_TRUE) {
                sdlMousePos = {event.motion.xrel, event.motion.yrel};
            }
            break;
        default:
            break;
        }
    }
    // When no input is given to the mouse, send a 0,0 movement to the buffer and lerp the mouse position
    if (SDL_GetRelativeMouseMode() == SDL_TRUE) {
        addToBuffer(sdlMousePos.x, sdlMousePos.y);
        lerpMousePos(mousePos, getAvgMousePos());
    }
}
References addToBuffer(), getAvgMousePos(), handleKeyEvent(), handleMouseButton(), handleMouseMotion(), handleWindowEvent(), hudManager, GLESC::isIterable_v, lerpMousePos(), mousePos, and GLESC::HUD::HUDManager::processInput().
Referenced by GLESC::Engine::processInput().
updateKeyState()
void InputManager::updateKeyState (Key key, bool pressed) private
Updates the state of a specific key in the key map.
If the key is pressed, the key state is updated to pressed. If the key has just been pressed, the key state is updated to just pressed. Also resets the key state if the key has been released.
Parameters
key - The key to update.
pressed - The state of the key.
Definition at line 94 of file InputManager.cpp.
{
    auto& keyState = keyMap[key];
    if (pressed) {
        if (!keyState.pressed) {
            keyState.justPressed = true;
        }
        else {
            keyState.justPressed = false;
        }
        keyState.pressed = true;
    }
    else {
        if (keyState.pressed) {
            keyState.justReleased = true;
        }
        else {
            keyState.justReleased = false;
        }
        keyState.pressed = false;
        keyState.justPressed = false;
    }
}
References GLESC::isIterable_v, and keyMap.
Referenced by handleKeyEvent(), and handleMouseButton().
Member Data Documentation
bufferSize
const size_t GLESC::Input::InputManager::bufferSize = 5 private
The size of the buffer used to store the delta values of the mouse position.
Definition at line 117 of file InputManager.h.
Referenced by addToBuffer().
deadzone
const float GLESC::Input::InputManager::deadzone = 1 private
The deadzone used to filter out small mouse movements.
SDL reports small mouse movements even when the mouse is not moving. This deadzone helps to filter out.
Definition at line 123 of file InputManager.h.
deltaBuffer
std::deque<Vec2F> GLESC::Input::InputManager::deltaBuffer private
The buffer used to store the delta values of the mouse position.
This helps to smooth out the mouse movement.
Definition at line 113 of file InputManager.h.
Referenced by addToBuffer(), and getAvgMousePos().
hudManager
HUD::HUDManager& GLESC::Input::InputManager::hudManager private
The HUDManager instance used to handle HUD events.
Definition at line 177 of file InputManager.h.
Referenced by update().
keyMap
KeyMap GLESC::Input::InputManager::keyMap {} private
The key map used to store the state of each key.
Definition at line 159 of file InputManager.h.
{};
Referenced by checkKeyAction(), getPressedKeys(), and updateKeyState().
mousePos
MousePosition GLESC::Input::InputManager::mousePos {} private
Represents the current mouse position.
Definition at line 127 of file InputManager.h.
{};
Referenced by getMousePosition(), handleMouseMotion(), setMouseRelative(), and update().
mouseSmoothFactor
float GLESC::Input::InputManager::mouseSmoothFactor {0.1f} private
The smooth factor used to smooth out the mouse movement.
Definition at line 135 of file InputManager.h.
{0.1f};
pressedOnceDetection
std::unordered_map<const KeyInput*, bool> GLESC::Input::InputManager::pressedOnceDetection private
A map of bools used to detect if a key was pressed once. Will be initialized dynamically, if a key is checked and its one time press is not initialized, it will be initialized with true (has been pressed once).
Definition at line 164 of file InputManager.h.
targetMousePos
MousePosition GLESC::Input::InputManager::targetMousePos {} private
The target mouse position used to smooth out the mouse movement.
Definition at line 131 of file InputManager.h.
{};
Referenced by lerpMousePos().
windowManager
WindowManager& GLESC::Input::InputManager::windowManager private
Definition at line 171 of file InputManager.h.
Referenced by handleWindowEvent().
The documentation for this class was generated from the following files:
InputManager.h
InputManager.cpp