GLESC: GLESC::GAPI::ShaderLoader Class Reference
GLESC::GAPI::ShaderLoader Class Reference
#include <ShaderLoader.h>
Static Public Member Functions
static UInt loadShader (const std::string &fileName, const std::vector< std::string > &macros={})
Load the shader from a file.
static UInt loadShader (const std::string &vertexShaderSourceParam, const std::string &fragmentShaderSourceParam, const std::vector< std::string > &macros={})
Load the shader from the source code.
Static Private Member Functions
static void clean ()
Clean the shader loader.
static UInt createShaderProgram ()
Links the loaded shaders into the shader program.
static void extractShaderCode (const std::string &shaderSource, std::string &vertexCode, std::string &fragmentCode)
Extracts the shader code from the source.
static std::string getGLSLVersionString ()
Gets the GLSL version string.
static void insertShaderMacros (std::string &vertexCode, std::string &fragmentCode, const std::vector< std::string > &macros)
Inserts the shader macros into the shader code.
static UInt loadFragmentShader (const std::string &fragmentShaderSourceParam)
Loads the fragment shader Calculates colors of pixels (a fragment is a pixel in OpenGL)
static UInt loadVertexShader (const std::string &vertexShaderSourceParam)
Loads the vertex shader Sets the actual coordinates of the vertices in the GPU.
static void prependGLSLVersion (std::string &vertexCode, std::string &fragmentCode)
Prepends the GLSL version to the shader code.
static void validateShaderCodes (const std::string &vertexCode, const std::string &fragmentCode)
Validates the shader codes.
static void validateShaderTokens (size_t vertexPos, size_t fragmentPos)
Validates the shader tokens.
Static Private Attributes
static UInt fragmentShader
ID reference to the fragment shader.
static std::string fragmentShaderSource
Source of the fragment shader.
static std::unordered_map< unsigned int, const char * > shaderNamesMap
Map of names of the shaders and their IDs.
static constexpr const char * tokenFragment = "#shader fragment"
Tokens used to separate the vertex and fragment shaders.
static constexpr const char * tokenVertex = "#shader vertex"
Tokens used to separate the vertex and fragment shaders.
static UInt vertexShader
ID reference to the vertex shader.
static std::string vertexShaderSource
Source of the vertex shader.
Detailed Description
Definition at line 18 of file ShaderLoader.h.
Member Function Documentation
clean()
void ShaderLoader::clean () static private
Clean the shader loader.
Clean the shader loader Once the shaders are linked, they can be cleared as they are no longer needed.
Once the shaders are linked, they can be cleared as they are no longer needed.
Definition at line 172 of file ShaderLoader.cpp.
{
    std::destroy(shaderNamesMap.begin(), shaderNamesMap.end()); //Delete pointers from map
    getGAPI().deleteShader(vertexShader);
    getGAPI().deleteShader(fragmentShader);
}
References fragmentShader, getGAPI(), shaderNamesMap, and vertexShader.
Referenced by loadShader().
createShaderProgram()
UInt ShaderLoader::createShaderProgram () static private
Links the loaded shaders into the shader program.
Definition at line 160 of file ShaderLoader.cpp.
{
    UInt shaderProgram = getGAPI().createShaderProgram(vertexShader, fragmentShader);
    D_ASSERT_LINKING_OK(shaderProgram);
    return shaderProgram;
}
References D_ASSERT_LINKING_OK, fragmentShader, getGAPI(), GLESC::isIterable_v, and vertexShader.
Referenced by loadShader().
extractShaderCode()
void ShaderLoader::extractShaderCode (const std::string & shaderSource, std::string & vertexCode, std::string & fragmentCode) static private
Extracts the shader code from the source.
The shader source is split into the vertex and fragment shader code. They are separated by the tokens defined in tokenVertex and tokenFragment.
See also
tokenVertex
tokenFragment
Parameters
shaderSource The source of the shader
vertexCode The extracted vertex shader code
fragmentCode The extracted fragment shader code
Definition at line 67 of file ShaderLoader.cpp.
{
    size_t vertexPos = shaderSource.find(tokenVertex);
    size_t fragmentPos = shaderSource.find(tokenFragment);
    validateShaderTokens(vertexPos, fragmentPos);
    // Extract shader codes
    if (vertexPos < fragmentPos) {
        vertexCode = shaderSource.substr(vertexPos + strlen(tokenVertex),
                                         fragmentPos - vertexPos - strlen(tokenVertex));
        fragmentCode = shaderSource.substr(fragmentPos + strlen(tokenFragment));
    }
    else {
        fragmentCode = shaderSource.substr(fragmentPos + strlen(tokenFragment),
                                           vertexPos - fragmentPos - strlen(tokenFragment));
        vertexCode = shaderSource.substr(vertexPos + strlen(tokenVertex));
    }
    validateShaderCodes(vertexCode, fragmentCode);
}
References GLESC::isIterable_v, tokenFragment, tokenVertex, validateShaderCodes(), and validateShaderTokens().
Referenced by loadShader().
getGLSLVersionString()
std::string ShaderLoader::getGLSLVersionString () static private
Gets the GLSL version string.
This obtains the GLSL version string based on the OpenGL version defined in the Config.h
See also
Config.h
Returns
The GLSL version string
Definition at line 97 of file ShaderLoader.cpp.
{
#if GLESC_GLSL_CORE_PROFILE == true
    std::string glslCoreStr = "core";
#else
    std::string glslCoreStr = "";
#endif
    // check if minor version occupies 2 digits
#if GLESC_GLSL_MINOR_VERSION < 10
    std::string glslMinorVersionStr = std::to_string(GLESC_GLSL_MINOR_VERSION) + "0";
#else
    std::string glslMinorVersionStr = std::to_string(GLESC_GLSL_MINOR_VERSION);
#endif
    return "#version " + std::to_string(GLESC_GLSL_MAJOR_VERSION) +
        glslMinorVersionStr + " " + glslCoreStr + "\n";
}
References GLESC_GLSL_MAJOR_VERSION, GLESC_GLSL_MINOR_VERSION, and GLESC::isIterable_v.
Referenced by prependGLSLVersion().
insertShaderMacros()
void ShaderLoader::insertShaderMacros (std::string & vertexCode, std::string & fragmentCode, const std::vector< std::string > & macros) static private
Inserts the shader macros into the shader code.
This function append the macros to the shader code.
Parameters
vertexCode The vertex shader code
fragmentCode The fragment shader code
macros The macros to be inserted
Definition at line 56 of file ShaderLoader.cpp.
{
    std::string macrosString;
    for (const auto& macro : macros) {
        macrosString += "#define " + macro + "\n";
    }
    vertexCode = macrosString + vertexCode;
    fragmentCode = macrosString + fragmentCode;
}
References GLESC::isIterable_v.
Referenced by loadShader().
loadFragmentShader()
UInt ShaderLoader::loadFragmentShader (const std::string & fragmentShaderSourceParam) static private
Loads the fragment shader Calculates colors of pixels (a fragment is a pixel in OpenGL)
Definition at line 151 of file ShaderLoader.cpp.
{
    UInt fragShader = getGAPI()
        .loadAndCompileShader(Enums::ShaderTypes::Fragment, fragmentShaderSourceParam);
    shaderNamesMap.emplace(fragShader, "FRAGMENT");
    D_ASSERT_COMPILATION_OK(fragShader);
    return fragShader;
}
References D_ASSERT_COMPILATION_OK, getGAPI(), GLESC::isIterable_v, and shaderNamesMap.
Referenced by loadShader().
loadShader() [1/2]
UInt ShaderLoader::loadShader (const std::string & fileName, const std::vector< std::string > & macros = {}) static
Load the shader from a file.
Parameters
fileName The name of the file containing the shader
macros The macros to be used in the shader
Returns
The ID of the shader program
Definition at line 18 of file ShaderLoader.cpp.
{
    std::string shaderPath = std::string(SHADER_PATH) + "/" + fileName;
    std::string shaderSource = FileManager::readFile(shaderPath);
    Logger::get().success("Shader file read successfully: " + shaderPath);
    std::string vertexShaderSourceTemp;
    std::string fragmentShaderSourceTemp;
    extractShaderCode(shaderSource, vertexShaderSourceTemp, fragmentShaderSourceTemp);
    return loadShader(vertexShaderSourceTemp, fragmentShaderSourceTemp, macros);
}
References extractShaderCode(), GLESC::Logger::get(), GLESC::isIterable_v, loadShader(), FileManager::readFile(), and GLESC::Logger::success().
Referenced by loadShader().
loadShader() [2/2]
UInt ShaderLoader::loadShader (const std::string & vertexShaderSourceParam, const std::string & fragmentShaderSourceParam, const std::vector< std::string > & macros = {}) static
Load the shader from the source code.
Parameters
vertexShaderSourceParam The source code of the vertex shader
fragmentShaderSourceParam The source code of the fragment shader
macros The macros to be used in the shader
Returns
The ID of the shader program
Definition at line 31 of file ShaderLoader.cpp.
{
    vertexShaderSource = vertexShaderSourceParam;
    fragmentShaderSource = fragmentShaderSourceParam;
    insertShaderMacros(vertexShaderSource, fragmentShaderSource, macros);
    prependGLSLVersion(vertexShaderSource, fragmentShaderSource);
    Logger::get().nonImportantInfo(
        "Vertex Shader:\n\t" + GLESC::Stringer::replace(vertexShaderSource, "\n", "\n\t"));
    Logger::get().nonImportantInfo(
        "Fragment Shader:\n\t" + GLESC::Stringer::replace(fragmentShaderSource, "\n", "\n\t"));
    vertexShader = loadVertexShader(vertexShaderSource);
    Logger::get().success("Vertex shader loaded successfully");
    fragmentShader = loadFragmentShader(fragmentShaderSource);
    Logger::get().success("Fragment shader loaded successfully");
    UInt shaderProgram = createShaderProgram();
    Logger::get().success("Shader program created successfully");
    clean();
    return shaderProgram;
}
References clean(), createShaderProgram(), fragmentShader, fragmentShaderSource, GLESC::Logger::get(), insertShaderMacros(), GLESC::isIterable_v, loadFragmentShader(), loadVertexShader(), GLESC::Logger::nonImportantInfo(), prependGLSLVersion(), GLESC::Stringer::replace(), GLESC::Logger::success(), vertexShader, and vertexShaderSource.
loadVertexShader()
UInt ShaderLoader::loadVertexShader (const std::string & vertexShaderSourceParam) static private
Loads the vertex shader Sets the actual coordinates of the vertices in the GPU.
Definition at line 143 of file ShaderLoader.cpp.
{
    UInt vertShader = getGAPI()
        .loadAndCompileShader(Enums::ShaderTypes::Vertex, vertexShaderSourceParam);
    shaderNamesMap.emplace(vertShader, "VERTEX");
    D_ASSERT_COMPILATION_OK(vertShader);
    return vertShader;
}
References D_ASSERT_COMPILATION_OK, getGAPI(), GLESC::isIterable_v, and shaderNamesMap.
Referenced by loadShader().
prependGLSLVersion()
void ShaderLoader::prependGLSLVersion (std::string & vertexCode, std::string & fragmentCode) static private
Prepends the GLSL version to the shader code.
The GLSL version is prepended to the shader code. The version is obtained in getGLSLVersionString().
See also
getGLSLVersionString()
Parameters
vertexCode The vertex shader code
fragmentCode The fragment shader code
Definition at line 91 of file ShaderLoader.cpp.
{
    std::string glslVersionStr = getGLSLVersionString();
    vertexShaderSource = glslVersionStr + vertexCode;
    fragmentShaderSource = glslVersionStr + fragmentCode;
}
References fragmentShaderSource, getGLSLVersionString(), GLESC::isIterable_v, and vertexShaderSource.
Referenced by loadShader().
validateShaderCodes()
void ShaderLoader::validateShaderCodes (const std::string & vertexCode, const std::string & fragmentCode) static private
Validates the shader codes.
The shader codes are validated to ensure that they are not empty.
Parameters
vertexCode The vertex shader code
fragmentCode The fragment shader code
Definition at line 124 of file ShaderLoader.cpp.
{
    if (vertexCode.empty()) {
        D_ASSERT_SHADER_CODE_FOUND("vertex");
    }
    if (fragmentCode.empty()) {
        D_ASSERT_SHADER_CODE_FOUND("fragment");
    }
}
References D_ASSERT_SHADER_CODE_FOUND, and GLESC::isIterable_v.
Referenced by extractShaderCode().
validateShaderTokens()
void ShaderLoader::validateShaderTokens (size_t vertexPos, size_t fragmentPos) static private
Validates the shader tokens.
The shader tokens are validated to ensure that they are present in the shader source.
Parameters
vertexPos The position of the vertex token
fragmentPos The position of the fragment token
Definition at line 114 of file ShaderLoader.cpp.
{
    if (vertexPos == std::string::npos) {
        D_ASSERT_SHADER_TOKEN_FOUND("vertex");
    }
    if (fragmentPos == std::string::npos) {
        D_ASSERT_SHADER_TOKEN_FOUND("fragment");
    }
}
References D_ASSERT_SHADER_TOKEN_FOUND, and GLESC::isIterable_v.
Referenced by extractShaderCode().
Member Data Documentation
fragmentShader
UInt ShaderLoader::fragmentShader static private
ID reference to the fragment shader.
Definition at line 58 of file ShaderLoader.h.
Referenced by clean(), createShaderProgram(), and loadShader().
fragmentShaderSource
std::string ShaderLoader::fragmentShaderSource static private
Source of the fragment shader.
Definition at line 48 of file ShaderLoader.h.
Referenced by loadShader(), and prependGLSLVersion().
shaderNamesMap
std::unordered_map< unsigned int, const char * > ShaderLoader::shaderNamesMap static private
Map of names of the shaders and their IDs.
Once the shader is created, we assign the name to the ID This is used to identify the shader in case of handling an error
Definition at line 149 of file ShaderLoader.h.
Referenced by clean(), loadFragmentShader(), and loadVertexShader().
tokenFragment
constexpr const char* GLESC::GAPI::ShaderLoader::tokenFragment = "#shader fragment" static constexpr private
Tokens used to separate the vertex and fragment shaders.
Definition at line 136 of file ShaderLoader.h.
Referenced by extractShaderCode().
tokenVertex
constexpr const char* GLESC::GAPI::ShaderLoader::tokenVertex = "#shader vertex" static constexpr private
Tokens used to separate the vertex and fragment shaders.
Definition at line 132 of file ShaderLoader.h.
Referenced by extractShaderCode().
vertexShader
UInt ShaderLoader::vertexShader static private
ID reference to the vertex shader.
Definition at line 53 of file ShaderLoader.h.
Referenced by clean(), createShaderProgram(), and loadShader().
vertexShaderSource
std::string ShaderLoader::vertexShaderSource static private
Source of the vertex shader.
Definition at line 43 of file ShaderLoader.h.
Referenced by loadShader(), and prependGLSLVersion().
The documentation for this class was generated from the following files:
ShaderLoader.h
ShaderLoader.cpp