GLESC: GLESC::HUD::EntityListHUD Class Reference
GLESC::HUD::EntityListHUD Class Reference
A class that encapsulates the HUD for the entity list.
#include <EntityListHUD.h>
Public Member Functions
EntityListHUD ()
Public Member Functions inherited from GLESC::InGameWindow
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Private Member Functions
void windowContent (float timeOfFrame) override
Additional Inherited Members
Protected Member Functions inherited from GLESC::InGameWindow
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
Protected Attributes inherited from GLESC::InGameWindow
bool isVisible = true
Detailed Description
A class that encapsulates the HUD for the entity list.
Allows visualizing the list of entities in the scene. Also, it allows selecting an entity to then be able to display in the debug entity data HUD.
Definition at line 20 of file EntityListHUD.h.
Constructor & Destructor Documentation
EntityListHUD()
GLESC::HUD::EntityListHUD::EntityListHUD ()
Definition at line 20 of file EntityListHUD.cpp.
{
    this->setTitle("Entity List");
    this->setSizeFraction({0.2f, 0.7f});
    this->setMinSize({300.0f, 0.0f});
    isVisible = true;
    this->setLayoutPosition(LayoutPos::BottomLeft);
    this->setCenter(WindowCenter::BottomLeft);
    this->addFlag(ImGuiWindowFlags_NoResize);
    this->addFlag(ImGuiWindowFlags_NoMove);
    this->addFlag(ImGuiWindowFlags_NoCollapse);
    this->addFlag(ImGuiWindowFlags_NoTitleBar);
    this->addFlag(ImGuiWindowFlags_NoSavedSettings);
    this->addFlag(ImGuiWindowFlags_NoBringToFrontOnFocus);
    this->addFlag(ImGuiWindowFlags_NoFocusOnAppearing);
    this->addFlag(ImGuiWindowFlags_AlwaysAutoResize);
}
References GLESC::InGameWindow::addFlag(), GLESC::BottomLeft, GLESC::isIterable_v, GLESC::InGameWindow::isVisible, GLESC::InGameWindow::setCenter(), GLESC::InGameWindow::setLayoutPosition(), GLESC::InGameWindow::setMinSize(), GLESC::InGameWindow::setSizeFraction(), and GLESC::InGameWindow::setTitle().
Member Function Documentation
windowContent()
void GLESC::HUD::EntityListHUD::windowContent (float timeOfFrame) override private virtual
Implements GLESC::InGameWindow.
Definition at line 55 of file EntityListHUD.cpp.
{
    std::map<std::string, std::vector<const std::string*>> entityMap;
    // Group entities and instances
    for (const auto& entityListItem : EntityListManager::getEntities()) {
        D_ASSERT_NOT_NULLPTR(entityListItem.name, "Entity is null");
        const std::string* entityName = entityListItem.name;
        if (entityListItem.type == EntityType::Instance) {
            std::string strippedName = Stringer::strip(*entityName, "1234567890");
            entityMap[strippedName].push_back(entityName);
        } else {
            entityMap[*entityName]; // Ensure the entity is in the map
        }
    }
    // Display entities and instances
    int entityIndex = 0;
    for (const auto& entityPair : entityMap) {
        const std::string& entityName = entityPair.first;
        const std::vector<const std::string*>& instances = entityPair.second;
        // Create two columns for all entries
        ImGui::Columns(2, nullptr, false);
        if(instances.empty())
            // Display the main entity
            entityButton(entityIndex + 1, entityName);
        ImGui::Columns(1,nullptr, false);
        // Display instances if any using CollapsingHeader for consistency
        if (!instances.empty()) {
            std::string headerLabel = entityName;
            ImGui::PushID(entityIndex); // Ensure unique IDs for ImGui components
            if (ImGui::CollapsingHeader(headerLabel.c_str())) {
                for (const auto& instanceName : instances) {
                    ImGui::Indent();
                    entityButton(++entityIndex, *instanceName);
                    ImGui::Unindent();
                }
            }
            ImGui::PopID();
        }
        ImGui::Columns(1); // Reset columns for the next entry
        ++entityIndex; // Increment the entity index
    }
}
References D_ASSERT_NOT_NULLPTR, entityButton(), GLESC::EntityListManager::getEntities(), GLESC::Instance, GLESC::isIterable_v, and GLESC::Stringer::strip().
The documentation for this class was generated from the following files:
EntityListHUD.h
EntityListHUD.cpp