GLESC: GLESC::Render::Texture Class Reference
GLESC::Render::Texture Class Reference
Class representing a texture. It abstracts away the creating and handling of textures for the renderer.
#include <Texture.h>
Public Member Functions
Texture ()=default
Texture (const std::string &path, bool flipTexture=true)
~Texture ()
void bind (TextureSlot textureSlot=0) const
Bind the texture to the renderer to be used in the next draw calls.
UInt getTextureID () const
const ResMng::Texture::TextureSurface & getTextureSurface () const
Get the texture surface.
bool hasBeenLoaded () const
void load (const std::string &path, bool flipTexture)
void release ()
void unbind () const
Private Member Functions
void load (const ResMng::Texture::TextureSurface &textureSurfaceParam)
Private Attributes
bool hasLoaded {false}
TextureID textureID {0}
ResMng::Texture::TextureSurface textureSurface
Detailed Description
Class representing a texture. It abstracts away the creating and handling of textures for the renderer.
This is just the abstraction for the Texture for the Graphic API, the actual texture data is handled by texture surface
See also
TextureSurface
Definition at line 21 of file Texture.h.
Constructor & Destructor Documentation
Texture() [1/2]
GLESC::Render::Texture::Texture () default
Texture() [2/2]
Texture::Texture (const std::string & path, bool flipTexture = true) explicit
Definition at line 11 of file Texture.cpp.
{
    load(path, flipTexture);
}
References GLESC::isIterable_v, and load().
~Texture()
Texture::~Texture ()
Definition at line 15 of file Texture.cpp.
                  {
    if (hasLoaded) {
        getGAPI().deleteTexture(textureID);
    }
}
References getGAPI(), hasLoaded, and textureID.
Member Function Documentation
bind()
void Texture::bind (TextureSlot textureSlot = 0) const
Bind the texture to the renderer to be used in the next draw calls.
Parameters
textureSlot Each renderer has a number of slots that can be used to bind textures (this depends on the platform and the renderer). This parameter specifies the slot to which the texture will be bound.
Definition at line 43 of file Texture.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Texture not loaded");
    getGAPI().bindTextureOnSlot(textureID, Enums::Texture::Types::Texture2D, textureSlot);
}
References D_ASSERT_TRUE, getGAPI(), hasLoaded, GLESC::isIterable_v, and textureID.
getTextureID()
UInt GLESC::Render::Texture::getTextureID () const inline
Definition at line 41 of file Texture.h.
{ return textureID; }
References textureID.
getTextureSurface()
const ResMng::Texture::TextureSurface & GLESC::Render::Texture::getTextureSurface () const inline
Get the texture surface.
The texture surface is the data of the texutre with its pixels and format
Returns
The texture surface
Definition at line 50 of file Texture.h.
{ return textureSurface; }
References textureSurface.
hasBeenLoaded()
bool GLESC::Render::Texture::hasBeenLoaded () const inline
Definition at line 43 of file Texture.h.
{ return hasLoaded; }
References hasLoaded.
load() [1/2]
void Texture::load (const ResMng::Texture::TextureSurface & textureSurfaceParam) private
Definition at line 33 of file Texture.cpp.
{
    textureSurface = textureSurfaceParam;
    const Enums::Texture::CPUBufferFormat inputFormat = getTextureInputFormat(textureSurface.getFormat().colorFormat);
    const Enums::Texture::BitDepth bitDepth = getTextureBitDepth(textureSurface.getFormat().bitDepth);
    getGAPI().setTextureData(
        Enums::Texture::Types::Texture2D, 0, textureSurface.getWidth(), textureSurface.getHeight(),
        inputFormat, bitDepth, textureSurface.getPixels().data());
}
References Format::bitDepth, Format::colorFormat, GLESC::ResMng::Texture::TextureSurface::getFormat(), getGAPI(), GLESC::ResMng::Texture::TextureSurface::getHeight(), GLESC::ResMng::Texture::TextureSurface::getPixels(), getTextureBitDepth(), getTextureInputFormat(), GLESC::ResMng::Texture::TextureSurface::getWidth(), GLESC::isIterable_v, and textureSurface.
load() [2/2]
void Texture::load (const std::string & path, bool flipTexture)
Definition at line 21 of file Texture.cpp.
{
    D_ASSERT_TRUE(!path.empty(), "File path is empty.");
    textureID = textureID = getGAPI().createTexture(Enums::Texture::Types::Texture2D,
                                                    Enums::Texture::Filters::Min::Linear,
                                                    Enums::Texture::Filters::Mag::Linear,
                                                    Enums::Texture::Filters::WrapMode::ClampToEdge,
                                                    Enums::Texture::Filters::WrapMode::ClampToEdge);
    textureSurface.load(path, flipTexture);
    load(textureSurface);
    hasLoaded = true;
}
References D_ASSERT_TRUE, getGAPI(), hasLoaded, GLESC::isIterable_v, load(), GLESC::ResMng::Texture::TextureSurface::load(), textureID, and textureSurface.
Referenced by Texture(), and load().
release()
void Texture::release ()
Definition at line 53 of file Texture.cpp.
                      {
    textureSurface.release();
}
References GLESC::ResMng::Texture::TextureSurface::release(), and textureSurface.
Referenced by GLESC::HUD::DebugItems::DebugItems().
unbind()
void Texture::unbind () const
Definition at line 48 of file Texture.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Texture not loaded");
    getGAPI().unbindTexture(Enums::Texture::Types::Texture2D);
}
References D_ASSERT_TRUE, getGAPI(), and hasLoaded.
Member Data Documentation
hasLoaded
bool GLESC::Render::Texture::hasLoaded {false} private
Definition at line 56 of file Texture.h.
{false};
Referenced by ~Texture(), bind(), hasBeenLoaded(), load(), and unbind().
textureID
TextureID GLESC::Render::Texture::textureID {0} private
Definition at line 57 of file Texture.h.
{0};
Referenced by ~Texture(), bind(), getTextureID(), and load().
textureSurface
ResMng::Texture::TextureSurface GLESC::Render::Texture::textureSurface private
Definition at line 58 of file Texture.h.
Referenced by getTextureSurface(), load(), load(), and release().
The documentation for this class was generated from the following files:
Texture.h
Texture.cpp