GLESC: GLESC::ECS::DebugInfoSystem Class Reference
GLESC::ECS::DebugInfoSystem Class Reference
#include <DebugInfoSystem.h>
Public Member Functions
DebugInfoSystem (ECSCoordinator &ecs, Render::Renderer &renderer)
void update () override
Updates the system.
Public Member Functions inherited from GLESC::ECS::System
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
Private Member Functions
void setEntityData (const EntityName &name)
Private Attributes
float maxDetectionValue = 20.0f
Render::Renderer & renderer
EntityID selectedEntity {nullEntity}
Additional Inherited Members
Protected Member Functions inherited from GLESC::ECS::System
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes inherited from GLESC::ECS::System
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Detailed Description
Definition at line 17 of file DebugInfoSystem.h.
Constructor & Destructor Documentation
DebugInfoSystem()
DebugInfoSystem::DebugInfoSystem (ECSCoordinator & ecs, Render::Renderer & renderer)
Definition at line 10 of file DebugInfoSystem.cpp.
                                                                              : System(ecs, "DebugInfoSystem"),
    renderer(renderer) {
    addComponentRequirement<TransformComponent>();
}
References GLESC::isIterable_v.
Member Function Documentation
setEntityData()
void DebugInfoSystem::setEntityData (const EntityName & name) private
Definition at line 15 of file DebugInfoSystem.cpp.
{
    EntityStatsManager::EntityData entityData;
    EntityID entityId = getEntity(name);
    if(selectedEntity == entityId) return;
    entityData.name = name;
    std::vector<IComponent*> components = getComponents(entityId);
    for (IComponent* component : components) {
        EntityStatsManager::ComponentData componentData;
        componentData.name = component->getName();
        componentData.values = &component->getDebuggingValues();
        componentData.getUpdatedValues = [component]{return component->getUpdatedDebuggingValues();};
        entityData.components.push_back(componentData);
    }
    selectedEntity = entityId;
    EntityStatsManager::setEntityData(entityData);
}
References EntityStatsManager::EntityData::components, GLESC::ECS::System::getComponents(), GLESC::ECS::System::getEntity(), GLESC::isIterable_v, GLESC::ECS::System::name, EntityStatsManager::ComponentData::name, EntityStatsManager::EntityData::name, selectedEntity, and EntityStatsManager::setEntityData().
Referenced by update().
update()
void DebugInfoSystem::update () override virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implements GLESC::ECS::System.
Definition at line 34 of file DebugInfoSystem.cpp.
{
    for (EntityID id : getAssociatedEntities()) {
        EntityListManager::addEntity(getEntityName(id), getEntityMetadata(id).type);
    }
    if(!EntityListManager::getSelectedEntity().empty())
        setEntityData(EntityListManager::getSelectedEntity());
}
References GLESC::EntityListManager::addEntity(), GLESC::ECS::System::getAssociatedEntities(), GLESC::ECS::System::getEntityMetadata(), GLESC::ECS::System::getEntityName(), GLESC::EntityListManager::getSelectedEntity(), GLESC::isIterable_v, and setEntityData().
Member Data Documentation
maxDetectionValue
float GLESC::ECS::DebugInfoSystem::maxDetectionValue = 20.0f private
Definition at line 29 of file DebugInfoSystem.h.
renderer
Render::Renderer& GLESC::ECS::DebugInfoSystem::renderer private
Definition at line 27 of file DebugInfoSystem.h.
selectedEntity
EntityID GLESC::ECS::DebugInfoSystem::selectedEntity {nullEntity} private
Definition at line 26 of file DebugInfoSystem.h.
{nullEntity};
Referenced by setEntityData().
The documentation for this class was generated from the following files:
DebugInfoSystem.h
DebugInfoSystem.cpp