GLESC: GLESC::EntityListManager Class Reference
GLESC::EntityListManager Class Reference
Class that manages the list of entities in the scene.
#include <EntityListManager.h>
Static Public Member Functions
static void addEntity (const std::string &entity, GLESC::EntityType type)
static void entityRemoved (const std::string &entity)
static auto & getEntities ()
static auto getSelectedEntity ()
static void setSelectedEntity (const std::string &entityName)
Static Private Attributes
static std::set< EntityListItem > entities
static std::string selectedEntity
Detailed Description
Class that manages the list of entities in the scene.
It allows adding, removing, and selecting entities. This class will be rendered by the EntityListHUD. It is static because it's logic and data are simple and it benefits from being accessed from anywhere.
Definition at line 40 of file EntityListManager.h.
Member Function Documentation
addEntity()
void EntityListManager::addEntity (const std::string & entity, GLESC::EntityType type) static
Definition at line 17 of file EntityListManager.cpp.
{
    entities.insert({&entity, type});
}
References entities, and GLESC::isIterable_v.
Referenced by GLESC::ECS::DebugInfoSystem::update().
entityRemoved()
void EntityListManager::entityRemoved (const std::string & entity) static
Definition at line 21 of file EntityListManager.cpp.
{
    entities.erase({&entity, EntityType::Default});
    if(selectedEntity == entity) selectedEntity.clear();
}
References GLESC::Default, entities, GLESC::isIterable_v, and selectedEntity.
Referenced by GLESC::Engine::update().
getEntities()
static auto & GLESC::EntityListManager::getEntities () inline static
Definition at line 43 of file EntityListManager.h.
{ return entities; }
References entities.
Referenced by GLESC::HUD::EntityListHUD::windowContent().
getSelectedEntity()
static auto GLESC::EntityListManager::getSelectedEntity () inline static
Definition at line 45 of file EntityListManager.h.
{ return selectedEntity; }
References selectedEntity.
Referenced by GLESC::ECS::DebugInfoSystem::update().
setSelectedEntity()
static void GLESC::EntityListManager::setSelectedEntity (const std::string & entityName) inline static
Definition at line 44 of file EntityListManager.h.
{ selectedEntity = entityName; }
References GLESC::isIterable_v, and selectedEntity.
Referenced by entityButton().
Member Data Documentation
entities
std::set< EntityListItem > EntityListManager::entities static private
Definition at line 49 of file EntityListManager.h.
Referenced by addEntity(), entityRemoved(), and getEntities().
selectedEntity
std::string EntityListManager::selectedEntity static private
Definition at line 50 of file EntityListManager.h.
Referenced by entityRemoved(), getSelectedEntity(), and setSelectedEntity().
The documentation for this class was generated from the following files:
EntityListManager.h
EntityListManager.cpp