GLESC: GLESC::GAPI::OpenGLAPI Class Reference
GLESC::GAPI::OpenGLAPI Class Reference final
#include <OpenGLAPI.h>
Public Member Functions
OpenGLAPI ()
void bindBuffer (Enums::BufferTypes bufferType, UInt buffer) override
Void bindTexture (TextureID textureID, Enums::Texture::Types textureType) override
Void bindTextureOnSlot (TextureID textureID, Enums::Texture::Types textureType, UInt slot) override
void bindVertexArray (UInt vertexArrayID) override
void clear (const std::initializer_list< Enums::ClearBits > &values) override
void clearColor (Float r, Float g, Float b, Float a) override
bool compilationOK (UInt shaderID, Char *message) override
void createContext (SDL_Window &window) override
UInt createShaderProgram (UInt vertexShaderID, UInt fragmentShaderID) override
TextureID createTexture (Enums::Texture::Types textureType, Enums::Texture::Filters::Min minFilter, Enums::Texture::Filters::Mag magFilter, Enums::Texture::Filters::WrapMode wrapS, Enums::Texture::Filters::WrapMode wrapT, Enums::Texture::Filters::WrapMode wrapR=Enums::Texture::Filters::WrapMode::ClampToEdge) override
void createVertexData (UInt index, UInt count, Enums::Types type, Bool isNormalized, UInt stride, UInt offset) override
Configures the layout of the vertex data.
void deleteBuffer (UInt &buffer) override
void deleteContext () override
void deleteShader (UInt shaderID) override
void deleteShaderProgram (UInt shaderProgram) override
void deleteTexture (TextureID textureID) override
void deleteVertexArray (UInt &vertexArrayID) override
void destroyShaderProgram (UInt shaderProgram)
void drawTriangles (UInt start, UInt count) override
void drawTrianglesIndexed (UInt indicesCount) override
void drawTrianglesIndexedInstanced (UInt indicesCount, UInt instanceCount) override
void enableDepthBuffer (Bool enabled) override
void enableVertexData (UInt index) override
Enables the vertex data.
void genBuffers (UInt amount, UInt &bufferID) override
void genVertexArray (UInt &vertexArrayID) override
std::vector< std::string > getAllUniforms () const override
std::vector< float > getBufferDataF (UInt bufferId) override
template<typename T >
std::vector< T > getBufferDataGL (GLuint bufferId)
std::vector< int > getBufferDataI (UInt bufferId) override
std::vector< unsigned int > getBufferDataUI (UInt bufferId) override
SDL_GLContext getContext () const
Enums::Texture::GPUBufferFormat getTextureColorFormat (TextureID textureID) override
std::vector< UByte > getTextureData (TextureID textureID, Enums::Texture::Types textureType) override
UInt getTextureHeight (TextureID textureID) override
UInt getTextureWidth (TextureID textureID) override
Int getUniformLocation (const std::string &uName) const override
Check if the uniform location is cached.
template<typename Type >
auto getUniformValue (Int location)
Viewport getViewport () override
Bool isBuffer (UInt bufferID) override
bool isShaderProgram (UInt shaderProgram) override
Checks if the given shader program is a shader program.
bool linkOK (UInt shaderProgram, Char *message) override
UInt loadAndCompileShader (Enums::ShaderTypes shaderType, const std::string &shaderSource) override
void postWindowCreationInit () override
void preWindowCreationInit () override
RGBAColor readPixelColor (int x, int y) override
RGBAColorNormalized readPixelColorNormalized (UInt x, UInt y) override
void setBufferData (const Void *data, Size elementCount, Size elementSize, Enums::BufferTypes bufferType, Enums::BufferUsages bufferUsage) override
void setDepthFunction (Enums::DepthFuncs depthFunction) override
void setDynamicBufferData (UInt size, Enums::BufferTypes bufferType) override
void setIndexBufferData (const UInt *data, Size count, Enums::BufferUsages buferUsage) override
Void setTextureData (Enums::Texture::Types textureType, Int level, UInt width, UInt height, Enums::Texture::CPUBufferFormat inputFormat, Enums::Texture::BitDepth bitsPerPixel, const UByte *texelBuffer) override
void setVertexAttribDivisor (UInt index, UInt divisor) override
void setViewport (Int width, Int height) override
void setViewport (Int x, Int y, Int width, Int height) override
void swapBuffers (SDL_Window &window) override
void unbindBuffer (Enums::BufferTypes bufferType) override
Void unbindTexture (Enums::Texture::Types textureType) override
void unbindVertexArray () override
void useShaderProgram (UInt shaderProgram) override
Public Member Functions inherited from GLESC::GAPI::IGraphicInterface
IGraphicInterface ()=default
virtual ~IGraphicInterface ()=default
Static Public Member Functions
template<typename Type >
static void setUniform (Int location, Type value)
Private Member Functions
Bool anyTextureBound () override
Bool isTexture (TextureID textureID) override
Bool isTextureBound (TextureID textureID) override
void setSDLGLAttribute (SDL_GLattr attrib, int val)
Static Private Member Functions
static void initGLEW ()
Must be called after creating the window and before enabling gl functions like glEnable() or glCullFace()
Private Attributes
SDL_GLContext context {}
Additional Inherited Members
Protected Member Functions inherited from GLESC::GAPI::IGraphicInterface
virtual Bool isTexture (UInt textureID)=0
virtual Bool isTextureBound (UInt textureID)=0
Protected Attributes inherited from GLESC::GAPI::IGraphicInterface
ShaderProgramID boundShaderProgram {}
TextureID boundTexture {}
std::set< TextureID > textureCache {}
std::unordered_map< std::string, UInt > uniformLocationsCache
Static Protected Attributes inherited from GLESC::GAPI::IGraphicInterface
static constexpr bool rowMajorMatrix {false}
Detailed Description
Definition at line 31 of file OpenGLAPI.h.
Constructor & Destructor Documentation
OpenGLAPI()
GLESC::GAPI::OpenGLAPI::OpenGLAPI () inline explicit
Definition at line 33 of file OpenGLAPI.h.
{
            D_ASSERT_GL_CORRECT_VERSION();
        }
References D_ASSERT_GL_CORRECT_VERSION.
Member Function Documentation
anyTextureBound()
Bool GLESC::GAPI::OpenGLAPI::anyTextureBound () inline override private virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 1098 of file OpenGLAPI.h.
{
            Bool anyTextureBoundBool =
                static_cast<Bool>(boundTexture != 0);
            return anyTextureBoundBool;
        }
References GLESC::GAPI::IGraphicInterface::boundTexture, and GLESC::isIterable_v.
Referenced by setTextureData().
bindBuffer()
void GLESC::GAPI::OpenGLAPI::bindBuffer (Enums::BufferTypes bufferType, UInt buffer) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 466 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("bindBuffer", bufferType, buffer);
            auto bufferTypeGL = static_cast<GLenum>(bufferType);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindBuffer", bufferTypeGL, buffer);
            glBindBuffer(bufferTypeGL, buffer);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
bindTexture()
Void GLESC::GAPI::OpenGLAPI::bindTexture (TextureID textureID, Enums::Texture::Types textureType) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 422 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("bindTexture", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Object is not a texture");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindTexture", GL_TEXTURE_2D, textureID);
            glBindTexture(static_cast<GLenum>(textureType), textureID);
            boundTexture = textureID;
        }
References GLESC::GAPI::IGraphicInterface::boundTexture, D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and isTexture().
Referenced by bindTextureOnSlot(), createTexture(), and getTextureData().
bindTextureOnSlot()
Void GLESC::GAPI::OpenGLAPI::bindTextureOnSlot (TextureID textureID, Enums::Texture::Types textureType, UInt slot) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 432 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("bindTextureOnSlot", textureID, slot);
            D_ASSERT_TRUE(isTexture(textureID), "Object is not a texture");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glActiveTexture", GL_TEXTURE0 + slot);
            glActiveTexture(GL_TEXTURE0 + slot);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindTexture", GL_TEXTURE_2D, textureID);
            bindTexture(textureID, textureType);
        }
References bindTexture(), D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and isTexture().
bindVertexArray()
void GLESC::GAPI::OpenGLAPI::bindVertexArray (UInt vertexArrayID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 577 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("bindVertexArray", vertexArrayID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindVertexArray", vertexArrayID);
            glBindVertexArray(vertexArrayID);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
clear()
void GLESC::GAPI::OpenGLAPI::clear (const std::initializer_list< Enums::ClearBits > & values) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 1033 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("clear", values);
            GLuint mask = 0;
            for (auto value : values) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glClear", value);
                mask |= static_cast<GLenum>(value);
            }
            glClear(mask);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
clearColor()
void GLESC::GAPI::OpenGLAPI::clearColor (Float r, Float g, Float b, Float a) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 1043 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("clearColor", r, g, b, a);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glClearColor", r, g, b, a);
            glClearColor(r, g, b, a);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
compilationOK()
bool GLESC::GAPI::OpenGLAPI::compilationOK (UInt shaderID, Char * message) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 704 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("compilationOK", shaderID, message);
            GLint success;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetShaderiv", shaderID, GL_COMPILE_STATUS,
                                             &success);
            glGetShaderiv(shaderID, GL_COMPILE_STATUS, &success);
            if (!success) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetShaderInfoLog", shaderID, 512, nullptr,
                                                 message);
                glGetShaderInfoLog(shaderID, 512, nullptr, message);
                return false;
            }
            return true;
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
createContext()
void GLESC::GAPI::OpenGLAPI::createContext (SDL_Window & window) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 1050 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("createContext");
            // OpenGL context initialization over the SDL windowManager,
            // needed for using OpenGL functions
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_CreateContext", "SDL_Window");
            this->context = SDL_GL_CreateContext(&window);
            D_ASSERT_NOT_EQUAL(this->context, nullptr,
                               "Unable to create context: " + std::string(SDL_GetError()));
            Logger::get().success("GL context created!");
        }
References context, D_ASSERT_NOT_EQUAL, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, GLESC::Logger::get(), GLESC::isIterable_v, and GLESC::Logger::success().
createShaderProgram()
UInt GLESC::GAPI::OpenGLAPI::createShaderProgram (UInt vertexShaderID, UInt fragmentShaderID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 685 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("createShaderProgram", vertexShaderID, fragmentShaderID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glCreateProgram", 0);
            GLuint shaderProgram = glCreateProgram();
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glAttachShader", shaderProgram, vertexShaderID);
            glAttachShader(shaderProgram, vertexShaderID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glAttachShader", shaderProgram, fragmentShaderID);
            glAttachShader(shaderProgram, fragmentShaderID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glLinkProgram", shaderProgram);
            glLinkProgram(shaderProgram);
            return shaderProgram;
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
createTexture()
TextureID GLESC::GAPI::OpenGLAPI::createTexture (Enums::Texture::Types textureType, Enums::Texture::Filters::Min minFilter, Enums::Texture::Filters::Mag magFilter, Enums::Texture::Filters::WrapMode wrapS, Enums::Texture::Filters::WrapMode wrapT, Enums::Texture::Filters::WrapMode wrapR = Enums::Texture::Filters::WrapMode::ClampToEdge) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 221 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("createTexture", "SDL_Surface", minFilter, magFilter, wrapS, wrapT);
            auto textureTypeGL = static_cast<GLint>(textureType);
            auto minFilterGL = static_cast<GLint>(minFilter);
            auto magFilterGL = static_cast<GLint>(magFilter);
            auto wrapSGL = static_cast<GLint>(wrapS);
            auto wrapTGL = static_cast<GLint>(wrapT);
            auto wrapRGL = static_cast<GLint>(wrapR);
            int numTextures = 1;
            TextureID textureID = 0;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGenTextures", numTextures, &textureID);
            glGenTextures(numTextures, &textureID);
            textureCache.insert(textureID);
            this->bindTexture(textureID, textureType);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexParameteri", textureTypeGL,
                                             GL_TEXTURE_MIN_FILTER,
                                             minFilterGL);
            glTexParameteri(textureTypeGL, GL_TEXTURE_MIN_FILTER, minFilterGL);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexParameteri", textureTypeGL,
                                             GL_TEXTURE_MAG_FILTER,
                                             magFilterGL);
            glTexParameteri(textureTypeGL, GL_TEXTURE_MAG_FILTER, magFilterGL);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexParameteri", textureTypeGL,
                                             GL_TEXTURE_WRAP_S,
                                             wrapSGL);
            glTexParameteri(textureTypeGL, GL_TEXTURE_WRAP_S, wrapSGL);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexParameteri", textureTypeGL,
                                             GL_TEXTURE_WRAP_T,
                                             wrapTGL);
            glTexParameteri(textureTypeGL, GL_TEXTURE_WRAP_T, wrapTGL);
            if (textureType != Enums::Texture::Types::Texture2D) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexParameteri", textureTypeGL,
                                                 GL_TEXTURE_WRAP_R,
                                                 wrapTGL);
                glTexParameteri(textureTypeGL, GL_TEXTURE_WRAP_R, wrapRGL);
            }
            return textureID;
        }
References bindTexture(), GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and GLESC::GAPI::IGraphicInterface::textureCache.
createVertexData()
void GLESC::GAPI::OpenGLAPI::createVertexData (UInt index, UInt count, Enums::Types type, Bool isNormalized, UInt stride, UInt offset) inline override virtual
Configures the layout of the vertex data.
This method sets up how OpenGL interprets the vertex buffer data. It is used to specify the location and data format of the array of generic vertex attributes.
Parameters
index The index of the vertex attribute to be modified.
count The number of components per generic vertex attribute. Typically, this is 1, 2, 3, or 4.
type The data type of each component in the array. For example, GL_FLOAT, GL_INT, etc.
isNormalized Specifies whether fixed-point data values should be normalized or converted directly as fixed-point values when they are accessed.
stride The byte offset between consecutive vertex attributes. If the attributes are tightly packed, this value is 0.
offset The offset of the first component of the first vertex attribute in the buffer. This is usually a byte offset.
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 629 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("createVertexData", index, count, type, isNormalized, stride,
                              offset);
            auto glType = static_cast<GLenum>(type);
            auto glNormalized = static_cast<GLboolean>(isNormalized);
            // Calls glVertexAttribPointer to define an array of generic vertex attribute data.
            // The parameters are set according to the function arguments, allowing for flexible
            // configuration of vertex data.
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glVertexAttribPointer",
                                             index,
                                             count,
                                             glType,
                                             glNormalized,
                                             stride,
                                             offset);
            glVertexAttribPointer(index, // Specifies the index of the generic vertex attribute.
                                  static_cast<int>(count), // Number of components per generic vertex attribute.
                                  glType, // Converts the GAPITypes enum to GLenum.
                                  glNormalized, // Specifies whether to normalize the data.
                                  static_cast<int>(stride), // Byte offset between consecutive vertex attributes.
                                  reinterpret_cast<GLvoid*>(offset)); // Offset of the first component in the buffer.
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
deleteBuffer()
void GLESC::GAPI::OpenGLAPI::deleteBuffer (UInt & buffer) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 480 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("deleteBuffer", buffer);
            //D_ASSERT_EQUAL(this->isBuffer(buffer), Bool::True, "Bound object is not a buffer");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDeleteBuffers", 1, &buffer);
            glDeleteBuffers(1, &buffer);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
deleteContext()
void GLESC::GAPI::OpenGLAPI::deleteContext () inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 38 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("deleteContext");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_DeleteContext", this->context);
            SDL_GL_DeleteContext(this->context);
        }
References context, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
deleteShader()
void GLESC::GAPI::OpenGLAPI::deleteShader (UInt shaderID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 759 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("deleteShader", shaderID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDeleteShader", shaderID);
            glDeleteShader(shaderID);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
deleteShaderProgram()
void GLESC::GAPI::OpenGLAPI::deleteShaderProgram (UInt shaderProgram) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 753 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("deleteShaderProgram", shaderProgram);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDeleteProgram", shaderProgram);
            glDeleteProgram(shaderProgram);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
deleteTexture()
void GLESC::GAPI::OpenGLAPI::deleteTexture (TextureID textureID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 274 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("deleteTexture", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Bound object is not a texture.");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDeleteTextures", textureID);
            glDeleteTextures(1, &textureID);
            this->textureCache.erase(textureID);
        }
References D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, isTexture(), and GLESC::GAPI::IGraphicInterface::textureCache.
deleteVertexArray()
void GLESC::GAPI::OpenGLAPI::deleteVertexArray (UInt & vertexArrayID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 589 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("deleteVertexArray", vertexArrayID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDeleteVertexArrays", 1, &vertexArrayID);
            glDeleteVertexArrays(1, &vertexArrayID);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
destroyShaderProgram()
void GLESC::GAPI::OpenGLAPI::destroyShaderProgram (UInt shaderProgram) inline virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 699 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("destroyShaderProgram", shaderProgram);
            glDeleteProgram(shaderProgram);
        }
References GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
drawTriangles()
void GLESC::GAPI::OpenGLAPI::drawTriangles (UInt start, UInt count) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 168 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("drawTriangles", start, count);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDrawArrays", GL_TRIANGLES, start, count);
            glDrawArrays(static_cast<GLenum>(Enums::PrimitiveTypes::Triangles), start, count);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
drawTrianglesIndexed()
void GLESC::GAPI::OpenGLAPI::drawTrianglesIndexed (UInt indicesCount) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 174 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("drawTrianglesIndexed", indicesCount);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDrawElements", GL_TRIANGLES, indicesCount,
                                             GL_UNSIGNED_INT, nullptr);
            glDrawElements(static_cast<GLenum>(Enums::PrimitiveTypes::Triangles),
                           indicesCount,
                           static_cast<GLenum>(Enums::Types::UInt),
                           nullptr);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
drawTrianglesIndexedInstanced()
void GLESC::GAPI::OpenGLAPI::drawTrianglesIndexedInstanced (UInt indicesCount, UInt instanceCount) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 184 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("drawTrianglesIndexedInstanced", indicesCount, instanceCount);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDrawElementsInstanced", GL_TRIANGLES, indicesCount,
                                             GL_UNSIGNED_INT, nullptr, instanceCount);
            glDrawElementsInstanced(static_cast<GLenum>(Enums::PrimitiveTypes::Triangles),
                                    static_cast<int>(indicesCount),
                                    static_cast<GLenum>(Enums::Types::UInt),
                                    nullptr,
                                    static_cast<int>(instanceCount));
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
enableDepthBuffer()
void GLESC::GAPI::OpenGLAPI::enableDepthBuffer (Bool enabled) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 156 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("enableDepthBuffer");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glEnable", GL_DEPTH_TEST);
            glDepthMask(static_cast<GLboolean>(enabled));
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
enableVertexData()
void GLESC::GAPI::OpenGLAPI::enableVertexData (UInt index) inline override virtual
Enables the vertex data.
This method enables the generic vertex attribute array specified by the index.
Parameters
index The index of the vertex attribute to be enabled.
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 602 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("enableVertexData", index);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glEnableVertexAttribArray", index);
            glEnableVertexAttribArray(index);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
genBuffers()
void GLESC::GAPI::OpenGLAPI::genBuffers (UInt amount, UInt & bufferID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 459 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("genBuffers", amount);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGenBuffers", amount, &bufferID);
            glGenBuffers(static_cast<int>(amount), &bufferID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("post glGenBuffers", amount, &bufferID);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
genVertexArray()
void GLESC::GAPI::OpenGLAPI::genVertexArray (UInt & vertexArrayID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 564 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("genVertexArray", vertexArrayID);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGenVertexArrays", 1, &vertexArrayID);
            glGenVertexArrays(1, &vertexArrayID);
        };
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
getAllUniforms()
std::vector< std::string > GLESC::GAPI::OpenGLAPI::getAllUniforms () const inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 1010 of file OpenGLAPI.h.
{
            D_ASSERT_TRUE(boundShaderProgram != 0, "No shader program bound.");
            GAPI_FUNCTION_NO_ARGS_LOG("getAllUniforms");
            std::vector<std::string> uniforms;
            GLint numUniforms;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetProgramiv", boundShaderProgram,
                                             GL_ACTIVE_UNIFORMS, &numUniforms);
            glGetProgramiv(boundShaderProgram, GL_ACTIVE_UNIFORMS, &numUniforms);
            for (int i = 0; i < numUniforms; i++) {
                char name[256];
                GLsizei length;
                GLint size;
                GLenum type;
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetActiveUniform", boundShaderProgram, i,
                                                 256, &length, &size, &type, name);
                glGetActiveUniform(boundShaderProgram, i, 256, &length, &size, &type, name);
                std::string uniform = std::string(name) + "(type:" + std::to_string(type) + " size:" +
                    std::to_string(size) + ")";
                uniforms.emplace_back(uniform);
            }
            return uniforms;
        }
References GLESC::GAPI::IGraphicInterface::boundShaderProgram, D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
getBufferDataF()
std::vector< float > GLESC::GAPI::OpenGLAPI::getBufferDataF (UInt bufferId) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 523 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getBufferDataF", bufferId);
            return getBufferDataGL<float>(bufferId);
        }
References GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
getBufferDataGL()
template<typename T > std::vector< T > GLESC::GAPI::OpenGLAPI::getBufferDataGL (GLuint bufferId) inline
Definition at line 539 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getBufferDataGL", bufferId);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindBuffer", GL_ARRAY_BUFFER, bufferId);
            glBindBuffer(GL_ARRAY_BUFFER, bufferId);
            GLint sizeBytes = 0;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetBufferParameteriv", GL_ARRAY_BUFFER,
                                             GL_BUFFER_SIZE, &sizeBytes);
            glGetBufferParameteriv(GL_ARRAY_BUFFER, GL_BUFFER_SIZE, &sizeBytes);
            D_ASSERT_GREATER(sizeBytes, 0, "Invalid buffer size.");
            auto numElements = sizeBytes / sizeof(T);
            std::vector<T> data(numElements);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetBufferSubData", GL_ARRAY_BUFFER, 0, sizeBytes);
            glGetBufferSubData(GL_ARRAY_BUFFER, 0, sizeBytes, data.data());
            GAPI_FUNCTION_IMPLEMENTATION_LOG("post glGetBufferSubData", data);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindBuffer", GL_ARRAY_BUFFER, 0);
            glBindBuffer(GL_ARRAY_BUFFER, 0);
            return data;
        }
References D_ASSERT_GREATER, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
getBufferDataI()
std::vector< int > GLESC::GAPI::OpenGLAPI::getBufferDataI (UInt bufferId) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 533 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getBufferDataI", bufferId);
            return getBufferDataGL<int>(bufferId);
        }
References GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
getBufferDataUI()
std::vector< unsigned int > GLESC::GAPI::OpenGLAPI::getBufferDataUI (UInt bufferId) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 528 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getBufferDataUI", bufferId);
            return getBufferDataGL<unsigned int>(bufferId);
        }
References GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
getContext()
SDL_GLContext GLESC::GAPI::OpenGLAPI::getContext () const inline
Definition at line 69 of file OpenGLAPI.h.
{ return context; };
References context.
getTextureColorFormat()
Enums::Texture::GPUBufferFormat GLESC::GAPI::OpenGLAPI::getTextureColorFormat (TextureID textureID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 328 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getTextureColorFormat", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Passed object is not a texture.");
            D_ASSERT_TRUE(isTextureBound(textureID), "Passed texture is not bound.");
            GLint internalFormat;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetTexLevelParameteriv", GL_TEXTURE_2D, 0,
                                             GL_TEXTURE_INTERNAL_FORMAT, &internalFormat);
            glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_INTERNAL_FORMAT, &internalFormat);
            Enums::Texture::GPUBufferFormat externalFormatEnum =
                static_cast<Enums::Texture::GPUBufferFormat>(internalFormat);
            Logger::get().info("\t\tInternal format: " + Enums::toString(externalFormatEnum));
            return externalFormatEnum;
        }
References D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::Logger::get(), GLESC::Logger::info(), GLESC::isIterable_v, isTexture(), isTextureBound(), and GLESC::GAPI::Enums::toString().
Referenced by getTextureData().
getTextureData()
std::vector< UByte > GLESC::GAPI::OpenGLAPI::getTextureData (TextureID textureID, Enums::Texture::Types textureType) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 375 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getTextureData", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Object is not a texture");
            D_ASSERT_TRUE(isTextureBound(textureID), "Passed texture is not bound.");
            bindTexture(textureID, textureType);
            GLint textureWidth = getTextureWidth(textureID);
            GLint textureHeight = getTextureHeight(textureID);
            Enums::Texture::GPUBufferFormat internalBufferFormat = getTextureColorFormat(textureID);
            size_t numBytes;
            GLuint padding;
            Enums::Texture::CPUBufferFormat extractedFormat;
            if (internalBufferFormat == Enums::Texture::GPUBufferFormat::RGB ||
                internalBufferFormat == Enums::Texture::GPUBufferFormat::RGB8) {
                numBytes = textureWidth * textureHeight * 3;
                extractedFormat = Enums::Texture::CPUBufferFormat::RGB;
                padding = 1;
            }
            else if (internalBufferFormat == Enums::Texture::GPUBufferFormat::RGBA ||
                internalBufferFormat == Enums::Texture::GPUBufferFormat::RGBA8) {
                numBytes = textureWidth * textureHeight * 4;
                extractedFormat = Enums::Texture::CPUBufferFormat::RGBA;
                padding = 4;
            }
            else
                D_ASSERT_FALSE(true, "Invalid texture format.");
            std::vector<UByte> data(numBytes);
            auto extractedFormatGL = static_cast<GLenum>(extractedFormat);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glPixelStorei", GL_PACK_ALIGNMENT, padding);
            glPixelStorei(GL_PACK_ALIGNMENT, padding);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetTexImage", GL_TEXTURE_2D, 0, extractedFormatGL,
                                             GL_UNSIGNED_BYTE, "data.data()");
            glGetTexImage(GL_TEXTURE_2D, 0, extractedFormatGL, GL_UNSIGNED_BYTE, data.data());
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glPixelStorei", GL_PACK_ALIGNMENT, 4);
            glPixelStorei(GL_PACK_ALIGNMENT, 4); // Reset to default
            return data;
        }
References bindTexture(), D_ASSERT_FALSE, D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, getTextureColorFormat(), getTextureHeight(), getTextureWidth(), GLESC::isIterable_v, isTexture(), and isTextureBound().
getTextureHeight()
UInt GLESC::GAPI::OpenGLAPI::getTextureHeight (TextureID textureID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 345 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getTextureHeight", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Passed object is not a texture.");
            D_ASSERT_TRUE(isTextureBound(textureID), "Passed texture is not bound.");
            GLint textureHeight;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetTexLevelParameteriv", GL_TEXTURE_2D, 0,
                                             GL_TEXTURE_HEIGHT, &textureHeight);
            glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_HEIGHT, &textureHeight);
            D_ASSERT_TRUE(textureHeight > 0, "Invalid texture height.");
            return static_cast<UInt>(textureHeight);
        }
References D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, isTexture(), and isTextureBound().
Referenced by getTextureData().
getTextureWidth()
UInt GLESC::GAPI::OpenGLAPI::getTextureWidth (TextureID textureID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 360 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getTextureWidth", textureID);
            D_ASSERT_TRUE(isTexture(textureID), "Passed object is not a texture.");
            D_ASSERT_TRUE(isTextureBound(textureID), "Passed texture is not bound.");
            GLint textureWidth;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetTexLevelParameteriv", GL_TEXTURE_2D, 0,
                                             GL_TEXTURE_WIDTH, &textureWidth);
            glGetTexLevelParameteriv(GL_TEXTURE_2D, 0, GL_TEXTURE_WIDTH, &textureWidth);
            D_ASSERT_TRUE(textureWidth > 0, "Invalid texture width.");
            return static_cast<UInt>(textureWidth);
        }
References D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, isTexture(), and isTextureBound().
Referenced by getTextureData().
getUniformLocation()
Int GLESC::GAPI::OpenGLAPI::getUniformLocation (const std::string & uName) const inline override virtual
Check if the uniform location is cached.
Parameters
uName The name of the uniform
Returns
-1 if the uniform location is not cached, otherwise the uniform location
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 993 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getUniformLocation", uName);
            auto it = uniformLocationsCache.find(uName);
            if (it != uniformLocationsCache.end()) {
                // If the uniform is found, return the location.
                GAPI_FUNCTION_IMPLEMENTATION_LOG("cacheing uniform location...", uName);
                return it->second;
            }
            // If the uniform is not found, get the location and cache it.
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformLocation", boundShaderProgram,
                                             uName);
            GLint location = glGetUniformLocation(boundShaderProgram, uName.c_str());
            D_ASSERT_NOT_EQUAL(location, -1, "Uniform " + uName + " not found.");
            uniformLocationsCache[uName] = location;
            return location;
        }
References GLESC::GAPI::IGraphicInterface::boundShaderProgram, D_ASSERT_NOT_EQUAL, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and GLESC::GAPI::IGraphicInterface::uniformLocationsCache.
getUniformValue()
template<typename Type > auto GLESC::GAPI::OpenGLAPI::getUniformValue (Int location) inline
Definition at line 861 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("getUniformValue", location);
            Type value{};
            // Floats
            if constexpr (std::is_floating_point_v<Type>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 &value);
                glGetUniformfv(boundShaderProgram, location, &value);
            }
            else if constexpr (std::is_same_v<Type, Vec2F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformfv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec3F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformfv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec4F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformfv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Mat2F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 &value[0][0]);
                glGetUniformfv(boundShaderProgram, location, &value[0][0]);
                if constexpr (rowMajorMatrix) {
                    value = value.transpose();
                }
            }
            else if constexpr (std::is_same_v<Type, Mat3F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 &value[0][0]);
                glGetUniformfv(boundShaderProgram, location, &value[0][0]);
                if constexpr (rowMajorMatrix) {
                    value = value.transpose();
                }
            }
            else if constexpr (std::is_same_v<Type, Mat4F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformfv", boundShaderProgram, location,
                                                 &value[0][0]);
                glGetUniformfv(boundShaderProgram, location, &value[0][0]);
                if constexpr (rowMajorMatrix) {
                    value = value.transpose();
                }
            }
            // Integers
            else if constexpr (std::is_same_v<Type, Int>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 &value);
                glGetUniformiv(boundShaderProgram, location, &value);
            }
            else if constexpr (std::is_same_v<Type, Vec2I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformiv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec3I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformiv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec4I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformiv(boundShaderProgram, location, value.data.data());
            }
            // Unsigned Integers
            else if constexpr (std::is_unsigned_v<Type>) {
                unsigned int temp = static_cast<unsigned int>(value);
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformuiv", boundShaderProgram, location,
                                                 &value);
                glGetUniformuiv(boundShaderProgram, location, &temp);
                value = static_cast<Type>(temp);
            }
            else if constexpr (std::is_same_v<Type, Vec2UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformuiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformuiv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec3UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformuiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformuiv(boundShaderProgram, location, value.data.data());
            }
            else if constexpr (std::is_same_v<Type, Vec4UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformuiv", boundShaderProgram, location,
                                                 value.data.data());
                glGetUniformuiv(boundShaderProgram, location, value.data.data());
            }
            // Boolean
            else if constexpr (std::is_same_v<Type, Bool>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 &value);
                glGetUniformiv(boundShaderProgram, location, &value);
                return static_cast<bool>(value);
            }
            else if constexpr (std::is_same_v<Type, Vec2B>) {
                Vec2I temp;
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 temp.data.data());
                glGetUniformiv(boundShaderProgram, location, temp.data.data());
                value.x() = static_cast<bool>(temp.x());
                value.y() = static_cast<bool>(temp.y());
            }
            else if constexpr (std::is_same_v<Type, Vec3B>) {
                Vec3I temp;
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 temp.data.data());
                glGetUniformiv(boundShaderProgram, location, temp.data.data());
                value.x() = static_cast<bool>(temp.x());
                value.y() = static_cast<bool>(temp.y());
                value.z() = static_cast<bool>(temp.z());
            }
            else if constexpr (std::is_same_v<Type, Vec4B>) {
                Vec4I temp;
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetUniformiv", boundShaderProgram, location,
                                                 temp.data.data());
                glGetUniformiv(boundShaderProgram, location, temp.data.data());
                value.x() = static_cast<bool>(temp.x());
                value.y() = static_cast<bool>(temp.y());
                value.z() = static_cast<bool>(temp.z());
                value.w() = static_cast<bool>(temp.w());
            }
            else {
                D_ASSERT_TRUE(false, "Invalid uniform type.");
            }
            return value;
        }
References GLESC::GAPI::IGraphicInterface::boundShaderProgram, D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and GLESC::GAPI::IGraphicInterface::rowMajorMatrix.
getViewport()
Viewport GLESC::GAPI::OpenGLAPI::getViewport () inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 54 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("getViewport");
            Int viewport[4];
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetIntegerv", GL_VIEWPORT, viewport);
            glGetIntegerv(GL_VIEWPORT, viewport);
            return Viewport{viewport[0], viewport[1], viewport[2], viewport[3]};
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
initGLEW()
static void GLESC::GAPI::OpenGLAPI::initGLEW () inline static private
Must be called after creating the window and before enabling gl functions like glEnable() or glCullFace()
Definition at line 1074 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("initGLEW");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glewExperimental", GL_TRUE);
            glewExperimental = GL_TRUE;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glewInit", 0);
            GLuint err = glewInit();
            std::string
                errStr = std::string(reinterpret_cast<const char*>(glewGetErrorString(err)));
            D_ASSERT_GLEW_OK((err == GLEW_OK), errStr);
        }
References D_ASSERT_GLEW_OK, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
Referenced by postWindowCreationInit().
isBuffer()
Bool GLESC::GAPI::OpenGLAPI::isBuffer (UInt bufferID) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 454 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("isBuffer", bufferID);
            return glIsBuffer(bufferID) ? Bool::True : Bool::False;
        }
References GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
isShaderProgram()
bool GLESC::GAPI::OpenGLAPI::isShaderProgram (UInt shaderProgram) inline override virtual
Checks if the given shader program is a shader program.
Parameters
shaderProgram The shader program ID
Returns
true if the given shader program is a shader program, false otherwise.
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 746 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("isShaderProgram", shaderProgram);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glIsProgram", shaderProgram);
            // TODO: Cache shader programs instead of calling glIsProgram every time.
            return glIsProgram(shaderProgram);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
isTexture()
Bool GLESC::GAPI::OpenGLAPI::isTexture (TextureID textureID) inline override private
Definition at line 1086 of file OpenGLAPI.h.
{
            Bool isTextureBool =
                static_cast<Bool>(textureCache.find(textureID) != textureCache.end());
            return isTextureBool;
        }
References GLESC::isIterable_v, and GLESC::GAPI::IGraphicInterface::textureCache.
Referenced by bindTexture(), bindTextureOnSlot(), deleteTexture(), getTextureColorFormat(), getTextureData(), getTextureHeight(), and getTextureWidth().
isTextureBound()
Bool GLESC::GAPI::OpenGLAPI::isTextureBound (TextureID textureID) inline override private
Definition at line 1092 of file OpenGLAPI.h.
{
            Bool isTextureBoundBool =
                static_cast<Bool>(textureID == boundTexture);
            return isTextureBoundBool;
        }
References GLESC::GAPI::IGraphicInterface::boundTexture, and GLESC::isIterable_v.
Referenced by getTextureColorFormat(), getTextureData(), getTextureHeight(), and getTextureWidth().
linkOK()
bool GLESC::GAPI::OpenGLAPI::linkOK (UInt shaderProgram, Char * message) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 719 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("linkOK", shaderProgram, message);
            GLint success;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetProgramiv", shaderProgram, GL_LINK_STATUS,
                                             &success);
            glGetProgramiv(shaderProgram, GL_LINK_STATUS, &success);
            if (!success) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glGetProgramInfoLog", shaderProgram, 512,
                                                 nullptr, message);
                glGetProgramInfoLog(shaderProgram, 512, nullptr, message);
                return false;
            }
            return true;
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
loadAndCompileShader()
UInt GLESC::GAPI::OpenGLAPI::loadAndCompileShader (Enums::ShaderTypes shaderType, const std::string & shaderSource) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 665 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("loadAndCompileShader", shaderType, shaderSource);
            auto shaderTypeGL = static_cast<GLenum>(shaderType);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glCreateShader", shaderTypeGL);
            GLuint vertexShader = glCreateShader(shaderTypeGL);
            const Char* source = shaderSource.c_str();
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glShaderSource", vertexShader, 1, &source, nullptr);
            glShaderSource(vertexShader, 1, &source, nullptr);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glCompileShader", vertexShader);
            glCompileShader(vertexShader);
            return vertexShader;
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
postWindowCreationInit()
void GLESC::GAPI::OpenGLAPI::postWindowCreationInit () inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 104 of file OpenGLAPI.h.
{
            // Initialize GLEW, must be called before the following OpenGL calls
            initGLEW();
            Logger::get().success("Glew Initialized!");
            // Enable depth test
            // Fragments will be discarded if they are behind
            // More info: https://www.khronos.org/opengl/wiki/Depth_Test
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glEnable", GL_DEPTH_TEST);
            glEnable(GL_DEPTH_TEST);
            // Accept fragment if it closer to the camera than the former one
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDepthFunc", GL_LESS);
            glDepthFunc(GL_LESS);
            // Enable back face culling
            // Important for performance
            // More info: https://www.khronos.org/opengl/wiki/Face_Culling
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glEnable", GL_CULL_FACE);
            glEnable(GL_CULL_FACE);
            // Cull back faces (default)
            // Important for performance and to avoid self-shadowing
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glCullFace", GL_BACK);
            glCullFace(GL_BACK);
            // Set the front face to be counter-clockwise (default)
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glFrontFace", GL_CCW);
            glFrontFace(GL_CCW);
            // Enable blending
            // Important for transparency and other effects
            // More info: https://www.khronos.org/opengl/wiki/Blending
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glEnable", GL_BLEND);
            glEnable(GL_BLEND);
            // Set blending function to alpha blending
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBlendFunc", GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
            // Set blending equation to add (default)
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBlendEquation", GL_FUNC_ADD);
            glBlendEquation(GL_FUNC_ADD);
            // Enable opengl debug callback
            // Improves debugging outputs
            GL_ENABLE_DEBUG_CALLBACK();
            // This makes our buffer swap synchronized with the monitor's vertical refresh
            // Parameters: 0 for immediate updates,
            // 1 for updates synchronized with the vertical retrace,
            // -1 for adaptive v-sync
            // More info: https://wiki.libsdl.org/SDL2/SDL_GL_SetSwapInterval
            //GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_SetSwapInterval", 1);
            //if (SDL_GL_SetSwapInterval(1) == -1)
            //    throw EngineException(std::string("Unable activate v-sync (swap interval): ") +
            //        std::string(SDL_GetError()));
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GLESC::Logger::get(), GL_ENABLE_DEBUG_CALLBACK, initGLEW(), GLESC::isIterable_v, and GLESC::Logger::success().
preWindowCreationInit()
void GLESC::GAPI::OpenGLAPI::preWindowCreationInit () inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 71 of file OpenGLAPI.h.
{
            PRINT_GAPI_INIT("OpenGL", std::to_string(GLESC_GL_MAJOR_VERSION) + "." +
                            std::to_string(GLESC_GL_MINOR_VERSION));
            // Core functions of OpenGL a.k.a. full modern openGL functionality.
            // More info: https://wiki.libsdl.org/SDL_GLprofile
#ifdef GLESC_GLSL_CORE_PROFILE
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_CONTEXT_PROFILE_MASK",
                                             SDL_GL_CONTEXT_PROFILE_CORE);
            setSDLGLAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
#else
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_CONTEXT_PROFILE_MASK",
                                             SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
            setSDLGLAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY);
#endif
            // We're using OpenGL Version 4.3 (released in 2012).
            // Changing this numbers will change some functions available of OpenGL.
            // Choosing a relatively old version of OpenGl allow most computers to use it.
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_CONTEXT_MAJOR_VERSION",
                                             GLESC_GL_MAJOR_VERSION);
            setSDLGLAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, GLESC_GL_MAJOR_VERSION);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_CONTEXT_MINOR_VERSION",
                                             GLESC_GL_MINOR_VERSION);
            setSDLGLAttribute(SDL_GL_CONTEXT_MINOR_VERSION, GLESC_GL_MINOR_VERSION);
            // Stencil size of 4 bits is used
            // Could be increased later if needed
            // Increases performance the lower it is, fewer data stored in each pixel
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_STENCIL_SIZE", 4);
            setSDLGLAttribute(SDL_GL_STENCIL_SIZE, 4);
            // Enable debug context
            // Possible performance loss
            GL_SET_DEBUG_CONTEXT_ATTRIBUTE();
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GL_SET_DEBUG_CONTEXT_ATTRIBUTE, GLESC_GL_MAJOR_VERSION, GLESC_GL_MINOR_VERSION, GLESC::isIterable_v, PRINT_GAPI_INIT, and setSDLGLAttribute().
readPixelColor()
RGBAColor GLESC::GAPI::OpenGLAPI::readPixelColor (int x, int y) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 196 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("readPixelColor", x, y);
            RGBAColor color;
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glReadPixels", x, y, 1, 1, GL_RGB,
                                             GL_UNSIGNED_BYTE, color.r, color.g, color.b, color.a);
            glReadPixels(x, y, 1, 1, GL_RGB, GL_UNSIGNED_BYTE, &color);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("post glReadPixels", x, y, 1, 1, GL_RGB,
                                             GL_UNSIGNED_BYTE, color.r, color.g, color.b, color.a);
            return color;
        }
References GLESC::GAPI::RGBAColor::a, GLESC::GAPI::RGBAColor::b, GLESC::GAPI::RGBAColor::g, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and GLESC::GAPI::RGBAColor::r.
readPixelColorNormalized()
RGBAColorNormalized GLESC::GAPI::OpenGLAPI::readPixelColorNormalized (UInt x, UInt y) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 207 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("readPixelColorNormalized", x, y);
            RGBAColorNormalized color{};
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glReadPixels", x, y, 1, 1, GL_RGB,
                                             GL_FLOAT, color.r, color.g, color.b, color.a);
            glReadPixels(x, y, 1, 1, GL_RGBA, GL_FLOAT, &color);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("post glReadPixels", x, y, 1, 1, GL_RGB,
                                             GL_UNSIGNED_BYTE, color.r, color.g, color.b, color.a);
            return color;
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
setBufferData()
void GLESC::GAPI::OpenGLAPI::setBufferData (const Void * data, Size elementCount, Size elementSize, Enums::BufferTypes bufferType, Enums::BufferUsages bufferUsage) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 502 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setBufferStaticData", "vectorData (is a pointer,can't be printed)",
                              elementCount, elementSize, bufferType, bufferUsage);
            // Only uncomment for debugging purposes, it will print the buffer data
            // It's VERY slow
            //if (bufferType == Enums::BufferTypes::Index)
            //    GAPI_PRINT_BUFFER_DATA(UInt, data, elementCount*elementSize);
            //else
            //    GAPI_PRINT_BUFFER_DATA(Float, data, elementCount*elementSize);
            auto type = static_cast<GLenum>(bufferType);
            auto usage = static_cast<GLenum>(bufferUsage);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBufferData", type, elementCount * elementSize, data, usage);
            glBufferData(type, elementCount * elementSize, data, usage);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
Referenced by setIndexBufferData().
setDepthFunction()
void GLESC::GAPI::OpenGLAPI::setDepthFunction (Enums::DepthFuncs depthFunction) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 162 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setDepthFunction", depthFunction);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glDepthFunc", depthFunction);
            glDepthFunc(static_cast<GLenum>(depthFunction));
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
setDynamicBufferData()
void GLESC::GAPI::OpenGLAPI::setDynamicBufferData (UInt size, Enums::BufferTypes bufferType) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 487 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("allocateDynamicBuffer", size, bufferType);
            auto bufferTypeGL = static_cast<GLenum>(bufferType);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBufferData", bufferTypeGL, size, nullptr);
            glBufferData(bufferTypeGL, size, nullptr, GL_DYNAMIC_DRAW);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
setIndexBufferData()
void GLESC::GAPI::OpenGLAPI::setIndexBufferData (const UInt * data, Size count, Enums::BufferUsages buferUsage) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 494 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setIndexBufferData", "vectorData (is a pointer,can't be printed)",
                              count);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBufferData", data, count, sizeof(UInt),
                                             Enums::BufferTypes::Index, buferUsage);
            setBufferData(data, count, sizeof(UInt), Enums::BufferTypes::Index, buferUsage);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and setBufferData().
setSDLGLAttribute()
void GLESC::GAPI::OpenGLAPI::setSDLGLAttribute (SDL_GLattr attrib, int val) inline private
Definition at line 1062 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setSDLGLAttribute", attrib, val);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_SetAttribute", attrib, val);
            int err = SDL_GL_SetAttribute(attrib, val);
            D_ASSERT_NOT_EQUAL(err, -1, "Unable to set gl attribute: " + std::string(SDL_GetError()));
        }
References D_ASSERT_NOT_EQUAL, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
Referenced by preWindowCreationInit().
setTextureData()
Void GLESC::GAPI::OpenGLAPI::setTextureData (Enums::Texture::Types textureType, Int level, UInt width, UInt height, Enums::Texture::CPUBufferFormat inputFormat, Enums::Texture::BitDepth bitsPerPixel, const UByte * texelBuffer) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 285 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setTextureData", level, height, width, "texelBuffer");
            D_ASSERT_TRUE(anyTextureBound(), "No texture bound.");
            GLenum GLinternalFormat;
            auto inputFormatGL = static_cast<GLenum>(inputFormat);
            auto textureTypeGL = static_cast<GLenum>(textureType);
            GLuint padding;
            if (inputFormat == Enums::Texture::CPUBufferFormat::RGB &&
                bitsPerPixel == Enums::Texture::BitDepth::Bit24) {
                GLinternalFormat = GL_RGB8;
                padding = 1;
            }
            else if (inputFormat == Enums::Texture::CPUBufferFormat::RGBA &&
                bitsPerPixel == Enums::Texture::BitDepth::Bit32) {
                GLinternalFormat = GL_RGBA8;
                padding = 4;
            }
            else
                D_ASSERT_FALSE(true, "Invalid texture format.");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glPixelStorei", GL_UNPACK_ALIGNMENT, padding);
            glPixelStorei(GL_UNPACK_ALIGNMENT, padding);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glTexImage2D", textureTypeGL, level, GLinternalFormat,
                                             width, height, 0, inputFormatGL,
                                             GL_UNSIGNED_BYTE, texelBuffer);
            glTexImage2D(textureTypeGL, level, GLinternalFormat, width, height, 0, inputFormatGL,
                         GL_UNSIGNED_BYTE, texelBuffer);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glPixelStorei", GL_UNPACK_ALIGNMENT, 4);
            glPixelStorei(GL_UNPACK_ALIGNMENT, 4); // Reset to default
        }
References anyTextureBound(), D_ASSERT_FALSE, D_ASSERT_TRUE, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
setUniform()
template<typename Type > static void GLESC::GAPI::OpenGLAPI::setUniform (Int location, Type value) inline static
Definition at line 768 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setUniformValue", location, value);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform1i", location, value);
            // Floats
            if constexpr (std::is_floating_point_v<Type>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform1f", location, value);
                glUniform1f(location, value);
            }
            else if constexpr (std::is_same_v<Type, Vec2F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform2f", location, value.x(), value.y());
                glUniform2f(location, value.x(), value.y());
            }
            else if constexpr (std::is_same_v<Type, Vec3F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform3f", location, value.x(), value.y(), value.z());
                glUniform3f(location, value.x(), value.y(), value.z());
            }
            else if constexpr (std::is_same_v<Type, Vec4F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform4f", location, value.x(), value.y(), value.z(),
                                                 value.w());
                glUniform4f(location, value.x(), value.y(), value.z(), value.w());
            }
            else if constexpr (std::is_same_v<Type, Mat2F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniformMatrix2fv", location, 1, GL_TRUE,
                                                 &value[0][0]);
                glUniformMatrix2fv(location, 1, rowMajorMatrix, &value[0][0]);
            }
            else if constexpr (std::is_same_v<Type, Mat3F>) {
                glUniformMatrix3fv(location, 1, rowMajorMatrix, &value[0][0]);
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniformMatrix3fv", location, 1, GL_TRUE,
                                                 &value[0][0]);
            }
            else if constexpr (std::is_same_v<Type, Mat4F>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniformMatrix4fv", location, 1, GL_TRUE,
                                                 &value[0][0]);
                glUniformMatrix4fv(location, 1, rowMajorMatrix, &value[0][0]);
            }
            // Integers
            else if constexpr (std::is_same_v<Type, Int>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform1i", location, value);
                glUniform1i(location, value);
            }
            else if constexpr (std::is_same_v<Type, Vec2I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform2i", location, value.x(), value.y());
                glUniform2i(location, value.x(), value.y());
            }
            else if constexpr (std::is_same_v<Type, Vec3I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform3i", location, value.x(), value.y(), value.z());
                glUniform3i(location, value.x(), value.y(), value.z());
            }
            else if constexpr (std::is_same_v<Type, Vec4I>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform4i", location, value.x(), value.y(), value.z(),
                                                 value.w());
                glUniform4i(location, value.x(), value.y(), value.z(), value.w());
            }
            // Unsigned Integers
            else if constexpr (std::is_unsigned_v<Type>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform1ui", location, value);
                glUniform1ui(location, value);
            }
            else if constexpr (std::is_same_v<Type, Vec2UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform2ui", location, value.x(), value.y());
                glUniform2ui(location, value.x(), value.y());
            }
            else if constexpr (std::is_same_v<Type, Vec3UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform3ui", location, value.x(), value.y(), value.z());
                glUniform3ui(location, value.x(), value.y(), value.z());
            }
            else if constexpr (std::is_same_v<Type, Vec4UI>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform4ui", location, value.x(), value.y(), value.z(),
                                                 value.w());
                glUniform4ui(location, value.x(), value.y(), value.z(), value.w());
            }
            // Boolean
            else if constexpr (std::is_same_v<Type, Bool>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform1i", location, value);
                glUniform1i(location, value);
            }
            else if constexpr (std::is_same_v<Type, Vec2B>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform2i", location, value.x(), value.y());
                glUniform2i(location, value.x(), value.y());
            }
            else if constexpr (std::is_same_v<Type, Vec3B>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform3i", location, value.x(), value.y(), value.z());
                glUniform3i(location, value.x(), value.y(), value.z());
            }
            else if constexpr (std::is_same_v<Type, Vec4B>) {
                GAPI_FUNCTION_IMPLEMENTATION_LOG("glUniform4i", location, value.x(), value.y(), value.z(),
                                                 value.w());
                glUniform4i(location, value.x(), value.y(), value.z(), value.w());
            }
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, GLESC::isIterable_v, and GLESC::GAPI::IGraphicInterface::rowMajorMatrix.
setVertexAttribDivisor()
void GLESC::GAPI::OpenGLAPI::setVertexAttribDivisor (UInt index, UInt divisor) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 571 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setVertexAttribDivisor", index, divisor);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glVertexAttribDivisor", index, divisor);
            glVertexAttribDivisor(index, divisor);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
setViewport() [1/2]
void GLESC::GAPI::OpenGLAPI::setViewport (Int width, Int height) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 44 of file OpenGLAPI.h.
{
            this->setViewport(0, 0, width, height);
        }
References setViewport().
Referenced by setViewport().
setViewport() [2/2]
void GLESC::GAPI::OpenGLAPI::setViewport (Int x, Int y, Int width, Int height) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 48 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("setViewport", x, y, width, height);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glViewport", x, y, width, height);
            glViewport(x, y, width, height);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
swapBuffers()
void GLESC::GAPI::OpenGLAPI::swapBuffers (SDL_Window & window) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 63 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("swapBuffers", "SDL_Window");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("SDL_GL_SwapWindow", "SDL_Window");
            SDL_GL_SwapWindow(&window);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
unbindBuffer()
void GLESC::GAPI::OpenGLAPI::unbindBuffer (Enums::BufferTypes bufferType) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 473 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("unbindBuffer", bufferType);
            auto bufferTypeGL = static_cast<GLenum>(bufferType);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindBuffer", bufferTypeGL, 0);
            glBindBuffer(bufferTypeGL, 0);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
unbindTexture()
Void GLESC::GAPI::OpenGLAPI::unbindTexture (Enums::Texture::Types textureType) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 443 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("unbindTexture");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindTexture", GL_TEXTURE_2D, 0);
            glBindTexture(GL_TEXTURE_2D, 0);
            boundTexture = 0;
        }
References GLESC::GAPI::IGraphicInterface::boundTexture, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
unbindVertexArray()
void GLESC::GAPI::OpenGLAPI::unbindVertexArray () inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 583 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_NO_ARGS_LOG("unbindVertexArray");
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glBindVertexArray", 0);
            glBindVertexArray(0);
        }
References GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_NO_ARGS_LOG, and GLESC::isIterable_v.
useShaderProgram()
void GLESC::GAPI::OpenGLAPI::useShaderProgram (UInt shaderProgram) inline override virtual
Implements GLESC::GAPI::IGraphicInterface.
Definition at line 734 of file OpenGLAPI.h.
{
            GAPI_FUNCTION_LOG("useShaderProgram", shaderProgram);
            GAPI_FUNCTION_IMPLEMENTATION_LOG("glUseProgram", shaderProgram);
            glUseProgram(shaderProgram);
            boundShaderProgram = shaderProgram;
        }
References GLESC::GAPI::IGraphicInterface::boundShaderProgram, GAPI_FUNCTION_IMPLEMENTATION_LOG, GAPI_FUNCTION_LOG, and GLESC::isIterable_v.
Member Data Documentation
context
SDL_GLContext GLESC::GAPI::OpenGLAPI::context {} private
Definition at line 1105 of file OpenGLAPI.h.
{};
Referenced by createContext(), deleteContext(), and getContext().
The documentation for this class was generated from the following file:
OpenGLAPI.h