GLESC: GLESC::ECS::EntityManager Class Reference
GLESC::ECS::EntityManager Class Reference
#include <EntityManager.h>
Public Member Functions
EntityManager ()
~EntityManager ()=default
The default destructor is correct, no need to define it.
void addComponentToEntity (EntityID entity, ComponentID componentID)
Add a component to the entity. The entity must exist.
bool areThereLivingEntities () const
bool canEntityBeCreated (const EntityName &name) const
Check if the entity can be created with the given name and the current state of the entity manager.
EntityID createNextEntity (const EntityName &nameParam, const EntityMetadata &metadata)
Create an entity with the given name. The name must be unique.
void destroyEntity (EntityID entity)
Destroy the entity with the given ID. The entity must exist.
bool doesEntityExist (const EntityName &name) const
Check if the entity with the given name exists.
bool doesEntityExist (EntityID entity) const
Check if the entity with the given ID exists.
bool doesEntityHaveComponent (EntityID entity, ComponentID componentID) const
Check if the entity has the given component. The entity must exist and the component must be in the range of the signature.
const std::queue< EntityID > & getAvailableEntities () const
const unsigned long long & getEntityCounter () const
EntityID getEntityID (const EntityName &name) const
Get the entity ID from the entity name.
const std::unordered_map< EntityID, EntityName > & getEntityIDToName () const
const EntityMetadata & getEntityMetadata (EntityID entity) const
Get the entity metadata from the entity ID. The entity must exist.
const EntityName & getEntityName (EntityID entity) const
Get the entity name from the entity ID. The entity must exist.
const std::unordered_map< EntityName, EntityID > & getEntityNameToID () const
const std::vector< EntityID > & getInstancedEntities (const EntityName &name) const
const EntityID & getLivingEntityCount () const
Signature getSignature (EntityID entity) const
Get the signature of the entity. The entity must exist.
const std::array< Signature, maxEntities > & getSignatures () const
bool isComponentInRange (ComponentID componentID) const
Check if the component ID is in the range of the signature.
bool isEntityAlive (const EntityName &name) const
Check if the entity with the given name is alive.
bool isEntityAlive (EntityID entity) const
Check if the entity with the given ID is alive.
bool isEntityInstanced (const EntityName &name) const
void removeComponentFromEntity (EntityID entity, ComponentID componentID)
Remove a component from the entity. The entity must exist.
S_ASSERT_TRUE (firstEntity==0, "First entity must be 0, ComponentArray uses the entity ID as index, " "if edited this, it needs ComponentArray to be updated as well")
EntityID tryGetEntity (const EntityName &name) const
Tries to get the entity ID from the entity name.
Public Attributes
const EntityName nullEntityName = EntityName{"NULL_ENTITY"}
Static Public Attributes
static constexpr EntityID firstEntity {0}
static constexpr EntityID nullEntity {std::numeric_limits<EntityID>::max()}
Null entity with ID 0. This is used to indicate that an entity does not exist.
Protected Attributes
std::queue< EntityID > availableEntities
Queue of the available entities, used to avoid iterating over all the entities.
unsigned long long entityCounter {}
Counter that counts all the entities that have ever been created. It's useful to be able to create entities without names, so we never create entities with the same name.
std::unordered_map< EntityID, EntityName > entityIDToName
std::unordered_map< EntityID, EntityMetadata > entityMetadata
std::unordered_map< EntityName, EntityID > entityNameToID
std::unordered_map< EntityName, std::vector< EntityID > > instancedEntities
std::unordered_map< EntityName, int > instancesNextID
EntityID livingEntityCount {}
The number of living entities.
std::array< Signature, maxEntities > signatures
Array of the signatures of the entities.
Friends
class ECS
Detailed Description
Definition at line 28 of file EntityManager.h.
Constructor & Destructor Documentation
EntityManager()
EntityManager::EntityManager ()
Definition at line 20 of file EntityManager.cpp.
{
    // Initialize the queue with all possible entity IDs
    for (EntityID entity = firstEntity; entity < maxEntities + firstEntity; ++entity) {
        availableEntities.push(entity);
    }
}
References availableEntities, firstEntity, GLESC::isIterable_v, and GLESC::ECS::maxEntities.
~EntityManager()
GLESC::ECS::EntityManager::~EntityManager () default
The default destructor is correct, no need to define it.
Member Function Documentation
addComponentToEntity()
void EntityManager::addComponentToEntity (EntityID entity, ComponentID componentID)
Add a component to the entity. The entity must exist.
Parameters
entity The ID of the entity
componentID The ID of the component
Definition at line 127 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist to add a component");
    D_ASSERT_TRUE(isComponentInRange(componentID), "Component must be in range to be added");
    if (doesEntityHaveComponent(entity, componentID)) return;
    signatures[entity].set(componentID);
}
References D_ASSERT_TRUE, doesEntityExist(), doesEntityHaveComponent(), isComponentInRange(), GLESC::isIterable_v, and signatures.
Referenced by GLESC::ECS::ECSCoordinator::addComponent().
areThereLivingEntities()
bool EntityManager::areThereLivingEntities () const
Definition at line 162 of file EntityManager.cpp.
{
    return livingEntityCount > 0;
}
References livingEntityCount.
Referenced by destroyEntity().
canEntityBeCreated()
bool EntityManager::canEntityBeCreated (const EntityName & name) const
Check if the entity can be created with the given name and the current state of the entity manager.
Parameters
name The name of the entity
Returns
True if the entity can be created, false otherwise
Definition at line 156 of file EntityManager.cpp.
{
    return livingEntityCount < maxEntities
        && !availableEntities.empty()
        && entityNameToID.find(name) == entityNameToID.end();
}
References availableEntities, entityNameToID, livingEntityCount, and GLESC::ECS::maxEntities.
Referenced by createNextEntity().
createNextEntity()
EntityID EntityManager::createNextEntity (const EntityName & nameParam, const EntityMetadata & metadata)
Create an entity with the given name. The name must be unique.
Parameters
nameParam
Returns
Definition at line 27 of file EntityManager.cpp.
{
    EntityID id = availableEntities.front();
    EntityName name = nameParam;
    if (metadata.type == EntityType::Instance) {
        instancedEntities[nameParam].push_back(id);
        name.append(std::to_string(instancesNextID[nameParam]));
        instancesNextID[nameParam]++;
    }
    D_ASSERT_TRUE(canEntityBeCreated(name), "Entity must be able to be created");
    availableEntities.pop();
    entityIDToName.insert({id, name});
    entityNameToID.insert({name, id});
    entityMetadata.insert({id, metadata});
    ++livingEntityCount;
    ++entityCounter;
    D_ASSERT_TRUE(doesEntityExist(id), "Entity must exist after creation");
    return id;
}
References availableEntities, canEntityBeCreated(), D_ASSERT_TRUE, doesEntityExist(), entityCounter, entityIDToName, entityMetadata, entityNameToID, GLESC::Instance, instancedEntities, instancesNextID, GLESC::isIterable_v, and livingEntityCount.
Referenced by GLESC::ECS::ECSCoordinator::createEntity(), and GLESC::ECS::ECSCoordinator::createEntity().
destroyEntity()
void EntityManager::destroyEntity (EntityID entity)
Destroy the entity with the given ID. The entity must exist.
Parameters
entity The ID of the entity
Definition at line 51 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(areThereLivingEntities(), "There must be living entities to destroy one");
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist before destruction");
    D_ASSERT_TRUE((entity != GLESC::ECS::EntityManager::nullEntity), "Entity must not be nullEntity");
    if (isEntityInstanced(entityIDToName[entity])) {
        EntityName instanceName = Stringer::strip(entityIDToName[entity], "1234567890");
        std::vector<EntityID>& instancedList = this->instancedEntities[instanceName];
        auto it = std::find(instancedList.begin(), instancedList.end(), entity);
        if (it != instancedList.end())
            instancedList.erase(it);
    }
    signatures[entity].reset();
    availableEntities.push(entity);
    entityNameToID.erase(entityIDToName[entity]);
    entityIDToName.erase(entity);
    entityMetadata.erase(entity);
    --livingEntityCount;
    D_ASSERT_FALSE(doesEntityExist(entity), "Entity must not exist after destruction");
    D_ASSERT_FALSE(isEntityAlive(entity), "Entity must not be alive after destruction");
}
References areThereLivingEntities(), availableEntities, D_ASSERT_FALSE, D_ASSERT_TRUE, doesEntityExist(), entityIDToName, entityMetadata, entityNameToID, instancedEntities, isEntityAlive(), isEntityInstanced(), GLESC::isIterable_v, livingEntityCount, nullEntity, signatures, and GLESC::Stringer::strip().
Referenced by GLESC::ECS::ECSCoordinator::destroyEntity().
doesEntityExist() [1/2]
bool EntityManager::doesEntityExist (const EntityName & name) const
Check if the entity with the given name exists.
Parameters
name The name of the entity
Returns
True if the entity exists, false otherwise
Definition at line 134 of file EntityManager.cpp.
{
    return entityNameToID.find(name) != entityNameToID.end();
}
References entityNameToID.
Referenced by addComponentToEntity(), GLESC::ECS::ECSCoordinator::createEntity(), GLESC::ECS::ECSCoordinator::createEntity(), createNextEntity(), GLESC::ECS::ECSCoordinator::destroyEntity(), destroyEntity(), doesEntityHaveComponent(), GLESC::ECS::ECSCoordinator::getAssociatedEntities(), GLESC::ECS::ECSCoordinator::getComponent(), getEntityID(), getEntityMetadata(), getEntityName(), getSignature(), isEntityAlive(), and tryGetEntity().
doesEntityExist() [2/2]
bool EntityManager::doesEntityExist (EntityID entity) const
Check if the entity with the given ID exists.
Parameters
entity The ID of the entity
Returns
True if the entity exists, false otherwise
Definition at line 138 of file EntityManager.cpp.
{
    return entityIDToName.find(entity) != entityIDToName.end();
}
References entityIDToName, and GLESC::isIterable_v.
doesEntityHaveComponent()
bool EntityManager::doesEntityHaveComponent (EntityID entity, ComponentID componentID) const
Check if the entity has the given component. The entity must exist and the component must be in the range of the signature.
Parameters
entity
componentID
Returns
Definition at line 84 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist to check if it has a component");
    D_ASSERT_TRUE(isComponentInRange(componentID), "Component must be in range to check if entity has it");
    return signatures[entity][componentID];
}
References D_ASSERT_TRUE, doesEntityExist(), isComponentInRange(), GLESC::isIterable_v, and signatures.
Referenced by addComponentToEntity(), GLESC::ECS::ECSCoordinator::hasComponent(), GLESC::ECS::ECSCoordinator::printEntity(), and removeComponentFromEntity().
getAvailableEntities()
const std::queue< EntityID > & GLESC::ECS::EntityManager::getAvailableEntities () const inline
Definition at line 51 of file EntityManager.h.
{ return availableEntities; }
References availableEntities.
getEntityCounter()
const unsigned long long & GLESC::ECS::EntityManager::getEntityCounter () const inline
Definition at line 54 of file EntityManager.h.
{ return entityCounter; }
References entityCounter.
Referenced by GLESC::ECS::ECSCoordinator::createEntity().
getEntityID()
EntityID EntityManager::getEntityID (const EntityName & name) const
Get the entity ID from the entity name.
This will return the ID of the entity with the given name. The entity must exist.
Parameters
name The name of the entity
Returns
The ID of the entity
Definition at line 100 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(name), "Entity must exist to get its ID");
    return entityNameToID.at(name);
}
References D_ASSERT_TRUE, doesEntityExist(), and entityNameToID.
Referenced by GLESC::ECS::ECSCoordinator::getEntityID(), and isEntityAlive().
getEntityIDToName()
const std::unordered_map< EntityID, EntityName > & GLESC::ECS::EntityManager::getEntityIDToName () const inline
Definition at line 50 of file EntityManager.h.
{ return entityIDToName; }
References entityIDToName.
getEntityMetadata()
const EntityMetadata & EntityManager::getEntityMetadata (EntityID entity) const
Get the entity metadata from the entity ID. The entity must exist.
Parameters
entity The ID of the entity
Returns
The metadata of the entity
Definition at line 95 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist to get its metadata");
    return entityMetadata.at(entity);
}
References D_ASSERT_TRUE, doesEntityExist(), entityMetadata, and GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::getEntityMetadata().
getEntityName()
const EntityName & EntityManager::getEntityName (EntityID entity) const
Get the entity name from the entity ID. The entity must exist.
Parameters
entity The ID of the entity
Returns
The name of the entity
Definition at line 90 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist to get its name");
    return entityIDToName.at(entity);
}
References D_ASSERT_TRUE, doesEntityExist(), entityIDToName, and GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::getEntityName(), and GLESC::ECS::ECSCoordinator::printEntity().
getEntityNameToID()
const std::unordered_map< EntityName, EntityID > & GLESC::ECS::EntityManager::getEntityNameToID () const inline
Definition at line 49 of file EntityManager.h.
{ return entityNameToID; }
References entityNameToID.
Referenced by GLESC::ECS::ECSCoordinator::getAllEntities(), and GLESC::ECS::ECSCoordinator::printStatus().
getInstancedEntities()
const std::vector< EntityID > & EntityManager::getInstancedEntities (const EntityName & name) const
Definition at line 111 of file EntityManager.cpp.
{
    return instancedEntities.at(name);
}
References instancedEntities.
Referenced by GLESC::ECS::ECSCoordinator::getInstancedEntities().
getLivingEntityCount()
const EntityID & GLESC::ECS::EntityManager::getLivingEntityCount () const inline
Definition at line 53 of file EntityManager.h.
{ return livingEntityCount; }
References livingEntityCount.
getSignature()
Signature EntityManager::getSignature (EntityID entity) const
Get the signature of the entity. The entity must exist.
Parameters
entity The ID of the entity
Returns
Copy of the signature of the entity
Definition at line 79 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(doesEntityExist(entity), "Entity must exist to get its signature");
    return signatures[entity];
}
References D_ASSERT_TRUE, doesEntityExist(), GLESC::isIterable_v, and signatures.
Referenced by GLESC::ECS::ECSCoordinator::addComponent(), GLESC::ECS::ECSCoordinator::getComponents(), GLESC::ECS::ECSCoordinator::printEntity(), and GLESC::ECS::ECSCoordinator::removeComponent().
getSignatures()
const std::array< Signature, maxEntities > & GLESC::ECS::EntityManager::getSignatures () const inline
Definition at line 52 of file EntityManager.h.
{ return signatures; }
References signatures.
isComponentInRange()
bool EntityManager::isComponentInRange (ComponentID componentID) const
Check if the component ID is in the range of the signature.
Returns
True if the component ID is in the range of the signature, false otherwise
Definition at line 152 of file EntityManager.cpp.
{
    return componentID < signatures[0].size();
}
References GLESC::isIterable_v, and signatures.
Referenced by addComponentToEntity(), doesEntityHaveComponent(), and removeComponentFromEntity().
isEntityAlive() [1/2]
bool EntityManager::isEntityAlive (const EntityName & name) const
Check if the entity with the given name is alive.
Parameters
name The name of the entity
Returns
True if the entity is alive, false otherwise
Definition at line 147 of file EntityManager.cpp.
{
    // Entity is alive if it has a signature that is not empty
    return isEntityAlive(getEntityID(name));
}
References getEntityID(), and isEntityAlive().
isEntityAlive() [2/2]
bool EntityManager::isEntityAlive (EntityID entity) const
Check if the entity with the given ID is alive.
Parameters
entity The ID of the entity
Returns
True if the entity is alive, false otherwise
Definition at line 142 of file EntityManager.cpp.
{
    // Entity is alive if it has a signature that is not empty
    return doesEntityExist(entity) && !signatures[entity].none();
}
References doesEntityExist(), GLESC::isIterable_v, and signatures.
Referenced by destroyEntity(), isEntityAlive(), GLESC::ECS::ECSCoordinator::isEntityAlive(), and removeComponentFromEntity().
isEntityInstanced()
bool EntityManager::isEntityInstanced (const EntityName & name) const
Definition at line 115 of file EntityManager.cpp.
{
    std::string strippedName = Stringer::strip(name, "1234567890");
    return instancedEntities.find(strippedName) != instancedEntities.end();
}
References instancedEntities, GLESC::isIterable_v, and GLESC::Stringer::strip().
Referenced by destroyEntity(), and GLESC::ECS::ECSCoordinator::isEntityInstanced().
removeComponentFromEntity()
void EntityManager::removeComponentFromEntity (EntityID entity, ComponentID componentID)
Remove a component from the entity. The entity must exist.
Parameters
entity The ID of the entity
componentID The ID of the component
Definition at line 120 of file EntityManager.cpp.
{
    D_ASSERT_TRUE(isEntityAlive(entity), "Entity must be alive to remove a component");
    D_ASSERT_TRUE(isComponentInRange(componentID), "Component must be in range to be removed");
    D_ASSERT_TRUE(doesEntityHaveComponent(entity, componentID), "Entity must have the component to remove it");
    signatures[entity].reset(componentID);
}
References D_ASSERT_TRUE, doesEntityHaveComponent(), isComponentInRange(), isEntityAlive(), GLESC::isIterable_v, and signatures.
Referenced by GLESC::ECS::ECSCoordinator::removeComponent().
S_ASSERT_TRUE()
GLESC::ECS::EntityManager::S_ASSERT_TRUE (firstEntity = =0, "First entity must be 0, ComponentArray uses the entity ID as index, " "if edited this, it needs ComponentArray to be updated as well")
tryGetEntity()
EntityID EntityManager::tryGetEntity (const EntityName & name) const
Tries to get the entity ID from the entity name.
This will return the ID of the entity with the given name. If the entity does not exist, it will return null entity (0).
Parameters
name The name of the entity
Returns
The ID of the entity, or NULL_ENTITY if the entity does not exist
Definition at line 105 of file EntityManager.cpp.
{
    if (!doesEntityExist(name))
        return nullEntity;
    return entityNameToID.at(name);
}
References doesEntityExist(), entityNameToID, and nullEntity.
Referenced by GLESC::ECS::ECSCoordinator::tryGetEntityID().
Friends And Related Symbol Documentation
ECS
friend class ECS friend
Definition at line 29 of file EntityManager.h.
Member Data Documentation
availableEntities
std::queue<EntityID> GLESC::ECS::EntityManager::availableEntities protected
Queue of the available entities, used to avoid iterating over all the entities.
Definition at line 182 of file EntityManager.h.
Referenced by EntityManager(), canEntityBeCreated(), createNextEntity(), destroyEntity(), and getAvailableEntities().
entityCounter
unsigned long long GLESC::ECS::EntityManager::entityCounter {} protected
Counter that counts all the entities that have ever been created. It's useful to be able to create entities without names, so we never create entities with the same name.
Definition at line 206 of file EntityManager.h.
{};
Referenced by createNextEntity(), and getEntityCounter().
entityIDToName
std::unordered_map<EntityID, EntityName> GLESC::ECS::EntityManager::entityIDToName protected
Definition at line 192 of file EntityManager.h.
Referenced by createNextEntity(), destroyEntity(), doesEntityExist(), getEntityIDToName(), and getEntityName().
entityMetadata
std::unordered_map<EntityID, EntityMetadata> GLESC::ECS::EntityManager::entityMetadata protected
Definition at line 193 of file EntityManager.h.
Referenced by createNextEntity(), destroyEntity(), and getEntityMetadata().
entityNameToID
std::unordered_map<EntityName, EntityID> GLESC::ECS::EntityManager::entityNameToID protected
Definition at line 191 of file EntityManager.h.
Referenced by canEntityBeCreated(), createNextEntity(), destroyEntity(), doesEntityExist(), getEntityID(), getEntityNameToID(), and tryGetEntity().
firstEntity
constexpr EntityID GLESC::ECS::EntityManager::firstEntity {0} static constexpr
Definition at line 36 of file EntityManager.h.
{0};
Referenced by EntityManager().
instancedEntities
std::unordered_map<EntityName, std::vector<EntityID> > GLESC::ECS::EntityManager::instancedEntities protected
Definition at line 194 of file EntityManager.h.
Referenced by createNextEntity(), destroyEntity(), getInstancedEntities(), and isEntityInstanced().
instancesNextID
std::unordered_map<EntityName, int> GLESC::ECS::EntityManager::instancesNextID protected
Definition at line 195 of file EntityManager.h.
Referenced by createNextEntity().
livingEntityCount
EntityID GLESC::ECS::EntityManager::livingEntityCount {} protected
The number of living entities.
Definition at line 200 of file EntityManager.h.
{};
Referenced by areThereLivingEntities(), canEntityBeCreated(), createNextEntity(), destroyEntity(), and getLivingEntityCount().
nullEntity
constexpr EntityID GLESC::ECS::EntityManager::nullEntity {std::numeric_limits<EntityID>::max()} static constexpr
Null entity with ID 0. This is used to indicate that an entity does not exist.
Definition at line 35 of file EntityManager.h.
{std::numeric_limits<EntityID>::max()};
Referenced by destroyEntity(), GLESC::ECS::EntityFactory::tryGetEntity(), and tryGetEntity().
nullEntityName
const EntityName GLESC::ECS::EntityManager::nullEntityName = EntityName{"NULL_ENTITY"}
Definition at line 39 of file EntityManager.h.
{"NULL_ENTITY"};
signatures
std::array<Signature, maxEntities> GLESC::ECS::EntityManager::signatures protected
Array of the signatures of the entities.
Signatures start all initialized to 0
The index of the array is the ID of the entity.
Definition at line 188 of file EntityManager.h.
Referenced by addComponentToEntity(), destroyEntity(), doesEntityHaveComponent(), getSignature(), getSignatures(), isComponentInRange(), isEntityAlive(), and removeComponentFromEntity().
The documentation for this class was generated from the following files:
EntityManager.h
EntityManager.cpp