GLESC: GLESC::Math::VectorMixedAlgorithms Class Reference
GLESC::Math::VectorMixedAlgorithms Class Reference
#include <VectorMixedAlgorithms.h>
Static Public Member Functions
template<typename Type >
static bool areCollinear (const VectorData< Type, 3 > &p1, const VectorData< Type, 3 > &p2, const VectorData< Type, 3 > &p3)
Checks if points are collinear.
template<typename Type >
static bool areCollinear (const VectorData< Type, 3 > &referencePoint, const std::vector< const VectorData< Type, 3 > * > &points)
Checks if points are collinear.
template<typename Type , size_t N>
static void vectorToMatrix (const VectorData< Type, N > &vector, MatrixData< Type, N, 1 > &matrix)
Converts a vector to a matrix.
Detailed Description
Definition at line 23 of file VectorMixedAlgorithms.h.
Member Function Documentation
areCollinear() [1/2]
template<typename Type > static bool GLESC::Math::VectorMixedAlgorithms::areCollinear (const VectorData< Type, 3 > & p1, const VectorData< Type, 3 > & p2, const VectorData< Type, 3 > & p3) inline static
Checks if points are collinear.
This function checks if a set of points are collinear. The points are collinear if cross product of the direction vectors from the reference point to each point is the zero vector.
Template Parameters
Type Data type of the points (e.g., double, float).
Parameters
p1 First point.
p2 Second point.
p3 Third point.
Definition at line 54 of file VectorMixedAlgorithms.h.
{
            // Compute two vectors from the points
            VectorData<Type, 3> v1;
            VectorAlgorithms::vectorSub(p2, p1, v1);
            VectorData<Type, 3> v2;
            VectorAlgorithms::vectorSub(p3, p1, v2);
            // Early return if either vector is zero, indicating two points are the same
            // and therefore collinear with any third point
            if (VectorAlgorithms::isZero(v1) || VectorAlgorithms::isZero(v2)) {
                return true;
            }
            // Calculate the cross product of v1 and v2
            VectorData<Type, 3> crossProduct;
            VectorAlgorithms::crossProduct(v1, v2, crossProduct);
            // If the cross product is almost (0,0,0), the points are collinear
            return VectorAlgorithms::isZero(crossProduct);
        }
References GLESC::Math::VectorAlgorithms::crossProduct(), GLESC::isIterable_v, GLESC::Math::VectorAlgorithms::isZero(), and GLESC::Math::VectorAlgorithms::vectorSub().
Referenced by GLESC::Math::Plane::Plane(), areCollinear(), GLESC::Math::Vector< Type, N >::isCollinear(), TYPED_TEST(), and TYPED_TEST().
areCollinear() [2/2]
template<typename Type > static bool GLESC::Math::VectorMixedAlgorithms::areCollinear (const VectorData< Type, 3 > & referencePoint, const std::vector< const VectorData< Type, 3 > * > & points) inline static
Checks if points are collinear.
This function checks if a set of points are collinear.
See also
areCollinear(p1, p2, p3)
Template Parameters
Type Data type of the points (e.g., double, float).
Parameters
referencePoint Reference for forming direction vectors.
points Points to be checked for collinearity.
Returns
true if points are collinear, false otherwise.
Definition at line 86 of file VectorMixedAlgorithms.h.
{
            if (points.size() < 2) {
                // Fewer than two points, trivially collinear
                return true;
            }
            // Iterate over each set of three points including the reference point
            for (size_t i = 0; i < points.size() - 1; ++i) {
                for (size_t j = i + 1; j < points.size(); ++j) {
                    // Use the three-point collinearity check
                    if (!VectorMixedAlgorithms::areCollinear(referencePoint, *points[i], *points[j])) {
                        return false;
                    }
                }
            }
            // If all direction vectors are parallel, the points are collinear
            return true;
        }
References areCollinear(), and GLESC::isIterable_v.
vectorToMatrix()
template<typename Type , size_t N> static void GLESC::Math::VectorMixedAlgorithms::vectorToMatrix (const VectorData< Type, N > & vector, MatrixData< Type, N, 1 > & matrix) inline static
Converts a vector to a matrix.
This function converts a vector to a single-column matrix.
Template Parameters
Type Data type of the vector and matrix (e.g., double, float).
N Dimension of the vector and matrix.
Parameters
vector Vector to be converted.
matrix Matrix to store the vector.
Definition at line 38 of file VectorMixedAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                matrix[i][0] = vector[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::toMatrix().
The documentation for this class was generated from the following file:
VectorMixedAlgorithms.h