GLESC: GLESC::Render::Fog Class Reference
GLESC::Render::Fog Class Reference
#include <Fog.h>
Public Member Functions
Fog ()=default
const ColorRgb & getColor () const
std::vector< EntityStatsManager::Value > getDebuggingValues ()
float getDensity () const
float getEnd () const
void setColor (const ColorRgb &color)
void setDensity (float density)
void setEnd (float end)
std::string toString () const
Private Attributes
GLESC::Render::ColorRgb color {255.f, 255.f, 255.f}
GLESC::Render::Intensity< float > density {1.0f}
float end = 300.0f
Detailed Description
Definition at line 17 of file Fog.h.
Constructor & Destructor Documentation
Fog()
GLESC::Render::Fog::Fog () default
Member Function Documentation
getColor()
const ColorRgb & GLESC::Render::Fog::getColor () const inline
Definition at line 42 of file Fog.h.
{
            return color;
        }
References color.
getDebuggingValues()
std::vector< EntityStatsManager::Value > Fog::getDebuggingValues ()
Definition at line 14 of file Fog.cpp.
{
 std::vector<EntityStatsManager::Value> values;
 EntityStatsManager::Value densityValue;
 densityValue.name = "Density";
 densityValue.data = reinterpret_cast<void*>(&density.getModifiable());
 densityValue.type = EntityStatsManager::ValueType::FLOAT;
 densityValue.isModifiable = true;
 densityValue.usesSlider = true;
 densityValue.min = 0.0f;
 densityValue.max = 1.0f;
 values.push_back(densityValue);
 EntityStatsManager::Value endValue;
 endValue.name = "End";
 endValue.data = reinterpret_cast<void*>(&end);
 endValue.type = EntityStatsManager::ValueType::FLOAT;
 endValue.isModifiable = true;
 endValue.usesSlider = true;
 endValue.min = 0.0f;
 endValue.max = 1000.0f;
 values.push_back(endValue);
 EntityStatsManager::Value colorValue;
 colorValue.name = "Color";
 colorValue.data = reinterpret_cast<void*>(&color);
 colorValue.type = EntityStatsManager::ValueType::VEC3F;
 colorValue.isModifiable = true;
 colorValue.usesSlider = true;
 colorValue.min = 0.0f;
 colorValue.max = 255.0f;
 values.push_back(colorValue);
 return values;
}
References color, density, end, EntityStatsManager::FLOAT, GLESC::Render::Intensity< IntensityType >::getModifiable(), GLESC::isIterable_v, EntityStatsManager::Value::name, and EntityStatsManager::VEC3F.
Referenced by GLESC::ECS::FogComponent::setDebuggingValues().
getDensity()
float GLESC::Render::Fog::getDensity () const inline
Definition at line 33 of file Fog.h.
{
            return density.get();
        }
References density, and GLESC::Render::Intensity< IntensityType >::get().
getEnd()
float GLESC::Render::Fog::getEnd () const inline
Definition at line 38 of file Fog.h.
{
            return end;
        }
References end.
setColor()
void GLESC::Render::Fog::setColor (const ColorRgb & color) inline
Definition at line 25 of file Fog.h.
{
            this->color = color;
        }
References color.
setDensity()
void GLESC::Render::Fog::setDensity (float density) inline
Definition at line 21 of file Fog.h.
{
            this->density.set(density);
        }
References density.
setEnd()
void GLESC::Render::Fog::setEnd (float end) inline
Definition at line 29 of file Fog.h.
{
            this->end = end;
        }
References end.
toString()
std::string Fog::toString () const
Definition at line 50 of file Fog.cpp.
{
    std::string str = "Density: " + std::to_string(density.get()) + "\n";
    str += "Color: " + color.toString() + "\n";
    return str;
}
References color, density, GLESC::Render::Intensity< IntensityType >::get(), GLESC::isIterable_v, and GLESC::Render::ColorRgb::toString().
Referenced by GLESC::ECS::FogComponent::toString().
Member Data Documentation
color
GLESC::Render::ColorRgb GLESC::Render::Fog::color {255.f, 255.f, 255.f} private
Definition at line 57 of file Fog.h.
{255.f, 255.f, 255.f};
Referenced by getColor(), getDebuggingValues(), setColor(), and toString().
density
GLESC::Render::Intensity<float> GLESC::Render::Fog::density {1.0f} private
Definition at line 55 of file Fog.h.
{1.0f};
Referenced by getDebuggingValues(), getDensity(), setDensity(), and toString().
end
float GLESC::Render::Fog::end = 300.0f private
Definition at line 56 of file Fog.h.
Referenced by getDebuggingValues(), getEnd(), and setEnd().
The documentation for this class was generated from the following files:
Fog.h
Fog.cpp