GLESC: GLESC::Math::PolyhedronFace Class Reference
GLESC::Math::PolyhedronFace Class Reference
#include <PolyhedronFace.h>
Public Member Functions
PolyhedronFace (const PolyhedronFace &other)
Custom copy constructor.
PolyhedronFace (FaceIndices indicesParam, const Points &verticesParam)
~PolyhedronFace ()=default
const Point & getNormal () const
Returns the normal the face.
const Plane & getPlane () const
const std::vector< Point > & getPolyhedronVertices () const
const FaceIndices & getVertexIndices () const
bool intersects (const Line &line) const
Checks if the face intersects with a given line.
bool intersects (const Plane &plane) const
Checks if the face intersects with a given plane.
bool intersects (const PolyhedronFace &face) const
Checks if the current face intersects with the given face.
bool intersects (const Vec3F &point) const
Checks if the face intersects with a given point.
PolyhedronFace & operator= (const PolyhedronFace &other)=delete
Deleted assignment operator.
Private Attributes
FaceIndices indices
The indices of the vertices of the face. These indices are used to access the vertices of the polyhedron that contains this face.
Plane plane
The (infinite) plane that contains the face. The plane is defined by its normal vector and a distance from the origin.
const std::vector< Point > & polyhedronVertices
Const reference to the vertices of the polyhedron that contains this face.
Detailed Description
Definition at line 20 of file PolyhedronFace.h.
Constructor & Destructor Documentation
PolyhedronFace() [1/2]
PolyhedronFace::PolyhedronFace (FaceIndices indicesParam, const Points & verticesParam)
Definition at line 7 of file PolyhedronFace.cpp.
                                                                                    :
        indices(indicesParam), polyhedronVertices(verticesParam) {
    D_ASSERT_TRUE(polyhedronVertices.size() >= 3, "Polyhedron must have at least 3 vertices.");
    D_ASSERT_FALSE(polyhedronVertices.at(indices[0]).isCollinear({polyhedronVertices.at(indices[1]),
        polyhedronVertices.at(indices[2])}),
                  "Face must not have collinear vertices.");
    // Construct the plane that contains this face with the 3 points constructor
    plane = Plane(polyhedronVertices.at(0), polyhedronVertices.at(1), polyhedronVertices.at(2));
}
References D_ASSERT_FALSE, D_ASSERT_TRUE, indices, plane, and polyhedronVertices.
~PolyhedronFace()
GLESC::Math::PolyhedronFace::~PolyhedronFace () default
PolyhedronFace() [2/2]
GLESC::Math::PolyhedronFace::PolyhedronFace (const PolyhedronFace & other) inline
Custom copy constructor.
Creates a new PolyhedronFace that refers to the same set of vertices as the other face. This is necessary because the default copy constructor is deleted due to the presence of a reference member.
Parameters
other The PolyhedronFace to copy from.
Definition at line 35 of file PolyhedronFace.h.
            : polyhedronVertices(other.polyhedronVertices), indices(other.indices),
              plane(other.plane) {}
Member Function Documentation
getNormal()
const Point & GLESC::Math::PolyhedronFace::getNormal () const inline
Returns the normal the face.
Returns
The normal of the face
Definition at line 53 of file PolyhedronFace.h.
{ return plane.getNormal(); }
References GLESC::Math::Plane::getNormal(), and plane.
Referenced by intersects(), intersects(), and intersects().
getPlane()
const Plane & GLESC::Math::PolyhedronFace::getPlane () const inline
Get the plane that contains the face.
Returns
The plane that contains the face.
Definition at line 71 of file PolyhedronFace.h.
{ return plane; }
References plane.
getPolyhedronVertices()
const std::vector< Point > & GLESC::Math::PolyhedronFace::getPolyhedronVertices () const inline
Get the vertices of the polyhedron that contains this face.
Returns
The vertices of the polyhedron.
Definition at line 59 of file PolyhedronFace.h.
{ return polyhedronVertices; }
References polyhedronVertices.
getVertexIndices()
const FaceIndices & GLESC::Math::PolyhedronFace::getVertexIndices () const inline
Get the indices of the vertices of the face.
Returns
The indices of the vertices of the face.
Definition at line 65 of file PolyhedronFace.h.
{ return indices; }
References indices.
intersects() [1/4]
bool PolyhedronFace::intersects (const Line & line) const
Checks if the face intersects with a given line.
Parameters
line The line to check for intersection.
Returns
True if the face intersects with the line, false otherwise.
Definition at line 100 of file PolyhedronFace.cpp.
{
    D_ASSERT_FALSE(polyhedronVertices.empty(), "Polyhedron vertices must not be empty.");
    // Check if the line is parallel to the plane
    Distance dotProduct = getNormal().dot(line.getDirection());
    if (Math::eq(Math::abs(dotProduct),0)) {
        return false; // Line is parallel to the plane, no intersection
    }
    // Find the intersection point with the plane
    float t = -(getNormal().dot(line.getPoint() - polyhedronVertices.at(0)) + plane.getDistance() / dotProduct);
    Direction intersectionPoint = line.getPoint() + line.getDirection() * t;
    // Check if the intersection point is inside the face
    return intersects(intersectionPoint);
}
References GLESC::Math::abs(), D_ASSERT_FALSE, GLESC::Math::Vector< Type, N >::dot(), GLESC::Math::eq(), GLESC::Math::Plane::getDistance(), getNormal(), intersects(), GLESC::isIterable_v, plane, and polyhedronVertices.
intersects() [2/4]
bool PolyhedronFace::intersects (const Plane & plane) const
Checks if the face intersects with a given plane.
This function determines whether the face intersects with the plane by checking the position of the face's vertices relative to the plane. If some vertices are on one side of the plane and some on the other, it indicates that the face intersects the plane.
Parameters
plane The plane to check for intersection with the face.
Returns
True if the face intersects with the plane, false otherwise.
Definition at line 116 of file PolyhedronFace.cpp.
{
    D_ASSERT_FALSE(polyhedronVertices.empty(), "Polyhedron vertices must not be empty.");
    // Counters for vertices on each side of the plane and on the plane
    int positive = 0, negative = 0, onPlane = 0;
    for (auto index : indices) {
        // Calculate the signed distance from the vertex to the plane
        Distance distance = planeParam.distanceToPoint(polyhedronVertices.at(index));
        const Distance intersectsEpsilon = 0.0001;
        // Count vertices on each side of the plane and on the plane
        if(eq(distance, 0, intersectsEpsilon)) onPlane++;
        else if (distance > 0) positive++;
        else if (distance < 0) negative++;
        // Check for early exit conditions
        if (positive > 0 && negative > 0) return true; // Vertices on both sides
        if (onPlane > 0 && (positive > 0 || negative > 0)) return true; // An edge or vertex on the plane
    }
    // Check if any edge lies entirely on the plane
    if (onPlane >= 2) return true;
    // No intersection found
    return false;
}
References D_ASSERT_FALSE, GLESC::Math::eq(), indices, GLESC::isIterable_v, and polyhedronVertices.
intersects() [3/4]
bool PolyhedronFace::intersects (const PolyhedronFace & face) const
Checks if the current face intersects with the given face.
This function determines whether the current face intersects with the given face. It checks if any of the edges of the current face intersects with any of the edges of the given face.
This uses SAT (Separating Axis Theorem) to determine if the faces intersect.
Attention
This only works for convex polygons. Convex polygons: https://en.wikipedia.org/wiki/Convex_polygon Convex polyhedrons: https://en.wikipedia.org/wiki/Concave_polygon
Parameters
face The face to check for intersection.
Returns
True if the current face intersects with the given face, false otherwise.
Definition at line 19 of file PolyhedronFace.cpp.
{
    D_ASSERT_FALSE(polyhedronVertices.empty(), "Polyhedron vertices must not be empty.");
    // Get normals of both faces
    const Direction& thisNormal = getNormal();
    const Direction& otherNormal = face.getNormal();
    // Vector to store all axes to test
    std::vector<Direction> axes;
    // Add face normals to axes (to handle face-face parallel cases)
    axes.push_back(thisNormal);
    axes.push_back(otherNormal);
    // Function to add unique axes from edge cross products
    auto addUniqueAxis = [&axes](const Direction &edgeNormal) {
        // Normalize the edge normal
        Direction normalized = edgeNormal.normalize();
        // Check if this normal is unique
        for (const auto &axis : axes) {
            if (axis.isParallel(normalized)) {
                return; // Skip if parallel axis already exists
            }
        }
        axes.push_back(normalized); // Add unique axis
    };
    // Generate axes from edges of this face
    for (size_t i = 0; i < indices.size(); ++i) {
        size_t next = (i + 1) % indices.size();
        Direction edge = polyhedronVertices.at(next) - polyhedronVertices.at(i);
        addUniqueAxis(thisNormal.cross(edge));
    }
    // Generate axes from edges of other face
    for (size_t i = 0; i < face.indices.size(); ++i) {
        size_t next = (i + 1) % face.indices.size();
        Direction edge = face.polyhedronVertices.at(next) - face.polyhedronVertices.at(i);
        addUniqueAxis(otherNormal.cross(edge));
    }
    // Check for overlap on all axes
    for (const auto &axis : axes) {
        double thisMin = std::numeric_limits<double>::max();
        double thisMax = std::numeric_limits<double>::lowest();
        double otherMin = std::numeric_limits<double>::max();
        double otherMax = std::numeric_limits<double>::lowest();
        // Project vertices of both faces onto the axis
        for (auto index : indices) {
            double projection = polyhedronVertices.at(index).dot(axis);
            thisMin = min(thisMin, projection);
            thisMax = max(thisMax, projection);
        }
        for (auto index : face.indices) {
            double projection = face.polyhedronVertices.at(index).dot(axis);
            otherMin = min(otherMin, projection);
            otherMax = max(otherMax, projection);
        }
        // Check for separation on this axis
        if (thisMax < otherMin || otherMax < thisMin) {
            return false; // No overlap, faces do not intersect
        }
    }
    return true; // Overlap on all axes, faces intersect
}
References D_ASSERT_FALSE, getNormal(), indices, GLESC::isIterable_v, GLESC::Math::max(), GLESC::Math::min(), GLESC::Math::Vector< Type, N >::normalize(), polyhedronVertices, and GLESC::Math::Vector< Type, N >::size().
Referenced by intersects().
intersects() [4/4]
bool PolyhedronFace::intersects (const Vec3F & point) const
Checks if the face intersects with a given point.
Parameters
point The point to check for intersection.
Returns
True if the face intersects with the point, false otherwise.
Definition at line 88 of file PolyhedronFace.cpp.
{
    D_ASSERT_FALSE(polyhedronVertices.empty(), "Polyhedron vertices must not be empty.");
    for (size_t i = 0; i < polyhedronVertices.size(); ++i) {
        Direction edge = polyhedronVertices.at((i + 1) % polyhedronVertices.size()) - polyhedronVertices.at(i);
        Direction toPoint = point - polyhedronVertices.at(i);
        if (getNormal().cross(edge).dot(toPoint) < 0) {
            return false; // Point is outside this edge
        }
    }
    return true; // Point is inside all edges
}
References D_ASSERT_FALSE, getNormal(), GLESC::isIterable_v, and polyhedronVertices.
operator=()
PolyhedronFace & GLESC::Math::PolyhedronFace::operator= (const PolyhedronFace & other) delete
Deleted assignment operator.
Assigns this PolyhedronFace to refer to the same set of vertices as the other face. This operator is necessary because the default assignment operator is deleted due to the presence of a reference member. Note that this operator doesn't allow reassignment of the reference itself; it only ensures consistent copying of other assignable members.
Member Data Documentation
indices
FaceIndices GLESC::Math::PolyhedronFace::indices private
The indices of the vertices of the face. These indices are used to access the vertices of the polyhedron that contains this face.
Definition at line 122 of file PolyhedronFace.h.
Referenced by PolyhedronFace(), getVertexIndices(), intersects(), and intersects().
plane
Plane GLESC::Math::PolyhedronFace::plane private
The (infinite) plane that contains the face. The plane is defined by its normal vector and a distance from the origin.
Definition at line 127 of file PolyhedronFace.h.
Referenced by PolyhedronFace(), getNormal(), getPlane(), and intersects().
polyhedronVertices
const std::vector<Point>& GLESC::Math::PolyhedronFace::polyhedronVertices private
Const reference to the vertices of the polyhedron that contains this face.
Definition at line 131 of file PolyhedronFace.h.
Referenced by PolyhedronFace(), getPolyhedronVertices(), intersects(), intersects(), intersects(), and intersects().
The documentation for this class was generated from the following files:
PolyhedronFace.h
PolyhedronFace.cpp