GLESC: GLESC::Math::Polyhedron Class Reference
GLESC::Math::Polyhedron Class Reference
#include <Polyhedron.h>
Public Member Functions
Polyhedron ()=default
Construct a new Polyhedron object. Default constructor.
Polyhedron (Points vertices, const std::vector< FaceIndices > &faces)
Construct a new Polyhedron object.
void addFace (const FaceIndices &faceParam)
Add a face to the polyhedron. The face is defined by the indices of the vertices.
void addQuad (const QuadIndices &faceParam)
Add a quad to the polyhedron. The quad is defined by the indices of the vertices.
void addVertex (const Point &vertex)
Add a vertex to the polyhedron.
void clear ()
Clear the polyhedron. Erase all vertices and faces.
Point getCenter () const
Get the center of the polyhedron.
const std::vector< PolyhedronFace > & getFaces () const
Get the faces of the polyhedron.
const std::vector< Point > & getVertices () const
Get the vertices of the polyhedron.
std::vector< Point > & getVerticesMutable ()
Get the vertices of the polyhedron.
bool hasAnyVertexInside (const Polyhedron &other) const
Checks if the polyhedron has any vertex inside another polyhedron.
bool hasInside (const Point &point) const
Checks if a point is inside the polyhedron.
bool hasInside (const Polyhedron &polyhedron) const
Checks if the polyhedron has any vertex inside another polyhedron.
bool hasInside (const PolyhedronFace &face)
Checks if a face is inside the polyhedron.
bool intersects (const Line &line) const
Checks if the polyhedron intersects with a line.
bool intersects (const Plane &plane) const
Checks if the polyhedron intersects with a plane.
bool intersects (const Point &point) const
Checks if the polyhedron intersects with a point.
bool intersects (const Polyhedron &other) const
Checks if the polyhedron intersects with another polyhedron.
Polyhedron & operator= (const Polyhedron &other)
Assignment operator.
Private Member Functions
bool isOutOfBounds (const FaceIndices &face) const
Checks if the face indices are out of bounds with the current size of the vertices.
bool isOutOfBounds (const std::vector< FaceIndices > &faces) const
Checks if the list of face indices are out of bounds with the current size of the vertices.
Private Attributes
std::vector< PolyhedronFace > faces
std::vector< Vec3F > vertices
Detailed Description
Definition at line 16 of file Polyhedron.h.
Constructor & Destructor Documentation
Polyhedron() [1/2]
GLESC::Math::Polyhedron::Polyhedron () default
Construct a new Polyhedron object. Default constructor.
Polyhedron() [2/2]
Polyhedron::Polyhedron (Points vertices, const std::vector< FaceIndices > & faces)
Construct a new Polyhedron object.
Parameters
vertices The vertices of the polyhedron.
faces The faces of the polyhedron.
Definition at line 16 of file Polyhedron.cpp.
                                                                           :
    vertices(std::move(vertices)) {
    for (const auto& face : faces) {
        addFace(face);
    }
}
References addFace(), faces, and GLESC::isIterable_v.
Member Function Documentation
addFace()
void Polyhedron::addFace (const FaceIndices & faceParam)
Add a face to the polyhedron. The face is defined by the indices of the vertices.
Parameters
faceParam The face to add.
Definition at line 33 of file Polyhedron.cpp.
{
    // Check for repeated vertices
    for (size_t i = 0; i < faceParam.size(); ++i) {
        for (size_t j = i + 1; j < faceParam.size(); ++j) {
            D_ASSERT_FALSE(faceParam[i] == faceParam[j], "Face must not have repeated vertices.");
        }
    }
    // Check for out of bounds indices
    D_ASSERT_FALSE(this->isOutOfBounds(faceParam), "Face must not have out of bounds indices.");
    PolyhedronFace face(faceParam, vertices);
    faces.push_back(face);
}
References D_ASSERT_FALSE, faces, GLESC::isIterable_v, isOutOfBounds(), and vertices.
Referenced by Polyhedron(), and addQuad().
addQuad()
void Polyhedron::addQuad (const QuadIndices & faceParam)
Add a quad to the polyhedron. The quad is defined by the indices of the vertices.
It will create two triangles from the quad.
Parameters
faceParam The quad to add.
Definition at line 47 of file Polyhedron.cpp.
{
    FaceIndices face1;
    FaceIndices face2;
    // First triangle
    face1[0] = faceParam[0];
    face1[1] = faceParam[1];
    face1[2] = faceParam[2];
    // Second triangle
    face2[0] = faceParam[0];
    face2[1] = faceParam[2];
    face2[2] = faceParam[3];
    addFace(face1);
    addFace(face2);
}
References addFace(), and GLESC::isIterable_v.
addVertex()
void Polyhedron::addVertex (const Point & vertex)
Add a vertex to the polyhedron.
Parameters
vertex The vertex to add.
Definition at line 23 of file Polyhedron.cpp.
{
    vertices.push_back(vertex);
}
References GLESC::isIterable_v, and vertices.
Referenced by GLESC::PolyhedronFactory::Regular::icos(), GLESC::PolyhedronFactory::Regular::octa(), and GLESC::PolyhedronFactory::Common::rectangularCuboid().
clear()
void Polyhedron::clear ()
Clear the polyhedron. Erase all vertices and faces.
Definition at line 27 of file Polyhedron.cpp.
                       {
    vertices = std::vector<Point>();
    faces = std::vector<PolyhedronFace>();
}
References faces, and vertices.
getCenter()
Point Polyhedron::getCenter () const
Get the center of the polyhedron.
Returns
Point The center of the polyhedron.
Definition at line 65 of file Polyhedron.cpp.
{
    Point center;
    for (const auto& vertex : vertices) {
        center += vertex;
    }
    center /= static_cast<Distance>(vertices.size());
    return center;
}
References GLESC::isIterable_v, and vertices.
getFaces()
const std::vector< PolyhedronFace > & Polyhedron::getFaces () const
Get the faces of the polyhedron.
Returns
const std::vector<PolyhedronFace>& The faces of the polyhedron.
Definition at line 74 of file Polyhedron.cpp.
{
    return faces;
}
References faces.
getVertices()
const std::vector< Point > & Polyhedron::getVertices () const
Get the vertices of the polyhedron.
Returns
const std::vector<Point>& The vertices of the polyhedron.
Definition at line 79 of file Polyhedron.cpp.
{
    return vertices;
}
References vertices.
getVerticesMutable()
std::vector< Point > & Polyhedron::getVerticesMutable ()
Get the vertices of the polyhedron.
Returns
std::vector<Point>& The vertices of the polyhedron.
Definition at line 83 of file Polyhedron.cpp.
{
    return vertices;
}
References vertices.
hasAnyVertexInside()
bool Polyhedron::hasAnyVertexInside (const Polyhedron & other) const
Checks if the polyhedron has any vertex inside another polyhedron.
Checks if any vertex of the polyhedron is inside the other polyhedron.
Parameters
other The polyhedron to check for vertices inside.
Returns
True if the polyhedron has any vertex inside the other polyhedron, false otherwise.
Definition at line 112 of file Polyhedron.cpp.
{
    for (const auto& vertex : polyhedron.getVertices()) {
        if (hasInside(vertex)) {
            return true;
        }
    }
    return false;
}
References hasInside(), and GLESC::isIterable_v.
hasInside() [1/3]
bool Polyhedron::hasInside (const Point & point) const
Checks if a point is inside the polyhedron.
Parameters
point The point to check.
Returns
True if the point is inside the polyhedron, false otherwise.
Definition at line 98 of file Polyhedron.cpp.
{
    (void)point;
    D_ASSERT_TRUE(false, "Not implemented");
}
References D_ASSERT_TRUE, and GLESC::isIterable_v.
Referenced by hasAnyVertexInside(), hasInside(), and hasInside().
hasInside() [2/3]
bool Polyhedron::hasInside (const Polyhedron & polyhedron) const
Checks if the polyhedron has any vertex inside another polyhedron.
Checks if any vertex of the polyhedron is inside the other polyhedron.
Parameters
polyhedron The polyhedron to check for vertices inside.
Returns
True if the polyhedron has any vertex inside the other polyhedron, false otherwise.
Definition at line 121 of file Polyhedron.cpp.
{
    for (const auto& vertex : polyhedron.getVertices()) {
        if (!hasInside(vertex)) {
            return false;
        }
    }
    return true;
}
References hasInside(), and GLESC::isIterable_v.
hasInside() [3/3]
bool Polyhedron::hasInside (const PolyhedronFace & face)
Checks if a face is inside the polyhedron.
Parameters
face The face to check.
Returns
True if the face is inside the polyhedron, false otherwise.
Definition at line 103 of file Polyhedron.cpp.
{
    for (const auto& vertex : face.getPolyhedronVertices()) {
        if (!hasInside(vertex)) {
            return false;
        }
    }
    return true;
}
References hasInside(), and GLESC::isIterable_v.
intersects() [1/4]
bool Polyhedron::intersects (const Line & line) const
Checks if the polyhedron intersects with a line.
Parameters
line The line to check for intersection.
Returns
True if the polyhedron intersects with the line, false otherwise.
Definition at line 130 of file Polyhedron.cpp.
{
    for (const auto& face : faces) {
        if (face.intersects(line)) {
            return true;
        }
    }
    return false;
}
References faces, and GLESC::isIterable_v.
intersects() [2/4]
bool Polyhedron::intersects (const Plane & plane) const
Checks if the polyhedron intersects with a plane.
Parameters
plane The plane to check for intersection.
Returns
True if the polyhedron intersects with the plane, false otherwise.
Definition at line 148 of file Polyhedron.cpp.
{
    for (const auto& face : faces) {
        if (face.intersects(plane)) {
            return true;
        }
    }
    return false;
}
References faces, and GLESC::isIterable_v.
intersects() [3/4]
bool Polyhedron::intersects (const Point & point) const
Checks if the polyhedron intersects with a point.
Parameters
point The point to check for intersection.
Returns
True if the polyhedron intersects with the point, false otherwise.
Definition at line 139 of file Polyhedron.cpp.
{
    for (const auto& face : faces) {
        if (face.intersects(point)) {
            return true;
        }
    }
    return false;
}
References faces, and GLESC::isIterable_v.
intersects() [4/4]
bool Polyhedron::intersects (const Polyhedron & other) const
Checks if the polyhedron intersects with another polyhedron.
Uses SAT but for each face of the polyhedron. Iterates through all faces of the polyhedron and applies the SAT algorithm to check for intersection for each face.
Parameters
other The polyhedron to check for intersection.
Returns
True if the polyhedron intersects with the other polyhedron, false otherwise.
Definition at line 87 of file Polyhedron.cpp.
{
    for (const auto& face : faces) {
        for (const auto& otherFace : other.getFaces()) {
            if (face.intersects(otherFace)) {
                return true;
            }
        }
    }
    return false;
}
References faces, and GLESC::isIterable_v.
isOutOfBounds() [1/2]
bool Polyhedron::isOutOfBounds (const FaceIndices & face) const private
Checks if the face indices are out of bounds with the current size of the vertices.
is used to check if the face is valid when adding it to the polyhedron.
Parameters
face The face indices to check.
Returns
True if the face indices are out of bounds, false otherwise.
Definition at line 168 of file Polyhedron.cpp.
{
    for (const auto& index : face) {
        if (index >= vertices.size()) {
            return true;
        }
    }
    return false;
}
References GLESC::isIterable_v, and vertices.
isOutOfBounds() [2/2]
bool Polyhedron::isOutOfBounds (const std::vector< FaceIndices > & faces) const private
Checks if the list of face indices are out of bounds with the current size of the vertices.
is used to check if the faces are valid when adding them to the polyhedron.
Parameters
faces The face indices to check.
Returns
True if the face indices are out of bounds, false otherwise.
Definition at line 159 of file Polyhedron.cpp.
{
    for (const auto& face : faces) {
        if (isOutOfBounds(face)) {
            return true;
        }
    }
    return false;
}
References faces, GLESC::isIterable_v, and isOutOfBounds().
Referenced by addFace(), and isOutOfBounds().
operator=()
Polyhedron & GLESC::Math::Polyhedron::operator= (const Polyhedron & other) inline
Assignment operator.
It needs to be defined like this because the default doesnt work because PolyhedronFace contains a reference to the vertices of the polyhedron.
Parameters
other The polyhedron to assign.
Returns
Polyhedron& The assigned polyhedron.
Definition at line 145 of file Polyhedron.h.
{
            vertices = other.vertices;
            return *this;
        }
References GLESC::isIterable_v, and vertices.
Member Data Documentation
faces
std::vector<PolyhedronFace> GLESC::Math::Polyhedron::faces private
Definition at line 166 of file Polyhedron.h.
Referenced by Polyhedron(), addFace(), clear(), getFaces(), intersects(), intersects(), intersects(), intersects(), and isOutOfBounds().
vertices
std::vector<Vec3F> GLESC::Math::Polyhedron::vertices private
Definition at line 165 of file Polyhedron.h.
Referenced by addFace(), addVertex(), clear(), getCenter(), getVertices(), getVerticesMutable(), isOutOfBounds(), and operator=().
The documentation for this class was generated from the following files:
Polyhedron.h
Polyhedron.cpp