GLESC: GLESC::WindowManager Class Reference
GLESC::WindowManager Class Reference
#include <WindowManager.h>
Public Member Functions
WindowManager ()
void destroyWindow ()
Destroy window and release resources.
Vec2I getPosition ()
Get the position of the window.
WindowDimensions getSize () const
Get the width and height of the window.
SDL_Window & getWindow ()
Get the Window object.
Vec2UI getWindowCenter () const
Get the center of the window.
bool isBorderlessWindow ()
Gets whether the window is borderless or not.
bool isFullscreen ()
Gets whether the windowManager is fullscreen or not.
bool isFullscreenBorderless ()
Gets whether the window is fullscreen borderless or not.
bool isResizable ()
Gets whether the window is resizable or not.
void setBorderlessWindow (bool isBorderless)
Sets the window borderless, meaning no title bar with close button.
void setFullscreen (bool isFullScreen)
Turn fullscreen on or off This will change the flags of the windowManager object.
void setFullscreenBorderless (bool isFullScreen)
Sets the window fullscreen borderless or "fake fullscreen".
void setIcon (const std::string &iconFile)
Set the window icon. Updates the icon displayed in the window's title bar.
void setPosition (unsigned int windowX, unsigned int windowY)
Set the position of the window. Changes the location of the window on the screen.
void setResizable (bool isResizable)
Sets the window resizable. If enabled, the window can be resized by the user. If disabled, the window cannot be resized, when trying to resize it, nothing will happen.
void setSize (uint16_t windowWidth, uint16_t windowHeight)
Callback function when window size is modified This will change the viewport with the new resolution.
void setWindowTitle (const std::string &title)
Set the window title. Changes the title of the window.
Private Member Functions
SDL_Window * createWindow (const char *title)
Initialize the windowManager with its title, setting its flags Checks if there is any error while doing it.
Static Private Member Functions
static uint32_t getRaisedFlags ()
Initialize SDL_Window flags.
static void initSDL ()
Initialize SDL, checks if there is any error while doing it Must be called before creating windowManager.
Private Attributes
SDL_Window * window
The SDL window struct pointer.
Detailed Description
Definition at line 29 of file WindowManager.h.
Constructor & Destructor Documentation
WindowManager()
WindowManager::WindowManager ()
Definition at line 20 of file WindowManager.cpp.
{
    initSDL();
    getGAPI().preWindowCreationInit();
    window = createWindow(GLESC_WINDOW_TITLE);
    auto x = GLESC_WINDOW_X;
    auto y = GLESC_WINDOW_Y;
    auto width = static_cast<unsigned short>(GLESC_WINDOW_WIDTH);
    auto height = static_cast<unsigned short>(GLESC_WINDOW_HEIGHT);
    auto isFullscreen = GLESC_WINDOW_FULLSCREEN;
    setFullscreen(isFullscreen);
    setSize(width, height);
    setPosition(x, y);
    getGAPI().createContext(*window);
    getGAPI().postWindowCreationInit();
    // Enable mouse relative mode
    // This will make the mouse cursor invisible and locked in the middle of the screen
    //setMouseRelative(true);
    setIcon("images/icons/TinyLogo.bmp");
}
References createWindow(), getGAPI(), GLESC_WINDOW_FULLSCREEN, GLESC_WINDOW_HEIGHT, GLESC_WINDOW_TITLE, GLESC_WINDOW_WIDTH, GLESC_WINDOW_X, GLESC_WINDOW_Y, initSDL(), isFullscreen(), setFullscreen(), setIcon(), setPosition(), setSize(), and window.
Member Function Documentation
createWindow()
SDL_Window * WindowManager::createWindow (const char * title) private
Initialize the windowManager with its title, setting its flags Checks if there is any error while doing it.
Definition at line 173 of file WindowManager.cpp.
{
    uint32_t flags = getRaisedFlags();
    SDL_Window* tempWindow = SDL_CreateWindow(title, GLESC_WINDOW_X, GLESC_WINDOW_Y,
                                              GLESC_WINDOW_WIDTH, GLESC_WINDOW_HEIGHT, flags);
    postSDLCall;
    D_ASSERT_NOT_NULLPTR(tempWindow, "Unable to create windowManager: " + std::string(SDL_GetError()));
    Logger::get().success("Window created!");
    SDLCall(SDL_SetWindowMinimumSize(tempWindow, windowMinWidth, windowMinHeight));
    return tempWindow;
}
References D_ASSERT_NOT_NULLPTR, GLESC::Logger::get(), getRaisedFlags(), GLESC_WINDOW_HEIGHT, GLESC_WINDOW_WIDTH, GLESC_WINDOW_X, GLESC_WINDOW_Y, GLESC::isIterable_v, postSDLCall, SDLCall, GLESC::Logger::success(), windowMinHeight, and windowMinWidth.
Referenced by WindowManager().
destroyWindow()
void WindowManager::destroyWindow ()
Destroy window and release resources.
Definition at line 185 of file WindowManager.cpp.
{
    getGAPI().deleteContext();
    SDLCall(SDL_DestroyWindow(window));
    SDLCall(SDL_Quit());
    Logger::get().success("Window destroyed!");
}
References GLESC::Logger::get(), getGAPI(), GLESC::isIterable_v, SDLCall, GLESC::Logger::success(), and window.
getPosition()
Vec2I WindowManager::getPosition ()
Get the position of the window.
Returns
Vec2I -> x: position on X axis, y: position on Y axis
Definition at line 99 of file WindowManager.cpp.
{
    int x, y;
    SDLCall(SDL_GetWindowPosition(window, &x, &y));
    return Vec2I{x, y};
}
References GLESC::isIterable_v, SDLCall, and window.
getRaisedFlags()
uint32_t WindowManager::getRaisedFlags () static private
Initialize SDL_Window flags.
Returns
int the flags
Definition at line 140 of file WindowManager.cpp.
{
    // Flags that are needed to be passed to the windowManager * to configure it.
    // To add more flags we need to use the binary OR ( | )
    // More info: https://wiki.libsdl.org/SDL_WindowFlags
    uint32_t flags = 0;
#if GLESC_RENDER_API == OpenGLAPI
    // Flag to allow SDL windowManager work with OpenGL
    flags |= SDL_WINDOW_OPENGL;
#elif GLESC_RENDER_API == VulkanAPI
    flags |= SDL_WINDOW_VULKAN;
#endif
    // Window has no borders
    // flags |= SDL_WINDOW_BORDERLESS;
    // Window grabs input focus
    // flags |= SDL_WINDOW_INPUT_GRABBED;
    // Window enables High pixel density if supported by monitor
    flags |= SDL_WINDOW_ALLOW_HIGHDPI;
    // Window is resizable
    flags |= SDL_WINDOW_RESIZABLE;
    return flags;
}
References GLESC::isIterable_v.
Referenced by createWindow().
getSize()
GLESC::WindowDimensions WindowManager::getSize () const
Get the width and height of the window.
Returns
WindowDimensions -> width: width of the window, height: height of the window
Definition at line 122 of file WindowManager.cpp.
{
    WindowDimensions dimensions{};
    Uint32 flags = SDL_GetWindowFlags(window);
    if (flags & (SDL_WINDOW_MINIMIZED | SDL_WINDOW_HIDDEN)) {
        return dimensions;
    }
    if (window == nullptr) {
        return dimensions;
    }
    SDLCall(SDL_GetWindowSize(window, &dimensions.width, &dimensions.height));
    return dimensions;
}
References GLESC::isIterable_v, SDLCall, and window.
Referenced by GLESC::Render::Renderer::getViewportSize(), getWindowCenter(), GLESC::EngineCamera::setupCamera(), and GLESC::ECS::CameraSystem::update().
getWindow()
SDL_Window & WindowManager::getWindow ()
Get the Window object.
Returns
SDL_Window* the windowManager object
Definition at line 118 of file WindowManager.cpp.
{
    return *window;
}
References window.
Referenced by GLESC::Render::Renderer::swapBuffers().
getWindowCenter()
Vec2UI WindowManager::getWindowCenter () const
Get the center of the window.
Definition at line 135 of file WindowManager.cpp.
{
    auto dimensions = getSize();
    return Vec2UI{dimensions.width / 2, dimensions.height / 2};
}
References getSize(), and GLESC::isIterable_v.
initSDL()
void WindowManager::initSDL () static private
Initialize SDL, checks if there is any error while doing it Must be called before creating windowManager.
Definition at line 165 of file WindowManager.cpp.
{
    int result = SDL_Init(SDL_INIT_EVERYTHING);
    postSDLCall;
    D_ASSERT_EQUAL(result, 0, "Unable to initialize SDL: " + std::string(SDL_GetError()));
    Logger::get().success("SDL Initialized!");
}
References D_ASSERT_EQUAL, GLESC::Logger::get(), GLESC::isIterable_v, postSDLCall, and GLESC::Logger::success().
Referenced by WindowManager().
isBorderlessWindow()
bool WindowManager::isBorderlessWindow ()
Gets whether the window is borderless or not.
Returns
true if window is borderless, false otherwise
Definition at line 75 of file WindowManager.cpp.
{
    auto flags = SDL_GetWindowFlags(window);
    return (flags & SDL_WINDOW_BORDERLESS) != 0;
}
References GLESC::isIterable_v, and window.
isFullscreen()
bool WindowManager::isFullscreen ()
Gets whether the windowManager is fullscreen or not.
Returns
true if windowManager is fullscreen, false otherwise
Definition at line 89 of file WindowManager.cpp.
{
    auto flags = SDL_GetWindowFlags(window);
    return (flags & SDL_WINDOW_FULLSCREEN) != 0;
}
References GLESC::isIterable_v, and window.
Referenced by WindowManager().
isFullscreenBorderless()
bool WindowManager::isFullscreenBorderless ()
Gets whether the window is fullscreen borderless or not.
Returns
true if window is fullscreen borderless, false otherwise
Definition at line 65 of file WindowManager.cpp.
{
    auto flags = SDL_GetWindowFlags(window);
    return (flags & SDL_WINDOW_FULLSCREEN_DESKTOP) != 0;
}
References GLESC::isIterable_v, and window.
isResizable()
bool WindowManager::isResizable ()
Gets whether the window is resizable or not.
Returns
true if window is resizable, false otherwise
Definition at line 84 of file WindowManager.cpp.
{
    auto flags = SDL_GetWindowFlags(window);
    return (flags & SDL_WINDOW_RESIZABLE) != 0;
}
References GLESC::isIterable_v, and window.
Referenced by setResizable(), and setSize().
setBorderlessWindow()
void WindowManager::setBorderlessWindow (bool isBorderless)
Sets the window borderless, meaning no title bar with close button.
Parameters
isBorderless true to enable, false to disable
Definition at line 71 of file WindowManager.cpp.
{
    SDLCall(SDL_SetWindowBordered(window, isBorderless ? SDL_FALSE : SDL_TRUE));
}
References GLESC::isIterable_v, SDLCall, and window.
setFullscreen()
void WindowManager::setFullscreen (bool isFullScreen)
Turn fullscreen on or off This will change the flags of the windowManager object.
Definition at line 55 of file WindowManager.cpp.
{
    Uint32 flag = isFullScreen ? SDL_WINDOW_FULLSCREEN : 0;
    SDLCall(SDL_SetWindowFullscreen(window, flag));
}
References GLESC::isIterable_v, SDLCall, and window.
Referenced by WindowManager().
setFullscreenBorderless()
void WindowManager::setFullscreenBorderless (bool isFullScreen)
Sets the window fullscreen borderless or "fake fullscreen".
This will make the window fullscreen but also facilitates changing to different apps and windows. This won't change the resolution of the screen, like true fullscreen. But also is less efficient than true fullscreen, costing more resources.
Parameters
isFullScreen true to enable, false to disable
Definition at line 60 of file WindowManager.cpp.
{
    Uint32 flag = isFullScreen ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0;
    SDLCall(SDL_SetWindowFullscreen(window, flag));
}
References GLESC::isIterable_v, SDLCall, and window.
setIcon()
void WindowManager::setIcon (const std::string & iconFile)
Set the window icon. Updates the icon displayed in the window's title bar.
Parameters
iconFile Path to the icon file.
Definition at line 105 of file WindowManager.cpp.
{
    std::string iconPath = BinPath::getExecutableDirectory() + std::string(ASSETS_PATH) + "/" + iconFile;
    Logger::get().info("Loading icon: " + iconPath);
    SDL_Surface* iconSurface = SDL_LoadBMP(iconPath.c_str());
    D_ASSERT_NOT_NULLPTR(iconSurface, "Unable to load icon with path: " + iconPath + " SDL_Error: " +
                         std::string(SDL_GetError()));
    SDLCall(SDL_SetWindowIcon(window, iconSurface));
    SDLCall(SDL_FreeSurface(iconSurface));
}
References D_ASSERT_NOT_NULLPTR, GLESC::Logger::get(), BinPath::getExecutableDirectory(), GLESC::Logger::info(), GLESC::isIterable_v, SDLCall, and window.
Referenced by WindowManager().
setPosition()
void WindowManager::setPosition (unsigned int windowX, unsigned int windowY)
Set the position of the window. Changes the location of the window on the screen.
Parameters
windowX New X position.
windowY New Y position.
Definition at line 95 of file WindowManager.cpp.
{
    SDLCall(SDL_SetWindowPosition(window, static_cast<int>(windowX), static_cast<int>(windowY)));
}
References GLESC::isIterable_v, SDLCall, and window.
Referenced by WindowManager().
setResizable()
void WindowManager::setResizable (bool isResizable)
Sets the window resizable. If enabled, the window can be resized by the user. If disabled, the window cannot be resized, when trying to resize it, nothing will happen.
Parameters
isResizable true to enable, false to disable
Definition at line 80 of file WindowManager.cpp.
{
    SDLCall(SDL_SetWindowResizable(window, static_cast<SDL_bool>(isResizable)));
}
References GLESC::isIterable_v, isResizable(), SDLCall, and window.
setSize()
void WindowManager::setSize (uint16_t windowWidth, uint16_t windowHeight)
Callback function when window size is modified This will change the viewport with the new resolution.
Definition at line 43 of file WindowManager.cpp.
{
    if (isResizable()) {
        SDLCall(SDL_SetWindowSize(window, windowWidth, windowHeight));
        getGAPI().setViewport(0, 0, windowWidth, windowHeight);
    }
}
References getGAPI(), GLESC::isIterable_v, isResizable(), SDLCall, and window.
Referenced by WindowManager(), and GLESC::Input::InputManager::handleWindowEvent().
setWindowTitle()
void WindowManager::setWindowTitle (const std::string & title)
Set the window title. Changes the title of the window.
Parameters
title New title.
Definition at line 50 of file WindowManager.cpp.
{
    SDLCall(SDL_SetWindowTitle(window, title.c_str()));
}
References GLESC::isIterable_v, SDLCall, and window.
Referenced by GLESC::Scene::SceneManager::switchScene().
Member Data Documentation
window
SDL_Window* GLESC::WindowManager::window private
The SDL window struct pointer.
Definition at line 178 of file WindowManager.h.
Referenced by WindowManager(), destroyWindow(), getPosition(), getSize(), getWindow(), isBorderlessWindow(), isFullscreen(), isFullscreenBorderless(), isResizable(), setBorderlessWindow(), setFullscreen(), setFullscreenBorderless(), setIcon(), setPosition(), setResizable(), setSize(), and setWindowTitle().
The documentation for this class was generated from the following files:
WindowManager.h
WindowManager.cpp