GLESC: GLESC::GAPI::VertexArray Class Reference
GLESC::GAPI::VertexArray Class Reference
#include <VertexArray.h>
Public Member Functions
VertexArray ()
~VertexArray ()
void addBuffer (const VertexBuffer &vb, const VertexBufferLayout &layout)
Add a vertex buffer to the vertex array.
void bind () const
void destroy ()
UInt getRendererID () const
void unbind () const
Private Member Functions
void destroyOnce ()
Private Attributes
bool objectAlive = true
UInt vertexArrayID {0}
Detailed Description
Definition at line 16 of file VertexArray.h.
Constructor & Destructor Documentation
VertexArray()
VertexArray::VertexArray ()
Definition at line 14 of file VertexArray.cpp.
{
    getGAPI().genVertexArray(vertexArrayID);
}
References getGAPI(), and vertexArrayID.
~VertexArray()
VertexArray::~VertexArray ()
Definition at line 18 of file VertexArray.cpp.
{
    destroyOnce();
}
References destroyOnce().
Member Function Documentation
addBuffer()
void VertexArray::addBuffer (const VertexBuffer & vb, const VertexBufferLayout & layout)
Add a vertex buffer to the vertex array.
The vertex buffer and the layout are moved, so they will be invalid after this call
Parameters
vb The vertex buffer to add
layout The layout of the vertex buffer
Definition at line 35 of file VertexArray.cpp.
{
    auto const &elements = layout.getElements();
    auto const &stride = layout.getStride();
    UInt offset = 0;
    this->bind();
    vb.bind();
    for (size_t i = 0; i < elements.size(); ++i) {
        auto const &element = elements[i];
        auto const typeCount = static_cast<UInt>(getTypeCount(element.type));
        auto const type = getTypePrimitiveType(element.type);
        auto const typeSize = static_cast<UInt>(getTypeSize(type));
        // Enable the vertex attribute array
        getGAPI().enableVertexData(static_cast<UInt>(i));
        // Set up the vertex attribute pointers
        getGAPI().createVertexData(static_cast<UInt>(i), typeCount, type, element.normalized, stride, offset);
        // Calculate the offset for the next attribute
        offset += typeCount * typeSize;
    }
}
References bind(), GLESC::GAPI::VertexBuffer::bind(), GLESC::GAPI::VertexBufferLayout::getElements(), getGAPI(), GLESC::GAPI::VertexBufferLayout::getStride(), and GLESC::isIterable_v.
bind()
void VertexArray::bind () const
Definition at line 26 of file VertexArray.cpp.
{
    getGAPI().bindVertexArray(vertexArrayID);
}
References getGAPI(), and vertexArrayID.
Referenced by addBuffer(), and GLESC::Render::Renderer::renderMesh().
destroy()
void VertexArray::destroy ()
Definition at line 22 of file VertexArray.cpp.
{
    destroyOnce();
}
References destroyOnce().
destroyOnce()
void VertexArray::destroyOnce () private
Definition at line 59 of file VertexArray.cpp.
{
    if (objectAlive) {
        getGAPI().deleteVertexArray(vertexArrayID);
        objectAlive = false;
    }
}
References getGAPI(), objectAlive, and vertexArrayID.
Referenced by ~VertexArray(), and destroy().
getRendererID()
UInt GLESC::GAPI::VertexArray::getRendererID () const inline
Definition at line 22 of file VertexArray.h.
{ return vertexArrayID; }
References vertexArrayID.
unbind()
void VertexArray::unbind () const
Definition at line 30 of file VertexArray.cpp.
{
    getGAPI().unbindVertexArray();
}
References getGAPI().
Member Data Documentation
objectAlive
bool GLESC::GAPI::VertexArray::objectAlive = true private
Definition at line 41 of file VertexArray.h.
Referenced by destroyOnce().
vertexArrayID
UInt GLESC::GAPI::VertexArray::vertexArrayID {0} private
Definition at line 42 of file VertexArray.h.
{0};
Referenced by VertexArray(), bind(), destroyOnce(), and getRendererID().
The documentation for this class was generated from the following files:
VertexArray.h
VertexArray.cpp