GLESC: GLESC::Transform::Transformer Class Reference
GLESC::Transform::Transformer Class Reference
Class that contains functions for transforming meshes and bounding volumes.
#include <Transform.h>
Static Public Member Functions
static Position clipToNDC (const HomogeneousPosition &clipPos)
Transforms the clip position to normalized device coordinates.
static Rotation lookAt (const Position &from, const Position &to, const Math::Direction &up)
static Position NDCToViewport (const Position &clipPos, float vpWidth, float vpHeight)
Transforms the normalized device coordinates to viewport coordinates.
static void rotateMesh (Render::ColorMesh &mesh, const Rotation &rotationDegrees)
Rotates a mesh by a given rotation.
static Math::BoundingVolume transformBoundingVolume (const Math::BoundingVolume &boundingVolume, const Render::Model &matrix)
Transforms a bounding volume by a given matrix matrix.
static Math::BoundingVolume transformBoundingVolume (const Math::BoundingVolume &boundingVolume, const Transform &transform)
Transforms a bounding volume by a given transform.
static void transformMesh (Render::ColorMesh &mesh, const Transform &transform)
Scales a mesh by a given scale.
static Position transformVector (const Position &position, const Render::Model &matrix)
Transforms a position by a given matrix.
static void translateMesh (Render::ColorMesh &mesh, const Position &translation)
Translates a mesh by a given position.
static Position worldToViewport (const Position &worldPos, const Render::VP &viewProj, float vpWidth, float vpHeight)
Transforms the world position to viewport coordinates.
Static Private Member Functions
static void transformMesh (Render::ColorMesh &mesh, const Mat4F &matrix)
Detailed Description
Class that contains functions for transforming meshes and bounding volumes.
This allows transforming all the vertices or points of a mesh or bounding volume by a given transform. Iterating over all the elements and transforming them.
Definition at line 351 of file Transform.h.
Member Function Documentation
clipToNDC()
Position Transformer::clipToNDC (const HomogeneousPosition & clipPos) static
Transforms the clip position to normalized device coordinates.
This is done by just dehomogenizing the clip position.
Parameters
clipPos The clip position to transform.
Returns
The normalized device coordinates.
Definition at line 131 of file Transform.cpp.
{
    return clipPos.dehomogenize();
}
References GLESC::Math::Vector< Type, N >::dehomogenize(), and GLESC::isIterable_v.
Referenced by worldToViewport().
lookAt()
Rotation Transformer::lookAt (const Position & from, const Position & to, const Math::Direction & up) static
Definition at line 103 of file Transform.cpp.
{
    Math::Direction forward = (to - from).normalize();
    return forward.vectorToEulerRotation(up).toDegrees();
}
References GLESC::isIterable_v, GLESC::Math::Vector< Type, N >::toDegrees(), and GLESC::Math::Vector< Type, N >::vectorToEulerRotation().
NDCToViewport()
Position Transformer::NDCToViewport (const Position & clipPos, float vpWidth, float vpHeight) static
Transforms the normalized device coordinates to viewport coordinates.
This is done by just scaling the clip position by the viewport width and height.
Parameters
clipPos The normalized device coordinates to transform.
vpWidth The viewport width.
vpHeight The viewport height.
Returns
The viewport coordinates.
Definition at line 136 of file Transform.cpp.
{
    // Map NDC to screen coordinates for x and y
    float screenX = (ndcPos.getX() + 1.0f) * vpWidth / 2.0f;
    float screenY = (1.0f - ndcPos.getY()) * vpHeight / 2.0f;
    float screenZ = (1.0f - ndcPos.getZ()) / 2;
    return {screenX, screenY, screenZ};
}
References GLESC::isIterable_v.
Referenced by worldToViewport().
rotateMesh()
void Transformer::rotateMesh (Render::ColorMesh & mesh, const Rotation & rotationDegrees) static
Rotates a mesh by a given rotation.
This function will rotate all the vertices of the mesh by the given rotation, iterating over all of them and applying the rotation.
Parameters
mesh The mesh to rotate.
rotationDegrees The rotation to apply.
Definition at line 90 of file Transform.cpp.
{
    const Rotation rotation = rotationDegrees.toRads();
    for (auto& vertex : mesh.getModifiableVertices()) {
        vertex.getPosition().rotate(rotation);
    }
}
References GLESC::Render::Mesh< VertexT >::getModifiableVertices(), GLESC::isIterable_v, GLESC::Math::Vector< Type, N >::rotate(), and GLESC::Math::Vector< Type, N >::toRads().
transformBoundingVolume() [1/2]
GLESC::Math::BoundingVolume Transformer::transformBoundingVolume (const Math::BoundingVolume & boundingVolume, const Render::Model & matrix) static
Transforms a bounding volume by a given matrix matrix.
This function will transform all the points of the bounding volume by the given matrix, iterating over all of them and applying the matrix.
Parameters
boundingVolume The bounding volume to transform.
matrix The model matrix to apply.
Returns
The transformed bounding volume.
Definition at line 108 of file Transform.cpp.
{
    return {
        transformVector(boundingVolume.getVolume().min, matrix),
        transformVector(boundingVolume.getVolume().max, matrix)
    };
}
References GLESC::Math::BoundingVolume::getVolume(), GLESC::Math::BoundingVolume::AABB::max, GLESC::Math::BoundingVolume::AABB::min, and transformVector().
transformBoundingVolume() [2/2]
GLESC::Math::BoundingVolume Transformer::transformBoundingVolume (const Math::BoundingVolume & boundingVolume, const Transform & transform) static
Transforms a bounding volume by a given transform.
This function will transform all the points of the bounding volume by the given transform, iterating over all of them and applying the transform.
Parameters
boundingVolume The bounding volume to transform.
transform The transform to apply.
Returns
The transformed bounding volume.
Definition at line 116 of file Transform.cpp.
{
    Render::Model modelMat = transform.getModelMatrix();
    return transformBoundingVolume(boundingVolume, modelMat);
}
References GLESC::Transform::Transform::getModelMatrix(), and transformBoundingVolume().
Referenced by GLESC::Render::Renderer::render(), transformBoundingVolume(), transformMesh(), and translateBV().
transformMesh() [1/2]
void Transformer::transformMesh (Render::ColorMesh & mesh, const Mat4F & matrix) static private
Definition at line 72 of file Transform.cpp.
{
    for (auto& vertex : mesh.getModifiableVertices()) {
        vertex.setPosition(transformVector(vertex.getPosition(), matrix));
    }
    transformBoundingVolume(mesh.getBoundingVolumeMutable(), matrix);
}
References GLESC::Render::Mesh< VertexT >::getBoundingVolumeMutable(), GLESC::Render::Mesh< VertexT >::getModifiableVertices(), GLESC::isIterable_v, transformBoundingVolume(), and transformVector().
transformMesh() [2/2]
void Transformer::transformMesh (Render::ColorMesh & mesh, const Transform & transform) static
Scales a mesh by a given scale.
This function will transform all the vertices of the mesh by the given transform, iterating over all of them and applying the scale.
Parameters
mesh The mesh to scale.
Definition at line 98 of file Transform.cpp.
{
    Render::Model modelMat = transform.getModelMatrix();
    transformMesh(mesh, modelMat);
}
References GLESC::Transform::Transform::getModelMatrix(), and transformMesh().
Referenced by transformMesh().
transformVector()
Position Transformer::transformVector (const Position & position, const Render::Model & matrix) static
Transforms a position by a given matrix.
It will just multiply the position by the matrix and return the result.
Parameters
position The position to transform.
matrix The matrix to apply.
Definition at line 123 of file Transform.cpp.
{
    // IMPORTANT! We use row major matrices but the data distribution is prepared to be column major for in GPU
    // operations. So for the CPU we need to transpose the matrices.
    Vec4F transformedToWorldVertex = matrix * position.homogenize();
    return transformedToWorldVertex.dehomogenize();
}
References GLESC::Math::Vector< Type, N >::homogenize(), and GLESC::isIterable_v.
Referenced by GLESC::Render::Renderer::renderLights(), transformBoundingVolume(), and transformMesh().
translateMesh()
void Transformer::translateMesh (Render::ColorMesh & mesh, const Position & translation) static
Translates a mesh by a given position.
This function will translate all the vertices of the mesh by the given position, iterating over all of them and applying the translation.
Parameters
mesh The mesh to translate.
translation The translation to apply.
Definition at line 80 of file Transform.cpp.
{
    for (auto& vertex : mesh.getModifiableVertices()) {
        vertex.setPosition({
            vertex.getPosition().getX() + translation.getX(),
            vertex.getPosition().getY() + translation.getY(),
            vertex.getPosition().getZ() + translation.getZ()
        });
    }
}
References GLESC::Render::Mesh< VertexT >::getModifiableVertices(), and GLESC::isIterable_v.
worldToViewport()
Position Transformer::worldToViewport (const Position & worldPos, const Render::VP & viewProj, float vpWidth, float vpHeight) static
Transforms the world position to viewport coordinates.
This is done by transforming the world position to clip position, then to normalized device coordinates, and finally to viewport coordinates.
Parameters
worldPos The world position to transform.
viewProj The view projection matrix.
vpWidth The viewport width.
vpHeight The viewport height.
Returns
The viewport coordinates.
Definition at line 146 of file Transform.cpp.
{
    // IMPORTANT! We use row major matrices but the data distribution is prepared to be column major for in GPU
    // operations. So for the CPU we need to transpose the matrices.
    HomogeneousPosition clipPos = viewProj * worldPos.homogenize();
    Position ndcPos = clipToNDC(clipPos);
    return NDCToViewport(ndcPos, vpWidth, vpHeight);
}
References clipToNDC(), GLESC::Math::Vector< Type, N >::homogenize(), GLESC::isIterable_v, and NDCToViewport().
Referenced by GLESC::HUD::DebugItems::windowContent().
The documentation for this class was generated from the following files:
Transform.h
Transform.cpp