GLESC: GLESC::Render::GlobalSun Class Reference
GLESC::Render::GlobalSun Class Reference
#include <GlobalSun.h>
Public Member Functions
GlobalSun ()=default
Default constructor.
GlobalSun (float intensity, ColorRgb color, Math::Direction direction)
ColorRgb getColor () const
std::vector< EntityStatsManager::Value > getDebuggingValues ()
Math::Direction getDirection () const
float getIntensity () const
bool & isDirty () const
void setClean () const
void setColor (const ColorRgb &color)
void setDirection (const Math::Direction &direction)
void setDirty () const
void setIntensity (float intensity)
std::string toString () const
Private Attributes
ColorRgb color {255, 255, 255}
Math::Direction direction {0.f, -1.0f, 0.f}
bool dirty = true
Dirty flag for the sun.
Intensity< float > intensity {1.0f}
Detailed Description
Definition at line 18 of file GlobalSun.h.
Constructor & Destructor Documentation
GlobalSun() [1/2]
GLESC::Render::GlobalSun::GlobalSun () default
Default constructor.
GlobalSun() [2/2]
GLESC::Render::GlobalSun::GlobalSun (float intensity, ColorRgb color, Math::Direction direction) inline
Definition at line 25 of file GlobalSun.h.
                                                                              :
            intensity(intensity), color(std::move(color)), direction(std::move(direction)) {
        }
Member Function Documentation
getColor()
ColorRgb GLESC::Render::GlobalSun::getColor () const inline
Definition at line 33 of file GlobalSun.h.
{
            return color;
        }
References color.
getDebuggingValues()
std::vector< EntityStatsManager::Value > GLESC::Render::GlobalSun::getDebuggingValues ()
Definition at line 3 of file GlobalSun.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value intensityValue;
    intensityValue.name = "Sun Intensity";
    intensityValue.data = reinterpret_cast<void*>(&intensity.getModifiable());
    intensityValue.type = EntityStatsManager::ValueType::FLOAT;
    intensityValue.isModifiable = true;
    intensityValue.usesSlider = true;
    intensityValue.valueDirty = &dirty;
    intensityValue.min = 0.0f;
    intensityValue.max = 1.0f;
    values.push_back(intensityValue);
    EntityStatsManager::Value colorValue;
    colorValue.name = "Sun Color";
    colorValue.data = reinterpret_cast<void*>(&color.data);
    colorValue.type = EntityStatsManager::ValueType::VEC3F;
    colorValue.isModifiable = true;
    colorValue.valueDirty = &dirty;
    colorValue.usesSlider = true;
    colorValue.min = 0.0f;
    colorValue.max = 255.0f;
    values.push_back(colorValue);
    EntityStatsManager::Value directionValue;
    directionValue.name = "Sun Direction";
    directionValue.data = reinterpret_cast<void*>(&direction);
    directionValue.type = EntityStatsManager::ValueType::VEC3F;
    directionValue.isModifiable = true;
    directionValue.usesSlider = true;
    directionValue.valueDirty = &dirty;
    directionValue.min = -1.0f;
    directionValue.max = 1.0f;
    values.push_back(directionValue);
    return values;
}
References color, GLESC::Math::Vector< Type, N >::data, direction, dirty, EntityStatsManager::FLOAT, GLESC::Render::Intensity< IntensityType >::getModifiable(), intensity, GLESC::isIterable_v, EntityStatsManager::Value::name, and EntityStatsManager::VEC3F.
Referenced by GLESC::ECS::SunComponent::setDebuggingValues().
getDirection()
Math::Direction GLESC::Render::GlobalSun::getDirection () const inline
Definition at line 37 of file GlobalSun.h.
{
            return direction;
        }
References direction.
getIntensity()
float GLESC::Render::GlobalSun::getIntensity () const inline
Definition at line 29 of file GlobalSun.h.
{
            return intensity.get();
        }
References GLESC::Render::Intensity< IntensityType >::get(), and intensity.
isDirty()
bool & GLESC::Render::GlobalSun::isDirty () const inline
Definition at line 66 of file GlobalSun.h.
{
            return dirty;
        }
References dirty.
setClean()
void GLESC::Render::GlobalSun::setClean () const inline
Definition at line 61 of file GlobalSun.h.
{
            dirty = false;
        }
References dirty.
setColor()
void GLESC::Render::GlobalSun::setColor (const ColorRgb & color) inline
Definition at line 47 of file GlobalSun.h.
{
            this->color = color;
            setDirty();
        }
References color, and setDirty().
setDirection()
void GLESC::Render::GlobalSun::setDirection (const Math::Direction & direction) inline
Definition at line 52 of file GlobalSun.h.
{
            this->direction = direction;
            setDirty();
        }
References direction, and setDirty().
setDirty()
void GLESC::Render::GlobalSun::setDirty () const inline
Definition at line 57 of file GlobalSun.h.
{
            dirty = true;
        }
References dirty.
Referenced by setColor(), setDirection(), and setIntensity().
setIntensity()
void GLESC::Render::GlobalSun::setIntensity (float intensity) inline
Definition at line 42 of file GlobalSun.h.
{
            this->intensity = Intensity(intensity);
            setDirty();
        }
References intensity, and setDirty().
toString()
std::string GLESC::Render::GlobalSun::toString () const
Definition at line 46 of file GlobalSun.cpp.
{
    return "Intensity: " + std::to_string(intensity.get()) +
        " Color: " + color.toString() +
        " Direction: " + direction.toString();
}
Referenced by GLESC::ECS::SunComponent::toString().
Member Data Documentation
color
ColorRgb GLESC::Render::GlobalSun::color {255, 255, 255} private
Definition at line 75 of file GlobalSun.h.
{255, 255, 255};
Referenced by getColor(), getDebuggingValues(), and setColor().
direction
Math::Direction GLESC::Render::GlobalSun::direction {0.f, -1.0f, 0.f} private
Definition at line 74 of file GlobalSun.h.
{0.f, -1.0f, 0.f};
Referenced by getDebuggingValues(), getDirection(), and setDirection().
dirty
bool GLESC::Render::GlobalSun::dirty = true mutable private
Dirty flag for the sun.
If the sun is dirty, it will be updated in the shader
Definition at line 80 of file GlobalSun.h.
Referenced by getDebuggingValues(), isDirty(), setClean(), and setDirty().
intensity
Intensity<float> GLESC::Render::GlobalSun::intensity {1.0f} private
Definition at line 73 of file GlobalSun.h.
{1.0f};
Referenced by getDebuggingValues(), getIntensity(), and setIntensity().
The documentation for this class was generated from the following files:
GlobalSun.h
GlobalSun.cpp