GLESC: GLESC::StatsManager Class Reference
GLESC::StatsManager Class Reference
Class to manage the stats of the game.
#include <StatsManager.h>
Static Public Member Functions
static std::unordered_map< std::string, std::string > getStats ()
template<typename Func >
static void registerStatSource (const std::string &name, Func callback)
Static Private Attributes
static std::map< std::string, std::function< std::string()> > sources = {}
Detailed Description
Class to manage the stats of the game.
This class allows registering stat sources such as FPS, memory usage, etc.
Definition at line 23 of file StatsManager.h.
Member Function Documentation
getStats()
std::unordered_map< std::string, std::string > StatsManager::getStats () static
Definition at line 12 of file StatsManager.cpp.
{
    std::unordered_map<std::string, std::string> result;
    for (auto& source : sources) {
        result[source.first] = source.second();
    }
    return result;
}
References GLESC::isIterable_v, and sources.
Referenced by GLESC::HUD::DebugStatsHUD::windowContent().
registerStatSource()
template<typename Func > static void GLESC::StatsManager::registerStatSource (const std::string & name, Func callback) inline static
Definition at line 27 of file StatsManager.h.
{
            S_ASSERT_TRUE(std::is_invocable_v<Func>, "Callback must be invocable");
            sources[name] = [callback]() -> std::string {
                return Stringer::toString(callback());
            };
        }
References GLESC::isIterable_v, S_ASSERT_TRUE, sources, and GLESC::Stringer::toString().
Referenced by GLESC::Engine::registerStats().
Member Data Documentation
sources
std::map< std::string, std::function< std::string()> > StatsManager::sources = {} static private
Definition at line 38 of file StatsManager.h.
Referenced by getStats(), and registerStatSource().
The documentation for this class was generated from the following files:
StatsManager.h
StatsManager.cpp