GLESC: GLESC::ECS::InputSystem Class Reference
GLESC::ECS::InputSystem Class Reference
#include <InputSystem.h>
Public Member Functions
InputSystem (Input::InputManager &inputManager, ECSCoordinator &ecs)
void update () override
Updates the system.
Public Member Functions inherited from GLESC::ECS::System
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
Private Attributes
Input::InputManager & inputManager
Additional Inherited Members
Protected Member Functions inherited from GLESC::ECS::System
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes inherited from GLESC::ECS::System
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Detailed Description
Definition at line 17 of file InputSystem.h.
Constructor & Destructor Documentation
InputSystem()
InputSystem::InputSystem (Input::InputManager & inputManager, ECSCoordinator & ecs) explicit
Definition at line 16 of file InputSystem.cpp.
                                                                             :
    System(ecs, "InputSystem"), inputManager(inputManager) {
    addComponentRequirement<InputComponent>();
}
References GLESC::isIterable_v.
Member Function Documentation
update()
void InputSystem::update () override virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implements GLESC::ECS::System.
Definition at line 21 of file InputSystem.cpp.
{
    for (auto &entity : getAssociatedEntities()) {
        auto &input = getComponent<InputComponent>(entity);
        for (std::pair<const Input::KeyInput, Input::KeyCommand> &keyPressedPair : input.input.getSubscribedKeys()) {
            const Input::KeyInput &key = keyPressedPair.first;
            Input::KeyCommand &command = keyPressedPair.second;
            if (inputManager.checkKeyAction(key)) {
                command.execute();
            }
        }
        input.input.getMouseCommand().execute(inputManager.getMousePosition());
    }
}
References GLESC::Input::InputManager::checkKeyAction(), GLESC::Input::KeyCommand::execute(), GLESC::ECS::System::getAssociatedEntities(), GLESC::Input::InputManager::getMousePosition(), input(), inputManager, and GLESC::isIterable_v.
Member Data Documentation
inputManager
Input::InputManager& GLESC::ECS::InputSystem::inputManager private
Definition at line 23 of file InputSystem.h.
Referenced by update().
The documentation for this class was generated from the following files:
InputSystem.h
InputSystem.cpp