GLESC: GLESC::Input::Input Class Reference
GLESC::Input::Input Class Reference
Class that stores the input from the user.
#include <Input.h>
Public Member Functions
std::vector< EntityStatsManager::Value > getDebuggingValues ()
MouseCommand & getMouseCommand ()
const MouseCommand & getMouseCommand () const
std::unordered_map< KeyInput, KeyCommand > & getSubscribedKeys ()
const std::unordered_map< KeyInput, KeyCommand > & getSubscribedKeys () const
void setMouseCommand (const MouseCommand &command)
void subscribeKey (const KeyInput &key, const KeyCommand &command)
std::string toString () const
void unsubscribeKey (const KeyInput &key)
Private Attributes
MouseCommand mouseCommand
A command that is executed when the mouse is moved.
std::unordered_map< KeyInput, KeyCommand > subscribedKeys
Vector of pairs, subscribed keys and bool,true if they are pressed.
Detailed Description
Class that stores the input from the user.
This is a entity component that stores all the input subscriptions to keys and the mouse movement.
The benefits of this class is that we can store directly the commands with their functions that will be executed when the input condition is met.
Definition at line 24 of file Input.h.
Member Function Documentation
getDebuggingValues()
std::vector< EntityStatsManager::Value > Input::getDebuggingValues ()
Definition at line 18 of file Input.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value subscribedKeysValue;
    subscribedKeysValue.name = "Subscribed keys";
    subscribedKeysValue.isString = true;
    std::stringstream ss;
    for (const auto& [key, command] : subscribedKeys) {
        ss << keyToString(key.key) << "\n";
    }
    subscribedKeysValue.stringData = ss.str();
    values.push_back(subscribedKeysValue);
    return values;
}
References GLESC::isIterable_v, GLESC::Input::keyToString(), EntityStatsManager::Value::name, and subscribedKeys.
Referenced by GLESC::ECS::InputComponent::setDebuggingValues().
getMouseCommand() [1/2]
MouseCommand & GLESC::Input::Input::getMouseCommand () inline
Definition at line 43 of file Input.h.
{
            return mouseCommand;
        }
References mouseCommand.
getMouseCommand() [2/2]
const MouseCommand & GLESC::Input::Input::getMouseCommand () const inline
Definition at line 39 of file Input.h.
{
            return mouseCommand;
        }
References mouseCommand.
getSubscribedKeys() [1/2]
std::unordered_map< KeyInput, KeyCommand > & GLESC::Input::Input::getSubscribedKeys () inline
Definition at line 35 of file Input.h.
{
            return subscribedKeys;
        }
References subscribedKeys.
getSubscribedKeys() [2/2]
const std::unordered_map< KeyInput, KeyCommand > & GLESC::Input::Input::getSubscribedKeys () const inline
Definition at line 31 of file Input.h.
{
            return subscribedKeys;
        }
References subscribedKeys.
setMouseCommand()
void GLESC::Input::Input::setMouseCommand (const MouseCommand & command) inline
Definition at line 55 of file Input.h.
{
            mouseCommand = command;
        }
References GLESC::isIterable_v, and mouseCommand.
subscribeKey()
void GLESC::Input::Input::subscribeKey (const KeyInput & key, const KeyCommand & command) inline
Definition at line 47 of file Input.h.
{
            subscribedKeys[key] = command;
        }
References GLESC::isIterable_v, and subscribedKeys.
toString()
std::string Input::Input::toString () const
Definition at line 33 of file Input.cpp.
{
    std::stringstream ss;
    ss << "Subscribed keys:\n";
    for (const auto& [key, command] : subscribedKeys) {
        ss << keyToString(key.key) << "\n";
    }
    return ss.str();
}
References GLESC::isIterable_v, and GLESC::Input::keyToString().
Referenced by GLESC::ECS::InputComponent::toString().
unsubscribeKey()
void GLESC::Input::Input::unsubscribeKey (const KeyInput & key) inline
Definition at line 51 of file Input.h.
{
            subscribedKeys.erase(key);
        }
References subscribedKeys.
Member Data Documentation
mouseCommand
MouseCommand GLESC::Input::Input::mouseCommand private
A command that is executed when the mouse is moved.
Definition at line 69 of file Input.h.
Referenced by getMouseCommand(), getMouseCommand(), and setMouseCommand().
subscribedKeys
std::unordered_map<KeyInput, KeyCommand> GLESC::Input::Input::subscribedKeys private
Vector of pairs, subscribed keys and bool,true if they are pressed.
This vector is used to store the keys that are subscribed to the input system, this it saves memory as each only stores the keys that are subscribed to it.
Definition at line 65 of file Input.h.
Referenced by getDebuggingValues(), getSubscribedKeys(), getSubscribedKeys(), subscribeKey(), and unsubscribeKey().
The documentation for this class was generated from the following files:
Input.h
Input.cpp