GLESC: HudLookAndFeel Class Reference
HudLookAndFeel Class Reference
Class that encapsulates the look and feel of the HUD.
#include <HUDLookAndFeel.h>
Public Types
using FontSize = int
Public Member Functions
~HudLookAndFeel ()=default
void addFont (const std::string &fileName, FontSize size)
Adds a font from a file with a size.
void apply ()
Applies the look and feel to ImGui.
std::string getDefaultFont () const
Returns the default font and font size.
FontSize getDefaultFontSize () const
Returns the default font size.
ImFont * getFont (const std::string &fileName, FontSize size)
void setDefaultFont (const std::string &fileName)
Sets the default font.
void setDefaultFontSize (int size)
Sets the default font size.
Static Public Member Functions
static HudLookAndFeel & get ()
Returns the singleton instance of the class.
Private Member Functions
HudLookAndFeel ()=default
Static Private Member Functions
static void validateFontName (const std::string &fileName)
static void validateFontSize (FontSize size)
Private Attributes
ImVec4 black = ImVec4(0.00f, 0.00f, 0.00f, 1.00f)
ImVec4 brightGreen = ImVec4(0.20f, 0.75f, 0.40f, 1.00f)
ImVec4 darkGreen = ImVec4(0.00f, 0.20f, 0.13f, 1.00f)
std::string defaultFont
int defaultFontSize = 0
std::unordered_map< std::string, ImFont * > fonts
ImVec4 gray = ImVec4(0.20f, 0.25f, 0.20f, 1.00f)
ImVec4 green = ImVec4(0.00f, 0.50f, 0.33f, 1.00f)
bool lookAndFeelApplied = false
ImVec4 veryDarkGreen = ImVec4(0.00f, 0.10f, 0.07f, 1.00f)
ImVec4 white = ImVec4(0.75f, 0.75f, 0.75f, 1.00f)
Detailed Description
Class that encapsulates the look and feel of the HUD.
Allows setting the look and feel of the HUD, such as the font, font size, and colors.
Definition at line 18 of file HUDLookAndFeel.h.
Member Typedef Documentation
FontSize
using HudLookAndFeel::FontSize = int
Definition at line 20 of file HUDLookAndFeel.h.
Constructor & Destructor Documentation
~HudLookAndFeel()
HudLookAndFeel::~HudLookAndFeel () default
HudLookAndFeel()
HudLookAndFeel::HudLookAndFeel () private default
Member Function Documentation
addFont()
void HudLookAndFeel::addFont (const std::string & fileName, FontSize size)
Adds a font from a file with a size.
The font is added to the list of fonts that can be used in the HUD. Fonts need to be loaded before use, and this class handles the loading and caching of fonts.
Parameters
fileName The name of the font file.
size The font size.
Definition at line 12 of file HUDLookAndFeel.cpp.
{
    validateFontName(fileName);
    validateFontSize(size);
    std::string fullFontPath = BinPath::getExecutableDirectory() + ASSETS_PATH + FONTS_PATH_FROM_ASSETS + fileName +
        FONTS_EXTENSION;
    //fullFontPath= GLESC::Stringer::replace(fullFontPath, "/", "\\");
    Logger::get().info("Loading font: " + fullFontPath);
    ImGuiIO& io = ImGui::GetIO();
    ImFont* font = io.Fonts->AddFontFromFileTTF(fullFontPath.c_str(), static_cast<float>(size));
    D_ASSERT_NOT_NULLPTR(font, "Failed to load font: " + fullFontPath);
    fonts[fileName + std::to_string(size)] = font;
}
References D_ASSERT_NOT_NULLPTR, fonts, FONTS_EXTENSION, FONTS_PATH_FROM_ASSETS, GLESC::Logger::get(), BinPath::getExecutableDirectory(), GLESC::Logger::info(), validateFontName(), and validateFontSize().
Referenced by getFont(), and GLESC::HUD::HUDManager::initImGUI().
apply()
void HudLookAndFeel::apply ()
Applies the look and feel to ImGui.
Definition at line 66 of file HUDLookAndFeel.cpp.
{
    ImVec4* colors = ImGui::GetStyle().Colors;
    colors[ImGuiCol_Text] = ImVec4(0.29f, 1.00f, 0.28f, 1.00f);
    colors[ImGuiCol_TextDisabled] = ImVec4(0.48f, 0.61f, 0.48f, 1.00f);
    colors[ImGuiCol_WindowBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.85f);
    colors[ImGuiCol_ChildBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_PopupBg] = ImVec4(0.11f, 0.11f, 0.14f, 0.92f);
    colors[ImGuiCol_Border] = ImVec4(0.15f, 0.70f, 0.22f, 0.50f);
    colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_FrameBg] = ImVec4(0.43f, 0.43f, 0.43f, 0.39f);
    colors[ImGuiCol_FrameBgHovered] = ImVec4(0.47f, 0.69f, 0.47f, 0.40f);
    colors[ImGuiCol_FrameBgActive] = ImVec4(0.41f, 0.64f, 0.41f, 0.69f);
    colors[ImGuiCol_TitleBg] = ImVec4(0.27f, 0.54f, 0.27f, 0.83f);
    colors[ImGuiCol_TitleBgActive] = ImVec4(0.32f, 0.63f, 0.32f, 0.87f);
    colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.40f, 0.80f, 0.41f, 0.20f);
    colors[ImGuiCol_MenuBarBg] = ImVec4(0.40f, 0.55f, 0.40f, 0.80f);
    colors[ImGuiCol_ScrollbarBg] = ImVec4(0.20f, 0.30f, 0.20f, 0.60f);
    colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.41f, 0.80f, 0.40f, 0.30f);
    colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.40f, 0.80f, 0.40f, 0.40f);
    colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.39f, 0.80f, 0.39f, 0.60f);
    colors[ImGuiCol_CheckMark] = ImVec4(0.90f, 0.90f, 0.90f, 0.50f);
    colors[ImGuiCol_SliderGrab] = ImVec4(1.00f, 1.00f, 1.00f, 0.30f);
    colors[ImGuiCol_SliderGrabActive] = ImVec4(0.39f, 0.80f, 0.39f, 0.60f);
    colors[ImGuiCol_Button] = ImVec4(0.35f, 0.61f, 0.36f, 0.62f);
    colors[ImGuiCol_ButtonHovered] = ImVec4(0.40f, 0.71f, 0.41f, 0.79f);
    colors[ImGuiCol_ButtonActive] = ImVec4(0.46f, 0.80f, 0.47f, 1.00f);
    colors[ImGuiCol_Header] = ImVec4(0.40f, 0.90f, 0.40f, 0.45f);
    colors[ImGuiCol_HeaderHovered] = ImVec4(0.45f, 0.90f, 0.45f, 0.80f);
    colors[ImGuiCol_HeaderActive] = ImVec4(0.53f, 0.87f, 0.54f, 0.80f);
    colors[ImGuiCol_Separator] = ImVec4(0.21f, 0.39f, 0.21f, 0.60f);
    colors[ImGuiCol_SeparatorHovered] = ImVec4(0.60f, 0.70f, 0.60f, 1.00f);
    colors[ImGuiCol_SeparatorActive] = ImVec4(0.70f, 0.90f, 0.70f, 1.00f);
    colors[ImGuiCol_ResizeGrip] = ImVec4(1.00f, 1.00f, 1.00f, 0.10f);
    colors[ImGuiCol_ResizeGripHovered] = ImVec4(0.78f, 1.00f, 0.79f, 0.60f);
    colors[ImGuiCol_ResizeGripActive] = ImVec4(0.78f, 1.00f, 0.78f, 0.90f);
    colors[ImGuiCol_Tab] = ImVec4(0.34f, 0.68f, 0.34f, 0.79f);
    colors[ImGuiCol_TabHovered] = ImVec4(0.45f, 0.90f, 0.46f, 0.80f);
    colors[ImGuiCol_TabActive] = ImVec4(0.40f, 0.73f, 0.41f, 0.84f);
    colors[ImGuiCol_TabUnfocused] = ImVec4(0.28f, 0.57f, 0.29f, 0.82f);
    colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.35f, 0.65f, 0.35f, 0.84f);
    colors[ImGuiCol_PlotLines] = ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
    colors[ImGuiCol_PlotLinesHovered] = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogram] = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
    colors[ImGuiCol_PlotHistogramHovered] = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
    colors[ImGuiCol_TableHeaderBg] = ImVec4(0.27f, 0.38f, 0.27f, 1.00f);
    colors[ImGuiCol_TableBorderStrong] = ImVec4(0.31f, 0.45f, 0.31f, 1.00f);
    colors[ImGuiCol_TableBorderLight] = ImVec4(0.26f, 0.26f, 0.28f, 1.00f);
    colors[ImGuiCol_TableRowBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
    colors[ImGuiCol_TableRowBgAlt] = ImVec4(1.00f, 1.00f, 1.00f, 0.07f);
    colors[ImGuiCol_TextSelectedBg] = ImVec4(0.00f, 1.00f, 0.01f, 0.35f);
    colors[ImGuiCol_DragDropTarget] = ImVec4(1.00f, 1.00f, 0.00f, 0.90f);
    colors[ImGuiCol_NavHighlight] = ImVec4(0.45f, 0.90f, 0.45f, 0.80f);
    colors[ImGuiCol_NavWindowingHighlight] = ImVec4(1.00f, 1.00f, 1.00f, 0.70f);
    colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.80f, 0.80f, 0.80f, 0.20f);
    colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.20f, 0.20f, 0.20f, 0.35f);
    // Make sure these changes take effect
    ImGui::GetIO().FontDefault = getFont(defaultFont, defaultFontSize);
    ImGui::GetIO().Fonts->Build();
    lookAndFeelApplied = true;
}
References defaultFont, defaultFontSize, getFont(), and lookAndFeelApplied.
Referenced by GLESC::HUD::HUDManager::initImGUI().
get()
static HudLookAndFeel & HudLookAndFeel::get () inline static
Returns the singleton instance of the class.
Returns
The singleton instance of the class.
Definition at line 27 of file HUDLookAndFeel.h.
{
        static HudLookAndFeel instance;
        return instance;
    }
Referenced by GLESC::HUD::HUDManager::initImGUI(), GLESC::HUD::DebugEntityData::windowContent(), and GLESC::HUD::DebugStatsHUD::windowContent().
getDefaultFont()
std::string HudLookAndFeel::getDefaultFont () const
Returns the default font and font size.
Returns
The default font and font size.
Definition at line 47 of file HUDLookAndFeel.cpp.
{
    D_ASSERT_TRUE(!defaultFont.empty(), "Default font not set");
    return defaultFont;
}
References D_ASSERT_TRUE, and defaultFont.
getDefaultFontSize()
HudLookAndFeel::FontSize HudLookAndFeel::getDefaultFontSize () const
Returns the default font size.
Returns
The default font size.
Definition at line 52 of file HUDLookAndFeel.cpp.
{
    D_ASSERT_TRUE(defaultFontSize > 0, "Default font size not set");
    return defaultFontSize;
}
References D_ASSERT_TRUE, and defaultFontSize.
getFont()
ImFont * HudLookAndFeel::getFont (const std::string & fileName, FontSize size)
Definition at line 57 of file HUDLookAndFeel.cpp.
{
    validateFontName(fileName);
    validateFontSize(size);
    if (fonts.find(fileName + std::to_string(size)) == fonts.end()) {
        addFont(fileName, size);
    }
    return fonts[fileName + std::to_string(size)];
}
References addFont(), fonts, validateFontName(), and validateFontSize().
Referenced by apply().
setDefaultFont()
void HudLookAndFeel::setDefaultFont (const std::string & fileName)
Sets the default font.
Parameters
fileName The name of the font file.
Definition at line 37 of file HUDLookAndFeel.cpp.
{
    validateFontName(fileName);
    defaultFont = fileName;
}
References defaultFont, and validateFontName().
Referenced by GLESC::HUD::HUDManager::initImGUI().
setDefaultFontSize()
void HudLookAndFeel::setDefaultFontSize (int size)
Sets the default font size.
Parameters
size The font size.
Definition at line 42 of file HUDLookAndFeel.cpp.
{
    validateFontSize(size);
    defaultFontSize = size;
}
References defaultFontSize, and validateFontSize().
Referenced by GLESC::HUD::HUDManager::initImGUI().
validateFontName()
void HudLookAndFeel::validateFontName (const std::string & fileName) static private
Definition at line 25 of file HUDLookAndFeel.cpp.
{
    D_ASSERT_TRUE(!fileName.empty(), "Font file name cannot be empty");
    D_ASSERT_TRUE(!GLESC::Stringer::contains(fileName, FONTS_EXTENSION),
                  "Font file should not contain the extension");
    D_ASSERT_TRUE(!GLESC::Stringer::contains(fileName, FONTS_PATH_FROM_ASSETS),
                  "Font file should not contain the path");
}
References GLESC::Stringer::contains(), D_ASSERT_TRUE, FONTS_EXTENSION, and FONTS_PATH_FROM_ASSETS.
Referenced by addFont(), getFont(), and setDefaultFont().
validateFontSize()
void HudLookAndFeel::validateFontSize (FontSize size) static private
Definition at line 33 of file HUDLookAndFeel.cpp.
{
    D_ASSERT_TRUE(size > 0, "Font size should be greater than 0");
}
References D_ASSERT_TRUE.
Referenced by addFont(), getFont(), and setDefaultFontSize().
Member Data Documentation
black
ImVec4 HudLookAndFeel::black = ImVec4(0.00f, 0.00f, 0.00f, 1.00f) private
Definition at line 82 of file HUDLookAndFeel.h.
brightGreen
ImVec4 HudLookAndFeel::brightGreen = ImVec4(0.20f, 0.75f, 0.40f, 1.00f) private
Definition at line 81 of file HUDLookAndFeel.h.
darkGreen
ImVec4 HudLookAndFeel::darkGreen = ImVec4(0.00f, 0.20f, 0.13f, 1.00f) private
Definition at line 79 of file HUDLookAndFeel.h.
defaultFont
std::string HudLookAndFeel::defaultFont private
Definition at line 86 of file HUDLookAndFeel.h.
Referenced by apply(), getDefaultFont(), and setDefaultFont().
defaultFontSize
int HudLookAndFeel::defaultFontSize = 0 private
Definition at line 87 of file HUDLookAndFeel.h.
Referenced by apply(), getDefaultFontSize(), and setDefaultFontSize().
fonts
std::unordered_map<std::string, ImFont *> HudLookAndFeel::fonts private
Definition at line 85 of file HUDLookAndFeel.h.
Referenced by addFont(), and getFont().
gray
ImVec4 HudLookAndFeel::gray = ImVec4(0.20f, 0.25f, 0.20f, 1.00f) private
Definition at line 84 of file HUDLookAndFeel.h.
green
ImVec4 HudLookAndFeel::green = ImVec4(0.00f, 0.50f, 0.33f, 1.00f) private
Definition at line 80 of file HUDLookAndFeel.h.
lookAndFeelApplied
bool HudLookAndFeel::lookAndFeelApplied = false private
Definition at line 89 of file HUDLookAndFeel.h.
Referenced by apply().
veryDarkGreen
ImVec4 HudLookAndFeel::veryDarkGreen = ImVec4(0.00f, 0.10f, 0.07f, 1.00f) private
Definition at line 78 of file HUDLookAndFeel.h.
white
ImVec4 HudLookAndFeel::white = ImVec4(0.75f, 0.75f, 0.75f, 1.00f) private
Definition at line 83 of file HUDLookAndFeel.h.
The documentation for this class was generated from the following files:
HUDLookAndFeel.h
HUDLookAndFeel.cpp