GLESC: GLESC::ECS::ComponentArray< Component > Class Template Reference
GLESC::ECS::ComponentArray< Component > Class Template Reference
The ComponentArray class is a template class that stores components of a specific type.
#include <ComponentArray.h>
Public Member Functions
ComponentArray ()=default
void entityDestroyed (EntityID entity) override
Called when an entity is destroyed.
IComponent & getComponent (EntityID entity) override
Get the component of the entity.
Component & getData (EntityID entity)
Get the data of the entity.
bool hasComponent (EntityID entity) override
Checks if the entity has a component of type T.
void insertData (EntityID entity, const Component &component)
Inserts the data of the entity into the array.
void removeData (EntityID entity)
Removes the data of the entity from the array The last element in the array is copied into the place of the removed element The maps are updated to reflect the changes.
Public Member Functions inherited from GLESC::ECS::IComponentArray
virtual ~IComponentArray ()=default
Private Member Functions
size_t getSize () override
void printStatus (const std::string &context)
Print the status of the component array.
Private Attributes
std::array< Component, maxEntities > componentArray
The packed array of components (of generic type T), set to a specified maximum amount, matching the maximum number of entities allowed to exist simultaneously, so that each entity has a unique spot.
std::unordered_map< EntityID, size_t > entityToIndexMap
Map from an entity ID to an array index.
std::unordered_map< size_t, EntityID > indexToEntityMap
size_t size {}
Total size of valid entries in the array.
Detailed Description
template<typename Component>
class GLESC::ECS::ComponentArray< Component >
The ComponentArray class is a template class that stores components of a specific type.
Template Parameters
Component The type of component to store
Definition at line 44 of file ComponentArray.h.
Constructor & Destructor Documentation
ComponentArray()
template<typename Component > GLESC::ECS::ComponentArray< Component >::ComponentArray () default
Member Function Documentation
entityDestroyed()
template<typename Component > void GLESC::ECS::ComponentArray< Component >::entityDestroyed (EntityID entity) inline override virtual
Called when an entity is destroyed.
The entity is removed from the array
Parameters
entity The entity that was destroyed
Implements GLESC::ECS::IComponentArray.
Definition at line 148 of file ComponentArray.h.
{
            if (entityToIndexMap.find(entity) != entityToIndexMap.end()) {
                removeData(entity);
            }
        }
References GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::isIterable_v, and GLESC::ECS::ComponentArray< Component >::removeData().
getComponent()
template<typename Component > IComponent & GLESC::ECS::ComponentArray< Component >::getComponent (EntityID entity) inline override virtual
Get the component of the entity.
Parameters
entity The entity to get the component from
Returns
The component of the entity
Implements GLESC::ECS::IComponentArray.
Definition at line 52 of file ComponentArray.h.
{
            D_ASSERT_TRUE(hasComponent(entity), "Entity does not have component");
            return componentArray[entityToIndexMap.at(entity)];
        }
References GLESC::ECS::ComponentArray< Component >::componentArray, D_ASSERT_TRUE, GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::ECS::ComponentArray< Component >::hasComponent(), and GLESC::isIterable_v.
getData()
template<typename Component > Component & GLESC::ECS::ComponentArray< Component >::getData (EntityID entity) inline
Get the data of the entity.
Parameters
entity The entity to get the data from
Returns
The data of the entity
Definition at line 125 of file ComponentArray.h.
{
            D_ASSERT_TRUE(hasComponent(entity), "Entity does not have component");
            // Return a reference to the entity's component
            return componentArray[entityToIndexMap[entity]];
        }
References GLESC::ECS::ComponentArray< Component >::componentArray, D_ASSERT_TRUE, GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::ECS::ComponentArray< Component >::hasComponent(), and GLESC::isIterable_v.
getSize()
template<typename Component > size_t GLESC::ECS::ComponentArray< Component >::getSize () inline override private virtual
Implements GLESC::ECS::IComponentArray.
Definition at line 199 of file ComponentArray.h.
{
            return size;
        }
References GLESC::ECS::ComponentArray< Component >::size.
hasComponent()
template<typename Component > bool GLESC::ECS::ComponentArray< Component >::hasComponent (EntityID entity) inline override virtual
Checks if the entity has a component of type T.
The check is useful to avoid adding or removing unnecessarily The remove and add components does not allow doing so, so this is a way to check
Parameters
entity
Returns
Implements GLESC::ECS::IComponentArray.
Definition at line 139 of file ComponentArray.h.
{
            return entityToIndexMap.find(entity) != entityToIndexMap.end();
        }
References GLESC::ECS::ComponentArray< Component >::entityToIndexMap, and GLESC::isIterable_v.
Referenced by GLESC::ECS::ComponentArray< Component >::getComponent(), GLESC::ECS::ComponentArray< Component >::getData(), GLESC::ECS::ComponentArray< Component >::insertData(), and GLESC::ECS::ComponentArray< Component >::removeData().
insertData()
template<typename Component > void GLESC::ECS::ComponentArray< Component >::insertData (EntityID entity, const Component & component) inline
Inserts the data of the entity into the array.
The entity is added to the end of the array It is also added to some maps for quick lookup
Parameters
entity The entity to insert
component The component to insert
Definition at line 64 of file ComponentArray.h.
{
            PRINT_COMPONENT_ARRAY_STATUS(
                "Before inserting component:\n"
                "\t" + component.toString() + "\n"
                "\tfrom entity " + std::to_string(entity));
            // If the entity already has a component in this array, do nothing
            if (hasComponent(entity)) return;
            // Put new entry at end and update the maps
            size_t newIndex = size;
            entityToIndexMap[entity] = newIndex;
            indexToEntityMap[newIndex] = entity;
            //componentArray[newIndex] = component;
            new(&componentArray[newIndex]) Component(std::move(component));
            ++size;
            PRINT_COMPONENT_ARRAY_STATUS(
                "After inserting component:\n"
                "\t" + component.toString() + "\n"
                "\tfrom entity " + std::to_string(entity));
        }
References GLESC::ECS::ComponentArray< Component >::componentArray, GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::ECS::ComponentArray< Component >::hasComponent(), GLESC::ECS::ComponentArray< Component >::indexToEntityMap, GLESC::isIterable_v, PRINT_COMPONENT_ARRAY_STATUS, and GLESC::ECS::ComponentArray< Component >::size.
printStatus()
template<typename Component > void GLESC::ECS::ComponentArray< Component >::printStatus (const std::string & context) inline private
Print the status of the component array.
Parameters
context The context of the status
Definition at line 159 of file ComponentArray.h.
{
            Logger::get().importantInfoBlue("ComponentArray Status Report - Context: " + context);
            const char* componentName = typeid(Component).name();
            Logger::get().infoBlue("Component Type: " + std::string(componentName));
            Logger::get().infoBlue("Total Components: " + std::to_string(size));
            Logger::get().infoBlue("\tEntityToIndexMap size: " + std::to_string(entityToIndexMap.size()));
            for (const auto& entry : entityToIndexMap) {
                Logger::get().infoBlue(
                    "\tEntity ID: " + std::to_string(entry.first) + ", Array Index: " + std::to_string(entry.second));
            }
            Logger::get().infoBlue("\tcomponent array with size " + std::to_string(size) + ":");
            for (int i = 0; i < size; i++) {
                Logger::get().infoBlue("\t\t Component number " + i);
                Logger::get().infoBlue("\t\t" + componentArray[i].toString()); // All components have a toString()
            }
        }
References GLESC::ECS::ComponentArray< Component >::componentArray, GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::Logger::get(), GLESC::Logger::importantInfoBlue(), GLESC::Logger::infoBlue(), GLESC::isIterable_v, and GLESC::ECS::ComponentArray< Component >::size.
removeData()
template<typename Component > void GLESC::ECS::ComponentArray< Component >::removeData (EntityID entity) inline
Removes the data of the entity from the array The last element in the array is copied into the place of the removed element The maps are updated to reflect the changes.
Parameters
entity The entity to remove
Definition at line 95 of file ComponentArray.h.
{
            PRINT_COMPONENT_ARRAY_STATUS("Before removing data from entity " + std::to_string(entity));
            D_ASSERT_TRUE(hasComponent(entity), "Entity does not have component");
            // Copy element at end into deleted element's place to maintain density
            size_t indexOfRemovedEntity = entityToIndexMap[entity];
            size_t indexOfLastElement = size - 1;
            // Call destructor on removed component, it is not called automatically causing bugs and memory leaks
            componentArray[indexOfRemovedEntity].~Component();
            new(&componentArray[indexOfRemovedEntity]) Component(std::move(componentArray[indexOfLastElement]));
            // Update map to point to moved spot
            EntityID entityOfLastElement = indexToEntityMap[indexOfLastElement];
            entityToIndexMap[entityOfLastElement] = indexOfRemovedEntity;
            indexToEntityMap[indexOfRemovedEntity] = entityOfLastElement;
            // Erase the entity from both maps
            entityToIndexMap.erase(entity);
            indexToEntityMap.erase(indexOfLastElement);
            --size;
            PRINT_COMPONENT_ARRAY_STATUS("After removing data from entity " + std::to_string(entity));
        }
References GLESC::ECS::ComponentArray< Component >::componentArray, D_ASSERT_TRUE, GLESC::ECS::ComponentArray< Component >::entityToIndexMap, GLESC::ECS::ComponentArray< Component >::hasComponent(), GLESC::ECS::ComponentArray< Component >::indexToEntityMap, GLESC::isIterable_v, PRINT_COMPONENT_ARRAY_STATUS, and GLESC::ECS::ComponentArray< Component >::size.
Referenced by GLESC::ECS::ComponentArray< Component >::entityDestroyed().
Member Data Documentation
componentArray
template<typename Component > std::array<Component, maxEntities> GLESC::ECS::ComponentArray< Component >::componentArray private
The packed array of components (of generic type T), set to a specified maximum amount, matching the maximum number of entities allowed to exist simultaneously, so that each entity has a unique spot.
Definition at line 184 of file ComponentArray.h.
Referenced by GLESC::ECS::ComponentArray< Component >::getComponent(), GLESC::ECS::ComponentArray< Component >::getData(), GLESC::ECS::ComponentArray< Component >::insertData(), GLESC::ECS::ComponentArray< Component >::printStatus(), and GLESC::ECS::ComponentArray< Component >::removeData().
entityToIndexMap
template<typename Component > std::unordered_map<EntityID, size_t> GLESC::ECS::ComponentArray< Component >::entityToIndexMap private
Map from an entity ID to an array index.
Definition at line 190 of file ComponentArray.h.
Referenced by GLESC::ECS::ComponentArray< Component >::entityDestroyed(), GLESC::ECS::ComponentArray< Component >::getComponent(), GLESC::ECS::ComponentArray< Component >::getData(), GLESC::ECS::ComponentArray< Component >::hasComponent(), GLESC::ECS::ComponentArray< Component >::insertData(), GLESC::ECS::ComponentArray< Component >::printStatus(), and GLESC::ECS::ComponentArray< Component >::removeData().
indexToEntityMap
template<typename Component > std::unordered_map<size_t, EntityID> GLESC::ECS::ComponentArray< Component >::indexToEntityMap private
Definition at line 191 of file ComponentArray.h.
Referenced by GLESC::ECS::ComponentArray< Component >::insertData(), and GLESC::ECS::ComponentArray< Component >::removeData().
size
template<typename Component > size_t GLESC::ECS::ComponentArray< Component >::size {} private
Total size of valid entries in the array.
Definition at line 197 of file ComponentArray.h.
{};
Referenced by GLESC::ECS::ComponentArray< Component >::getSize(), GLESC::ECS::ComponentArray< Component >::insertData(), GLESC::ECS::ComponentArray< Component >::printStatus(), and GLESC::ECS::ComponentArray< Component >::removeData().
The documentation for this class was generated from the following file:
ComponentArray.h