GLESC: GLESC::GAPI::VertexBuffer Class Reference
GLESC::GAPI::VertexBuffer Class Reference
#include <VertexBuffer.h>
Public Member Functions
VertexBuffer (const Void *data, Size count, Size elementSize, Enums::BufferUsages bufferUsage=Enums::BufferUsages::DynamicDraw)
~VertexBuffer ()
void bind () const
void destroy ()
UInt getBufferID () const
void unbind () const
Private Member Functions
void destroyOnce ()
This method destroys the vertex buffer object once. It is called from the destructor and the destroy method. If its called once the next time it will do nothing. This is to prevent double deletion. Enables the destruction of this object from the destroy method.
Private Attributes
bool objectAlive = true
UInt vertexBufferID {0}
Detailed Description
Definition at line 16 of file VertexBuffer.h.
Constructor & Destructor Documentation
VertexBuffer()
VertexBuffer::VertexBuffer (const Void * data, Size count, Size elementSize, Enums::BufferUsages bufferUsage = Enums::BufferUsages::DynamicDraw)
Definition at line 8 of file VertexBuffer.cpp.
{
    D_ASSERT_NOT_NULLPTR(data, "Data is null in VertexBuffer constructor");
    D_ASSERT_TRUE(elementSize > 0, "Size is 0 in VertexBuffer constructor");
    D_ASSERT_TRUE(count > 0, "Count is 0 in VertexBuffer constructor");
    getGAPI().genBuffers(1, vertexBufferID);
    this->bind();
    getGAPI().setBufferData(data, count, elementSize, Enums::BufferTypes::Vertex, bufferUsage);
}
References bind(), D_ASSERT_NOT_NULLPTR, D_ASSERT_TRUE, getGAPI(), GLESC::isIterable_v, and vertexBufferID.
~VertexBuffer()
VertexBuffer::~VertexBuffer ()
Definition at line 20 of file VertexBuffer.cpp.
{
    destroyOnce();
}
References destroyOnce().
Member Function Documentation
bind()
void VertexBuffer::bind () const
Definition at line 28 of file VertexBuffer.cpp.
{
    getGAPI().bindBuffer(Enums::BufferTypes::Vertex, vertexBufferID);
}
References getGAPI(), and vertexBufferID.
Referenced by VertexBuffer(), GLESC::GAPI::VertexArray::addBuffer(), and GLESC::GAPI::VertexInstanceBuffer::setupInstanceAttributes().
destroy()
void VertexBuffer::destroy ()
Definition at line 24 of file VertexBuffer.cpp.
{
    destroyOnce();
}
References destroyOnce().
destroyOnce()
void VertexBuffer::destroyOnce () private
This method destroys the vertex buffer object once. It is called from the destructor and the destroy method. If its called once the next time it will do nothing. This is to prevent double deletion. Enables the destruction of this object from the destroy method.
Definition at line 36 of file VertexBuffer.cpp.
{
    if (objectAlive) {
        getGAPI().deleteBuffer(vertexBufferID);
        objectAlive = false;
    }
    D_ASSERT_TRUE(!objectAlive, "Failed to destroy VertexBuffer");
}
References D_ASSERT_TRUE, getGAPI(), objectAlive, and vertexBufferID.
Referenced by ~VertexBuffer(), and destroy().
getBufferID()
UInt GLESC::GAPI::VertexBuffer::getBufferID () const inline
Definition at line 25 of file VertexBuffer.h.
{ return vertexBufferID; }
References vertexBufferID.
unbind()
void VertexBuffer::unbind () const
Definition at line 32 of file VertexBuffer.cpp.
{
    getGAPI().unbindBuffer(Enums::BufferTypes::Vertex);
}
References getGAPI().
Member Data Documentation
objectAlive
bool GLESC::GAPI::VertexBuffer::objectAlive = true private
Definition at line 43 of file VertexBuffer.h.
Referenced by destroyOnce().
vertexBufferID
UInt GLESC::GAPI::VertexBuffer::vertexBufferID {0} private
Definition at line 44 of file VertexBuffer.h.
{0};
Referenced by VertexBuffer(), bind(), destroyOnce(), and getBufferID().
The documentation for this class was generated from the following files:
VertexBuffer.h
VertexBuffer.cpp