GLESC: TerminalLogger Class Reference
TerminalLogger Class Reference
#include <TerminalLogger.h>
Public Member Functions
TerminalLogger ()
void error (const std::string &text) override
Display error messages Background – Red Text – Black Bold.
void importantInfo (const std::string &text) override
Display important information Background – White Text – Black.
void importantInfoBlue (const std::string &text) override
Display important information Background – Light Blue Text – Black.
void importantInfoPurple (const std::string &text) override
Display important information Background – Light Purple Text – Black.
void importantInfoWhite (const std::string &text) override
Display important information Background – White Text – Black.
void importantSuccess (const std::string &text) override
Display important success information.
void info (const std::string &text) override
Display basic information Background – Black Text – White.
void infoBlue (const std::string &text) override
Display basic information Background – Black Text – Light Blue.
void infoPurple (const std::string &text) override
Display basic information Background – Black Text – Light Purple.
void log (const std::string &text) override
Display log messages Background and text default.
void nonImportantInfo (const std::string &text) override
Display non important information Background – Black Text – Grey.
void success (const std::string &text) override
Display success information Background – Green Text – White Bold.
void warning (const std::string &text) override
Display warning messages Background – Black Text – Yellow.
Public Member Functions inherited from ILogger
virtual ~ILogger ()=default
Detailed Description
Definition at line 14 of file TerminalLogger.h.
Constructor & Destructor Documentation
TerminalLogger()
TerminalLogger::TerminalLogger () default
Member Function Documentation
error()
void TerminalLogger::error (const std::string & text) override virtual
Display error messages Background – Red Text – Black Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 20 of file TerminalLogger.cpp.
{
    std::cout << dye::black_on_red(text) << std::endl;
}
References text().
importantInfo()
void TerminalLogger::importantInfo (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 44 of file TerminalLogger.cpp.
{
    std::cout << dye::blue_on_grey(text) << std::endl;
}
References text().
importantInfoBlue()
void TerminalLogger::importantInfoBlue (const std::string & text) override virtual
Display important information Background – Light Blue Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 48 of file TerminalLogger.cpp.
{
    std::cout << dye::blue_on_light_blue(text) << std::endl;
}
References text().
importantInfoPurple()
void TerminalLogger::importantInfoPurple (const std::string & text) override virtual
Display important information Background – Light Purple Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 52 of file TerminalLogger.cpp.
{
    std::cout << dye::black_on_purple(text) << std::endl;
}
References text().
importantInfoWhite()
void TerminalLogger::importantInfoWhite (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 56 of file TerminalLogger.cpp.
{
    std::cout << dye::black_on_white(text) << std::endl;
}
References text().
importantSuccess()
void TerminalLogger::importantSuccess (const std::string & text) override virtual
Display important success information.
Parameters
text
Implements ILogger.
Definition at line 59 of file TerminalLogger.cpp.
{
    std::cout << dye::black_on_green(text) << std::endl;
}
References text().
info()
void TerminalLogger::info (const std::string & text) override virtual
Display basic information Background – Black Text – White.
Parameters
text printed text
Implements ILogger.
Definition at line 32 of file TerminalLogger.cpp.
{
    std::cout << dye::white(text) << std::endl;
}
References text().
infoBlue()
void TerminalLogger::infoBlue (const std::string & text) override virtual
Display basic information Background – Black Text – Light Blue.
Parameters
text printed text
Implements ILogger.
Definition at line 36 of file TerminalLogger.cpp.
{
    std::cout << dye::light_blue(text) << std::endl;
}
References text().
infoPurple()
void TerminalLogger::infoPurple (const std::string & text) override virtual
Display basic information Background – Black Text – Light Purple.
Parameters
text printed text
Implements ILogger.
Definition at line 40 of file TerminalLogger.cpp.
{
    std::cout << dye::light_purple(text) << std::endl;
}
References text().
log()
void TerminalLogger::log (const std::string & text) override virtual
Display log messages Background and text default.
Parameters
text
Implements ILogger.
Definition at line 16 of file TerminalLogger.cpp.
{
    std::cout << text << std::endl;
}
References text().
nonImportantInfo()
void TerminalLogger::nonImportantInfo (const std::string & text) override virtual
Display non important information Background – Black Text – Grey.
Parameters
text printed text
Implements ILogger.
Definition at line 28 of file TerminalLogger.cpp.
{
    std::cout << dye::grey(text) << std::endl;
}
References text().
success()
void TerminalLogger::success (const std::string & text) override virtual
Display success information Background – Green Text – White Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 62 of file TerminalLogger.cpp.
{
    std::cout << dye::green_on_black(text) << std::endl;
}
References text().
warning()
void TerminalLogger::warning (const std::string & text) override virtual
Display warning messages Background – Black Text – Yellow.
Parameters
text printed text
Implements ILogger.
Definition at line 24 of file TerminalLogger.cpp.
{
    std::cout << dye::black_on_yellow(text) << std::endl;
}
References text().
The documentation for this class was generated from the following files:
TerminalLogger.h
TerminalLogger.cpp