GLESC: GLESC::Stringer Class Reference
GLESC::Stringer Class Reference
A general class to convert objects to strings.
#include <Stringer.h>
Static Public Member Functions
static bool contains (const std::string &string, const std::string &substring)
Checks if a string contains a substring.
static std::string replace (const std::string &string, const std::string &stringToReplace, const std::string &replacement)
Converts a string to a number.
static void setFloatPrecision (int precision)
Sets the precision for floating point numbers.
static std::string strip (const std::string &string, const std::string &chars)
Strips the string of the characters in the chars string.
template<typename Type >
static std::string toString (const Type &value)
Converts an object to a string.
Static Private Member Functions
template<typename Iterable >
static std::string iterableToString (const Iterable &iterable)
Converts an iterable object to a string.
template<typename Type >
static std::string nonIterableToString (const Type &value)
Converts a non-iterable object to a string.
Static Private Attributes
static int floatPrecision = DEFAULT_FLOAT_PRECISION
Detailed Description
A general class to convert objects to strings.
Definition at line 49 of file Stringer.h.
Member Function Documentation
contains()
bool GLESC::Stringer::contains (const std::string & string, const std::string & substring) static
Checks if a string contains a substring.
Parameters
string - the string to check.
substring - the substring to check for.
Returns
true if the string contains the substring, false otherwise.
Definition at line 36 of file Stringer.cpp.
{
    return string.find(substring) != std::string::npos;
}
References GLESC::isIterable_v.
Referenced by HudLookAndFeel::validateFontName().
iterableToString()
template<typename Iterable > static std::string GLESC::Stringer::iterableToString (const Iterable & iterable) inline static private
Converts an iterable object to a string.
Parameters
iterable - the iterable object to convert.
Returns
the string representation of the iterable object.
Definition at line 168 of file Stringer.h.
{
            std::ostringstream oss;
            oss << "{";
            for (auto it = iterable.begin(); it != iterable.end(); ++it) {
                if (it != iterable.begin()) {
                    oss << ", ";
                }
                oss << toString(*it);
                if (isIterable_v<decltype(*it)>) {
                    oss << "\n";
                }
            }
            oss << "}";
            return oss.str();
        }
References GLESC::isIterable_v, and toString().
Referenced by toString().
nonIterableToString()
template<typename Type > static std::string GLESC::Stringer::nonIterableToString (const Type & value) inline static private
Converts a non-iterable object to a string.
Parameters
value - the object to convert.
Returns
the string representation of the object.
Definition at line 110 of file Stringer.h.
{
            std::ostringstream oss;
            if constexpr (std::is_pointer_v<Type>) {
                if constexpr (std::is_void_v<std::remove_const_t<std::remove_pointer_t<Type>>>) {
                    // Format void* pointers as hexadecimal memory addresses
                    oss << "void*: 0x" << std::hex << std::setw(sizeof(void*) * 2) << std::setfill('0')
                        << reinterpret_cast<uintptr_t>(value);
                }
                else {
                    return nonIterableToString(*value);
                }
            }
            else if constexpr (std::is_array_v<Type>) {
                oss << "[";
                for (size_t i = 0; i < std::extent_v<Type>; ++i) {
                    if (i != 0) {
                        oss << ", ";
                    }
                    oss << nonIterableToString(value[i]);
                }
                oss << "]";
            }
            else if constexpr (std::is_enum_v<Type>) {
                // Handle enums by casting to their underlying type
                oss << static_cast<std::underlying_type_t<Type>>(value);
            }
            else if constexpr (std::is_convertible_v<Type, std::string_view>) {
                oss << value;
            }
            else if constexpr (std::is_null_pointer_v<Type>) {
                oss << "nullptr";
            }
            else if constexpr (std::is_floating_point_v<Type>) {
                // Handle floating points with more precision
                oss << std::fixed << std::setprecision(floatPrecision)
                    << value;
            }
            else if constexpr (std::is_arithmetic_v<Type>) {
                // Directly use std::to_string for arithmetic types
                return std::to_string(value);
            }
            else if constexpr (hasToString_v<Type>) {
                // Handle types with a toString() method
                oss << value.toString();
            }
            else {
                // TODO: Handle other types
            }
            return oss.str();
        }
References floatPrecision, GLESC::isIterable_v, and nonIterableToString().
Referenced by nonIterableToString(), and toString().
replace()
std::string GLESC::Stringer::replace (const std::string & string, const std::string & stringToReplace, const std::string & replacement) static
Converts a string to a number.
Parameters
string - the string to convert.
Returns
the number representation of the string.
Definition at line 15 of file Stringer.cpp.
{
    std::string result = string;
    size_t pos = 0;
    while ((pos = result.find(stringToReplace, pos)) != std::string::npos) {
        result.replace(pos, stringToReplace.length(), replacement);
        pos += replacement.length();
    }
    return result;
}
References GLESC::isIterable_v.
Referenced by GLESC::GAPI::ShaderLoader::loadShader(), and GLESC::ECS::ECSCoordinator::printEntity().
setFloatPrecision()
static void GLESC::Stringer::setFloatPrecision (int precision) inline static
Sets the precision for floating point numbers.
Parameters
precision - the precision to set.
Definition at line 55 of file Stringer.h.
{
            floatPrecision = precision;
        }
References floatPrecision.
strip()
std::string GLESC::Stringer::strip (const std::string & string, const std::string & chars) static
Strips the string of the characters in the chars string.
Parameters
string The string to strip
chars The characters to strip from the string
Returns
The stripped string
Definition at line 26 of file Stringer.cpp.
{
    const std::string& result = string;
    size_t start = result.find_first_not_of(chars);
    if (start == std::string::npos) {
        return ""; // Return an empty string if all characters are to be stripped
    }
    size_t end = result.find_last_not_of(chars);
    return result.substr(start, end - start + 1);
}
References GLESC::isIterable_v.
Referenced by GLESC::ECS::EntityManager::destroyEntity(), GLESC::ECS::EntityManager::isEntityInstanced(), and GLESC::HUD::EntityListHUD::windowContent().
toString()
template<typename Type > static std::string GLESC::Stringer::toString (const Type & value) inline static
Converts an object to a string.
The object to convert can be iterable or non iterable. If it is iterable, the output will be a list separated by commas. If it is non iterable, the output will be the string representation of the object. If the object is a floating point number, the precision of the output will be either the default or the one set by setFloatPrecision. Once the object is converted, the precision will be reset to the default. The default precision is 6.
Parameters
value - the object to convert.
Returns
the string representation of the object.
Definition at line 69 of file Stringer.h.
{
            if constexpr (isIterable_v<Type> && !std::is_same_v<Type, std::string>) {
                return iterableToString(value);
            }
            else {
                return nonIterableToString(value);
            }
            floatPrecision = DEFAULT_FLOAT_PRECISION;
        }
References DEFAULT_FLOAT_PRECISION, floatPrecision, GLESC::isIterable_v, iterableToString(), and nonIterableToString().
Referenced by argsToString(), argsToString(), iterableToString(), GLESC::ECS::ECSCoordinator::printStatus(), GLESC::Engine::registerStats(), GLESC::StatsManager::registerStatSource(), GLESC::Render::Intensity< IntensityType >::toString(), GLESC::Render::ColorRgb::toString(), GLESC::Render::ColorRgba::toString(), GLESC::Render::ColorRgbNorm::toString(), and GLESC::Render::ColorRgbaNorm::toString().
Member Data Documentation
floatPrecision
int GLESC::Stringer::floatPrecision = DEFAULT_FLOAT_PRECISION static private
Definition at line 103 of file Stringer.h.
Referenced by nonIterableToString(), setFloatPrecision(), and toString().
The documentation for this class was generated from the following files:
Stringer.h
Stringer.cpp