GLESC: GLESC::Scene::Scene Class Reference
GLESC::Scene::Scene Class Reference abstract
Contains all the classes and functions related to the scene management. Any scene of the game should be derived from the Scene class.
#include <Scene.h>
Public Member Functions
Scene (WindowManager &windowManager, ECS::EntityFactory &entityFactory, Input::InputManager &inputManager, SceneManager &sceneManager, HUD::HUDManager &hudManager, EngineCamera &camera)
Constructor for the Scene class.
virtual ~Scene ()=default
virtual void destroy ()=0
Destroys the scene. Must be implemented by the derived class.
EngineCamera & getCamera ()
TimeMillis getSceneTimeMillis ()
Gets the scene time in milliseconds.
TimeSecondsUI getSceneTimeSeconds ()
Gets the scene time in seconds.
virtual void init ()=0
Initializes the scene. Must be implemented by the derived class.
bool isInitialized () const
Checks if the scene is initialized.
void setInitialized (bool initializedParam)
template<typename SceneType >
void switchScene ()
Switches to another scene.
virtual void update ()=0
Updates the scene. Must be implemented by the derived class.
Protected Member Functions
template<typename WindowType >
HUD::HUDManager::WindowID addWindow ()
Adds a window to the scene.
ECS::Entity createEntity ()
Creates an entity and adds it to the scene.
ECS::Entity createEntity (const std::string &entityName, const ECS::EntityMetadata &metadata={})
Creates an entity and adds it to the scene.
void destroyEntities ()
Destroys all entities in the scene.
void destroyEntity (const ECS::EntityID &entityID)
Destroys an entity by ID.
void destroyEntity (const std::string &entityName)
Destroys an entity by name.
void destroyWindows ()
Removes a window by ID.
ECS::Entity getEntity (const ECS::EntityID &entityID)
Gets an entity by ID.
ECS::Entity getEntity (const std::string &entityName)
Gets an entity by name.
std::vector< ECS::EntityID > & getSceneEntities ()
Gets the scene entities.
template<typename WindowType >
WindowType & getWindow (HUD::HUDManager::WindowID id)
Gets a window by ID.
Protected Attributes
ECS::EntityFactory & entityFactory
Input::InputManager & inputManager
WindowManager & windowManager
Private Attributes
EngineCamera & camera
HUD::HUDManager & hudManager
bool initialized = false
std::vector< ECS::EntityID > sceneEntities
SceneID sceneID {}
SceneManager & sceneManager
Timer sceneTimer
std::vector< std::unique_ptr< GLESC::InGameWindow > > sceneWindows
std::vector< HUD::HUDManager::WindowID > windowReferences
Detailed Description
Contains all the classes and functions related to the scene management. Any scene of the game should be derived from the Scene class.
Definition at line 45 of file Scene.h.
Constructor & Destructor Documentation
~Scene()
virtual GLESC::Scene::Scene::~Scene () virtual default
Scene()
GLESC::Scene::Scene::Scene (WindowManager & windowManager, ECS::EntityFactory & entityFactory, Input::InputManager & inputManager, SceneManager & sceneManager, HUD::HUDManager & hudManager, EngineCamera & camera) inline
Constructor for the Scene class.
Parameters
windowManager The window manager.
entityFactory The entity factory.
inputManager The input manager.
sceneManager The scene manager.
hudManager The HUD manager.
camera The camera.
Definition at line 58 of file Scene.h.
            : entityFactory(entityFactory),
              windowManager(windowManager),
              inputManager(inputManager),
              sceneManager(sceneManager),
              hudManager(hudManager),
              camera(camera) {
            sceneTimer.start();
        }
References sceneTimer, and GLESC::Timer::start().
Member Function Documentation
addWindow()
template<typename WindowType > HUD::HUDManager::WindowID GLESC::Scene::Scene::addWindow () inline protected
Adds a window to the scene.
Template Parameters
WindowType The type of the window to add.
Returns
The ID of the window.
Definition at line 206 of file Scene.h.
{
            D_ASSERT_TRUE((std::is_base_of_v<GLESC::InGameWindow, WindowType>),
                          "WindowType must be derived from InGameWindow");
            sceneWindows.push_back(std::make_unique<WindowType>());
            windowReferences.push_back(hudManager.addWindow(*sceneWindows.back()));
            return windowReferences.back();
        }
References GLESC::HUD::HUDManager::addWindow(), D_ASSERT_TRUE, hudManager, sceneWindows, and windowReferences.
createEntity() [1/2]
ECS::Entity GLESC::Scene::Scene::createEntity () inline protected
Creates an entity and adds it to the scene.
Creates entity with default name and metadata.
Stores the entity ID in the sceneEntities vector.
Returns
The created entity.
Definition at line 150 of file Scene.h.
{
            ECS::Entity entity = entityFactory.createEntity();
            sceneEntities.push_back(entity.getID());
            return entityFactory.getEntity(sceneEntities.back());
        }
References GLESC::ECS::EntityFactory::createEntity(), entityFactory, GLESC::ECS::EntityFactory::getEntity(), GLESC::isIterable_v, and sceneEntities.
Referenced by Default::init().
createEntity() [2/2]
ECS::Entity GLESC::Scene::Scene::createEntity (const std::string & entityName, const ECS::EntityMetadata & metadata = {}) inline protected
Creates an entity and adds it to the scene.
Stores the entity ID in the sceneEntities vector.
Parameters
entityName The name of the entity.
metadata The metadata of the entity.
Returns
The created entity.
Definition at line 138 of file Scene.h.
                                                                                                {}) {
            ECS::Entity entity = entityFactory.createEntity(entityName, metadata);
            sceneEntities.push_back(entity.getID());
            return entityFactory.getEntity(sceneEntities.back());
        }
destroy()
virtual void GLESC::Scene::Scene::destroy () pure virtual
Destroys the scene. Must be implemented by the derived class.
destroyEntities()
void GLESC::Scene::Scene::destroyEntities () inline protected
Destroys all entities in the scene.
Definition at line 239 of file Scene.h.
{
            for (auto& entity : getSceneEntities()) {
                entityFactory.getEntity(entity).destroy();
            }
            sceneEntities.clear();
        }
References GLESC::ECS::Entity::destroy(), entityFactory, GLESC::ECS::EntityFactory::getEntity(), getSceneEntities(), GLESC::isIterable_v, and sceneEntities.
destroyEntity() [1/2]
void GLESC::Scene::Scene::destroyEntity (const ECS::EntityID & entityID) inline protected
Destroys an entity by ID.
This will alert the ECSManager to destroy the entity through the entity object. Also erases the entity from the sceneEntities vector.
Parameters
entityID The ID of the entity.
Definition at line 193 of file Scene.h.
{
            auto entity = entityFactory.getEntity(entityID);
            entity.destroy();
            sceneEntities.erase(std::remove(sceneEntities.begin(), sceneEntities.end(), entityID),
                                sceneEntities.end());
        }
References GLESC::ECS::Entity::destroy(), entityFactory, GLESC::ECS::EntityFactory::getEntity(), GLESC::isIterable_v, and sceneEntities.
destroyEntity() [2/2]
void GLESC::Scene::Scene::destroyEntity (const std::string & entityName) inline protected
Destroys an entity by name.
This will alert the ECSManager to destroy the entity through the entity object. Also erases the entity from the sceneEntities vector.
Parameters
entityName The name of the entity.
Definition at line 180 of file Scene.h.
{
            auto entity = entityFactory.getEntity(entityName);
            entity.destroy();
            sceneEntities.erase(std::remove(sceneEntities.begin(), sceneEntities.end(), entity.getID()),
                                sceneEntities.end());
        }
References GLESC::ECS::Entity::destroy(), entityFactory, GLESC::ECS::EntityFactory::getEntity(), GLESC::isIterable_v, and sceneEntities.
destroyWindows()
void GLESC::Scene::Scene::destroyWindows () inline protected
Removes a window by ID.
Definition at line 228 of file Scene.h.
{
            for (auto& window : windowReferences) {
                hudManager.removeWindow(window);
            }
            windowReferences.clear();
            sceneWindows.clear();
        }
References hudManager, GLESC::HUD::HUDManager::removeWindow(), sceneWindows, and windowReferences.
getCamera()
EngineCamera & GLESC::Scene::Scene::getCamera () inline
Gets the camera object of the scene
Returns
The camera object
Definition at line 101 of file Scene.h.
{ return camera; }
References camera.
getEntity() [1/2]
ECS::Entity GLESC::Scene::Scene::getEntity (const ECS::EntityID & entityID) inline protected
Gets an entity by ID.
Parameters
entityID The ID of the entity.
Returns
The entity.
Definition at line 170 of file Scene.h.
{
            return entityFactory.getEntity(entityID);
        }
References entityFactory, GLESC::ECS::EntityFactory::getEntity(), and GLESC::isIterable_v.
getEntity() [2/2]
ECS::Entity GLESC::Scene::Scene::getEntity (const std::string & entityName) inline protected
Gets an entity by name.
Parameters
entityName The name of the entity.
Returns
The entity.
Definition at line 161 of file Scene.h.
{
            return entityFactory.getEntity(entityName);
        }
References entityFactory, GLESC::ECS::EntityFactory::getEntity(), and GLESC::isIterable_v.
getSceneEntities()
std::vector< ECS::EntityID > & GLESC::Scene::Scene::getSceneEntities () inline protected
Gets the scene entities.
Only returns the entities that are part of the scene.
Returns
The scene entities.
Definition at line 129 of file Scene.h.
{ return sceneEntities; }
References sceneEntities.
Referenced by destroyEntities().
getSceneTimeMillis()
TimeMillis GLESC::Scene::Scene::getSceneTimeMillis () inline
Gets the scene time in milliseconds.
Returns
The scene time in milliseconds.
Definition at line 116 of file Scene.h.
{ return sceneTimer.getCurrentTime(); }
References GLESC::Timer::getCurrentTime(), and sceneTimer.
Referenced by getSceneTimeSeconds().
getSceneTimeSeconds()
TimeSecondsUI GLESC::Scene::Scene::getSceneTimeSeconds () inline
Gets the scene time in seconds.
Returns
The scene time in seconds.
Definition at line 121 of file Scene.h.
{ return static_cast<TimeSecondsUI>(getSceneTimeMillis() / 1000.0); }
References getSceneTimeMillis().
getWindow()
template<typename WindowType > WindowType & GLESC::Scene::Scene::getWindow (HUD::HUDManager::WindowID id) inline protected
Gets a window by ID.
Template Parameters
WindowType The type of the window to get.
Parameters
id The ID of the window.
Returns
The window.
Definition at line 221 of file Scene.h.
{
            return dynamic_cast<WindowType&>(hudManager.getWindow(id));
        }
References GLESC::HUD::HUDManager::getWindow(), hudManager, and GLESC::isIterable_v.
init()
virtual void GLESC::Scene::Scene::init () pure virtual
Initializes the scene. Must be implemented by the derived class.
Implemented in Default.
isInitialized()
bool GLESC::Scene::Scene::isInitialized () const inline
Checks if the scene is initialized.
Returns
True if the scene is initialized, false otherwise.
Definition at line 83 of file Scene.h.
{ return initialized; }
References initialized.
setInitialized()
void GLESC::Scene::Scene::setInitialized (bool initializedParam) inline
Flags the scene as initialized
Parameters
initializedParam
Definition at line 77 of file Scene.h.
{ initialized = initializedParam; }
References initialized, and GLESC::isIterable_v.
switchScene()
template<typename SceneType > void GLESC::Scene::Scene::switchScene () inline
Switches to another scene.
Template Parameters
SceneType The type of the scene to switch to.
Definition at line 108 of file Scene.h.
{
            sceneManager.switchScene(SceneType::getSceneName());
        }
References sceneManager, and GLESC::Scene::SceneManager::switchScene().
update()
virtual void GLESC::Scene::Scene::update () pure virtual
Updates the scene. Must be implemented by the derived class.
Implemented in Default.
Member Data Documentation
camera
EngineCamera& GLESC::Scene::Scene::camera private
Definition at line 260 of file Scene.h.
Referenced by getCamera().
entityFactory
ECS::EntityFactory& GLESC::Scene::Scene::entityFactory protected
Definition at line 247 of file Scene.h.
Referenced by createEntity(), destroyEntities(), destroyEntity(), destroyEntity(), getEntity(), and getEntity().
hudManager
HUD::HUDManager& GLESC::Scene::Scene::hudManager private
Definition at line 252 of file Scene.h.
Referenced by addWindow(), destroyWindows(), and getWindow().
initialized
bool GLESC::Scene::Scene::initialized = false private
Definition at line 255 of file Scene.h.
Referenced by isInitialized(), and setInitialized().
inputManager
Input::InputManager& GLESC::Scene::Scene::inputManager protected
Definition at line 249 of file Scene.h.
sceneEntities
std::vector<ECS::EntityID> GLESC::Scene::Scene::sceneEntities private
Definition at line 256 of file Scene.h.
Referenced by createEntity(), destroyEntities(), destroyEntity(), destroyEntity(), and getSceneEntities().
sceneID
SceneID GLESC::Scene::Scene::sceneID {} private
Definition at line 258 of file Scene.h.
{};
sceneManager
SceneManager& GLESC::Scene::Scene::sceneManager private
Definition at line 257 of file Scene.h.
Referenced by switchScene().
sceneTimer
Timer GLESC::Scene::Scene::sceneTimer private
Definition at line 259 of file Scene.h.
Referenced by Scene(), and getSceneTimeMillis().
sceneWindows
std::vector<std::unique_ptr<GLESC::InGameWindow> > GLESC::Scene::Scene::sceneWindows private
Definition at line 254 of file Scene.h.
Referenced by addWindow(), and destroyWindows().
windowManager
WindowManager& GLESC::Scene::Scene::windowManager protected
Definition at line 248 of file Scene.h.
windowReferences
std::vector<HUD::HUDManager::WindowID> GLESC::Scene::Scene::windowReferences private
Definition at line 253 of file Scene.h.
Referenced by addWindow(), and destroyWindows().
The documentation for this class was generated from the following file:
Scene.h