GLESC: ILogger Class Reference
ILogger Class Reference abstract
#include <ILogger.h>
Public Member Functions
virtual ~ILogger ()=default
virtual void error (const std::string &text)=0
Display error messages Background – Red Text – Black Bold.
virtual void importantInfo (const std::string &text)=0
Display important information Background – White Text – Black.
virtual void importantInfoBlue (const std::string &text)=0
Display important information Background – Light Blue Text – Black.
virtual void importantInfoPurple (const std::string &text)=0
Display important information Background – Light Purple Text – Black.
virtual void importantInfoWhite (const std::string &text)=0
Display important information Background – White Text – Black.
virtual void importantSuccess (const std::string &text)=0
Display important success information.
virtual void info (const std::string &text)=0
Display basic information Background – Black Text – White.
virtual void infoBlue (const std::string &text)=0
Display basic information Background – Black Text – Light Blue.
virtual void infoPurple (const std::string &text)=0
Display basic information Background – Black Text – Light Purple.
virtual void log (const std::string &text)=0
Display log messages Background and text default.
virtual void nonImportantInfo (const std::string &text)=0
Display non important information Background – Black Text – Grey.
virtual void success (const std::string &text)=0
Display success information Background – Green Text – White Bold.
virtual void warning (const std::string &text)=0
Display warning messages Background – Black Text – Yellow.
Detailed Description
Definition at line 14 of file ILogger.h.
Constructor & Destructor Documentation
~ILogger()
virtual ILogger::~ILogger () virtual default
Member Function Documentation
error()
virtual void ILogger::error (const std::string & text) pure virtual
Display error messages Background – Red Text – Black Bold.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::error().
importantInfo()
virtual void ILogger::importantInfo (const std::string & text) pure virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::importantInfo().
importantInfoBlue()
virtual void ILogger::importantInfoBlue (const std::string & text) pure virtual
Display important information Background – Light Blue Text – Black.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::importantInfoBlue().
importantInfoPurple()
virtual void ILogger::importantInfoPurple (const std::string & text) pure virtual
Display important information Background – Light Purple Text – Black.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::importantInfoPurple().
importantInfoWhite()
virtual void ILogger::importantInfoWhite (const std::string & text) pure virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::importantInfoWhite().
importantSuccess()
virtual void ILogger::importantSuccess (const std::string & text) pure virtual
Display important success information.
Parameters
text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::importantSuccess().
info()
virtual void ILogger::info (const std::string & text) pure virtual
Display basic information Background – Black Text – White.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::info().
infoBlue()
virtual void ILogger::infoBlue (const std::string & text) pure virtual
Display basic information Background – Black Text – Light Blue.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::infoBlue().
infoPurple()
virtual void ILogger::infoPurple (const std::string & text) pure virtual
Display basic information Background – Black Text – Light Purple.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::infoPurple().
log()
virtual void ILogger::log (const std::string & text) pure virtual
Display log messages Background and text default.
Parameters
text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::log().
nonImportantInfo()
virtual void ILogger::nonImportantInfo (const std::string & text) pure virtual
Display non important information Background – Black Text – Grey.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::nonImportantInfo().
success()
virtual void ILogger::success (const std::string & text) pure virtual
Display success information Background – Green Text – White Bold.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::success().
warning()
virtual void ILogger::warning (const std::string & text) pure virtual
Display warning messages Background – Black Text – Yellow.
Parameters
text printed text
Implemented in FileLogger, TerminalLogger, and GLESC::Logger.
Referenced by GLESC::Logger::warning().
The documentation for this class was generated from the following file:
ILogger.h