GLESC: GLESC::ECS::SunSystem Class Reference
GLESC::ECS::SunSystem Class Reference
#include <SunSystem.h>
Public Member Functions
SunSystem (ECSCoordinator &ecs, Render::Renderer &renderer)
void update () override
Updates the system.
Public Member Functions inherited from GLESC::ECS::System
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
Private Attributes
Render::Renderer & renderer
std::set< SunComponent * > sunCache
Additional Inherited Members
Protected Member Functions inherited from GLESC::ECS::System
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes inherited from GLESC::ECS::System
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Detailed Description
Definition at line 16 of file SunSystem.h.
Constructor & Destructor Documentation
SunSystem()
GLESC::ECS::SunSystem::SunSystem (ECSCoordinator & ecs, Render::Renderer & renderer) explicit
Definition at line 17 of file SunSystem.cpp.
                                                                      :
        System(ecs, "SunSystem"), renderer(renderer) {
        addComponentRequirement<SunComponent>();
        addComponentRequirement<TransformComponent>();
    };
References GLESC::isIterable_v.
Member Function Documentation
update()
void GLESC::ECS::SunSystem::update () override virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implements GLESC::ECS::System.
Definition at line 23 of file SunSystem.cpp.
{
        const std::set<EntityID>& entities = getAssociatedEntities();
        D_ASSERT_TRUE(entities.size() <= 1, "For now, only one sun is supported.");
        if (renderer.hasRenderBeenCalledThisFrame())
            for (auto& entity : entities) {
                auto& sun = getComponent<SunComponent>(entity);
                auto& transform = getComponent<TransformComponent>(entity);
                renderer.setSun(sun.sun, sun.globalAmbientLight, transform.transform);
                HudItemsManager::addItem(HudItemType::SUN, transform.transform.getPosition());
            }
    }
References HudItemsManager::addItem(), D_ASSERT_TRUE, entities, GLESC::ECS::System::getAssociatedEntities(), GLESC::Render::Renderer::hasRenderBeenCalledThisFrame(), GLESC::isIterable_v, renderer, GLESC::Render::Renderer::setSun(), and SUN.
Member Data Documentation
renderer
Render::Renderer& GLESC::ECS::SunSystem::renderer private
Definition at line 23 of file SunSystem.h.
Referenced by update().
sunCache
std::set<SunComponent*> GLESC::ECS::SunSystem::sunCache private
Definition at line 22 of file SunSystem.h.
The documentation for this class was generated from the following files:
SunSystem.h
SunSystem.cpp