GLESC: GLESC::ECS::System Class Reference
GLESC::ECS::System Class Reference abstract
#include <System.h>
Public Member Functions
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
virtual void update ()=0
Updates the system.
Protected Member Functions
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Private Attributes
ECSCoordinator & ecs
Reference to the ECSCoordinator.
SystemName name
Easy access to the name of the system.
Friends
class Entity
Detailed Description
Class that must be inherited by all systems in the engine. This helps with the access to the entities that are related with the system and facilitates the assignment of component requirements.
Definition at line 21 of file System.h.
Constructor & Destructor Documentation
System()
System::System (ECSCoordinator & ecs, const SystemName & name) explicit
Constructs a system with a name and a reference to the ECS coordinator.
Parameters
ecs The ECS coordinator
name The name of the system
Definition at line 6 of file System.cpp.
                                                          : ecs(ecs), name(name) {
    ecs.registerSystem(name);
}
References ecs, name, and GLESC::ECS::ECSCoordinator::registerSystem().
~System()
virtual GLESC::ECS::System::~System () virtual default
Member Function Documentation
addComponentRequirement()
template<class Component > void GLESC::ECS::System::addComponentRequirement () inline
Adds a component requirement to the system.
The component requirement makes so that only entities that have the required component are considered associated with the system
Template Parameters
Component The type of the component
Definition at line 41 of file System.h.
{
            ecs.addComponentRequirementToSystem<Component>(name);
        }
References GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem(), ecs, GLESC::isIterable_v, and name.
getAllEntities()
std::unordered_map< EntityName, EntityID > System::getAllEntities () const
Gets all the entities in the ECS.
In case the system needs to access all the entities in the ECS
Returns
A map of entity names and IDs
Definition at line 14 of file System.cpp.
{
    return ecs.getAllEntities();
}
References ecs, and GLESC::ECS::ECSCoordinator::getAllEntities().
getAssociatedEntities()
const std::set< EntityID > & System::getAssociatedEntities () const
Gets the entities associated with the system.
The entities are the ones that have all the required components
Returns
A set of entity IDs
Definition at line 10 of file System.cpp.
{
    return ecs.getAssociatedEntities(name);
}
References ecs, GLESC::ECS::ECSCoordinator::getAssociatedEntities(), and name.
Referenced by GLESC::ECS::CameraSystem::update(), GLESC::ECS::DebugInfoSystem::update(), GLESC::ECS::FogSystem::update(), GLESC::ECS::InputSystem::update(), GLESC::ECS::LightSystem::update(), GLESC::ECS::PhysicsCollisionSystem::update(), GLESC::ECS::PhysicsSystem::update(), GLESC::ECS::RenderSystem::update(), GLESC::ECS::SunSystem::update(), and GLESC::ECS::TransformSystem::update().
getComponent()
template<class Component > Component & GLESC::ECS::System::getComponent (EntityID entityId) inline protected
Gets the component of an entity.
Template Parameters
Component The type of the component
Parameters
entityId The ID of the entity
Returns
A reference to the component
Definition at line 102 of file System.h.
{
            return ecs.getComponent<Component>(entityId);
        }
References ecs, GLESC::ECS::ECSCoordinator::getComponent(), and GLESC::isIterable_v.
getComponents()
std::vector< IComponent * > System::getComponents (EntityID entityId) const
Gets the components of an entity.
This method is useful when the system needs to access the components of an entity
Parameters
entityId The ID of the entity
Returns
A vector of pointers to the components
Definition at line 18 of file System.cpp.
{
    return ecs.getComponents(entityId);
}
References ecs, GLESC::ECS::ECSCoordinator::getComponents(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::DebugInfoSystem::setEntityData().
getEntity()
EntityID System::getEntity (const EntityName & entityName) const
Gets the ID of an entity.
Parameters
entityName The name of the entity
Returns
The ID of the entity
Definition at line 26 of file System.cpp.
{
    return ecs.getEntityID(entityName);
}
References ecs, GLESC::ECS::ECSCoordinator::getEntityID(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::DebugInfoSystem::setEntityData().
getEntityMetadata()
const EntityMetadata & System::getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
Parameters
entityId The ID of the entity
Returns
The metadata of the entity
Definition at line 30 of file System.cpp.
{
    return ecs.getEntityMetadata(entityId);
}
References ecs, GLESC::ECS::ECSCoordinator::getEntityMetadata(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::DebugInfoSystem::update().
getEntityName()
const EntityName & System::getEntityName (EntityID entityId) const
Gets the name of an entity.
Parameters
entityId The ID of the entity
Returns
The name of the entity
Definition at line 22 of file System.cpp.
{
    return ecs.getEntityName(entityId);
}
References ecs, GLESC::ECS::ECSCoordinator::getEntityName(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::DebugInfoSystem::update(), GLESC::ECS::PhysicsCollisionSystem::update(), GLESC::ECS::RenderSystem::update(), and GLESC::ECS::TransformSystem::update().
update()
virtual void GLESC::ECS::System::update () pure virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implemented in GLESC::ECS::CameraSystem, GLESC::ECS::DebugInfoSystem, GLESC::ECS::FogSystem, GLESC::ECS::InputSystem, GLESC::ECS::LightSystem, GLESC::ECS::PhysicsCollisionSystem, GLESC::ECS::PhysicsSystem, GLESC::ECS::RenderSystem, GLESC::ECS::SunSystem, and GLESC::ECS::TransformSystem.
Friends And Related Symbol Documentation
Entity
friend class Entity friend
Definition at line 22 of file System.h.
Member Data Documentation
ecs
ECSCoordinator& GLESC::ECS::System::ecs private
Reference to the ECSCoordinator.
Definition at line 115 of file System.h.
Referenced by System(), addComponentRequirement(), getAllEntities(), getAssociatedEntities(), getComponent(), getComponents(), getEntity(), getEntityMetadata(), and getEntityName().
name
SystemName GLESC::ECS::System::name private
Easy access to the name of the system.
Definition at line 119 of file System.h.
Referenced by System(), addComponentRequirement(), getAssociatedEntities(), and GLESC::ECS::DebugInfoSystem::setEntityData().
nullEntity
EntityID GLESC::ECS::System::nullEntity = EntityManager::nullEntity protected
Easy access to the value of nullEntity.
Definition at line 109 of file System.h.
The documentation for this class was generated from the following files:
System.h
System.cpp