GLESC: GLESC::ECS::EntityFactory Class Reference
GLESC::ECS::EntityFactory Class Reference
The EntityFactory class is responsible for creating entity objects, this helps avoid the need to pass the ECSManager to the entity constructor every time an entity is created. Also, if the entity needs more complex creation logic, it can be encapsulated in this class.
#include <EntityFactory.h>
Public Member Functions
EntityFactory (ECSCoordinator &ecs)
Entity createEntity ()
Creates an entity with a default name and no metadata.
Entity createEntity (const EntityName &name, const EntityMetadata &metadata)
Creates an entity with a name and metadata.
Entity getEntity (const EntityID &id)
Gets an entity by its ID.
Entity getEntity (const EntityName &name)
Gets an entity by its name.
std::optional< Entity > tryGetEntity (const EntityName &name)
Tries to get an entity by its name.
Private Attributes
ECSCoordinator & ecs
Detailed Description
The EntityFactory class is responsible for creating entity objects, this helps avoid the need to pass the ECSManager to the entity constructor every time an entity is created. Also, if the entity needs more complex creation logic, it can be encapsulated in this class.
Definition at line 23 of file EntityFactory.h.
Constructor & Destructor Documentation
EntityFactory()
GLESC::ECS::EntityFactory::EntityFactory (ECSCoordinator & ecs) inline explicit
Definition at line 25 of file EntityFactory.h.
: ecs(ecs) {}
Member Function Documentation
createEntity() [1/2]
Entity GLESC::ECS::EntityFactory::createEntity ()
Creates an entity with a default name and no metadata.
The entity is returned as value, because is just a wrapper around an ID
Returns
The created entity
Definition at line 17 of file EntityFactory.cpp.
{
        return Entity(ecs);
    }
References ecs.
createEntity() [2/2]
Entity GLESC::ECS::EntityFactory::createEntity (const EntityName & name, const EntityMetadata & metadata)
Creates an entity with a name and metadata.
The entity is returned as value, because is just a wrapper around an ID
Parameters
name The name of the entity
metadata The metadata of the entity
Returns
The created entity
Definition at line 13 of file EntityFactory.cpp.
{
        return Entity(name, metadata, ecs);
    }
References ecs, and GLESC::isIterable_v.
Referenced by GLESC::Engine::createEngineEntities(), and GLESC::Scene::Scene::createEntity().
getEntity() [1/2]
Entity GLESC::ECS::EntityFactory::getEntity (const EntityID & id)
Gets an entity by its ID.
The entity is returned as value, because is just a wrapper around an ID
Parameters
id The ID of the entity
Returns
The entity
Definition at line 31 of file EntityFactory.cpp.
{
        return Entity(id, ecs);
    }
References ecs.
getEntity() [2/2]
Entity GLESC::ECS::EntityFactory::getEntity (const EntityName & name)
Gets an entity by its name.
The entity is returned as value, because is just a wrapper around an ID
Parameters
name The name of the entity
Returns
The entity
Definition at line 27 of file EntityFactory.cpp.
{
        return Entity(ecs.getEntityID(name), ecs);
    }
References ecs, and GLESC::ECS::ECSCoordinator::getEntityID().
Referenced by GLESC::Scene::Scene::createEntity(), GLESC::Scene::Scene::destroyEntities(), GLESC::Scene::Scene::destroyEntity(), GLESC::Scene::Scene::destroyEntity(), GLESC::Scene::Scene::getEntity(), and GLESC::Scene::Scene::getEntity().
tryGetEntity()
std::optional< Entity > GLESC::ECS::EntityFactory::tryGetEntity (const EntityName & name)
Tries to get an entity by its name.
Parameters
name The name of the entity
Returns
The entity if it exists, otherwise std::nullopt
Definition at line 21 of file EntityFactory.cpp.
{
        if (ecs.tryGetEntityID(name) == EntityManager::nullEntity)
            return std::nullopt;
        return Entity(ecs.tryGetEntityID(name), ecs);
    }
References ecs, GLESC::ECS::EntityManager::nullEntity, and GLESC::ECS::ECSCoordinator::tryGetEntityID().
Member Data Documentation
ecs
ECSCoordinator& GLESC::ECS::EntityFactory::ecs private
Definition at line 66 of file EntityFactory.h.
Referenced by createEntity(), createEntity(), getEntity(), getEntity(), and tryGetEntity().
The documentation for this class was generated from the following files:
EntityFactory.h
EntityFactory.cpp