GLESC: GLESC::Console Class Reference
GLESC::Console Class Reference
Class that encapsulates the logic of the console.
#include <Console.h>
Static Public Member Functions
static void error (const std::string &message)
static const std::vector< LogEntry > & GetMessages ()
static void log (const std::string &message)
static void warn (const std::string &message)
Static Private Member Functions
static void addMessage (const std::string &message, LogLevel level)
Static Private Attributes
static std::unordered_map< std::string, size_t > messageIndices = {}
static std::vector< LogEntry > messages = {}
static std::mutex mutex = {}
Detailed Description
Class that encapsulates the logic of the console.
Allows logging messages with different levels of importance. Also, handles messages so that repeated messages are not displayed multiple times but instead a counter is shown.
Definition at line 35 of file Console.h.
Member Function Documentation
addMessage()
void Console::addMessage (const std::string & message, LogLevel level) static private
Definition at line 22 of file Console.cpp.
{
    std::lock_guard lock(mutex);
    auto it = messageIndices.find(message);
    if (it != messageIndices.end()) {
        messages[it->second].count++;
    }
    else {
        messageIndices[message] = messages.size();
        messages.push_back({message, 1, level});
    }
}
References GLESC::isIterable_v, messageIndices, messages, and mutex.
Referenced by error(), log(), and warn().
error()
static void GLESC::Console::error (const std::string & message) inline static
Definition at line 40 of file Console.h.
{ addMessage(message, LogLevel::Error); }
References addMessage(), and GLESC::Error.
Referenced by GLESC::Engine::update().
GetMessages()
static const std::vector< LogEntry > & GLESC::Console::GetMessages () inline static
Definition at line 41 of file Console.h.
{ return messages; }
References messages.
Referenced by GLESC::HUD::DebugConsoleHUD::windowContent().
log()
static void GLESC::Console::log (const std::string & message) inline static
Definition at line 38 of file Console.h.
{ addMessage(message, LogLevel::Info); }
References addMessage(), and GLESC::Info.
Referenced by GLESC::InGameWindow::render(), and GLESC::Engine::update().
warn()
static void GLESC::Console::warn (const std::string & message) inline static
Definition at line 39 of file Console.h.
{ addMessage(message, LogLevel::Warning); }
References addMessage(), and GLESC::Warning.
Referenced by GLESC::Render::Renderer::sendMeshData(), and GLESC::Engine::update().
Member Data Documentation
messageIndices
std::unordered_map< std::string, size_t > Console::messageIndices = {} static private
Definition at line 52 of file Console.h.
Referenced by addMessage().
messages
std::vector< LogEntry > Console::messages = {} static private
Definition at line 51 of file Console.h.
Referenced by addMessage(), and GetMessages().
mutex
std::mutex Console::mutex = {} static private
Definition at line 53 of file Console.h.
Referenced by addMessage().
The documentation for this class was generated from the following files:
Console.h
Console.cpp