GLESC: GLESC::Math::BoundingVolume Class Reference
GLESC::Math::BoundingVolume Class Reference
A bounding volume is a geometric shape that encloses a set of points.
#include <BoundingVolume.h>
Classes
struct AABB
The axis-aligned bounding box of the bounding volume.
Public Member Functions
BoundingVolume ()=default
Construct a new Bounding Volume object.
BoundingVolume (const Vec3F &min, const Vec3F &max)
Construct a new Bounding Volume object.
AABB & getBoundingBox ()
Get the bounding box of the bounding volume.
const AABB & getBoundingBox () const
Get the const bounding box of the bounding volume.
const Vec3F & getMax () const
Get the maximum point of the bounding volume.
const Vec3F & getMin () const
Get the minimum point of the bounding volume.
const AABB & getVolume () const
Get the volume of the bounding volume.
bool hasInside (const Vec3F &point) const
Checks if the bounding volume contains the given point.
float intersectionVolume (const BoundingVolume &other) const
Get the intersection volume of the bounding volume with another bounding volume.
bool intersects (const BoundingVolume &other) const
Checks if the bounding volume intersects with another bounding volume.
void setVolume (const Vec3F &min, const Vec3F &max)
Set the volume of the bounding volume.
void updateBoundingBox (const void *data, unsigned int size, unsigned int stride, unsigned int offset)
Updates the bounding volume to fit the points it encloses.
Static Public Member Functions
static BoundingVolume createFromVulume (float width, float height, float depth)
Create a bounding volume from a volume.
Private Member Functions
void buildBoundingVolume (const Vec3F &minVec, const Vec3F &maxVec)
Builds the bounding volume from the minimum and maximum points.
Private Attributes
AABB boundingBox
The bounding box of the bounding volume.
Detailed Description
A bounding volume is a geometric shape that encloses a set of points.
This class updates the bounding cuboid to fit the points it encloses.
Definition at line 18 of file BoundingVolume.h.
Class Documentation
GLESC::Math::BoundingVolume::AABB
struct GLESC::Math::BoundingVolume::AABB
The axis-aligned bounding box of the bounding volume.
AABB is a box aligned with the axes of the coordinate space. It is a very simple shape that can be used to enclose other shapes. It's simpicity makes operations like intersection and containment very fast. [https://gdbooks.gitbooks.io/3dcollisions/content/Chapter1/aabb.html]
Definition at line 27 of file BoundingVolume.h.
Class Members
Vec3F max {1, 1, 1}
Vec3F min {-1, -1, -1}
Constructor & Destructor Documentation
BoundingVolume() [1/2]
GLESC::Math::BoundingVolume::BoundingVolume () default
Construct a new Bounding Volume object.
The default bounding volume is a unit cube ([-1, -1, -1], [1, 1, 1]).
BoundingVolume() [2/2]
GLESC::Math::BoundingVolume::BoundingVolume (const Vec3F & min, const Vec3F & max)
Construct a new Bounding Volume object.
Parameters
min The minimum point of the bounding volume
max The maximum point of the bounding volume
Definition at line 13 of file BoundingVolume.cpp.
{
    buildBoundingVolume(min, max);
}
References buildBoundingVolume(), GLESC::Math::max(), and GLESC::Math::min().
Member Function Documentation
buildBoundingVolume()
void GLESC::Math::BoundingVolume::buildBoundingVolume (const Vec3F & minVec, const Vec3F & maxVec) private
Builds the bounding volume from the minimum and maximum points.
Parameters
minVec The minimum point of the bounding volume
maxVec The maximum point of the bounding volume
Definition at line 116 of file BoundingVolume.cpp.
{
    boundingBox.min = minVec;
    boundingBox.max = maxVec;
}
References GLESC::isIterable_v.
Referenced by BoundingVolume().
createFromVulume()
GLESC::Math::BoundingVolume GLESC::Math::BoundingVolume::createFromVulume (float width, float height, float depth) static
Create a bounding volume from a volume.
Parameters
width The width of the volume
height The height of the volume
depth The depth of the volume
Returns
The bounding volume created from the volume
Definition at line 109 of file BoundingVolume.cpp.
{
    D_ASSERT_GREATER(width, 0, "Width must be greater than 0");
    D_ASSERT_GREATER(height, 0, "Height must be greater than 0");
    D_ASSERT_GREATER(depth, 0, "Depth must be greater than 0");
    return {Vec3F(-width / 2, -height / 2, -depth / 2), Vec3F(width / 2, height / 2, depth / 2)};
}
References D_ASSERT_GREATER, and GLESC::isIterable_v.
getBoundingBox() [1/2]
AABB & GLESC::Math::BoundingVolume::getBoundingBox () inline
Get the bounding box of the bounding volume.
Returns
The bounding box of the bounding volume
Definition at line 98 of file BoundingVolume.h.
{ return boundingBox; }
References boundingBox.
getBoundingBox() [2/2]
const AABB & GLESC::Math::BoundingVolume::getBoundingBox () const inline
Get the const bounding box of the bounding volume.
Returns
The bounding box of the bounding volume
Definition at line 92 of file BoundingVolume.h.
{ return boundingBox; }
References boundingBox.
Referenced by GLESC::Physics::Collider::getDebuggingValues().
getMax()
const Vec3F & GLESC::Math::BoundingVolume::getMax () const inline
Get the maximum point of the bounding volume.
Returns
The maximum point of the bounding volume
Definition at line 110 of file BoundingVolume.h.
{ return boundingBox.max; }
References boundingBox, and GLESC::Math::BoundingVolume::AABB::max.
getMin()
const Vec3F & GLESC::Math::BoundingVolume::getMin () const inline
Get the minimum point of the bounding volume.
Returns
The minimum point of the bounding volume
Definition at line 104 of file BoundingVolume.h.
{ return boundingBox.min; }
References boundingBox, and GLESC::Math::BoundingVolume::AABB::min.
getVolume()
const AABB & GLESC::Math::BoundingVolume::getVolume () const inline
Get the volume of the bounding volume.
Returns
The volume of the bounding volume
Definition at line 55 of file BoundingVolume.h.
{ return boundingBox; }
References boundingBox.
Referenced by GLESC::Transform::Transformer::transformBoundingVolume().
hasInside()
bool GLESC::Math::BoundingVolume::hasInside (const Vec3F & point) const
Checks if the bounding volume contains the given point.
Parameters
point The point to check
Returns
True if the bounding volume contains the point, false otherwise
Definition at line 22 of file BoundingVolume.cpp.
{
    return point.getX() >= boundingBox.min.getX() && point.getX() <= boundingBox.max.getX() &&
        point.getY() >= boundingBox.min.getY() && point.getY() <= boundingBox.max.getY() &&
        point.getZ() >= boundingBox.min.getZ() && point.getZ() <= boundingBox.max.getZ();
}
References GLESC::Math::Vector< Type, N >::getX(), GLESC::Math::Vector< Type, N >::getY(), and GLESC::Math::Vector< Type, N >::getZ().
intersectionVolume()
float GLESC::Math::BoundingVolume::intersectionVolume (const BoundingVolume & other) const
Get the intersection volume of the bounding volume with another bounding volume.
Parameters
other The other bounding volume
Returns
The intersection volume of the bounding volume with the other bounding volume
Definition at line 28 of file BoundingVolume.cpp.
{
    float depthX = 0, depthY = 0, depthZ = 0;
    // Check X axis
    if (boundingBox.max.getX() > other.boundingBox.min.getX() &&
        boundingBox.min.getX() < other.boundingBox.max.getX()) {
        depthX = std::min(boundingBox.max.getX(), other.boundingBox.max.getX()) -
            std::max(boundingBox.min.getX(), other.boundingBox.min.getX());
    }
    // Check Y axis
    if (boundingBox.max.getY() > other.boundingBox.min.getY() &&
        boundingBox.min.getY() < other.boundingBox.max.getY()) {
        depthY = std::min(boundingBox.max.getY(), other.boundingBox.max.getY()) -
            std::max(boundingBox.min.getY(), other.boundingBox.min.getY());
    }
    // Check Z axis
    if (boundingBox.max.getZ() > other.boundingBox.min.getZ() &&
        boundingBox.min.getZ() < other.boundingBox.max.getZ()) {
        depthZ = std::min(boundingBox.max.getZ(), other.boundingBox.max.getZ()) -
            std::max(boundingBox.min.getZ(), other.boundingBox.min.getZ());
    }
    // If no overlap in any axis, return 0
    if (depthX <= 0 || depthY <= 0 || depthZ <= 0) {
        return 0.0f;
    }
    // Return the volume of the intersection
    return depthX * depthY * depthZ;
}
References GLESC::isIterable_v.
intersects()
bool GLESC::Math::BoundingVolume::intersects (const BoundingVolume & other) const
Checks if the bounding volume intersects with another bounding volume.
Parameters
other The other bounding volume
Returns
True if the bounding volume intersects with the other bounding volume, false otherwise
Definition at line 62 of file BoundingVolume.cpp.
{
    if (boundingBox.min.getX() >= other.boundingBox.max.getX() ||
        boundingBox.max.getX() <= other.boundingBox.min.getX())
        return false;
    if (boundingBox.min.getY() >= other.boundingBox.max.getY() ||
        boundingBox.max.getY() <= other.boundingBox.min.getY())
        return false;
    if (boundingBox.min.getZ() >= other.boundingBox.max.getZ() ||
        boundingBox.max.getZ() <= other.boundingBox.min.getZ())
        return false;
    return true;
}
References GLESC::isIterable_v.
setVolume()
void GLESC::Math::BoundingVolume::setVolume (const Vec3F & min, const Vec3F & max)
Set the volume of the bounding volume.
Parameters
min The minimum point of the bounding volume
max The maximum point of the bounding volume
Definition at line 17 of file BoundingVolume.cpp.
{
    buildBoundingVolume(min, max);
}
References GLESC::Math::max(), and GLESC::Math::min().
updateBoundingBox()
void GLESC::Math::BoundingVolume::updateBoundingBox (const void * data, unsigned int size, unsigned int stride, unsigned int offset)
Updates the bounding volume to fit the points it encloses.
Parameters
data The data to update the bounding volume with
size The size of the data
stride The stride (size of each vertex) of the data
offset The offset (position of the position attribute) of the data
Definition at line 75 of file BoundingVolume.cpp.
{
    // Initialize bounds
    Vec3F minVec(std::numeric_limits<float>::max(), std::numeric_limits<float>::max(),
                 std::numeric_limits<float>::max());
    Vec3F maxVec(std::numeric_limits<float>::lowest(), std::numeric_limits<float>::lowest(),
                 std::numeric_limits<float>::lowest());
    // Iterate through the vertices to find the bounding box
    for (unsigned int i = 0; i < size; i += stride) {
        float x = *reinterpret_cast<const float*>(static_cast<const char*>(data) + i + offset);
        float y = *reinterpret_cast<const float*>(static_cast<const char*>(data) + i + offset + sizeof(
            float));
        float z = *reinterpret_cast<const float*>(static_cast<const char*>(data) + i + offset + 2 * sizeof(
            float));
        minVec.x() = std::min(minVec.x(), x);
        minVec.y() = std::min(minVec.y(), y);
        minVec.z() = std::min(minVec.z(), z);
        maxVec.x() = std::max(maxVec.x(), x);
        maxVec.y() = std::max(maxVec.y(), y);
        maxVec.z() = std::max(maxVec.z(), z);
    }
    // Check if the bounding volume is valid (not empty)
    if (minVec.x() >= maxVec.x() || minVec.y() >= maxVec.y() || minVec.z() >= maxVec.z()) {
        return;
    }
    // Build the bounding volume
    buildBoundingVolume(minVec, maxVec);
}
References GLESC::isIterable_v.
Referenced by GLESC::Render::Mesh< VertexT >::finishBuilding().
Member Data Documentation
boundingBox
AABB GLESC::Math::BoundingVolume::boundingBox private
The bounding box of the bounding volume.
Definition at line 132 of file BoundingVolume.h.
Referenced by getBoundingBox(), getBoundingBox(), getMax(), getMin(), and getVolume().
The documentation for this class was generated from the following files:
BoundingVolume.h
BoundingVolume.cpp