GLESC: GLESC::InGameWindow Class Reference
GLESC::InGameWindow Class Reference abstract
Class to encapsulate the logic of an in-game window.
#include <InGameWindow.h>
Public Member Functions
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Protected Member Functions
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
virtual void windowContent (float timeOfFrame)=0
Protected Attributes
bool isVisible = true
Private Attributes
ImGuiWindowFlags cachedFlags = 0
ImVec2 center = ImVec2(0.5f, 0.5f)
ImVec2 maxSize = ImVec2(999999, 999999)
ImVec2 minSize = ImVec2(0, 0)
ImVec2 position
ImVec2 positionFraction = ImVec2(0.5f, 0.5f)
ImVec2 size
ImVec2 sizeFraction = ImVec2(0.5f, 0.5f)
std::string title = "Window"
std::vector< ImGuiWindowFlags_ > windowFlags
bool windowFlagsCached = false
float windowMarginFraction {0.02f}
Detailed Description
Class to encapsulate the logic of an in-game window.
This class must be inherited by any class that wants to create a window in the game. Allows setting the position, size, and layout of the window.
Definition at line 47 of file InGameWindow.h.
Constructor & Destructor Documentation
InGameWindow()
InGameWindow::InGameWindow ()
Definition at line 8 of file InGameWindow.cpp.
                           : isVisible(false) {
}
~InGameWindow()
virtual GLESC::InGameWindow::~InGameWindow () virtual default
Member Function Documentation
addFlag()
void GLESC::InGameWindow::addFlag (ImGuiWindowFlags_ flag) inline
Definition at line 86 of file InGameWindow.h.
{
            windowFlags.push_back(flag);
            windowFlagsCached = false;
        }
References GLESC::isIterable_v, windowFlags, and windowFlagsCached.
Referenced by GLESC::HUD::CrosshairHUD::CrosshairHUD(), GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), and GLESC::HUD::EntityListHUD::EntityListHUD().
calculatePosition()
ImVec2 InGameWindow::calculatePosition (ImVec2 windowSize) const protected
Definition at line 132 of file InGameWindow.cpp.
{
    float screenWidth = ImGui::GetIO().DisplaySize.x;
    float screenHeight = ImGui::GetIO().DisplaySize.y;
    // Calculate position based on fractions of screen width and height, correctly centering the window
    float posX = (screenWidth * positionFraction.x) - (windowSize.x * center.x);
    float posY = (screenHeight * positionFraction.y) - (windowSize.y * center.y);
    // Ensure the position respects the screen boundaries
    posX = std::max(posX, windowMarginFraction * screenWidth);
    posY = std::max(posY, windowMarginFraction * screenHeight);
    posX = std::min(posX, screenWidth - windowSize.x - windowMarginFraction * screenWidth);
    posY = std::min(posY, screenHeight - windowSize.y - windowMarginFraction * screenHeight);
    return {posX, posY};
}
References center, GLESC::isIterable_v, positionFraction, and windowMarginFraction.
Referenced by update().
calculateSize()
ImVec2 InGameWindow::calculateSize () const protected
Definition at line 149 of file InGameWindow.cpp.
{
    float screenWidth = ImGui::GetIO().DisplaySize.x;
    float screenHeight = ImGui::GetIO().DisplaySize.y;
    // Calculate size based on fractions of screen width and height
    ImVec2 calculatedSize = ImVec2(screenWidth * sizeFraction.x, screenHeight * sizeFraction.y);
    // Apply minimum size constraints
    calculatedSize.x = std::max(calculatedSize.x, minSize.x);
    calculatedSize.y = std::max(calculatedSize.y, minSize.y);
    // Apply maximum size constraints
    calculatedSize.x = std::min(calculatedSize.x, maxSize.x > 0 ? maxSize.x : screenWidth);
    calculatedSize.y = std::min(calculatedSize.y, maxSize.y > 0 ? maxSize.y : screenHeight);
    return calculatedSize;
}
References GLESC::isIterable_v, maxSize, minSize, and sizeFraction.
Referenced by update().
getFlags()
ImGuiWindowFlags InGameWindow::getFlags () protected
Definition at line 75 of file InGameWindow.cpp.
{
    if (!windowFlagsCached) {
        cachedFlags = 0;
        for (auto& flag : windowFlags) {
            cachedFlags |= flag;
        }
        windowFlagsCached = true;
    }
    return cachedFlags;
}
References cachedFlags, GLESC::isIterable_v, windowFlags, and windowFlagsCached.
Referenced by render().
getTitle()
const std::string & GLESC::InGameWindow::getTitle () const inline
Definition at line 83 of file InGameWindow.h.
{ return title; }
References title.
isVisibile()
bool GLESC::InGameWindow::isVisibile () const inline
Definition at line 91 of file InGameWindow.h.
{ return isVisible; }
References isVisible.
render()
void InGameWindow::render (float timeOfFrame)
Render the window.
The time of frame is needed to interpolate hud items and allow for smooth rendering
Parameters
timeOfFrame The time of the current frame
Definition at line 167 of file InGameWindow.cpp.
{
    if (!isVisible) return;
    ImGui::SetNextWindowPos(position, ImGuiCond_Always);
    ImGui::SetNextWindowSize(size, ImGuiCond_Always);
    // Debugging output
    Console::log(title + " window Position: (" + std::to_string(position.x) + ", " + std::to_string(position.y) + ")");
    Console::log(title + " window Size: (" + std::to_string(size.x) + ", " + std::to_string(size.y) + ")");
    if (ImGui::Begin(title.c_str(), &isVisible, getFlags())) {
        windowContent(timeOfFrame);
        ImGui::End();
    }
}
References getFlags(), GLESC::isIterable_v, isVisible, GLESC::Console::log(), position, size, title, and windowContent().
setCenter()
void InGameWindow::setCenter (WindowCenter center)
Set the center of the window.
The center is used to calculate the position of the window.
Definition at line 41 of file InGameWindow.cpp.
{
    if (center == WindowCenter::TopLeft) {
        this->center = ImVec2(0.0f, 0.0f);
    }
    else if (center == WindowCenter::CenterLeft) {
        this->center = ImVec2(0.0f, 0.5f);
    }
    else if (center == WindowCenter::BottomLeft) {
        this->center = ImVec2(0.0f, 1.0f);
    }
    else if (center == WindowCenter::TopCenter) {
        this->center = ImVec2(0.5f, 0.0f);
    }
    else if (center == WindowCenter::Center) {
        this->center = ImVec2(0.5f, 0.5f);
    }
    else if (center == WindowCenter::BottomCenter) {
        this->center = ImVec2(0.5f, 1.0f);
    }
    else if (center == WindowCenter::TopRight) {
        this->center = ImVec2(1.0f, 0.0f);
    }
    else if (center == WindowCenter::CenterRight) {
        this->center = ImVec2(1.0f, 0.5f);
    }
    else if (center == WindowCenter::BottomRight) {
        this->center = ImVec2(1.0f, 1.0f);
    }
    else {
        D_ASSERT_TRUE(false, "Invalid center");
    }
}
References GLESC::BottomCenter, GLESC::BottomLeft, GLESC::BottomRight, GLESC::Center, center, GLESC::CenterLeft, GLESC::CenterRight, D_ASSERT_TRUE, GLESC::isIterable_v, GLESC::TopCenter, GLESC::TopLeft, and GLESC::TopRight.
Referenced by GLESC::HUD::CrosshairHUD::CrosshairHUD(), GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), and GLESC::HUD::EntityListHUD::EntityListHUD().
setLayoutPosition()
void InGameWindow::setLayoutPosition (LayoutPos position)
Set the layout position of the window.
The layout position is used to calculate the position of the window.
Definition at line 86 of file InGameWindow.cpp.
{
    if (position == LayoutPos::TopLeft) {
        positionFraction.x = windowMarginFraction;
        positionFraction.y = windowMarginFraction;
    }
    else if (position == LayoutPos::TopCenter) {
        positionFraction.x = 0.5f;
        positionFraction.y = windowMarginFraction;
    }
    else if (position == LayoutPos::TopRight) {
        positionFraction.x = 1.0f - windowMarginFraction;
        positionFraction.y = windowMarginFraction;
    }
    else if (position == LayoutPos::BottomLeft) {
        positionFraction.x = windowMarginFraction;
        positionFraction.y = 1.0f - windowMarginFraction;
    }
    else if (position == LayoutPos::BottomCenter) {
        positionFraction.x = 0.5f;
        positionFraction.y = 1.0f - windowMarginFraction;
    }
    else if (position == LayoutPos::BottomRight) {
        positionFraction.x = 1.0f - windowMarginFraction;
        positionFraction.y = 1.0f - windowMarginFraction;
    }
    else if (position == LayoutPos::CenterLeft) {
        positionFraction.x = windowMarginFraction;
        positionFraction.y = 0.5f;
    }
    else if (position == LayoutPos::Center) {
        positionFraction.x = 0.5f;
        positionFraction.y = 0.5f;
    }
    else if (position == LayoutPos::CenterRight) {
        positionFraction.x = 1.0f - windowMarginFraction;
        positionFraction.y = 0.5f;
    }
    else if (position == LayoutPos::Custom) {
        // Do nothing, use the already set position
    }
    else {
        D_ASSERT_TRUE(false, "Invalid layout position");
    }
}
References GLESC::BottomCenter, GLESC::BottomLeft, GLESC::BottomRight, GLESC::Center, GLESC::CenterLeft, GLESC::CenterRight, GLESC::Custom, D_ASSERT_TRUE, position, positionFraction, GLESC::TopCenter, GLESC::TopLeft, GLESC::TopRight, and windowMarginFraction.
Referenced by GLESC::HUD::CrosshairHUD::CrosshairHUD(), GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), and GLESC::HUD::EntityListHUD::EntityListHUD().
setMaxSize()
void InGameWindow::setMaxSize (ImVec2 size)
Set the max size of the window.
If the window gets bigger this value, it will be clamped to this size
Definition at line 22 of file InGameWindow.cpp.
{
    D_ASSERT_TRUE(maxSize.x >= 0.0f && maxSize.y >= 0.0f, "Invalid max size");
    this->maxSize = maxSize;
}
References D_ASSERT_TRUE, and maxSize.
Referenced by GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD().
setMinSize()
void InGameWindow::setMinSize (ImVec2 size)
Set the min size of the window.
If the window gets smaller this value, it will be clamped to this size
Definition at line 17 of file InGameWindow.cpp.
{
    D_ASSERT_TRUE(minSize.x >= 0.0f && minSize.y >= 0.0f, "Invalid min size");
    this->minSize = minSize;
}
References D_ASSERT_TRUE, and minSize.
Referenced by GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), and GLESC::HUD::EntityListHUD::EntityListHUD().
setPositionFraction()
void InGameWindow::setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
The fraction is clamped between 0.0f and 1.0f. The center of the window is set by the set center function. The position will modify that center.
Definition at line 35 of file InGameWindow.cpp.
{
    D_ASSERT_TRUE(fraction.x >= 0.0f && fraction.x <= 1.0f, "Invalid fraction x");
    D_ASSERT_TRUE(fraction.y >= 0.0f && fraction.y <= 1.0f, "Invalid fraction y");
    positionFraction = fraction;
}
References D_ASSERT_TRUE, GLESC::isIterable_v, and positionFraction.
setSizeFraction()
void InGameWindow::setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
The fraction is clamped between 0.0f and 1.0f
Definition at line 27 of file InGameWindow.cpp.
{
    D_ASSERT_TRUE(fraction.x >= 0.0f && fraction.x <= 1.0f, "Invalid fraction x");
    D_ASSERT_TRUE(fraction.y >= 0.0f && fraction.y <= 1.0f, "Invalid fraction y");
    // We need the min between 1.0f - margin and fraction to avoid the window going off margins
    sizeFraction.x = std::min(fraction.x, 1.0f - windowMarginFraction * 2);
    sizeFraction.y = std::min(fraction.y, 1.0f - windowMarginFraction * 2);
}
References D_ASSERT_TRUE, GLESC::isIterable_v, sizeFraction, and windowMarginFraction.
Referenced by GLESC::HUD::CrosshairHUD::CrosshairHUD(), GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), and GLESC::HUD::EntityListHUD::EntityListHUD().
setTitle()
void InGameWindow::setTitle (const std::string & title) protected
Definition at line 11 of file InGameWindow.cpp.
{
    D_ASSERT_FALSE(title.empty(), "Title cannot be empty");
    D_ASSERT_FALSE(title.size() > 100, "Title is too long");
    this->title = title;
}
References D_ASSERT_FALSE, and title.
Referenced by GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), and GLESC::HUD::EntityListHUD::EntityListHUD().
setVisible()
void GLESC::InGameWindow::setVisible (bool visible) inline
Definition at line 92 of file InGameWindow.h.
{ isVisible = visible; }
References GLESC::isIterable_v, and isVisible.
toggleVisibility()
void GLESC::InGameWindow::toggleVisibility () inline
Definition at line 93 of file InGameWindow.h.
{ isVisible = !isVisible; }
References isVisible.
Referenced by GLESC::HUD::EngineHUDManager::toggle().
update()
void InGameWindow::update ()
Update the window position and size.
Updates the windows positions given it's layout configuration and the current window size
Definition at line 183 of file InGameWindow.cpp.
{
    size = calculateSize();
    position = calculatePosition(size);
}
References calculatePosition(), calculateSize(), position, and size.
windowContent()
virtual void GLESC::InGameWindow::windowContent (float timeOfFrame) protected pure virtual
Implemented in GLESC::HUD::CrosshairHUD, GLESC::HUD::DebugConsoleHUD, GLESC::HUD::DebugEntityData, GLESC::HUD::DebugItems, GLESC::HUD::DebugStatsHUD, and GLESC::HUD::EntityListHUD.
Referenced by render().
Member Data Documentation
cachedFlags
ImGuiWindowFlags GLESC::InGameWindow::cachedFlags = 0 private
Definition at line 127 of file InGameWindow.h.
Referenced by getFlags().
center
ImVec2 GLESC::InGameWindow::center = ImVec2(0.5f, 0.5f) private
Definition at line 120 of file InGameWindow.h.
Referenced by calculatePosition(), and setCenter().
isVisible
bool GLESC::InGameWindow::isVisible = true protected
Definition at line 113 of file InGameWindow.h.
Referenced by GLESC::HUD::CrosshairHUD::CrosshairHUD(), GLESC::HUD::DebugConsoleHUD::DebugConsoleHUD(), GLESC::HUD::DebugEntityData::DebugEntityData(), GLESC::HUD::DebugItems::DebugItems(), GLESC::HUD::DebugStatsHUD::DebugStatsHUD(), GLESC::HUD::EntityListHUD::EntityListHUD(), isVisibile(), render(), setVisible(), and toggleVisibility().
maxSize
ImVec2 GLESC::InGameWindow::maxSize = ImVec2(999999, 999999) private
Definition at line 116 of file InGameWindow.h.
Referenced by calculateSize(), and setMaxSize().
minSize
ImVec2 GLESC::InGameWindow::minSize = ImVec2(0, 0) private
Definition at line 117 of file InGameWindow.h.
Referenced by calculateSize(), and setMinSize().
position
ImVec2 GLESC::InGameWindow::position private
Definition at line 125 of file InGameWindow.h.
Referenced by render(), setLayoutPosition(), and update().
positionFraction
ImVec2 GLESC::InGameWindow::positionFraction = ImVec2(0.5f, 0.5f) private
Definition at line 119 of file InGameWindow.h.
Referenced by calculatePosition(), setLayoutPosition(), and setPositionFraction().
size
ImVec2 GLESC::InGameWindow::size private
Definition at line 124 of file InGameWindow.h.
Referenced by render(), update(), and GLESC::HUD::DebugItems::windowContent().
sizeFraction
ImVec2 GLESC::InGameWindow::sizeFraction = ImVec2(0.5f, 0.5f) private
Definition at line 118 of file InGameWindow.h.
Referenced by calculateSize(), and setSizeFraction().
title
std::string GLESC::InGameWindow::title = "Window" private
Definition at line 123 of file InGameWindow.h.
Referenced by getTitle(), render(), and setTitle().
windowFlags
std::vector<ImGuiWindowFlags_> GLESC::InGameWindow::windowFlags private
Definition at line 126 of file InGameWindow.h.
Referenced by addFlag(), and getFlags().
windowFlagsCached
bool GLESC::InGameWindow::windowFlagsCached = false mutable private
Definition at line 128 of file InGameWindow.h.
Referenced by addFlag(), and getFlags().
windowMarginFraction
float GLESC::InGameWindow::windowMarginFraction {0.02f} private
Definition at line 121 of file InGameWindow.h.
{0.02f};
Referenced by calculatePosition(), setLayoutPosition(), and setSizeFraction().
The documentation for this class was generated from the following files:
InGameWindow.h
InGameWindow.cpp