GLESC: GLESC::Physics::Collider Class Reference
GLESC::Physics::Collider Class Reference
The collider class component for entities.
#include <Collider.h>
Public Member Functions
Collider ()=default
~Collider () override=default
const Math::BoundingVolume & getBoundingVolume () const
CollisionInformation & getCollisionInformation () const
std::vector< EntityStatsManager::Value > getDebuggingValues () override
Get the debugging values of the component.
const CollisionCallback & getGeneralCollisionCallback () const
const SpecificCollisionCallbacks & getSpecificCollisionCallbacks () const
std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues () override
Get the updated debugging values of the component.
bool isSolid () const
void setBoundingVolume (const Math::BoundingVolume &boundingVolume)
void setCollisionCallback (std::function< void(Collider &)> callback)
void setCollisionInformation (const CollisionInformation &collisionInformation)
void setSolid (bool solid)
std::string toString () const override
Public Member Functions inherited from EngineComponent
virtual ~EngineComponent ()=default
const char * getOwnerName () const
Get the owner name of the component for debugging purposes.
void setOwnerName (const char *ownerName)
Set the owner name of the component for debugging purposes.
Private Types
using CollisionCallback = std::function< void(Collider &)>
using SpecificCollisionCallbacks = std::unordered_map< Collider *, CollisionCallback >
Private Attributes
Math::BoundingVolume boundingVolume
CollisionCallback collisionCallback
SpecificCollisionCallbacks collisionCallbacks
CollisionInformation collisionInformation
bool solid = true
Friends
class CollisionManager
Detailed Description
The collider class component for entities.
This class handles all the data of the collider and the information of the collision itself (such as the position or the depth of the collision). Also stores the callbacks for the collision.
Definition at line 28 of file Collider.h.
Member Typedef Documentation
CollisionCallback
using GLESC::Physics::Collider::CollisionCallback = std::function<void(Collider&)> private
Definition at line 29 of file Collider.h.
SpecificCollisionCallbacks
using GLESC::Physics::Collider::SpecificCollisionCallbacks = std::unordered_map<Collider*, CollisionCallback> private
Definition at line 30 of file Collider.h.
Constructor & Destructor Documentation
Collider()
GLESC::Physics::Collider::Collider () default
~Collider()
GLESC::Physics::Collider::~Collider () override default
Member Function Documentation
getBoundingVolume()
const Math::BoundingVolume & GLESC::Physics::Collider::getBoundingVolume () const inline
Definition at line 50 of file Collider.h.
{ return boundingVolume; }
References boundingVolume.
Referenced by translateBV().
getCollisionInformation()
CollisionInformation & GLESC::Physics::Collider::getCollisionInformation () const inline
Definition at line 46 of file Collider.h.
{ return collisionInformation; }
References collisionInformation.
Referenced by GLESC::Physics::CollisionManager::checkAndUpdateColliderInformation(), GLESC::Physics::getAxisFree(), and GLESC::Physics::PhysicsManager::handleCollisions().
getDebuggingValues()
std::vector< EntityStatsManager::Value > GLESC::Physics::Collider::getDebuggingValues () override virtual
Get the debugging values of the component.
This function can be overriden by the derived class to return the debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented from EngineComponent.
Definition at line 8 of file Collider.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value solidValue;
    solidValue.name = "Solid";
    solidValue.data = reinterpret_cast<void*>(&solid);
    solidValue.type = EntityStatsManager::ValueType::BOOL;
    solidValue.isModifiable = true;
    values.push_back(solidValue);
    EntityStatsManager::Value boundingVolumeValueMin;
    boundingVolumeValueMin.name = "Bounding Volume Min";
    boundingVolumeValueMin.data = reinterpret_cast<void*>(&boundingVolume.getBoundingBox().min);
    boundingVolumeValueMin.type = EntityStatsManager::ValueType::VEC3F;
    boundingVolumeValueMin.usesSlider = true;
    boundingVolumeValueMin.min = -1000.0F;
    boundingVolumeValueMin.max = 1000.0F;
    boundingVolumeValueMin.isModifiable = true;
    values.push_back(boundingVolumeValueMin);
    EntityStatsManager::Value boundingVolumeValueMax;
    boundingVolumeValueMax.name = "Bounding Volume Max";
    boundingVolumeValueMax.data = reinterpret_cast<void*>(&boundingVolume.getBoundingBox().max);
    boundingVolumeValueMax.type = EntityStatsManager::ValueType::VEC3F;
    boundingVolumeValueMax.usesSlider = true;
    boundingVolumeValueMax.min = -1000.0F;
    boundingVolumeValueMax.max = 1000.0F;
    boundingVolumeValueMax.isModifiable = true;
    values.push_back(boundingVolumeValueMax);
    EntityStatsManager::Value isCollidingValue;
    isCollidingValue.name = "Is Colliding";
    isCollidingValue.data = reinterpret_cast<void*>(&collisionInformation.isColliding());
    isCollidingValue.type = EntityStatsManager::ValueType::BOOL;
    isCollidingValue.isModifiable = false;
    values.push_back(isCollidingValue);
    EntityStatsManager::Value isCollidingWithAxisValue;
    isCollidingWithAxisValue.name = "Is Colliding with axis";
    isCollidingWithAxisValue.data = reinterpret_cast<void*>(&collisionInformation.getCollidingAxis());
    isCollidingWithAxisValue.type = EntityStatsManager::ValueType::VEC3B;
    isCollidingWithAxisValue.isModifiable = true;
    values.push_back(isCollidingWithAxisValue);
    EntityStatsManager::Value onAirValue;
    onAirValue.name = "Is on ground";
    onAirValue.data = reinterpret_cast<void*>(&collisionInformation.isOnGround());
    onAirValue.type = EntityStatsManager::ValueType::BOOL;
    onAirValue.isModifiable = true;
    values.push_back(onAirValue);
    return values;
}
References EntityStatsManager::BOOL, boundingVolume, collisionInformation, GLESC::Math::BoundingVolume::getBoundingBox(), GLESC::Physics::CollisionInformation::getCollidingAxis(), GLESC::Physics::CollisionInformation::isColliding(), GLESC::isIterable_v, GLESC::Physics::CollisionInformation::isOnGround(), GLESC::Math::BoundingVolume::AABB::max, GLESC::Math::BoundingVolume::AABB::min, EntityStatsManager::Value::name, solid, EntityStatsManager::VEC3B, and EntityStatsManager::VEC3F.
Referenced by GLESC::ECS::CollisionComponent::setDebuggingValues().
getGeneralCollisionCallback()
const CollisionCallback & GLESC::Physics::Collider::getGeneralCollisionCallback () const inline
Definition at line 47 of file Collider.h.
{ return collisionCallback; }
References collisionCallback.
Referenced by GLESC::Physics::PhysicsManager::executeCallbacks().
getSpecificCollisionCallbacks()
const SpecificCollisionCallbacks & GLESC::Physics::Collider::getSpecificCollisionCallbacks () const inline
Definition at line 48 of file Collider.h.
{ return collisionCallbacks; }
References collisionCallbacks.
Referenced by GLESC::Physics::PhysicsManager::executeCallbacks().
getUpdatedDebuggingValues()
std::vector< EntityStatsManager::Value > GLESC::Physics::Collider::getUpdatedDebuggingValues () override virtual
Get the updated debugging values of the component.
This function can be overriden by the derived class to return the updated debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented from EngineComponent.
Definition at line 63 of file Collider.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value colliderNamesValue;
    colliderNamesValue.name = "Colliders";
    colliderNamesValue.isString = true;
    for (int i = 0; i < collisionInformation.getCollisionDepthForAxis().size(); i++) {
        Vec3F& collisionDepth = collisionInformation.getCollisionDepthForAxis()[i];
        Collider* collider = collisionInformation.getCollidingWithColliders()[i];
        colliderNamesValue.stringData += std::string(collider->getOwnerName()) +
            " depth: " + collisionDepth.toString() + "\n";
    }
    colliderNamesValue.type = EntityStatsManager::ValueType::STRING;
    colliderNamesValue.isModifiable = false;
    values.push_back(colliderNamesValue);
    return values;
}
References EngineComponent::getOwnerName(), GLESC::isIterable_v, EntityStatsManager::Value::name, EntityStatsManager::STRING, and toString().
Referenced by GLESC::ECS::CollisionComponent::setUpdatedDebuggingValues().
isSolid()
bool GLESC::Physics::Collider::isSolid () const inline
Definition at line 49 of file Collider.h.
{ return solid; }
References solid.
Referenced by GLESC::Physics::CollisionManager::checkAndUpdateColliderInformation().
setBoundingVolume()
void GLESC::Physics::Collider::setBoundingVolume (const Math::BoundingVolume & boundingVolume) inline
Definition at line 37 of file Collider.h.
{ this->boundingVolume = boundingVolume; }
References boundingVolume.
setCollisionCallback()
void GLESC::Physics::Collider::setCollisionCallback (std::function< void(Collider &)> callback) inline
Definition at line 38 of file Collider.h.
{ collisionCallback = callback; }
References collisionCallback, and GLESC::isIterable_v.
setCollisionInformation()
void GLESC::Physics::Collider::setCollisionInformation (const CollisionInformation & collisionInformation) inline
Definition at line 41 of file Collider.h.
{
            this->collisionInformation = collisionInformation;
        }
References collisionInformation.
setSolid()
void GLESC::Physics::Collider::setSolid (bool solid) inline
Definition at line 39 of file Collider.h.
{ this->solid = solid; }
References solid.
toString()
std::string GLESC::Physics::Collider::toString () const override virtual
Implements EngineComponent.
Definition at line 84 of file Collider.cpp.
{
    // TODO: Improve this if needed (missing stuff)
    std::stringstream ss;
    ss << "AABB max:" + boundingVolume.getMax().toString() + " min:" + boundingVolume.getMin().toString();
    ss << " Solid:" << solid;
    ss << " On Air:" << collisionInformation.isOnGround();
    ss << " Collides Axis:" << collisionInformation.getCollidingAxis().toString();
    return ss.str();
}
References GLESC::isIterable_v.
Referenced by getUpdatedDebuggingValues(), and GLESC::ECS::CollisionComponent::toString().
Friends And Related Symbol Documentation
CollisionManager
friend class CollisionManager friend
Definition at line 31 of file Collider.h.
Member Data Documentation
boundingVolume
Math::BoundingVolume GLESC::Physics::Collider::boundingVolume private
Definition at line 60 of file Collider.h.
Referenced by getBoundingVolume(), getDebuggingValues(), and setBoundingVolume().
collisionCallback
CollisionCallback GLESC::Physics::Collider::collisionCallback private
Definition at line 58 of file Collider.h.
Referenced by getGeneralCollisionCallback(), and setCollisionCallback().
collisionCallbacks
SpecificCollisionCallbacks GLESC::Physics::Collider::collisionCallbacks private
Definition at line 59 of file Collider.h.
Referenced by getSpecificCollisionCallbacks().
collisionInformation
CollisionInformation GLESC::Physics::Collider::collisionInformation mutable private
Definition at line 61 of file Collider.h.
Referenced by getCollisionInformation(), getDebuggingValues(), and setCollisionInformation().
solid
bool GLESC::Physics::Collider::solid = true private
Definition at line 63 of file Collider.h.
Referenced by getDebuggingValues(), isSolid(), and setSolid().
The documentation for this class was generated from the following files:
Collider.h
Collider.cpp