GLESC: GLESC::TextureLoader Class Reference
GLESC::TextureLoader Class Reference
A class that loads textures from the file system.
#include <TextureLoader.h>
Static Public Member Functions
static SDL_SurfacePtr loadTexture (const std::string &path, bool flipTexture)
Loads a texture from the file system.
Static Private Member Functions
static SDL_SurfacePtr createSurface (const std::string &filePath)
Creates a surface from a file, it is called by loadTexture.
static SDL_SurfacePtr flipSurface (SDL_Surface &surface)
Flips a surface.
Detailed Description
A class that loads textures from the file system.
Definition at line 26 of file TextureLoader.h.
Member Function Documentation
createSurface()
SDL_SurfacePtr TextureLoader::createSurface (const std::string & filePath) static private
Creates a surface from a file, it is called by loadTexture.
Parameters
filePath The path to the file
Returns
The surface
Definition at line 18 of file TextureLoader.cpp.
{
    D_ASSERT_FALSE(filePath.empty(), "File path is empty.");
    std::string fullImagePath = BinPath::getExecutableDirectory() + "/" + filePath;
    Logger::get().info("Loading image: " + fullImagePath);
    // Load the image
    SDL_SurfacePtr surfacePtr(IMG_Load(fullImagePath.c_str()), &SDL_FreeSurface);
    //postSDLCall
    SDL_ClearError();
    // Check if the image was loaded
    D_ASSERT_NOT_NULLPTR(surfacePtr, "Image couldn't be loaded. Image path: " + fullImagePath +
                                     ", SDL error: " + SDL_GetError());
    Logger::get().success("Image loaded successfully: " + filePath);
    return surfacePtr;
}
References D_ASSERT_FALSE, D_ASSERT_NOT_NULLPTR, GLESC::Logger::get(), BinPath::getExecutableDirectory(), GLESC::Logger::info(), GLESC::isIterable_v, and GLESC::Logger::success().
Referenced by loadTexture().
flipSurface()
SDL_SurfacePtr TextureLoader::flipSurface (SDL_Surface & surface) static private
Flips a surface.
It is needed because some graphic APIs require textures to be flipped
Parameters
surface The surface to flip
Returns
The flipped surface
Definition at line 52 of file TextureLoader.cpp.
{
    SDL_SurfacePtr flippedSurface = std::unique_ptr<SDL_Surface, decltype(&SDL_FreeSurface)>(
            SDL_CreateRGBSurface(0, surface.w, surface.h, surface.format->BitsPerPixel,
                                 surface.format->Rmask, surface.format->Gmask,
                                 surface.format->Bmask, surface.format->Amask),
            &SDL_FreeSurface);
    D_ASSERT_NOT_NULLPTR(flippedSurface, "Flipped surface couldn't be created. SDL error: " +
                                         std::string(SDL_GetError()));
    Logger::get().info("Flipping image...");
    D_ASSERT_TRUE(!SDL_MUSTLOCK(&surface) || SDL_LockSurface(&surface) == 0,
                  "Original surface must be locked.");
    D_ASSERT_TRUE(!SDL_MUSTLOCK(flippedSurface.get()) || SDL_LockSurface(flippedSurface.get()) == 0,
                  "Flipped surface must be locked.");
    int pitch = surface.pitch;
    for (int currentLine = 0; currentLine < surface.h; ++currentLine) {
        memcpy(static_cast<unsigned char *>(flippedSurface->pixels) + currentLine * pitch,
               static_cast<unsigned char *>(surface.pixels) + (surface.h - 1 - currentLine) * pitch,
               pitch);
    }
    if (SDL_MUSTLOCK(&surface)) {
        SDL_UnlockSurface(&surface);
    }
    if (SDL_MUSTLOCK(flippedSurface.get())) {
        SDL_UnlockSurface(flippedSurface.get());
    }
    Logger::get().success("Image flipped successfully.");
    return flippedSurface;
}
References D_ASSERT_NOT_NULLPTR, D_ASSERT_TRUE, GLESC::Logger::get(), GLESC::Logger::info(), GLESC::isIterable_v, and GLESC::Logger::success().
Referenced by loadTexture().
loadTexture()
SDL_SurfacePtr TextureLoader::loadTexture (const std::string & filePath, bool flipTexture) static
Loads a texture from the file system.
Takes the path of an image and loads it into a texture.
Parameters
path The path to the texture
flipTexture If the texture should be flipped
Returns
A smart pointer to the texture
Parameters
filePath The path of the image.
flipTexture
Returns
The image data of the loaded image.
Definition at line 40 of file TextureLoader.cpp.
{
    D_ASSERT_FALSE(filePath.empty(), "File path is empty.");
    SDL_SurfacePtr surface = createSurface(filePath);
    D_ASSERT_NOT_NULLPTR(surface, "Surface is null.");
    if (flipTexture)
        surface = flipSurface(*surface.get());
    return surface;
}
References createSurface(), D_ASSERT_FALSE, D_ASSERT_NOT_NULLPTR, flipSurface(), and GLESC::isIterable_v.
Referenced by GLESC::ResMng::Texture::TextureSurface::load().
The documentation for this class was generated from the following files:
TextureLoader.h
TextureLoader.cpp