GLESC: GLESC::Render::ColorVertex Class Reference
GLESC::Render::ColorVertex Class Reference
Represents a vertex with color.
#include <Vertex.h>
Public Member Functions
ColorVertex (const Position &position, const Normal &normal, const ColorRgba &color)
const ColorRgbaNorm & getColor () const
bool operator== (const ColorVertex &other) const
void setColor (const ColorRgba &colorParam)
std::string toString () const
Public Member Functions inherited from GLESC::Render::BaseVertex
BaseVertex (Position position, Normal normal)
Normal & getNormal ()
const Normal & getNormal () const
Position & getPosition ()
const Position & getPosition () const
bool operator== (const BaseVertex &other) const
void setNormal (const Normal &normalParam)
void setPosition (const Position &positionParam)
std::string toString () const
Static Public Member Functions
static const std::vector< GAPI::Enums::Types > & getLayout ()
Static Public Member Functions inherited from GLESC::Render::BaseVertex
static const std::vector< GAPI::Enums::Types > & getLayout ()
Private Attributes
ColorRgbaNorm color
Static Private Attributes
static std::vector< GAPI::Enums::Types > layout
Additional Inherited Members
Static Public Attributes inherited from GLESC::Render::BaseVertex
static std::vector< GAPI::Enums::Types > layout
Detailed Description
Represents a vertex with color.
This is tightly packed, and so are all of its members
Definition at line 49 of file Vertex.h.
Constructor & Destructor Documentation
ColorVertex()
GLESC::Render::ColorVertex::ColorVertex (const Position & position, const Normal & normal, const ColorRgba & color) inline
Definition at line 52 of file Vertex.h.
            : BaseVertex(position, normal), color(color) {
        }
Member Function Documentation
getColor()
const ColorRgbaNorm & GLESC::Render::ColorVertex::getColor () const inline
Definition at line 60 of file Vertex.h.
{ return color; }
References color.
getLayout()
static const std::vector< GAPI::Enums::Types > & GLESC::Render::ColorVertex::getLayout () inline static
Definition at line 51 of file Vertex.h.
{ return layout; }
References layout.
operator==()
bool GLESC::Render::ColorVertex::operator== (const ColorVertex & other) const inline
Definition at line 56 of file Vertex.h.
{
            return BaseVertex::operator==(other) && color == other.color;
        }
References color, GLESC::isIterable_v, and GLESC::Render::BaseVertex::operator==().
setColor()
void GLESC::Render::ColorVertex::setColor (const ColorRgba & colorParam) inline
Definition at line 61 of file Vertex.h.
{ color = colorParam; }
References color, and GLESC::isIterable_v.
toString()
std::string GLESC::Render::ColorVertex::toString () const inline
Definition at line 62 of file Vertex.h.
{
            return BaseVertex::toString() + " Color: " + color.toString();
        }
References color, GLESC::Render::BaseVertex::toString(), and GLESC::Render::ColorRgbaNorm::toString().
Member Data Documentation
color
ColorRgbaNorm GLESC::Render::ColorVertex::color private
Definition at line 66 of file Vertex.h.
Referenced by getColor(), operator==(), setColor(), and toString().
layout
std::vector< GLESC::GAPI::Enums::Types > GLESC::Render::ColorVertex::layout static private
Initial value:
= {
    GAPI::Enums::Types::Vec3F,
    GAPI::Enums::Types::Vec3F,
    GAPI::Enums::Types::Vec4F
}
Definition at line 11 of file Vertex.h.
Referenced by getLayout().
The documentation for this class was generated from the following files:
Vertex.h
Vertex.cpp