GLESC: GLESC::ECS::PhysicsCollisionSystem Class Reference
GLESC::ECS::PhysicsCollisionSystem Class Reference
#include <PhysicsCollisionSystem.h>
Public Member Functions
PhysicsCollisionSystem (Physics::PhysicsManager &physicsManager, Physics::CollisionManager &collisionManager, ECSCoordinator &ecs)
void update () override
Updates the system.
Public Member Functions inherited from GLESC::ECS::System
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
Private Attributes
Physics::CollisionManager & collisionManager
Physics::PhysicsManager & physicsManager
Additional Inherited Members
Protected Member Functions inherited from GLESC::ECS::System
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes inherited from GLESC::ECS::System
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Detailed Description
The update of this class must be called after the update of the PhysicsSystem
Definition at line 20 of file PhysicsCollisionSystem.h.
Constructor & Destructor Documentation
PhysicsCollisionSystem()
PhysicsCollisionSystem::PhysicsCollisionSystem (Physics::PhysicsManager & physicsManager, Physics::CollisionManager & collisionManager, ECSCoordinator & ecs) explicit
Definition at line 10 of file PhysicsCollisionSystem.cpp.
                                                                    :
    collisionManager(collisionManager), physicsManager(physicsManager),
    System(ecs, "PhysicsCollisionSystem") {
    addComponentRequirement<PhysicsComponent>();
    addComponentRequirement<TransformComponent>();
    addComponentRequirement<CollisionComponent>();
}
References GLESC::isIterable_v.
Member Function Documentation
update()
void PhysicsCollisionSystem::update () override virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implements GLESC::ECS::System.
Definition at line 20 of file PhysicsCollisionSystem.cpp.
{
    auto& entities = getAssociatedEntities();
    // TODO: Get the component array from the ecs so we don't need to iterate over the entities
    for (auto& entity : entities) {
        getComponent<CollisionComponent>(entity).collider.setOwnerName(getEntityName(entity).c_str());
        getComponent<PhysicsComponent>(entity).physics.setOwnerName(getEntityName(entity).c_str());
        collisionManager.addCollider(getComponent<CollisionComponent>(entity).collider,
                                     getComponent<PhysicsComponent>(entity).physics,
                                     getComponent<TransformComponent>(entity).transform);
    }
    for (auto& entity : entities) {
        auto& physics = getComponent<PhysicsComponent>(entity);
        auto& collision = getComponent<CollisionComponent>(entity);
        auto& transform = getComponent<TransformComponent>(entity);
        collisionManager.checkAndUpdateColliderInformation(collision.collider,
                                                 physics.oldTransform,
                                                 transform.transform);
        if (collision.collider.getCollisionInformation().isColliding()) {
            physicsManager.handleCollisions(collision.collider, physics.physics);
            transform.transform = GLESC::Physics::PhysicsManager::updateTransform(physics.oldTransform,
                physics.physics);
        }
    }
    collisionManager.clearColliders();
}
References GLESC::Physics::CollisionManager::addCollider(), GLESC::Physics::CollisionManager::checkAndUpdateColliderInformation(), GLESC::Physics::CollisionManager::clearColliders(), collisionManager, entities, GLESC::ECS::System::getAssociatedEntities(), GLESC::ECS::System::getEntityName(), GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::isIterable_v, physicsManager, and GLESC::Physics::PhysicsManager::updateTransform().
Member Data Documentation
collisionManager
Physics::CollisionManager& GLESC::ECS::PhysicsCollisionSystem::collisionManager private
Definition at line 29 of file PhysicsCollisionSystem.h.
Referenced by update().
physicsManager
Physics::PhysicsManager& GLESC::ECS::PhysicsCollisionSystem::physicsManager private
Definition at line 28 of file PhysicsCollisionSystem.h.
Referenced by update().
The documentation for this class was generated from the following files:
PhysicsCollisionSystem.h
PhysicsCollisionSystem.cpp