GLESC: GLESC::GAPI::VertexBufferLayout Class Reference
GLESC::GAPI::VertexBufferLayout Class Reference
#include <VertexBufferLayout.h>
Public Member Functions
VertexBufferLayout ()
const std::vector< VertexBufferElement > & getElements () const
uint32_t getStride () const
void push (Enums::Types type, Bool normalized=Bool::False)
Private Attributes
std::vector< VertexBufferElement > elements
UInt stride
Detailed Description
Definition at line 20 of file VertexBufferLayout.h.
Constructor & Destructor Documentation
VertexBufferLayout()
GLESC::GAPI::VertexBufferLayout::VertexBufferLayout () inline
Definition at line 23 of file VertexBufferLayout.h.
: stride(0) {}
Member Function Documentation
getElements()
const std::vector< VertexBufferElement > & GLESC::GAPI::VertexBufferLayout::getElements () const inline
Definition at line 25 of file VertexBufferLayout.h.
{ return elements; }
References elements.
Referenced by GLESC::GAPI::VertexArray::addBuffer(), and GLESC::GAPI::VertexInstanceBuffer::setupInstanceAttributes().
getStride()
uint32_t GLESC::GAPI::VertexBufferLayout::getStride () const inline
Definition at line 26 of file VertexBufferLayout.h.
{ return stride; }
References stride.
Referenced by GLESC::GAPI::VertexArray::addBuffer(), and GLESC::GAPI::VertexInstanceBuffer::setupInstanceAttributes().
push()
void VertexBufferLayout::push (Enums::Types type, Bool normalized = Bool::False)
Definition at line 15 of file VertexBufferLayout.cpp.
{
    auto typeSize = getTypeSize(type);
    elements.push_back({type, normalized});
    stride += static_cast<UInt>(typeSize);
}
References elements, GLESC::isIterable_v, and stride.
Referenced by GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
Member Data Documentation
elements
std::vector<VertexBufferElement> GLESC::GAPI::VertexBufferLayout::elements private
Definition at line 31 of file VertexBufferLayout.h.
Referenced by getElements(), and push().
stride
UInt GLESC::GAPI::VertexBufferLayout::stride private
Definition at line 32 of file VertexBufferLayout.h.
Referenced by getStride(), and push().
The documentation for this class was generated from the following files:
VertexBufferLayout.h
VertexBufferLayout.cpp