GLESC: GLESC::ECS::LightSystem Class Reference
GLESC::ECS::LightSystem Class Reference
#include <LightSystem.h>
Public Member Functions
LightSystem (ECSCoordinator &ecs, Render::Renderer &renderer)
Default constructor.
void update () override
Updates the system.
Public Member Functions inherited from GLESC::ECS::System
System (ECSCoordinator &ecs, const SystemName &name)
Constructs a system with a name and a reference to the ECS coordinator.
virtual ~System ()=default
template<class Component >
void addComponentRequirement ()
Adds a component requirement to the system.
std::unordered_map< EntityName, EntityID > getAllEntities () const
Gets all the entities in the ECS.
const std::set< EntityID > & getAssociatedEntities () const
Gets the entities associated with the system.
std::vector< IComponent * > getComponents (EntityID entityId) const
Gets the components of an entity.
EntityID getEntity (const EntityName &entityName) const
Gets the ID of an entity.
const EntityMetadata & getEntityMetadata (EntityID entityId) const
Gets the metadata of an entity.
const EntityName & getEntityName (EntityID entityId) const
Gets the name of an entity.
Private Attributes
Render::Renderer & renderer
Additional Inherited Members
Protected Member Functions inherited from GLESC::ECS::System
template<class Component >
Component & getComponent (EntityID entityId)
Gets the component of an entity.
Protected Attributes inherited from GLESC::ECS::System
EntityID nullEntity = EntityManager::nullEntity
Easy access to the value of nullEntity.
Detailed Description
Definition at line 16 of file LightSystem.h.
Constructor & Destructor Documentation
LightSystem()
GLESC::ECS::LightSystem::LightSystem (ECSCoordinator & ecs, Render::Renderer & renderer)
Default constructor.
Definition at line 17 of file LightSystem.cpp.
                                                                          : System(ecs, "LightSystem"),
        renderer(renderer) {
        addComponentRequirement<LightComponent>();
        addComponentRequirement<TransformComponent>();
    }
References GLESC::isIterable_v.
Member Function Documentation
update()
void GLESC::ECS::LightSystem::update () override virtual
Updates the system.
This method is called every frame This must be implemented by the derived class, and the derived class must know what to do with the entities that are associated with the system.
Implements GLESC::ECS::System.
Definition at line 23 of file LightSystem.cpp.
{
        if (renderer.hasRenderBeenCalledThisFrame()) {
            renderer.clearLightData();
            for (const auto& entity : getAssociatedEntities()) {
                auto& light = getComponent<LightComponent>(entity);
                auto& transform = getComponent<TransformComponent>(entity);
                renderer.sendLightPoint(light.light, transform.transform);
                HudItemsManager::addItem(HudItemType::LIGHT_SPOT, transform.transform.getPosition());
            }
        }
    }
References HudItemsManager::addItem(), GLESC::Render::Renderer::clearLightData(), GLESC::ECS::System::getAssociatedEntities(), GLESC::Render::Renderer::hasRenderBeenCalledThisFrame(), GLESC::isIterable_v, LIGHT_SPOT, renderer, and GLESC::Render::Renderer::sendLightPoint().
Member Data Documentation
renderer
Render::Renderer& GLESC::ECS::LightSystem::renderer private
Definition at line 25 of file LightSystem.h.
Referenced by update().
The documentation for this class was generated from the following files:
LightSystem.h
LightSystem.cpp