GLESC: GLESC::Math::Matrix< Type, N, M > Class Template Reference
GLESC::Math::Matrix< Type, N, M > Class Template Reference
Matrix class. Represents a matrix of N rows and M columns.
#include <Matrix.h>
Classes
class MatrixIterator
Iterator class for the matrix.
Public Types
using ConstIterator = MatrixIterator< const GLESC::Math::Matrix< Type, N, M >, const MatrixRow< Type, M >, const Type >
Iterator class for the matrix.
using Iterator = MatrixIterator< GLESC::Math::Matrix< Type, N, M >, MatrixRow< Type, M >, Type >
Iterator class for the matrix.
Public Member Functions
Matrix ()
Constructs a matrix with all elements set to zero.
Matrix (const Matrix &other)
Copy constructor.
template<typename OtherType , size_t OtherN, size_t OtherM>
Matrix (const Matrix< OtherType, OtherN, OtherM > &other)
Constructor from another matrix.
Matrix (const MatrixData< Type, N, M > &&other)
Constructor from MatrixData.
Matrix (const MatrixData< Type, N, M > &other)
Constructor from a 2D array.
Matrix (const Type diagonal)
Constructs a matrix with the diagonal elements set to the given value.
Matrix (const Type(&data)[N][M])
Constructor array list of elements.
Matrix (Matrix &&other) noexcept
Move constructor.
Iterator begin ()
Returns an iterator to the beginning of the matrix.
ConstIterator begin () const
Returns a const iterator to the beginning of the matrix.
Type determinant () const
Calculates the determinant of the matrix.
Iterator end ()
Returns an iterator to the end of the matrix.
ConstIterator end () const
Returns a const iterator to the end of the matrix.
const MatrixRow< Type, M > & get (size_t i) const
Access operator for the matrix, getters are always const.
const Type & get (size_t i, size_t j) const
Access operator for the matrix, getters are always const.
Matrix< Type, N, N > inverse () const
Calculates the inverse of the matrix.
bool isValidViewMatrix () const
Checks if the matrix is a valid view matrix.
template<typename PosType , typename RotType , typename ScaleType >
Matrix & makeModelMatrix (const Vector< PosType, 3 > &position, const Vector< RotType, 3 > &rotationRads, const Vector< ScaleType, 3 > &scale)
Creates a model matrix from the given position, rotation and scale vectors.
template<typename ModelType >
Matrix & makeNormalMatrix (const Matrix< ModelType, 4, 4 > &MVMat)
Creates a normal matrix from the given model-view matrix.
Matrix & makeProjectionMatrix (float fovDegrees, float nearPlane, float farPlane, float viewWidth, float viewHeight)
Creates a projection matrix from the given fov, aspect ratio, near and far planes.
template<typename RotType >
Matrix & makeRotationMatrix (const Vector< RotType, 3 > &rotationRads)
Creates a rotation matrix from the given rotation vector.
template<typename ScaleType >
Matrix & makeScaleMatrix (const Vector< ScaleType, 3 > &scale)
Creates a scale matrix from the given scale vector.
template<typename PosType >
Matrix & makeTranslationMatrix (const Vector< PosType, 3 > &position)
Creates a translation matrix from the given position vector.
Matrix & makeViewMatrixEye (const Vector< Type, 3 > &eye, const Vector< Type, 3 > &target, const Vector< Type, 3 > &up)
Creates a view matrix from the given position, rotation and scale vectors.
Matrix & makeViewMatrixPosRot (const Vector< Type, 3 > &position, const Vector< Type, 3 > &rotation)
Creates a view matrix from the given position and rotation vectors.
bool operator!= (const Matrix &rhs) const
Inequality operator.
template<size_t X>
auto operator* (const Matrix< Type, X, N > &other) const
Multiplying Matrix by Matrix.
Vector< Type, N > operator* (const Vector< Type, M > &other) const
Multiplying Matrix by Vector.
Matrix operator* (Type scalar) const
Multiplying Matrix by scalar.
Matrix & operator*= (const Matrix &rhs)
In-place element-wise multiplication with another matrix.
Matrix & operator*= (Type scalar)
In-place scalar multiplication.
Matrix operator+ (const Matrix &rhs) const
Adding two matrices, element-wise.
Matrix operator+ (Type scalar) const
Adding a scalar to the matrix.
Matrix & operator+= (const Matrix &rhs)
In-place element-wise addition with another matrix.
Matrix & operator+= (Type rhs)
In-place scalar addition.
Matrix operator- () const
Negating the matrix.
Matrix operator- (const Matrix &rhs) const
Subtracting two matrices, element-wise.
Matrix operator- (Type scalar) const
Subtracting a scalar from the matrix.
Matrix & operator-= (const Matrix &rhs)
In-place element-wise subtraction with another matrix.
Matrix & operator-= (Type rhs)
In-place scalar subtraction.
template<size_t X>
Matrix operator/ (const Matrix< Type, M, X > &rhs) const
Matrix division by matrix.
Matrix operator/ (Type scalar) const
Division of matrix by scalar.
Matrix & operator/= (const Matrix &rhs)
In-place division by another matrix.
Matrix & operator/= (Type scalar)
In-place scalar division.
Matrix & operator= (const Matrix &other) noexcept
Copy assignment operator.
template<typename OtherType >
constexpr Matrix & operator= (const Matrix< OtherType, N, M > &other) noexcept
Copy assignment operator.
template<typename OtherType , size_t OtherN, size_t OtherM>
constexpr Matrix & operator= (const Matrix< OtherType, OtherN, OtherM > &other) noexcept
Copy assignment operator for different size matrices.
template<typename OtherType , size_t OtherN, size_t OtherM>
constexpr Matrix & operator= (const MatrixData< OtherType, OtherN, OtherM > &&other) noexcept
Copy assignment operator for MatrixData of different size.
constexpr Matrix & operator= (Matrix &&rhs) noexcept
Move assignment operator.
constexpr Matrix & operator= (MatrixData< Type, N, M > &&other) noexcept
constexpr Matrix & operator= (Type(&data)[N][M])
Assignment operator from a 2D array.
bool operator== (const Matrix &rhs) const
Equality operator.
std::array< Type, M > & operator[] (size_t index)
Access operator for the matrix.
const std::array< Type, M > & operator[] (size_t index) const
Access operator for the matrix, getters are always const.
size_t rank ()
Calculates the rank of the matrix.
std::string toString () const
Gets the string representation of the matrix.
Vector< Type, N > toVector () const
Transforms the matrix into a vector.
Matrix< Type, M, N > transpose () const
Transposes the matrix.
Static Public Member Functions
static size_t cols ()
Get the number of columns in the matrix.
static size_t rows ()
Get the number of rows in the matrix.
Public Attributes
MatrixData< Type, N, M > data {}
Matrix data.
Private Member Functions
S_ASSERT_TRUE (N > 0 &&M > 0, "Matrix must have at least one row and one column.")
Detailed Description
template<typename Type, size_t N, size_t M>
class GLESC::Math::Matrix< Type, N, M >
Matrix class. Represents a matrix of N rows and M columns.
This matrix is row-major.
Template Parameters
Type The type of the elements in the matrix
N The number of rows in the matrix
M The number of columns in the matrix
Definition at line 30 of file Matrix.h.
Member Typedef Documentation
ConstIterator
template<typename Type , size_t N, size_t M> using GLESC::Math::Matrix< Type, N, M >::ConstIterator = MatrixIterator<const GLESC::Math::Matrix<Type, N, M>, const MatrixRow<Type, M>, const Type>
Iterator class for the matrix.
Template Parameters
MatrixType The matrix, we use this to allow reusing the iterator for const and non-const matrices
ValueType The type of the elements in the matrix
Definition at line 779 of file Matrix.h.
Iterator
template<typename Type , size_t N, size_t M> using GLESC::Math::Matrix< Type, N, M >::Iterator = MatrixIterator<GLESC::Math::Matrix<Type, N, M>, MatrixRow<Type, M>, Type>
Iterator class for the matrix.
Template Parameters
MatrixType The matrix, we use this to allow reusing the iterator for const and non-const matrices
ValueType The type of the elements in the matrix
Definition at line 773 of file Matrix.h.
Constructor & Destructor Documentation
Matrix() [1/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix () inline
Constructs a matrix with all elements set to zero.
Definition at line 40 of file Matrix.h.
                 {
            MatrixAlgorithms::setMatrixZero(this->data);
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::setMatrixZero().
Matrix() [2/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (const Type diagonal) inline explicit
Constructs a matrix with the diagonal elements set to the given value.
Parameters
diagonal The value to set the diagonal elements to.
Definition at line 47 of file Matrix.h.
{
            MatrixAlgorithms::setMatrixDiagonal(this->data, diagonal);
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::setMatrixDiagonal().
Matrix() [3/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (const Type(&) data[N][M]) inline explicit
Constructor array list of elements.
The array list must have N * M elements
Parameters
data
Definition at line 56 of file Matrix.h.
{
            MatrixAlgorithms::setMatrix(this->data, data);
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::setMatrix().
Matrix() [4/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (const MatrixData< Type, N, M > & other) inline explicit
Constructor from a 2D array.
Parameters
other The 2D array to copy from
Definition at line 64 of file Matrix.h.
{
            MatrixAlgorithms::setMatrix(this->data, other);
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::setMatrix().
Matrix() [5/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (const MatrixData< Type, N, M > && other) inline explicit
Constructor from MatrixData.
See also
MatrixData
Parameters
other The 2D array to move from
Definition at line 72 of file Matrix.h.
{
            MatrixAlgorithms::setMatrix(this->data, other);
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::setMatrix().
Matrix() [6/8]
template<typename Type , size_t N, size_t M> template<typename OtherType , size_t OtherN, size_t OtherM> GLESC::Math::Matrix< Type, N, M >::Matrix (const Matrix< OtherType, OtherN, OtherM > & other) inline explicit
Constructor from another matrix.
Parameters
other The matrix to copy from
Definition at line 80 of file Matrix.h.
{
            MatrixAlgorithms::resizeMatrix(other.data, this->data);
        }
References GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::resizeMatrix().
Matrix() [7/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (const Matrix< Type, N, M > & other) inline
Copy constructor.
Parameters
other The matrix to copy from
Definition at line 89 of file Matrix.h.
{
            MatrixAlgorithms::copyMatrix(this->data, other.data);
        }
References GLESC::Math::MatrixAlgorithms::copyMatrix(), and GLESC::Math::Matrix< Type, N, M >::data.
Matrix() [8/8]
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::Matrix (Matrix< Type, N, M > && other) inline noexcept
Move constructor.
Parameters
other The matrix to move from
Definition at line 97 of file Matrix.h.
{
            MatrixAlgorithms::moveMatrix(this->data, std::move(other.data));
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::moveMatrix().
Member Function Documentation
begin() [1/2]
template<typename Type , size_t N, size_t M> Iterator GLESC::Math::Matrix< Type, N, M >::begin () inline
Returns an iterator to the beginning of the matrix.
Returns
The iterator to the beginning of the matrix
Definition at line 786 of file Matrix.h.
{ return Iterator(this, 0); }
begin() [2/2]
template<typename Type , size_t N, size_t M> ConstIterator GLESC::Math::Matrix< Type, N, M >::begin () const inline
Returns a const iterator to the beginning of the matrix.
Returns
The const iterator to the beginning of the matrix
Definition at line 796 of file Matrix.h.
{ return ConstIterator(this, 0); }
cols()
template<typename Type , size_t N, size_t M> static size_t GLESC::Math::Matrix< Type, N, M >::cols () inline static
Get the number of columns in the matrix.
Returns
The number of columns
Definition at line 457 of file Matrix.h.
{
            return M;
        }
determinant()
template<typename Type , size_t N, size_t M> Type GLESC::Math::Matrix< Type, N, M >::determinant () const inline
Calculates the determinant of the matrix.
The determinant is a value that can be calculated for square matrices only
Returns
The determinant of the matrix
Definition at line 525 of file Matrix.h.
{
            return MatrixAlgorithms::laplaceExpansionDeterminant(this->data);
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::laplaceExpansionDeterminant().
end() [1/2]
template<typename Type , size_t N, size_t M> Iterator GLESC::Math::Matrix< Type, N, M >::end () inline
Returns an iterator to the end of the matrix.
Returns
The iterator to the end of the matrix
Definition at line 791 of file Matrix.h.
{ return Iterator(this, N); }
end() [2/2]
template<typename Type , size_t N, size_t M> ConstIterator GLESC::Math::Matrix< Type, N, M >::end () const inline
Returns a const iterator to the end of the matrix.
Returns
The const iterator to the end of the matrix
Definition at line 801 of file Matrix.h.
{ return ConstIterator(this, N); }
get() [1/2]
template<typename Type , size_t N, size_t M> const MatrixRow< Type, M > & GLESC::Math::Matrix< Type, N, M >::get (size_t i) const inline
Access operator for the matrix, getters are always const.
Parameters
i The row index
Returns
The const row at the given index
Definition at line 441 of file Matrix.h.
{
            return data[i];
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
get() [2/2]
template<typename Type , size_t N, size_t M> const Type & GLESC::Math::Matrix< Type, N, M >::get (size_t i, size_t j) const inline
Access operator for the matrix, getters are always const.
Parameters
i The row index
j The column index
Returns
The value at the given row and column
Definition at line 432 of file Matrix.h.
{
            return data[i][j];
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
inverse()
template<typename Type , size_t N, size_t M> Matrix< Type, N, N > GLESC::Math::Matrix< Type, N, M >::inverse () const inline
Calculates the inverse of the matrix.
The inverse of a matrix is a matrix that when multiplied with the original matrix results in the identity M*M^-1 = I
Returns
The inverse of the matrix
Definition at line 534 of file Matrix.h.
{
            Matrix<Type, N, N> inv;
            MatrixAlgorithms::matrixInverse(this->data, inv.data);
            return inv;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::matrixInverse().
isValidViewMatrix()
template<typename Type , size_t N, size_t M> bool GLESC::Math::Matrix< Type, N, M >::isValidViewMatrix () const inline
Checks if the matrix is a valid view matrix.
A valid view matrix is a matrix that is ivertible
Returns
True if the matrix is a valid view matrix, false otherwise
Definition at line 649 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "View matrix can only be created for 4x4 matrices");
            return MatrixAlgorithms::isValidViewMatrix(this->data);
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::MatrixAlgorithms::isValidViewMatrix(), and S_ASSERT_TRUE.
makeModelMatrix()
template<typename Type , size_t N, size_t M> template<typename PosType , typename RotType , typename ScaleType > Matrix & GLESC::Math::Matrix< Type, N, M >::makeModelMatrix (const Vector< PosType, 3 > & position, const Vector< RotType, 3 > & rotationRads, const Vector< ScaleType, 3 > & scale) inline
Creates a model matrix from the given position, rotation and scale vectors.
This operation will overwrite the current matrix with the result of the model matrix
Template Parameters
PosType The type of the position vector
RotType The type of the rotation vector
ScaleType The type of the scale vector
Parameters
position The position vector
rotationRads The rotation vector
scale The scale vector
Definition at line 551 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "Model matrix can only be created for 4x4 matrices");
            MatrixMixedAlgorithms::calculateModelMatrix<Type, PosType, RotType, ScaleType>
                (position.data, rotationRads.data, scale.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Transform::Transform::Transform(), and GLESC::Transform::Transform::getModelMatrix().
makeNormalMatrix()
template<typename Type , size_t N, size_t M> template<typename ModelType > Matrix & GLESC::Math::Matrix< Type, N, M >::makeNormalMatrix (const Matrix< ModelType, 4, 4 > & MVMat) inline
Creates a normal matrix from the given model-view matrix.
This operation will overwrite the current matrix with the result of the normal matrix The normal matrix is a 3x3 matrix that is the inverse transpose of the model-view matrix
Template Parameters
ModelType The type of the model-view matrix
Parameters
MVMat The model-view matrix
Definition at line 610 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 3 && M == 3, "Normal matrix can only be created for 4x4 matrices");
            MatrixAlgorithms::calculateNormalMatrix(MVMat.data, this->data);
            return *this;
        }
References GLESC::Math::MatrixAlgorithms::calculateNormalMatrix(), GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Render::Renderer::render().
makeProjectionMatrix()
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::makeProjectionMatrix (float fovDegrees, float nearPlane, float farPlane, float viewWidth, float viewHeight) inline
Creates a projection matrix from the given fov, aspect ratio, near and far planes.
This operation will overwrite the current matrix with the result of the projection matrix
Parameters
fovDegrees The field of view in radians
nearPlane The near plane
farPlane The far plane
viewWidth The width of the view
viewHeight The height of the view
Definition at line 663 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "Projection matrix can only be created for 4x4 matrices");
            MatrixAlgorithms::perspective<Type>(Math::radians(fovDegrees), nearPlane, farPlane, viewWidth, viewHeight,
                                                this->data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::radians(), and S_ASSERT_TRUE.
Referenced by GLESC::Render::Renderer::createProjectionMatrix(), and GLESC::Render::Renderer::start().
makeRotationMatrix()
template<typename Type , size_t N, size_t M> template<typename RotType > Matrix & GLESC::Math::Matrix< Type, N, M >::makeRotationMatrix (const Vector< RotType, 3 > & rotationRads) inline
Creates a rotation matrix from the given rotation vector.
This operation will overwrite the current matrix with the result of the rotation matrix The rotation matrix is a 4x4 matrix with the rotation values in the upper left 3x3 matrix
Template Parameters
RotType The type of the rotation vector
Parameters
rotationRads The rotation vector
Definition at line 582 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "Rotation matrix can only be created for 4x4 matrices");
            MatrixMixedAlgorithms::getRotate3DMatrix<Type, RotType>(rotationRads.data, this->data);
            return *this;
        }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Transform::Transform::getRotationMatrix().
makeScaleMatrix()
template<typename Type , size_t N, size_t M> template<typename ScaleType > Matrix & GLESC::Math::Matrix< Type, N, M >::makeScaleMatrix (const Vector< ScaleType, 3 > & scale) inline
Creates a scale matrix from the given scale vector.
This operation will overwrite the current matrix with the result of the scale matrix The scale matrix is a 4x4 matrix with the scale values in the diagonal
Template Parameters
ScaleType The type of the scale vector
Parameters
scale The scale vector
Definition at line 596 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "Scale matrix can only be created for 4x4 matrices");
            MatrixAlgorithms::getScaleMatrix<Type, ScaleType>(scale.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Transform::Transform::getScaleMatrix().
makeTranslationMatrix()
template<typename Type , size_t N, size_t M> template<typename PosType > Matrix & GLESC::Math::Matrix< Type, N, M >::makeTranslationMatrix (const Vector< PosType, 3 > & position) inline
Creates a translation matrix from the given position vector.
This operation will overwrite the current matrix with the result of the translation matrix The translation matrix is a 4x4 matrix with the translation values in the last column
Template Parameters
PosType The type of the position vector
Parameters
position The position vector
Definition at line 568 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "Translation matrix can only be created for 4x4 matrices");
            MatrixAlgorithms::getTranslationMatrix<Type, PosType>(position.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Transform::Transform::getTranslationMatrix().
makeViewMatrixEye()
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::makeViewMatrixEye (const Vector< Type, 3 > & eye, const Vector< Type, 3 > & target, const Vector< Type, 3 > & up) inline
Creates a view matrix from the given position, rotation and scale vectors.
This operation will overwrite the current matrix with the result of the view matrix
Parameters
eye The position of the camera
target The target of the camera
up The up vector of the camera
Definition at line 623 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "View matrix can only be created for 4x4 matrices");
            MatrixMixedAlgorithms::calculateViewMatrixEye(eye.data, target.data, up.data, data);
            return *this;
        }
References GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixEye(), GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_TRUE.
makeViewMatrixPosRot()
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot (const Vector< Type, 3 > & position, const Vector< Type, 3 > & rotation) inline
Creates a view matrix from the given position and rotation vectors.
This operation will overwrite the current matrix with the result of the view matrix
Parameters
position The position of the camera
rotation The rotation of the camera
Definition at line 637 of file Matrix.h.
{
            S_ASSERT_TRUE(N == 4 && M == 4, "View matrix can only be created for 4x4 matrices");
            MatrixMixedAlgorithms::calculateViewMatrixPosRot(position.data, rotation.data, data);
            return *this;
        }
References GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot(), GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Render::Renderer::createViewMatrix(), and GLESC::Render::Renderer::start().
operator!=()
template<typename Type , size_t N, size_t M> bool GLESC::Math::Matrix< Type, N, M >::operator!= (const Matrix< Type, N, M > & rhs) const inline
Inequality operator.
Parameters
rhs The matrix to compare with
Returns
True if the matrices are not equal, false otherwise
Definition at line 486 of file Matrix.h.
{
            return !(*this == rhs);
        }
References GLESC::isIterable_v.
operator*() [1/3]
template<typename Type , size_t N, size_t M> template<size_t X> auto GLESC::Math::Matrix< Type, N, M >::operator* (const Matrix< Type, X, N > & other) const inline
Multiplying Matrix by Matrix.
A matrix NxM multiplied by a matrix MxX results in a matrix N x X For example: | 1 2 3 | | 7 8 | | 58 64 | | 4 5 6 | * | 9 10 | = | 139 154 | | 11 12 | 2x3 * 3x2 = 2x2
Template Parameters
X
Parameters
other
Returns
Definition at line 328 of file Matrix.h.
{
            if constexpr (MatrixAlgorithms::columnMajorMatrix) {
                Matrix<Type, X, M> result;
                MatrixAlgorithms::matrixMatrixMulColMaj(this->data, other.data, result.data);
                return result;
            }
            else {
                Matrix<Type, N, X> result;
                MatrixAlgorithms::matrixMatrixMulRowMaj(other.data, this->data, result.data);
                return result;
            }
        }
References GLESC::Math::MatrixAlgorithms::columnMajorMatrix, GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixMatrixMulColMaj(), and GLESC::Math::MatrixAlgorithms::matrixMatrixMulRowMaj().
operator*() [2/3]
template<typename Type , size_t N, size_t M> Vector< Type, N > GLESC::Math::Matrix< Type, N, M >::operator* (const Vector< Type, M > & other) const inline
Multiplying Matrix by Vector.
A matrix NxM multiplied by a vector M results in a vector N For example: | 1 2 3 | | 7 | | 58 | | 4 5 6 | * | 9 | = | 139 | | 11 | 2x3 * 3 = 2
Template Parameters
X
Parameters
other
Returns
Definition at line 353 of file Matrix.h.
{
            Vector<Type, N> resultVector;
            if constexpr (MatrixAlgorithms::columnMajorMatrix) {
                MatrixAlgorithms::matrixVectorMulColMaj(this->data, other.data, resultVector.data);
            }
            else {
                MatrixAlgorithms::matrixVectorMulRowMaj(other.data, this->data, resultVector.data);
            }
            return resultVector;
        }
References GLESC::Math::MatrixAlgorithms::columnMajorMatrix, GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixVectorMulColMaj(), and GLESC::Math::MatrixAlgorithms::matrixVectorMulRowMaj().
operator*() [3/3]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator* (Type scalar) const inline
Multiplying Matrix by scalar.
Multiplies each element of the matrix by the scalar
Parameters
scalar The scalar to multiply by
Returns
The result of the multiplication
Definition at line 370 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixScalarMul(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarMul().
operator*=() [1/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator*= (const Matrix< Type, N, M > & rhs) inline
In-place element-wise multiplication with another matrix.
Parameters
rhs The matrix to multiply with.
Returns
Reference to the modified instance.
Definition at line 178 of file Matrix.h.
{
            S_ASSERT_TRUE(N == M, "Matrix must be square for in-place multiplication");
            MatrixAlgorithms::matrixMatrixMulInPlace(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace(), and S_ASSERT_TRUE.
operator*=() [2/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator*= (Type scalar) inline
In-place scalar multiplication.
Parameters
scalar The scalar to multiply with.
Returns
Reference to the modified instance.
Definition at line 189 of file Matrix.h.
{
            MatrixAlgorithms::matrixScalarMul(this->data, scalar, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarMul().
operator+() [1/2]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator+ (const Matrix< Type, N, M > & rhs) const inline
Adding two matrices, element-wise.
Parameters
rhs The matrix to add
Returns
The result of the addition
Definition at line 263 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixAdd(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixAdd().
operator+() [2/2]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator+ (Type scalar) const inline
Adding a scalar to the matrix.
Adds a scalar to each element of the matrix
Parameters
scalar The scalar to add
Returns
The result of the addition
Definition at line 275 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixScalarAdd(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarAdd().
operator+=() [1/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator+= (const Matrix< Type, N, M > & rhs) inline
In-place element-wise addition with another matrix.
Parameters
rhs The matrix to add with.
Returns
Reference to the modified instance.
Definition at line 209 of file Matrix.h.
{
            MatrixAlgorithms::matrixAdd(this->data, rhs.data, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixAdd().
operator+=() [2/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator+= (Type rhs) inline
In-place scalar addition.
Parameters
rhs The scalar to add.
Returns
Reference to the modified instance.
Definition at line 199 of file Matrix.h.
{
            MatrixAlgorithms::matrixScalarAdd(this->data, rhs, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarAdd().
operator-() [1/3]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator- () const inline
Negating the matrix.
Negates each element of the matrix
Returns
The negated matrix
Definition at line 309 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixScalarMul(this->data, Type(-1), result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::matrixScalarMul().
operator-() [2/3]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator- (const Matrix< Type, N, M > & rhs) const inline
Subtracting two matrices, element-wise.
Parameters
rhs The matrix to subtract
Returns
The result of the subtraction
Definition at line 286 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixSub(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixSub().
operator-() [3/3]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator- (Type scalar) const inline
Subtracting a scalar from the matrix.
Subtracts a scalar from each element of the matrix
Parameters
scalar The scalar to subtract
Returns
The result of the subtraction
Definition at line 298 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixScalarSub(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarSub().
operator-=() [1/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator-= (const Matrix< Type, N, M > & rhs) inline
In-place element-wise subtraction with another matrix.
Parameters
rhs The matrix to subtract with.
Returns
Reference to the modified instance.
Definition at line 219 of file Matrix.h.
{
            MatrixAlgorithms::matrixSub(this->data, rhs.data, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixSub().
operator-=() [2/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator-= (Type rhs) inline
In-place scalar subtraction.
Parameters
rhs The scalar to subtract.
Returns
Reference to the modified instance.
Definition at line 229 of file Matrix.h.
{
            MatrixAlgorithms::matrixScalarSub(this->data, rhs, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarSub().
operator/() [1/2]
template<typename Type , size_t N, size_t M> template<size_t X> Matrix GLESC::Math::Matrix< Type, N, M >::operator/ (const Matrix< Type, M, X > & rhs) const inline
Matrix division by matrix.
The matrix division by matrix is defined as the multiplication of the first matrix by the inverse of the second matrix
Parameters
rhs
Returns
Definition at line 398 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixMatrixDiv(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixMatrixDiv().
operator/() [2/2]
template<typename Type , size_t N, size_t M> Matrix GLESC::Math::Matrix< Type, N, M >::operator/ (Type scalar) const inline
Division of matrix by scalar.
Divides each element of the matrix by the scalar
Parameters
scalar The scalar to divide by
Returns
The result of the division
Definition at line 383 of file Matrix.h.
{
            Matrix result;
            MatrixAlgorithms::matrixScalarDiv(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarDiv().
operator/=() [1/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator/= (const Matrix< Type, N, M > & rhs) inline
In-place division by another matrix.
Parameters
rhs The matrix to divide by.
Returns
Reference to the modified instance.
Exceptions
MathException if division by zero
Definition at line 251 of file Matrix.h.
{
            MatrixAlgorithms::matrixMatrixDiv(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::matrixMatrixDiv().
operator/=() [2/2]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator/= (Type scalar) inline
In-place scalar division.
Parameters
scalar The scalar to divide by.
Returns
Reference to the modified instance.
Exceptions
MathException if division by zero
Definition at line 240 of file Matrix.h.
{
            MatrixAlgorithms::matrixScalarDiv(this->data, scalar, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::matrixScalarDiv().
operator=() [1/7]
template<typename Type , size_t N, size_t M> Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (const Matrix< Type, N, M > & other) inline noexcept
Copy assignment operator.
Parameters
other The matrix to copy from.
Definition at line 142 of file Matrix.h.
{
            MatrixAlgorithms::copyMatrix(this->data, other.data);
            return *this;
        }
References GLESC::Math::MatrixAlgorithms::copyMatrix(), GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
operator=() [2/7]
template<typename Type , size_t N, size_t M> template<typename OtherType > constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (const Matrix< OtherType, N, M > & other) inline constexpr noexcept
Copy assignment operator.
Parameters
other The matrix to copy from.
Returns
Reference to the modified instance.
Definition at line 115 of file Matrix.h.
{
            MatrixAlgorithms::copyMatrix(this->data, other.data);
            return *this;
        }
References GLESC::Math::MatrixAlgorithms::copyMatrix(), GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
operator=() [3/7]
template<typename Type , size_t N, size_t M> template<typename OtherType , size_t OtherN, size_t OtherM> constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (const Matrix< OtherType, OtherN, OtherM > & other) inline constexpr noexcept
Copy assignment operator for different size matrices.
Parameters
other The matrix to copy from. Can be of different size.
Definition at line 124 of file Matrix.h.
{
            MatrixAlgorithms::resizeMatrix(this->data, other.data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::resizeMatrix().
operator=() [4/7]
template<typename Type , size_t N, size_t M> template<typename OtherType , size_t OtherN, size_t OtherM> constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (const MatrixData< OtherType, OtherN, OtherM > && other) inline constexpr noexcept
Copy assignment operator for MatrixData of different size.
Parameters
other The matrix to copy from. Can be of different size.
Definition at line 133 of file Matrix.h.
{
            MatrixAlgorithms::resizeMatrix(this->data, other);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::resizeMatrix().
operator=() [5/7]
template<typename Type , size_t N, size_t M> constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (Matrix< Type, N, M > && rhs) inline constexpr noexcept
Move assignment operator.
Parameters
rhs The matrix to move from.
Returns
Reference to the modified instance.
Definition at line 158 of file Matrix.h.
{
            MatrixAlgorithms::moveMatrix(this->data, std::move(rhs.data));
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::moveMatrix().
operator=() [6/7]
template<typename Type , size_t N, size_t M> constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (MatrixData< Type, N, M > && other) inline constexpr noexcept
Definition at line 148 of file Matrix.h.
{
            MatrixAlgorithms::moveMatrix(this->data, std::move(other));
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::isIterable_v, and GLESC::Math::MatrixAlgorithms::moveMatrix().
operator=() [7/7]
template<typename Type , size_t N, size_t M> constexpr Matrix & GLESC::Math::Matrix< Type, N, M >::operator= (Type(&) data[N][M]) inline constexpr
Assignment operator from a 2D array.
Parameters
data 2D array to assign from.
Returns
Reference to the modified instance.
Definition at line 168 of file Matrix.h.
{
            MatrixAlgorithms::setMatrix(this->data, data);
            return *this;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::setMatrix().
operator==()
template<typename Type , size_t N, size_t M> bool GLESC::Math::Matrix< Type, N, M >::operator== (const Matrix< Type, N, M > & rhs) const inline
Equality operator.
Parameters
rhs The matrix to compare with
Returns
True if the matrices are equal, false otherwise
Definition at line 470 of file Matrix.h.
{
            for (size_t i = 0; i < N; ++i) {
                for (size_t k = 0; k < M; ++k) {
                    if (!eq(this->data[i][k], rhs.data[i][k])) {
                        return false;
                    }
                }
            }
            return true;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::eq(), and GLESC::isIterable_v.
operator[]() [1/2]
template<typename Type , size_t N, size_t M> std::array< Type, M > & GLESC::Math::Matrix< Type, N, M >::operator[] (size_t index) inline
Access operator for the matrix.
Parameters
index The row index
Returns
The row at the given index
Definition at line 422 of file Matrix.h.
{
            return data[index];
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
operator[]() [2/2]
template<typename Type , size_t N, size_t M> const std::array< Type, M > & GLESC::Math::Matrix< Type, N, M >::operator[] (size_t index) const inline
Access operator for the matrix, getters are always const.
Parameters
index The row index
Returns
The const row at the given index
Definition at line 413 of file Matrix.h.
{
            return data[index];
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
rank()
template<typename Type , size_t N, size_t M> size_t GLESC::Math::Matrix< Type, N, M >::rank () inline
Calculates the rank of the matrix.
The rank of a matrix is the maximum number of linearly independent rows or columns. This implementation uses Gaussian elimination.
Returns
size_t representing the rank of the matrix.
Definition at line 680 of file Matrix.h.
{
            return MatrixAlgorithms::gaussianElimination(this->data).rank;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::gaussianElimination().
rows()
template<typename Type , size_t N, size_t M> static size_t GLESC::Math::Matrix< Type, N, M >::rows () inline static
Get the number of rows in the matrix.
Returns
The number of rows
Definition at line 449 of file Matrix.h.
{
            return N;
        }
S_ASSERT_TRUE()
template<typename Type , size_t N, size_t M> GLESC::Math::Matrix< Type, N, M >::S_ASSERT_TRUE (N , 0 && M, 0 , "Matrix< Type, N, M > must have at least one row and one column.") private
toString()
template<typename Type , size_t N, size_t M> std::string GLESC::Math::Matrix< Type, N, M >::toString () const inline
Gets the string representation of the matrix.
The matrix is represented as a string with each row on a new line
Returns
The string representation of the matrix
Definition at line 689 of file Matrix.h.
{
            std::string result;
            for (size_t i = 0; i < N; ++i) {
                result += "[";
                for (size_t j = 0; j < M; ++j) {
                    result += std::to_string(this->data[i][j]);
                    if (j != M - 1) {
                        result += ", ";
                    }
                }
                result += "]\n";
            }
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::isIterable_v.
toVector()
template<typename Type , size_t N, size_t M> Vector< Type, N > GLESC::Math::Matrix< Type, N, M >::toVector () const inline
Transforms the matrix into a vector.
Only works for matrices with one column
The matrix must have one column to be converted to a vector
Returns
The vector representation of the matrix
Definition at line 500 of file Matrix.h.
{
            S_ASSERT_EQUAL(M, 1, "Matrix must have one column to be converted to a vector");
            Vector<Type, N> result;
            MatrixMixedAlgorithms::matrixToVector(this->data, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, GLESC::Math::Vector< Type, N >::data, GLESC::Math::MatrixMixedAlgorithms::matrixToVector(), and S_ASSERT_EQUAL.
transpose()
template<typename Type , size_t N, size_t M> Matrix< Type, M, N > GLESC::Math::Matrix< Type, N, M >::transpose () const inline
Transposes the matrix.
In a transposed matrix, the rows become columns and the columns become rows
Returns
The transposed matrix
Definition at line 512 of file Matrix.h.
{
            Matrix<Type, M, N> result;
            MatrixAlgorithms::transpose(this->data, result.data);
            return result;
        }
References GLESC::Math::Matrix< Type, N, M >::data, and GLESC::Math::MatrixAlgorithms::transpose().
Referenced by TYPED_TEST().
Member Data Documentation
data
template<typename Type , size_t N, size_t M> MatrixData<Type, N, M> GLESC::Math::Matrix< Type, N, M >::data {}
Matrix data.
Matrix data is stored in a vector of vectors M is the number of columns or the width of the matrix N is the number of rows (or vertices) or the height of the matrix
Definition at line 809 of file Matrix.h.
{};
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::determinant(), expectEqMat(), expectNeMat(), generateMatrixWithRandomNumbers(), GLESC::Math::Matrix< Type, N, M >::get(), GLESC::Math::Matrix< Type, N, M >::get(), initializeMatrixWithDifferentValues(), initializeMatrixWithValues(), GLESC::Math::Matrix< Type, N, M >::inverse(), GLESC::Math::Matrix< Type, N, M >::isValidViewMatrix(), GLESC::Math::Matrix< Type, N, M >::makeProjectionMatrix(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixEye(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot(), GLESC::Math::Matrix< Type, N, M >::operator*(), GLESC::Math::Matrix< Type, N, M >::operator*(), GLESC::Math::Matrix< Type, N, M >::operator*(), GLESC::Math::Matrix< Type, N, M >::operator*=(), GLESC::Math::Matrix< Type, N, M >::operator*=(), GLESC::Math::Matrix< Type, N, M >::operator+(), GLESC::Math::Matrix< Type, N, M >::operator+(), GLESC::Math::Matrix< Type, N, M >::operator+=(), GLESC::Math::Matrix< Type, N, M >::operator+=(), GLESC::Math::Matrix< Type, N, M >::operator-(), GLESC::Math::Matrix< Type, N, M >::operator-(), GLESC::Math::Matrix< Type, N, M >::operator-(), GLESC::Math::Matrix< Type, N, M >::operator-=(), GLESC::Math::Matrix< Type, N, M >::operator-=(), GLESC::Math::Matrix< Type, N, M >::operator/(), GLESC::Math::Matrix< Type, N, M >::operator/(), GLESC::Math::Matrix< Type, N, M >::operator/=(), GLESC::Math::Matrix< Type, N, M >::operator/=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator==(), GLESC::Math::Matrix< Type, N, M >::operator[](), GLESC::Math::Matrix< Type, N, M >::operator[](), GLESC::Math::Matrix< Type, N, M >::rank(), GLESC::Math::Matrix< Type, N, M >::toString(), GLESC::Math::Matrix< Type, N, M >::toVector(), GLESC::Math::Matrix< Type, N, M >::transpose(), and TYPED_TEST().
The documentation for this class was generated from the following file:
Matrix.h