GLESC: GLESC::Render::Mesh< VertexT > Class Template Reference
GLESC::Render::Mesh< VertexT > Class Template Reference
A class that represents a mesh.
#include <Mesh.h>
Classes
struct VertexColorParam
Struct with only color and position vertex.
struct VertexTexParam
Struct with only texture UV and position vertex.
Public Types
using Index = unsigned int
Alias for the index type of the mesh. Is unsigned because the index can't be negative.
using Vertex = VertexT
Alias for the vertex, for readability purposes.
Public Member Functions
Mesh ()
Mesh constructor.
Mesh (const Mesh &other)
Mesh (Mesh &&other) noexcept
~Mesh () override=default
void addQuad (const VertexColorParam &v1, const VertexColorParam &v2, const VertexColorParam &v3, const VertexColorParam &v4)
Adds a quad to the mesh, quads are defined by 4 vertices.
void addQuad (Index index1, Index index2, Index index3, Index index4)
Adds a quad to the mesh, quads are defined by 4 vertices.
void addTris (const Vertex &v1, const Vertex &v2, const Vertex &v3)
Adds a tris to the mesh, tris are defined by 3 vertices.
void addTris (const VertexColorParam &a, const VertexColorParam &b, const VertexColorParam &c)
Adds a tris to the mesh, tris are defined by 3 vertices.
void addTris (Index index1, Index index2, Index index3)
Adds a list of indices to the mesh.
Index addVertex (const Vertex &vertexParam)
Adds a vertex to the mesh.
void addVertices (const std::vector< Vertex > &verticesParam)
Adds a list of vertices to the mesh.
void attatchMesh (const Mesh &mesh)
Attaches a mesh to the current mesh.
void clear ()
void finishBuilding ()
const Math::BoundingVolume & getBoundingVolume () const
Math::BoundingVolume & getBoundingVolumeMutable ()
const std::vector< Math::FaceIndices > & getFaces () const
const std::vector< Index > & getIndices () const
std::vector< Vertex > & getModifiableVertices ()
const RenderType & getRenderType () const
std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues () override
Get the updated debugging values of the component.
const std::vector< GLESC::GAPI::Enums::Types > & getVertexLayout () const
const std::vector< Vertex > & getVertices () const
size_t hash () const
Calculates lazily the hash of the mesh. Only recalculates if the mesh has been changed.
bool isBeingBuilt () const
bool isDirty () const
Mesh & operator= (const Mesh &other)
Mesh & operator= (Mesh &&other) noexcept
bool operator== (const Mesh &other) const
To check if a mesh is equal to another mesh we iterate over the vertices and indices and compare them. If the vertices and indices are the same, the meshes are equal.
void reserveFaces (size_t size)
void reserveIndices (size_t size)
void reserveVertices (size_t size)
S_ASSERT_TRUE ((std::is_base_of_v< ColorVertex, VertexT >||std::is_base_of_v< TextureVertex, VertexT >), "Vertex must be a ColorVertex or TextureVertex")
Static assert to ensure that the vertex is a ColorVertex or TextureVertex. As we currently only support these two types of vertices.
void setRenderType (RenderType renderTypeParam)
void startBuilding ()
Starts the building of the mesh.
std::string toString () const override
This converts the mesh to a string.
Public Member Functions inherited from EngineComponent
virtual ~EngineComponent ()=default
virtual std::vector< EntityStatsManager::Value > getDebuggingValues ()
Get the debugging values of the component.
const char * getOwnerName () const
Get the owner name of the component for debugging purposes.
void setOwnerName (const char *ownerName)
Set the owner name of the component for debugging purposes.
Private Member Functions
size_t calculateHash () const
Helper function to calculate the hash of the mesh.
Normal calculateNormal (const Position &p1, const Position &p2, const Position &p3) const
Helper function to automatically calculate the normal of a face with 3 points.
void destroyBuffers () const
This destroys the buffers in the GPU, removing the data with it.
const GLESC::GAPI::IndexBuffer & getIndexBuffer () const
const GLESC::GAPI::VertexArray & getVertexArray () const
const GLESC::GAPI::VertexBuffer & getVertexBuffer () const
void sendToGpuBuffers () const
This method creates GPU buffers and sends the data to the GPU.
Private Attributes
Math::BoundingVolume boundingVolume
The bounding volume of the mesh.
size_t cachedHash = 0
bool dirtyFlag = false
A flag that indicates whether the mesh is dirty.
std::vector< Math::FaceIndices > faces {}
std::mutex facesMutex {}
bool hashDirty = true
std::unique_ptr< GLESC::GAPI::IndexBuffer > indexBuffer
buffer that handles the indices of the mesh in the gpu.
std::vector< Index > indices {}
std::mutex indicesMutex {}
bool isBuilding = false
A flag that indicates whether the mesh is being built.
RenderType renderType
std::unique_ptr< GLESC::GAPI::VertexArray > vertexArray
std::unique_ptr< GLESC::GAPI::VertexBuffer > vertexBuffer
buffer that handles the vertices of the mesh in the gpu.
std::vector< GLESC::GAPI::Enums::Types > vertexLayout
The vertex layout of the mesh.
std::vector< Vertex > vertices {}
std::mutex verticesMutex {}
bool wasDataSentToGpu = false
Friends
class GLESC::Render::Renderer
Detailed Description
template<typename VertexT>
class GLESC::Render::Mesh< VertexT >
A class that represents a mesh.
This is the mesh class for the engine. Is a template class that needs to be instantiated with the types (
See also
Types) of the vertex attributes that the mesh will have. This mesh class contains only the abstraction of the mesh data. This mesh is thread safe, so its safe to modify it from multiple threads.
Warning
mesh does NOT need to be instantiated with the position attribute, as it is always present, Doing so might lead to unexpected behavior. Position is inside the topology and is always present.
Definition at line 40 of file Mesh.h.
Member Typedef Documentation
Index
template<typename VertexT > using GLESC::Render::Mesh< VertexT >::Index = unsigned int
Alias for the index type of the mesh. Is unsigned because the index can't be negative.
Definition at line 53 of file Mesh.h.
Vertex
template<typename VertexT > using GLESC::Render::Mesh< VertexT >::Vertex = VertexT
Alias for the vertex, for readability purposes.
Definition at line 57 of file Mesh.h.
Constructor & Destructor Documentation
Mesh() [1/3]
template<typename VertexT > GLESC::Render::Mesh< VertexT >::Mesh () inline
Mesh constructor.
Starts with some default values: RenderType - SingleDrawDynamic
Definition at line 65 of file Mesh.h.
              :
            dirtyFlag(false),
            vertexLayout({Vertex::getLayout()}),
            renderType(RenderType::SingleDrawDynamic),
            vertexArray(), indexBuffer(), vertexBuffer() {
        }
~Mesh()
template<typename VertexT > GLESC::Render::Mesh< VertexT >::~Mesh () override default
Default destructor, nothing else to do.
Mesh() [2/3]
template<typename VertexT > GLESC::Render::Mesh< VertexT >::Mesh (const Mesh< VertexT > & other) inline
Definition at line 78 of file Mesh.h.
                                : vertices(other.vertices),
                                  indices(other.indices),
                                  boundingVolume(other.boundingVolume),
                                  vertexLayout(other.vertexLayout),
                                  faces(other.faces),
                                  dirtyFlag(other.dirtyFlag),
                                  renderType(other.renderType),
                                  hashDirty(other.hashDirty),
                                  cachedHash(other.cachedHash) {
        }
Mesh() [3/3]
template<typename VertexT > GLESC::Render::Mesh< VertexT >::Mesh (Mesh< VertexT > && other) inline noexcept
Definition at line 89 of file Mesh.h.
                                    : vertices(std::move(other.vertices)),
                                      indices(std::move(other.indices)),
                                      boundingVolume(std::move(other.boundingVolume)),
                                      vertexLayout(std::move(other.vertexLayout)),
                                      faces(std::move(other.faces)),
                                      dirtyFlag(other.dirtyFlag),
                                      renderType(other.renderType),
                                      hashDirty(other.hashDirty),
                                      cachedHash(other.cachedHash){}
Member Function Documentation
addQuad() [1/2]
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addQuad (const VertexColorParam & v1, const VertexColorParam & v2, const VertexColorParam & v3, const VertexColorParam & v4) inline
Adds a quad to the mesh, quads are defined by 4 vertices.
The order of the faces is important, the vertices should be defined in a counter-clockwise order.
Parameters
v1 The first vertex of the quad.
v2 The second vertex of the quad.
v3 The third vertex of the quad.
v4 The fourth vertex of the quad.
Definition at line 278 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            Normal normal = calculateNormal(v1.position, v2.position, v3.position);
            unsigned int v1Index;
            unsigned int v2Index;
            unsigned int v3Index;
            unsigned int v4Index;
            if constexpr (std::is_same_v<Vertex, ColorVertex>) {
                v1Index = this->addVertex({v1.position, normal, v1.color});
                v2Index = this->addVertex({v2.position, normal, v2.color});
                v3Index = this->addVertex({v3.position, normal, v3.color});
                v4Index = this->addVertex({v4.position, normal, v4.color});
            }
            else {
                v1Index = this->addVertex({v1.position, normal, v1.textureCoordinate});
                v2Index = this->addVertex({v2.position, normal, v2.textureCoordinate});
                v3Index = this->addVertex({v3.position, normal, v3.textureCoordinate});
                v4Index = this->addVertex({v4.position, normal, v4.textureCoordinate});
            }
            this->addQuad(v1Index, v2Index, v3Index, v4Index);
        }
References GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::Mesh< VertexT >::addVertex(), GLESC::Render::Mesh< VertexT >::calculateNormal(), GLESC::Render::Mesh< VertexT >::VertexColorParam::color, D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::VertexColorParam::position.
Referenced by GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::MeshFactory::cuboid(), GLESC::Render::MeshFactory::plane(), GLESC::Render::MeshFactory::pyramid(), and GLESC::Render::MeshFactory::sphere().
addQuad() [2/2]
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addQuad (Index index1, Index index2, Index index3, Index index4) inline
Adds a quad to the mesh, quads are defined by 4 vertices.
Will add two tris to the mesh. The order of the faces is important, the vertices should be defined in a counter-clockwise order.
Parameters
index1
index2
index3
index4
Definition at line 312 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            addTris(index1, index2, index3);
            addTris(index1, index3, index4);
        }
References GLESC::Render::Mesh< VertexT >::addTris(), D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, and GLESC::isIterable_v.
addTris() [1/3]
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addTris (const Vertex & v1, const Vertex & v2, const Vertex & v3) inline
Adds a tris to the mesh, tris are defined by 3 vertices.
The order of the faces is important, the vertices should be defined in a counter-clockwise order.
Parameters
v1 The first vertex of the tris.
v2 The second vertex of the tris.
v3 The third vertex of the tris.
Definition at line 240 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            unsigned int v1Index = this->addVertex(v1);
            unsigned int v2Index = this->addVertex(v2);
            unsigned int v3Index = this->addVertex(v3);
            this->addTris(v1Index, v2Index, v3Index);
        }
References GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addVertex(), D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, and GLESC::isIterable_v.
addTris() [2/3]
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addTris (const VertexColorParam & a, const VertexColorParam & b, const VertexColorParam & c) inline
Adds a tris to the mesh, tris are defined by 3 vertices.
The order of the faces is important, the vertices should be defined in a counter-clockwise order.
Parameters
a The first vertex of the tris.
b The second vertex of the tris.
c The third vertex of the tris.
Definition at line 214 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            Normal normal = calculateNormal(a.position, b.position, c.position);
            unsigned int v1Index;
            unsigned int v2Index;
            unsigned int v3Index;
            if constexpr (std::is_same_v<Vertex, ColorVertex>) {
                v1Index = this->addVertex({a.position, normal, a.color});
                v2Index = this->addVertex({b.position, normal, b.color});
                v3Index = this->addVertex({c.position, normal, c.color});
            }
            else {
                v1Index = this->addVertex({a.position, normal, a.textureCoordinate});
                v2Index = this->addVertex({b.position, normal, b.textureCoordinate});
                v3Index = this->addVertex({c.position, normal, c.textureCoordinate});
            }
            this->addTris(v1Index, v2Index, v3Index);
        }
References GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addVertex(), GLESC::Render::Mesh< VertexT >::calculateNormal(), GLESC::Render::Mesh< VertexT >::VertexColorParam::color, D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::VertexColorParam::position.
Referenced by GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::attatchMesh(), GLESC::Render::MeshFactory::pyramid(), GLESC::Render::MeshFactory::sphere(), and GLESC::Render::MeshFactory::tris().
addTris() [3/3]
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addTris (Index index1, Index index2, Index index3) inline
Adds a list of indices to the mesh.
This method will add a list of indices to the index buffer of the mesh. The indices must be valid indices of the vertices vector, not out of bounds.
Parameters
index1 The first index of the tris.
index2 The second index of the tris.
index3 The third index of the tris.
Definition at line 357 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            D_ASSERT_NOT_EQUAL(index1, index2, "Index 1 and 2 are equal");
            D_ASSERT_NOT_EQUAL(index1, index3, "Index 1 and 3 are equal");
            D_ASSERT_NOT_EQUAL(index2, index3, "Index 2 and 3 are equal");
            D_ASSERT_LESS(index1, vertices.size(), "Index 1 out of bounds");
            D_ASSERT_LESS(index2, vertices.size(), "Index 2 out of bounds");
            D_ASSERT_LESS(index3, vertices.size(), "Index 3 out of bounds");
            {
                std::lock_guard<std::mutex> lock(indicesMutex);
                indices.push_back(index1);
                indices.push_back(index2);
                indices.push_back(index3);
                faces.push_back({index1, index2, index3});
            }
            this->dirtyFlag = true;
        }
References D_ASSERT_LESS, D_ASSERT_NOT_EQUAL, D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::dirtyFlag, GLESC::Render::Mesh< VertexT >::faces, GLESC::Render::Mesh< VertexT >::indices, GLESC::Render::Mesh< VertexT >::indicesMutex, GLESC::Render::Mesh< VertexT >::isBuilding, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::vertices.
addVertex()
template<typename VertexT > Index GLESC::Render::Mesh< VertexT >::addVertex (const Vertex & vertexParam) inline
Adds a vertex to the mesh.
This method will just add a vertex to the vertex buffer of the mesh. The mesh is a thread safe structure, so it is safe to call this method from multiple threads.
Parameters
vertexParam
Returns
Definition at line 325 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            // Insert new vertex
            auto newIndex = static_cast<Index>(vertices.size());
            {
                std::lock_guard<std::mutex> lock(verticesMutex);
                vertices.push_back(vertexParam);
            }
            return newIndex;
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, GLESC::isIterable_v, GLESC::Render::Mesh< VertexT >::vertices, and GLESC::Render::Mesh< VertexT >::verticesMutex.
Referenced by GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addTris(), and GLESC::Render::Mesh< VertexT >::addVertices().
addVertices()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::addVertices (const std::vector< Vertex > & verticesParam) inline
Adds a list of vertices to the mesh.
This method will just add a list of vertices to the vertex buffer of the mesh. Will call addVertex for each vertex in the list.
Parameters
verticesParam
Definition at line 342 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            for (const auto& vertex : verticesParam) {
                addVertex(vertex);
            }
        }
References GLESC::Render::Mesh< VertexT >::addVertex(), D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, and GLESC::isIterable_v.
attatchMesh()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::attatchMesh (const Mesh< VertexT > & mesh) inline
Attaches a mesh to the current mesh.
This method will add the faces and vertices to the current mesh. It is an expesive operation as will iterate over all the faces of other mesh to add to this one.
Parameters
mesh The mesh to be attached.
Definition at line 255 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            for (Math::FaceIndices face : mesh.getFaces()) {
                Index v1Index = face[0];
                Index v2Index = face[1];
                Index v3Index = face[2];
                const Vertex& v1 = mesh.getVertices()[v1Index];
                const Vertex& v2 = mesh.getVertices()[v2Index];
                const Vertex& v3 = mesh.getVertices()[v3Index];
                addTris(v1, v2, v3);
            }
        }
References GLESC::Render::Mesh< VertexT >::addTris(), D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::getFaces(), GLESC::Render::Mesh< VertexT >::getVertices(), GLESC::Render::Mesh< VertexT >::isBuilding, and GLESC::isIterable_v.
calculateHash()
template<typename VertexT > size_t GLESC::Render::Mesh< VertexT >::calculateHash () const inline private
Helper function to calculate the hash of the mesh.
This method will calculate the hash of the mesh by hashing the vertices and indices.
This a heavy function and should be avoided.
Returns
The hash of the mesh.
Definition at line 550 of file Mesh.h.
{
            size_t hashValue = 0;
            // Hash vertex data
            for (const auto& vertex : vertices) {
                Hasher::hashCombine(hashValue, std::hash<Vertex>{}(vertex));
            }
            // Hash index data
            for (const auto& index : indices) {
                Hasher::hashCombine(hashValue, std::hash<Index>{}(index));
            }
            return hashValue;
        }
References GLESC::Hasher::hashCombine(), GLESC::Render::Mesh< VertexT >::indices, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::vertices.
Referenced by GLESC::Render::Mesh< VertexT >::hash().
calculateNormal()
template<typename VertexT > Normal GLESC::Render::Mesh< VertexT >::calculateNormal (const Position & p1, const Position & p2, const Position & p3) const inline private
Helper function to automatically calculate the normal of a face with 3 points.
The formula to calculate the normal of a face is: normal = ((p2 - p1) x (p3 - p1)).normalize()
Parameters
p1 The first point of the face.
p2 The second point of the face.
p3 The third point of the face.
Returns
The normal of the face.
Definition at line 540 of file Mesh.h.
{
            return (p2 - p1).cross(p3 - p1).normalize();
        }
References GLESC::Math::Vector< Type, N >::cross(), and GLESC::isIterable_v.
Referenced by GLESC::Render::Mesh< VertexT >::addQuad(), and GLESC::Render::Mesh< VertexT >::addTris().
clear()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::clear () inline
Definition at line 140 of file Mesh.h.
                     {
            vertices.clear();
            indices.clear();
            faces.clear();
            dirtyFlag = true;
        }
References GLESC::Render::Mesh< VertexT >::dirtyFlag, GLESC::Render::Mesh< VertexT >::faces, GLESC::Render::Mesh< VertexT >::indices, and GLESC::Render::Mesh< VertexT >::vertices.
destroyBuffers()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::destroyBuffers () const inline private
This destroys the buffers in the GPU, removing the data with it.
This will call gpu functions that will destroy the buffers in the GPU.
If needed to render again, must be called sendToGpuBuffers again.
If the data was never sent to the GPU, this method will do nothing.
Definition at line 507 of file Mesh.h.
{
            if (!wasDataSentToGpu) return;
            vertexArray->destroy();
            vertexBuffer->destroy();
            indexBuffer->destroy();
            wasDataSentToGpu = false;
        }
References GLESC::Render::Mesh< VertexT >::indexBuffer, GLESC::Render::Mesh< VertexT >::vertexArray, GLESC::Render::Mesh< VertexT >::vertexBuffer, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
finishBuilding()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::finishBuilding () inline
Definition at line 147 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            D_ASSERT_TRUE(!vertices.empty(), "No vertices in mesh");
            D_ASSERT_TRUE(!indices.empty(), "No indices in mesh");
            boundingVolume.updateBoundingBox(vertices.data(), vertices.size() * sizeof(Vertex), sizeof(Vertex), 0);
            isBuilding = false;
        }
References GLESC::Render::Mesh< VertexT >::boundingVolume, D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::indices, GLESC::Render::Mesh< VertexT >::isBuilding, GLESC::Math::BoundingVolume::updateBoundingBox(), and GLESC::Render::Mesh< VertexT >::vertices.
Referenced by GLESC::Render::MeshFactory::cuboid(), GLESC::Render::MeshFactory::plane(), GLESC::Render::MeshFactory::pyramid(), GLESC::Render::MeshFactory::sphere(), and GLESC::Render::MeshFactory::tris().
getBoundingVolume()
template<typename VertexT > const Math::BoundingVolume & GLESC::Render::Mesh< VertexT >::getBoundingVolume () const inline
Definition at line 175 of file Mesh.h.
{ return boundingVolume; }
References GLESC::Render::Mesh< VertexT >::boundingVolume.
Referenced by GLESC::Render::Renderer::render().
getBoundingVolumeMutable()
template<typename VertexT > Math::BoundingVolume & GLESC::Render::Mesh< VertexT >::getBoundingVolumeMutable () inline
Definition at line 176 of file Mesh.h.
{ return boundingVolume; }
References GLESC::Render::Mesh< VertexT >::boundingVolume.
Referenced by GLESC::Transform::Transformer::transformMesh().
getFaces()
template<typename VertexT > const std::vector< Math::FaceIndices > & GLESC::Render::Mesh< VertexT >::getFaces () const inline
Definition at line 174 of file Mesh.h.
{ return faces; }
References GLESC::Render::Mesh< VertexT >::faces.
Referenced by GLESC::Render::Mesh< VertexT >::attatchMesh().
getIndexBuffer()
template<typename VertexT > const GLESC::GAPI::IndexBuffer & GLESC::Render::Mesh< VertexT >::getIndexBuffer () const inline private
Definition at line 521 of file Mesh.h.
{
            D_ASSERT_TRUE(wasDataSentToGpu, "Data was not sent to GPU");
            return *indexBuffer;
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::indexBuffer, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
Referenced by GLESC::Render::Renderer::renderMesh().
getIndices()
template<typename VertexT > const std::vector< Index > & GLESC::Render::Mesh< VertexT >::getIndices () const inline
Definition at line 172 of file Mesh.h.
{ return indices; }
References GLESC::Render::Mesh< VertexT >::indices.
Referenced by GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
getModifiableVertices()
template<typename VertexT > std::vector< Vertex > & GLESC::Render::Mesh< VertexT >::getModifiableVertices () inline
Definition at line 171 of file Mesh.h.
{ return vertices; }
References GLESC::Render::Mesh< VertexT >::vertices.
Referenced by GLESC::Transform::Transformer::rotateMesh(), GLESC::Transform::Transformer::transformMesh(), and GLESC::Transform::Transformer::translateMesh().
getRenderType()
template<typename VertexT > const RenderType & GLESC::Render::Mesh< VertexT >::getRenderType () const inline
Definition at line 178 of file Mesh.h.
{ return renderType; }
References GLESC::Render::Mesh< VertexT >::renderType.
Referenced by GLESC::Render::Renderer::sendMeshData(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
getUpdatedDebuggingValues()
template<typename VertexT > std::vector< EntityStatsManager::Value > GLESC::Render::Mesh< VertexT >::getUpdatedDebuggingValues () inline override virtual
Get the updated debugging values of the component.
This function can be overriden by the derived class to return the updated debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented from EngineComponent.
Definition at line 430 of file Mesh.h.
{
            std::vector<EntityStatsManager::Value> values;
            if (wasDataSentToGpu) {
                EntityStatsManager::Value vertexCountValue;
                vertexCountValue.name = "Vertex Count";
                vertexCountValue.stringData = std::to_string(vertices.size());
                vertexCountValue.isString = true;
                values.push_back(vertexCountValue);
                EntityStatsManager::Value faceCountValue;
                faceCountValue.name = "Face Count";
                faceCountValue.stringData = std::to_string(faces.size());
                faceCountValue.isString = true;
                values.push_back(faceCountValue);
                EntityStatsManager::Value VAOIDValue;
                VAOIDValue.name = "VAO ID";
                VAOIDValue.stringData = std::to_string(getVertexArray().getRendererID());
                VAOIDValue.isString = true;
                values.push_back(VAOIDValue);
            }
            else {
                EntityStatsManager::Value errorValue;
                errorValue.name = "Error";
                errorValue.stringData = "Data was not sent to GPU";
                errorValue.isString = true;
                values.push_back(errorValue);
            }
            return values;
        }
References GLESC::Render::Mesh< VertexT >::faces, GLESC::Render::Mesh< VertexT >::getVertexArray(), GLESC::isIterable_v, EntityStatsManager::Value::name, GLESC::Render::Mesh< VertexT >::vertices, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
Referenced by GLESC::ECS::RenderComponent::setUpdatedDebuggingValues().
getVertexArray()
template<typename VertexT > const GLESC::GAPI::VertexArray & GLESC::Render::Mesh< VertexT >::getVertexArray () const inline private
Definition at line 516 of file Mesh.h.
{
            D_ASSERT_TRUE(wasDataSentToGpu, "Data was not sent to GPU");
            return *vertexArray;
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::vertexArray, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
Referenced by GLESC::Render::Mesh< VertexT >::getUpdatedDebuggingValues(), and GLESC::Render::Renderer::renderMesh().
getVertexBuffer()
template<typename VertexT > const GLESC::GAPI::VertexBuffer & GLESC::Render::Mesh< VertexT >::getVertexBuffer () const inline private
Definition at line 526 of file Mesh.h.
{
            D_ASSERT_TRUE(wasDataSentToGpu, "Data was not sent to GPU");
            return *vertexBuffer;
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::vertexBuffer, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
getVertexLayout()
template<typename VertexT > const std::vector< GLESC::GAPI::Enums::Types > & GLESC::Render::Mesh< VertexT >::getVertexLayout () const inline
Definition at line 173 of file Mesh.h.
{ return vertexLayout; }
References GLESC::Render::Mesh< VertexT >::vertexLayout.
Referenced by GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
getVertices()
template<typename VertexT > const std::vector< Vertex > & GLESC::Render::Mesh< VertexT >::getVertices () const inline
Definition at line 170 of file Mesh.h.
{ return vertices; }
References GLESC::Render::Mesh< VertexT >::vertices.
Referenced by GLESC::Render::Mesh< VertexT >::attatchMesh(), GLESC::Render::Renderer::sendMeshData(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
hash()
template<typename VertexT > size_t GLESC::Render::Mesh< VertexT >::hash () const inline
Calculates lazily the hash of the mesh. Only recalculates if the mesh has been changed.
Returns
The hash of the mesh.
Definition at line 420 of file Mesh.h.
{
            if (hashDirty) {
                cachedHash = this->calculateHash();
                hashDirty = false;
            }
            return cachedHash;
        }
References GLESC::Render::Mesh< VertexT >::cachedHash, GLESC::Render::Mesh< VertexT >::calculateHash(), and GLESC::Render::Mesh< VertexT >::hashDirty.
isBeingBuilt()
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::isBeingBuilt () const inline
Definition at line 179 of file Mesh.h.
{ return isBuilding; }
References GLESC::Render::Mesh< VertexT >::isBuilding.
Referenced by GLESC::Render::Renderer::sendMeshData().
isDirty()
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::isDirty () const inline
Definition at line 177 of file Mesh.h.
{ return dirtyFlag; }
References GLESC::Render::Mesh< VertexT >::dirtyFlag.
operator=() [1/2]
template<typename VertexT > Mesh & GLESC::Render::Mesh< VertexT >::operator= (const Mesh< VertexT > & other) inline
Definition at line 114 of file Mesh.h.
{
            if (this == &other)
                return *this;
            vertices = other.vertices;
            indices = other.indices;
            boundingVolume = other.boundingVolume;
            vertexLayout = other.vertexLayout;
            dirtyFlag = other.dirtyFlag;
            renderType = other.renderType;
            hashDirty = other.hashDirty;
            cachedHash = other.cachedHash;
            faces = other.faces;
            return *this;
        }
References GLESC::Render::Mesh< VertexT >::boundingVolume, GLESC::Render::Mesh< VertexT >::cachedHash, GLESC::Render::Mesh< VertexT >::dirtyFlag, GLESC::Render::Mesh< VertexT >::faces, GLESC::Render::Mesh< VertexT >::hashDirty, GLESC::Render::Mesh< VertexT >::indices, GLESC::isIterable_v, GLESC::Render::Mesh< VertexT >::renderType, GLESC::Render::Mesh< VertexT >::vertexLayout, and GLESC::Render::Mesh< VertexT >::vertices.
operator=() [2/2]
template<typename VertexT > Mesh & GLESC::Render::Mesh< VertexT >::operator= (Mesh< VertexT > && other) inline noexcept
Definition at line 99 of file Mesh.h.
{
            if (this == &other)
                return *this;
            vertices = std::move(other.vertices);
            indices = std::move(other.indices);
            boundingVolume = std::move(other.boundingVolume);
            vertexLayout = std::move(other.vertexLayout);
            faces = std::move(other.faces);
            dirtyFlag = other.dirtyFlag;
            renderType = other.renderType;
            hashDirty = other.hashDirty;
            cachedHash = other.cachedHash;
            return *this;
        }
References GLESC::Render::Mesh< VertexT >::boundingVolume, GLESC::Render::Mesh< VertexT >::cachedHash, GLESC::Render::Mesh< VertexT >::dirtyFlag, GLESC::Render::Mesh< VertexT >::faces, GLESC::Render::Mesh< VertexT >::hashDirty, GLESC::Render::Mesh< VertexT >::indices, GLESC::isIterable_v, GLESC::Render::Mesh< VertexT >::renderType, GLESC::Render::Mesh< VertexT >::vertexLayout, and GLESC::Render::Mesh< VertexT >::vertices.
operator==()
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::operator== (const Mesh< VertexT > & other) const inline
To check if a mesh is equal to another mesh we iterate over the vertices and indices and compare them. If the vertices and indices are the same, the meshes are equal.
This is a slow operation and should be avoided.
Parameters
other
Returns
Definition at line 382 of file Mesh.h.
{
            for (size_t i = 0; i < vertices.size(); ++i) {
                if (vertices[i] != other.vertices[i]) {
                    return false;
                }
            }
            for (size_t i = 0; i < indices.size(); ++i) {
                if (indices[i] != other.indices[i]) {
                    return false;
                }
            }
            return true;
        }
References GLESC::Render::Mesh< VertexT >::indices, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::vertices.
reserveFaces()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::reserveFaces (size_t size) inline
Definition at line 165 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            faces.reserve(size);
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::faces, and GLESC::Render::Mesh< VertexT >::isBuilding.
reserveIndices()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::reserveIndices (size_t size) inline
Definition at line 160 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            indices.reserve(size);
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::indices, and GLESC::Render::Mesh< VertexT >::isBuilding.
reserveVertices()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::reserveVertices (size_t size) inline
Definition at line 155 of file Mesh.h.
{
            D_ASSERT_TRUE(isBuilding, "Mesh is not being built");
            vertices.reserve(size);
        }
References D_ASSERT_TRUE, GLESC::Render::Mesh< VertexT >::isBuilding, and GLESC::Render::Mesh< VertexT >::vertices.
S_ASSERT_TRUE()
template<typename VertexT > GLESC::Render::Mesh< VertexT >::S_ASSERT_TRUE ((std::is_base_of_v< ColorVertex, VertexT >||std::is_base_of_v< TextureVertex, VertexT >) , "Vertex must be a ColorVertex or TextureVertex")
Static assert to ensure that the vertex is a ColorVertex or TextureVertex. As we currently only support these two types of vertices.
sendToGpuBuffers()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::sendToGpuBuffers () const inline private
This method creates GPU buffers and sends the data to the GPU.
This method will create the vertex array, vertex buffer and index buffer objects and send the data to the GPU. This method also ensures that it is only called once. Even if the data is modified, as the mesh is not prepared for modifications.
Todo:
Prepare the mesh for modifications.
Definition at line 470 of file Mesh.h.
{
            if (wasDataSentToGpu) return;
            vertexArray = std::make_unique<GLESC::GAPI::VertexArray>();
            const void* bufferData = getVertices().data();
            size_t bufferCount = getVertices().size();
            size_t vertexBytes = sizeof(Vertex);
            GLESC::GAPI::Enums::BufferUsages bufferUsage = getBufferUsage(getRenderType());
            vertexArray->bind();
            vertexBuffer = std::make_unique<GLESC::GAPI::VertexBuffer>(
                bufferData,
                bufferCount,
                vertexBytes,
                bufferUsage
            );
            indexBuffer = std::make_unique<GLESC::GAPI::IndexBuffer>(
                getIndices().data(),
                getIndices().size());
            GLESC::GAPI::VertexBufferLayout layout;
            for (GLESC::GAPI::Enums::Types type : getVertexLayout()) {
                layout.push(type);
            }
            vertexArray->addBuffer(*vertexBuffer, layout);
            wasDataSentToGpu = true;
        }
References GLESC::Render::getBufferUsage(), GLESC::Render::Mesh< VertexT >::getIndices(), GLESC::Render::Mesh< VertexT >::getRenderType(), GLESC::Render::Mesh< VertexT >::getVertexLayout(), GLESC::Render::Mesh< VertexT >::getVertices(), GLESC::Render::Mesh< VertexT >::indexBuffer, GLESC::isIterable_v, GLESC::GAPI::VertexBufferLayout::push(), GLESC::Render::Mesh< VertexT >::vertexArray, GLESC::Render::Mesh< VertexT >::vertexBuffer, and GLESC::Render::Mesh< VertexT >::wasDataSentToGpu.
Referenced by GLESC::Render::Renderer::render().
setRenderType()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::setRenderType (RenderType renderTypeParam) inline
Definition at line 181 of file Mesh.h.
{ renderType = renderTypeParam; }
References GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::renderType.
startBuilding()
template<typename VertexT > void GLESC::Render::Mesh< VertexT >::startBuilding () inline
Starts the building of the mesh.
This method should be called before adding any vertices or indices to the mesh. It will also set the isBuilding flag to true. It is only possible to attach vertices or whole meshes to the mesh while it is being built.
Definition at line 135 of file Mesh.h.
{
            dirtyFlag = true;
            isBuilding = true;
        }
References GLESC::Render::Mesh< VertexT >::dirtyFlag, and GLESC::Render::Mesh< VertexT >::isBuilding.
Referenced by GLESC::Render::MeshFactory::cuboid(), GLESC::Render::MeshFactory::plane(), GLESC::Render::MeshFactory::pyramid(), and GLESC::Render::MeshFactory::sphere().
toString()
template<typename VertexT > std::string GLESC::Render::Mesh< VertexT >::toString () const inline override virtual
This converts the mesh to a string.
Will only convert the first 10 vertices and indices to a string, just for debugging purposes.
Returns
The string representation of the mesh.
Implements EngineComponent.
Definition at line 403 of file Mesh.h.
{
            std::string result = "Mesh\n";
            result += "Vertices (first 10):\n";
            for (size_t i = 0; i < 10 && i < vertices.size(); ++i) {
                result += vertices[i].toString() + "\n";
            }
            result += "Indices (first 10):\n";
            for (size_t i = 0; i < 10 && i < indices.size(); ++i) {
                result += std::to_string(indices[i]) + "\n";
            }
            return result;
        }
References GLESC::Render::Mesh< VertexT >::indices, GLESC::isIterable_v, and GLESC::Render::Mesh< VertexT >::vertices.
Referenced by GLESC::ECS::RenderComponent::toString().
Friends And Related Symbol Documentation
GLESC::Render::Renderer
template<typename VertexT > friend class GLESC::Render::Renderer friend
Definition at line 41 of file Mesh.h.
Member Data Documentation
boundingVolume
template<typename VertexT > Math::BoundingVolume GLESC::Render::Mesh< VertexT >::boundingVolume private
The bounding volume of the mesh.
The bounding volume is a polyhedron cuboid that encloses the mesh. It is used for culling.
Definition at line 574 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::finishBuilding(), GLESC::Render::Mesh< VertexT >::getBoundingVolume(), GLESC::Render::Mesh< VertexT >::getBoundingVolumeMutable(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::operator=().
cachedHash
template<typename VertexT > size_t GLESC::Render::Mesh< VertexT >::cachedHash = 0 mutable private
Definition at line 597 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::hash(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::operator=().
dirtyFlag
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::dirtyFlag = false mutable private
A flag that indicates whether the mesh is dirty.
The flag is set to true when the mesh is modified. It is used to avoid unnecessary updates to the vertex array object. It is mutable because it is modified by const methods, specifically after rendering the mesh, we want to set the flag to false and nothing else.
Definition at line 589 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::clear(), GLESC::Render::Mesh< VertexT >::isDirty(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::startBuilding().
faces
template<typename VertexT > std::vector<Math::FaceIndices> GLESC::Render::Mesh< VertexT >::faces {} private
Definition at line 566 of file Mesh.h.
{};
Referenced by GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::clear(), GLESC::Render::Mesh< VertexT >::getFaces(), GLESC::Render::Mesh< VertexT >::getUpdatedDebuggingValues(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::reserveFaces().
facesMutex
template<typename VertexT > std::mutex GLESC::Render::Mesh< VertexT >::facesMutex {} mutable private
Definition at line 619 of file Mesh.h.
{};
hashDirty
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::hashDirty = true mutable private
Definition at line 598 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::hash(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::operator=().
indexBuffer
template<typename VertexT > std::unique_ptr<GLESC::GAPI::IndexBuffer> GLESC::Render::Mesh< VertexT >::indexBuffer mutable private
buffer that handles the indices of the mesh in the gpu.
Definition at line 603 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::destroyBuffers(), GLESC::Render::Mesh< VertexT >::getIndexBuffer(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
indices
template<typename VertexT > std::vector<Index> GLESC::Render::Mesh< VertexT >::indices {} private
Definition at line 567 of file Mesh.h.
{};
Referenced by GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::calculateHash(), GLESC::Render::Mesh< VertexT >::clear(), GLESC::Render::Mesh< VertexT >::finishBuilding(), GLESC::Render::Mesh< VertexT >::getIndices(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator==(), GLESC::Render::Mesh< VertexT >::reserveIndices(), and GLESC::Render::Mesh< VertexT >::toString().
indicesMutex
template<typename VertexT > std::mutex GLESC::Render::Mesh< VertexT >::indicesMutex {} mutable private
Definition at line 618 of file Mesh.h.
{};
Referenced by GLESC::Render::Mesh< VertexT >::addTris().
isBuilding
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::isBuilding = false mutable private
A flag that indicates whether the mesh is being built.
The mesh can only be modified while it is being built. If trying to modify the mesh while it is not being built, the renderer will assert error.
Definition at line 595 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::Mesh< VertexT >::addQuad(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addVertex(), GLESC::Render::Mesh< VertexT >::addVertices(), GLESC::Render::Mesh< VertexT >::attatchMesh(), GLESC::Render::Mesh< VertexT >::finishBuilding(), GLESC::Render::Mesh< VertexT >::isBeingBuilt(), GLESC::Render::Mesh< VertexT >::reserveFaces(), GLESC::Render::Mesh< VertexT >::reserveIndices(), GLESC::Render::Mesh< VertexT >::reserveVertices(), and GLESC::Render::Mesh< VertexT >::startBuilding().
renderType
template<typename VertexT > RenderType GLESC::Render::Mesh< VertexT >::renderType private
Definition at line 565 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::getRenderType(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::setRenderType().
vertexArray
template<typename VertexT > std::unique_ptr<GLESC::GAPI::VertexArray> GLESC::Render::Mesh< VertexT >::vertexArray mutable private
Definition at line 611 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::destroyBuffers(), GLESC::Render::Mesh< VertexT >::getVertexArray(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
vertexBuffer
template<typename VertexT > std::unique_ptr<GLESC::GAPI::VertexBuffer> GLESC::Render::Mesh< VertexT >::vertexBuffer mutable private
buffer that handles the vertices of the mesh in the gpu.
Definition at line 607 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::destroyBuffers(), GLESC::Render::Mesh< VertexT >::getVertexBuffer(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
vertexLayout
template<typename VertexT > std::vector<GLESC::GAPI::Enums::Types> GLESC::Render::Mesh< VertexT >::vertexLayout private
The vertex layout of the mesh.
The vertex layout is a vector of Types that describes the layout of the vertex data in the vertices vector. The layout is used to create the vertex buffer layout for the vertex array object.
Definition at line 581 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::getVertexLayout(), GLESC::Render::Mesh< VertexT >::operator=(), and GLESC::Render::Mesh< VertexT >::operator=().
vertices
template<typename VertexT > std::vector<Vertex> GLESC::Render::Mesh< VertexT >::vertices {} private
Definition at line 568 of file Mesh.h.
{};
Referenced by GLESC::Render::Mesh< VertexT >::addTris(), GLESC::Render::Mesh< VertexT >::addVertex(), GLESC::Render::Mesh< VertexT >::calculateHash(), GLESC::Render::Mesh< VertexT >::clear(), GLESC::Render::Mesh< VertexT >::finishBuilding(), GLESC::Render::Mesh< VertexT >::getModifiableVertices(), GLESC::Render::Mesh< VertexT >::getUpdatedDebuggingValues(), GLESC::Render::Mesh< VertexT >::getVertices(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator=(), GLESC::Render::Mesh< VertexT >::operator==(), GLESC::Render::Mesh< VertexT >::reserveVertices(), and GLESC::Render::Mesh< VertexT >::toString().
verticesMutex
template<typename VertexT > std::mutex GLESC::Render::Mesh< VertexT >::verticesMutex {} mutable private
Definition at line 617 of file Mesh.h.
{};
Referenced by GLESC::Render::Mesh< VertexT >::addVertex().
wasDataSentToGpu
template<typename VertexT > bool GLESC::Render::Mesh< VertexT >::wasDataSentToGpu = false mutable private
Flag to ensure that the data was sent to the gpu only once.
Definition at line 615 of file Mesh.h.
Referenced by GLESC::Render::Mesh< VertexT >::destroyBuffers(), GLESC::Render::Mesh< VertexT >::getIndexBuffer(), GLESC::Render::Mesh< VertexT >::getUpdatedDebuggingValues(), GLESC::Render::Mesh< VertexT >::getVertexArray(), GLESC::Render::Mesh< VertexT >::getVertexBuffer(), and GLESC::Render::Mesh< VertexT >::sendToGpuBuffers().
The documentation for this class was generated from the following file:
Mesh.h