GLESC: Cubemap Class Reference
Cubemap Class Reference
Class representing a cubemap texture. It abstract away the creating and handling of cubemaps.
#include <Cubemap.h>
Public Member Functions
Cubemap ()=default
Cubemap (const std::array< std::string, 6 > &facePaths)
~Cubemap ()
void bind () const
std::array< GLESC::ResMng::Texture::TextureSurface, 6 > & getCubemapTextures ()
const std::array< GLESC::ResMng::Texture::TextureSurface, 6 > & getCubemapTextures () const
std::array< Pixel, 6 > getPixelsAtCoords (int x, int y) const
bool hasBeenLoaded () const
void load (const std::array< std::string, 6 > &facePaths)
void release ()
void unbind () const
Private Attributes
std::array< GLESC::ResMng::Texture::TextureSurface, 6 > cubemapTextures {}
bool hasLoaded {false}
TextureID textureID {0}
Detailed Description
Class representing a cubemap texture. It abstract away the creating and handling of cubemaps.
A cubemap is a type of texture that contains 6 faces of a cube, each face being a 2D texture.
A cubemap helps retrieving a texel from a 3D direction vector, which is useful for many rendering techniques
Example of cubemap usage is skyboxes, reflections, refractions, etc.
Definition at line 22 of file Cubemap.h.
Constructor & Destructor Documentation
Cubemap() [1/2]
Cubemap::Cubemap () default
Cubemap() [2/2]
Cubemap::Cubemap (const std::array< std::string, 6 > & facePaths) explicit
Definition at line 14 of file Cubemap.cpp.
{
    load(facePaths);
}
References load().
~Cubemap()
Cubemap::~Cubemap ()
Definition at line 18 of file Cubemap.cpp.
                  {
    if (hasLoaded) {
        release();
        getGAPI().deleteTexture(textureID);
    }
}
References getGAPI(), hasLoaded, release(), and textureID.
Member Function Documentation
bind()
void Cubemap::bind () const
Definition at line 63 of file Cubemap.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Cubemap not loaded");
    getGAPI().bindTextureOnSlot(textureID, Enums::Texture::Types::TextureCubeMap, 0);
}
References D_ASSERT_TRUE, getGAPI(), hasLoaded, and textureID.
Referenced by GLESC::Render::Skybox::draw().
getCubemapTextures() [1/2]
std::array< GLESC::ResMng::Texture::TextureSurface, 6 > & Cubemap::getCubemapTextures () inline
Definition at line 33 of file Cubemap.h.
{
        return cubemapTextures;
    }
References cubemapTextures.
getCubemapTextures() [2/2]
const std::array< GLESC::ResMng::Texture::TextureSurface, 6 > & Cubemap::getCubemapTextures () const inline
Definition at line 29 of file Cubemap.h.
{
        return cubemapTextures;
    }
References cubemapTextures.
Referenced by GLESC::Render::Skybox::calculateAverageColor().
getPixelsAtCoords()
std::array< Pixel, 6 > Cubemap::getPixelsAtCoords (int x, int y) const
Definition at line 47 of file Cubemap.cpp.
{
    std::array<Pixel, 6> pixels{};
    for (int i = 0; i < 6; i++) {
        pixels[i] = cubemapTextures[i].getPixel(x, y);
    }
    return pixels;
}
References cubemapTextures.
Referenced by GLESC::Render::Skybox::calculateAverageColor().
hasBeenLoaded()
bool Cubemap::hasBeenLoaded () const inline
Definition at line 27 of file Cubemap.h.
{ return hasLoaded; }
References hasLoaded.
load()
void Cubemap::load (const std::array< std::string, 6 > & facePaths)
Definition at line 25 of file Cubemap.cpp.
{
    textureID = getGAPI().createTexture(Enums::Texture::Types::TextureCubeMap,
                                        Enums::Texture::Filters::Min::Linear,
                                        Enums::Texture::Filters::Mag::Linear,
                                        Enums::Texture::Filters::WrapMode::ClampToEdge,
                                        Enums::Texture::Filters::WrapMode::ClampToEdge,
                                        Enums::Texture::Filters::WrapMode::ClampToEdge);
    for (size_t i = 0; i < facePaths.size(); ++i) {
        cubemapTextures[i].load("/cubemaps/"+facePaths[i], false);
        auto nextFaceEnumInt = static_cast<int>(Enums::Texture::Types::TextureCubeMapPositiveX) + i;
        auto nextFaceEnum = static_cast<Enums::Texture::Types>(nextFaceEnumInt);
        getGAPI().setTextureData(nextFaceEnum,
                                 0,
                                 cubemapTextures[i].getWidth(),
                                 cubemapTextures[i].getHeight(),
                                 getTextureInputFormat(cubemapTextures[i].getFormat().colorFormat),
                                 getTextureBitDepth(cubemapTextures[i].getFormat().bitDepth),
                                 cubemapTextures[i].getPixels().data());
    }
    hasLoaded = true;
}
References cubemapTextures, getGAPI(), getTextureBitDepth(), getTextureInputFormat(), hasLoaded, and textureID.
Referenced by Cubemap().
release()
void Cubemap::release ()
Definition at line 55 of file Cubemap.cpp.
                      {
    if (hasLoaded) {
        for (auto& texture : cubemapTextures) {
            texture.release();
        }
    }
}
References cubemapTextures, and hasLoaded.
Referenced by ~Cubemap().
unbind()
void Cubemap::unbind () const
Definition at line 68 of file Cubemap.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Cubemap not loaded");
    getGAPI().unbindTexture(Enums::Texture::Types::TextureCubeMap);
}
References D_ASSERT_TRUE, getGAPI(), and hasLoaded.
Member Data Documentation
cubemapTextures
std::array<GLESC::ResMng::Texture::TextureSurface, 6> Cubemap::cubemapTextures {} private
Definition at line 47 of file Cubemap.h.
{};
Referenced by getCubemapTextures(), getCubemapTextures(), getPixelsAtCoords(), load(), and release().
hasLoaded
bool Cubemap::hasLoaded {false} private
Definition at line 45 of file Cubemap.h.
{false};
Referenced by ~Cubemap(), bind(), hasBeenLoaded(), load(), release(), and unbind().
textureID
TextureID Cubemap::textureID {0} private
Definition at line 46 of file Cubemap.h.
{0};
Referenced by ~Cubemap(), bind(), and load().
The documentation for this class was generated from the following files:
Cubemap.h
Cubemap.cpp