GLESC: GLESC::HUD::CrosshairHUD Class Reference
GLESC::HUD::CrosshairHUD Class Reference
Class to encapsulate the logic of the crosshair HUD.
#include <CrosshairHUD.h>
Public Member Functions
CrosshairHUD ()
Public Member Functions inherited from GLESC::InGameWindow
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Private Member Functions
void windowContent (float timeOfFrame) override
Private Attributes
GLESC::Render::ColorRgba linesColor = GLESC::Render::ColorRgba(255, 255, 255, 255)
float linesLength = 10.0f
Additional Inherited Members
Protected Member Functions inherited from GLESC::InGameWindow
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
Protected Attributes inherited from GLESC::InGameWindow
bool isVisible = true
Detailed Description
Class to encapsulate the logic of the crosshair HUD.
The crosshair HUD is a simple crosshair that is displayed in the center of the screen.
Definition at line 19 of file CrosshairHUD.h.
Constructor & Destructor Documentation
CrosshairHUD()
CrosshairHUD::CrosshairHUD ()
Definition at line 14 of file CrosshairHUD.cpp.
{
    this->setSizeFraction({0.3f, 0.3f});
    isVisible = true;
    this->setLayoutPosition(GLESC::LayoutPos::Center);
    this->setCenter(GLESC::WindowCenter::Center);
    this->addFlag(ImGuiWindowFlags_NoBackground);
    this->addFlag(ImGuiWindowFlags_NoResize);
    this->addFlag(ImGuiWindowFlags_NoMove);
    this->addFlag(ImGuiWindowFlags_NoCollapse);
    this->addFlag(ImGuiWindowFlags_NoTitleBar);
    this->addFlag(ImGuiWindowFlags_NoSavedSettings);
    this->addFlag(ImGuiWindowFlags_NoBringToFrontOnFocus);
    this->addFlag(ImGuiWindowFlags_NoFocusOnAppearing);
}
References GLESC::InGameWindow::addFlag(), GLESC::Center, GLESC::isIterable_v, GLESC::InGameWindow::isVisible, GLESC::InGameWindow::setCenter(), GLESC::InGameWindow::setLayoutPosition(), and GLESC::InGameWindow::setSizeFraction().
Member Function Documentation
windowContent()
void CrosshairHUD::windowContent (float timeOfFrame) override private virtual
Implements GLESC::InGameWindow.
Definition at line 29 of file CrosshairHUD.cpp.
{
    // Get the center of your window or viewport
    ImVec2 windowCenter = ImVec2(
        ImGui::GetWindowPos().x + ImGui::GetWindowSize().x * 0.5f,
        ImGui::GetWindowPos().y + ImGui::GetWindowSize().y * 0.5f
    );
    ImU32 crosshairColor = IM_COL32(
        static_cast<int>(linesColor.getR()),
        static_cast<int>(linesColor.getG()),
        static_cast<int>(linesColor.getB()),
        static_cast<int>(linesColor.getA())
    );
    ImDrawList* drawList = ImGui::GetWindowDrawList();
    // Draw vertical line
    drawList->AddLine(
        ImVec2(windowCenter.x, windowCenter.y - linesLength),
        ImVec2(windowCenter.x, windowCenter.y + linesLength),
        crosshairColor
    );
    // Draw horizontal line
    drawList->AddLine(
        ImVec2(windowCenter.x - linesLength, windowCenter.y),
        ImVec2(windowCenter.x + linesLength, windowCenter.y),
        crosshairColor
    );
}
References GLESC::Render::ColorRgba::getA(), GLESC::Render::ColorRgba::getB(), GLESC::Render::ColorRgba::getG(), GLESC::Render::ColorRgba::getR(), GLESC::isIterable_v, linesColor, and linesLength.
Member Data Documentation
linesColor
GLESC::Render::ColorRgba GLESC::HUD::CrosshairHUD::linesColor = GLESC::Render::ColorRgba(255, 255, 255, 255) private
Definition at line 25 of file CrosshairHUD.h.
Referenced by windowContent().
linesLength
float GLESC::HUD::CrosshairHUD::linesLength = 10.0f private
Definition at line 24 of file CrosshairHUD.h.
Referenced by windowContent().
The documentation for this class was generated from the following files:
CrosshairHUD.h
CrosshairHUD.cpp