GLESC: GLESC::Render::Frustum Class Reference
GLESC::Render::Frustum Class Reference
#include <Frustum.h>
Public Member Functions
Frustum ()=delete
Frustum (const VP &VPMatrix)
Constructs a frustum from a camera transform and perspective.
bool contains (const Math::BoundingVolume &volume) const
Checks if the frustum intersects with a given bounding volume.
bool contains (const Position &position) const
const std::array< Math::Plane, 6 > & getPlanes () const
void update (const VP &VPMat)
Updates the frustum planes based on new view and projection matrices.
Private Member Functions
void extractPlanes (const VP &VPMatrix)
Extracts the frustum planes from a combined view-projection matrix. Uses Hartmann & Gribbs method. It's done with colum-major matrices (OpenGL).
Private Attributes
std::array< Math::Plane, 6 > planes {}
Detailed Description
Definition at line 17 of file Frustum.h.
Constructor & Destructor Documentation
Frustum() [1/2]
GLESC::Render::Frustum::Frustum () delete
Frustum() [2/2]
GLESC::Render::Frustum::Frustum (const VP & VPMatrix) inline explicit
Constructs a frustum from a camera transform and perspective.
Parameters
VPMatrix The combined view-projection matrix.
Definition at line 30 of file Frustum.h.
{
            extractPlanes(VPMatrix);
        }
References extractPlanes(), and GLESC::isIterable_v.
Member Function Documentation
contains() [1/2]
bool Frustum::contains (const Math::BoundingVolume & volume) const
Checks if the frustum intersects with a given bounding volume.
Returns true if any point is inside all the planes
Parameters
volume The bounding volume to test for intersection.
Returns
true If the frustum intersects the volume.
false If the frustum does not intersect the volume.
Definition at line 103 of file Frustum.cpp.
{
    const auto& bbox = volume.getBoundingBox();
    for (const auto& plane : planes) {
        // Check if all points of the AABB are outside a plane
        if (!plane.hasInside({bbox.min.getX(), bbox.min.getY(), bbox.min.getZ()}) &&
            !plane.hasInside({bbox.max.getX(), bbox.min.getY(), bbox.min.getZ()}) &&
            !plane.hasInside({bbox.min.getX(), bbox.max.getY(), bbox.min.getZ()}) &&
            !plane.hasInside({bbox.max.getX(), bbox.max.getY(), bbox.min.getZ()}) &&
            !plane.hasInside({bbox.min.getX(), bbox.min.getY(), bbox.max.getZ()}) &&
            !plane.hasInside({bbox.max.getX(), bbox.min.getY(), bbox.max.getZ()}) &&
            !plane.hasInside({bbox.min.getX(), bbox.max.getY(), bbox.max.getZ()}) &&
            !plane.hasInside({bbox.max.getX(), bbox.max.getY(), bbox.max.getZ()})) {
            return false;
        }
    }
    return true;
}
References GLESC::isIterable_v, and planes.
Referenced by GLESC::Render::Renderer::render(), and GLESC::HUD::DebugItems::windowContent().
contains() [2/2]
bool Frustum::contains (const Position & position) const
Definition at line 94 of file Frustum.cpp.
{
    for (const Math::Plane& plane : planes) {
        if (!plane.hasInside(position)) {
            return false;
        }
    }
    return true;
}
References planes.
extractPlanes()
void Frustum::extractPlanes (const VP & VPMatrix) private
Extracts the frustum planes from a combined view-projection matrix. Uses Hartmann & Gribbs method. It's done with colum-major matrices (OpenGL).
See also
https://web.archive.org/web/20210226045225/http://www.cs.otago.ac.nz/postgrads/alexis/planeExtraction.pdf
Parameters
VPMatrix The combined view-projection matrix.
Definition at line 5 of file Frustum.cpp.
{
    if constexpr (Math::MatrixAlgorithms::columnMajorMatrix) [[maybe_unused]]  {
        // Left clipping plane
        planes[0].setNormal(Math::Direction(VPMatrix[0][3] + VPMatrix[0][0],
                                            VPMatrix[1][3] + VPMatrix[1][0],
                                            VPMatrix[2][3] + VPMatrix[2][0]));
        planes[0].setDistance(VPMatrix[3][3] + VPMatrix[3][0]);
        planes[0].normalize();
        // Right clipping plane
        planes[1].setNormal(Math::Direction(VPMatrix[0][3] - VPMatrix[0][0],
                                            VPMatrix[1][3] - VPMatrix[1][0],
                                            VPMatrix[2][3] - VPMatrix[2][0]));
        planes[1].setDistance(VPMatrix[3][3] - VPMatrix[3][0]);
        planes[1].normalize();
        // Top clipping plane
        planes[2].setNormal(Math::Direction(VPMatrix[0][3] - VPMatrix[0][1],
                                            VPMatrix[1][3] - VPMatrix[1][1],
                                            VPMatrix[2][3] - VPMatrix[2][1]));
        planes[2].setDistance(VPMatrix[3][3] - VPMatrix[3][1]);
        planes[2].normalize();
        // Bottom clipping plane
        planes[3].setNormal(Math::Direction(VPMatrix[0][3] + VPMatrix[0][1],
                                            VPMatrix[1][3] + VPMatrix[1][1],
                                            VPMatrix[2][3] + VPMatrix[2][1]));
        planes[3].setDistance(VPMatrix[3][3] + VPMatrix[3][1]);
        planes[3].normalize();
        // Near clipping plane
        planes[4].setNormal(Math::Direction(VPMatrix[0][3] + VPMatrix[0][2],
                                            VPMatrix[1][3] + VPMatrix[1][2],
                                            VPMatrix[2][3] + VPMatrix[2][2]));
        planes[4].setDistance(VPMatrix[3][3] + VPMatrix[3][2]);
        planes[4].normalize();
        // Far clipping plane
        planes[5].setNormal(Math::Direction(VPMatrix[0][3] - VPMatrix[0][2],
                                            VPMatrix[1][3] - VPMatrix[1][2],
                                            VPMatrix[2][3] - VPMatrix[2][2]));
        planes[5].setDistance(VPMatrix[3][3] - VPMatrix[3][2]);
        planes[5].normalize();
    }
    else [[maybe_unused]] {
        // Left clipping plane
        planes[0].setNormal(Math::Direction(VPMatrix[3][0] + VPMatrix[0][0],
                                            VPMatrix[3][1] + VPMatrix[0][1],
                                            VPMatrix[3][2] + VPMatrix[0][2]));
        planes[0].setDistance(VPMatrix[3][3] + VPMatrix[0][3]);
        planes[0].normalize();
        // Right clipping plane
        planes[1].setNormal(Math::Direction(VPMatrix[3][0] - VPMatrix[0][0],
                                            VPMatrix[3][1] - VPMatrix[0][1],
                                            VPMatrix[3][2] - VPMatrix[0][2]));
        planes[1].setDistance(VPMatrix[3][3] - VPMatrix[0][3]);
        planes[1].normalize();
        // Top clipping plane
        planes[2].setNormal(Math::Direction(VPMatrix[3][0] - VPMatrix[1][0],
                                            VPMatrix[3][1] - VPMatrix[1][1],
                                            VPMatrix[3][2] - VPMatrix[1][2]));
        planes[2].setDistance(VPMatrix[3][3] - VPMatrix[1][3]);
        planes[2].normalize();
        // Bottom clipping plane
        planes[3].setNormal(Math::Direction(VPMatrix[3][0] + VPMatrix[1][0],
                                            VPMatrix[3][1] + VPMatrix[1][1],
                                            VPMatrix[3][2] + VPMatrix[1][2]));
        planes[3].setDistance(VPMatrix[3][3] + VPMatrix[1][3]);
        planes[3].normalize();
        // Near clipping plane
        planes[4].setNormal(Math::Direction(VPMatrix[3][0] + VPMatrix[2][0],
                                            VPMatrix[3][1] + VPMatrix[2][1],
                                            VPMatrix[3][2] + VPMatrix[2][2]));
        planes[4].setDistance(VPMatrix[3][3] + VPMatrix[2][3]);
        planes[4].normalize();
        // Far clipping plane
        planes[5].setNormal(Math::Direction(VPMatrix[3][0] - VPMatrix[2][0],
                                            VPMatrix[3][1] - VPMatrix[2][1],
                                            VPMatrix[3][2] - VPMatrix[2][2]));
        planes[5].setDistance(VPMatrix[3][3] - VPMatrix[2][3]);
        planes[5].normalize();
    }
}
References GLESC::Math::MatrixAlgorithms::columnMajorMatrix, GLESC::isIterable_v, and planes.
Referenced by Frustum(), and update().
getPlanes()
const std::array< Math::Plane, 6 > & GLESC::Render::Frustum::getPlanes () const inline
Definition at line 21 of file Frustum.h.
{
            return planes;
        }
References planes.
update()
void GLESC::Render::Frustum::update (const VP & VPMat) inline
Updates the frustum planes based on new view and projection matrices.
Parameters
VPMat The combined view-projection matrix.
Definition at line 39 of file Frustum.h.
{
            extractPlanes(VPMat);
        }
References extractPlanes(), and GLESC::isIterable_v.
Referenced by GLESC::Render::Renderer::render().
Member Data Documentation
planes
std::array<Math::Plane, 6> GLESC::Render::Frustum::planes {} private
Definition at line 65 of file Frustum.h.
{};
Referenced by contains(), contains(), extractPlanes(), and getPlanes().
The documentation for this class was generated from the following files:
Frustum.h
Frustum.cpp