GLESC: GLESC::Render::Skybox Class Reference
GLESC::Render::Skybox Class Reference
Class that represents a skybox.
#include <Skybox.h>
Public Member Functions
Skybox (const std::string &folderName="default")
Sybox constructor. Is in charge of loading the cubemap, creating the textures, loading the buffers and loading the shaders.
void calculateAverageColor ()
Calculates the average color of the skybox.
void draw (const View &view, const Projection &projection) const
Renders the skybox around the player given the view and projection.
ColorRgb getAverageColor () const
Returns the average color of the skybox. It is cached so it is not recalculated every frame.
Private Attributes
ColorRgb averageColor
Cubemap skyboxCubemap
Shader skyboxShader
std::unique_ptr< VertexArray > skyboxVAO
UInt skyboxVAOID
std::unique_ptr< VertexBuffer > skyboxVBO
UInt skyboxVBOID
float skyboxVertices [108]
Detailed Description
Class that represents a skybox.
Stores the skybox cubemap, and handles the textures and rendering of the skybox.
Definition at line 23 of file Skybox.h.
Constructor & Destructor Documentation
Skybox()
Skybox::Skybox (const std::string & folderName = "default") explicit
Sybox constructor. Is in charge of loading the cubemap, creating the textures, loading the buffers and loading the shaders.
Definition at line 13 of file Skybox.cpp.
    : skyboxCubemap(Cubemap(std::array<std::string, 6>{
          "skyboxes/" + folderName + "/" + std::string("right.png"),
          "skyboxes/" + folderName + "/" + std::string("left.png"),
          "skyboxes/" + folderName + "/" + std::string("top.png"),
          "skyboxes/" + folderName + "/" + std::string("bottom.png"),
          "skyboxes/" + folderName + "/" + std::string("front.png"),
          "skyboxes/" + folderName + "/" + std::string("back.png")
      })), skyboxShader("SkyboxShader.glsl"),
      skyboxVAOID{0}, skyboxVBOID{0},
      skyboxVertices{
          // positions
          -1.0f, 1.0f, -1.0f,
          -1.0f, -1.0f, -1.0f,
          1.0f, -1.0f, -1.0f,
          1.0f, -1.0f, -1.0f,
          1.0f, 1.0f, -1.0f,
          -1.0f, 1.0f, -1.0f,
          -1.0f, -1.0f, 1.0f,
          -1.0f, -1.0f, -1.0f,
          -1.0f, 1.0f, -1.0f,
          -1.0f, 1.0f, -1.0f,
          -1.0f, 1.0f, 1.0f,
          -1.0f, -1.0f, 1.0f,
          1.0f, -1.0f, -1.0f,
          1.0f, -1.0f, 1.0f,
          1.0f, 1.0f, 1.0f,
          1.0f, 1.0f, 1.0f,
          1.0f, 1.0f, -1.0f,
          1.0f, -1.0f, -1.0f,
          -1.0f, -1.0f, 1.0f,
          -1.0f, 1.0f, 1.0f,
          1.0f, 1.0f, 1.0f,
          1.0f, 1.0f, 1.0f,
          1.0f, -1.0f, 1.0f,
          -1.0f, -1.0f, 1.0f,
          -1.0f, 1.0f, -1.0f,
          1.0f, 1.0f, -1.0f,
          1.0f, 1.0f, 1.0f,
          1.0f, 1.0f, 1.0f,
          -1.0f, 1.0f, 1.0f,
          -1.0f, 1.0f, -1.0f,
          -1.0f, -1.0f, -1.0f,
          -1.0f, -1.0f, 1.0f,
          1.0f, -1.0f, -1.0f,
          1.0f, -1.0f, -1.0f,
          -1.0f, -1.0f, 1.0f,
          1.0f, -1.0f, 1.0f
      } {
    size_t skyboxVerticesCount = sizeof(skyboxVertices) / sizeof(float);
    size_t skyboxVerticesSize = sizeof(float);
    calculateAverageColor();
    skyboxCubemap.release();
    skyboxVAO = std::make_unique<VertexArray>();
    skyboxVAO->bind();
    skyboxVBO = std::make_unique<VertexBuffer>(
        &skyboxVertices,
        skyboxVerticesCount,
        skyboxVerticesSize,
        Enums::BufferUsages::StaticDraw);
    VertexBufferLayout skyboxLayout;
    skyboxLayout.push(Enums::Types::Vec3F);
    skyboxVAO->addBuffer(*skyboxVBO, skyboxLayout);
}
References GLESC::isIterable_v.
Member Function Documentation
calculateAverageColor()
void Skybox::calculateAverageColor ()
Calculates the average color of the skybox.
Takes a set of random pixles and calculates the average color between them. For now it is not used.
Definition at line 87 of file Skybox.cpp.
{
    // To calculate the average color of the skybox we'll get 20 pixels at random
    // and calculate the average color of those pixels
    // (technicall its gonna be 120 as we get 6 pixels per sample)
    for (int i = 0; i < PIXEL_SAMPLE_COUNT; i++) {
        // Its a cube, with the width is enough, no need more checking
        Size pixelWidth = skyboxCubemap.getCubemapTextures()[0].getWidth();
        Size x = Math::generateRandomNumber(static_cast<Size>(0), pixelWidth - 1);
        Size y = Math::generateRandomNumber(static_cast<Size>(0), pixelWidth - 1);
        std::array<Pixel, 6> pixels = skyboxCubemap.getPixelsAtCoords(x, y);
        ColorRgb finalColor;
        for (int pix = 0; pix < 6; pix++) {
            ColorRgb pixColor =
                ColorRgb(pixels[pix].r, pixels[pix].g, pixels[pix].b);
            finalColor += pixColor;
        }
        finalColor /= pixels.size();
        averageColor += finalColor;
    }
    averageColor /= PIXEL_SAMPLE_COUNT;
}
References averageColor, GLESC::Math::generateRandomNumber(), Cubemap::getCubemapTextures(), Cubemap::getPixelsAtCoords(), GLESC::isIterable_v, PIXEL_SAMPLE_COUNT, and skyboxCubemap.
draw()
void Skybox::draw (const View & view, const Projection & projection) const
Renders the skybox around the player given the view and projection.
A skybox is a cubemap that is always aroud the player and simulates infinity distance. This is done by having the skybox follow the camera and having the depth component in the shader to be maximum depth (1.0).
Parameters
view
projection
Definition at line 109 of file Skybox.cpp.
{
    Mat3F resizedView(view);
    VP viewTranslationless(resizedView);
    // change depth function so depth test passes when values are equal to depth buffer's content
    getGAPI().setDepthFunction(Enums::DepthFuncs::LessEqual);
    skyboxShader.bind();
    Shader::setUniform("uVPTranslationless", projection * viewTranslationless);
    skyboxVAO->bind();
    skyboxCubemap.bind();
    getGAPI().drawTriangles(0, 36);
    getGAPI().setDepthFunction(Enums::DepthFuncs::Less);
}
References GLESC::GAPI::Shader::bind(), Cubemap::bind(), getGAPI(), GLESC::isIterable_v, GLESC::GAPI::Shader::setUniform(), skyboxCubemap, skyboxShader, and skyboxVAO.
getAverageColor()
ColorRgb GLESC::Render::Skybox::getAverageColor () const inline
Returns the average color of the skybox. It is cached so it is not recalculated every frame.
Returns
Definition at line 35 of file Skybox.h.
{ return averageColor; }
References averageColor.
Member Data Documentation
averageColor
ColorRgb GLESC::Render::Skybox::averageColor private
Definition at line 54 of file Skybox.h.
Referenced by calculateAverageColor(), and getAverageColor().
skyboxCubemap
Cubemap GLESC::Render::Skybox::skyboxCubemap private
Definition at line 58 of file Skybox.h.
Referenced by calculateAverageColor(), and draw().
skyboxShader
Shader GLESC::Render::Skybox::skyboxShader private
Definition at line 57 of file Skybox.h.
Referenced by draw().
skyboxVAO
std::unique_ptr<VertexArray> GLESC::Render::Skybox::skyboxVAO private
Definition at line 60 of file Skybox.h.
Referenced by draw().
skyboxVAOID
UInt GLESC::Render::Skybox::skyboxVAOID private
Definition at line 55 of file Skybox.h.
skyboxVBO
std::unique_ptr<VertexBuffer> GLESC::Render::Skybox::skyboxVBO private
Definition at line 61 of file Skybox.h.
skyboxVBOID
UInt GLESC::Render::Skybox::skyboxVBOID private
Definition at line 56 of file Skybox.h.
skyboxVertices
float GLESC::Render::Skybox::skyboxVertices[108] private
Definition at line 62 of file Skybox.h.
The documentation for this class was generated from the following files:
Skybox.h
Skybox.cpp