GLESC: GLESC::HUD::DebugItems Class Reference
GLESC::HUD::DebugItems Class Reference
Class that encapsulates the logic of the debug displaying of non visible items.
#include <DebugItemsHUD.h>
Public Member Functions
DebugItems (Render::Renderer &renderer, TextureFactory &textureFactory)
Public Member Functions inherited from GLESC::InGameWindow
InGameWindow ()
virtual ~InGameWindow ()=default
void addFlag (ImGuiWindowFlags_ flag)
const std::string & getTitle () const
bool isVisibile () const
void render (float timeOfFrame)
Render the window.
void setCenter (WindowCenter center)
Set the center of the window.
void setLayoutPosition (LayoutPos position)
Set the layout position of the window.
void setMaxSize (ImVec2 size)
Set the max size of the window.
void setMinSize (ImVec2 size)
Set the min size of the window.
void setPositionFraction (ImVec2 fraction)
Set the position of the window as a fraction of the screen size.
void setSizeFraction (ImVec2 fraction)
Set the size of the window as a fraction of the screen size.
void setVisible (bool visible)
void toggleVisibility ()
void update ()
Update the window position and size.
Private Member Functions
void windowContent (float timeOfFrame) override
Private Attributes
std::unordered_map< const Transform::Position *, Transform::Interpolator > interpolators
std::unordered_map< HudItemType, Render::Texture * > items
Render::Renderer & renderer
TextureFactory & textureFactory
Additional Inherited Members
Protected Member Functions inherited from GLESC::InGameWindow
ImVec2 calculatePosition (ImVec2 windowSize) const
ImVec2 calculateSize () const
ImGuiWindowFlags getFlags ()
void setTitle (const std::string &title)
Protected Attributes inherited from GLESC::InGameWindow
bool isVisible = true
Detailed Description
Class that encapsulates the logic of the debug displaying of non visible items.
Allows seeing as heads up display the items that are not visible in the game world. Such as sun, lights, etc. Helps with debugging.
Definition at line 28 of file DebugItemsHUD.h.
Constructor & Destructor Documentation
DebugItems()
DebugItems::DebugItems (Render::Renderer & renderer, TextureFactory & textureFactory)
Definition at line 8 of file DebugItemsHUD.cpp.
                                                                              :
    renderer(renderer),
    textureFactory(textureFactory) {
    items[HudItemType::LIGHT_SPOT] = &textureFactory.loadTexture("sprites/engine-debug/GLESC_Light.png");
    items[HudItemType::LIGHT_SPOT]->release();
    items[HudItemType::SUN] = &textureFactory.loadTexture("sprites/engine-debug/GLESC_Sun.png");
    items[HudItemType::SUN]->release();
    items[HudItemType::FOG] = &textureFactory.loadTexture("sprites/engine-debug/GLESC_Fog.png");
    items[HudItemType::FOG]->release();
    this->setTitle("Items");
    this->setSizeFraction({1.0f, 1.0f});
    this->setMinSize({300.0f, 300.0f});
    this->isVisible = true;
    this->setCenter(WindowCenter::Center);
    this->setLayoutPosition(LayoutPos::Center);
    this->addFlag(ImGuiWindowFlags_NoResize);
    this->addFlag(ImGuiWindowFlags_NoMove);
    this->addFlag(ImGuiWindowFlags_NoCollapse);
    this->addFlag(ImGuiWindowFlags_NoTitleBar);
    this->addFlag(ImGuiWindowFlags_NoSavedSettings);
    this->addFlag(ImGuiWindowFlags_NoBringToFrontOnFocus);
    this->addFlag(ImGuiWindowFlags_NoScrollbar);
    this->addFlag(ImGuiWindowFlags_NoBackground);
}
References GLESC::InGameWindow::addFlag(), GLESC::Center, FOG, GLESC::isIterable_v, GLESC::InGameWindow::isVisible, items, LIGHT_SPOT, TextureFactory::loadTexture(), GLESC::Render::Texture::release(), GLESC::InGameWindow::setCenter(), GLESC::InGameWindow::setLayoutPosition(), GLESC::InGameWindow::setMinSize(), GLESC::InGameWindow::setSizeFraction(), GLESC::InGameWindow::setTitle(), SUN, and textureFactory.
Member Function Documentation
windowContent()
void DebugItems::windowContent (float timeOfFrame) override private virtual
Implements GLESC::InGameWindow.
Definition at line 35 of file DebugItemsHUD.cpp.
{
    float width = static_cast<float>(renderer.getViewportSize().width);
    float height = static_cast<float>(renderer.getViewportSize().height);
    const auto& viewProj = renderer.getViewProjection();
    float vpWidth = static_cast<float>(renderer.getViewportSize().height);
    float vpHeight = static_cast<float>(renderer.getViewportSize().height);
    for (Item& item : HudItemsManager::getItems()) {
        if (!renderer.getFrustum().contains(*item.worldPosition)) continue;
        // TODO: Possible memory leak here if the item is not removed from the interpolators map
        interpolators[item.worldPosition].pushTransform(Transform::Transform(*
                                                                             item.worldPosition, {}, {1, 1, 1}));
        Render::Position screenPos =
            Transform::Transformer::worldToViewport(
                interpolators[item.worldPosition].interpolate(timeOfFrame).getPosition(),
                viewProj, width, height);
        float imageScale = screenPos.z() * 20;
        ImVec2 size = ImVec2(imageScale * vpWidth, imageScale * vpHeight);
        ImGui::SetCursorPos(ImVec2(screenPos.x() - size.x / 2, screenPos.y() - size.y / 2));
        // Get texture ID from the item's type
        auto textureId = (void*)(intptr_t)items[item.type]->getTextureID();
        // Draw the texture at the specified position
        ImGui::Image(textureId, ImVec2(size.x, size.y));
        // Optionally, you can create a tooltip on hover
        if (ImGui::IsItemHovered()) {
            ImGui::BeginTooltip();
            ImGui::Text("Item: %s", itemToString(item.type).c_str());
            ImGui::Text("Screen Position: (%.2f, %.2f)", screenPos.x(), screenPos.y());
            ImGui::EndTooltip();
        }
    }
}
References GLESC::Render::Frustum::contains(), GLESC::Render::Renderer::getFrustum(), HudItemsManager::getItems(), GLESC::Render::Renderer::getViewportSize(), GLESC::Render::Renderer::getViewProjection(), GLESC::WindowDimensions::height, interpolators, GLESC::isIterable_v, items, itemToString(), renderer, GLESC::InGameWindow::size, GLESC::WindowDimensions::width, and GLESC::Transform::Transformer::worldToViewport().
Member Data Documentation
interpolators
std::unordered_map<const Transform::Position*, Transform::Interpolator> GLESC::HUD::DebugItems::interpolators mutable private
Definition at line 36 of file DebugItemsHUD.h.
Referenced by windowContent().
items
std::unordered_map<HudItemType, Render::Texture*> GLESC::HUD::DebugItems::items private
Definition at line 37 of file DebugItemsHUD.h.
Referenced by DebugItems(), and windowContent().
renderer
Render::Renderer& GLESC::HUD::DebugItems::renderer private
Definition at line 35 of file DebugItemsHUD.h.
Referenced by windowContent().
textureFactory
TextureFactory& GLESC::HUD::DebugItems::textureFactory private
Definition at line 34 of file DebugItemsHUD.h.
Referenced by DebugItems().
The documentation for this class was generated from the following files:
DebugItemsHUD.h
DebugItemsHUD.cpp