GLESC: Counter Class Reference
Counter Class Reference
#include <Counter.h>
Public Member Functions
Counter ()=default
Default constructor.
void addToCounter (float value)
Adds a value to the counter.
float getCount () const
Returns the current count.
void startCounter ()
Starts counter from 0.
Private Attributes
float count {0}
The current count.
Detailed Description
Definition at line 12 of file Counter.h.
Constructor & Destructor Documentation
Counter()
Counter::Counter () default
Default constructor.
Member Function Documentation
addToCounter()
void Counter::addToCounter (float value) inline
Adds a value to the counter.
Parameters
value - the value to be added to the counter.
Definition at line 30 of file Counter.h.
{
        count += value;
    }
References count.
Referenced by GLESC::Render::Renderer::renderMesh().
getCount()
float Counter::getCount () const inline
Returns the current count.
Returns
the current count.
Definition at line 37 of file Counter.h.
{
        return count;
    }
References count.
Referenced by GLESC::Render::Renderer::getMeshRenderCount().
startCounter()
void Counter::startCounter () inline
Starts counter from 0.
Definition at line 22 of file Counter.h.
{
        count = 0;
    }
References count.
Referenced by GLESC::Render::Renderer::render().
Member Data Documentation
count
float Counter::count {0} private
The current count.
Definition at line 45 of file Counter.h.
{0};
Referenced by addToCounter(), getCount(), and startCounter().
The documentation for this class was generated from the following file:
Counter.h