GLESC: FileLogger Class Reference
FileLogger Class Reference
#include <FileLogger.h>
Public Member Functions
FileLogger ()
~FileLogger () override
void error (const std::string &text) override
Display error messages Background – Red Text – Black Bold.
void importantInfo (const std::string &text) override
Display important information Background – White Text – Black.
void importantInfoBlue (const std::string &text) override
Display important information Background – Light Blue Text – Black.
void importantInfoPurple (const std::string &text) override
Display important information Background – Light Purple Text – Black.
void importantInfoWhite (const std::string &text) override
Display important information Background – White Text – Black.
void importantSuccess (const std::string &text) override
Display important success information.
void info (const std::string &text) override
Display basic information Background – Black Text – White.
void infoBlue (const std::string &text) override
Display basic information Background – Black Text – Light Blue.
void infoPurple (const std::string &text) override
Display basic information Background – Black Text – Light Purple.
void log (const std::string &text) override
Display log messages Background and text default.
void nonImportantInfo (const std::string &text) override
Display non important information Background – Black Text – Grey.
void success (const std::string &text) override
Display success information Background – Green Text – White Bold.
void warning (const std::string &text) override
Display warning messages Background – Black Text – Yellow.
Public Member Functions inherited from ILogger
virtual ~ILogger ()=default
Private Member Functions
void clearFileContent ()
Private Attributes
std::ofstream logFile
Detailed Description
Definition at line 16 of file FileLogger.h.
Constructor & Destructor Documentation
FileLogger()
FileLogger::FileLogger ()
Definition at line 8 of file FileLogger.cpp.
                       {
    clearFileContent();
    // Open the log file in append mode
    logFile.open(LOG_FILE, std::ios::app);
    D_ASSERT_TRUE(logFile.is_open(), "Log file couldn't be opened.");
}
References clearFileContent(), D_ASSERT_TRUE, LOG_FILE, and logFile.
~FileLogger()
FileLogger::~FileLogger () override
Definition at line 22 of file FileLogger.cpp.
{
    logFile.close();
}
References logFile.
Member Function Documentation
clearFileContent()
void FileLogger::clearFileContent () private
Definition at line 15 of file FileLogger.cpp.
{
    // Open the file in truncation mode to clear its contents
    logFile.open(LOG_FILE, std::ios::trunc);
    logFile.close();
}
References LOG_FILE, and logFile.
Referenced by FileLogger().
error()
void FileLogger::error (const std::string & text) override virtual
Display error messages Background – Red Text – Black Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 30 of file FileLogger.cpp.
{
    logFile << "[ERROR] " << text << std::endl;
}
References logFile, and text().
importantInfo()
void FileLogger::importantInfo (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 54 of file FileLogger.cpp.
{
    logFile << "[IMPORTANT INFO] " << text << std::endl;
}
References logFile, and text().
importantInfoBlue()
void FileLogger::importantInfoBlue (const std::string & text) override virtual
Display important information Background – Light Blue Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 58 of file FileLogger.cpp.
{
    logFile << "[IMPORTANT INFO Blue] " << text << std::endl;
}
References logFile, and text().
importantInfoPurple()
void FileLogger::importantInfoPurple (const std::string & text) override virtual
Display important information Background – Light Purple Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 62 of file FileLogger.cpp.
{
    logFile << "[IMPORTANT INFO Purple] " << text << std::endl;
}
References logFile, and text().
importantInfoWhite()
void FileLogger::importantInfoWhite (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 66 of file FileLogger.cpp.
{
    logFile << "[IMPORTANT INFO White] " << text << std::endl;
}
References logFile, and text().
importantSuccess()
void FileLogger::importantSuccess (const std::string & text) override virtual
Display important success information.
Parameters
text
Implements ILogger.
Definition at line 70 of file FileLogger.cpp.
{
    logFile << "[IMPORTANT SUCCESS] " << text << std::endl;
}
References logFile, and text().
info()
void FileLogger::info (const std::string & text) override virtual
Display basic information Background – Black Text – White.
Parameters
text printed text
Implements ILogger.
Definition at line 42 of file FileLogger.cpp.
{
    logFile << "[INFO] " << text << std::endl;
}
References logFile, and text().
infoBlue()
void FileLogger::infoBlue (const std::string & text) override virtual
Display basic information Background – Black Text – Light Blue.
Parameters
text printed text
Implements ILogger.
Definition at line 46 of file FileLogger.cpp.
{
    logFile << "[INFO Blue] " << text << std::endl;
}
References logFile, and text().
infoPurple()
void FileLogger::infoPurple (const std::string & text) override virtual
Display basic information Background – Black Text – Light Purple.
Parameters
text printed text
Implements ILogger.
Definition at line 50 of file FileLogger.cpp.
{
    logFile << "[INFO Purple] " << text << std::endl;
}
References logFile, and text().
log()
void FileLogger::log (const std::string & text) override virtual
Display log messages Background and text default.
Parameters
text
Implements ILogger.
Definition at line 26 of file FileLogger.cpp.
{
    logFile << "[LOG] " << text << std::endl;
}
References logFile, and text().
nonImportantInfo()
void FileLogger::nonImportantInfo (const std::string & text) override virtual
Display non important information Background – Black Text – Grey.
Parameters
text printed text
Implements ILogger.
Definition at line 38 of file FileLogger.cpp.
{
    logFile << "[NON IMPORTANT INFO] " << text << std::endl;
}
References logFile, and text().
success()
void FileLogger::success (const std::string & text) override virtual
Display success information Background – Green Text – White Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 74 of file FileLogger.cpp.
{
    logFile << "[SUCCESS] " << text << std::endl;
}
References logFile, and text().
warning()
void FileLogger::warning (const std::string & text) override virtual
Display warning messages Background – Black Text – Yellow.
Parameters
text printed text
Implements ILogger.
Definition at line 34 of file FileLogger.cpp.
{
    logFile << "[WARNING] " << text << std::endl;
}
References logFile, and text().
Member Data Documentation
logFile
std::ofstream FileLogger::logFile private
Definition at line 50 of file FileLogger.h.
Referenced by FileLogger(), ~FileLogger(), clearFileContent(), error(), importantInfo(), importantInfoBlue(), importantInfoPurple(), importantInfoWhite(), importantSuccess(), info(), infoBlue(), infoPurple(), log(), nonImportantInfo(), success(), and warning().
The documentation for this class was generated from the following files:
FileLogger.h
FileLogger.cpp