GLESC: GLESC::HUD::HUDManager Class Reference
GLESC::HUD::HUDManager Class Reference
#include <HUDManager.h>
Public Types
using WindowID = int
Public Member Functions
HUDManager (SDL_Window &window)
Constructor for the HUDManager.
~HUDManager ()
Destructor for the HUDManager.
WindowID addWindow (InGameWindow &window)
Add a new window to the HUD.
InGameWindow & getWindow (WindowID id)
Get a window by its ID.
void processInput (SDL_Event &event)
Process input for the HUD.
void removeWindow (WindowID id)
void render (double timeOfFrame)
Render the HUD.
void update ()
Update the HUD.
Private Member Functions
void endFrame ()
void initImGUI ()
void newFrame ()
Private Attributes
WindowID nextWindowID = 0
SDL_Window & window
std::unordered_map< WindowID, GLESC::InGameWindow * > windowIDs
std::vector< GLESC::InGameWindow * > windows
Detailed Description
Definition at line 20 of file HUDManager.h.
Member Typedef Documentation
WindowID
using GLESC::HUD::HUDManager::WindowID = int
The ID of a window
Definition at line 25 of file HUDManager.h.
Constructor & Destructor Documentation
HUDManager()
HUDManager::HUDManager (SDL_Window & window) explicit
Constructor for the HUDManager.
Parameters
window The SDL window to render the HUD on
Definition at line 15 of file HUDManager.cpp.
                                         :
    window(window) {
    initImGUI();
}
References initImGUI().
~HUDManager()
HUDManager::~HUDManager ()
Destructor for the HUDManager.
Definition at line 20 of file HUDManager.cpp.
{
#ifdef GLESC_OPENGL
    ImGui_ImplOpenGL3_Shutdown();
#endif
    ImGui_ImplSDL2_Shutdown();
    ImGui::DestroyContext();
}
References GLESC::isIterable_v.
Member Function Documentation
addWindow()
HUDManager::WindowID HUDManager::addWindow (GLESC::InGameWindow & window)
Add a new window to the HUD.
Uses the move operator, this manager will take ownership of the window
Returns
the ID of the window
Definition at line 32 of file HUDManager.cpp.
{
    WindowID id = nextWindowID;
    windows.push_back(&window);
    windowIDs.insert(std::make_pair(id, &window));
    nextWindowID++;
    return id;
}
References GLESC::isIterable_v, nextWindowID, window, windowIDs, and windows.
Referenced by GLESC::HUD::EngineHUDManager::EngineHUDManager(), and GLESC::Scene::Scene::addWindow().
endFrame()
void HUDManager::endFrame () private
Definition at line 81 of file HUDManager.cpp.
{
    ImGui::EndFrame();
    ImGui::Render();
#ifdef GLESC_OPENGL
    ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());
#endif
}
References GLESC::isIterable_v.
Referenced by render().
getWindow()
GLESC::InGameWindow & HUDManager::getWindow (WindowID id)
Get a window by its ID.
Parameters
id The ID of the window
Returns
The window
Definition at line 40 of file HUDManager.cpp.
{
    return *windowIDs[id];
}
References GLESC::isIterable_v, and windowIDs.
Referenced by GLESC::Scene::Scene::getWindow().
initImGUI()
void HUDManager::initImGUI () private
Definition at line 90 of file HUDManager.cpp.
{
    // Setup Dear ImGui context
    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGui::GetIO().ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;
    std::string glslCoreStr = GLESC_GLSL_CORE_PROFILE ? "core" : "";
    std::string glslVersionStr = "#version " + std::to_string(GLESC_GL_MAJOR_VERSION) + "" +
        std::to_string(GLESC_GL_MINOR_VERSION) + "0 " + glslCoreStr + "\n";
#ifdef GLESC_OPENGL
    // Setup Platform/Renderer bindings
    ImGui_ImplSDL2_InitForOpenGL(&window, getGAPI().getContext());
    ImGui_ImplOpenGL3_Init(glslVersionStr.c_str());
#endif
    HudLookAndFeel::get().setDefaultFont("PixelIntv");
    HudLookAndFeel::get().setDefaultFontSize(20);
    // This must be called after all the inits
    for (int i = 5; i < 40; i++) {
        HudLookAndFeel::get().addFont(HudLookAndFeel::get().getDefaultFont(), i);
    }
    HudLookAndFeel::get().apply();
}
References HudLookAndFeel::addFont(), HudLookAndFeel::apply(), HudLookAndFeel::get(), getGAPI(), GLESC_GL_MAJOR_VERSION, GLESC_GL_MINOR_VERSION, GLESC_GLSL_CORE_PROFILE, GLESC::isIterable_v, HudLookAndFeel::setDefaultFont(), HudLookAndFeel::setDefaultFontSize(), and window.
Referenced by HUDManager().
newFrame()
void HUDManager::newFrame () private
Definition at line 73 of file HUDManager.cpp.
{
#ifdef GLESC_OPENGL
    ImGui_ImplOpenGL3_NewFrame();
#endif
    ImGui_ImplSDL2_NewFrame(&window);
    ImGui::NewFrame();
}
References GLESC::isIterable_v, and window.
Referenced by render().
processInput()
void HUDManager::processInput (SDL_Event & event)
Process input for the HUD.
Calls the ImGui SDL input processing function
Parameters
event The SDL event to process
Definition at line 28 of file HUDManager.cpp.
{
    ImGui_ImplSDL2_ProcessEvent(&event);
}
References GLESC::isIterable_v.
Referenced by GLESC::Input::InputManager::update().
removeWindow()
void HUDManager::removeWindow (WindowID id)
Remove a window from the HUD
Parameters
id The ID of the window to remove
Definition at line 44 of file HUDManager.cpp.
{
    auto it = windowIDs.find(id);
    if (it != windowIDs.end()) {
        // Remove from vector
        auto win_it = std::find(windows.begin(), windows.end(), it->second);
        if (win_it != windows.end()) {
            windows.erase(win_it);
        }
        // Remove from map
        windowIDs.erase(it);
    } else {
        D_ASSERT_TRUE(false, "Window ID not found");
    }
}
References D_ASSERT_TRUE, GLESC::isIterable_v, windowIDs, and windows.
Referenced by GLESC::Scene::Scene::destroyWindows().
render()
void HUDManager::render (double timeOfFrame)
Render the HUD.
The time of frame is needed to interpolate hud items and allow for smooth rendering
Parameters
timeOfFrame The time of the current frame
Definition at line 65 of file HUDManager.cpp.
{
    newFrame();
    for (auto& window : windows) {
        window->render(static_cast<float>(timeOfFrame));
    }
    endFrame();
}
References endFrame(), GLESC::isIterable_v, newFrame(), window, and windows.
Referenced by GLESC::Engine::render().
update()
void HUDManager::update ()
Update the HUD.
Updates the positions of the windows given their layout configurations and the current window size
Definition at line 59 of file HUDManager.cpp.
{
    for (auto& window : windows) {
        window->update();
    }
}
References window, and windows.
Referenced by GLESC::Engine::update().
Member Data Documentation
nextWindowID
WindowID GLESC::HUD::HUDManager::nextWindowID = 0 private
Definition at line 84 of file HUDManager.h.
Referenced by addWindow().
window
SDL_Window& GLESC::HUD::HUDManager::window private
Definition at line 83 of file HUDManager.h.
Referenced by addWindow(), initImGUI(), newFrame(), render(), and update().
windowIDs
std::unordered_map<WindowID, GLESC::InGameWindow*> GLESC::HUD::HUDManager::windowIDs private
Definition at line 86 of file HUDManager.h.
Referenced by addWindow(), getWindow(), and removeWindow().
windows
std::vector<GLESC::InGameWindow*> GLESC::HUD::HUDManager::windows private
Definition at line 85 of file HUDManager.h.
Referenced by addWindow(), removeWindow(), render(), and update().
The documentation for this class was generated from the following files:
HUDManager.h
HUDManager.cpp