GLESC: Default Class Reference
Default Class Reference
Default scene.
#include <Default.h>
Public Member Functions
void init () override
Initializes the scene. Must be implemented by the derived class.
void update () override
Updates the scene. Must be implemented by the derived class.
Public Member Functions inherited from GLESC::Scene::Scene
Scene (WindowManager &windowManager, ECS::EntityFactory &entityFactory, Input::InputManager &inputManager, SceneManager &sceneManager, HUD::HUDManager &hudManager, EngineCamera &camera)
Constructor for the Scene class.
virtual ~Scene ()=default
virtual void destroy ()=0
Destroys the scene. Must be implemented by the derived class.
EngineCamera & getCamera ()
TimeMillis getSceneTimeMillis ()
Gets the scene time in milliseconds.
TimeSecondsUI getSceneTimeSeconds ()
Gets the scene time in seconds.
bool isInitialized () const
Checks if the scene is initialized.
void setInitialized (bool initializedParam)
template<typename SceneType >
void switchScene ()
Switches to another scene.
Additional Inherited Members
Protected Member Functions inherited from GLESC::Scene::Scene
template<typename WindowType >
HUD::HUDManager::WindowID addWindow ()
Adds a window to the scene.
ECS::Entity createEntity ()
Creates an entity and adds it to the scene.
ECS::Entity createEntity (const std::string &entityName, const ECS::EntityMetadata &metadata={})
Creates an entity and adds it to the scene.
void destroyEntities ()
Destroys all entities in the scene.
void destroyEntity (const ECS::EntityID &entityID)
Destroys an entity by ID.
void destroyEntity (const std::string &entityName)
Destroys an entity by name.
void destroyWindows ()
Removes a window by ID.
ECS::Entity getEntity (const ECS::EntityID &entityID)
Gets an entity by ID.
ECS::Entity getEntity (const std::string &entityName)
Gets an entity by name.
std::vector< ECS::EntityID > & getSceneEntities ()
Gets the scene entities.
template<typename WindowType >
WindowType & getWindow (HUD::HUDManager::WindowID id)
Gets a window by ID.
Protected Attributes inherited from GLESC::Scene::Scene
ECS::EntityFactory & entityFactory
Input::InputManager & inputManager
WindowManager & windowManager
Detailed Description
Default scene.
This is the default scene that is loaded when the engine starts. It contains some objects rotationg, some lights and the camera with default camera movement.
Definition at line 18 of file Default.h.
Member Function Documentation
init()
void Default::init () override virtual
Initializes the scene. Must be implemented by the derived class.
Implements GLESC::Scene::Scene.
Definition at line 19 of file Default.cpp.
                   {
    int numOfEntities = 20;
    for (int i = 0; i < numOfEntities; i++) {
        ECS::Entity entity = createEntity("entity" + std::to_string(i))
                                          .addComponent<ECS::TransformComponent>()
                                          .addComponent<ECS::RenderComponent>();
        float increment = Math::clamp(0.1f * static_cast<float>(i), 0.0f, 1.0f);
        Transform::Position position = Transform::Position(i * 3, 0, 0);
        // Setting position
        entity.getComponent<ECS::TransformComponent>().transform.setPosition(position);
        // Setting scale
        entity.getComponent<ECS::TransformComponent>().transform.setScale(
            Transform::Scale(1 + i * 0.1, 1 + i * 0.1, 1 + i * 0.1));
        // Choosing a color
        Render::ColorRgba color = Render::ColorRgba(increment * 255,
                                                    255 - 255 * increment,
                                                    255 - 255 * increment,
                                                    255);
        // Setting mesh, cube, sphere, pyramid, in this order
        if (i % 3 == 1)
            entity.getComponent<ECS::RenderComponent>().moveMesh(
                Render::MeshFactory::sphere(4 + i, 4 + i, 1, color));
        else
            entity.getComponent<ECS::RenderComponent>().moveMesh(
                Render::MeshFactory::cube(color));
        // Put a light every 3 entities
        if (i % 3 == 0) {
            ECS::Entity light = createEntity("light" + std::to_string(i))
                                             .addComponent<ECS::TransformComponent>()
                                             .addComponent<ECS::LightComponent>();
            light.getComponent<ECS::TransformComponent>().transform.setPosition(
                Transform::Position(position + Transform::Position(0, 0, 1 + increment)));
        }
        // Setting material
        entity.getComponent<ECS::RenderComponent>().getMaterial().setShininess(increment);
        entity.getComponent<ECS::RenderComponent>().getMaterial().setSpecularColor(
            Render::ColorRgb(increment * 255, increment * 255, increment * 255));
        entities.push_back(entity);
    }
}
References GLESC::ECS::Entity::addComponent(), GLESC::Math::clamp(), GLESC::Scene::Scene::createEntity(), GLESC::Render::MeshFactory::cube(), entities, GLESC::ECS::Entity::getComponent(), GLESC::isIterable_v, and GLESC::Render::MeshFactory::sphere().
update()
void Default::update () override virtual
Updates the scene. Must be implemented by the derived class.
Implements GLESC::Scene::Scene.
Definition at line 70 of file Default.cpp.
                     {
    for (auto& entity : entities) {
        auto& transform = entity.getComponent<ECS::TransformComponent>().transform;
        transform.addRotation(Transform::Rotation(0.01, 0.01, 0.1));
    }
}
References entities, and GLESC::isIterable_v.
The documentation for this class was generated from the following files:
Default.h
Default.cpp