GLESC: GLESC::Physics::CollisionManager Class Reference
GLESC::Physics::CollisionManager Class Reference
#include <CollisionManager.h>
Public Member Functions
void addCollider (Collider &collider, Physics &physics, Transform::Transform &transform)
void checkAndUpdateColliderInformation (Collider &collider, const Transform::Transform &originalTransform, const Transform::Transform &hypNextFrameTransform)
void clearColliders ()
Private Member Functions
void updateCollider (Collider &originalCollider, const Transform::Transform &originalTransform, const Math::BoundingVolume &nextColliderBVX, const Math::BoundingVolume &nextColliderBVY, const Math::BoundingVolume &nextColliderBVZ)
Static Private Member Functions
static Vec3F getCollisionDepth (const Math::BoundingVolume &nextColliderBVX, const Math::BoundingVolume &nextColliderBVY, const Math::BoundingVolume &nextColliderBVZ, const Math::BoundingVolume &otherBV)
Private Attributes
std::vector< Collider * > colliders
std::vector< Physics * > physicsOfColliders
std::vector< Transform::Transform * > transformsOfColliders
Detailed Description
Definition at line 19 of file CollisionManager.h.
Member Function Documentation
addCollider()
void GLESC::Physics::CollisionManager::addCollider (Collider & collider, Physics & physics, Transform::Transform & transform) inline
Definition at line 21 of file CollisionManager.h.
{
            this->colliders.push_back(&collider);
            this->transformsOfColliders.push_back(&transform);
            this->physicsOfColliders.push_back(&physics);
        }
References colliders, physicsOfColliders, and transformsOfColliders.
Referenced by GLESC::ECS::PhysicsCollisionSystem::update().
checkAndUpdateColliderInformation()
void CollisionManager::checkAndUpdateColliderInformation (Collider & collider, const Transform::Transform & originalTransform, const Transform::Transform & hypNextFrameTransform)
Definition at line 23 of file CollisionManager.cpp.
{
    // Clear the information before using it (so we don't accumulate information)
    collider.getCollisionInformation().clearInformation();
    // If it's not solid, go ahead and update the transform, nothing else to do
    if (!collider.isSolid()) {
        return;
    }
    Transform::Transform hypNextTransformX{};
    Transform::Transform hypNextTransformY{};
    Transform::Transform hypNextTransformZ{};
    hypNextTransformX.setPosition({
        hypNextFrameTransform.getPosition().getX(),
        originalTransform.getPosition().getY(),
        originalTransform.getPosition().getZ()
    });
    hypNextTransformY.setPosition({
        originalTransform.getPosition().getX(),
        hypNextFrameTransform.getPosition().getY(),
        originalTransform.getPosition().getZ()
    });
    hypNextTransformZ.setPosition({
        originalTransform.getPosition().getX(),
        originalTransform.getPosition().getY(),
        hypNextFrameTransform.getPosition().getZ()
    });
    const Math::BoundingVolume hypotheticalNextBVX = translateBV(collider, hypNextTransformX);
    const Math::BoundingVolume hypotheticalNextBVY = translateBV(collider, hypNextTransformY);
    const Math::BoundingVolume hypotheticalNextBVZ = translateBV(collider, hypNextTransformZ);
    // Cancel the component that causes the collision
    updateCollider(collider,
                   hypNextFrameTransform,
                   hypotheticalNextBVX,
                   hypotheticalNextBVY,
                   hypotheticalNextBVZ);
}
References GLESC::Physics::CollisionInformation::clearInformation(), GLESC::Physics::Collider::getCollisionInformation(), GLESC::isIterable_v, GLESC::Physics::Collider::isSolid(), GLESC::Transform::Transform::setPosition(), translateBV(), and updateCollider().
Referenced by GLESC::ECS::PhysicsCollisionSystem::update().
clearColliders()
void GLESC::Physics::CollisionManager::clearColliders () inline
Definition at line 27 of file CollisionManager.h.
{
            this->colliders.clear();
            this->transformsOfColliders.clear();
            this->physicsOfColliders.clear();
        }
References colliders, physicsOfColliders, and transformsOfColliders.
Referenced by GLESC::ECS::PhysicsCollisionSystem::update().
getCollisionDepth()
Vec3F CollisionManager::getCollisionDepth (const Math::BoundingVolume & nextColliderBVX, const Math::BoundingVolume & nextColliderBVY, const Math::BoundingVolume & nextColliderBVZ, const Math::BoundingVolume & otherBV) static private
Definition at line 101 of file CollisionManager.cpp.
{
    // Assumes that collision occured, therefore depth will be non-zero
    float depthX = nextColliderBVX.intersectionVolume(otherBV);
    float depthY = nextColliderBVY.intersectionVolume(otherBV);
    float depthZ = nextColliderBVZ.intersectionVolume(otherBV);
    // Negate volume if collision occurred on the negative side of the axis
    if (otherBV.getMin().getX() < nextColliderBVX.getMin().getX()) {
        depthX = -depthX;
    }
    if (otherBV.getMin().getY() < nextColliderBVY.getMin().getY()) {
        depthY = -depthY;
    }
    if (otherBV.getMin().getZ() < nextColliderBVZ.getMin().getZ()) {
        depthZ = -depthZ;
    }
    return {depthX, depthY, depthZ};
}
References GLESC::isIterable_v.
Referenced by updateCollider().
updateCollider()
void CollisionManager::updateCollider (Collider & originalCollider, const Transform::Transform & originalTransform, const Math::BoundingVolume & nextColliderBVX, const Math::BoundingVolume & nextColliderBVY, const Math::BoundingVolume & nextColliderBVZ) private
Definition at line 65 of file CollisionManager.cpp.
{
    Collider& ogColl = originalCollider;
    const Transform::Transform& ogTrans = originalTransform;
    ogColl.getCollisionInformation().setColliding(false);
    bool collidesX = false;
    bool collidesY = false;
    bool collidesZ = false;
    for (int i = 0; i < colliders.size(); i++) {
        if (&ogColl == colliders[i]) continue;
        Collider& otherCollider = *colliders[i];
        Physics& otherPhysics = *physicsOfColliders[i];
        Transform::Transform& otherTransform = *transformsOfColliders[i];
        Math::BoundingVolume transformedOriginalBV = translateBV(ogColl, ogTrans);
        Math::BoundingVolume transformedOtherBV = translateBV(otherCollider, otherTransform);
        if (transformedOriginalBV.intersects(transformedOtherBV)) {
            ogColl.getCollisionInformation().setColliding(true);
            Vec3F collisionDepths = getCollisionDepth(nextColliderBVX, nextColliderBVY, nextColliderBVZ,
                                                      transformedOtherBV);
            ogColl.getCollisionInformation().addCollidingWith(&otherCollider, &otherPhysics, collisionDepths);
            collidesX = collidesX || !Math::eq(collisionDepths.getX(), 0);
            collidesY = collidesY || !Math::eq(collisionDepths.getY(), 0);
            collidesZ = collidesZ || !Math::eq(collisionDepths.getZ(), 0);
        }
    }
    ogColl.getCollisionInformation().setCollidesAxis({collidesX, collidesY, collidesZ});
    bool isOnGround = ogColl.getCollisionInformation().getCollidingAxis().getY();
    ogColl.getCollisionInformation().setOnGround(isOnGround);
}
References colliders, GLESC::Math::eq(), getCollisionDepth(), GLESC::isIterable_v, physicsOfColliders, transformsOfColliders, and translateBV().
Referenced by checkAndUpdateColliderInformation().
Member Data Documentation
colliders
std::vector<Collider*> GLESC::Physics::CollisionManager::colliders private
Definition at line 52 of file CollisionManager.h.
Referenced by addCollider(), clearColliders(), and updateCollider().
physicsOfColliders
std::vector<Physics*> GLESC::Physics::CollisionManager::physicsOfColliders private
Definition at line 51 of file CollisionManager.h.
Referenced by addCollider(), clearColliders(), and updateCollider().
transformsOfColliders
std::vector<Transform::Transform*> GLESC::Physics::CollisionManager::transformsOfColliders private
Definition at line 53 of file CollisionManager.h.
Referenced by addCollider(), clearColliders(), and updateCollider().
The documentation for this class was generated from the following files:
CollisionManager.h
CollisionManager.cpp