GLESC: GLESC::GAPI::OpenGLDebugger Class Reference
GLESC::GAPI::OpenGLDebugger Class Reference
#include <OpenGLDebugger.h>
Static Public Member Functions
static void enableGlDebugCallback ()
Enables the OpenGL debug callback.
static void setSdlGlDebugContextAttribute ()
Sets the SDL_GL_CONTEXT_DEBUG_FLAG attribute.
Static Private Member Functions
static std::string errorStringFromSeverity (GLenum severity)
Returns a string representation of the OpenGL error severity.
static std::string errorStringFromSource (GLenum source)
Returns a string representation of the OpenGL error source.
static std::string errorStringFromType (GLenum type)
Returns a string representation of the OpenGL error type.
static void glDebugCallback (GLenum source, GLenum type, GLuint errorCode, GLenum severity, GLsizei length, const GLchar *message, const void *userParam)
The OpenGL debug callback.
Detailed Description
Definition at line 25 of file OpenGLDebugger.h.
Member Function Documentation
enableGlDebugCallback()
static void GLESC::GAPI::OpenGLDebugger::enableGlDebugCallback () inline static
Enables the OpenGL debug callback.
This callback is used to throw exceptions when an OpenGL error occurs
See also
https://www.khronos.org/opengl/wiki/Debug_Output
Definition at line 32 of file OpenGLDebugger.h.
{
            // Enable OpenGL debug callback
            glEnable(GL_DEBUG_OUTPUT);
            // This ensures that the callback function is called right after an error has occurred.
            glEnable(GL_DEBUG_OUTPUT_SYNCHRONOUS);
            // Set the callback function
            glDebugMessageCallback(glDebugCallback, nullptr);
            // Enable all OpenGL debug messages
            glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, 0, nullptr, GL_TRUE);
        }
References glDebugCallback(), and GLESC::isIterable_v.
errorStringFromSeverity()
std::string OpenGLDebugger::errorStringFromSeverity (GLenum severity) static private
Returns a string representation of the OpenGL error severity.
This function is used to convert the severity parameter of the OpenGL debug callback to a string
Parameters
severity
Returns
Definition at line 79 of file OpenGLDebugger.cpp.
{
    std::string severityString;
    severityString += "Severity: ";
    switch (severity) {
        case GL_DEBUG_SEVERITY_HIGH:
            return severityString + "High";
        case GL_DEBUG_SEVERITY_MEDIUM:
            return severityString + "Medium";
        case GL_DEBUG_SEVERITY_LOW:
            return severityString + "Low";
        case GL_DEBUG_SEVERITY_NOTIFICATION:
            return severityString + "Notification";
        default:
            return severityString + "Unknown";
    }
}
References GLESC::isIterable_v.
Referenced by glDebugCallback().
errorStringFromSource()
std::string OpenGLDebugger::errorStringFromSource (GLenum source) static private
Returns a string representation of the OpenGL error source.
This function is used to convert the source parameter of the OpenGL debug callback to a string
Parameters
source
Returns
Definition at line 26 of file OpenGLDebugger.cpp.
{
    std::string sourceString;
    sourceString += "Source: ";
    switch (source) {
        case GL_DEBUG_SOURCE_API:
            return sourceString + "API";
        case GL_DEBUG_SOURCE_WINDOW_SYSTEM:
            return sourceString + "Window System";
        case GL_DEBUG_SOURCE_SHADER_COMPILER:
            return sourceString + "Shader Compiler";
        case GL_DEBUG_SOURCE_THIRD_PARTY:
            return sourceString + "Third Party";
        case GL_DEBUG_SOURCE_APPLICATION:
            return sourceString + "Application";
        case GL_DEBUG_SOURCE_OTHER:
            return sourceString + "Other";
        default:
            return sourceString + "Unknown";
    }
}
References GLESC::isIterable_v.
Referenced by glDebugCallback().
errorStringFromType()
std::string OpenGLDebugger::errorStringFromType (GLenum type) static private
Returns a string representation of the OpenGL error type.
This function is used to convert the type parameter of the OpenGL debug callback to a string
Parameters
type
Returns
Definition at line 50 of file OpenGLDebugger.cpp.
{
    std::string typeString;
    typeString += "Type: ";
    switch (type) {
        case GL_DEBUG_TYPE_ERROR:
            return typeString + "Error";
        case GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR:
            return typeString + "Deprecated Behaviour";
        case GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR:
            return typeString + "Undefined Behaviour";
        case GL_DEBUG_TYPE_PORTABILITY:
            return typeString + "Portability";
        case GL_DEBUG_TYPE_PERFORMANCE:
            return typeString + "Performance";
        case GL_DEBUG_TYPE_MARKER:
            return typeString + "Marker";
        case GL_DEBUG_TYPE_PUSH_GROUP:
            return typeString + "push Group";
        case GL_DEBUG_TYPE_POP_GROUP:
            return typeString + "Pop Group";
        case GL_DEBUG_TYPE_OTHER:
            return typeString + "Other";
        default:
            return typeString + "Unknown";
    }
}
References GLESC::isIterable_v.
Referenced by glDebugCallback().
glDebugCallback()
void OpenGLDebugger::glDebugCallback (GLenum source, GLenum type, GLuint errorCode, GLenum severity, GLsizei length, const GLchar * message, const void * userParam) static private
The OpenGL debug callback.
This callback is used to throw exceptions when an OpenGL error occurs
Parameters
source
type
errorCode
severity
length
message
userParam
Definition at line 9 of file OpenGLDebugger.cpp.
{
    // ignore non-significant error/warning codes
    const std::set<GLuint> nonSignificantErrorCodes = {131169, 131185, 131218, 131204};
    if (nonSignificantErrorCodes.find(errorCode) != nonSignificantErrorCodes.end())
        return;
    D_ASSERT_GL_CALL_IS_CORRECT(false,
                              "Debug message (" +
                              std::to_string(errorCode) + "): \n Message:" + message +
                              "\n | " + errorStringFromSource(source) +
                              "\n | " + errorStringFromType(type) +
                              "\n | " + errorStringFromSeverity(severity));
}
References D_ASSERT_GL_CALL_IS_CORRECT, errorStringFromSeverity(), errorStringFromSource(), errorStringFromType(), and GLESC::isIterable_v.
Referenced by enableGlDebugCallback().
setSdlGlDebugContextAttribute()
static void GLESC::GAPI::OpenGLDebugger::setSdlGlDebugContextAttribute () inline static
Sets the SDL_GL_CONTEXT_DEBUG_FLAG attribute.
This attribute is used to enable OpenGL debug context, which is required for the OpenGL debug callback. This might reduce performance. It must be called before creating the OpenGL context.
See also
https://wiki.libsdl.org/SDL_GLattr#SDL_GLattr
Definition at line 50 of file OpenGLDebugger.h.
{
            // Enable OpenGL debug context
            SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, SDL_GL_CONTEXT_DEBUG_FLAG);
        }
References GLESC::isIterable_v.
The documentation for this class was generated from the following files:
OpenGLDebugger.h
OpenGLDebugger.cpp