GLESC: GLESC::ECS::ComponentManager Class Reference
GLESC::ECS::ComponentManager Class Reference
#include <ComponentManager.h>
Public Member Functions
ComponentManager ()=default
~ComponentManager ()=default
template<typename Component >
void addComponentToEntity (EntityID entity, const Component &component)
Add a component to an entity.
void entityDestroyed (EntityID entity)
Alert the component manager that an entity has been destroyed.
template<typename Component >
Component & getComponent (EntityID entity) const
Get the component of an entity by its Id.
IComponent & getComponent (EntityID entity, ComponentID componentID) const
Get the component of an entity by its ID.
const std::unordered_map< ComponentName, IComponentArrayPtr > & getComponentArrays () const
template<typename Component >
ComponentID getComponentID () const
Get the ID of a component by its type.
const std::unordered_map< ComponentName, ComponentID > & getComponentIDs () const
ComponentName getComponentName (ComponentID componentID) const
Get the name of a component by its ID.
const ComponentID & getNextComponentID () const
template<typename Component >
bool isComponentRegistered () const
Check if a component is registered.
bool isComponentRegistered (ComponentID componentID) const
Check if a component is registered.
template<typename Component >
void registerComponent ()
Register a component.
template<typename Component >
void registerComponentIfNotRegistered ()
Register a component if it is not already registered. If it is already registered, does nothing.
template<typename Component >
void removeComponent (EntityID entity)
Remove a component from an entity.
Static Public Attributes
static constexpr ComponentID firstComponentID = 0
The first component ID is zero, this is because signatures are just a bitset, and the first bit is the 'zeroth' bit, so std::bitset bitset[0] is the first bit.
Protected Member Functions
template<typename Component >
std::shared_ptr< ComponentArray< Component > > getComponentArray () const
Gets the component array of a component. The component must be registered and must be a component.
Protected Attributes
std::unordered_map< ComponentName, IComponentArrayPtr > componentArrays {}
Map from the name of a component to a component array that stores all the components of that type.
std::unordered_map< ComponentName, ComponentID > componentIDs {}
Map from the name of a component to the ID of that component.
std::unordered_map< ComponentID, ComponentName > componentNames {}
Map from the ID of a component to the name of that component.
ComponentID nextComponentID {firstComponentID}
ID of the next component to be registered. It is incremented after each component is registered.
Friends
class ECSCoordinator
Detailed Description
Definition at line 18 of file ComponentManager.h.
Constructor & Destructor Documentation
ComponentManager()
GLESC::ECS::ComponentManager::ComponentManager () default
~ComponentManager()
GLESC::ECS::ComponentManager::~ComponentManager () default
Member Function Documentation
addComponentToEntity()
template<typename Component > void GLESC::ECS::ComponentManager::addComponentToEntity (EntityID entity, const Component & component)
Add a component to an entity.
The component must be registered before adding it to an entity. Adding a component to an entity means adding a new component to the array of components of that type. And assigning the component to the entity inside the component array.
Template Parameters
Component The type of the component.
Parameters
entity The ID of the entity.
component The component to add.
Definition at line 210 of file ComponentManager.h.
{
        // No need for asserts or printing, they are already done in the functions called
        registerComponentIfNotRegistered<Component>();
        getComponentArray<Component>()->insertData(entity, component);
    }
References GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::addComponent().
entityDestroyed()
void ComponentManager::entityDestroyed (EntityID entity)
Alert the component manager that an entity has been destroyed.
This will alert all the component arrays that an entity has been destroyed amd they should remove the entity from their arrays with their assigned components.
Parameters
entity The ID of the entity.
Definition at line 5 of file ComponentManager.cpp.
{
    for (auto const &[name, array] : componentArrays) {
        array->entityDestroyed(entity);
    }
}
References componentArrays, and GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::destroyEntity().
getComponent() [1/2]
template<typename Component > Component & GLESC::ECS::ComponentManager::getComponent (EntityID entity) const
Get the component of an entity by its Id.
Template Parameters
Component The type of the component
Parameters
entity The ID of the entity
Returns
The component
Definition at line 167 of file ComponentManager.h.
{
        auto componentArray = getComponentArray<Component>();
        S_ASSERT_TRUE((std::is_base_of_v<IComponent, Component>), "Component must inherit from IComponent");
        D_ASSERT_TRUE(isComponentRegistered<Component>(), "Component is not registered");
        D_ASSERT_TRUE(componentArray->hasComponent(entity),
                      "Entity does not have component. Add component first. "
                      "Check if you tried to get the component before adding it.")
        ;
        return componentArray->getData(entity);
    }
References D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
getComponent() [2/2]
IComponent & ComponentManager::getComponent (EntityID entity, ComponentID componentID) const
Get the component of an entity by its ID.
Parameters
entity The ID of the entity.
componentID The ID of the component.
Returns
The component.
Definition at line 21 of file ComponentManager.cpp.
{
    ComponentName componentName = getComponentName(componentID);
    IComponentArrayPtr componentArray = componentArrays.at(componentName);
    IComponent& component = componentArray->getComponent(entity);
    return component;
}
References componentArrays, getComponentName(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::getComponent(), GLESC::ECS::ECSCoordinator::getComponents(), and GLESC::ECS::ECSCoordinator::printEntity().
getComponentArray()
template<typename Component > std::shared_ptr< ComponentArray< Component > > GLESC::ECS::ComponentManager::getComponentArray () const protected
Gets the component array of a component. The component must be registered and must be a component.
Template Parameters
Component The type of the component
Returns
A shared pointer to the component array of the component
Definition at line 235 of file ComponentManager.h.
{
        S_ASSERT_TRUE((std::is_base_of_v<IComponent, Component>), "Component must inherit from IComponent");
        D_ASSERT_TRUE(isComponentRegistered<Component>(), "Component is not registered");
        const char* typeName = typeid(Component).name();
        return std::static_pointer_cast<ComponentArray<Component>>(componentArrays.at(typeName));
    }
References componentArrays, D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
getComponentArrays()
const std::unordered_map< ComponentName, IComponentArrayPtr > & GLESC::ECS::ComponentManager::getComponentArrays () const inline
Definition at line 30 of file ComponentManager.h.
{
            return componentArrays;
        }
References componentArrays.
getComponentID()
template<typename Component > ComponentID GLESC::ECS::ComponentManager::getComponentID () const
Get the ID of a component by its type.
Template Parameters
Component The type of the component.
Returns
The ID of the component.
Definition at line 186 of file ComponentManager.h.
{
        S_ASSERT_TRUE((std::is_base_of_v<IComponent, Component>), "Component must inherit from IComponent");
        D_ASSERT_TRUE(isComponentRegistered<Component>(), "Component is not registered");
        const char* typeName = typeid(Component).name();
        return componentIDs.at(typeName);
    }
References componentIDs, D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::ECS::ECSCoordinator::addComponent(), GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem(), GLESC::ECS::ECSCoordinator::getComponentID(), GLESC::ECS::ECSCoordinator::hasComponent(), and GLESC::ECS::ECSCoordinator::removeComponent().
getComponentIDs()
const std::unordered_map< ComponentName, ComponentID > & GLESC::ECS::ComponentManager::getComponentIDs () const inline
Definition at line 34 of file ComponentManager.h.
{
            return componentIDs;
        }
References componentIDs.
Referenced by GLESC::ECS::ECSCoordinator::printEntity(), and GLESC::ECS::ECSCoordinator::printStatus().
getComponentName()
ComponentName ComponentManager::getComponentName (ComponentID componentID) const
Get the name of a component by its ID.
Parameters
componentID The ID of the component.
Returns
The name of the component.
Definition at line 15 of file ComponentManager.cpp.
{
    D_ASSERT_TRUE(isComponentRegistered(componentID), "Component must be registered to get its name");
    return componentNames.at(componentID);
}
References componentNames, D_ASSERT_TRUE, isComponentRegistered(), and GLESC::isIterable_v.
Referenced by getComponent().
getNextComponentID()
const ComponentID & GLESC::ECS::ComponentManager::getNextComponentID () const inline
Definition at line 38 of file ComponentManager.h.
{
            return nextComponentID;
        }
References nextComponentID.
isComponentRegistered() [1/2]
template<typename Component > bool GLESC::ECS::ComponentManager::isComponentRegistered () const
Check if a component is registered.
Template Parameters
Component The type of the component.
Returns
True if the component is registered, false otherwise.
Definition at line 179 of file ComponentManager.h.
{
        auto name = typeid(Component).name();
        return componentArrays.find(name) !=
            componentArrays.end();
    }
References componentArrays, and GLESC::isIterable_v.
Referenced by getComponentName(), and GLESC::ECS::ECSCoordinator::hasComponent().
isComponentRegistered() [2/2]
bool ComponentManager::isComponentRegistered (ComponentID componentID) const
Check if a component is registered.
Parameters
componentID The ID of the component.
Returns
True if the component is registered, false otherwise.
Definition at line 11 of file ComponentManager.cpp.
{
    return componentNames.find(componentID) != componentNames.end();
}
References componentNames, and GLESC::isIterable_v.
registerComponent()
template<typename Component > void GLESC::ECS::ComponentManager::registerComponent ()
Register a component.
When a component is registered, it is added to the component arrays and it is assigned an ID.
Template Parameters
Component The type of the component.
Definition at line 195 of file ComponentManager.h.
{
        S_ASSERT_TRUE((std::is_base_of_v<IComponent, Component>), "Component must inherit from IComponent");
        D_ASSERT_TRUE(!isComponentRegistered<Component>(), "Component is already registered");
        const char* typeName = typeid(Component).name();
        componentArrays.try_emplace(typeName,
                                    std::make_shared<ComponentArray<Component>>());
        componentIDs.insert({typeName, nextComponentID});
        componentNames.insert({nextComponentID, typeName});
        ++nextComponentID;
    }
References componentArrays, componentIDs, componentNames, D_ASSERT_TRUE, GLESC::isIterable_v, nextComponentID, and S_ASSERT_TRUE.
registerComponentIfNotRegistered()
template<typename Component > void GLESC::ECS::ComponentManager::registerComponentIfNotRegistered ()
Register a component if it is not already registered. If it is already registered, does nothing.
Template Parameters
Component The type of the component.
Definition at line 225 of file ComponentManager.h.
{
        // No need for asserts or printing,
        // they are already done in the functions called
        if (!isComponentRegistered<Component>()) {
            registerComponent<Component>();
        }
    }
References GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem().
removeComponent()
template<typename Component > void GLESC::ECS::ComponentManager::removeComponent (EntityID entity)
Remove a component from an entity.
Removing a component from an entity means removing the component from the array of components of that type and removing the component from the entity inside the component array.
Template Parameters
Component The type of the component.
Parameters
entity The ID of the entity.
Definition at line 217 of file ComponentManager.h.
{
        S_ASSERT_TRUE((std::is_base_of_v<IComponent, Component>), "Component must inherit from IComponent");
        D_ASSERT_TRUE(isComponentRegistered<Component>(), "Component is not registered");
        D_ASSERT_TRUE(getComponentArray<Component>()->hasComponent(entity), "Entity does not have component");
        getComponentArray<Component>()->removeData(entity);
    }
References D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::ECS::ECSCoordinator::removeComponent().
Friends And Related Symbol Documentation
ECSCoordinator
friend class ECSCoordinator friend
Definition at line 19 of file ComponentManager.h.
Member Data Documentation
componentArrays
std::unordered_map<ComponentName, IComponentArrayPtr> GLESC::ECS::ComponentManager::componentArrays {} protected
Map from the name of a component to a component array that stores all the components of that type.
Definition at line 141 of file ComponentManager.h.
{};
Referenced by entityDestroyed(), getComponent(), getComponentArray(), getComponentArrays(), isComponentRegistered(), and registerComponent().
componentIDs
std::unordered_map<ComponentName, ComponentID> GLESC::ECS::ComponentManager::componentIDs {} protected
Map from the name of a component to the ID of that component.
Definition at line 145 of file ComponentManager.h.
{};
Referenced by getComponentID(), getComponentIDs(), and registerComponent().
componentNames
std::unordered_map<ComponentID, ComponentName> GLESC::ECS::ComponentManager::componentNames {} protected
Map from the ID of a component to the name of that component.
Definition at line 149 of file ComponentManager.h.
{};
Referenced by getComponentName(), isComponentRegistered(), and registerComponent().
firstComponentID
constexpr ComponentID GLESC::ECS::ComponentManager::firstComponentID = 0 static constexpr
The first component ID is zero, this is because signatures are just a bitset, and the first bit is the 'zeroth' bit, so std::bitset bitset[0] is the first bit.
Definition at line 26 of file ComponentManager.h.
nextComponentID
ComponentID GLESC::ECS::ComponentManager::nextComponentID {firstComponentID} protected
ID of the next component to be registered. It is incremented after each component is registered.
It starts as 1, because it is needed for defining signatures and having it as as zero wouldn't allow for signature definition.
Definition at line 155 of file ComponentManager.h.
{firstComponentID};
Referenced by getNextComponentID(), and registerComponent().
The documentation for this class was generated from the following files:
ComponentManager.h
ComponentManager.cpp