GLESC: GLESC::ResMng::Texture::TextureSurface Class Reference
GLESC::ResMng::Texture::TextureSurface Class Reference
Class that represents a texture surface. This class will hold the data of the texture and will be used to load the data from the file. It stores all the pixels to be able to retreive and modify. Also can be released to free the memory, as textures are memory intensive.
#include <TextureSurface.h>
Public Member Functions
TextureSurface ()=default
Default constructor. This will not initialize the texture, therefore you will need to call load() to load the the data from the desired file.
TextureSurface (const std::string &pathParam, bool flipTexture)
Loader constructor. This constructor will initialize the texture with the data from the file.
~TextureSurface ()=default
const Format & getFormat () const
unsigned int getHeight () const
Pixel getPixel (unsigned int x, unsigned int y) const
const std::vector< UByte > & getPixels () const
Size getTotalOfPixels () const
unsigned int getWidth () const
void initializeData (SDL_Surface &sdlSurface)
void load (const std::string &pathParam, bool flipTexture)
Loads the texture from the file system.
void release ()
Releases the texture data.
std::string toString () const
Static Private Member Functions
static bool isDppCorrect (UInt bpp)
Private Attributes
Format format {}
bool hasLoaded = false
UInt height {0}
std::vector< UByte > pixels {}
UInt width {0}
Detailed Description
Class that represents a texture surface. This class will hold the data of the texture and will be used to load the data from the file. It stores all the pixels to be able to retreive and modify. Also can be released to free the memory, as textures are memory intensive.
Definition at line 24 of file TextureSurface.h.
Constructor & Destructor Documentation
TextureSurface() [1/2]
TextureSurface::TextureSurface (const std::string & pathParam, bool flipTexture)
Loader constructor. This constructor will initialize the texture with the data from the file.
Definition at line 16 of file TextureSurface.cpp.
{
    load(pathParam, flipTexture);
}
References GLESC::isIterable_v, and load().
TextureSurface() [2/2]
GLESC::ResMng::Texture::TextureSurface::TextureSurface () default
Default constructor. This will not initialize the texture, therefore you will need to call load() to load the the data from the desired file.
~TextureSurface()
GLESC::ResMng::Texture::TextureSurface::~TextureSurface () default
Member Function Documentation
getFormat()
const Format & GLESC::ResMng::Texture::TextureSurface::getFormat () const inline
Definition at line 57 of file TextureSurface.h.
{
            return format;
        }
References format.
Referenced by GLESC::Render::Texture::load().
getHeight()
unsigned int GLESC::ResMng::Texture::TextureSurface::getHeight () const inline
Definition at line 49 of file TextureSurface.h.
{
            return height;
        }
References height.
Referenced by GLESC::Render::Texture::load(), and toString().
getPixel()
Pixel TextureSurface::getPixel (unsigned int x, unsigned int y) const
Definition at line 65 of file TextureSurface.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Texture not loaded");
    D_ASSERT_LESS(x, width, "X coordinate out of bounds");
    D_ASSERT_LESS(y, height, "Y coordinate out of bounds");
    auto baseUBytePixelPtr = pixels.data();
    // Calculate the number of bytes per pixel
    // Divide by 8 because the bit depth is stored in bits and each byte has 8 bits
    auto byteDepth = static_cast<UInt>(format.bitDepth) / 8;
    // Move the pointer to the pixel we want to read
    // Multiply by byteDepth because the pixel data is stored as bytes
    baseUBytePixelPtr += (y * width + x) * byteDepth;
    Uint32 pixelValue = 0;
    for (UInt i = 0; i < byteDepth; ++i) {
        pixelValue |= static_cast<Uint32>(baseUBytePixelPtr[i]) << (8 * i);
    }
    // Extract the individual color components
    auto r = static_cast<Uint8>((pixelValue & format.rMask) >> format.rShift);
    auto g = static_cast<Uint8>((pixelValue & format.gMask) >> format.gShift);
    auto b = static_cast<Uint8>((pixelValue & format.bMask) >> format.bShift);
    Uint8 a = (format.aMask != 0)
                  ? static_cast<Uint8>((pixelValue & format.aMask) >> format.aShift)
                  : 255;
    // Normalize if needed (i.e. if the bit depth is less than 8)
    r = (format.rLoss != 0) ? r * 255 / ((1 << format.rLoss) - 1) : r;
    g = (format.gLoss != 0) ? g * 255 / ((1 << format.gLoss) - 1) : g;
    b = (format.bLoss != 0) ? b * 255 / ((1 << format.bLoss) - 1) : b;
    // Alpha normalization is typically not needed if alpha is either 0 or 255
    return Pixel{r, g, b, a};
}
References Format::aMask, Format::aShift, Format::bitDepth, Format::bLoss, Format::bMask, Format::bShift, D_ASSERT_LESS, D_ASSERT_TRUE, format, Format::gLoss, Format::gMask, Format::gShift, hasLoaded, height, GLESC::isIterable_v, pixels, Format::rLoss, Format::rMask, Format::rShift, and width.
Referenced by toString().
getPixels()
const std::vector< UByte > & GLESC::ResMng::Texture::TextureSurface::getPixels () const inline
Definition at line 61 of file TextureSurface.h.
{
            return pixels;
        }
References pixels.
Referenced by GLESC::Render::Texture::load().
getTotalOfPixels()
Size GLESC::ResMng::Texture::TextureSurface::getTotalOfPixels () const inline
Definition at line 65 of file TextureSurface.h.
{ return width * height; }
References height, and width.
Referenced by toString().
getWidth()
unsigned int GLESC::ResMng::Texture::TextureSurface::getWidth () const inline
Definition at line 53 of file TextureSurface.h.
{
            return width;
        }
References width.
Referenced by GLESC::Render::Texture::load(), and toString().
initializeData()
void TextureSurface::initializeData (SDL_Surface & sdlSurface)
Definition at line 20 of file TextureSurface.cpp.
{
    // TODO: Is all this copying really necessary? Maybe use the SDL_Surface directly?
    //    But having our own format is useful
    format = Format();
    format.rMask = sdlSurface.format->Rmask;
    format.gMask = sdlSurface.format->Gmask;
    format.bMask = sdlSurface.format->Bmask;
    format.aMask = sdlSurface.format->Amask;
    format.rLoss = sdlSurface.format->Rloss;
    format.gLoss = sdlSurface.format->Gloss;
    format.bLoss = sdlSurface.format->Bloss;
    format.aLoss = sdlSurface.format->Aloss;
    format.rShift = sdlSurface.format->Rshift;
    format.gShift = sdlSurface.format->Gshift;
    format.bShift = sdlSurface.format->Bshift;
    format.aShift = sdlSurface.format->Ashift;
    // Assert that the bits per pixel is as expected
    D_ASSERT_TRUE(isDppCorrect(sdlSurface.format->BitsPerPixel), "Bits per pixel is not correct");
    if (format.aMask)
        format.colorFormat = ColorFormat::RGBA;
    else
        format.colorFormat = ColorFormat::RGB;
    // Set format's bit depth
    format.bitDepth = static_cast<BitDepth>(sdlSurface.format->BitsPerPixel);
    // Set texture dimensions
    width = static_cast<UInt>(sdlSurface.w);
    height = static_cast<UInt>(sdlSurface.h);
    // Calculate the total number of bytes for all pixels
    size_t totalBytes = width * height * static_cast<size_t>(sdlSurface.format->BytesPerPixel);
    // Resize the pixel vector to accommodate all bytes
    pixels.resize(totalBytes);
    // Copy the pixel data using memcpy for efficiency
    std::memcpy(pixels.data(), sdlSurface.pixels, totalBytes);
}
References Format::aLoss, Format::aMask, Format::aShift, Format::bitDepth, Format::bLoss, Format::bMask, Format::bShift, Format::colorFormat, D_ASSERT_TRUE, format, Format::gLoss, Format::gMask, Format::gShift, height, isDppCorrect(), GLESC::isIterable_v, pixels, GLESC::ResMng::Texture::RGB, GLESC::ResMng::Texture::RGBA, Format::rLoss, Format::rMask, Format::rShift, and width.
Referenced by load().
isDppCorrect()
static bool GLESC::ResMng::Texture::TextureSurface::isDppCorrect (UInt bpp) inline static private
Definition at line 75 of file TextureSurface.h.
{
            return bpp == 8 || bpp == 16 || bpp == 24 || bpp == 32;
        }
References GLESC::isIterable_v.
Referenced by initializeData().
load()
void TextureSurface::load (const std::string & pathParam, bool flipTexture)
Loads the texture from the file system.
Parameters
pathParam The path to the file
flipTexture If the texture should be flipped
Definition at line 102 of file TextureSurface.cpp.
{
    D_ASSERT_FALSE(pathParam.empty(), "File path is empty.");
    SDL_SurfacePtr sdlSurface = TextureLoader::loadTexture(
        ASSETS_PATH + std::string("/") + pathParam, flipTexture);
    initializeData(*sdlSurface);
    // Texture is now loaded, must be set to true right after the texture is loaded
    // the above functions will throw an error if the texture is not loaded
    hasLoaded = true;
}
References D_ASSERT_FALSE, hasLoaded, initializeData(), GLESC::isIterable_v, and GLESC::TextureLoader::loadTexture().
Referenced by TextureSurface(), and GLESC::Render::Texture::load().
release()
void TextureSurface::release ()
Releases the texture data.
Definition at line 112 of file TextureSurface.cpp.
{
    pixels.clear();
    hasLoaded = false;
}
References hasLoaded, and pixels.
Referenced by GLESC::Render::Texture::release().
toString()
std::string TextureSurface::toString () const
Definition at line 119 of file TextureSurface.cpp.
{
    D_ASSERT_TRUE(hasLoaded, "Texture not loaded");
    std::stringstream ss;
    ss << "Texture:\n";
    ss << "\tWidth: " << width << "\n";
    ss << "\tHeight: " << height << "\n";
    ss << "\tTotal of pixels: " << getTotalOfPixels() << "\n";
    ss << "\tFormat:\n" << format.toString() << "\n";
    unsigned int pixelCount = 20;
    pixelCount = Math::sqrt(pixelCount);
    unsigned int widthStep = std::max(1u, getWidth() / pixelCount);
    unsigned int heightStep = std::max(1u, getHeight() / pixelCount);
    Logger::get().info("\tPixels:");
    for (UInt y = 0; y < getHeight() - 1; y += heightStep) {
        for (UInt x = 0; x < getWidth() - 1; x += widthStep) {
            auto pixel = getPixel(x, y);
            Logger::get().info("\t\tPixel at (" + std::to_string(x) + ", " + std::to_string(y) +
                "): " + pixel.toString());
        }
    }
    return ss.str();
}
References D_ASSERT_TRUE, format, GLESC::Logger::get(), getHeight(), getPixel(), getTotalOfPixels(), getWidth(), hasLoaded, height, GLESC::Logger::info(), GLESC::isIterable_v, GLESC::Math::sqrt(), Format::toString(), and width.
Member Data Documentation
format
Format GLESC::ResMng::Texture::TextureSurface::format {} private
Definition at line 82 of file TextureSurface.h.
{};
Referenced by getFormat(), getPixel(), initializeData(), and toString().
hasLoaded
bool GLESC::ResMng::Texture::TextureSurface::hasLoaded = false private
Definition at line 83 of file TextureSurface.h.
Referenced by getPixel(), load(), release(), and toString().
height
UInt GLESC::ResMng::Texture::TextureSurface::height {0} private
Definition at line 80 of file TextureSurface.h.
{0};
Referenced by getHeight(), getPixel(), getTotalOfPixels(), initializeData(), and toString().
pixels
std::vector<UByte> GLESC::ResMng::Texture::TextureSurface::pixels {} private
Definition at line 81 of file TextureSurface.h.
{};
Referenced by getPixel(), getPixels(), initializeData(), and release().
width
UInt GLESC::ResMng::Texture::TextureSurface::width {0} private
Definition at line 79 of file TextureSurface.h.
{0};
Referenced by getPixel(), getTotalOfPixels(), getWidth(), initializeData(), and toString().
The documentation for this class was generated from the following files:
TextureSurface.h
TextureSurface.cpp