GLESC: GLESC::Physics::Physics Class Reference
GLESC::Physics::Physics Class Reference
#include <Physics.h>
Public Member Functions
Physics ()=default
void addAcceleration (const Acceleration &acceleration)
void addAirFriction (Friction airFriction)
void addAngularAcceleration (const AngularAcceleration &angAccelParam)
void addAngularVelocity (const AngularVelocity &angularVelocity)
void addDirectionalAcceleration (const Math::Direction &dir, float speed)
void addDirectionalForce (const Math::Direction &dir, float forceParam)
void addDirectionalVelocity (const Math::Direction &direction, float speed)
void addForce (const Force &force)
void addFriciton (float friction)
void addMass (const Mass &mass)
void addVelocity (const Velocity &velocity)
Acceleration getAcceleration () const
Friction getAirFriction () const
AngularAcceleration getAngularAcceleration () const
AngularForce getAngularForce () const
AngularVelocity getAngularVelocity () const
std::vector< EntityStatsManager::Value > getDebuggingValues () override
Get the debugging values of the component.
Force getForce () const
Friction getFriction () const
Mass getMass () const
Velocity getVelocity () const
void giveAngularForce (const AngularForce &angularForce)
bool isAffectedByGravity () const
bool isStatic () const
void setAcceleration (const Acceleration &acceleration)
void setAffectedByGravity (bool affectedByGravity)
void setAirFriction (Friction airFriction)
void setAngularAcceleration (const AngularAcceleration &angAccelParam)
void setAngularVelocity (const AngularVelocity &angularVelocity)
void setDirectionalAcceleration (const Math::Direction &dir, float speed)
void setDirectionalForce (const Math::Direction &dir, float forceParam)
void setDirectionalVelocity (const Math::Direction &direction, float speed)
void setForce (const Force &force)
void setFriction (float friction)
void setMass (const Mass &mass)
void setMass (Mass &mass)
void setStatic (bool isStatic)
void setVelocity (const Velocity &velocity)
std::string toString () const override
Public Member Functions inherited from EngineComponent
virtual ~EngineComponent ()=default
const char * getOwnerName () const
Get the owner name of the component for debugging purposes.
virtual std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues ()
Get the updated debugging values of the component.
void setOwnerName (const char *ownerName)
Set the owner name of the component for debugging purposes.
Private Attributes
Acceleration acceleration {0, 0, 0}
bool affectedByGravity {true}
Friction airFriction {-1.f}
AngularAcceleration angAccel {0, 0, 0}
AngularForce angularForce {0, 0, 0}
AngularVelocity angularVelocity {0, 0, 0}
Force force {0, 0, 0}
Friction friction {0.01f}
Mass mass {1.0F}
bool staticObj {false}
Velocity velocity {0, 0, 0}
Detailed Description
Definition at line 17 of file Physics.h.
Constructor & Destructor Documentation
Physics()
GLESC::Physics::Physics::Physics () default
Member Function Documentation
addAcceleration()
void GLESC::Physics::Physics::addAcceleration (const Acceleration & acceleration) inline
Definition at line 41 of file Physics.h.
{ this->acceleration += acceleration; }
References acceleration.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
addAirFriction()
void GLESC::Physics::Physics::addAirFriction (Friction airFriction) inline
Definition at line 29 of file Physics.h.
{ this->airFriction += airFriction; }
References airFriction.
addAngularAcceleration()
void GLESC::Physics::Physics::addAngularAcceleration (const AngularAcceleration & angAccelParam) inline
Definition at line 46 of file Physics.h.
{ this->angAccel += angAccelParam; }
References angAccel, and GLESC::isIterable_v.
addAngularVelocity()
void GLESC::Physics::Physics::addAngularVelocity (const AngularVelocity & angularVelocity) inline
Definition at line 39 of file Physics.h.
{ this->angularVelocity += angularVelocity; }
References angularVelocity.
addDirectionalAcceleration()
void GLESC::Physics::Physics::addDirectionalAcceleration (const Math::Direction & dir, float speed) inline
Definition at line 43 of file Physics.h.
{ acceleration += dir * speed; }
References acceleration, and GLESC::isIterable_v.
addDirectionalForce()
void GLESC::Physics::Physics::addDirectionalForce (const Math::Direction & dir, float forceParam) inline
Definition at line 51 of file Physics.h.
{ force += dir * forceParam; }
References force, and GLESC::isIterable_v.
addDirectionalVelocity()
void GLESC::Physics::Physics::addDirectionalVelocity (const Math::Direction & direction, float speed) inline
Definition at line 37 of file Physics.h.
{ velocity += direction * speed; }
References GLESC::isIterable_v, and velocity.
addForce()
void GLESC::Physics::Physics::addForce (const Force & force) inline
Definition at line 49 of file Physics.h.
{ this->force += force; }
References force.
addFriciton()
void GLESC::Physics::Physics::addFriciton (float friction) inline
Definition at line 31 of file Physics.h.
{ this->friction += friction; }
References friction.
addMass()
void GLESC::Physics::Physics::addMass (const Mass & mass) inline
Definition at line 26 of file Physics.h.
{ this->mass += mass; }
References mass.
addVelocity()
void GLESC::Physics::Physics::addVelocity (const Velocity & velocity) inline
Definition at line 34 of file Physics.h.
{ this->velocity += velocity; }
References velocity.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
getAcceleration()
Acceleration GLESC::Physics::Physics::getAcceleration () const inline
Definition at line 63 of file Physics.h.
{ return acceleration; }
References acceleration.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
getAirFriction()
Friction GLESC::Physics::Physics::getAirFriction () const inline
Definition at line 60 of file Physics.h.
{ return airFriction; }
References airFriction.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
getAngularAcceleration()
AngularAcceleration GLESC::Physics::Physics::getAngularAcceleration () const inline
Definition at line 70 of file Physics.h.
{ return angAccel; }
References angAccel.
getAngularForce()
AngularForce GLESC::Physics::Physics::getAngularForce () const inline
Definition at line 69 of file Physics.h.
{ return angularForce; }
References angularForce.
getAngularVelocity()
AngularVelocity GLESC::Physics::Physics::getAngularVelocity () const inline
Definition at line 71 of file Physics.h.
{ return angularVelocity; }
References angularVelocity.
getDebuggingValues()
std::vector< EntityStatsManager::Value > Physics::getDebuggingValues () override virtual
Get the debugging values of the component.
This function can be overriden by the derived class to return the debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented from EngineComponent.
Definition at line 23 of file Physics.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value massValue;
    massValue.name = "Mass";
    massValue.data = reinterpret_cast<void*>(&mass);
    massValue.type = EntityStatsManager::ValueType::FLOAT;
    massValue.isModifiable = true;
    massValue.usesSlider = true;
    massValue.min = 0.0F;
    massValue.max = 10000.0F;
    values.push_back(massValue);
    EntityStatsManager::Value velocityValue;
    velocityValue.name = "Velocity";
    velocityValue.data = reinterpret_cast<void*>(&velocity);
    velocityValue.type = EntityStatsManager::ValueType::VEC3F;
    velocityValue.isModifiable = true;
    velocityValue.usesSlider = true;
    velocityValue.min = -1000.0F;
    velocityValue.max = 1000.0F;
    values.push_back(velocityValue);
    EntityStatsManager::Value forceValue;
    forceValue.name = "Force";
    forceValue.data = reinterpret_cast<void*>(&force);
    forceValue.type = EntityStatsManager::ValueType::VEC3F;
    forceValue.isModifiable = true;
    forceValue.usesSlider = true;
    forceValue.min = -1000.0F;
    forceValue.max = 1000.0F;
    values.push_back(forceValue);
    EntityStatsManager::Value accelerationValue;
    accelerationValue.name = "Acceleration";
    accelerationValue.data = reinterpret_cast<void*>(&acceleration);
    accelerationValue.type = EntityStatsManager::ValueType::VEC3F;
    accelerationValue.isModifiable = true;
    accelerationValue.usesSlider = true;
    accelerationValue.min = -1000.0F;
    accelerationValue.max = 1000.0F;
    values.push_back(accelerationValue);
    EntityStatsManager::Value affectedByGravity;
    affectedByGravity.name = "Affected by gravity";
    affectedByGravity.data = reinterpret_cast<void*>(&this->affectedByGravity);
    affectedByGravity.type = EntityStatsManager::ValueType::BOOL;
    affectedByGravity.isModifiable = true;
    values.push_back(affectedByGravity);
    EntityStatsManager::Value frictionValue;
    frictionValue.name = "Friction";
    frictionValue.data = reinterpret_cast<void*>(&friction);
    frictionValue.type = EntityStatsManager::ValueType::FLOAT;
    frictionValue.isModifiable = true;
    frictionValue.usesSlider = true;
    frictionValue.min = 0.0F;
    frictionValue.max = 1.0F;
    values.push_back(frictionValue);
    return values;
}
References acceleration, affectedByGravity, EntityStatsManager::BOOL, EntityStatsManager::FLOAT, force, friction, GLESC::isIterable_v, mass, EntityStatsManager::Value::name, EntityStatsManager::Value::type, EntityStatsManager::VEC3F, and velocity.
Referenced by GLESC::ECS::PhysicsComponent::setDebuggingValues().
getForce()
Force GLESC::Physics::Physics::getForce () const inline
Definition at line 62 of file Physics.h.
{ return force; }
References force.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
getFriction()
Friction GLESC::Physics::Physics::getFriction () const inline
Definition at line 59 of file Physics.h.
{ return friction; }
References friction.
Referenced by GLESC::Physics::getVelocityWithFriction().
getMass()
Mass GLESC::Physics::Physics::getMass () const inline
Definition at line 58 of file Physics.h.
{ return mass; }
References mass.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
getVelocity()
Velocity GLESC::Physics::Physics::getVelocity () const inline
Definition at line 61 of file Physics.h.
{ return velocity; }
References velocity.
Referenced by GLESC::Physics::PhysicsManager::applyForces(), GLESC::Physics::getVelocityWithFriction(), GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::Physics::isFrictionApplied(), and GLESC::Physics::PhysicsManager::updateTransform().
giveAngularForce()
void GLESC::Physics::Physics::giveAngularForce (const AngularForce & angularForce) inline
Definition at line 52 of file Physics.h.
{ this->angularForce = angularForce; }
References angularForce.
isAffectedByGravity()
bool GLESC::Physics::Physics::isAffectedByGravity () const inline
Definition at line 66 of file Physics.h.
{ return affectedByGravity; }
References affectedByGravity.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
isStatic()
bool GLESC::Physics::Physics::isStatic () const inline
Definition at line 67 of file Physics.h.
{ return staticObj; }
References staticObj.
Referenced by GLESC::Physics::PhysicsManager::applyForces(), GLESC::Physics::PhysicsManager::handleCollisions(), and setStatic().
setAcceleration()
void GLESC::Physics::Physics::setAcceleration (const Acceleration & acceleration) inline
Definition at line 42 of file Physics.h.
{ this->acceleration = acceleration; }
References acceleration.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
setAffectedByGravity()
void GLESC::Physics::Physics::setAffectedByGravity (bool affectedByGravity) inline
Definition at line 54 of file Physics.h.
{ this->affectedByGravity = affectedByGravity; }
References affectedByGravity.
setAirFriction()
void GLESC::Physics::Physics::setAirFriction (Friction airFriction) inline
Definition at line 28 of file Physics.h.
{ this->airFriction = airFriction; }
References airFriction.
setAngularAcceleration()
void GLESC::Physics::Physics::setAngularAcceleration (const AngularAcceleration & angAccelParam) inline
Definition at line 45 of file Physics.h.
{ this->angAccel = angAccelParam; }
References angAccel, and GLESC::isIterable_v.
setAngularVelocity()
void GLESC::Physics::Physics::setAngularVelocity (const AngularVelocity & angularVelocity) inline
Definition at line 38 of file Physics.h.
{ this->angularVelocity = angularVelocity; }
References angularVelocity.
setDirectionalAcceleration()
void GLESC::Physics::Physics::setDirectionalAcceleration (const Math::Direction & dir, float speed) inline
Definition at line 44 of file Physics.h.
{ acceleration = dir * speed; }
References acceleration, and GLESC::isIterable_v.
setDirectionalForce()
void GLESC::Physics::Physics::setDirectionalForce (const Math::Direction & dir, float forceParam) inline
Definition at line 50 of file Physics.h.
{ force = dir * forceParam; }
References force, and GLESC::isIterable_v.
setDirectionalVelocity()
void GLESC::Physics::Physics::setDirectionalVelocity (const Math::Direction & direction, float speed) inline
Definition at line 36 of file Physics.h.
{ velocity = direction * speed; }
References GLESC::isIterable_v, and velocity.
setForce()
void GLESC::Physics::Physics::setForce (const Force & force) inline
Definition at line 48 of file Physics.h.
{ this->force = force; }
References force.
Referenced by GLESC::Physics::PhysicsManager::applyForces().
setFriction()
void GLESC::Physics::Physics::setFriction (float friction) inline
Definition at line 30 of file Physics.h.
{ this->friction = friction; }
References friction.
setMass() [1/2]
void GLESC::Physics::Physics::setMass (const Mass & mass) inline
Definition at line 21 of file Physics.h.
{
            D_ASSERT_TRUE(mass > 0.0F, "Mass must be greater than 0");
            this->mass = mass;
        }
References D_ASSERT_TRUE, and mass.
setMass() [2/2]
void GLESC::Physics::Physics::setMass (Mass & mass) inline
Definition at line 27 of file Physics.h.
{ this->mass = mass; }
References mass.
setStatic()
void GLESC::Physics::Physics::setStatic (bool isStatic) inline
Definition at line 55 of file Physics.h.
{ this->staticObj = isStatic; }
References isStatic(), and staticObj.
setVelocity()
void GLESC::Physics::Physics::setVelocity (const Velocity & velocity) inline
Definition at line 35 of file Physics.h.
{ this->velocity = velocity; }
References velocity.
Referenced by GLESC::Physics::PhysicsManager::applyForces(), and GLESC::Physics::PhysicsManager::handleCollisions().
toString()
std::string Physics::toString () const override virtual
Implements EngineComponent.
Definition at line 14 of file Physics.cpp.
{
    return "Physics: " +
        std::to_string(mass) + " " +
        velocity.toString() + " " +
        acceleration.toString() + " " +
        force.toString() + " " +
        std::to_string(affectedByGravity);
}
References acceleration, affectedByGravity, force, mass, GLESC::Math::Vector< Type, N >::toString(), and velocity.
Referenced by GLESC::ECS::PhysicsComponent::toString().
Member Data Documentation
acceleration
Acceleration GLESC::Physics::Physics::acceleration {0, 0, 0} private
Definition at line 86 of file Physics.h.
{0, 0, 0};
Referenced by addAcceleration(), addDirectionalAcceleration(), getAcceleration(), getDebuggingValues(), setAcceleration(), setDirectionalAcceleration(), and toString().
affectedByGravity
bool GLESC::Physics::Physics::affectedByGravity {true} private
Definition at line 94 of file Physics.h.
{true};
Referenced by getDebuggingValues(), isAffectedByGravity(), setAffectedByGravity(), and toString().
airFriction
Friction GLESC::Physics::Physics::airFriction {-1.f} private
While its negative, it will be the default value for air friction defined in the physics manager
Definition at line 84 of file Physics.h.
{-1.f};
Referenced by addAirFriction(), getAirFriction(), and setAirFriction().
angAccel
AngularAcceleration GLESC::Physics::Physics::angAccel {0, 0, 0} private
Definition at line 90 of file Physics.h.
{0, 0, 0};
Referenced by addAngularAcceleration(), getAngularAcceleration(), and setAngularAcceleration().
angularForce
AngularForce GLESC::Physics::Physics::angularForce {0, 0, 0} private
Definition at line 89 of file Physics.h.
{0, 0, 0};
Referenced by getAngularForce(), and giveAngularForce().
angularVelocity
AngularVelocity GLESC::Physics::Physics::angularVelocity {0, 0, 0} private
Definition at line 91 of file Physics.h.
{0, 0, 0};
Referenced by addAngularVelocity(), getAngularVelocity(), and setAngularVelocity().
force
Force GLESC::Physics::Physics::force {0, 0, 0} private
Definition at line 87 of file Physics.h.
{0, 0, 0};
Referenced by addDirectionalForce(), addForce(), getDebuggingValues(), getForce(), setDirectionalForce(), setForce(), and toString().
friction
Friction GLESC::Physics::Physics::friction {0.01f} private
Definition at line 80 of file Physics.h.
{0.01f};
Referenced by addFriciton(), getDebuggingValues(), getFriction(), and setFriction().
mass
Mass GLESC::Physics::Physics::mass {1.0F} private
Definition at line 79 of file Physics.h.
{1.0F};
Referenced by addMass(), getDebuggingValues(), getMass(), setMass(), setMass(), and toString().
staticObj
bool GLESC::Physics::Physics::staticObj {false} private
Definition at line 93 of file Physics.h.
{false};
Referenced by isStatic(), and setStatic().
velocity
Velocity GLESC::Physics::Physics::velocity {0, 0, 0} private
Definition at line 85 of file Physics.h.
{0, 0, 0};
Referenced by addDirectionalVelocity(), addVelocity(), getDebuggingValues(), getVelocity(), setDirectionalVelocity(), setVelocity(), and toString().
The documentation for this class was generated from the following files:
Physics.h
Physics.cpp