GLESC: GLESC::Math::MatrixAlgorithms Class Reference
GLESC::Math::MatrixAlgorithms Class Reference
#include <MatrixAlgorithms.h>
Classes
struct GaussianEliminationData
Struct that holds the result of Gaussian elimination with tracking.
struct GaussianEliminationTrackedResult
Struct that holds the result of Gaussian elimination with tracking.
Static Public Member Functions
template<typename ModelType , typename NormalMatType >
static void calculateNormalMatrix (const MatrixData< ModelType, 4, 4 > &MVMat, MatrixData< NormalMatType, 3, 3 > &normalMat)
Calculates the normal matrix given the model-view matrix.
template<typename Type >
static void calculateProjectionMatrix (float fovDegrees, float nearPlane, float farPlane, float viewWidth, float viewHeight, MatrixData< Type, 4, 4 > &projection)
Calculates the perspective projection matrix.
template<typename Type1 , typename Type2 , size_t N, size_t M>
static void copyMatrix (MatrixData< Type1, N, M > &matrixObjective, const MatrixData< Type2, N, M > &matrixToCopy)
Copies the data from one matrix to another.
template<typename Type >
static void determinant2x2 (const MatrixData< Type, 2, 2 > &matrix, Type &result)
Calculates the determinant of a 2x2 matrix.
template<typename Type >
static void determinant3x3 (const MatrixData< Type, 3, 3 > &matrix, Type &result)
Computes the determinant of a matrix 3x3.
template<typename Type >
static void determinant4x4 (const MatrixData< Type, 4, 4 > &matrix, Type &result)
Computes the determinant of a matrix 4x4.
template<typename Type , size_t N, size_t M>
static void fillMatrix (MatrixData< Type, N, M > &matrixObjective, const Type &value)
Sets the values of a matrix to one.
template<typename Type , size_t N, size_t M>
static GaussianEliminationData< Type, N, M > gaussianElimination (const MatrixData< Type, N, M > &matrix)
Performs Gaussian elimination on a matrix. @TODO: Make this work (doesn't work for some reason)
template<typename Type1 , typename Type2 , size_t N>
static void getScaleMatrix (const VectorData< Type2, N - 1 > &scale, MatrixData< Type1, N, N > &result)
Gets the scale matrix.
template<typename TypeMat , typename TypePos >
static void getTranslationMatrix (const VectorData< TypePos, 3 > &translation, MatrixData< TypeMat, 4, 4 > &result)
Applies the translation to a model matrix.
template<typename Type , size_t N>
static void inverse2x2 (const MatrixData< Type, N, N > &matrix, MatrixData< Type, N, N > &result)
Calculates the inverse of a 2x2 matrix.
template<typename Type , size_t N>
static void inverse3x3 (const MatrixData< Type, N, N > &matrix, MatrixData< Type, N, N > &result)
Calculates the inverse of a 3x3 matrix.
template<typename Type , size_t N>
static void inverse4x4 (const MatrixData< Type, N, N > &matrix, MatrixData< Type, N, N > &result)
Calculates the inverse of a 4x4 matrix.
template<typename Type , size_t N>
static bool isInvertible (const MatrixData< Type, N, N > &matrix)
Checks if a matrix is invertible.
template<typename Type >
static bool isValidViewMatrix (const MatrixData< Type, 4, 4 > &viewMatrix)
Checks if a matrix is a valid view matrix.
template<class Type , size_t N>
static Type laplaceExpansionDeterminant (const MatrixData< Type, N, N > &matrix)
Calculates the determinant of any matrix using Laplace expansion.
template<typename Type , size_t N, size_t M>
static void matrixAdd (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, N, M > &matrix2, MatrixData< Type, N, M > &result)
Adds two matrices, element-wise.
template<typename Type , size_t N, size_t M>
static void matrixHadamardDiv (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, N, M > &matrix2, MatrixData< Type, N, M > &result)
Divides two matrices. Hadamard division.
template<typename Type , size_t N, size_t M>
static void matrixHadamardMul (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, N, M > &matrix2, MatrixData< Type, N, M > &result)
Multiplies two matrices, element-wise.
template<typename Type , size_t N, typename = std::enable_if_t<N == 2 || N == 3 || N == 4>>
static void matrixInverse (const MatrixData< Type, N, N > &matrix, MatrixData< Type, N, N > &result)
Calculates the inverse of any square matrix.
template<typename Type , size_t N, size_t M, size_t X>
static void matrixMatrixDiv (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, M, X > &matrix2, MatrixData< Type, N, X > &result)
Matrix division.
template<typename Type , size_t N, size_t M, size_t X>
static void matrixMatrixMulColMaj (const MatrixData< Type, M, N > &matrix1, const MatrixData< Type, X, M > &matrix2, MatrixData< Type, X, N > &result)
template<typename Type , size_t N, size_t M, size_t N2, size_t M2, size_t N3, size_t M3>
static void matrixMatrixMulInPlace (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, N2, M2 > &matrix2, MatrixData< Type, N3, M3 > &result)
Dot product matrix multiplication in place.
template<typename Type , size_t N, size_t M, size_t X>
static void matrixMatrixMulNaiveColMaj (const MatrixData< Type, M, N > &matrix1, const MatrixData< Type, X, M > &matrix2, MatrixData< Type, X, N > &result)
template<typename Type , size_t N, size_t M>
static void matrixMatrixMulNaiveInPlace (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, M, M > &matrix2, MatrixData< Type, N, M > &result)
Dot product matrix multiplication in place.
template<typename Type , size_t N, size_t M, size_t X>
static void matrixMatrixMulNaiveRowMaj (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, M, X > &matrix2, MatrixData< Type, N, X > &result)
template<typename Type , size_t N, size_t M, size_t X>
static void matrixMatrixMulRowMaj (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, M, X > &matrix2, MatrixData< Type, N, X > &result)
template<typename Type , size_t N, size_t M>
static void matrixNegate (const MatrixData< Type, N, M > &matrix, MatrixData< Type, N, M > &result)
Negates a matrix.
template<typename Type , size_t N, size_t M>
static void matrixScalarAdd (const MatrixData< Type, N, M > &matrix, const Type &scalar, MatrixData< Type, N, M > &result)
Adds a scalar to a matrix.
template<typename Type , size_t N, size_t M>
static void matrixScalarDiv (const MatrixData< Type, N, M > &matrix, const Type &scalar, MatrixData< Type, N, M > &result)
Divides a matrix by a scalar.
template<typename Type , size_t N, size_t M>
static void matrixScalarMul (const MatrixData< Type, N, M > &matrix, const Type &scalar, MatrixData< Type, N, M > &result)
Multiplies a matrix by a scalar, element-wise.
template<typename Type , size_t N, size_t M>
static void matrixScalarSub (const MatrixData< Type, N, M > &matrix, const Type &scalar, MatrixData< Type, N, M > &result)
Subtracts a scalar from a matrix, element-wise.
template<typename Type , size_t N, size_t M>
static void matrixSub (const MatrixData< Type, N, M > &matrix1, const MatrixData< Type, N, M > &matrix2, MatrixData< Type, N, M > &result)
Subtracts two matrices, element-wise.
template<typename Type , size_t N, size_t M>
static void matrixVectorMulColMaj (const MatrixData< Type, M, N > &matrix, const VectorData< Type, M > &vector, VectorData< Type, N > &result)
template<typename Type , size_t N, size_t M>
static void matrixVectorMulRowMaj (const VectorData< Type, M > &vector, const MatrixData< Type, N, M > &matrix, VectorData< Type, N > &result)
template<typename Type , size_t N, size_t M>
static void moveMatrix (MatrixData< Type, N, M > &matrixObjective, MatrixData< Type, N, M > &&matrixToMove)
Moves the data from one matrix to another. @deatails This function moves the data from the source matrix to the destination matrix. If the source and destination matrices are the same, the function does nothing.
template<typename Type >
static void perspective (float fovRad, float nearPlane, float farPlane, float viewWidth, float viewHeight, MatrixData< Type, 4, 4 > &result)
Calculates the perspective projection matrix.
template<typename Type1 , size_t N1, size_t M1, typename Type2 , size_t N2, size_t M2>
static void resizeMatrix (const MatrixData< Type1, N1, M1 > &matrix, MatrixData< Type2, N2, M2 > &result)
Resizes a matrix.
template<typename Type , size_t N, size_t M>
static void setMatrix (MatrixData< Type, N, M > &matrixObjective, const Type(&&values)[N][M])
Sets the values of a matrix using a rvalue raw array.
template<typename Type , size_t N, size_t M>
static void setMatrix (MatrixData< Type, N, M > &matrixObjective, const Type(&values)[N][M])
Sets the values of a matrix using a raw array.
template<typename Type1 , typename Type2 , size_t N, size_t M>
static void setMatrix (MatrixData< Type1, N, M > &leftMat, const MatrixData< Type2, N, M > &rightMat)
Sets the values of a matrix using a raw array.
template<typename Type , size_t N>
static void setMatrixDiagonal (MatrixData< Type, N, N > &matrixObjective, const Type &value)
Sets the diagonal of a matrix to a specific value.
template<typename Type , size_t N, size_t M>
static void setMatrixZero (MatrixData< Type, N, M > &matrixObjective)
Sets the values of a matrix to zero.
template<typename Type , size_t N, size_t M>
static void swapRows (MatrixData< Type, N, M > &matrix, size_t row1, size_t row2)
Swaps two rows of a matrix.
template<typename Type , size_t N, size_t M>
static void transpose (const MatrixData< Type, N, M > &matrix, MatrixData< Type, M, N > &result)
Transposes a matrix.
template<typename Type , size_t N>
static void transposeInPlace (MatrixData< Type, N, N > &matrix)
Transposes a matrix in place.
Static Public Attributes
static constexpr bool columnMajorMatrix = true
Defines if the matrix implementation is row-major.
Static Private Member Functions
template<class Type , size_t N>
static Type cofactor (const MatrixData< Type, N, N > &matrix, size_t row, size_t col)
Calculates the cofactor of a matrix element.
template<typename Type , size_t N, size_t M>
static GaussianEliminationTrackedResult< Type, N, M > gaussianEliminationAlgorithm (const MatrixData< Type, N, M > &inputMatrix)
Calculates gaussian elimination with partial pivoting and extracts the result.
Detailed Description
Definition at line 26 of file MatrixAlgorithms.h.
Class Documentation
GLESC::Math::MatrixAlgorithms::GaussianEliminationTrackedResult
struct GLESC::Math::MatrixAlgorithms::GaussianEliminationTrackedResult
template<typename Type, size_t N, size_t M>
struct GLESC::Math::MatrixAlgorithms::GaussianEliminationTrackedResult< Type, N, M >
Struct that holds the result of Gaussian elimination with tracking.
Definition at line 1100 of file MatrixAlgorithms.h.
Class Members
MatrixData< Type, N, M > resultMatrix
vector< tuple< size_t, size_t, Type > > rowMultipleAdditions
vector< pair< size_t, Type > > rowMultiplications
map< pair< size_t, size_t >, pair< size_t, size_t > > rowSwaps
Member Function Documentation
calculateNormalMatrix()
template<typename ModelType , typename NormalMatType > static void GLESC::Math::MatrixAlgorithms::calculateNormalMatrix (const MatrixData< ModelType, 4, 4 > & MVMat, MatrixData< NormalMatType, 3, 3 > & normalMat) inline static
Calculates the normal matrix given the model-view matrix.
The normal matrix is used to transform the normal vectors from model space to eye space.
Template Parameters
ModelType The data type of the model-view matrix elements (e.g., float, double).
NormalMatType The data type of the normal matrix elements (e.g., float, double).
Parameters
MVMat The model-view matrix.
normalMat The result normal matrix.
Definition at line 675 of file MatrixAlgorithms.h.
{
            // Calculate the inverse of the 3x3 matrix
            MatrixData<ModelType, 4, 4> inverseMat;
            MatrixAlgorithms::inverse4x4(MVMat, inverseMat);
            MatrixData<ModelType, 4, 4> transposedMVMat;
            MatrixAlgorithms::transpose(inverseMat, transposedMVMat);
            // Now extract the upper-left 3x3 part from the transposed matrix
            MatrixData<ModelType, 3, 3> resizedMVMat;
            MatrixAlgorithms::resizeMatrix(transposedMVMat, resizedMVMat);
            // Assign the result to normalMat, no further transpose needed as we already transposed the whole matrix
            normalMat = resizedMVMat;
        }
References inverse4x4(), GLESC::isIterable_v, resizeMatrix(), and transpose().
Referenced by GLESC::Math::Matrix< Type, N, M >::makeNormalMatrix().
calculateProjectionMatrix()
template<typename Type > static void GLESC::Math::MatrixAlgorithms::calculateProjectionMatrix (float fovDegrees, float nearPlane, float farPlane, float viewWidth, float viewHeight, MatrixData< Type, 4, 4 > & projection) inline static
Calculates the perspective projection matrix.
Calculates the perspective projection matrix given the field of view, aspect ratio, near and far planes. The fov must be in degrees, on the contrary the result will be incorrect.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
fovDegrees The field of view in degrees.
nearPlane The near plane.
farPlane The far plane.
viewWidth The width of the view.
viewHeight The height of the view.
projection The result matrix.
Definition at line 860 of file MatrixAlgorithms.h.
{
            MatrixAlgorithms::perspective(radians(fovDegrees), nearPlane, farPlane, viewWidth, viewHeight, projection);
        }
References perspective(), and GLESC::Math::radians().
cofactor()
template<class Type , size_t N> static Type GLESC::Math::MatrixAlgorithms::cofactor (const MatrixData< Type, N, N > & matrix, size_t row, size_t col) inline static private
Calculates the cofactor of a matrix element.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the square matrix.
Parameters
matrix The matrix.
row The row of the element.
col The column of the element.
Returns
The cofactor of the element.
Definition at line 1188 of file MatrixAlgorithms.h.
{
            MatrixData<Type, N - 1, N - 1> subMatrix;
            size_t subI = 0;
            for (size_t i = 0; i < N; ++i) {
                if (i == row)
                    continue;
                size_t subJ = 0;
                for (size_t j = 0; j < N; ++j) {
                    if (j == col)
                        continue;
                    subMatrix[subI][subJ] = matrix[i][j];
                    subJ++;
                }
                subI++;
            }
            return laplaceExpansionDeterminant(subMatrix);
        }
References GLESC::isIterable_v, and laplaceExpansionDeterminant().
Referenced by laplaceExpansionDeterminant().
copyMatrix()
template<typename Type1 , typename Type2 , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::copyMatrix (MatrixData< Type1, N, M > & matrixObjective, const MatrixData< Type2, N, M > & matrixToCopy) inline static
Copies the data from one matrix to another.
If the source and destination matrices are the same, the function does nothing.
Template Parameters
Type1 The data type of the matrix elements (e.g., float, double).
Type2 The data type of the source matrix elements (e.g., float, double).
N The number of rows in the matrix.
M The number of columns in the matrix.
Parameters
matrixObjective The destination matrix where the data will be copied to.
matrixToCopy The source matrix from which the data will be copied.
Definition at line 172 of file MatrixAlgorithms.h.
{
            S_ASSERT_TRUE(std::is_copy_assignable_v<Type2>, "Type1 must be copy assignable.");
            S_ASSERT_TRUE((std::is_convertible_v<Type2, Type1>), "Type1 must be convertible from Type2.");
            // If the types are the same and the matrices are the same, do nothing
            if constexpr (std::is_same_v<Type1, Type2>) {
                if (&matrixObjective == &matrixToCopy)
                    return;
            }
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    matrixObjective[i][j] = static_cast<Type1>(matrixToCopy[i][j]);
        }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), gaussianEliminationAlgorithm(), matrixMatrixMulInPlace(), matrixMatrixMulNaiveInPlace(), GLESC::Math::Matrix< Type, N, M >::operator=(), GLESC::Math::Matrix< Type, N, M >::operator=(), and setMatrix().
determinant2x2()
template<typename Type > static void GLESC::Math::MatrixAlgorithms::determinant2x2 (const MatrixData< Type, 2, 2 > & matrix, Type & result) inline static
Calculates the determinant of a 2x2 matrix.
Computes the determinant of a matrix using Laplace expansion.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
matrix The matrix.
Returns
The determinant of the matrix.
Definition at line 920 of file MatrixAlgorithms.h.
{
            result = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0];
        }
References GLESC::isIterable_v.
Referenced by inverse2x2(), and laplaceExpansionDeterminant().
determinant3x3()
template<typename Type > static void GLESC::Math::MatrixAlgorithms::determinant3x3 (const MatrixData< Type, 3, 3 > & matrix, Type & result) inline static
Computes the determinant of a matrix 3x3.
Computes the determinant of a matrix using Laplace expansion.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
matrix The matrix.
result The result determinant.
Definition at line 932 of file MatrixAlgorithms.h.
{
            result = matrix[0][0] * (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) -
                matrix[0][1] * (matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0]) +
                matrix[0][2] * (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0]);
        }
References GLESC::isIterable_v.
Referenced by inverse3x3(), and laplaceExpansionDeterminant().
determinant4x4()
template<typename Type > static void GLESC::Math::MatrixAlgorithms::determinant4x4 (const MatrixData< Type, 4, 4 > & matrix, Type & result) inline static
Computes the determinant of a matrix 4x4.
Computes the determinant of a matrix using Laplace expansion.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
matrix The matrix.
result The result determinant.
Definition at line 946 of file MatrixAlgorithms.h.
{
            result = matrix[0][0] * (matrix[1][1] * (matrix[2][2] * matrix[3][3] - matrix[2][3] * matrix[3][2]) -
                matrix[1][2] * (matrix[2][1] * matrix[3][3] - matrix[2][3] * matrix[3][1]) +
                matrix[1][3] * (matrix[2][1] * matrix[3][2] - matrix[2][2] * matrix[3][1]));
            result -= matrix[0][1] * (matrix[1][0] * (matrix[2][2] * matrix[3][3] - matrix[2][3] * matrix[3][2]) -
                matrix[1][2] * (matrix[2][0] * matrix[3][3] - matrix[2][3] * matrix[3][0]) +
                matrix[1][3] * (matrix[2][0] * matrix[3][2] - matrix[2][2] * matrix[3][0]));
            result += matrix[0][2] * (matrix[1][0] * (matrix[2][1] * matrix[3][3] - matrix[2][3] * matrix[3][1]) -
                matrix[1][1] * (matrix[2][0] * matrix[3][3] - matrix[2][3] * matrix[3][0]) +
                matrix[1][3] * (matrix[2][0] * matrix[3][1] - matrix[2][1] * matrix[3][0]));
            result -= matrix[0][3] * (matrix[1][0] * (matrix[2][1] * matrix[3][2] - matrix[2][2] * matrix[3][1]) -
                matrix[1][1] * (matrix[2][0] * matrix[3][2] - matrix[2][2] * matrix[3][0]) +
                matrix[1][2] * (matrix[2][0] * matrix[3][1] - matrix[2][1] * matrix[3][0]));
        }
References GLESC::isIterable_v.
Referenced by inverse4x4(), and laplaceExpansionDeterminant().
fillMatrix()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::fillMatrix (MatrixData< Type, N, M > & matrixObjective, const Type & value) inline static
Sets the values of a matrix to one.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrixObjective The matrix to be set.
Definition at line 109 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    matrixObjective[i][j] = value;
        }
References GLESC::isIterable_v.
Referenced by setMatrixZero().
gaussianElimination()
template<typename Type , size_t N, size_t M> static GaussianEliminationData< Type, N, M > GLESC::Math::MatrixAlgorithms::gaussianElimination (const MatrixData< Type, N, M > & matrix) inline static
Performs Gaussian elimination on a matrix. @TODO: Make this work (doesn't work for some reason)
Template Parameters
Type
N
M
Parameters
matrix
Returns
Definition at line 998 of file MatrixAlgorithms.h.
{
            MatrixData<Type, N, M * 2> augmentedMatrix;
            MatrixData<Type, N, M> identityMatrix;
            MatrixData<Type, N, M> inverseResult;
            // Initialize identity matrix
            MatrixAlgorithms::setMatrixDiagonal(identityMatrix, Type(1));
            // Augment the original matrix with identity matrix
            for (size_t i = 0; i < N; ++i) {
                for (size_t j = 0; j < M; ++j) {
                    augmentedMatrix[i][j] = matrix[i][j];
                    augmentedMatrix[i][N + j] = identityMatrix[i][j];
                }
            }
            // Perform Gaussian elimination on the augmented matrix
            auto result = gaussianEliminationAlgorithm(augmentedMatrix);
            // Extract the inverse matrix from the augmented matrix
            for (size_t i = 0; i < N; i++) {
                for (size_t j = 0; j < M; j++) {
                    inverseResult[i][j] = augmentedMatrix[i][j + M];
                }
            }
            // Extract the rank of the matrix
            // Rank is the number of non-zero rows in the matrix
            unsigned int rank = 0;
            for (size_t i = 0; i < N; ++i) {
                bool isZeroRow = true;
                for (size_t j = 0; j < N; ++j) {
                    if (augmentedMatrix[i][j] != 0) {
                        isZeroRow = false;
                        break;
                    }
                }
                if (!isZeroRow)
                    ++rank;
            }
            // Extract the determinant of the matrix
            // Determinant is the product of diagonal entries of the matrix
            // Also, the result must be multiplied by -1 if the number of row swaps is odd
            Type determinant = Type(1);
            for (size_t i = 0; i < N; ++i) {
                determinant *= augmentedMatrix[i][i];
            }
            bool isRowSwapOdd = result.rowSwaps.size() % 2 == 1;
            determinant *= isRowSwapOdd ? Type(-1) : Type(1);
            GaussianEliminationData<Type, N, M> extractedData(inverseResult, rank, determinant);
            return extractedData;
        }
References gaussianEliminationAlgorithm(), GLESC::isIterable_v, and setMatrixDiagonal().
Referenced by GLESC::Math::Matrix< Type, N, M >::rank().
gaussianEliminationAlgorithm()
template<typename Type , size_t N, size_t M> static GaussianEliminationTrackedResult< Type, N, M > GLESC::Math::MatrixAlgorithms::gaussianEliminationAlgorithm (const MatrixData< Type, N, M > & inputMatrix) inline static private
Calculates gaussian elimination with partial pivoting and extracts the result.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
inputMatrix The input matrix.
Returns
The result of the Gaussian elimination.
Definition at line 1117 of file MatrixAlgorithms.h.
{
            GaussianEliminationTrackedResult<Type, N, M> trackedResult;
            // Copy input matrix to result matrix
            copyMatrix(trackedResult.resultMatrix, inputMatrix);
            // Perform Gaussian elimination with partial pivoting
            for (size_t i = 0; i < std::min(N, M); ++i) {
                // Search for maximum in this column
                size_t maxRow = i;
                Type maxElem = std::fabs(trackedResult.resultMatrix[i][i]);
                for (size_t k = i + 1; k < N; ++k) {
                    Type absValue = std::fabs(trackedResult.resultMatrix[k][i]);
                    if (absValue > maxElem) {
                        maxElem = absValue;
                        maxRow = k;
                    }
                }
                // Check for zero pivot value (potential singularity)
                if (maxElem == Type(0)) {
                    throw std::runtime_error("Singular matrix, no unique solution exists.");
                }
                // Swap maximum row with current row (column by column)
                if (i != maxRow) {
                    swapRows(trackedResult.resultMatrix, i, maxRow);
                    trackedResult.rowSwaps[{i, maxRow}] = {maxRow, i};
                }
                // Make all rows below this one 0 in current column
                for (size_t k = i + 1; k < N; ++k) {
                    Type c = -trackedResult.resultMatrix[k][i] / trackedResult.resultMatrix[i][i];
                    for (size_t j = i; j < M; ++j) {
                        if (i == j) {
                            trackedResult.resultMatrix[k][j] = 0;
                        }
                        else {
                            trackedResult.resultMatrix[k][j] += c * trackedResult.resultMatrix[i][j];
                        }
                    }
                    trackedResult.rowMultipleAdditions.push_back({k, i, c});
                }
            }
            // Back-substitution (if the system is square and N == M)
            if (N == M) {
                for (size_t i = N; i-- > 0;) {
                    Type sum = trackedResult.resultMatrix[i][N];
                    for (size_t j = i + 1; j < N; ++j) {
                        sum -= trackedResult.resultMatrix[i][j] * trackedResult.resultMatrix[j][N];
                    }
                    trackedResult.resultMatrix[i][N] = sum / trackedResult.resultMatrix[i][i];
                    trackedResult.rowMultiplications.push_back({i, 1 / trackedResult.resultMatrix[i][i]});
                }
            }
            return trackedResult;
        }
References copyMatrix(), GLESC::isIterable_v, and swapRows().
Referenced by gaussianElimination().
getScaleMatrix()
template<typename Type1 , typename Type2 , size_t N> static void GLESC::Math::MatrixAlgorithms::getScaleMatrix (const VectorData< Type2, N - 1 > & scale, MatrixData< Type1, N, N > & result) inline static
Gets the scale matrix.
Creates a scale matrix from a scale vector. The scale matrix is a diagonal matrix with the scale vector elements on the diagonal.
Template Parameters
Type1 The data type of the matrix elements (e.g., float, double).
Type2 The data type of the scale vector elements (e.g., float, double).
N The size of the scale vector.
Parameters
scale The scale vector.
result The result matrix.
Definition at line 651 of file MatrixAlgorithms.h.
{
            static_assert(N == 3 || N == 4, "Scaling only makes sense for 3x3 and 4x4 matrices.");
            // Create the scale matrix
            MatrixAlgorithms::setMatrixZero(result);
            // Set the scale components on the matrix's diagonal
            for (size_t i = 0; i < N - 1; ++i) {
                result[i][i] = scale[i];
            }
            result[N - 1][N - 1] = Type1(1);
        }
References GLESC::isIterable_v, and setMatrixZero().
Referenced by GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix(), and GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot().
getTranslationMatrix()
template<typename TypeMat , typename TypePos > static void GLESC::Math::MatrixAlgorithms::getTranslationMatrix (const VectorData< TypePos, 3 > & translation, MatrixData< TypeMat, 4, 4 > & result) inline static
Applies the translation to a model matrix.
The translation matrix is applied taking into account the matrix is in row major order.
Template Parameters
TypeMat The data type of the matrix elements (e.g., float, double).
TypePos The data type of the translation vector elements (e.g., float, double).
Parameters
translation The translation vector.
result The result matrix.
Definition at line 629 of file MatrixAlgorithms.h.
{
            // Create the translation matrix
            MatrixAlgorithms::setMatrixZero(result);
            MatrixAlgorithms::setMatrixDiagonal(result, TypeMat(1));
            result[3][0] = translation[0];
            result[3][1] = translation[1];
            result[3][2] = translation[2];
        }
References GLESC::isIterable_v, setMatrixDiagonal(), and setMatrixZero().
Referenced by GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix(), and GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot().
inverse2x2()
template<typename Type , size_t N> static void GLESC::Math::MatrixAlgorithms::inverse2x2 (const MatrixData< Type, N, N > & matrix, MatrixData< Type, N, N > & result) inline static
Calculates the inverse of a 2x2 matrix.
The inverse matrix is calculated using the formula: |a b|^-1 = 1/det |d -b| |c d| |-c a|
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the matrix.
Parameters
matrix The matrix.
result The result matrix.
Definition at line 718 of file MatrixAlgorithms.h.
{
            Type determinant;
            MatrixAlgorithms::determinant2x2(matrix, determinant);
            D_ASSERT_TRUE(MatrixAlgorithms::isInvertible(matrix), "Matrix is not invertible.");
            D_ASSERT_FALSE(&matrix == &result, "Cannot invert matrix in place.");
            result[0][0] = matrix[1][1] / determinant;
            result[0][1] = -matrix[0][1] / determinant;
            result[1][0] = -matrix[1][0] / determinant;
            result[1][1] = matrix[0][0] / determinant;
        }
References D_ASSERT_FALSE, D_ASSERT_TRUE, determinant2x2(), isInvertible(), and GLESC::isIterable_v.
Referenced by matrixInverse().
inverse3x3()
template<typename Type , size_t N> static void GLESC::Math::MatrixAlgorithms::inverse3x3 (const MatrixData< Type, N, N > & matrix, MatrixData< Type, N, N > & result) inline static
Calculates the inverse of a 3x3 matrix.
The inverse matrix is calculated using the formula: |a b c|^-1 = 1/det |i -f g| |d e f| |-h e c| |g h i| |g -d a|
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the matrix.
Parameters
matrix The matrix.
result The result matrix.
Definition at line 742 of file MatrixAlgorithms.h.
{
            Type determinant;
            MatrixAlgorithms::determinant3x3(matrix, determinant);
            D_ASSERT_TRUE(MatrixAlgorithms::isInvertible(matrix), "Matrix is not invertible.");
            D_ASSERT_FALSE(&matrix == &result, "Cannot invert matrix in place.");
            result[0][0] = (matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1]) / determinant;
            result[0][1] = (matrix[0][2] * matrix[2][1] - matrix[0][1] * matrix[2][2]) / determinant;
            result[0][2] = (matrix[0][1] * matrix[1][2] - matrix[0][2] * matrix[1][1]) / determinant;
            result[1][0] = (matrix[1][2] * matrix[2][0] - matrix[1][0] * matrix[2][2]) / determinant;
            result[1][1] = (matrix[0][0] * matrix[2][2] - matrix[0][2] * matrix[2][0]) / determinant;
            result[1][2] = (matrix[0][2] * matrix[1][0] - matrix[0][0] * matrix[1][2]) / determinant;
            result[2][0] = (matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0]) / determinant;
            result[2][1] = (matrix[0][1] * matrix[2][0] - matrix[0][0] * matrix[2][1]) / determinant;
            result[2][2] = (matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]) / determinant;
        }
References D_ASSERT_FALSE, D_ASSERT_TRUE, determinant3x3(), isInvertible(), and GLESC::isIterable_v.
Referenced by matrixInverse().
inverse4x4()
template<typename Type , size_t N> static void GLESC::Math::MatrixAlgorithms::inverse4x4 (const MatrixData< Type, N, N > & matrix, MatrixData< Type, N, N > & result) inline static
Calculates the inverse of a 4x4 matrix.
The inverse matrix is calculated using the formula of the adjugate matrix. [https://en.wikipedia.org/wiki/Invertible_matrix]Inversion_of_4_C3%97_4_matrices
Template Parameters
N The size of the matrix.
Parameters
matrix The matrix.
result The result matrix.
Definition at line 768 of file MatrixAlgorithms.h.
{
            Type determinant;
            MatrixAlgorithms::determinant4x4(matrix, determinant);
            D_ASSERT_TRUE(MatrixAlgorithms::isInvertible(matrix), "Matrix is not invertible.");
            D_ASSERT_FALSE(&matrix == &result, "Cannot invert matrix in place.");
            Type A2323 = matrix[2][2] * matrix[3][3] - matrix[2][3] * matrix[3][2];
            Type A1323 = matrix[2][1] * matrix[3][3] - matrix[2][3] * matrix[3][1];
            Type A1223 = matrix[2][1] * matrix[3][2] - matrix[2][2] * matrix[3][1];
            Type A0323 = matrix[2][0] * matrix[3][3] - matrix[2][3] * matrix[3][0];
            Type A0223 = matrix[2][0] * matrix[3][2] - matrix[2][2] * matrix[3][0];
            Type A0123 = matrix[2][0] * matrix[3][1] - matrix[2][1] * matrix[3][0];
            Type A2313 = matrix[1][2] * matrix[3][3] - matrix[1][3] * matrix[3][2];
            Type A1313 = matrix[1][1] * matrix[3][3] - matrix[1][3] * matrix[3][1];
            Type A1213 = matrix[1][1] * matrix[3][2] - matrix[1][2] * matrix[3][1];
            Type A2312 = matrix[1][2] * matrix[2][3] - matrix[1][3] * matrix[2][2];
            Type A1312 = matrix[1][1] * matrix[2][3] - matrix[1][3] * matrix[2][1];
            Type A1212 = matrix[1][1] * matrix[2][2] - matrix[1][2] * matrix[2][1];
            Type A0313 = matrix[1][0] * matrix[3][3] - matrix[1][3] * matrix[3][0];
            Type A0213 = matrix[1][0] * matrix[3][2] - matrix[1][2] * matrix[3][0];
            Type A0312 = matrix[1][0] * matrix[2][3] - matrix[1][3] * matrix[2][0];
            Type A0212 = matrix[1][0] * matrix[2][2] - matrix[1][2] * matrix[2][0];
            Type A0113 = matrix[1][0] * matrix[3][1] - matrix[1][1] * matrix[3][0];
            Type A0112 = matrix[1][0] * matrix[2][1] - matrix[1][1] * matrix[2][0];
            Type invDet = 1.0 / determinant;
            result[0][0] = invDet * (matrix[1][1] * A2323 - matrix[1][2] * A1323 + matrix[1][3] * A1223);
            result[0][1] = invDet * -(matrix[0][1] * A2323 - matrix[0][2] * A1323 + matrix[0][3] * A1223);
            result[0][2] = invDet * (matrix[0][1] * A2313 - matrix[0][2] * A1313 + matrix[0][3] * A1213);
            result[0][3] = invDet * -(matrix[0][1] * A2312 - matrix[0][2] * A1312 + matrix[0][3] * A1212);
            result[1][0] = invDet * -(matrix[1][0] * A2323 - matrix[1][2] * A0323 + matrix[1][3] * A0223);
            result[1][1] = invDet * (matrix[0][0] * A2323 - matrix[0][2] * A0323 + matrix[0][3] * A0223);
            result[1][2] = invDet * -(matrix[0][0] * A2313 - matrix[0][2] * A0313 + matrix[0][3] * A0213);
            result[1][3] = invDet * (matrix[0][0] * A2312 - matrix[0][2] * A0312 + matrix[0][3] * A0212);
            result[2][0] = invDet * (matrix[1][0] * A1323 - matrix[1][1] * A0323 + matrix[1][3] * A0123);
            result[2][1] = invDet * -(matrix[0][0] * A1323 - matrix[0][1] * A0323 + matrix[0][3] * A0123);
            result[2][2] = invDet * (matrix[0][0] * A1313 - matrix[0][1] * A0313 + matrix[0][3] * A0113);
            result[2][3] = invDet * -(matrix[0][0] * A1312 - matrix[0][1] * A0312 + matrix[0][3] * A0112);
            result[3][0] = invDet * -(matrix[1][0] * A1223 - matrix[1][1] * A0223 + matrix[1][2] * A0123);
            result[3][1] = invDet * (matrix[0][0] * A1223 - matrix[0][1] * A0223 + matrix[0][2] * A0123);
            result[3][2] = invDet * -(matrix[0][0] * A1213 - matrix[0][1] * A0213 + matrix[0][2] * A0113);
            result[3][3] = invDet * (matrix[0][0] * A1212 - matrix[0][1] * A0212 + matrix[0][2] * A0112);
        }
References D_ASSERT_FALSE, D_ASSERT_TRUE, determinant4x4(), isInvertible(), and GLESC::isIterable_v.
Referenced by calculateNormalMatrix(), and matrixInverse().
isInvertible()
template<typename Type , size_t N> static bool GLESC::Math::MatrixAlgorithms::isInvertible (const MatrixData< Type, N, N > & matrix) inline static
Checks if a matrix is invertible.
A matrix is invertible if its determinant is not zero.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the square matrix.
Parameters
matrix The matrix.
Returns
True if the matrix is invertible, false otherwise.
Definition at line 906 of file MatrixAlgorithms.h.
{
            Type determinant = MatrixAlgorithms::laplaceExpansionDeterminant(matrix);
            return !Math::eq(determinant, 0);
        }
References GLESC::Math::eq(), GLESC::isIterable_v, and laplaceExpansionDeterminant().
Referenced by inverse2x2(), inverse3x3(), inverse4x4(), and isValidViewMatrix().
isValidViewMatrix()
template<typename Type > static bool GLESC::Math::MatrixAlgorithms::isValidViewMatrix (const MatrixData< Type, 4, 4 > & viewMatrix) inline static
Checks if a matrix is a valid view matrix.
A view matrix is valid if it is invertible.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
viewMatrix The view matrix.
Returns
True if the view matrix is valid, false otherwise.
Definition at line 701 of file MatrixAlgorithms.h.
{
            // The view matrix is valid if it is invertible
            return MatrixAlgorithms::isInvertible(viewMatrix);
        }
References isInvertible(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::isValidViewMatrix().
laplaceExpansionDeterminant()
template<class Type , size_t N> static Type GLESC::Math::MatrixAlgorithms::laplaceExpansionDeterminant (const MatrixData< Type, N, N > & matrix) inline static
Calculates the determinant of any matrix using Laplace expansion.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the square matrix.
Parameters
matrix The matrix.
Returns
The determinant of the matrix.
Definition at line 1064 of file MatrixAlgorithms.h.
{
            if constexpr (N == 1) {
                return matrix[0][0];
            }
            else if constexpr (N == 2) {
                Type det;
                MatrixAlgorithms::determinant2x2(matrix, det);
                return det;
            }
            else if constexpr (N == 3) {
                Type det;
                MatrixAlgorithms::determinant3x3(matrix, det);
                return det;
            }
            else if constexpr (N == 4) {
                Type det;
                MatrixAlgorithms::determinant4x4(matrix, det);
                return det;
            }
            else {
                Type result = Type();
                Type sign = 1;
                for (size_t j = 0; j < N; ++j) {
                    result += sign * matrix[0][j] * cofactor(matrix, Type(0), j);
                    sign = -sign; // Alternate sign for cofactor expansion
                }
                return result;
            }
        }
References cofactor(), determinant2x2(), determinant3x3(), determinant4x4(), and GLESC::isIterable_v.
Referenced by cofactor(), GLESC::Math::Matrix< Type, N, M >::determinant(), isInvertible(), and matrixMatrixDiv().
matrixAdd()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixAdd (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, N, M > & matrix2, MatrixData< Type, N, M > & result) inline static
Adds two matrices, element-wise.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrices.
M The number of columns of the matrices.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
result The result matrix.
Definition at line 242 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix1[i][j] + matrix2[i][j];
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator+(), and GLESC::Math::Matrix< Type, N, M >::operator+=().
matrixHadamardDiv()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixHadamardDiv (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, N, M > & matrix2, MatrixData< Type, N, M > & result) inline static
Divides two matrices. Hadamard division.
Divides all elements of the first matrix by the corresponding elements of the second matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrices.
M The number of columns of the matrices.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
result The result matrix.
Definition at line 368 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j) {
                    if (matrix2[i][j] == 0)
                        throw MathException("Division by zero is not allowed.");
                    result[i][j] = matrix1[i][j] / matrix2[i][j];
                }
        }
References GLESC::isIterable_v.
matrixHadamardMul()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixHadamardMul (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, N, M > & matrix2, MatrixData< Type, N, M > & result) inline static
Multiplies two matrices, element-wise.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrices.
M The number of columns of the matrices.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
result The result matrix.
Definition at line 278 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix1[i][j] * matrix2[i][j];
        }
References GLESC::isIterable_v.
matrixInverse()
template<typename Type , size_t N, typename = std::enable_if_t<N == 2 || N == 3 || N == 4>> static void GLESC::Math::MatrixAlgorithms::matrixInverse (const MatrixData< Type, N, N > & matrix, MatrixData< Type, N, N > & result) inline static
Calculates the inverse of any square matrix.
The inverse matrix is calculated using the adjugate matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the matrix.
Parameters
matrix The matrix.
result The result matrix.
Definition at line 881 of file MatrixAlgorithms.h.
{
            if constexpr (N == 2) {
                MatrixAlgorithms::inverse2x2(matrix, result);
            }
            else if constexpr (N == 3) {
                MatrixAlgorithms::inverse3x3(matrix, result);
            }
            else if constexpr (N == 4) {
                MatrixAlgorithms::inverse4x4(matrix, result);
            }
            else {
                // TODO: Implement general inverse
                //result = MatrixAlgorithms::gaussianElimination(matrix).inverse;
            }
        }
References inverse2x2(), inverse3x3(), inverse4x4(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::inverse(), and matrixMatrixDiv().
matrixMatrixDiv()
template<typename Type , size_t N, size_t M, size_t X> static void GLESC::Math::MatrixAlgorithms::matrixMatrixDiv (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, M, X > & matrix2, MatrixData< Type, N, X > & result) inline static
Matrix division.
Computes the inverse of the second matrix and multiplies it with the first matrix.
Template Parameters
Type The data type of the matrix and vector elements (e.g., float, double).
N The number of rows of the first matrix.
M The number of columns of the first matrix.
X The number of columns of the second matrix.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
result The result matrix.
Definition at line 570 of file MatrixAlgorithms.h.
{
            Type det = MatrixAlgorithms::laplaceExpansionDeterminant(matrix2);
            if (Math::eq(det, 0))
                throw MathException("Matrix is not invertible.");
            MatrixData<Type, M, X> inverse;
            MatrixAlgorithms::matrixInverse(matrix2, inverse);
            if constexpr (columnMajorMatrix) {
                MatrixData<Type, X, N> resultTemp;
                MatrixAlgorithms::matrixMatrixMulColMaj(matrix1, inverse, resultTemp);
                result = resultTemp;
            }
            else {
                MatrixData<Type, N, X> resultTemp;
                MatrixAlgorithms::matrixMatrixMulRowMaj(matrix1, inverse, resultTemp);
                result = resultTemp;
            }
        }
References columnMajorMatrix, GLESC::Math::eq(), GLESC::isIterable_v, laplaceExpansionDeterminant(), matrixInverse(), matrixMatrixMulColMaj(), and matrixMatrixMulRowMaj().
Referenced by GLESC::Math::Matrix< Type, N, M >::operator/(), and GLESC::Math::Matrix< Type, N, M >::operator/=().
matrixMatrixMulColMaj()
template<typename Type , size_t N, size_t M, size_t X> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulColMaj (const MatrixData< Type, M, N > & matrix1, const MatrixData< Type, X, M > & matrix2, MatrixData< Type, X, N > & result) inline static
Definition at line 398 of file MatrixAlgorithms.h.
{
            D_ASSERT_NOT_EQUAL(&matrix1, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            D_ASSERT_NOT_EQUAL(&matrix2, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            for (size_t i = 0; i < N; ++i) {
                for (size_t j = 0; j < X; ++j) {
                    Type sum = static_cast<Type>(0);
                    Type c = static_cast<Type>(0); // A running compensation for lost low-order bits.
                    for (size_t k = 0; k < M; ++k) {
                        Type product = matrix1[k][i] * matrix2[j][k];
                        Type y = product - c;
                        Type t = sum + y;
                        c = (t - sum) - y;
                        sum = t;
                    }
                    result[j][i] = sum;
                }
            }
        }
References D_ASSERT_NOT_EQUAL, and GLESC::isIterable_v.
Referenced by matrixMatrixDiv(), matrixMatrixMulInPlace(), and GLESC::Math::Matrix< Type, N, M >::operator*().
matrixMatrixMulInPlace()
template<typename Type , size_t N, size_t M, size_t N2, size_t M2, size_t N3, size_t M3> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulInPlace (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, N2, M2 > & matrix2, MatrixData< Type, N3, M3 > & result) inline static
Dot product matrix multiplication in place.
An in place method is needed because the normal matrix multiplication doesn't allow it without making any copy. So this method is provieded but does make copy of the result.
Note
Only makes sense for square matrices.
Template Parameters
Type The data type of the matrix and vector elements (e.g., float, double).
N The number of rows of the first matrix.
M The number of columns of the first matrix.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
Definition at line 516 of file MatrixAlgorithms.h.
{
            if constexpr (columnMajorMatrix) {
                MatrixData<Type, M, N> temp(result);
                matrixMatrixMulColMaj(matrix1, matrix2, temp);
                copyMatrix(result, temp);
            }
            else {
                MatrixData<Type, N, M> temp(result);
                matrixMatrixMulRowMaj(matrix1, matrix2, temp);
                copyMatrix(result, temp);
            }
        }
References columnMajorMatrix, copyMatrix(), GLESC::isIterable_v, matrixMatrixMulColMaj(), and matrixMatrixMulRowMaj().
Referenced by GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix(), GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot(), GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrix(), and GLESC::Math::Matrix< Type, N, M >::operator*=().
matrixMatrixMulNaiveColMaj()
template<typename Type , size_t N, size_t M, size_t X> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulNaiveColMaj (const MatrixData< Type, M, N > & matrix1, const MatrixData< Type, X, M > & matrix2, MatrixData< Type, X, N > & result) inline static
Definition at line 443 of file MatrixAlgorithms.h.
{
            D_ASSERT_NOT_EQUAL(&matrix1, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            D_ASSERT_NOT_EQUAL(&matrix2, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            for (size_t i = 0; i < N; ++i) {
                for (size_t j = 0; j < X; ++j) {
                    Type sum = 0;
                    for (size_t k = 0; k < M; ++k) {
                        sum += matrix1[k][i] * matrix2[j][k]; // Reversed multiplication order
                    }
                    result[j][i] = sum; // Store the result
                }
            }
        }
References D_ASSERT_NOT_EQUAL, and GLESC::isIterable_v.
Referenced by matrixMatrixMulNaiveInPlace().
matrixMatrixMulNaiveInPlace()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulNaiveInPlace (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, M, M > & matrix2, MatrixData< Type, N, M > & result) inline static
Dot product matrix multiplication in place.
An in place method is needed because the normal matrix multiplication doesn't allow it without making any copy. So this method is provieded but does make copy of the result.
Note
Only makes sense for square matrices.
Template Parameters
Type The data type of the matrix and vector elements (e.g., float, double).
N The number of rows of the first matrix.
M The number of columns of the first matrix.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
Definition at line 543 of file MatrixAlgorithms.h.
{
            if constexpr (columnMajorMatrix) {
                MatrixData<Type, M, N> temp(result);
                matrixMatrixMulNaiveColMaj(matrix1, matrix2, temp);
                copyMatrix(result, temp);
            }
            else {
                MatrixData<Type, N, M> temp(result);
                matrixMatrixMulNaiveRowMaj(matrix1, matrix2, temp);
                copyMatrix(result, temp);
            }
        }
References columnMajorMatrix, copyMatrix(), GLESC::isIterable_v, matrixMatrixMulNaiveColMaj(), and matrixMatrixMulNaiveRowMaj().
matrixMatrixMulNaiveRowMaj()
template<typename Type , size_t N, size_t M, size_t X> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulNaiveRowMaj (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, M, X > & matrix2, MatrixData< Type, N, X > & result) inline static
Definition at line 460 of file MatrixAlgorithms.h.
{
            D_ASSERT_NOT_EQUAL(&matrix1, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            D_ASSERT_NOT_EQUAL(&matrix2, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            for (size_t i = 0; i < N; ++i) {
                for (size_t j = 0; j < X; ++j) {
                    Type sum = 0;
                    for (size_t k = 0; k < M; ++k) {
                        sum += matrix1[i][k] * matrix2[k][j];
                    }
                    result[i][j] = sum;
                }
            }
        }
References D_ASSERT_NOT_EQUAL, and GLESC::isIterable_v.
Referenced by matrixMatrixMulNaiveInPlace().
matrixMatrixMulRowMaj()
template<typename Type , size_t N, size_t M, size_t X> static void GLESC::Math::MatrixAlgorithms::matrixMatrixMulRowMaj (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, M, X > & matrix2, MatrixData< Type, N, X > & result) inline static
Definition at line 420 of file MatrixAlgorithms.h.
{
            D_ASSERT_NOT_EQUAL(&matrix1, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            D_ASSERT_NOT_EQUAL(&matrix2, &result, "Cannot multiply matrix in place. Use matrixMatrixMulNaiveInPlace.");
            for (size_t i = 0; i < N; ++i) {
                for (size_t j = 0; j < X; ++j) {
                    Type sum = static_cast<Type>(0);
                    Type c = static_cast<Type>(0); // A running compensation for lost low-order bits.
                    for (size_t k = 0; k < M; ++k) {
                        Type product = matrix1[i][k] * matrix2[k][j];
                        Type y = product - c;
                        Type t = sum + y;
                        c = (t - sum) - y;
                        sum = t;
                    }
                    result[i][j] = sum;
                }
            }
        }
References D_ASSERT_NOT_EQUAL, and GLESC::isIterable_v.
Referenced by matrixMatrixDiv(), matrixMatrixMulInPlace(), and GLESC::Math::Matrix< Type, N, M >::operator*().
matrixNegate()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixNegate (const MatrixData< Type, N, M > & matrix, MatrixData< Type, N, M > & result) inline static
Negates a matrix.
Negates each element of a matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
Returns
Negated matrix.
Definition at line 350 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = -matrix[i][j];
        }
References GLESC::isIterable_v.
matrixScalarAdd()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixScalarAdd (const MatrixData< Type, N, M > & matrix, const Type & scalar, MatrixData< Type, N, M > & result) inline static
Adds a scalar to a matrix.
Adds a scalar to each element of a matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
scalar The scalar.
result The result matrix.
Definition at line 262 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix[i][j] + scalar;
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator+(), and GLESC::Math::Matrix< Type, N, M >::operator+=().
matrixScalarDiv()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixScalarDiv (const MatrixData< Type, N, M > & matrix, const Type & scalar, MatrixData< Type, N, M > & result) inline static
Divides a matrix by a scalar.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
scalar The scalar.
result The result matrix.
Definition at line 390 of file MatrixAlgorithms.h.
{
            if (scalar == 0)
                throw MathException("Division by zero is not allowed.");
            matrixScalarMul(matrix, Type(1) / scalar, result);
        }
References GLESC::isIterable_v, and matrixScalarMul().
Referenced by GLESC::Math::Matrix< Type, N, M >::operator/(), and GLESC::Math::Matrix< Type, N, M >::operator/=().
matrixScalarMul()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixScalarMul (const MatrixData< Type, N, M > & matrix, const Type & scalar, MatrixData< Type, N, M > & result) inline static
Multiplies a matrix by a scalar, element-wise.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
scalar The scalar.
result The result matrix.
Definition at line 297 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix[i][j] * scalar;
        }
References GLESC::isIterable_v.
Referenced by matrixScalarDiv(), GLESC::Math::Matrix< Type, N, M >::operator*(), GLESC::Math::Matrix< Type, N, M >::operator*=(), and GLESC::Math::Matrix< Type, N, M >::operator-().
matrixScalarSub()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixScalarSub (const MatrixData< Type, N, M > & matrix, const Type & scalar, MatrixData< Type, N, M > & result) inline static
Subtracts a scalar from a matrix, element-wise.
Subtracts a scalar from each element of a matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
scalar The scalar.
result The result matrix.
Definition at line 334 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix[i][j] - scalar;
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator-(), and GLESC::Math::Matrix< Type, N, M >::operator-=().
matrixSub()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixSub (const MatrixData< Type, N, M > & matrix1, const MatrixData< Type, N, M > & matrix2, MatrixData< Type, N, M > & result) inline static
Subtracts two matrices, element-wise.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrices.
M The number of columns of the matrices.
Parameters
matrix1 The first matrix.
matrix2 The second matrix.
result The result matrix.
Definition at line 313 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[i][j] = matrix1[i][j] - matrix2[i][j];
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator-(), and GLESC::Math::Matrix< Type, N, M >::operator-=().
matrixVectorMulColMaj()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixVectorMulColMaj (const MatrixData< Type, M, N > & matrix, const VectorData< Type, M > & vector, VectorData< Type, N > & result) inline static
Definition at line 491 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                Type sum = 0;
                for (size_t j = 0; j < M; ++j) {
                    sum += matrix[j][i] * vector[j];
                }
                result[i] = sum;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator*().
matrixVectorMulRowMaj()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::matrixVectorMulRowMaj (const VectorData< Type, M > & vector, const MatrixData< Type, N, M > & matrix, VectorData< Type, N > & result) inline static
Definition at line 478 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                Type sum = 0;
                for (size_t j = 0; j < M; ++j) {
                    sum += matrix[i][j] * vector[j];
                }
                result[i] = sum;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::operator*().
moveMatrix()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::moveMatrix (MatrixData< Type, N, M > & matrixObjective, MatrixData< Type, N, M > && matrixToMove) inline static
Moves the data from one matrix to another. @deatails This function moves the data from the source matrix to the destination matrix. If the source and destination matrices are the same, the function does nothing.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows in the matrix.
M The number of columns in the matrix.
Parameters
matrixObjective The destination matrix where the data will be moved to.
matrixToMove The source matrix from which the data will be moved.
Definition at line 200 of file MatrixAlgorithms.h.
{
            if (&matrixObjective == &matrixToMove)
                return;
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    matrixObjective[i][j] = std::move(matrixToMove[i][j]);
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::operator=(), and GLESC::Math::Matrix< Type, N, M >::operator=().
perspective()
template<typename Type > static void GLESC::Math::MatrixAlgorithms::perspective (float fovRad, float nearPlane, float farPlane, float viewWidth, float viewHeight, MatrixData< Type, 4, 4 > & result) inline static
Calculates the perspective projection matrix.
Calculates the perspective projection matrix given the field of view, aspect ratio, near and far planes. The fov must be in radians, on the contrary the result will be incorrect. [https://www.songho.ca/opengl/gl_projectionmatrix.html]
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
Parameters
fovRad The field of view in radians.
nearPlane The near plane.
farPlane The far plane.
viewWidth The width of the view.
viewHeight The height of the view.
result The result matrix.
Definition at line 827 of file MatrixAlgorithms.h.
{
            S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic.");
            MatrixAlgorithms::setMatrixZero(result);
            Type const tanHalfFovy = Math::tan(fovRad / static_cast<Type>(2));
            Type aspect = viewWidth / viewHeight;
            result[0][0] = static_cast<Type>(1) / (aspect * tanHalfFovy);
            result[1][1] = static_cast<Type>(1) / (tanHalfFovy);
            result[2][2] = -(farPlane + nearPlane) / (farPlane - nearPlane);
            result[2][3] = -static_cast<Type>(1);
            result[3][2] = -(static_cast<Type>(2) * farPlane * nearPlane) / (farPlane - nearPlane);
        }
References GLESC::isIterable_v, S_ASSERT_TRUE, setMatrixZero(), and GLESC::Math::tan().
Referenced by calculateProjectionMatrix().
resizeMatrix()
template<typename Type1 , size_t N1, size_t M1, typename Type2 , size_t N2, size_t M2> static void GLESC::Math::MatrixAlgorithms::resizeMatrix (const MatrixData< Type1, N1, M1 > & matrix, MatrixData< Type2, N2, M2 > & result) inline static
Resizes a matrix.
Resizes a matrix to a new size. The new matrix will have the same values as the original matrix. But the new matrix will have the new size. If the new size is smaller than the original matrix, the values will be truncated. If the new size is larger than the original matrix, the new values will be set to zero.
Template Parameters
Type1 The data type of the matrix elements (e.g., float, double).
N1 The number of rows of the original matrix.
M1 The number of columns of the original matrix.
Type2 The data type of the new matrix elements (e.g., float, double).
N2 The number of rows of the new matrix.
M2 The number of columns of the new matrix.
Parameters
matrix The original matrix.
result The new matrix.
Definition at line 52 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N2; ++i) {
                for (size_t j = 0; j < M2; ++j) {
                    // Check if current indices are within the bounds of the original matrix
                    if (i < N1 && j < M1) {
                        // Safe to copy from the original matrix
                        result[i][j] = static_cast<Type2>(matrix[i][j]);
                    }
                    else {
                        // Outside the bounds of the original matrix, fill with zeroes
                        result[i][j] = static_cast<Type2>(0);
                    }
                }
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), calculateNormalMatrix(), GLESC::Math::Matrix< Type, N, M >::operator=(), and GLESC::Math::Matrix< Type, N, M >::operator=().
setMatrix() [1/3]
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::setMatrix (MatrixData< Type, N, M > & matrixObjective, const Type(&&) values[N][M]) inline static
Sets the values of a matrix using a rvalue raw array.
This function moves the data from the raw array to the matrix data.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows in the matrix.
M The number of columns in the matrix.
Parameters
matrixObjective The matrix to be set.
values The rvalue raw array containing the values to be moved into the matrix.
Definition at line 220 of file MatrixAlgorithms.h.
{
            if (&matrixObjective == &values)
                return;
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    matrixObjective[i][j] = std::move(values[i][j]);
        }
References GLESC::isIterable_v.
setMatrix() [2/3]
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::setMatrix (MatrixData< Type, N, M > & matrixObjective, const Type(&) values[N][M]) inline static
Sets the values of a matrix using a raw array.
Copies the values from the raw array into the matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows in the matrix.
M The number of columns in the matrix.
Parameters
matrixObjective The matrix to be set.
values The raw array containing the values to be copied into the matrix.
Definition at line 155 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    matrixObjective[i][j] = values[i][j];
        }
References GLESC::isIterable_v.
setMatrix() [3/3]
template<typename Type1 , typename Type2 , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::setMatrix (MatrixData< Type1, N, M > & leftMat, const MatrixData< Type2, N, M > & rightMat) inline static
Sets the values of a matrix using a raw array.
Copies the values from the raw array into the matrix. Works something like this: leftMat = rightMat;
Template Parameters
Type1 The data type of the matrix elements (e.g., float, double).
N The number of rows in the matrix.
M The number of columns in the matrix.
Parameters
leftMat The matrix to be set.
rightMat The raw array containing the values to be copied into the matrix.
Definition at line 141 of file MatrixAlgorithms.h.
{
            MatrixAlgorithms::copyMatrix(leftMat, rightMat);
        }
References copyMatrix(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::Matrix< Type, N, M >::Matrix(), and GLESC::Math::Matrix< Type, N, M >::operator=().
setMatrixDiagonal()
template<typename Type , size_t N> static void GLESC::Math::MatrixAlgorithms::setMatrixDiagonal (MatrixData< Type, N, N > & matrixObjective, const Type & value) inline static
Sets the diagonal of a matrix to a specific value.
Sets the diagonal of a matrix to a specific value. The matrix must be square.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows and columns of the matrix.
Parameters
matrixObjective The matrix to be set.
value The value to be set on the diagonal.
Definition at line 124 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                matrixObjective[i][i] = value;
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix(), GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot(), gaussianElimination(), GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrix(), and getTranslationMatrix().
setMatrixZero()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::setMatrixZero (MatrixData< Type, N, M > & matrixObjective) inline static
Sets the values of a matrix to zero.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrixObjective The matrix to be set.
Definition at line 97 of file MatrixAlgorithms.h.
{
            MatrixAlgorithms::fillMatrix(matrixObjective, Type(0));
        }
References fillMatrix(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Matrix< Type, N, M >::Matrix(), GLESC::Math::MatrixMixedAlgorithms::calculateModelMatrix(), GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot(), GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrix(), getScaleMatrix(), getTranslationMatrix(), and perspective().
swapRows()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::swapRows (MatrixData< Type, N, M > & matrix, size_t row1, size_t row2) inline static
Swaps two rows of a matrix.
Swaps two rows of a matrix. The rows are specified by their indices.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
row1 The index of the first row.
row2 The index of the second row.
Definition at line 79 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < M; ++i) {
                std::swap(matrix[row1][i], matrix[row2][i]);
            }
        }
References GLESC::isIterable_v.
Referenced by gaussianEliminationAlgorithm().
transpose()
template<typename Type , size_t N, size_t M> static void GLESC::Math::MatrixAlgorithms::transpose (const MatrixData< Type, N, M > & matrix, MatrixData< Type, M, N > & result) inline static
Transposes a matrix.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The number of rows of the matrix.
M The number of columns of the matrix.
Parameters
matrix The matrix.
result The result matrix.
Definition at line 599 of file MatrixAlgorithms.h.
{
            if constexpr (M == N)
                D_ASSERT_FALSE(&matrix == &result, "Cannot transpose matrix in place.");
            for (size_t i = 0; i < N; ++i)
                for (size_t j = 0; j < M; ++j)
                    result[j][i] = matrix[i][j]; // j,i becomes i,j, the numbers are mirrored
        }
References D_ASSERT_FALSE, and GLESC::isIterable_v.
Referenced by calculateNormalMatrix(), and GLESC::Math::Matrix< Type, N, M >::transpose().
transposeInPlace()
template<typename Type , size_t N> static void GLESC::Math::MatrixAlgorithms::transposeInPlace (MatrixData< Type, N, N > & matrix) inline static
Transposes a matrix in place.
Template Parameters
Type The data type of the matrix elements (e.g., float, double).
N The size of the square matrix
Parameters
matrix The matrix.
Definition at line 614 of file MatrixAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i)
                for (size_t j = i + 1; j < N; ++j)
                    std::swap(matrix[i][j], matrix[j][i]);
        }
References GLESC::isIterable_v.
Member Data Documentation
columnMajorMatrix
constexpr bool GLESC::Math::MatrixAlgorithms::columnMajorMatrix = true static constexpr
Defines if the matrix implementation is row-major.
Definition at line 33 of file MatrixAlgorithms.h.
Referenced by GLESC::Render::Frustum::extractPlanes(), matrixMatrixDiv(), matrixMatrixMulInPlace(), matrixMatrixMulNaiveInPlace(), GLESC::Math::Matrix< Type, N, M >::operator*(), and GLESC::Math::Matrix< Type, N, M >::operator*().
The documentation for this class was generated from the following file:
MatrixAlgorithms.h