GLESC: GLESC::Math::Vector< Type, N > Class Template Reference
GLESC::Math::Vector< Type, N > Class Template Reference
#include <Vector.h>
Public Types
using ValueType = Type
Public Member Functions
constexpr Vector () noexcept
Default constructor.
template<typename... Args, typename = std::enable_if_t<(sizeof...(Args) == N)>>
constexpr Vector (Args &&... args) noexcept
Variadic constructor.
constexpr Vector (const Type(&list)[N]) noexcept
Array constructor.
constexpr Vector (const Vector &other) noexcept
Copy constructor.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &&other) noexcept
Move constructor, for vectors of different sizes.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &other) noexcept
Copy constructor.
constexpr Vector (const VectorData< Type, N > &values) noexcept
Copy constructor for VectorData.
constexpr Vector (Type values) noexcept
Fill constructor.
constexpr Vector (Vector &&other) noexcept
Move constructor.
constexpr Vector (VectorData< Type, N > &&values) noexcept
Move constructor for VectorData.
Vector abs () const noexcept
Returns the absolute value of the vector.
Type angle (const Vector &other) const
Gives the rads between two vectors.
Type angleDegrees (const Vector &other) const
Gives the angle between two vectors in degrees.
Vector clamp (const Vector &min, const Vector &max) const
Clamps the vector to a given range.
Vector clamp (Type min, Type max) const
Clamps the vector to a given range.
Vector< Type, 3 > cross (const Vector< Type, 3 > &other) const
Calculates the cross product of two vectors.
Vector< Type, N - 1 > dehomogenize () const
Dehomogenizes the vector.
Type distance (const Vector &other) const
Gives the distance between two vectors.
Type distanceSquared (const Vector &other) const
Gives the squared distance between two vectors.
Type dot (const Vector &rhs) const
Returns the dot product of two vectors.
const Type & get (size_t index) const
Returns the data of the vector given an index.
Vector getOrthogonal () const
Get an orthogonal (or perpendicular) vector.
Type getW () const
Returns the w (fourth) value of the vector.
const Type & getX () const
Returns the x (first) value of the vector.
Type getY () const
Returns the y (second) value of the vector.
Type getZ () const
Returns the z (third) value of the vector.
Vector< Type, N+1 > homogenize () const
Homogenizes the vector.
bool isCollinear (const std::vector< Vector< Type, 3 > > &points) const
Checks if the current vector is a scalar multiple of some vectors.
Type isHomogeneous () const
Checks if the vector is homogeneous.
bool isMultipleOf (const Vector &other) const
Checks if the current vector is a scalar multiple of another vector.
bool isNormalized () const
checks if the vector is normalized
bool isOrthogonal (const Vector &other) const
Checks if the vector is orthogonal to another vector.
bool isParallel (const Vector &other) const
Checks if the vector is parallel to another vector.
bool isZero () const
Checks if the vector is a zero vector.
Type length () const
Returns the length of the vector.
Type lengthSquared () const
Returns the squared length of the vector.
Vector lerp (const Vector &other, Type factor) const
Calculates the linear interpolation between two vectors using a factor.
Type magnitude () const
Returns the length of the vector.
Vector & makeForward (const Vector &rotation)
Returs the forward vector of a rotation.
Vector & makeRight (const Vector &rotation)
Returns the right vector of a rotation.
Vector & makeUp (const Vector &rotation)
Returns the up vector of a rotation.
Vector mod (Type divisor) const
Returns the mod of the vector given a divisor.
Vector mod (Vector divisors) const
Returns the mod of the vector given a vector of divisors.
Vector & normalize ()
Normalizes the vector.
Vector normalize () const
Normalizes the vector.
constexpr bool operator!= (const Vector &rhs) const
Inequality operator for vectors.
constexpr Vector operator* (const Vector &rhs) const
Overloads the '*' operator for vector multiplication.
constexpr Vector operator* (Type scalar) const
Overloads the '*' operator for scalar multiplication.
constexpr Vector operator*= (const Type scalar)
In-place multiplication with a scalar.
constexpr Vector operator*= (const Vector &rhs)
In-place multiplication with another vector.
constexpr Vector operator+ (const Type &scalar) const
Overloads the '+' operator for scalar addition.
constexpr Vector operator+ (const Vector &rhs) const
Overloads the '+' operator for vector addition.
constexpr Vector operator+= (const Vector &rhs)
In-place addition with another vector.
constexpr Vector operator+= (Type scalar)
In-place addition with a scalar.
constexpr Vector operator- () const
Overloads the unary '-' operator for negation.
constexpr Vector operator- (const Type &scalar) const
Overloads the '-' operator for scalar subtraction.
constexpr Vector operator- (const Vector &rhs) const
Overloads the '-' operator for vector subtraction.
constexpr Vector operator-= (const Type scalar)
In-place subtraction with a scalar.
constexpr Vector operator-= (const Vector &rhs)
In-place subtraction with another vector.
constexpr Vector operator/ (const Vector &rhs) const
Overloads the '/' operator for vector division.
constexpr Vector operator/ (Type scalar) const
Overloads the '/' operator for scalar division.
constexpr Vector operator/= (const Type scalar)
In-place division with a scalar.
constexpr Vector operator/= (const Vector &rhs)
In-place division with another vector.
constexpr bool operator< (const Vector &rhs) const
Less than operator for vectors.
constexpr bool operator<= (const Vector &rhs) const
Less than or equal to operator for vectors.
constexpr Vector & operator= (const Type(&list)[N]) noexcept
Array assignment operator.
constexpr Vector & operator= (const Vector &other) noexcept
Copy assignment operator.
constexpr Vector & operator= (Vector &&other) noexcept
Move assignment operator.
template<typename OtherType >
constexpr bool operator== (const Vector< OtherType, N > &rhs) const
Equality operator for vectors.
constexpr bool operator> (const Vector &rhs) const
Greater than operator for vectors.
constexpr bool operator>= (const Vector &rhs) const
Greater than or equal to operator for vectors.
Type & operator[] (size_t index)
Returns the data of the vector given an index.
const Type & operator[] (size_t index) const
Returns the data of the vector given an index, const version (read only)
Vector project (const Vector &other) const
Projects the vector onto another vector.
Vector & reflect (const Vector &normal)
Reflects the vector by a given normal, modifying the current vector.
Vector reflect (const Vector &normal) const
Reflects the vector by a given normal.
Vector< Type, 3 > & rotate (const Vector< Type, 3 > &rotation)
Rotates the vector by a given rotation.
Vector< Type, 3 > rotate (const Vector< Type, 3 > &rotation) const
Rotates the vector by a given rotation.
void set (size_t index, Type value)
Sets the data of the vector given an index.
void setW (Type value)
Sets the w (fourth) value of the vector.
void setX (Type value)
Sets the x (first) value of the vector.
void setY (Type value)
Sets the y (second) value of the vector.
void setZ (Type value)
Sets the z (third) value of the vector.
int size () const
Returns the size of the vector.
Type sum () const
Returns the sum of all the elements in the vector.
void swap (Vector &other) noexcept
Swaps the data of this vector with another vector.
Vector toDegrees () const
Converts the vector to degrees.
MatrixData< Type, N, 1 > toMatrix () const
Converts the vector to a single column matrix.
Vector toRads () const
Converts the vector to radians.
std::string toString () const
Converts the vector to string.
Vector & vectorToEulerRotation (const Vector &up)
Converts the vector to euler angles.
Vector vectorToEulerRotation (const Vector &up) const
Converts the vector to euler angles.
Type & w ()
Returns the w (fourth) value of the vector.
void w (Type value)
Sets the w (fourth) value of the vector.
Type & x ()
Returns the x (reference) value of the vector.
void x (Type value)
Sets the x (first) value of the vector.
Type & y ()
Returns the y (second) value of the vector.
void y (Type value)
Sets the y (second) value of the vector.
Type & z ()
Returns the z (third) value of the vector.
void z (Type value)
Sets the z (third) value of the vector.
Public Attributes
VectorData< Type, N > data
Data of the vector.
Detailed Description
template<typename Type, size_t N>
class GLESC::Math::Vector< Type, N >
Definition at line 25 of file Vector.h.
Member Typedef Documentation
ValueType
template<typename Type , size_t N> using GLESC::Math::Vector< Type, N >::ValueType = Type
Definition at line 27 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector () inline constexpr noexcept
Default constructor.
Initializes the vector with zeroes
Definition at line 36 of file Vector.h.
{
            VectorAlgorithms::vectorZero(data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorZero().
Vector() [2/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (const Type(&) list[N]) inline constexpr noexcept
Array constructor.
Initializes the vector with the values from the array
Parameters
list The array of values to initialize the vector with
Definition at line 45 of file Vector.h.
{
            VectorAlgorithms::vectorInitRawArray(data, list);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorInitRawArray().
Vector() [3/10]
template<typename Type , size_t N> template<typename... Args, typename = std::enable_if_t<(sizeof...(Args) == N)>> constexpr GLESC::Math::Vector< Type, N >::Vector (Args &&... args) inline constexpr noexcept
Variadic constructor.
Initializes the vector with the values from the variadic arguments. This means that this constructor can be called with any number of arguments. This constructor is only enabled if the number of arguments is equal to the dimension of the vector.
Template Parameters
Args
Parameters
args
Definition at line 59 of file Vector.h.
                                                  : data{args...} {
        }
References GLESC::isIterable_v.
Vector() [4/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (Type values) inline constexpr noexcept
Fill constructor.
Initializes all the values of the vector with the given value
Parameters
values
Definition at line 68 of file Vector.h.
{
            VectorAlgorithms::vectorFill(data, values);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorFill().
Vector() [5/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (VectorData< Type, N > && values) inline constexpr noexcept
Move constructor for VectorData.
See also
VectorData
Parameters
values The VectorData to move from
Definition at line 77 of file Vector.h.
{
            VectorAlgorithms::vectorMove(data, values);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorMove().
Vector() [6/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (const VectorData< Type, N > & values) inline constexpr noexcept
Copy constructor for VectorData.
See also
VectorData
Parameters
values The VectorData to copy from
Definition at line 86 of file Vector.h.
{
            VectorAlgorithms::vectorCopy(data, values);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorCopy().
Vector() [7/10]
template<typename Type , size_t N> template<size_t N2> constexpr GLESC::Math::Vector< Type, N >::Vector (const Vector< Type, N2 > & other) inline constexpr noexcept
Copy constructor.
Copies the data from the other vector to this one
Parameters
other The vector to copy from
Definition at line 97 of file Vector.h.
{
            VectorAlgorithms::vectorFill(data, Type{0});
            VectorAlgorithms::vectorCopy(data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, GLESC::Math::VectorAlgorithms::vectorCopy(), and GLESC::Math::VectorAlgorithms::vectorFill().
Vector() [8/10]
template<typename Type , size_t N> template<size_t N2> constexpr GLESC::Math::Vector< Type, N >::Vector (const Vector< Type, N2 > && other) inline constexpr noexcept
Move constructor, for vectors of different sizes.
Moves the data from the other vector to this one
Parameters
other The vector to move from
Definition at line 108 of file Vector.h.
{
            VectorAlgorithms::vectorFill(data, Type{0});
            VectorAlgorithms::vectorMove(data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, GLESC::Math::VectorAlgorithms::vectorFill(), and GLESC::Math::VectorAlgorithms::vectorMove().
Vector() [9/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (const Vector< Type, N > & other) inline constexpr noexcept
Copy constructor.
Copies the data from the other vector to this one
Parameters
other The vector to copy from
Definition at line 118 of file Vector.h.
{
            VectorAlgorithms::vectorCopy(data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorCopy().
Vector() [10/10]
template<typename Type , size_t N> constexpr GLESC::Math::Vector< Type, N >::Vector (Vector< Type, N > && other) inline constexpr noexcept
Move constructor.
Moves the data from the other vector to this one
Parameters
other The vector to move from
Definition at line 127 of file Vector.h.
{
            VectorAlgorithms::vectorMove(data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorMove().
Member Function Documentation
abs()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::abs () const inline noexcept
Returns the absolute value of the vector.
The absolute value of a vector is a vector where each component is the absolute
Returns
The absolute value of the vector
Definition at line 766 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::abs(this->data, result.data);
            return result;
        }
References GLESC::Math::VectorAlgorithms::abs(), and GLESC::Math::Vector< Type, N >::data.
angle()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::angle (const Vector< Type, N > & other) const inline
Gives the rads between two vectors.
Parameters
other The vector to calculate the angle to
Returns
The angle between the two vectors
Definition at line 692 of file Vector.h.
{
            return VectorAlgorithms::angle(this->data, other.data);
        }
References GLESC::Math::VectorAlgorithms::angle(), and GLESC::Math::Vector< Type, N >::data.
angleDegrees()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::angleDegrees (const Vector< Type, N > & other) const inline
Gives the angle between two vectors in degrees.
Parameters
other The vector to calculate the angle to
Returns
The angle between the two vectors in degrees
Definition at line 701 of file Vector.h.
{
            return Math::degrees(VectorAlgorithms::angle(this->data, other.data));
        }
References GLESC::Math::VectorAlgorithms::angle(), GLESC::Math::Vector< Type, N >::data, and GLESC::Math::degrees().
clamp() [1/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::clamp (const Vector< Type, N > & min, const Vector< Type, N > & max) const inline
Clamps the vector to a given range.
Parameters
min The minimum values of the range
max The maximum values of the range
Returns
The clamped vector
Definition at line 723 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::clampWithVectors(this->data, min.data, max.data, result.data);
            return result;
        }
References GLESC::Math::VectorAlgorithms::clampWithVectors(), GLESC::Math::Vector< Type, N >::data, and GLESC::Math::max().
clamp() [2/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::clamp (Type min, Type max) const inline
Clamps the vector to a given range.
Parameters
min The minimum value of the range
max The maximum value of the range
Returns
The clamped vector
Definition at line 711 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::clampWithValues(this->data, min, max, result.data);
            return result;
        }
References GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::Vector< Type, N >::data, and GLESC::Math::max().
cross()
template<typename Type , size_t N> Vector< Type, 3 > GLESC::Math::Vector< Type, N >::cross (const Vector< Type, 3 > & other) const inline
Calculates the cross product of two vectors.
The cross product is a vector that is perpendicular to the plane formed by the two vectors. Only works for 3 dimensional vectors.
Parameters
other
Returns
Definition at line 1126 of file Vector.h.
{
            Vector<Type, 3> result;
            VectorAlgorithms::crossProduct(this->data, other.data, result.data);
            return result;
        }
References GLESC::Math::VectorAlgorithms::crossProduct(), and GLESC::Math::Vector< Type, N >::data.
Referenced by GLESC::Math::Plane::calculateDistanceFromPointAndLine(), GLESC::Render::Mesh< VertexT >::calculateNormal(), GLESC::Math::Plane::calculateNormalFromPointAndLine(), GLESC::Math::Plane::calculateNormalFromPoints(), GLESC::Math::Line::distance(), and GLESC::Math::Line::intersects().
dehomogenize()
template<typename Type , size_t N> Vector< Type, N - 1 > GLESC::Math::Vector< Type, N >::dehomogenize () const inline
Dehomogenizes the vector.
Dehomogenizing a vector means dividing each component of the vector by the last component of the vector.
Returns
The dehomogenized vector (a vector with one less component)
Definition at line 918 of file Vector.h.
{
            Vector<Type, N - 1> result;
            VectorAlgorithms::dehomogenize(this->data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::Math::VectorAlgorithms::dehomogenize(), and GLESC::isIterable_v.
Referenced by GLESC::Transform::Transformer::clipToNDC().
distance()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::distance (const Vector< Type, N > & other) const inline
Gives the distance between two vectors.
Parameters
other The vector to calculate the distance to
Returns
The distance between the two vectors
Definition at line 674 of file Vector.h.
{
            return VectorAlgorithms::distance(this->data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::distance().
Referenced by GLESC::Engine::update().
distanceSquared()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::distanceSquared (const Vector< Type, N > & other) const inline
Gives the squared distance between two vectors.
Parameters
other The vector to calculate the squared distance to
Returns
The squared distance between the two vectors
Definition at line 683 of file Vector.h.
{
            return VectorAlgorithms::distanceSquared(this->data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::distanceSquared().
dot()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::dot (const Vector< Type, N > & rhs) const inline
Returns the dot product of two vectors.
The dot product of two vectors is a scalar value that represents the projection of one vector onto the other.
Parameters
rhs The vector to calculate the dot product with
Returns
The dot product of the two vectors
Definition at line 827 of file Vector.h.
{
            return VectorAlgorithms::dotProduct(this->data, rhs.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::dotProduct().
Referenced by GLESC::Math::Plane::calculateDistanceFromPointAndLine(), GLESC::Math::Plane::calculateDistanceFromPointAndNormal(), GLESC::Math::Plane::calculateDistanceFromPoints(), GLESC::Math::Plane::distanceToPoint(), GLESC::Math::Plane::intersects(), GLESC::Math::PolyhedronFace::intersects(), GLESC::Math::Plane::intersects(), and GLESC::Math::Plane::operator==().
get()
template<typename Type , size_t N> const Type & GLESC::Math::Vector< Type, N >::get (size_t index) const inline
Returns the data of the vector given an index.
This is the same as operator[] but it's more explicit (it's const, read only)
Parameters
index
Returns
Definition at line 161 of file Vector.h.
{
            return data[index];
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
Referenced by GLESC::Transform::Transform::addPosition(), GLESC::Transform::Transform::addRotation(), and GLESC::Transform::Transform::addScale().
getOrthogonal()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::getOrthogonal () const inline
Get an orthogonal (or perpendicular) vector.
Returns
A new vector that is orthogonal to this one. If the vector has more than 2 dimensions, the axis of orthogonality is chosen arbitrarily.
Definition at line 1082 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::getOrthogonal(this->data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::getOrthogonal().
getW()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::getW () const inline
Returns the w (fourth) value of the vector.
This is a getter for the w (fourth) value of the vector.
Returns
The w (fourth) value of the vector
Definition at line 327 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(4);
            return data[3];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
getX()
template<typename Type , size_t N> const Type & GLESC::Math::Vector< Type, N >::getX () const inline
Returns the x (first) value of the vector.
This is a getter for the x (first) value of the vector.
Returns
The x (first) value of the vector
Definition at line 204 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(1);
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Referenced by GLESC::Input::InputManager::getAvgMousePos(), GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::Math::Plane::hasInside(), GLESC::Math::BoundingVolume::hasInside(), and GLESC::Transform::Interpolator::interpolate().
getY()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::getY () const inline
Returns the y (second) value of the vector.
This is a getter for the y (second) value of the vector.
Returns
The y (second) value of the vector
Definition at line 245 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(2);
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Referenced by GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::Math::Plane::hasInside(), GLESC::Math::BoundingVolume::hasInside(), and GLESC::Transform::Interpolator::interpolate().
getZ()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::getZ () const inline
Returns the z (third) value of the vector.
This is a getter for the z (third) value of the vector.
Returns
The z (third) value of the vector
Definition at line 286 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(3);
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Referenced by GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::Math::Plane::hasInside(), GLESC::Math::BoundingVolume::hasInside(), and GLESC::Transform::Interpolator::interpolate().
homogenize()
template<typename Type , size_t N> Vector< Type, N+1 > GLESC::Math::Vector< Type, N >::homogenize () const inline
Homogenizes the vector.
Homogenizing a vector means adding a 1 as the last component of the vector.
Returns
The homogenized vector (a vector with one more component)
Definition at line 906 of file Vector.h.
{
            Vector<Type, N + 1> result;
            VectorAlgorithms::homogenize(this->data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::homogenize().
Referenced by GLESC::Transform::Transformer::transformVector(), and GLESC::Transform::Transformer::worldToViewport().
isCollinear()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isCollinear (const std::vector< Vector< Type, 3 > > & points) const inline
Checks if the current vector is a scalar multiple of some vectors.
Parameters
points The vectors to compare against
Returns
true If the current vector is a scalar multiple of all the other vectors.
Definition at line 1105 of file Vector.h.
{
            // Create a vector of pointers to the data of each point
            std::vector<const VectorData<Type, 3>*> pointData;
            for (const auto& point : points) {
                pointData.push_back(&point.data);
            }
            // Call the areCollinear function with the reference point's data and the vector of data pointers
            return VectorMixedAlgorithms::areCollinear(this->data, pointData);
        }
References GLESC::Math::VectorMixedAlgorithms::areCollinear(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
isHomogeneous()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::isHomogeneous () const inline
Checks if the vector is homogeneous.
A homogeneous vector is a vector whose last component is not equal to zero.
Returns
True if the vector is homogeneous, false otherwise
Definition at line 897 of file Vector.h.
{
            return VectorAlgorithms::isHomogeneous(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::isHomogeneous().
Referenced by TYPED_TEST().
isMultipleOf()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isMultipleOf (const Vector< Type, N > & other) const inline
Checks if the current vector is a scalar multiple of another vector.
Parameters
other The vector to compare against.
Returns
true If the current vector is a scalar multiple of the other vector.
false Otherwise.
Definition at line 1096 of file Vector.h.
{
            return VectorAlgorithms::isMultipleOf(this->data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::isMultipleOf().
isNormalized()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isNormalized () const inline
checks if the vector is normalized
A normalized vector is a vector whose length is equal to 1.
Returns
True if the vector is normalized, false otherwise
Definition at line 879 of file Vector.h.
{
            return VectorAlgorithms::isNormalized(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::isNormalized().
isOrthogonal()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isOrthogonal (const Vector< Type, N > & other) const inline
Checks if the vector is orthogonal to another vector.
Two vectors are orthogonal if their dot product is zero.
Parameters
other The vector to compare against
Returns
True if the vectors are orthogonal, false otherwise
Definition at line 1073 of file Vector.h.
{
            return VectorAlgorithms::areOrthogonal(this->data, other.data);
        }
References GLESC::Math::VectorAlgorithms::areOrthogonal(), and GLESC::Math::Vector< Type, N >::data.
isParallel()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isParallel (const Vector< Type, N > & other) const inline
Checks if the vector is parallel to another vector.
Two vectors are parallel if they have the same direction or are scalar multiples of each other.
Parameters
other The vector to compare against
Returns
True if the vectors are parallel, false otherwise
Definition at line 1063 of file Vector.h.
{
            return VectorAlgorithms::areParallel(this->data, other.data);
        }
References GLESC::Math::VectorAlgorithms::areParallel(), and GLESC::Math::Vector< Type, N >::data.
Referenced by GLESC::Math::Plane::intersects().
isZero()
template<typename Type , size_t N> bool GLESC::Math::Vector< Type, N >::isZero () const inline
Checks if the vector is a zero vector.
Returns
True if the vector is a zero vector, false otherwise
Definition at line 665 of file Vector.h.
{
            return VectorAlgorithms::isZero(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::isZero().
length()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::length () const inline
Returns the length of the vector.
The length of a vector is the square root of the sum of the squares of its components.
Returns
The length of the vector
Definition at line 837 of file Vector.h.
{
            return VectorAlgorithms::length(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::length().
Referenced by GLESC::Physics::PhysicsManager::handleCollisions(), GLESC::Math::Plane::normalize(), GLESC::SoundPlayer::play3DSound(), and GLESC::Transform::Interpolator::pushTransform().
lengthSquared()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::lengthSquared () const inline
Returns the squared length of the vector.
The squared length of a vector is the sum of the squares of its components.
Returns
The squared length of the vector
Definition at line 888 of file Vector.h.
{
            return VectorAlgorithms::lengthSquared(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::lengthSquared().
Referenced by GLESC::Math::Sphere::intersects().
lerp()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::lerp (const Vector< Type, N > & other, Type factor) const inline
Calculates the linear interpolation between two vectors using a factor.
The linear interpolation between two vectors is a vector where each component is the linear interpolation of the corresponding components of the two vectors.
Parameters
other The other vector to interpolate with
factor The factor to use for the interpolation
Returns
The linear interpolation between the two vectors
Definition at line 806 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::lerp(this->data, other.data, factor, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::lerp().
Referenced by GLESC::Transform::Interpolator::interpolate().
magnitude()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::magnitude () const inline
Returns the length of the vector.
The length of a vector is the square root of the sum of the squares of its components.
Returns
The length of the vector
Definition at line 847 of file Vector.h.
{
            return VectorAlgorithms::length(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::length().
makeForward()
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::makeForward (const Vector< Type, N > & rotation) inline
Returs the forward vector of a rotation.
The forward vector of a rotation is the vector that points in the direction of an object that has been rotated by the given rotation.
Parameters
rotation The rotation to get the forward vector from
Returns
The forward vector of the rotation
Definition at line 945 of file Vector.h.
{
            VectorAlgorithms::makeForwardVector(rotation.data, this->data);
            return *this;
        }
References GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::makeForwardVector().
Referenced by GLESC::Transform::Transform::calculateForward().
makeRight()
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::makeRight (const Vector< Type, N > & rotation) inline
Returns the right vector of a rotation.
The right vector of a rotation is the vector that points to the right of an object that has been rotated by the given rotation.
Parameters
rotation The rotation to get the right vector from
Returns
The right vector of the rotation
Definition at line 957 of file Vector.h.
{
            VectorAlgorithms::makeRightVector(rotation.data, this->data);
            return *this;
        }
References GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::makeRightVector().
Referenced by GLESC::Transform::Transform::calculateRight().
makeUp()
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::makeUp (const Vector< Type, N > & rotation) inline
Returns the up vector of a rotation.
The up vector of a rotation is the vector that points up from an object that has been rotated by the given rotation.
Parameters
rotation The rotation to get the up vector from
Returns
The up vector of the rotation
Definition at line 969 of file Vector.h.
{
            VectorAlgorithms::makeUpVector(rotation.data, this->data);
            return *this;
        }
References GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::makeUpVector().
Referenced by GLESC::Transform::Transform::calculateUp().
mod() [1/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::mod (Type divisor) const inline
Returns the mod of the vector given a divisor.
The mod of a vector is a vector where each component is the remainder of the division of the component by the divisor.
Parameters
divisor The divisor to use
Returns
The mod of the vector
Definition at line 779 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::modWithValue(this->data, divisor, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::modWithValue().
mod() [2/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::mod (Vector< Type, N > divisors) const inline
Returns the mod of the vector given a vector of divisors.
The mod of a vector is a vector where each component is the remainder of the division of the component by the corresponding divisor.
Parameters
divisors The vector of divisors to use
Returns
The mod of the vector
Definition at line 792 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::modWithVector(this->data, divisors.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::modWithVector().
normalize() [1/2]
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::normalize () inline
Normalizes the vector.
Normalizing a vector means dividing each component of the vector by the length of the vector. Modifies the vector in place.
Returns
A reference to this vector after the operation
Definition at line 857 of file Vector.h.
{
            VectorAlgorithms::normalize(this->data, data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::normalize().
Referenced by GLESC::Math::PolyhedronFace::intersects(), GLESC::Math::Line::setDirection(), and GLESC::Math::Line::setDirectionFromPoints().
normalize() [2/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::normalize () const inline
Normalizes the vector.
Normalizing a vector means dividing each component of the vector by the length of the vector.
Returns
The normalized vector
Definition at line 868 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::normalize(this->data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::normalize().
operator!=()
template<typename Type , size_t N> constexpr bool GLESC::Math::Vector< Type, N >::operator!= (const Vector< Type, N > & rhs) const inline constexpr
Inequality operator for vectors.
Utilizes the equality operator for the actual comparison
Parameters
rhs Vector to compare against
Returns
True if the vectors are not equal, false otherwise
Definition at line 602 of file Vector.h.
{
            return VectorAlgorithms::neq(this->data, rhs.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::neq().
operator*() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator* (const Vector< Type, N > & rhs) const inline constexpr
Overloads the '*' operator for vector multiplication.
Multiplies the corresponding data of two vectors
Parameters
rhs The right-hand-side vector to multiply by
Returns
A new vector containing the result
Definition at line 575 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorMul(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorMul().
operator*() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator* (Type scalar) const inline constexpr
Overloads the '*' operator for scalar multiplication.
Multiplies each component of the vector by a scalar
Parameters
scalar The scalar value to multiply by
Returns
A new vector containing the result
Definition at line 563 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorScalarMul(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
operator*=() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator*= (const Type scalar) inline constexpr
In-place multiplication with a scalar.
Multiplies each element of this vector by the scalar value.
Parameters
scalar The scalar value to multiply with
Returns
A reference to this vector after the operation
Definition at line 431 of file Vector.h.
{
            VectorAlgorithms::vectorScalarMul(this->data, scalar, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarMul().
operator*=() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator*= (const Vector< Type, N > & rhs) inline constexpr
In-place multiplication with another vector.
Multiplies the elements of this vector with the elements of the given vector element-wise.
Parameters
rhs The vector to multiply with
Returns
A reference to this vector after the operation
Definition at line 443 of file Vector.h.
{
            VectorAlgorithms::vectorMul(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorMul().
operator+() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator+ (const Type & scalar) const inline constexpr
Overloads the '+' operator for scalar addition.
Adds a scalar to each component of the vector
Parameters
scalar The scalar value to add
Returns
A new vector containing the result
Definition at line 480 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorScalarAdd(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarAdd().
operator+() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator+ (const Vector< Type, N > & rhs) const inline constexpr
Overloads the '+' operator for vector addition.
Adds the corresponding data of two vectors
Parameters
rhs The right-hand-side vector to add
Returns
A new vector containing the result
Definition at line 492 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorAdd(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorAdd().
operator+=() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator+= (const Vector< Type, N > & rhs) inline constexpr
In-place addition with another vector.
Adds the elements of the given vector to this vector element-wise.
Parameters
rhs The vector to add
Returns
A reference to this vector after the operation
Definition at line 387 of file Vector.h.
{
            VectorAlgorithms::vectorAdd(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorAdd().
operator+=() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator+= (Type scalar) inline constexpr
In-place addition with a scalar.
Adds the scalar value to each element of this vector.
Parameters
scalar The scalar value to add
Returns
A reference to this vector after the operation
Definition at line 398 of file Vector.h.
{
            VectorAlgorithms::vectorScalarAdd(this->data, scalar, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarAdd().
operator-() [1/3]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator- () const inline constexpr
Overloads the unary '-' operator for negation.
Negates each component of the vector
Returns
A new vector containing the result
Definition at line 503 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorNegate(this->data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorNegate().
operator-() [2/3]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator- (const Type & scalar) const inline constexpr
Overloads the '-' operator for scalar subtraction.
Subtracts a scalar from each component of the vector
Parameters
scalar The scalar value to subtract
Returns
A new vector containing the result
Definition at line 515 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorScalarSub(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarSub().
operator-() [3/3]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator- (const Vector< Type, N > & rhs) const inline constexpr
Overloads the '-' operator for vector subtraction.
Subtracts the corresponding data of two vectors
Parameters
rhs The right-hand-side vector to subtract
Returns
A new vector containing the result
Definition at line 527 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorSub(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorSub().
operator-=() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator-= (const Type scalar) inline constexpr
In-place subtraction with a scalar.
Subtracts the scalar value from each element of this vector.
Parameters
scalar The scalar value to subtract
Returns
A reference to this vector after the operation
Definition at line 420 of file Vector.h.
{
            VectorAlgorithms::vectorScalarSub(this->data, scalar, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarSub().
operator-=() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator-= (const Vector< Type, N > & rhs) inline constexpr
In-place subtraction with another vector.
Subtracts the elements of the given vector from this vector element-wise.
Parameters
rhs The vector to subtract
Returns
A reference to this vector after the operation
Definition at line 409 of file Vector.h.
{
            VectorAlgorithms::vectorSub(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorSub().
operator/() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator/ (const Vector< Type, N > & rhs) const inline constexpr
Overloads the '/' operator for vector division.
Divides the corresponding data of two vectors
Parameters
rhs The right-hand-side vector to divide by
Returns
A new vector containing the result
Definition at line 551 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorDiv(this->data, rhs.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorDiv().
operator/() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator/ (Type scalar) const inline constexpr
Overloads the '/' operator for scalar division.
Divides each component of the vector by a scalar
Parameters
scalar The scalar value to divide by
Returns
A new vector containing the result
Definition at line 539 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorScalarDiv(this->data, scalar, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarDiv().
operator/=() [1/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator/= (const Type scalar) inline constexpr
In-place division with a scalar.
Divides each element of this vector by the scalar value.
Parameters
scalar The scalar value to divide by
Returns
A reference to this vector after the operation
Definition at line 454 of file Vector.h.
{
            VectorAlgorithms::vectorScalarDiv(this->data, scalar, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorScalarDiv().
operator/=() [2/2]
template<typename Type , size_t N> constexpr Vector GLESC::Math::Vector< Type, N >::operator/= (const Vector< Type, N > & rhs) inline constexpr
In-place division with another vector.
Divides the elements of this vector by the elements of the given vector element-wise.
Parameters
rhs The vector to divide by
Returns
A reference to this vector after the operation
Definition at line 466 of file Vector.h.
{
            VectorAlgorithms::vectorDiv(this->data, rhs.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorDiv().
operator<()
template<typename Type , size_t N> constexpr bool GLESC::Math::Vector< Type, N >::operator< (const Vector< Type, N > & rhs) const inline constexpr
Less than operator for vectors.
Compares vectors using their lengths
Parameters
rhs Vector to compare against
Returns
True if this vector's length is less than rhs's length, false otherwise
Definition at line 612 of file Vector.h.
{
            return VectorAlgorithms::lt(this->data, rhs.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::lt().
operator<=()
template<typename Type , size_t N> constexpr bool GLESC::Math::Vector< Type, N >::operator<= (const Vector< Type, N > & rhs) const inline constexpr
Less than or equal to operator for vectors.
Derived from the greater-than operator
Parameters
rhs Vector to compare against
Returns
True if this vector is less than or equal to rhs, false otherwise
Definition at line 632 of file Vector.h.
{
            return *this < rhs || *this == rhs;
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator>().
operator=() [1/3]
template<typename Type , size_t N> constexpr Vector & GLESC::Math::Vector< Type, N >::operator= (const Type(&) list[N]) inline constexpr noexcept
Array assignment operator.
Assigns the values from the array to this vector
Parameters
list
Returns
A reference to this vector
Definition at line 376 of file Vector.h.
{
            VectorAlgorithms::vectorInitRawArray(data, list);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorInitRawArray().
operator=() [2/3]
template<typename Type , size_t N> constexpr Vector & GLESC::Math::Vector< Type, N >::operator= (const Vector< Type, N > & other) inline constexpr noexcept
Copy assignment operator.
Copies the data from the other vector to this one
Parameters
other
Returns
A reference to this vector
Definition at line 354 of file Vector.h.
{
            VectorAlgorithms::vectorCopy(data, other.data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorCopy().
Referenced by GLESC::Render::ColorRgbNorm::operator=().
operator=() [3/3]
template<typename Type , size_t N> constexpr Vector & GLESC::Math::Vector< Type, N >::operator= (Vector< Type, N > && other) inline constexpr noexcept
Move assignment operator.
Moves the data from the other vector to this one
Parameters
other The vector to move from
Returns
A reference to this vector
Definition at line 365 of file Vector.h.
{
            VectorAlgorithms::vectorMove(data, other.data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorMove().
operator==()
template<typename Type , size_t N> template<typename OtherType > constexpr bool GLESC::Math::Vector< Type, N >::operator== (const Vector< OtherType, N > & rhs) const inline constexpr
Equality operator for vectors.
Compares this vector to another, allowing for different underlying types. Handles floating-point comparison via 'eq' function.
Parameters
rhs Vector to compare against
Returns
True if the vectors are equal, false otherwise
Definition at line 592 of file Vector.h.
{
            return VectorAlgorithms::eq(this->data, rhs.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::eq().
Referenced by GLESC::Render::ColorRgbaNorm::operator==(), and GLESC::Render::ColorRgbNorm::operator==().
operator>()
template<typename Type , size_t N> constexpr bool GLESC::Math::Vector< Type, N >::operator> (const Vector< Type, N > & rhs) const inline constexpr
Greater than operator for vectors.
Derived from the less-than-or-equal operator
Parameters
rhs Vector to compare against
Returns
True if this vector is greater than rhs, false otherwise
Definition at line 622 of file Vector.h.
{
            return !(this->operator<=(rhs));
        }
References GLESC::Math::Vector< Type, N >::operator<=().
operator>=()
template<typename Type , size_t N> constexpr bool GLESC::Math::Vector< Type, N >::operator>= (const Vector< Type, N > & rhs) const inline constexpr
Greater than or equal to operator for vectors.
Derived from the less-than operator
Parameters
rhs Vector to compare against
Returns
True if this vector is greater than or equal to rhs, false otherwise
Definition at line 642 of file Vector.h.
{
            return !(*this < rhs);
        }
References GLESC::isIterable_v.
operator[]() [1/2]
template<typename Type , size_t N> Type & GLESC::Math::Vector< Type, N >::operator[] (size_t index) inline
Returns the data of the vector given an index.
Parameters
index The index of the data to return
Returns
The data of the vector at the given index
Definition at line 142 of file Vector.h.
{
            return data[index];
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
operator[]() [2/2]
template<typename Type , size_t N> const Type & GLESC::Math::Vector< Type, N >::operator[] (size_t index) const inline
Returns the data of the vector given an index, const version (read only)
Parameters
index
Returns
Definition at line 151 of file Vector.h.
{
            return data[index];
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
project()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::project (const Vector< Type, N > & other) const inline
Projects the vector onto another vector.
The projection of a vector onto another vector is the vector that results from projecting the first vector onto the second vector.
Parameters
other The vector to project onto
Returns
The projected vector
Definition at line 932 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::project(this->data, other.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::project().
Referenced by GLESC::Math::Sphere::intersects().
reflect() [1/2]
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::reflect (const Vector< Type, N > & normal) inline
Reflects the vector by a given normal, modifying the current vector.
Reflecting a vector means reflecting the vector by a given normal.
Parameters
normal The normal to reflect the vector by
Returns
A reference to this vector after the operation
Definition at line 1004 of file Vector.h.
{
            VectorAlgorithms::reflect(this->data, normal.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::reflect().
Referenced by GLESC::Physics::getBouncingVelocity().
reflect() [2/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::reflect (const Vector< Type, N > & normal) const inline
Reflects the vector by a given normal.
Reflecting a vector means reflecting the vector by a given normal.
Parameters
normal The normal to reflect the vector by
Returns
The reflected vector
Definition at line 1015 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::reflect(this->data, normal.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::reflect().
rotate() [1/2]
template<typename Type , size_t N> Vector< Type, 3 > & GLESC::Math::Vector< Type, N >::rotate (const Vector< Type, 3 > & rotation) inline
Rotates the vector by a given rotation.
Rotating a vector means applying a rotation to the vector.
Parameters
rotation The rotation to apply
Returns
A reference to this vector after the operation
Definition at line 980 of file Vector.h.
{
            VectorAlgorithms::rotateVector3D(this->data, rotation.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::rotateVector3D().
Referenced by GLESC::Transform::Transformer::rotateMesh().
rotate() [2/2]
template<typename Type , size_t N> Vector< Type, 3 > GLESC::Math::Vector< Type, N >::rotate (const Vector< Type, 3 > & rotation) const inline
Rotates the vector by a given rotation.
Rotating a vector means applying a rotation to the vector.
Parameters
rotation The rotation to apply
Returns
The rotated vector
Definition at line 991 of file Vector.h.
{
            Vector<Type, 3> result;
            VectorAlgorithms::rotateVector3D(this->data, rotation.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::rotateVector3D().
set()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::set (size_t index, Type value) inline
Sets the data of the vector given an index.
This is the same as operator[] but it's more explicit. Because it's a normal setter.
Parameters
index
value
Definition at line 172 of file Vector.h.
{
            data[index] = value;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
Referenced by GLESC::Transform::Transform::setPosition(), GLESC::Transform::Transform::setRotation(), and GLESC::Transform::Transform::setScale().
setW()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::setW (Type value) inline
Sets the w (fourth) value of the vector.
This works as a setter for the w (fourth) value of the vector.
Parameters
value The value to set
Definition at line 337 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(4);
            data[3] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
setX()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::setX (Type value) inline
Sets the x (first) value of the vector.
This works as a setter but for the x (first) value of the vector.
Parameters
value The value to set
Definition at line 214 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(1);
            data[0] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
setY()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::setY (Type value) inline
Sets the y (second) value of the vector.
This works as a setter for the y (second) value of the vector.
Parameters
value The value to set
Definition at line 255 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(2);
            data[1] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
setZ()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::setZ (Type value) inline
Sets the z (third) value of the vector.
This works as a setter for the z (third) value of the vector.
Parameters
value The value to set
Definition at line 296 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(3);
            data[2] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
size()
template<typename Type , size_t N> int GLESC::Math::Vector< Type, N >::size () const inline
Returns the size of the vector.
Returns
The size of the vector
Definition at line 1052 of file Vector.h.
{
            return N;
        }
Referenced by GLESC::Math::PolyhedronFace::intersects().
sum()
template<typename Type , size_t N> Type GLESC::Math::Vector< Type, N >::sum () const inline
Returns the sum of all the elements in the vector.
Returns
The sum of all the elements in the vector
Definition at line 733 of file Vector.h.
{
            return VectorAlgorithms::sum(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::sum().
swap()
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::swap (Vector< Type, N > & other) inline noexcept
Swaps the data of this vector with another vector.
Parameters
other The other vector to swap with
Definition at line 816 of file Vector.h.
{
            std::swap(data, other.data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
toDegrees()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::toDegrees () const inline
Converts the vector to degrees.
Returns
The vector in degrees
Definition at line 753 of file Vector.h.
{
            Vector result;
            for (size_t i = 0; i < N; i++) {
                result[i] = Math::degrees(data[i]);
            }
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::Math::degrees(), and GLESC::isIterable_v.
Referenced by GLESC::Transform::Transformer::lookAt().
toMatrix()
template<typename Type , size_t N> MatrixData< Type, N, 1 > GLESC::Math::Vector< Type, N >::toMatrix () const inline
Converts the vector to a single column matrix.
Returns
The matrix representation of the vector
Definition at line 655 of file Vector.h.
{
            MatrixData<Type, N, 1> result;
            VectorMixedAlgorithms::vectorToMatrix(this->data, result);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorMixedAlgorithms::vectorToMatrix().
toRads()
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::toRads () const inline
Converts the vector to radians.
Returns
The vector in radians
Definition at line 741 of file Vector.h.
{
            Vector result;
            for (size_t i = 0; i < N; i++) {
                result[i] = Math::radians(data[i]);
            }
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::radians().
Referenced by GLESC::Transform::Transform::Transform(), GLESC::Transform::Transform::calculateForward(), GLESC::Transform::Transform::calculateRight(), GLESC::Transform::Transform::calculateUp(), GLESC::Render::Renderer::createViewMatrix(), GLESC::Transform::Transform::getModelMatrix(), GLESC::Transform::Transform::getRotationMatrix(), and GLESC::Transform::Transformer::rotateMesh().
toString()
template<typename Type , size_t N> std::string GLESC::Math::Vector< Type, N >::toString () const inline
Converts the vector to string.
Returns
The string representation of the vector
Definition at line 1136 of file Vector.h.
{
            return VectorAlgorithms::toString(this->data);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::toString().
Referenced by GLESC::Math::Plane::toString(), GLESC::Render::BaseVertex::toString(), GLESC::Render::TextureVertex::toString(), GLESC::Physics::Physics::toString(), and GLESC::Transform::Transform::toString().
vectorToEulerRotation() [1/2]
template<typename Type , size_t N> Vector & GLESC::Math::Vector< Type, N >::vectorToEulerRotation (const Vector< Type, N > & up) inline
Converts the vector to euler angles.
Takes the vector as a direction vector, receives a up vector and returns the euler angles that represents the rotation of an object that needs to be rotated to look in the direction of the direction vector. Modifies the current vector.
Parameters
up The up vector
Returns
A reference to this vector after the operation
Definition at line 1030 of file Vector.h.
{
            VectorAlgorithms::vectorToEuler(this->data, up.data, this->data);
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and GLESC::Math::VectorAlgorithms::vectorToEuler().
Referenced by GLESC::Transform::Transformer::lookAt().
vectorToEulerRotation() [2/2]
template<typename Type , size_t N> Vector GLESC::Math::Vector< Type, N >::vectorToEulerRotation (const Vector< Type, N > & up) const inline
Converts the vector to euler angles.
Takes the vector as a direction vector, receives a up vector and returns the euler angles that represents the rotation of an object that needs to be rotated to look in the direction of the direction vector.
Parameters
up The up vector
Returns
The euler angles that represent the rotation
Definition at line 1042 of file Vector.h.
{
            Vector result;
            VectorAlgorithms::vectorToEuler(this->data, up.data, result.data);
            return result;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Math::VectorAlgorithms::vectorToEuler().
w() [1/2]
template<typename Type , size_t N> Type & GLESC::Math::Vector< Type, N >::w () inline
Returns the w (fourth) value of the vector.
This is the same as operator[] but only for the w (fourth) value. The returned value is a reference so it can be modified.
Returns
The w (fourth) value of the vector
Definition at line 307 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(4);
            return data[3];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
w() [2/2]
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::w (Type value) inline
Sets the w (fourth) value of the vector.
This works as a setter but for the w (fourth) value of the vector.
Parameters
value The value to set
Definition at line 317 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(4);
            data[3] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
x() [1/2]
template<typename Type , size_t N> Type & GLESC::Math::Vector< Type, N >::x () inline
Returns the x (reference) value of the vector.
This is the same as operator[] but only for the x (first) value. The returned value is a reference so it can be modified.
Returns
The x (first) value of the vector
Definition at line 184 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(1);
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Referenced by GLESC::Input::InputManager::handleMouseMotion(), and GLESC::Input::InputManager::setMouseRelative().
x() [2/2]
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::x (Type value) inline
Sets the x (first) value of the vector.
This works as a setter but for the x (first) value of the vector.
Parameters
value The value to set
Definition at line 194 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(1);
            data[0] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
y() [1/2]
template<typename Type , size_t N> Type & GLESC::Math::Vector< Type, N >::y () inline
Returns the y (second) value of the vector.
This is the same as operator[] but only for the y (second) value. The returned value is a reference so it can be modified.
Returns
The y (second) value of the vector
Definition at line 225 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(2);
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Referenced by GLESC::Input::InputManager::handleMouseMotion(), and GLESC::Input::InputManager::setMouseRelative().
y() [2/2]
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::y (Type value) inline
Sets the y (second) value of the vector.
This works as a setter but for the y (second) value of the vector.
Parameters
value The value to set
Definition at line 235 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(2);
            data[1] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
z() [1/2]
template<typename Type , size_t N> Type & GLESC::Math::Vector< Type, N >::z () inline
Returns the z (third) value of the vector.
This is the same as operator[] but only for the z (third) value. The returned value is a reference so it can be modified.
Returns
The z (third) value of the vector
Definition at line 266 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(3);
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
z() [2/2]
template<typename Type , size_t N> void GLESC::Math::Vector< Type, N >::z (Type value) inline
Sets the z (third) value of the vector.
This works as a setter but for the z (third) value of the vector.
Parameters
value The value to set
Definition at line 276 of file Vector.h.
{
            S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER(3);
            data[2] = value;
        }
References GLESC::Math::Vector< Type, N >::data, GLESC::isIterable_v, and S_ASSERT_VEC_IS_OF_SIZE_OR_BIGGER.
Member Data Documentation
data
template<typename Type , size_t N> VectorData<Type, N> GLESC::Math::Vector< Type, N >::data
Data of the vector.
See also
VectorData
Definition at line 1144 of file Vector.h.
Referenced by GLESC::Render::ColorRgb::ColorRgb(), GLESC::Render::ColorRgba::ColorRgba(), GLESC::Render::ColorRgbaNorm::ColorRgbaNorm(), GLESC::Render::ColorRgbNorm::ColorRgbNorm(), GLESC::Render::ColorRgbNorm::ColorRgbNorm(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::abs(), GLESC::Math::Vector< Type, N >::angle(), GLESC::Math::Vector< Type, N >::angleDegrees(), GLESC::Math::Vector< Type, N >::clamp(), GLESC::Math::Vector< Type, N >::clamp(), GLESC::Math::Vector< Type, N >::cross(), GLESC::Math::Vector< Type, N >::dehomogenize(), GLESC::Math::Vector< Type, N >::distance(), GLESC::Math::Vector< Type, N >::distanceSquared(), GLESC::Math::Vector< Type, N >::dot(), expectEqVec(), GLESC::Math::Vector< Type, N >::get(), GLESC::Render::ColorRgba::getA(), GLESC::Render::ColorRgbaNorm::getA(), GLESC::Render::ColorRgba::getAModifiable(), GLESC::Render::ColorRgba::getANormalized(), GLESC::Render::ColorRgb::getB(), GLESC::Render::ColorRgba::getB(), GLESC::Render::ColorRgbNorm::getB(), GLESC::Render::ColorRgbaNorm::getB(), GLESC::Render::ColorRgba::getBModifiable(), GLESC::Render::ColorRgb::getBNormalized(), GLESC::Render::ColorRgba::getBNormalized(), GLESC::Render::GlobalSun::getDebuggingValues(), GLESC::Render::ColorRgb::getG(), GLESC::Render::ColorRgba::getG(), GLESC::Render::ColorRgbNorm::getG(), GLESC::Render::ColorRgbaNorm::getG(), GLESC::Render::ColorRgba::getGModifiable(), GLESC::Render::ColorRgb::getGNormalized(), GLESC::Render::ColorRgba::getGNormalized(), GLESC::Math::Vector< Type, N >::getOrthogonal(), GLESC::Render::ColorRgb::getR(), GLESC::Render::ColorRgba::getR(), GLESC::Render::ColorRgbNorm::getR(), GLESC::Render::ColorRgbaNorm::getR(), GLESC::Render::ColorRgba::getRModifiable(), GLESC::Render::ColorRgb::getRNormalized(), GLESC::Render::ColorRgba::getRNormalized(), GLESC::Math::Vector< Type, N >::getW(), GLESC::Math::Vector< Type, N >::getX(), GLESC::Math::Vector< Type, N >::getY(), GLESC::Math::Vector< Type, N >::getZ(), GLESC::Math::Vector< Type, N >::homogenize(), initVector1(), initVector2(), GLESC::Math::Vector< Type, N >::isCollinear(), GLESC::Math::Vector< Type, N >::isHomogeneous(), GLESC::Math::Vector< Type, N >::isMultipleOf(), GLESC::Math::Vector< Type, N >::isNormalized(), GLESC::Math::Vector< Type, N >::isOrthogonal(), GLESC::Math::Vector< Type, N >::isParallel(), GLESC::Math::Vector< Type, N >::isZero(), GLESC::Math::Vector< Type, N >::length(), GLESC::Math::Vector< Type, N >::lengthSquared(), GLESC::Math::Vector< Type, N >::lerp(), GLESC::Math::Vector< Type, N >::magnitude(), GLESC::Math::Matrix< Type, N, M >::makeModelMatrix(), GLESC::Math::Matrix< Type, N, M >::makeScaleMatrix(), GLESC::Math::Matrix< Type, N, M >::makeTranslationMatrix(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixEye(), GLESC::Math::Matrix< Type, N, M >::makeViewMatrixPosRot(), GLESC::Math::Vector< Type, N >::mod(), GLESC::Math::Vector< Type, N >::mod(), GLESC::Math::Vector< Type, N >::normalize(), GLESC::Math::Vector< Type, N >::normalize(), GLESC::Math::Vector< Type, N >::operator!=(), GLESC::Math::Vector< Type, N >::operator*(), GLESC::Math::Matrix< Type, N, M >::operator*(), GLESC::Math::Vector< Type, N >::operator*(), GLESC::Math::Vector< Type, N >::operator*=(), GLESC::Math::Vector< Type, N >::operator*=(), GLESC::Math::Vector< Type, N >::operator+(), GLESC::Math::Vector< Type, N >::operator+(), GLESC::Math::Vector< Type, N >::operator+=(), GLESC::Math::Vector< Type, N >::operator+=(), GLESC::Math::Vector< Type, N >::operator-(), GLESC::Math::Vector< Type, N >::operator-(), GLESC::Math::Vector< Type, N >::operator-(), GLESC::Math::Vector< Type, N >::operator-=(), GLESC::Math::Vector< Type, N >::operator-=(), GLESC::Math::Vector< Type, N >::operator/(), GLESC::Math::Vector< Type, N >::operator/(), GLESC::Math::Vector< Type, N >::operator/=(), GLESC::Math::Vector< Type, N >::operator/=(), GLESC::Math::Vector< Type, N >::operator<(), GLESC::Render::ColorRgbNorm::operator=(), GLESC::Render::ColorRgbaNorm::operator=(), GLESC::Math::Vector< Type, N >::operator=(), GLESC::Math::Vector< Type, N >::operator=(), GLESC::Math::Vector< Type, N >::operator=(), GLESC::Math::Vector< Type, N >::operator==(), GLESC::Math::Vector< Type, N >::operator[](), GLESC::Math::Vector< Type, N >::operator[](), GLESC::Math::Vector< Type, N >::project(), GLESC::Math::Vector< Type, N >::reflect(), GLESC::Math::Vector< Type, N >::reflect(), GLESC::Math::Vector< Type, N >::rotate(), GLESC::Math::Vector< Type, N >::rotate(), GLESC::Math::Vector< Type, N >::set(), GLESC::Render::ColorRgba::setA(), GLESC::Render::ColorRgb::setB(), GLESC::Render::ColorRgba::setB(), GLESC::Render::ColorRgb::setG(), GLESC::Render::ColorRgba::setG(), GLESC::Render::ColorRgb::setR(), GLESC::Render::ColorRgba::setR(), GLESC::Math::Vector< Type, N >::setW(), GLESC::Math::Vector< Type, N >::setX(), GLESC::Math::Vector< Type, N >::setY(), GLESC::Math::Vector< Type, N >::setZ(), GLESC::Math::Vector< Type, N >::sum(), GLESC::Math::Vector< Type, N >::swap(), GLESC::Math::Vector< Type, N >::toDegrees(), GLESC::Math::Vector< Type, N >::toMatrix(), GLESC::Math::Vector< Type, N >::toRads(), GLESC::Math::Vector< Type, N >::toString(), GLESC::Math::Matrix< Type, N, M >::toVector(), TYPED_TEST(), GLESC::Math::Vector< Type, N >::vectorToEulerRotation(), GLESC::Math::Vector< Type, N >::vectorToEulerRotation(), GLESC::Math::Vector< Type, N >::w(), GLESC::Math::Vector< Type, N >::w(), GLESC::Math::Vector< Type, N >::x(), GLESC::Math::Vector< Type, N >::x(), GLESC::Math::Vector< Type, N >::y(), GLESC::Math::Vector< Type, N >::y(), GLESC::Math::Vector< Type, N >::z(), and GLESC::Math::Vector< Type, N >::z().
The documentation for this class was generated from the following file:
Vector.h