GLESC: GLESC::SoundLoader Class Reference
GLESC::SoundLoader Class Reference
Class that loads and stores sounds and music.
#include <SoundLoader.h>
Private Member Functions
void cleanup ()
Cleans up the resources used by SDL and SDL_mixer.
Mix_Music & getMusic (const std::string &name)
Gets a music by name.
Mix_Chunk & getSound (const std::string &name)
Gets a sound by name.
void loadMusic (const std::string &filePath, const std::string &name)
Loads a music from a file.
void loadSound (const std::string &filePath, const std::string &name)
Loads a sound from a file.
Static Private Member Functions
static void init ()
Initializes SDL and SDL_mixer.
Private Attributes
std::map< Hasher::Hash, Mix_Music * > music {}
std::map< Hasher::Hash, Mix_Chunk * > sounds {}
Static Private Attributes
static constexpr const char * soundsPath = SOUNDS_PATH"/"
Friends
class SoundPlayer
Detailed Description
Class that loads and stores sounds and music.
Sounds and music are stored in maps that are accesed by their name.
Definition at line 25 of file SoundLoader.h.
Member Function Documentation
cleanup()
void SoundLoader::cleanup () private
Cleans up the resources used by SDL and SDL_mixer.
Definition at line 28 of file SoundLoader.cpp.
{
    for (auto& sound : sounds) {
        Mix_FreeChunk(sound.second);
    }
    sounds.clear();
    for (auto& m : music) {
        Mix_FreeMusic(m.second);
    }
    music.clear();
    Mix_Quit();
}
References GLESC::isIterable_v, music, and sounds.
Referenced by GLESC::SoundPlayer::cleanup().
getMusic()
Mix_Music & SoundLoader::getMusic (const std::string & name) private
Gets a music by name.
Parameters
name The name of the music.
Returns
The music.
Definition at line 59 of file SoundLoader.cpp.
{
    Hasher::Hash nameHash = Hasher::hash(name);
    D_ASSERT_TRUE(music.count(nameHash), "Music not found: "+ name);
    return *music[nameHash];
}
References D_ASSERT_TRUE, GLESC::Hasher::hash(), GLESC::isIterable_v, and music.
Referenced by GLESC::SoundPlayer::setMusic().
getSound()
Mix_Chunk & SoundLoader::getSound (const std::string & name) private
Gets a sound by name.
Parameters
name The name of the sound.
Returns
The sound.
Definition at line 65 of file SoundLoader.cpp.
{
    Hasher::Hash nameHash = Hasher::hash(name);
    D_ASSERT_TRUE(sounds.count(nameHash), "Sound not found: "+ name);
    return *sounds[nameHash];
}
References D_ASSERT_TRUE, GLESC::Hasher::hash(), GLESC::isIterable_v, and sounds.
Referenced by GLESC::SoundPlayer::playSound().
init()
void SoundLoader::init () static private
Initializes SDL and SDL_mixer.
Definition at line 19 of file SoundLoader.cpp.
                       {
    D_ASSERT_FALSE(SDL_Init(SDL_INIT_AUDIO) < 0,
                   std::string("SDL could not initialize! SDL Error: %s\n")+ SDL_GetError());
    D_ASSERT_FALSE(Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 2048) < 0,
                   std::string("SDL_mixer could not initialize! SDL_mixer Error: %s\n") + Mix_GetError());
}
References D_ASSERT_FALSE, and GLESC::isIterable_v.
Referenced by GLESC::SoundPlayer::init().
loadMusic()
void SoundLoader::loadMusic (const std::string & filePath, const std::string & name) private
Loads a music from a file.
The music is stored in a map with the name as the key.
Parameters
filePath The path to the music file.
name The name of the music.
Definition at line 51 of file SoundLoader.cpp.
{
    std::string songPath = BinPath::getExecutableDirectory() + soundsPath + filePath;
    Mix_Music* m = Mix_LoadMUS(songPath.c_str());
    D_ASSERT_NOT_NULLPTR(m, "Failed to load music: "+ songPath);
    Hasher::Hash nameHash = Hasher::hash(name);
    music[nameHash] = m;
}
References D_ASSERT_NOT_NULLPTR, BinPath::getExecutableDirectory(), GLESC::Hasher::hash(), GLESC::isIterable_v, music, and soundsPath.
Referenced by GLESC::SoundPlayer::loadSong().
loadSound()
void SoundLoader::loadSound (const std::string & filePath, const std::string & name) private
Loads a sound from a file.
The sound is stored in a map with the name as the key.
Parameters
filePath The path to the sound file.
name The name of the sound.
Definition at line 42 of file SoundLoader.cpp.
{
    std::string soundPath = BinPath::getExecutableDirectory() + soundsPath + filePath;
    Mix_Chunk* sound = Mix_LoadWAV(soundPath.c_str());
    D_ASSERT_NOT_NULLPTR(sound, "Failed to load sound: "+ soundPath);
    Hasher::Hash nameHash = Hasher::hash(name);
    sounds[nameHash] = sound;
}
References D_ASSERT_NOT_NULLPTR, BinPath::getExecutableDirectory(), GLESC::Hasher::hash(), GLESC::isIterable_v, sounds, and soundsPath.
Referenced by GLESC::SoundPlayer::loadSound().
Friends And Related Symbol Documentation
SoundPlayer
friend class SoundPlayer friend
Definition at line 26 of file SoundLoader.h.
Member Data Documentation
music
std::map<Hasher::Hash, Mix_Music*> GLESC::SoundLoader::music {} private
Definition at line 65 of file SoundLoader.h.
{};
Referenced by cleanup(), getMusic(), and loadMusic().
sounds
std::map<Hasher::Hash, Mix_Chunk*> GLESC::SoundLoader::sounds {} private
Definition at line 64 of file SoundLoader.h.
{};
Referenced by cleanup(), getSound(), and loadSound().
soundsPath
constexpr const char* GLESC::SoundLoader::soundsPath = SOUNDS_PATH"/" static constexpr private
Definition at line 63 of file SoundLoader.h.
Referenced by loadMusic(), and loadSound().
The documentation for this class was generated from the following files:
SoundLoader.h
SoundLoader.cpp