GLESC: ConcurrentQueue< T > Class Template Reference
ConcurrentQueue< T > Class Template Reference
#include <ConcurrentQueue.h>
Public Member Functions
bool pop (T &value)
void push (T value)
Private Attributes
std::condition_variable cond_var_
std::mutex mutex_
std::queue< T > queue_
Detailed Description
template<typename T>
class ConcurrentQueue< T >
Definition at line 17 of file ConcurrentQueue.h.
Member Function Documentation
pop()
template<typename T > bool ConcurrentQueue< T >::pop (T & value) inline
Definition at line 25 of file ConcurrentQueue.h.
                       {
        std::unique_lock<std::mutex> lock(mutex_);
        cond_var_.wait(lock, [this] { return !queue_.empty(); });
        value = std::move(queue_.front());
        queue_.pop();
        return true;
    }
References ConcurrentQueue< T >::cond_var_, ConcurrentQueue< T >::mutex_, and ConcurrentQueue< T >::queue_.
Referenced by GLESC::Logger::processQueue().
push()
template<typename T > void ConcurrentQueue< T >::push (T value) inline
Definition at line 19 of file ConcurrentQueue.h.
                       {
        std::lock_guard<std::mutex> lock(mutex_);
        queue_.push(std::move(value));
        cond_var_.notify_one();
    }
References ConcurrentQueue< T >::cond_var_, ConcurrentQueue< T >::mutex_, and ConcurrentQueue< T >::queue_.
Referenced by GLESC::Logger::~Logger(), and GLESC::Logger::executeOnAllInputs().
Member Data Documentation
cond_var_
template<typename T > std::condition_variable ConcurrentQueue< T >::cond_var_ private
Definition at line 36 of file ConcurrentQueue.h.
Referenced by ConcurrentQueue< T >::pop(), and ConcurrentQueue< T >::push().
mutex_
template<typename T > std::mutex ConcurrentQueue< T >::mutex_ private
Definition at line 35 of file ConcurrentQueue.h.
Referenced by ConcurrentQueue< T >::pop(), and ConcurrentQueue< T >::push().
queue_
template<typename T > std::queue<T> ConcurrentQueue< T >::queue_ private
Definition at line 34 of file ConcurrentQueue.h.
Referenced by ConcurrentQueue< T >::pop(), and ConcurrentQueue< T >::push().
The documentation for this class was generated from the following file:
ConcurrentQueue.h