GLESC: GLESC::Logger Class Reference
GLESC::Logger Class Reference
#include <Logger.h>
Public Member Functions
Logger (const Logger &)=delete
void addLogger (std::unique_ptr< ILogger > loggerParam)
void error (const std::string &text) override
Display error messages Background – Red Text – Black Bold.
void executeOnAllInputs (void(ILogger::*func)(const std::string &), const std::string &text)
void importantInfo (const std::string &text) override
Display important information Background – White Text – Black.
void importantInfoBlue (const std::string &text) override
Display important information Background – Light Blue Text – Black.
void importantInfoPurple (const std::string &text) override
Display important information Background – Light Purple Text – Black.
void importantInfoWhite (const std::string &text) override
Display important information Background – White Text – Black.
void importantSuccess (const std::string &text) override
Display important success information.
void info (const std::string &text) override
Display basic information Background – Black Text – White.
void infoBlue (const std::string &text) override
Display basic information Background – Black Text – Light Blue.
void infoPurple (const std::string &text) override
Display basic information Background – Black Text – Light Purple.
void log (const std::string &text) override
Display log messages Background and text default.
void nonImportantInfo (const std::string &text) override
Display non important information Background – Black Text – Grey.
Logger & operator= (const Logger &)=delete
void success (const std::string &text) override
Display success information Background – Green Text – White Bold.
void warning (const std::string &text) override
Display warning messages Background – Black Text – Yellow.
Public Member Functions inherited from ILogger
virtual ~ILogger ()=default
Static Public Member Functions
static Logger & get ()
Private Member Functions
Logger ()
~Logger ()
void processQueue ()
Private Attributes
std::atomic< bool > done_
std::vector< std::unique_ptr< ILogger > > loggers
std::mutex mutex_
ConcurrentQueue< std::function< void()> > queue_
std::thread worker_
Detailed Description
Definition at line 24 of file Logger.h.
Constructor & Destructor Documentation
Logger() [1/2]
GLESC::Logger::Logger (const Logger &) delete
Logger() [2/2]
Logger::Logger () private
Definition at line 16 of file Logger.cpp.
               : done_(false), worker_(&Logger::processQueue, this) {
#ifndef NLOGGING
    addLogger(std::make_unique<TerminalLogger>());
#endif
    addLogger(std::make_unique<FileLogger>());
}
References addLogger().
~Logger()
Logger::~Logger () private
Definition at line 23 of file Logger.cpp.
                {
    done_ = true;
    queue_.push([] {
    }); // Push an empty task to wake up the thread
    worker_.join();
}
References done_, ConcurrentQueue< T >::push(), queue_, and worker_.
Member Function Documentation
addLogger()
void Logger::addLogger (std::unique_ptr< ILogger > loggerParam)
Definition at line 35 of file Logger.cpp.
{
    std::lock_guard<std::mutex> lock(mutex_);
    loggers.push_back(std::move(loggerParam));
}
References GLESC::isIterable_v, loggers, and mutex_.
Referenced by Logger().
error()
void Logger::error (const std::string & text) override virtual
Display error messages Background – Red Text – Black Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 53 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::error, text);
}
References ILogger::error(), executeOnAllInputs(), and text().
executeOnAllInputs()
void Logger::executeOnAllInputs (void(ILogger::*)(const std::string &) func, const std::string & text)
Definition at line 40 of file Logger.cpp.
{
    queue_.push([this, func, text] {
        std::lock_guard<std::mutex> lock(mutex_);
        for (auto& logger : loggers) {
            (logger.get()->*func)(text);
        }
    });
}
References GLESC::isIterable_v, loggers, mutex_, ConcurrentQueue< T >::push(), queue_, and text().
Referenced by error(), importantInfo(), importantInfoBlue(), importantInfoPurple(), importantInfoWhite(), importantSuccess(), info(), infoBlue(), infoPurple(), log(), nonImportantInfo(), success(), and warning().
get()
Logger & Logger::get () static
Definition at line 30 of file Logger.cpp.
                    {
    static Logger instance;
    return instance;
}
References GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem(), HudLookAndFeel::addFont(), GLESC::GAPI::OpenGLAPI::createContext(), GLESC::TextureLoader::createSurface(), GLESC::WindowManager::createWindow(), GLESC::WindowManager::destroyWindow(), GLESC::TextureLoader::flipSurface(), GLESC::GAPI::OpenGLAPI::getTextureColorFormat(), GLESC::WindowManager::initSDL(), GLESC::GAPI::ShaderLoader::loadShader(), GLESC::GAPI::ShaderLoader::loadShader(), main(), GLESC::GAPI::OpenGLAPI::postWindowCreationInit(), GLESC::ECS::ECSCoordinator::printEntity(), printGAPIInit(), GLESC::ECS::ComponentArray< Component >::printStatus(), GLESC::ECS::ECSCoordinator::printStatus(), GLESC::Engine::processInput(), GLESC::Engine::render(), GLESC::WindowManager::setIcon(), GLESC::ResMng::Texture::TextureSurface::toString(), and GLESC::Engine::update().
importantInfo()
void Logger::importantInfo (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 77 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::importantInfo, text);
}
References executeOnAllInputs(), ILogger::importantInfo(), and text().
Referenced by GLESC::ECS::ECSCoordinator::printStatus().
importantInfoBlue()
void Logger::importantInfoBlue (const std::string & text) override virtual
Display important information Background – Light Blue Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 81 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::importantInfoBlue, text);
}
References executeOnAllInputs(), ILogger::importantInfoBlue(), and text().
Referenced by GLESC::ECS::ComponentArray< Component >::printStatus(), GLESC::ECS::ECSCoordinator::printStatus(), and GLESC::Engine::processInput().
importantInfoPurple()
void Logger::importantInfoPurple (const std::string & text) override virtual
Display important information Background – Light Purple Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 85 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::importantInfoPurple, text);
}
References executeOnAllInputs(), ILogger::importantInfoPurple(), and text().
Referenced by GLESC::Engine::render().
importantInfoWhite()
void Logger::importantInfoWhite (const std::string & text) override virtual
Display important information Background – White Text – Black.
Parameters
text printed text
Implements ILogger.
Definition at line 89 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::importantInfoWhite, text);
}
References executeOnAllInputs(), ILogger::importantInfoWhite(), and text().
Referenced by GLESC::ECS::ECSCoordinator::printStatus(), and GLESC::Engine::update().
importantSuccess()
void Logger::importantSuccess (const std::string & text) override virtual
Display important success information.
Parameters
text
Implements ILogger.
Definition at line 97 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::importantSuccess, text);
}
References executeOnAllInputs(), ILogger::importantSuccess(), and text().
Referenced by printGAPIInit().
info()
void Logger::info (const std::string & text) override virtual
Display basic information Background – Black Text – White.
Parameters
text printed text
Implements ILogger.
Definition at line 65 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::info, text);
}
References executeOnAllInputs(), ILogger::info(), and text().
Referenced by HudLookAndFeel::addFont(), GLESC::TextureLoader::createSurface(), GLESC::TextureLoader::flipSurface(), GLESC::GAPI::OpenGLAPI::getTextureColorFormat(), GLESC::ECS::ECSCoordinator::printEntity(), GLESC::ECS::ECSCoordinator::printStatus(), GLESC::WindowManager::setIcon(), and GLESC::ResMng::Texture::TextureSurface::toString().
infoBlue()
void Logger::infoBlue (const std::string & text) override virtual
Display basic information Background – Black Text – Light Blue.
Parameters
text printed text
Implements ILogger.
Definition at line 69 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::infoBlue, text);
}
References executeOnAllInputs(), ILogger::infoBlue(), and text().
Referenced by GLESC::ECS::ComponentArray< Component >::printStatus().
infoPurple()
void Logger::infoPurple (const std::string & text) override virtual
Display basic information Background – Black Text – Light Purple.
Parameters
text printed text
Implements ILogger.
Definition at line 73 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::infoPurple, text);
}
References executeOnAllInputs(), ILogger::infoPurple(), and text().
log()
void Logger::log (const std::string & text) override virtual
Display log messages Background and text default.
Parameters
text
Implements ILogger.
Definition at line 49 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::log, text);
}
References executeOnAllInputs(), ILogger::log(), and text().
nonImportantInfo()
void Logger::nonImportantInfo (const std::string & text) override virtual
Display non important information Background – Black Text – Grey.
Parameters
text printed text
Implements ILogger.
Definition at line 61 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::nonImportantInfo, text);
}
References executeOnAllInputs(), ILogger::nonImportantInfo(), and text().
Referenced by GLESC::GAPI::ShaderLoader::loadShader(), and GLESC::ECS::ECSCoordinator::printEntity().
operator=()
Logger & GLESC::Logger::operator= (const Logger &) delete
processQueue()
void Logger::processQueue () private
Definition at line 101 of file Logger.cpp.
{
    while (!done_) {
        std::function<void()> task;
        if (queue_.pop(task) && task) {
            task();
        }
    }
}
References done_, GLESC::isIterable_v, ConcurrentQueue< T >::pop(), and queue_.
success()
void Logger::success (const std::string & text) override virtual
Display success information Background – Green Text – White Bold.
Parameters
text printed text
Implements ILogger.
Definition at line 93 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::success, text);
}
References executeOnAllInputs(), ILogger::success(), and text().
Referenced by GLESC::GAPI::OpenGLAPI::createContext(), GLESC::TextureLoader::createSurface(), GLESC::WindowManager::createWindow(), GLESC::WindowManager::destroyWindow(), GLESC::TextureLoader::flipSurface(), GLESC::WindowManager::initSDL(), GLESC::GAPI::ShaderLoader::loadShader(), GLESC::GAPI::ShaderLoader::loadShader(), GLESC::GAPI::OpenGLAPI::postWindowCreationInit(), and printGAPIInit().
warning()
void Logger::warning (const std::string & text) override virtual
Display warning messages Background – Black Text – Yellow.
Parameters
text printed text
Implements ILogger.
Definition at line 57 of file Logger.cpp.
{
    executeOnAllInputs(&ILogger::warning, text);
}
References executeOnAllInputs(), text(), and ILogger::warning().
Referenced by GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem(), and main().
Member Data Documentation
done_
std::atomic<bool> GLESC::Logger::done_ private
Definition at line 58 of file Logger.h.
Referenced by ~Logger(), and processQueue().
loggers
std::vector<std::unique_ptr<ILogger> > GLESC::Logger::loggers private
Definition at line 55 of file Logger.h.
Referenced by addLogger(), and executeOnAllInputs().
mutex_
std::mutex GLESC::Logger::mutex_ private
Definition at line 59 of file Logger.h.
Referenced by addLogger(), and executeOnAllInputs().
queue_
ConcurrentQueue<std::function<void()> > GLESC::Logger::queue_ private
Definition at line 56 of file Logger.h.
Referenced by ~Logger(), executeOnAllInputs(), and processQueue().
worker_
std::thread GLESC::Logger::worker_ private
Definition at line 57 of file Logger.h.
Referenced by ~Logger().
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp