GLESC: GLESC::Engine Class Reference
GLESC::Engine Class Reference
#include <GLESC.h>
Private Member Functions
Engine (FPSManager &fpsManager)
The constructor is private, the engine can only be created by the main function.
~Engine ()
void createEngineEntities ()
std::vector< std::unique_ptr< ECS::System > > createSystems ()
friend int::main (int argc, char *argv[])
The engine can only be created by the main function, where the game loop is defined.
void processInput ()
Processes the input of the game.
void registerStats () const
void render (double timeOfFrame)
Processes the rendering of the game Can be called at variable intervals of time as it uses elapsed.
void update ()
Processes the logic of the game Is called every frame, must be called at constant intervals of time as it does not use elapsed, more information https://www.gameprogrammingpatterns.com/game-loop.html.
Private Attributes
Physics::CollisionManager collisionManager
Handles the collision of the game.
ECS::ECSCoordinator ecs
The ECS coordinator, stores all the entities, components and systems.
EngineCamera engineCamera
A default implementation of the engine camera.
HUD::EngineHUDManager engineHuds
A simple storage for the engine entities.
ECS::EntityFactory entityFactory
The ECS entity factory, used to create entities.
FPSManager & fpsManager
A reference to the FPS manager.
Game game
The game, handles the game logic.
HUD::HUDManager hudManager
Handles the HUD of the game.
Input::InputManager inputManager
Handles the input of the game.
Physics::PhysicsManager physicsManager
Handles the physics of the game.
Render::Renderer renderer
Handles the rendering of the game.
bool running {true}
If true, the game is running. If false, the game is stopped.
Scene::SceneContainer sceneContainer
The scene container, stores all the scenes of the game.
Scene::SceneManager sceneManager
The scene manager, handles the scenes of the game.
std::vector< std::unique_ptr< ECS::System > > systems
A list of systems that are updated every frame.
TextureFactory textureFactory
A factory for creating textures.
WindowManager windowManager
Handles the window of the game.
Detailed Description
Definition at line 40 of file GLESC.h.
Constructor & Destructor Documentation
Engine()
Engine::Engine (FPSManager & fpsManager) explicit private
The constructor is private, the engine can only be created by the main function.
Definition at line 37 of file GLESC.cpp.
                                     :
    fpsManager(fpsManager),
    windowManager(),
    renderer(windowManager),
    hudManager(windowManager.getWindow()),
    inputManager(hudManager, windowManager),
    engineHuds(hudManager, renderer, textureFactory),
    ecs(),
    entityFactory(ecs),
    systems(createSystems()),
    engineCamera(entityFactory, inputManager, windowManager),
    sceneManager(entityFactory, windowManager),
    sceneContainer(windowManager, entityFactory, inputManager, sceneManager, hudManager, engineCamera),
    game(sceneManager, sceneContainer) {
    engineCamera.setupCamera();
    engineCamera.setEngineHuds(&engineHuds);
    this->registerStats();
    SoundPlayer::init();
    createEngineEntities();
    game.init();
}
References createEngineEntities(), engineCamera, engineHuds, game, GLESC::SoundPlayer::init(), registerStats(), GLESC::EngineCamera::setEngineHuds(), and GLESC::EngineCamera::setupCamera().
~Engine()
Engine::~Engine () private
Definition at line 59 of file GLESC.cpp.
                {
    SoundPlayer::cleanup();
}
References GLESC::SoundPlayer::cleanup().
Member Function Documentation
createEngineEntities()
void Engine::createEngineEntities () private
Definition at line 139 of file GLESC.cpp.
{
    ECS::Entity sun = entityFactory.createEntity("sun", {EntityType::Engine})
                                   .addComponent<ECS::TransformComponent>()
                                   .addComponent<ECS::SunComponent>();
    sun.getComponent<ECS::TransformComponent>().transform.setPosition(
        Transform::Position(0, 10, 0));
    sun.getComponent<ECS::SunComponent>().sun.setDirection({-0.4, -1, -0.4});
    sun.getComponent<ECS::SunComponent>().sun.setIntensity(0.7);
    sun.getComponent<ECS::SunComponent>().sun.setColor({255, 255, 150});
    sun.getComponent<ECS::SunComponent>().globalAmbientLight.setIntensity(0.3);
    sun.getComponent<ECS::SunComponent>().globalAmbientLight.setColor({255, 255, 150});
    ECS::Entity fog = entityFactory.createEntity("fog", {EntityType::Engine})
                                   .addComponent<ECS::TransformComponent>()
                                   .addComponent<ECS::FogComponent>();
    fog.getComponent<ECS::TransformComponent>().transform.setPosition({1, 0, 0});
    fog.getComponent<ECS::FogComponent>().fog.setDensity(1);
    fog.getComponent<ECS::FogComponent>().fog.setColor({255, 255, 255});
}
References GLESC::ECS::Entity::addComponent(), GLESC::ECS::EntityFactory::createEntity(), GLESC::Engine, entityFactory, GLESC::ECS::Entity::getComponent(), and GLESC::isIterable_v.
Referenced by Engine().
createSystems()
std::vector< std::unique_ptr< ECS::System > > Engine::createSystems () private
Definition at line 121 of file GLESC.cpp.
{
    std::vector<std::unique_ptr<ECS::System>> systems;
    systems.push_back(std::make_unique<ECS::RenderSystem>(renderer, ecs));
    systems.push_back(std::make_unique<ECS::TransformSystem>(ecs));
    // Physics system must update before the physics collision system
    systems.push_back(std::make_unique<ECS::PhysicsSystem>(physicsManager, ecs));
    systems.push_back(std::make_unique<ECS::PhysicsCollisionSystem>(physicsManager, collisionManager, ecs));
    systems.push_back(std::make_unique<ECS::InputSystem>(inputManager, ecs));
    systems.push_back(std::make_unique<ECS::CameraSystem>(renderer, windowManager, ecs));
    systems.push_back(std::make_unique<ECS::LightSystem>(ecs, renderer));
    systems.push_back(std::make_unique<ECS::SunSystem>(ecs, renderer));
    systems.push_back(std::make_unique<ECS::FogSystem>(renderer, ecs));
#ifndef NDEBUG_GLESC
  systems.push_back(std::make_unique<ECS::DebugInfoSystem>(ecs, renderer));
#endif
    return systems;
}
References collisionManager, ecs, inputManager, physicsManager, renderer, systems, and windowManager.
int::main()
GLESC::Engine::int::main (int argc, char * argv[]) private
The engine can only be created by the main function, where the game loop is defined.
processInput()
void Engine::processInput () private
Processes the input of the game.
Definition at line 64 of file GLESC.cpp.
{
    Logger::get().importantInfoBlue("Engine processInput started");
    inputManager.update(running);
    Logger::get().importantInfoBlue("Engine processInput finished");
}
References GLESC::Logger::get(), GLESC::Logger::importantInfoBlue(), inputManager, running, and GLESC::Input::InputManager::update().
Referenced by main().
registerStats()
void Engine::registerStats () const private
Definition at line 161 of file GLESC.cpp.
{
    StatsManager::registerStatSource("Update FPS", [&]() -> float {
        return fpsManager.getUpdateFPS();
    });
    StatsManager::registerStatSource("Render FPS", [&]() -> float {
        return fpsManager.getRenderFPS();
    });
    StatsManager::registerStatSource("Update frame time", [&]() -> Uint32 {
        return fpsManager.getUpdateTimeMillis();
    });
    StatsManager::registerStatSource("Render frame time", [&]() -> Uint32 {
        return fpsManager.getAverageRenderTimeMillis();
    });
    StatsManager::registerStatSource("Mesh Render Counter", [&]() -> std::string {
        return Stringer::toString(renderer.getMeshRenderCount());
    });
    StatsManager::registerStatSource("Pressed Keys: ", [&]() -> std::string {
        std::string keys = "[";
        for (const auto& key : inputManager.getPressedKeys()) {
            keys += keyToString(key) + ", ";
        }
        // Remove last comma and space
        if (!inputManager.getPressedKeys().empty()) {
            keys.pop_back();
            keys.pop_back();
        }
        keys += "]";
        return keys;
    });
    StatsManager::registerStatSource("Mouse Position: ", [&]() -> std::string {
        return inputManager.getMousePosition().toString();
    });
    StatsManager::registerStatSource("Projection Matrix: ", [&]() -> std::string {
        return renderer.getProjection().toString();
    });
    StatsManager::registerStatSource("View Matrix: ", [&]() -> std::string {
        return renderer.getView().toString();
    });
}
References fpsManager, FPSManager::getAverageRenderTimeMillis(), GLESC::Render::Renderer::getMeshRenderCount(), GLESC::Input::InputManager::getMousePosition(), GLESC::Input::InputManager::getPressedKeys(), GLESC::Render::Renderer::getProjection(), FPSManager::getRenderFPS(), FPSManager::getUpdateFPS(), FPSManager::getUpdateTimeMillis(), GLESC::Render::Renderer::getView(), inputManager, GLESC::isIterable_v, GLESC::StatsManager::registerStatSource(), renderer, and GLESC::Stringer::toString().
Referenced by Engine().
render()
void Engine::render (double timeOfFrame) private
Processes the rendering of the game Can be called at variable intervals of time as it uses elapsed.
Parameters
timeOfFrame The time of the frame
Definition at line 70 of file GLESC.cpp.
{
    Logger::get().importantInfoPurple("Engine render started");
    renderer.start(timeOfFrame);
    renderer.render(timeOfFrame);
    hudManager.render(timeOfFrame);
    renderer.swapBuffers();
    Logger::get().importantInfoPurple("Engine render finished");
}
References GLESC::Logger::get(), hudManager, GLESC::Logger::importantInfoPurple(), GLESC::isIterable_v, GLESC::HUD::HUDManager::render(), GLESC::Render::Renderer::render(), renderer, GLESC::Render::Renderer::start(), and GLESC::Render::Renderer::swapBuffers().
Referenced by main().
update()
void Engine::update () private
Processes the logic of the game Is called every frame, must be called at constant intervals of time as it does not use elapsed, more information https://www.gameprogrammingpatterns.com/game-loop.html.
Definition at line 79 of file GLESC.cpp.
                    {
    Logger::get().importantInfoWhite("Engine update started");
    hudManager.update();
    game.update();
    for (ECS::EntityID id : ecs.getEntitiesToBeDestroyed()) {
#ifndef NDEBUG_GLESC
        EntityListManager::entityRemoved(ecs.getEntityName(id));
#endif
        if (ecs.hasComponent<ECS::RenderComponent>(id) && ecs.hasComponent<ECS::TransformComponent>(id)) {
            renderer.remove(ecs.getComponent<ECS::RenderComponent>(id).getMesh(),
                            ecs.getComponent<ECS::TransformComponent>(id).transform);
        }
    }
    ecs.destroyEntities();
#ifndef NDEBUG_GLESC
    // We need to clear the hud items (Sun, Fog, etc) here, if not called here, juttering will occur
    // Or we will get memory leaks
    HudItemsManager::clearItems();
#endif
    for (auto& system : systems) {
        system->update();
    }
    // This tells the renderer that all the data it needs to render has been updated
    // (Update and render are decoupled, therefore not necesarily consecutive)
    renderer.setRendererUpdated();
    for (const auto& [name,id] : ecs.getAllEntities()) {
        if (ecs.isEntityInstanced(name))
            if ((engineCamera.getEntity().getComponent<ECS::TransformComponent>().transform.getPosition().distance(
                ecs.getComponent<ECS::TransformComponent>(id).transform.getPosition()) > 10000.0f)) {
                ecs.markForDestruction(id);
            }
    }
    Console::log("Debug log message");
    Console::warn("Debug warning message");
    Console::error("Debug error message");
    Logger::get().importantInfoWhite("Engine update finished");
}
References HudItemsManager::clearItems(), GLESC::ECS::ECSCoordinator::destroyEntities(), GLESC::Math::Vector< Type, N >::distance(), ecs, engineCamera, GLESC::EntityListManager::entityRemoved(), GLESC::Console::error(), game, GLESC::Logger::get(), GLESC::ECS::ECSCoordinator::getAllEntities(), GLESC::ECS::Entity::getComponent(), GLESC::ECS::ECSCoordinator::getComponent(), GLESC::ECS::ECSCoordinator::getEntitiesToBeDestroyed(), GLESC::EngineCamera::getEntity(), GLESC::ECS::ECSCoordinator::getEntityName(), GLESC::ECS::RenderComponent::getMesh(), GLESC::Transform::Transform::getPosition(), GLESC::ECS::ECSCoordinator::hasComponent(), hudManager, GLESC::Logger::importantInfoWhite(), GLESC::ECS::ECSCoordinator::isEntityInstanced(), GLESC::isIterable_v, GLESC::Console::log(), GLESC::ECS::ECSCoordinator::markForDestruction(), GLESC::Render::Renderer::remove(), renderer, GLESC::Render::Renderer::setRendererUpdated(), systems, GLESC::ECS::TransformComponent::transform, GLESC::HUD::HUDManager::update(), and GLESC::Console::warn().
Referenced by main().
Member Data Documentation
collisionManager
Physics::CollisionManager GLESC::Engine::collisionManager private
Handles the collision of the game.
Handles all the collision of the game, including collision detection and it's information.
Definition at line 113 of file GLESC.h.
Referenced by createSystems().
ecs
ECS::ECSCoordinator GLESC::Engine::ecs private
The ECS coordinator, stores all the entities, components and systems.
Definition at line 139 of file GLESC.h.
Referenced by createSystems(), and update().
engineCamera
EngineCamera GLESC::Engine::engineCamera private
A default implementation of the engine camera.
Definition at line 148 of file GLESC.h.
Referenced by Engine(), and update().
engineHuds
HUD::EngineHUDManager GLESC::Engine::engineHuds private
A simple storage for the engine entities.
Definition at line 134 of file GLESC.h.
Referenced by Engine().
entityFactory
ECS::EntityFactory GLESC::Engine::entityFactory private
The ECS entity factory, used to create entities.
Operates using the ECS coordinator
Definition at line 144 of file GLESC.h.
Referenced by createEngineEntities().
fpsManager
FPSManager& GLESC::Engine::fpsManager private
A reference to the FPS manager.
Handles the FPS of the game, including the calculation of the FPS and the limiting of the FPS.
Definition at line 129 of file GLESC.h.
Referenced by registerStats().
game
Game GLESC::Engine::game private
The game, handles the game logic.
Definition at line 165 of file GLESC.h.
Referenced by Engine(), and update().
hudManager
HUD::HUDManager GLESC::Engine::hudManager private
Handles the HUD of the game.
Handles all the HUD of the game, including the rendering of the HUD and the input of the HUD.
Definition at line 118 of file GLESC.h.
Referenced by render(), and update().
inputManager
Input::InputManager GLESC::Engine::inputManager private
Handles the input of the game.
Handles all the inputs of the game, and stores the state of the inputs.
Definition at line 96 of file GLESC.h.
Referenced by createSystems(), processInput(), and registerStats().
physicsManager
Physics::PhysicsManager GLESC::Engine::physicsManager private
Handles the physics of the game.
Handles all the physics of the game, including collision handling and physics simulation.
Definition at line 108 of file GLESC.h.
Referenced by createSystems().
renderer
Render::Renderer GLESC::Engine::renderer private
Handles the rendering of the game.
Handles all the rendering of the game, provides a high level interface to the graphics API. Can be used to render 2D and 3D graphics, including generating meshes and textures.
Definition at line 102 of file GLESC.h.
Referenced by createSystems(), registerStats(), render(), and update().
running
bool GLESC::Engine::running {true} private
If true, the game is running. If false, the game is stopped.
Definition at line 86 of file GLESC.h.
{true};
Referenced by main(), and processInput().
sceneContainer
Scene::SceneContainer GLESC::Engine::sceneContainer private
The scene container, stores all the scenes of the game.
Definition at line 161 of file GLESC.h.
sceneManager
Scene::SceneManager GLESC::Engine::sceneManager private
The scene manager, handles the scenes of the game.
Definition at line 157 of file GLESC.h.
systems
std::vector<std::unique_ptr<ECS::System> > GLESC::Engine::systems private
A list of systems that are updated every frame.
Definition at line 152 of file GLESC.h.
Referenced by createSystems(), and update().
textureFactory
TextureFactory GLESC::Engine::textureFactory private
A factory for creating textures.
This factory facilitates the creating and handling of textures.
Definition at line 123 of file GLESC.h.
windowManager
WindowManager GLESC::Engine::windowManager private
Handles the window of the game.
Definition at line 91 of file GLESC.h.
Referenced by createSystems().
The documentation for this class was generated from the following files:
GLESC.h
GLESC.cpp