GLESC: GLESC::ECS::SystemManager Class Reference
GLESC::ECS::SystemManager Class Reference
#include <SystemManager.h>
Public Member Functions
SystemManager ()=default
~SystemManager ()=default
void addComponentRequirementToSystem (const SystemName &name, ComponentID componentID)
Adds a component requirement to a system, this changes the entities that are considered associated with it. The system must be registered. The component must not be required by the system already.
void entityDestroyed (EntityID entity)
Removes the entity from the systems it is associated with.
void entitySignatureChanged (EntityID entity, Signature entitySignature)
Adds the entity to the systems it is associated with and removes it from the systems it is no longer associated with.
const std::unordered_map< SystemName, std::set< EntityID > > & getAllAssociatedEntities () const
const std::set< EntityID > & getAssociatedEntitiesOfSystem (const SystemName &name) const
Gets the entities associated with a system. The system must be registered.
const std::unordered_map< SystemName, Signature > & getSystemSignatures () const
bool isComponentRequiredBySystem (const SystemName &system, ComponentID component) const
Checks if a component is required by a system.
bool isEntityAssociatedWithSystem (const SystemName &name, EntityID entity) const
Checks if an entity is associated with a system.
bool isSystemRegistered (const SystemName &name) const
Checks if a system is registered.
void registerSystem (const SystemName &name)
Registers a system in the system manager. It initializes the system data such as the signature and the associated entities. The system must not be registered.
Protected Attributes
std::unordered_map< SystemName, std::set< EntityID > > associatedEntities {}
A map of the names of the systems and their associated entities.
std::unordered_map< SystemName, Signature > systemSignatures {}
A map of the names of the systems and their signatures.
Friends
class ECSCoordinator
Detailed Description
Definition at line 18 of file SystemManager.h.
Constructor & Destructor Documentation
SystemManager()
GLESC::ECS::SystemManager::SystemManager () default
~SystemManager()
GLESC::ECS::SystemManager::~SystemManager () default
Member Function Documentation
addComponentRequirementToSystem()
void SystemManager::addComponentRequirementToSystem (const SystemName & name, ComponentID componentID)
Adds a component requirement to a system, this changes the entities that are considered associated with it. The system must be registered. The component must not be required by the system already.
Parameters
name The name of the system
componentID The ID of the component
Definition at line 60 of file SystemManager.cpp.
{
    D_ASSERT_TRUE(isSystemRegistered(name), "System must be registered before adding component requirement");
    D_ASSERT_FALSE(isComponentRequiredBySystem(name, componentID), "Component must not be required by system already");
    systemSignatures.find(name)->second.set(componentID);
    D_ASSERT_TRUE(isComponentRequiredBySystem(name, componentID), "Component must be required by system");
}
References D_ASSERT_FALSE, D_ASSERT_TRUE, isComponentRequiredBySystem(), GLESC::isIterable_v, isSystemRegistered(), and systemSignatures.
Referenced by GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem().
entityDestroyed()
void SystemManager::entityDestroyed (EntityID entity)
Removes the entity from the systems it is associated with.
Parameters
entity The ID of the destroyed entity
Definition at line 47 of file SystemManager.cpp.
{
    // Erase a destroyed entity from all system lists
    for (auto& [name, entitySet] : associatedEntities) {
        entitySet.erase(entity);
        D_ASSERT_TRUE(!isEntityAssociatedWithSystem(name, entity), "Entity must not be associated with system");
    }
}
References associatedEntities, D_ASSERT_TRUE, isEntityAssociatedWithSystem(), and GLESC::isIterable_v.
Referenced by GLESC::ECS::ECSCoordinator::destroyEntity().
entitySignatureChanged()
void SystemManager::entitySignatureChanged (EntityID entity, Signature entitySignature)
Adds the entity to the systems it is associated with and removes it from the systems it is no longer associated with.
Parameters
entity The ID of the entity
entitySignature The signature of the entity
Definition at line 32 of file SystemManager.cpp.
{
    D_ASSERT_FALSE(systemSignatures.empty(),
                   "All systems must be registered before entities can be associated with them");
    // Notify each system that an entity's signature changed
    for (auto& [name, entitySet] : associatedEntities) {
        if ((entitySignature & systemSignatures[name]) == systemSignatures[name]) {
            // If the systemSignature of the entity matches the systemSignature of the system, insert it into the set
            entitySet.insert(entity);
        }
        else {
            entitySet.erase(entity);
        }
    }
}
References associatedEntities, D_ASSERT_FALSE, GLESC::isIterable_v, and systemSignatures.
Referenced by GLESC::ECS::ECSCoordinator::addComponent(), and GLESC::ECS::ECSCoordinator::removeComponent().
getAllAssociatedEntities()
const std::unordered_map< SystemName, std::set< EntityID > > & GLESC::ECS::SystemManager::getAllAssociatedEntities () const inline
Definition at line 26 of file SystemManager.h.
{
            return associatedEntities;
        }
References associatedEntities.
getAssociatedEntitiesOfSystem()
const std::set< EntityID > & SystemManager::getAssociatedEntitiesOfSystem (const SystemName & name) const
Gets the entities associated with a system. The system must be registered.
Parameters
name The name of the system
Returns
A set of entities associated with the system
Definition at line 20 of file SystemManager.cpp.
{
    D_ASSERT_TRUE(isSystemRegistered(name), "System must be registered before getting associated entities");
    return associatedEntities.at(name);
}
References associatedEntities, D_ASSERT_TRUE, and isSystemRegistered().
Referenced by GLESC::ECS::ECSCoordinator::getAssociatedEntities(), and GLESC::ECS::ECSCoordinator::printStatus().
getSystemSignatures()
const std::unordered_map< SystemName, Signature > & GLESC::ECS::SystemManager::getSystemSignatures () const inline
Definition at line 30 of file SystemManager.h.
{
            return systemSignatures;
        }
References systemSignatures.
Referenced by GLESC::ECS::ECSCoordinator::printStatus().
isComponentRequiredBySystem()
bool SystemManager::isComponentRequiredBySystem (const SystemName & system, ComponentID component) const
Checks if a component is required by a system.
Parameters
system The name of the system
component The ID of the component
Returns
True if the component is required by the system, false otherwise
Definition at line 74 of file SystemManager.cpp.
{
    return systemSignatures.find(system)->second.test(component);
}
References GLESC::isIterable_v, and systemSignatures.
Referenced by addComponentRequirementToSystem().
isEntityAssociatedWithSystem()
bool SystemManager::isEntityAssociatedWithSystem (const SystemName & name, EntityID entity) const
Checks if an entity is associated with a system.
Parameters
name The name of the system
entity The ID of the entity
Returns
True if the entity is associated with the system, false otherwise
Definition at line 68 of file SystemManager.cpp.
{
    auto it = associatedEntities.find(name);
    return it != associatedEntities.end() && it->second.find(entity) != it->second.end();
}
References associatedEntities, and GLESC::isIterable_v.
Referenced by entityDestroyed(), and GLESC::ECS::ECSCoordinator::getAssociatedEntities().
isSystemRegistered()
bool SystemManager::isSystemRegistered (const SystemName & name) const
Checks if a system is registered.
Parameters
name The name of the system
Returns
True if the system is registered, false otherwise
Definition at line 55 of file SystemManager.cpp.
{
    // Check if name is contained in systems
    return systemSignatures.find(name) != systemSignatures.end();
}
References systemSignatures.
Referenced by GLESC::ECS::ECSCoordinator::addComponentRequirementToSystem(), addComponentRequirementToSystem(), GLESC::ECS::ECSCoordinator::getAssociatedEntities(), getAssociatedEntitiesOfSystem(), GLESC::ECS::ECSCoordinator::registerSystem(), and registerSystem().
registerSystem()
void SystemManager::registerSystem (const SystemName & name)
Registers a system in the system manager. It initializes the system data such as the signature and the associated entities. The system must not be registered.
Parameters
name
Definition at line 25 of file SystemManager.cpp.
{
    D_ASSERT_FALSE(isSystemRegistered(name), "System must not be registered");
    systemSignatures.try_emplace(name, Signature{});
    associatedEntities.try_emplace(name);
    D_ASSERT_TRUE(isSystemRegistered(name), "System must be registered after calling registerSystem");
}
References associatedEntities, D_ASSERT_FALSE, D_ASSERT_TRUE, isSystemRegistered(), and systemSignatures.
Referenced by GLESC::ECS::ECSCoordinator::registerSystem().
Friends And Related Symbol Documentation
ECSCoordinator
friend class ECSCoordinator friend
Definition at line 19 of file SystemManager.h.
Member Data Documentation
associatedEntities
std::unordered_map<SystemName, std::set<EntityID> > GLESC::ECS::SystemManager::associatedEntities {} protected
A map of the names of the systems and their associated entities.
Definition at line 107 of file SystemManager.h.
{};
Referenced by entityDestroyed(), entitySignatureChanged(), getAllAssociatedEntities(), getAssociatedEntitiesOfSystem(), isEntityAssociatedWithSystem(), and registerSystem().
systemSignatures
std::unordered_map<SystemName, Signature> GLESC::ECS::SystemManager::systemSignatures {} protected
A map of the names of the systems and their signatures.
Definition at line 111 of file SystemManager.h.
{};
Referenced by addComponentRequirementToSystem(), entitySignatureChanged(), getSystemSignatures(), isComponentRequiredBySystem(), isSystemRegistered(), and registerSystem().
The documentation for this class was generated from the following files:
SystemManager.h
SystemManager.cpp