GLESC: GLESC::Math::VectorAlgorithms Class Reference
GLESC::Math::VectorAlgorithms Class Reference
#include <VectorAlgorithms.h>
Static Public Member Functions
template<typename Type , size_t N>
static void abs (const VectorData< Type, N > &vec, VectorData< Type, N > &result)
Computes the absolute value of a vector.
template<typename Type , size_t N>
static Type angle (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Computes the rads between two vectors.
template<typename Type , size_t N>
static bool areOrthogonal (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Checks if two vectors are orthogonal.
template<typename Type , size_t N>
static bool areParallel (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Checks if two vectors are parallel.
template<typename Type , size_t N>
static void clampWithValues (const VectorData< Type, N > &vec, const Type &min, const Type &max, VectorData< Type, N > &result)
template<typename Type , size_t N>
static void clampWithVectors (const VectorData< Type, N > &vec, const VectorData< Type, N > &min, const VectorData< Type, N > &max, VectorData< Type, N > &result)
template<typename TypeResult , typename TypeLeft , typename TypeRight >
static void crossProduct (const VectorData< TypeLeft, 3 > &vec1, const VectorData< TypeRight, 3 > &vec2, VectorData< TypeResult, 3 > &result)
Computes the cross product of two vectors.
template<typename Type , size_t N>
static void dehomogenize (const VectorData< Type, N > &vec, VectorData< Type, N - 1 > &result)
Dehomogenizes a vector.
template<typename Type , size_t N>
static Type distance (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Computes the distance between two vectors.
template<typename Type , size_t N>
static Type distanceSquared (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Computes the squared distance between two vectors.
template<typename TypeLeft , typename TypeRight , size_t N>
static auto dotProduct (const VectorData< TypeLeft, N > &leftVec, const VectorData< TypeRight, N > &rightVec)
Computes the dot product of two vectors.
template<typename Type , size_t N>
static bool eq (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Equality operator for vectors.
template<typename Type , size_t N>
static void getOrthogonal (const VectorData< Type, N > &data, VectorData< Type, N > &result)
Gets an orthogonal vector to the input vector.
template<typename Type , size_t N>
static void homogenize (const VectorData< Type, N > &vec, VectorData< Type, N+1 > &result)
Homozenizes a vector.
template<typename Type , size_t N>
static bool isHomogeneous (const VectorData< Type, N > &vec)
Checks if a vector is homogeneous.
template<typename Type , size_t N>
static bool isMultipleOf (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
Checks if two vectors are collinear.
template<typename Type , size_t N>
static bool isNormalized (const VectorData< Type, N > &vec)
template<typename Type , size_t N>
static bool isZero (const VectorData< Type, N > &vec)
Checks if a vector is zero.
template<typename Type , size_t N>
static Type length (const VectorData< Type, N > &vec)
Computes the length of a vector.
template<typename Type , size_t N>
static Type lengthSquared (const VectorData< Type, N > &vec)
Computes the squared length of a vector.
template<typename Type , size_t N>
static void lerp (const VectorData< Type, N > &start, const VectorData< Type, N > &end, const Type &factor, VectorData< Type, N > &result)
template<typename Type , size_t N>
static bool lt (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
template<typename Type , size_t N>
static void makeForwardVector (const VectorData< Type, N > &rotationRads, VectorData< Type, N > &result)
Makes a forward vector from rotation angles.
template<typename Type , size_t N>
static void makeRightVector (const VectorData< Type, N > &rotationRads, VectorData< Type, N > &result)
Makes a right vector from rotation angles.
template<typename Type , size_t N>
static void makeUpVector (const VectorData< Type, N > &rotationRads, VectorData< Type, N > &result)
Makes an up vector from rotation angles.
template<typename Type , size_t N>
static void modWithValue (const VectorData< Type, N > &vec, const Type &mod, VectorData< Type, N > &result)
template<typename Type , size_t N>
static void modWithVector (const VectorData< Type, N > &vec, const VectorData< Type, N > &mod, VectorData< Type, N > &result)
template<typename Type , size_t N>
static bool neq (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2)
template<typename Type , size_t N>
static void normalize (const VectorData< Type, N > &vec, VectorData< Type, N > &result)
Normalizes a vector.
template<typename Type , size_t N>
static void project (const VectorData< Type, N > &vec, const VectorData< Type, N > &onto, VectorData< Type, N > &result)
Projects a vector onto another vector.
template<typename Type , size_t N>
static void reflect (const VectorData< Type, N > &vec, const VectorData< Type, N > &normal, VectorData< Type, N > &result)
Reflects a vector against a normal vector.
template<typename Type >
static void rotateVector3D (const VectorData< Type, 3 > &vec, const VectorData< Type, 3 > &rotationRads, VectorData< Type, 3 > &result)
Rotates a 3D vector by the given rotation angles.
template<typename Type , size_t N>
static Type sum (const VectorData< Type, N > &vec)
Computes the sum of all elements inside the vector.
template<typename Type , size_t N>
static std::string toString (const VectorData< Type, N > &vec)
Generates a string representation of a vector.
template<typename Type , size_t N>
static void vectorAdd (const VectorData< Type, N > &a, const VectorData< Type, N > &b, VectorData< Type, N > &result)
Adds two vectors.
template<typename Type , size_t N, size_t N2>
static void vectorCopy (VectorData< Type, N > &vecToCopyTo, const VectorData< Type, N2 > &vecToCopy)
template<typename Type , size_t N>
static void vectorDiv (const VectorData< Type, N > &dividend, const VectorData< Type, N > &divisor, VectorData< Type, N > &result)
Divides two vectors.
template<typename Type , size_t N>
static void vectorFill (VectorData< Type, N > &vec, const Type &value)
template<typename Type , size_t N>
static void vectorInitRawArray (VectorData< Type, N > &vec, const Type(&list)[N])
template<typename Type , size_t N>
static void vectorMove (VectorData< Type, N > &vecToMoveTo, VectorData< Type, N > &movedVec)
template<typename Type , size_t N>
static void vectorMul (const VectorData< Type, N > &vec1, const VectorData< Type, N > &vec2, VectorData< Type, N > &result)
Multiplies two vectors.
template<typename Type , size_t N>
static void vectorNegate (const VectorData< Type, N > &vec, VectorData< Type, N > &result)
Negates a vector.
template<typename Type , size_t N>
static void vectorScalarAdd (const VectorData< Type, N > &vec, const Type &scalar, VectorData< Type, N > &result)
Add a scalar to a vector.
template<typename Type , size_t N>
static void vectorScalarDiv (const VectorData< Type, N > &dividend, const Type &divisorScalar, VectorData< Type, N > &result)
Divides a vector by a scalar.
template<typename Type , size_t N>
static void vectorScalarMul (const VectorData< Type, N > &vec, const Type &scalar, VectorData< Type, N > &result)
Multiplies a vector by a scalar.
template<typename Type , size_t N>
static void vectorScalarSub (const VectorData< Type, N > &vec, const Type &scalar, VectorData< Type, N > &result)
Subtracts a scalar from a vector.
template<typename TypeResult , typename TypeLeft , typename TypeRight , size_t N>
static void vectorSub (const VectorData< TypeLeft, N > &vecLeft, const VectorData< TypeRight, N > &vecRight, VectorData< TypeResult, N > &result)
Subtracts two vectors.
template<typename Type >
static void vectorToEuler (const VectorData< Type, 3 > &direction, const VectorData< Type, 3 > &up, VectorData< Type, 3 > &rotation)
Converts a direction vector to Euler angles.
template<typename Type , size_t N>
static void vectorZero (VectorData< Type, N > &vec)
Detailed Description
Definition at line 17 of file VectorAlgorithms.h.
Member Function Documentation
abs()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::abs (const VectorData< Type, N > & vec, VectorData< Type, N > & result) inline static
Computes the absolute value of a vector.
Computes the absolute value of each element of a vector, it can be used for in place absolute value.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be used.
result Vector to store the absolute value of the input vector.
Returns
Absolute value of the vector.
Definition at line 350 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::abs(vec[i]);
            }
        }
References GLESC::Math::abs(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::abs(), and TYPED_TEST().
angle()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::angle (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Computes the rads between two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
Rads between the two vectors.
Definition at line 497 of file VectorAlgorithms.h.
{
            D_ASSERT_TRUE(length(vec1) * length(vec2) != Type(0), "Cannot compute angle between zero vectors");
            return std::acos(dotProduct(vec1, vec2) / (length(vec1) * length(vec2)));
        }
References D_ASSERT_TRUE, dotProduct(), GLESC::isIterable_v, and length().
Referenced by GLESC::Math::Vector< Type, N >::angle(), GLESC::Math::Vector< Type, N >::angleDegrees(), and TYPED_TEST().
areOrthogonal()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::areOrthogonal (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Checks if two vectors are orthogonal.
Two vectors are orthogonal if their dot product is zero.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
true if the vectors are orthogonal, false otherwise.
Definition at line 764 of file VectorAlgorithms.h.
{
            Type dot = dotProduct(vec1, vec2);
            return Math::eq(dot, Type(0));
        }
References dotProduct(), GLESC::Math::eq(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::isOrthogonal(), TYPED_TEST(), and TYPED_TEST().
areParallel()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::areParallel (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Checks if two vectors are parallel.
Two vectors are parallel if the absolute value of their dot product equals the product of their lengths.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
true if the vectors are parallel, false otherwise.
Definition at line 531 of file VectorAlgorithms.h.
{
            Type absDot = Math::abs(VectorAlgorithms::dotProduct(vec1, vec2));
            Type length1 = VectorAlgorithms::length(vec1);
            Type length2 = VectorAlgorithms::length(vec2);
            Type productOfLengths = length1 * length2;
            return Math::eq(absDot, productOfLengths); // Account for floating-point errors
        }
References GLESC::Math::abs(), dotProduct(), GLESC::Math::eq(), GLESC::isIterable_v, and length().
Referenced by GLESC::Math::Vector< Type, N >::isParallel(), and TYPED_TEST().
clampWithValues()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::clampWithValues (const VectorData< Type, N > & vec, const Type & min, const Type & max, VectorData< Type, N > & result) inline static
Definition at line 293 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::clamp(vec[i], min, max);
            }
        }
References GLESC::Math::clamp(), GLESC::isIterable_v, GLESC::Math::max(), and GLESC::Math::min().
Referenced by GLESC::Math::Vector< Type, N >::clamp(), TYPED_TEST(), and TYPED_TEST().
clampWithVectors()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::clampWithVectors (const VectorData< Type, N > & vec, const VectorData< Type, N > & min, const VectorData< Type, N > & max, VectorData< Type, N > & result) inline static
Definition at line 285 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::clamp(vec[i], min[i], max[i]);
            }
        }
References GLESC::Math::clamp(), GLESC::isIterable_v, GLESC::Math::max(), and GLESC::Math::min().
Referenced by GLESC::Math::Vector< Type, N >::clamp(), TYPED_TEST(), and TYPED_TEST().
crossProduct()
template<typename TypeResult , typename TypeLeft , typename TypeRight > static void GLESC::Math::VectorAlgorithms::crossProduct (const VectorData< TypeLeft, 3 > & vec1, const VectorData< TypeRight, 3 > & vec2, VectorData< TypeResult, 3 > & result) inline static
Computes the cross product of two vectors.
The cross product is a vector that is perpendicular to the two vectors being multiplied and the plane containing them. This only has meaning in 3D space. The magnitude of the cross product is the area of the parallelogram that the two vectors span. The direction of the cross product is orthogonal to both vectors, and follows the right-hand rule.
Note
Cross product is not commutative, is anti-commutative, meaning that a x b = -b x a.
Template Parameters
TypeResult Data type of the result vector (e.g., double, float).
TypeLeft Data type of the first vector (e.g., double, float).
TypeRight Data type of the second vector (e.g., double, float).
Parameters
vec1 First vector.
vec2 Second vector.
Returns
Cross product of the two vectors.
Definition at line 395 of file VectorAlgorithms.h.
{
            result[0] = vec1[1] * vec2[2] - vec1[2] * vec2[1];
            result[1] = vec1[2] * vec2[0] - vec1[0] * vec2[2];
            result[2] = vec1[0] * vec2[1] - vec1[1] * vec2[0];
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::VectorMixedAlgorithms::areCollinear(), GLESC::Math::Vector< Type, N >::cross(), getOrthogonal(), GLESC::Math::MatrixMixedAlgorithms::lookAt3D(), TYPED_TEST(), TYPED_TEST(), and vectorToEuler().
dehomogenize()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::dehomogenize (const VectorData< Type, N > & vec, VectorData< Type, N - 1 > & result) inline static
Dehomogenizes a vector.
Divides each element of the vector by the last element and removes the last element.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be dehomogenized.
result Vector to store the dehomogenized vector.
Definition at line 643 of file VectorAlgorithms.h.
{
            if (vec[N - 1] == Type(0))
                throw MathException("Cannot dehomogenize a vector with a zero w-component.");
            Type wInv = Type(1) / vec[N - 1]; // Inverse of the w-component
            for (size_t i = 0; i < N - 1; ++i) {
                result[i] = vec[i] * wInv; // Divide each component by the w-component
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::dehomogenize(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
distance()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::distance (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Computes the distance between two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
Distance between the two vectors.
Definition at line 445 of file VectorAlgorithms.h.
{
            VectorData<Type, N> diff;
            vectorSub(vec1, vec2, diff);
            return length(diff);
        }
References GLESC::isIterable_v, length(), and vectorSub().
Referenced by GLESC::Math::Vector< Type, N >::distance(), TYPED_TEST(), and TYPED_TEST().
distanceSquared()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::distanceSquared (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Computes the squared distance between two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
Squared distance between the two vectors.
Definition at line 461 of file VectorAlgorithms.h.
{
            VectorData<Type, N> diff;
            vectorSub(vec1, vec2, diff);
            return lengthSquared(diff);
        }
References GLESC::isIterable_v, lengthSquared(), and vectorSub().
Referenced by GLESC::Math::Vector< Type, N >::distanceSquared(), and TYPED_TEST().
dotProduct()
template<typename TypeLeft , typename TypeRight , size_t N> static auto GLESC::Math::VectorAlgorithms::dotProduct (const VectorData< TypeLeft, N > & leftVec, const VectorData< TypeRight, N > & rightVec) inline static
Computes the dot product of two vectors.
Also called Inner Product, it is the sum of the products of the corresponding elements of the two. Dot product gives us a sense of similarity between two vectors. Also, represents the projection of one vector onto another. This implementation is for cartesian coordinates in euclidean space only.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
leftVec First vector.
rightVec Second vector.
Returns
Dot product of the two vectors.
Definition at line 369 of file VectorAlgorithms.h.
{
            using CommonType = std::common_type_t<TypeLeft, TypeRight>;
            CommonType result = 0;
            for (size_t i = 0; i < N; ++i) {
                result += leftVec[i] * rightVec[i];
            }
            return result;
        }
References GLESC::isIterable_v.
Referenced by angle(), areOrthogonal(), areParallel(), GLESC::Math::Vector< Type, N >::dot(), length(), lengthSquared(), GLESC::Math::MatrixMixedAlgorithms::lookAt3D(), project(), reflect(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
eq()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::eq (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Equality operator for vectors.
Compares this vector to another, allowing for different underlying types. Handles floating-point comparison via 'eq' function.
Parameters
vec1 First vector
vec2 Second vector
Returns
True if the vectors are equal, false otherwise
Definition at line 240 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                if (!Math::eq(vec1[i], vec2[i])) {
                    return false;
                }
            }
            return true;
        }
References GLESC::Math::eq(), and GLESC::isIterable_v.
Referenced by isZero(), neq(), GLESC::Math::Vector< Type, N >::operator==(), and TYPED_TEST().
getOrthogonal()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::getOrthogonal (const VectorData< Type, N > & data, VectorData< Type, N > & result) inline static
Gets an orthogonal vector to the input vector.
Gets an orthogonal vector to the input vector in the same plane.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
data Input vector.
result Output orthogonal vector.
Definition at line 779 of file VectorAlgorithms.h.
{
            static_assert(N == 2 || N == 3 || N == 4, "getOrthogonal is only implemented for 2D, 3D, and 4D vectors");
            if constexpr (N == 2) {
                // In 2D, the orthogonal vector can be obtained by swapping the data
                // and negating one of them.
                result = {-data[1], data[0]};
            }
            else if constexpr (N == 3) {
                // In 3D, we use the cross product to find an orthogonal vector.
                // First, we need a non-parallel vector to cross with.
                // We choose either (0, 1, 0) or (1, 0, 0) depending on which one is less parallel
                // to the original vector, to avoid degenerate cross products.
                VectorData<Type, N> nonParallel;
                if (Math::abs(data[0]) > Math::abs(data[1]))
                    nonParallel = VectorData<Type, N>({0, 1, 0});
                else
                    nonParallel = VectorData<Type, N>({1, 0, 0});
                // The cross product of this vector with 'nonParallel' yields an orthogonal vector.
                VectorAlgorithms::crossProduct(data, nonParallel, result);
            }
            else if constexpr (N == 4) {
                // Finding an orthogonal vector in 4D involves more choices due to extra degrees of
                // freedom. Here, we zero out two data and solve the other two to maintain
                // orthogonality. The choice of which data to zero out depends on the
                // non-zero data of the original vector.
                if (data[0] != 0 || data[1] != 0) {
                    // If the first or second component is non-zero, we set the last two data
                    // to zero and negate one of the first two data to create orthogonality.
                    result = VectorData<Type, N>({-data[1], data[0], 0, 0});
                }
                else {
                    // If the first two data are zero, we work with the last two data.
                    // We negate one and copy the other to create orthogonality.
                    result = VectorData<Type, N>({0, -data[3], data[2], 0});
                }
            }
        }
References GLESC::Math::abs(), crossProduct(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::getOrthogonal(), TYPED_TEST(), and TYPED_TEST().
homogenize()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::homogenize (const VectorData< Type, N > & vec, VectorData< Type, N+1 > & result) inline static
Homozenizes a vector.
Adds a 1 to the end of the vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be homogenized.
result Vector to store the homogenized vector.
Definition at line 629 of file VectorAlgorithms.h.
{
            VectorAlgorithms::vectorCopy(result, vec); // Copies until the Nth element
            result[N] = Type(1); // Set the N+1th element to 1
        }
References GLESC::isIterable_v, and vectorCopy().
Referenced by GLESC::Math::Vector< Type, N >::homogenize(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
isHomogeneous()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::isHomogeneous (const VectorData< Type, N > & vec) inline static
Checks if a vector is homogeneous.
A vector is homogeneous if its last element is 1.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be checked.
Returns
true if the vector is homogeneous, false otherwise.
Definition at line 617 of file VectorAlgorithms.h.
{
            return vec[N - 1] == Type(1);
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::isHomogeneous(), and TYPED_TEST().
isMultipleOf()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::isMultipleOf (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Checks if two vectors are collinear.
Two vectors are collinear if one is a scalar multiple of the other.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
true if the vectors are collinear, false otherwise.
Definition at line 829 of file VectorAlgorithms.h.
{
            Type ratio;
            bool ratioInitialized = false;
            for (size_t i = 0; i < N; ++i) {
                if (!Math::eq(vec2[i], Type(0))) {
                    if (!ratioInitialized) {
                        ratio = vec1[i] / vec2[i];
                        ratioInitialized = true;
                    }
                    else {
                        if (!Math::eq(vec1[i] / vec2[i], ratio)) {
                            return false;
                        }
                    }
                }
                else if (!Math::eq(vec1[i], Type(0))) {
                    return false;
                }
            }
            return true;
        }
References GLESC::Math::eq(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::isMultipleOf().
isNormalized()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::isNormalized (const VectorData< Type, N > & vec) inline static
Definition at line 431 of file VectorAlgorithms.h.
{
            return Math::eq(length(vec), Type(1));
        }
References GLESC::Math::eq(), GLESC::isIterable_v, and length().
Referenced by GLESC::Math::Vector< Type, N >::isNormalized().
isZero()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::isZero (const VectorData< Type, N > & vec) inline static
Checks if a vector is zero.
A vector is zero if all its elements are zero.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be checked.
Returns
true if the vector is zero, false otherwise.
Definition at line 278 of file VectorAlgorithms.h.
{
            VectorData<Type, N> zeroVec;
            VectorAlgorithms::vectorFill(zeroVec, Type(0));
            return eq(vec, zeroVec);
        }
References eq(), GLESC::isIterable_v, and vectorFill().
Referenced by GLESC::Math::VectorMixedAlgorithms::areCollinear(), GLESC::Math::Vector< Type, N >::isZero(), and TYPED_TEST().
length()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::length (const VectorData< Type, N > & vec) inline static
Computes the length of a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector.
Returns
Length of the vector.
Definition at line 412 of file VectorAlgorithms.h.
{
            return Math::sqrt(dotProduct(vec, vec));
        }
References dotProduct(), GLESC::isIterable_v, and GLESC::Math::sqrt().
Referenced by angle(), areParallel(), distance(), isNormalized(), GLESC::Math::Vector< Type, N >::length(), GLESC::Math::Vector< Type, N >::magnitude(), normalize(), project(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
lengthSquared()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::lengthSquared (const VectorData< Type, N > & vec) inline static
Computes the squared length of a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector.
Returns
Squared length of the vector.
Definition at line 425 of file VectorAlgorithms.h.
{
            return dotProduct(vec, vec);
        }
References dotProduct(), and GLESC::isIterable_v.
Referenced by distanceSquared(), GLESC::Math::Vector< Type, N >::lengthSquared(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
lerp()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::lerp (const VectorData< Type, N > & start, const VectorData< Type, N > & end, const Type & factor, VectorData< Type, N > & result) inline static
Definition at line 316 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::lerp(start[i], end[i], factor);
            }
        }
References GLESC::isIterable_v, and GLESC::Math::lerp().
Referenced by GLESC::Math::Vector< Type, N >::lerp().
lt()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::lt (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Definition at line 256 of file VectorAlgorithms.h.
{
            // Use of length squared is more efficient
            auto length1 = VectorAlgorithms::sum(vec1);
            auto length2 = VectorAlgorithms::sum(vec2);
            return length1 < length2;
        }
References GLESC::isIterable_v, and sum().
Referenced by GLESC::Math::Vector< Type, N >::operator<(), and TYPED_TEST().
makeForwardVector()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::makeForwardVector (const VectorData< Type, N > & rotationRads, VectorData< Type, N > & result) inline static
Makes a forward vector from rotation angles.
Computes the forward vector from the rotation angles (pitch, yaw, roll).
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
rotationRads Rotation angles in radians.
result Vector to store the forward vector.
Definition at line 663 of file VectorAlgorithms.h.
{
            Type pitch = rotationRads[0];
            Type yaw = rotationRads[1];
            result[0] = Math::cos(-pitch) * Math::sin(yaw);
            result[1] = Math::sin(-pitch);
            result[2] = Math::cos(-pitch) * Math::cos(yaw);
        }
References GLESC::Math::cos(), GLESC::isIterable_v, and GLESC::Math::sin().
Referenced by GLESC::Math::Vector< Type, N >::makeForward().
makeRightVector()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::makeRightVector (const VectorData< Type, N > & rotationRads, VectorData< Type, N > & result) inline static
Makes a right vector from rotation angles.
Computes the right vector from the rotation angles (pitch, yaw, roll).
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
rotationRads Rotation angles in radians.
result Vector to store the right vector.
Definition at line 681 of file VectorAlgorithms.h.
{
            Type pitch = rotationRads[0];
            Type yaw = rotationRads[1];
            Type roll = rotationRads[2];
            result[0] = Math::cos(pitch) * Math::sin(yaw - Math::PI / 2);
            result[1] = Math::sin(roll);
            result[2] = Math::cos(pitch) * Math::cos(yaw - Math::PI / 2);
        }
References GLESC::Math::cos(), GLESC::isIterable_v, GLESC::Math::PI, and GLESC::Math::sin().
Referenced by GLESC::Math::Vector< Type, N >::makeRight().
makeUpVector()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::makeUpVector (const VectorData< Type, N > & rotationRads, VectorData< Type, N > & result) inline static
Makes an up vector from rotation angles.
Computes the up vector from the rotation angles (pitch, yaw, roll).
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
rotationRads Rotation angles in radians.
result Vector to store the up vector.
Definition at line 700 of file VectorAlgorithms.h.
{
            Type pitch = rotationRads[0];
            Type yaw = rotationRads[1];
            Type roll = rotationRads[2];
            result[0] = -Math::cos(roll) * Math::sin(pitch) * Math::sin(yaw) + Math::sin(roll) * Math::cos(yaw); // up_x
            result[1] = Math::cos(roll) * Math::cos(pitch); // up_y
            result[2] = -Math::cos(roll) * Math::sin(pitch) * Math::cos(yaw) - Math::sin(roll) * Math::sin(yaw); // up_z
        }
References GLESC::Math::cos(), GLESC::isIterable_v, and GLESC::Math::sin().
Referenced by GLESC::Math::Vector< Type, N >::makeUp().
modWithValue()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::modWithValue (const VectorData< Type, N > & vec, const Type & mod, VectorData< Type, N > & result) inline static
Definition at line 301 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::mod(vec[i], mod);
            }
        }
References GLESC::isIterable_v, and GLESC::Math::mod().
Referenced by GLESC::Math::Vector< Type, N >::mod().
modWithVector()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::modWithVector (const VectorData< Type, N > & vec, const VectorData< Type, N > & mod, VectorData< Type, N > & result) inline static
Definition at line 308 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = Math::mod(vec[i], mod[i]);
            }
        }
References GLESC::isIterable_v, and GLESC::Math::mod().
Referenced by GLESC::Math::Vector< Type, N >::mod().
neq()
template<typename Type , size_t N> static bool GLESC::Math::VectorAlgorithms::neq (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2) inline static
Definition at line 251 of file VectorAlgorithms.h.
{
            return !eq(vec1, vec2);
        }
References eq(), and GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator!=(), and TYPED_TEST().
normalize()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::normalize (const VectorData< Type, N > & vec, VectorData< Type, N > & result) inline static
Normalizes a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be normalized.
Returns
Normalized vector.
Definition at line 476 of file VectorAlgorithms.h.
{
            Type length = VectorAlgorithms::length(vec);
            if (Math::eq(length, Type(1)) || Math::eq(length, Type(0))) {
                result = vec;
                return;
            }
            for (size_t i = 0; i < N; ++i)
                result[i] = vec[i] / length;
        }
References GLESC::Math::eq(), GLESC::isIterable_v, and length().
Referenced by GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrixForAxis(), GLESC::Math::MatrixMixedAlgorithms::lookAt3D(), GLESC::Math::Vector< Type, N >::normalize(), GLESC::Math::Vector< Type, N >::normalize(), reflect(), TYPED_TEST(), and vectorToEuler().
project()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::project (const VectorData< Type, N > & vec, const VectorData< Type, N > & onto, VectorData< Type, N > & result) inline static
Projects a vector onto another vector.
Projects a vector onto another vector by computing the scalar projection and multiplying it by the unit vector of the second vector.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be projected.
onto Vector to be projected onto.
Returns
Projected vector.
Definition at line 514 of file VectorAlgorithms.h.
{
            Type scalarProjection = dotProduct(vec, onto) / length(onto);
            VectorAlgorithms::vectorScalarMul(onto, scalarProjection, result);
        }
References dotProduct(), GLESC::isIterable_v, length(), and vectorScalarMul().
Referenced by GLESC::Math::Vector< Type, N >::project(), and TYPED_TEST().
reflect()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::reflect (const VectorData< Type, N > & vec, const VectorData< Type, N > & normal, VectorData< Type, N > & result) inline static
Reflects a vector against a normal vector.
Computes the reflection of a vector against a given normal vector.
Template Parameters
Type Data type of the vectors (e.g., double, float).
Parameters
vec The vector to be reflected.
normal The normal vector to reflect against.
result The reflected vector.
Definition at line 548 of file VectorAlgorithms.h.
{
            VectorData<Type, N> normalizedNormal;
            VectorAlgorithms::normalize(normal, normalizedNormal);
            Type dotProd = VectorAlgorithms::dotProduct(vec, normalizedNormal);
            for (size_t i = 0; i < N; ++i) {
                result[i] = vec[i] - normalizedNormal[i] * dotProd * 2.0f;
            }
        }
References dotProduct(), GLESC::isIterable_v, and normalize().
Referenced by GLESC::Math::Vector< Type, N >::reflect(), and GLESC::Math::Vector< Type, N >::reflect().
rotateVector3D()
template<typename Type > static void GLESC::Math::VectorAlgorithms::rotateVector3D (const VectorData< Type, 3 > & vec, const VectorData< Type, 3 > & rotationRads, VectorData< Type, 3 > & result) inline static
Rotates a 3D vector by the given rotation angles.
Rotates a 3D vector by the given rotation angles (pitch, yaw, roll). Rotating a vector means rotating a vector around the origin of the coordinate system. Imagine the vector as an arrow pointing from the origin to the vector's tip, we rotate the arrow.
Template Parameters
Type Data type of the vector (e.g., double, float).
Parameters
vec Vector to be rotated.
rotationRads Rotation angles in radians.
result Vector to store the rotated vector.
Definition at line 721 of file VectorAlgorithms.h.
{
            Type cosX = Math::cos(rotationRads[0]);
            Type sinX = Math::sin(rotationRads[0]);
            Type cosY = Math::cos(rotationRads[1]);
            Type sinY = Math::sin(rotationRads[1]);
            Type cosZ = Math::cos(rotationRads[2]);
            Type sinZ = Math::sin(rotationRads[2]);
            // Rotation matrix for X axis
            VectorData<Type, 3> rotatedX = {
                vec[0],
                vec[1] * cosX - vec[2] * sinX,
                vec[1] * sinX + vec[2] * cosX
            };
            // Rotation matrix for Y axis
            VectorData<Type, 3> rotatedY = {
                rotatedX[0] * cosY + rotatedX[2] * sinY,
                rotatedX[1],
                -rotatedX[0] * sinY + rotatedX[2] * cosY
            };
            // Rotation matrix for Z axis
            result = {
                rotatedY[0] * cosZ - rotatedY[1] * sinZ,
                rotatedY[0] * sinZ + rotatedY[1] * cosZ,
                rotatedY[2]
            };
        }
References GLESC::Math::cos(), GLESC::isIterable_v, and GLESC::Math::sin().
Referenced by GLESC::Math::Vector< Type, N >::rotate(), and GLESC::Math::Vector< Type, N >::rotate().
sum()
template<typename Type , size_t N> static Type GLESC::Math::VectorAlgorithms::sum (const VectorData< Type, N > & vec) inline static
Computes the sum of all elements inside the vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be used.
Returns
Sum of the vector.
Definition at line 331 of file VectorAlgorithms.h.
{
            Type result = 0;
            for (size_t i = 0; i < N; ++i) {
                result += vec[i];
            }
            return result;
        }
References GLESC::isIterable_v.
Referenced by lt(), GLESC::Math::Vector< Type, N >::sum(), TYPED_TEST(), and TYPED_TEST().
toString()
template<typename Type , size_t N> static std::string GLESC::Math::VectorAlgorithms::toString (const VectorData< Type, N > & vec) inline static
Generates a string representation of a vector.
Generates a string representation of a vector by calling the toString method of each element.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be converted to string.
Returns
String representation of the vector.
Definition at line 863 of file VectorAlgorithms.h.
{
            std::string result;
            result += "[";
            if constexpr (std::is_arithmetic_v<Type>) {
                for (size_t i = 0; i < N; ++i) {
                    result += std::to_string(vec[i]) + ", ";
                }
            }
            else {
                for (size_t i = 0; i < N; ++i) {
                    result += vec[i].toString() + ", ";
                }
            }
            result.pop_back();
            result.pop_back();
            result += "]";
            return result;
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::toString().
vectorAdd()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorAdd (const VectorData< Type, N > & a, const VectorData< Type, N > & b, VectorData< Type, N > & result) inline static
Adds two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
a First vector.
b Second vector.
Returns
Sum of the two vectors.
Definition at line 81 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = a[i] + b[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator+(), GLESC::Math::Vector< Type, N >::operator+=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorCopy()
template<typename Type , size_t N, size_t N2> static void GLESC::Math::VectorAlgorithms::vectorCopy (VectorData< Type, N > & vecToCopyTo, const VectorData< Type, N2 > & vecToCopy) inline static
Definition at line 45 of file VectorAlgorithms.h.
{
            if constexpr (N == N2) // This is needed because you can't compare pointers to different types
                if (&vecToCopyTo == &vecToCopy) {
                    return;
                }
            constexpr size_t minOfTheTwo = std::min(N, N2); // So we don't go out of bounds
            for (size_t i = 0; i < minOfTheTwo; ++i) {
                vecToCopyTo[i] = vecToCopy[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), homogenize(), GLESC::Math::Vector< Type, N >::operator=(), and TYPED_TEST().
vectorDiv()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorDiv (const VectorData< Type, N > & dividend, const VectorData< Type, N > & divisor, VectorData< Type, N > & result) inline static
Divides two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
dividend First vector.
divisor Second vector.
Returns
Product of the two vectors.
Definition at line 203 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = dividend[i] / divisor[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator/(), GLESC::Math::Vector< Type, N >::operator/=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorFill()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorFill (VectorData< Type, N > & vec, const Type & value) inline static
Definition at line 32 of file VectorAlgorithms.h.
{
            std::fill(std::begin(vec), std::end(vec), value);
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), isZero(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorInitRawArray()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorInitRawArray (VectorData< Type, N > & vec, const Type(&) list[N]) inline static
Definition at line 38 of file VectorAlgorithms.h.
{
            std::copy(std::begin(list), std::end(list), std::begin(vec));
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::operator=(), and TYPED_TEST().
vectorMove()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorMove (VectorData< Type, N > & vecToMoveTo, VectorData< Type, N > & movedVec) inline static
Definition at line 59 of file VectorAlgorithms.h.
{
            if (&vecToMoveTo == &movedVec) {
                return;
            }
            std::move(std::begin(movedVec), std::end(movedVec), std::begin(vecToMoveTo));
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::Vector(), GLESC::Math::Vector< Type, N >::operator=(), and TYPED_TEST().
vectorMul()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorMul (const VectorData< Type, N > & vec1, const VectorData< Type, N > & vec2, VectorData< Type, N > & result) inline static
Multiplies two vectors.
Template Parameters
Type Data type of the vectors (e.g., double, float).
N Dimension of space.
Parameters
vec1 First vector.
vec2 Second vector.
Returns
Product of the two vectors.
Definition at line 168 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = vec1[i] * vec2[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator*(), GLESC::Math::Vector< Type, N >::operator*=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorNegate()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorNegate (const VectorData< Type, N > & vec, VectorData< Type, N > & result) inline static
Negates a vector.
Negates each element of a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be negated.
Returns
Negated vector.
Definition at line 151 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = -vec[i];
            }
        }
References GLESC::isIterable_v.
Referenced by calculateGlmViewMatrix(), GLESC::Math::MatrixMixedAlgorithms::calculateViewMatrixPosRot(), GLESC::Math::Vector< Type, N >::operator-(), TYPED_TEST(), and TYPED_TEST().
vectorScalarAdd()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorScalarAdd (const VectorData< Type, N > & vec, const Type & scalar, VectorData< Type, N > & result) inline static
Add a scalar to a vector.
Adds a scalar to each element of a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be added to.
scalar Scalar to add to the vector.
Returns
Sum of the vector and the scalar.
Definition at line 98 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = vec[i] + scalar;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator+(), GLESC::Math::Vector< Type, N >::operator+=(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorScalarDiv()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorScalarDiv (const VectorData< Type, N > & dividend, const Type & divisorScalar, VectorData< Type, N > & result) inline static
Divides a vector by a scalar.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
dividend Vector to be divided.
divisorScalar Scalar to divide the vector by.
Returns
Quotient of the vector and the scalar.
Definition at line 221 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = dividend[i] / divisorScalar;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator/(), GLESC::Math::Vector< Type, N >::operator/=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorScalarMul()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorScalarMul (const VectorData< Type, N > & vec, const Type & scalar, VectorData< Type, N > & result) inline static
Multiplies a vector by a scalar.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be multiplied.
scalar Scalar to multiply the vector by.
Returns
Product of the vector and the scalar.
Definition at line 185 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = vec[i] * scalar;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrixForAxis(), GLESC::Math::Vector< Type, N >::operator*(), GLESC::Math::Vector< Type, N >::operator*=(), project(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorScalarSub()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorScalarSub (const VectorData< Type, N > & vec, const Type & scalar, VectorData< Type, N > & result) inline static
Subtracts a scalar from a vector.
Subtracts a scalar from each element of a vector.
Template Parameters
Type Data type of the vector (e.g., double, float).
N Dimension of space.
Parameters
vec Vector to be subtracted from.
scalar Scalar to subtract from the vector.
Returns
Difference of the vector and the scalar.
Definition at line 136 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = vec[i] - scalar;
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::operator-(), GLESC::Math::Vector< Type, N >::operator-=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorSub()
template<typename TypeResult , typename TypeLeft , typename TypeRight , size_t N> static void GLESC::Math::VectorAlgorithms::vectorSub (const VectorData< TypeLeft, N > & vecLeft, const VectorData< TypeRight, N > & vecRight, VectorData< TypeResult, N > & result) inline static
Subtracts two vectors.
result = vecLeft - vecRight
Template Parameters
TypeResult Data type of the result vector (e.g., double, float).
TypeLeft Data type of the first vector (e.g., double, float).
TypeRight Data type of the second vector (e.g., double, float).
N Dimension of space.
Parameters
vecLeft First vector.
vecRight Second vector.
Returns
Difference of the two vectors.
Definition at line 116 of file VectorAlgorithms.h.
{
            for (size_t i = 0; i < N; ++i) {
                result[i] = vecLeft[i] - vecRight[i];
            }
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::VectorMixedAlgorithms::areCollinear(), distance(), distanceSquared(), GLESC::Math::MatrixMixedAlgorithms::lookAt3D(), GLESC::Math::Vector< Type, N >::operator-(), GLESC::Math::Vector< Type, N >::operator-=(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
vectorToEuler()
template<typename Type > static void GLESC::Math::VectorAlgorithms::vectorToEuler (const VectorData< Type, 3 > & direction, const VectorData< Type, 3 > & up, VectorData< Type, 3 > & rotation) inline static
Converts a direction vector to Euler angles.
Converts a direction vector to Euler angles (pitch, yaw, roll).
Template Parameters
Type Data type of the vector (e.g., double, float).
Parameters
direction The direction vector.
up The up vector.
rotation Output vector for pitch, yaw, and roll.
Definition at line 568 of file VectorAlgorithms.h.
{
            VectorData<Type, 3> normalizedDirection;
            VectorAlgorithms::normalize(direction, normalizedDirection);
            VectorData<Type, 3> right;
            VectorAlgorithms::crossProduct(normalizedDirection, up, right);
            VectorAlgorithms::normalize(right, right);
            VectorData<Type, 3> newUp;
            VectorAlgorithms::crossProduct(right, normalizedDirection, newUp);
            Type pitch, yaw, roll;
            // Calculate yaw (rotation around the y-axis)
            if (!Math::eq(normalizedDirection[0], Type(0)) || !Math::eq(normalizedDirection[2], Type(0))) {
                yaw = Math::atan2(normalizedDirection[0], normalizedDirection[2]);
            }
            else {
                yaw = 0;
            }
            // Calculate pitch (rotation around the x-axis)
            Type horizontalDist = Math::sqrt(
                normalizedDirection[0] * normalizedDirection[0] + normalizedDirection[2] * normalizedDirection[2]);
            pitch = Math::atan2(-normalizedDirection[1], horizontalDist);
            // Calculate roll (rotation around the z-axis)
            if (!Math::eq(up[0], Type(0)) || !Math::eq(up[1], Type(0)) || !Math::eq(up[2], Type(0))) {
                roll = Math::atan2(newUp[0], newUp[1]);
            }
            else {
                roll = 0;
            }
            rotation[0] = pitch;
            rotation[1] = yaw;
            rotation[2] = roll;
        }
References GLESC::Math::atan2(), crossProduct(), GLESC::Math::eq(), GLESC::isIterable_v, normalize(), and GLESC::Math::sqrt().
Referenced by GLESC::Math::Vector< Type, N >::vectorToEulerRotation(), and GLESC::Math::Vector< Type, N >::vectorToEulerRotation().
vectorZero()
template<typename Type , size_t N> static void GLESC::Math::VectorAlgorithms::vectorZero (VectorData< Type, N > & vec) inline static
Definition at line 25 of file VectorAlgorithms.h.
{
            std::fill(std::begin(vec), std::end(vec), Type(0));
        }
References GLESC::isIterable_v.
Referenced by GLESC::Math::Vector< Type, N >::Vector(), TYPED_TEST(), TYPED_TEST(), and TYPED_TEST().
The documentation for this class was generated from the following file:
VectorAlgorithms.h