GLESC: GLESC::Render::TextureVertex Class Reference
GLESC::Render::TextureVertex Class Reference
Represents a vertex with texture coordinates.
#include <Vertex.h>
Public Member Functions
TextureVertex (const Position &position, const Normal &normal, UV textureCoordinate)
const UV & getTextureCoordinate () const
bool operator== (const TextureVertex &other) const
void setTextureCoordinate (const UV &textureCoordinateParam)
std::string toString () const
Public Member Functions inherited from GLESC::Render::BaseVertex
BaseVertex (Position position, Normal normal)
Normal & getNormal ()
const Normal & getNormal () const
Position & getPosition ()
const Position & getPosition () const
bool operator== (const BaseVertex &other) const
void setNormal (const Normal &normalParam)
void setPosition (const Position &positionParam)
std::string toString () const
Static Public Member Functions
static const std::vector< GAPI::Enums::Types > & getLayout ()
Static Public Member Functions inherited from GLESC::Render::BaseVertex
static const std::vector< GAPI::Enums::Types > & getLayout ()
Private Attributes
UV textureCoordinate
Static Private Attributes
static std::vector< GAPI::Enums::Types > layout
Additional Inherited Members
Static Public Attributes inherited from GLESC::Render::BaseVertex
static std::vector< GAPI::Enums::Types > layout
Detailed Description
Represents a vertex with texture coordinates.
This is tightly packed, and so are all of its members
Definition at line 74 of file Vertex.h.
Constructor & Destructor Documentation
TextureVertex()
GLESC::Render::TextureVertex::TextureVertex (const Position & position, const Normal & normal, UV textureCoordinate) inline
Definition at line 77 of file Vertex.h.
            : BaseVertex(position, normal), textureCoordinate(std::move(textureCoordinate)) {
        }
Member Function Documentation
getLayout()
static const std::vector< GAPI::Enums::Types > & GLESC::Render::TextureVertex::getLayout () inline static
Definition at line 76 of file Vertex.h.
{ return layout; }
References layout.
getTextureCoordinate()
const UV & GLESC::Render::TextureVertex::getTextureCoordinate () const inline
Definition at line 85 of file Vertex.h.
{ return textureCoordinate; }
References textureCoordinate.
operator==()
bool GLESC::Render::TextureVertex::operator== (const TextureVertex & other) const inline
Definition at line 81 of file Vertex.h.
{
            return BaseVertex::operator==(other) && textureCoordinate == other.textureCoordinate;
        }
References GLESC::isIterable_v, GLESC::Render::BaseVertex::operator==(), and textureCoordinate.
setTextureCoordinate()
void GLESC::Render::TextureVertex::setTextureCoordinate (const UV & textureCoordinateParam) inline
Definition at line 86 of file Vertex.h.
{ textureCoordinate = textureCoordinateParam; }
References GLESC::isIterable_v, and textureCoordinate.
toString()
std::string GLESC::Render::TextureVertex::toString () const inline
Definition at line 87 of file Vertex.h.
{
            return BaseVertex::toString() + " Texture Coordinate: " + textureCoordinate.toString();
        }
References textureCoordinate, GLESC::Math::Vector< Type, N >::toString(), and GLESC::Render::BaseVertex::toString().
Member Data Documentation
layout
std::vector< GLESC::GAPI::Enums::Types > GLESC::Render::TextureVertex::layout static private
Initial value:
= {
    GAPI::Enums::Types::Vec3F,
    GAPI::Enums::Types::Vec3F,
    GAPI::Enums::Types::Vec2F
}
Definition at line 17 of file Vertex.h.
          :
        [[nodisacrd]] static const std::vector<GAPI::Enums::Types>& getLayout() { return layout; }
        BaseVertex(Position  position, Normal  normal)
            : position(std::move(position)), normal(std::move(normal)) {
        }
Referenced by getLayout().
textureCoordinate
UV GLESC::Render::TextureVertex::textureCoordinate private
Definition at line 91 of file Vertex.h.
Referenced by getTextureCoordinate(), operator==(), setTextureCoordinate(), and toString().
The documentation for this class was generated from the following files:
Vertex.h
Vertex.cpp