GLESC: GLESC::Math::Plane Class Reference
GLESC::Math::Plane Class Reference
#include <Plane.h>
Public Member Functions
Plane ()
Construct a new Plane object.
Plane (const Direction &normalParam, float distanceParam)
Construct a new Plane object from a normal vector and a distance.
Plane (const Plane &plane)=default
Construct a new Plane object from another plane. Default copy constructor.
Plane (const Point &point, const Direction &normalParam)
Construct a new Plane object from a point and a normal vector.
Plane (const Point &point, const Line &line)
Construct a new Plane object from a point and a line.
Plane (const Point &point1, const Point &point2, const Point &point3)
Construct a new Plane object from three distinct points.
Plane (Plane &&plane)=default
Construct a new Plane object from another plane. Default move constructor.
~Plane ()=default
Destroy the Plane object. Default destructor.
Distance distanceToPoint (const Point &point) const
Calculate the distance from the plane to a point.
Distance getDistance () const
Get the distance from the origin to the plane.
const Direction & getNormal () const
Get the normal vector of the plane.
bool hasInside (const Point &point) const
Check if a point is inside the plane.
bool intersects (const Line &line) const
Checks if the plane intersects with a given line.
bool intersects (const Line &line, Point &intersectionPoint) const
Checks if the plane intersects with a given line and sets the intersection point if it exists. The parameter intersectionPoint is set to the intersection point.
bool intersects (const Plane &plane) const
bool intersects (const Point &point) const
void normalize ()
Normalize the normal vector of the plane.
Plane & operator= (const Plane &plane)=default
Assign a plane to another plane. Default copy assignment operator.
Plane & operator= (Plane &&plane)=default
Assign a plane to another plane. Default move assignment operator.
bool operator== (const Plane &other) const
Compare two planes for equality.
void setDistance (Distance distanceParam)
Set the distance from the origin to the plane.
void setNormal (const Direction &normalParam)
Set the normal vector of the plane.
std::string toString () const
Convert the plane to a string.
Static Private Member Functions
static Distance calculateDistanceFromPointAndLine (const Point &point, const Line &line)
Calculate the distance from the origin to the plane defined by a point and a line.
static Distance calculateDistanceFromPointAndNormal (const Point &point, const Direction &normal)
Calculate the distance from the origin to the plane defined by a point on the plane and the plane's normal vector.
static Distance calculateDistanceFromPoints (const Point &point1, const Point &point2, const Point &point3)
Calculate the distance from the origin to the plane defined by three distinct points.
static Direction calculateNormalFromPointAndLine (const Point &point, const Line &line)
Calculate the normal vector of the plane defined by a point and a line.
static Direction calculateNormalFromPoints (const Point &firstPoint, const Point &secondPoint, const Point &thirdPoint)
Calculate the normal vector of the plane defined by three distinct points.
Private Attributes
Distance distance {}
The distance from the origin to the plane along its normal.
Direction normal {}
The unit vector normal to the plane. Defines the orientation of the plane.
Detailed Description
Definition at line 18 of file Plane.h.
Constructor & Destructor Documentation
Plane() [1/7]
Plane::Plane ()
Construct a new Plane object.
The default constructor creates a plane with the normal vector (0, 0, 1) and distance 0. Constructs a "zero plane".
Definition at line 14 of file Plane.cpp.
             : Plane(Direction(0, 0, 1), 0) {
}
Plane() [2/7]
Plane::Plane (const Direction & normalParam, float distanceParam)
Construct a new Plane object from a normal vector and a distance.
The normal vector is normalized if its length is greater than 1. The normal cannot be a zero vector. The distance is the distance from the origin to the plane. It can be any real number (positive, negative or zero).
Parameters
normalParam The normal vector of the plane.
distanceParam The distance from the origin to the plane.
Definition at line 18 of file Plane.cpp.
{
    setNormal(normalParam);
    setDistance(distanceParam);
}
References GLESC::isIterable_v, setDistance(), and setNormal().
Plane() [3/7]
Plane::Plane (const Point & point, const Direction & normalParam)
Construct a new Plane object from a point and a normal vector.
The normal vector is normalized if its length is greater than 1. The normal cannot be a zero vector.
Parameters
point
normalParam
Definition at line 23 of file Plane.cpp.
{
    setNormal(normalParam);
    setDistance(calculateDistanceFromPointAndNormal(point, normalParam));
}
References calculateDistanceFromPointAndNormal(), GLESC::isIterable_v, setDistance(), and setNormal().
Plane() [4/7]
Plane::Plane (const Point & point1, const Point & point2, const Point & point3)
Construct a new Plane object from three distinct points.
The normal vector of the plane is calculated from the three points. The distance is the distance from the origin to the plane. The points must be distinct and not lie on the same line.
Parameters
point1 The first point.
point2 The second point.
point3 The third point.
Definition at line 28 of file Plane.cpp.
{
    D_ASSERT_TRUE((point1 != point2 && point1 != point3 && point2 != point3), "Points must be different");
    D_ASSERT_TRUE(!VectorMixedAlgorithms::areCollinear(point1.data, point2.data, point3.data),
                  "Points must not lie on the same line");
    setNormal(calculateNormalFromPoints(point1, point2, point3));
    setDistance(calculateDistanceFromPoints(point1, point2, point3));
}
References GLESC::Math::VectorMixedAlgorithms::areCollinear(), calculateDistanceFromPoints(), calculateNormalFromPoints(), D_ASSERT_TRUE, GLESC::isIterable_v, setDistance(), and setNormal().
Plane() [5/7]
Plane::Plane (const Point & point, const Line & line)
Construct a new Plane object from a point and a line.
The normal vector of the plane is calculated from the point and the line. The distance is the distance from the origin to the plane. The point must not lie on the line.
Parameters
point A point not on the line.
line A line not containing the point.
Definition at line 37 of file Plane.cpp.
{
    D_ASSERT_TRUE(!line.intersects(point), "Point must not lie on the line");
    setNormal(calculateNormalFromPointAndLine(point, line));
    setDistance(calculateDistanceFromPointAndLine(point, line));
}
References calculateDistanceFromPointAndLine(), calculateNormalFromPointAndLine(), D_ASSERT_TRUE, GLESC::isIterable_v, setDistance(), and setNormal().
Plane() [6/7]
GLESC::Math::Plane::Plane (const Plane & plane) default
Construct a new Plane object from another plane. Default copy constructor.
Parameters
plane The plane to copy.
Plane() [7/7]
GLESC::Math::Plane::Plane (Plane && plane) default
Construct a new Plane object from another plane. Default move constructor.
Parameters
plane The plane to move.
~Plane()
GLESC::Math::Plane::~Plane () default
Destroy the Plane object. Default destructor.
Member Function Documentation
calculateDistanceFromPointAndLine()
Distance Plane::calculateDistanceFromPointAndLine (const Point & point, const Line & line) static private
Calculate the distance from the origin to the plane defined by a point and a line.
Parameters
point A point not on the line.
line A line not containing the point.
Returns
double The distance from the origin to the plane.
Definition at line 154 of file Plane.cpp.
{
    Direction vectorFromLineToPoint = point - line.getPoint();
    Direction normal = line.getDirection().cross(vectorFromLineToPoint).normalize();
    return -normal.dot(point);
}
References GLESC::Math::Vector< Type, N >::cross(), GLESC::Math::Vector< Type, N >::dot(), GLESC::isIterable_v, and normal.
Referenced by Plane().
calculateDistanceFromPointAndNormal()
Distance Plane::calculateDistanceFromPointAndNormal (const Point & point, const Direction & normal) static private
Calculate the distance from the origin to the plane defined by a point on the plane and the plane's normal vector.
Parameters
point A point on the plane.
normal The normal vector of the plane.
Returns
double The distance from the origin to the plane.
Definition at line 149 of file Plane.cpp.
{
    return -normal.dot(point);
}
References GLESC::Math::Vector< Type, N >::dot(), and normal.
Referenced by Plane().
calculateDistanceFromPoints()
Distance Plane::calculateDistanceFromPoints (const Point & point1, const Point & point2, const Point & point3) static private
Calculate the distance from the origin to the plane defined by three distinct points.
Parameters
point1 The first point.
point2 The second point.
point3 The third point.
Returns
double The distance from the origin to the plane.
Definition at line 161 of file Plane.cpp.
{
    Direction normal = calculateNormalFromPoints(point1, point2, point3);
    return -normal.dot(point1);
}
References calculateNormalFromPoints(), GLESC::Math::Vector< Type, N >::dot(), GLESC::isIterable_v, and normal.
Referenced by Plane().
calculateNormalFromPointAndLine()
Direction Plane::calculateNormalFromPointAndLine (const Point & point, const Line & line) static private
Calculate the normal vector of the plane defined by a point and a line.
Parameters
point A point not on the line.
line A line not containing the point.
Returns
Direction The normal vector of the plane.
Definition at line 143 of file Plane.cpp.
{
    Direction vectorFromLineToPoint = point - line.getPoint();
    return line.getDirection().cross(vectorFromLineToPoint).normalize();
}
References GLESC::Math::Vector< Type, N >::cross(), and GLESC::isIterable_v.
Referenced by Plane().
calculateNormalFromPoints()
Direction Plane::calculateNormalFromPoints (const Point & firstPoint, const Point & secondPoint, const Point & thirdPoint) static private
Calculate the normal vector of the plane defined by three distinct points.
Parameters
firstPoint The first point.
secondPoint The second point.
thirdPoint The third point.
Returns
Direction The normal vector of the plane.
Definition at line 134 of file Plane.cpp.
{
    Direction vectorFromFirstToSecond = secondPoint - firstPoint;
    Direction vectorFromFirstToThird = thirdPoint - firstPoint;
    return vectorFromFirstToSecond.cross(vectorFromFirstToThird).normalize();
}
References GLESC::Math::Vector< Type, N >::cross(), and GLESC::isIterable_v.
Referenced by Plane(), and calculateDistanceFromPoints().
distanceToPoint()
Distance Plane::distanceToPoint (const Point & point) const
Calculate the distance from the plane to a point.
The formula for calculating the distance from a plane to a point is: d = (n p) + D Where: n is the normalized normal vector of the plane. p is the point. D is the distance of the plane from the origin along its normal.
Parameters
point
Returns
Definition at line 76 of file Plane.cpp.
{
    return normal.dot(point) + distance;
}
References distance, GLESC::Math::Vector< Type, N >::dot(), and normal.
Referenced by intersects(), GLESC::Math::Sphere::intersects(), and intersects().
getDistance()
Distance GLESC::Math::Plane::getDistance () const inline
Get the distance from the origin to the plane.
Returns
Distance The distance from the origin to the plane.
Definition at line 127 of file Plane.h.
{ return distance; }
References distance.
Referenced by GLESC::Math::PolyhedronFace::intersects().
getNormal()
const Direction & GLESC::Math::Plane::getNormal () const inline
Get the normal vector of the plane.
Returns
const Direction& The normal vector of the plane.
Definition at line 121 of file Plane.h.
{ return normal; }
References normal.
Referenced by GLESC::Math::PolyhedronFace::getNormal().
hasInside()
bool Plane::hasInside (const Point & point) const
Check if a point is inside the plane.
A point is inside the plane if it's on the side of the plane where the normal points.
Parameters
point The point to check.
Returns
True if the point is inside the plane, false otherwise.
Definition at line 80 of file Plane.cpp.
{
    // Check if point is on the side of the normal
    // Using the formula Ax+By+Cz+D
    // If the result is greater than 0, the point is on the side of the normal
    float side = normal.getX() * point.getX() +
        normal.getY() * point.getY() +
        normal.getZ() * point.getZ() + distance;
    return side > 0;
}
References distance, GLESC::Math::Vector< Type, N >::getX(), GLESC::Math::Vector< Type, N >::getY(), GLESC::Math::Vector< Type, N >::getZ(), GLESC::isIterable_v, and normal.
intersects() [1/4]
bool Plane::intersects (const Line & line) const
Checks if the plane intersects with a given line.
Parameters
line The line to check for intersection with the plane.
Returns
True if the plane intersects with the line, false otherwise.
Definition at line 104 of file Plane.cpp.
{
    // Check if the line direction is parallel to the plane normal
    // This is determined by checking if their dot product is close to zero
    double dotProduct = normal.dot(line.getDirection());
    bool isParallel = eq(dotProduct, 0);
    if (isParallel) {
        // If the line is parallel to the plane, check if any point on the line lies in the plane
        // Use the distance formula: d = (n  p) + D
        // If the distance is close to 0, the line lies in the plane
        return eq(abs(distanceToPoint(line.getPoint())), 0);
    }
    // If the line is not parallel to the plane, it will intersect the plane at some point
    return true;
}
References GLESC::Math::abs(), distanceToPoint(), GLESC::Math::Vector< Type, N >::dot(), GLESC::Math::eq(), GLESC::isIterable_v, and normal.
intersects() [2/4]
bool Plane::intersects (const Line & line, Point & intersectionPoint) const
Checks if the plane intersects with a given line and sets the intersection point if it exists. The parameter intersectionPoint is set to the intersection point.
Parameters
line The line to check for intersection with the plane.
intersectionPoint The intersection point that is overwritten if it exists.
Returns
True if the plane intersects with the line, false otherwise.
Definition at line 120 of file Plane.cpp.
{
    if (!intersects(line)) {
        return false;
    }
    Distance t = -(normal.dot(line.getPoint()) + distance) / normal.dot(line.getDirection());
    intersectionPoint = line.getPoint() + line.getDirection() * t;
    return true;
}
References distance, GLESC::Math::Vector< Type, N >::dot(), intersects(), GLESC::isIterable_v, and normal.
intersects() [3/4]
bool Plane::intersects (const Plane & plane) const
Definition at line 94 of file Plane.cpp.
{
    bool isParallel = normal.isParallel(plane.normal);
    // When the dot product is 1, the planes are parallel
    // So we check if the dot product is not 1, which means the planes are not parallel
    return !isParallel ||
        // And if they are parallel we check if the distance between the planes is 0,
        // which means the planes are the same, so they intersect
        (eq(distance, plane.distance) && isParallel);
}
References distance, GLESC::Math::eq(), GLESC::Math::Vector< Type, N >::isParallel(), and normal.
intersects() [4/4]
bool Plane::intersects (const Point & point) const
Definition at line 90 of file Plane.cpp.
{
    return eq(distanceToPoint(point), 0);
}
References distanceToPoint(), and GLESC::Math::eq().
Referenced by intersects().
normalize()
void Plane::normalize ()
Normalize the normal vector of the plane.
Definition at line 50 of file Plane.cpp.
                      {
    float length = normal.length();
    if (!eq(length, 1)) {
        normal /= length;
        distance /= length;
    }
}
References distance, GLESC::Math::eq(), GLESC::Math::Vector< Type, N >::length(), and normal.
operator=() [1/2]
Plane & GLESC::Math::Plane::operator= (const Plane & plane) default
Assign a plane to another plane. Default copy assignment operator.
Parameters
plane The plane to copy.
Returns
Plane& The assigned plane.
operator=() [2/2]
Plane & GLESC::Math::Plane::operator= (Plane && plane) default
Assign a plane to another plane. Default move assignment operator.
Parameters
plane The plane to move.
Returns
Plane& The assigned plane.
operator==()
bool Plane::operator== (const Plane & other) const
Compare two planes for equality.
Parameters
other The plane to compare with.
Returns
True if the planes are equal, false otherwise.
Definition at line 129 of file Plane.cpp.
{
    return eq(normal.dot(other.normal), 1) && eq(distance, other.distance);
}
References distance, GLESC::Math::Vector< Type, N >::dot(), GLESC::Math::eq(), GLESC::isIterable_v, and normal.
setDistance()
void GLESC::Math::Plane::setDistance (Distance distanceParam) inline
Set the distance from the origin to the plane.
Parameters
distanceParam The distance from the origin to the plane.
Definition at line 115 of file Plane.h.
{ distance = distanceParam; }
References distance, and GLESC::isIterable_v.
Referenced by Plane(), Plane(), Plane(), and Plane().
setNormal()
void Plane::setNormal (const Direction & normalParam)
Set the normal vector of the plane.
The normal vector is normalized if its length is greater than 1. The normal cannot be a zero vector.
Parameters
normalParam The normal vector of the plane.
Definition at line 43 of file Plane.cpp.
{
    D_ASSERT_FALSE(normalParam.isZero(), "Normal cannot be a zero vector");
    normal = normalParam;
}
References D_ASSERT_FALSE, GLESC::isIterable_v, and normal.
Referenced by Plane(), Plane(), Plane(), and Plane().
toString()
std::string Plane::toString () const
Convert the plane to a string.
Returns
String representation of the plane.
Definition at line 59 of file Plane.cpp.
{
    return "Plane: normal = " + normal.toString() + ", distance from [0,0] = " + std::to_string(distance);
}
References distance, normal, and GLESC::Math::Vector< Type, N >::toString().
Member Data Documentation
distance
Distance GLESC::Math::Plane::distance {} private
The distance from the origin to the plane along its normal.
If the distance is positive, the plane is in the direction of the normal. If the distance is negative, the plane is in the opposite direction of the normal.
Definition at line 255 of file Plane.h.
{};
Referenced by distanceToPoint(), getDistance(), hasInside(), intersects(), intersects(), normalize(), operator==(), setDistance(), and toString().
normal
Direction GLESC::Math::Plane::normal {} private
The unit vector normal to the plane. Defines the orientation of the plane.
Definition at line 249 of file Plane.h.
{};
Referenced by calculateDistanceFromPointAndLine(), calculateDistanceFromPointAndNormal(), calculateDistanceFromPoints(), distanceToPoint(), getNormal(), hasInside(), intersects(), intersects(), intersects(), normalize(), operator==(), setNormal(), and toString().
The documentation for this class was generated from the following files:
Plane.h
Plane.cpp