GLESC: GAPIDebugger.h File Reference
GAPIDebugger.h File Reference
Debugger for the Graphic Application Programming Interface (GAPI).
#include <iomanip>
#include "engine/core/debugger/Debugger.h"
#include "engine/core/logger/Logger.h"
Macros
#define GAPI_FUNCTION_IMPLEMENTATION_LOG(FUNCTION_NAME, ...) do {} while (false)
#define GAPI_FUNCTION_IMPLEMENTATION_LOG(FUNCTION_NAME, ...)
#define GAPI_FUNCTION_LOG(FUNCTION_NAME, ...) do {} while (false)
#define GAPI_FUNCTION_LOG(FUNCTION_NAME, ...)
#define GAPI_FUNCTION_NO_ARGS_LOG(FUNCTION_NAME) do {} while (false)
#define GAPI_FUNCTION_NO_ARGS_LOG(FUNCTION_NAME) Logger::get().infoBlue("Entering " + std::string(FUNCTION_NAME));
#define GAPI_PRINT_BUFFER_DATA(TYPE, DATA, SIZE) do {} while (false)
#define GAPI_PRINT_BUFFER_DATA(TYPE, DATA, SIZE) printBufferData<TYPE>(DATA, SIZE)
#define GAPI_PRINT_CODE(CONTENT) do {} while (false)
#define GAPI_PRINT_CODE(CONTENT)
#define PRINT_GAPI_INIT(name, version) do {} while (false)
#define PRINT_GAPI_INIT(name, version) GAPI_PRINT_CODE(printGAPIInit(name, version););
Functions
template<typename BufferType >
void printBufferData (const GLESC::GAPI::Void *data, GLESC::GAPI::Size size)
void printGAPIInit (const std::string &GAPIName, const std::string &GAPIVersion)
Detailed Description
Debugger for the Graphic Application Programming Interface (GAPI).
Author
Valentin Dumitru
Date
2023-09-26
Includes toStrings and logging for the GAPI.
Copyright (c) 2023 Valentin Dumitru. Licensed under the MIT License. See LICENSE.txt in the project root for license information.
Definition in file concrete-apis/debugger/GAPIDebugger.h.
Macro Definition Documentation
GAPI_FUNCTION_IMPLEMENTATION_LOG [1/2]
#define GAPI_FUNCTION_IMPLEMENTATION_LOG (FUNCTION_NAME, ...) do {} while (false)
Definition at line 22 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_FUNCTION_IMPLEMENTATION_LOG [2/2]
#define GAPI_FUNCTION_IMPLEMENTATION_LOG (FUNCTION_NAME, ...)
Value:
    Logger::get().infoBlue("\tExecuting " +           \
            FUNCTION_CALL_STR(FUNCTION_NAME, __VA_ARGS__));
Definition at line 22 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_FUNCTION_LOG [1/2]
#define GAPI_FUNCTION_LOG (FUNCTION_NAME, ...) do {} while (false)
Definition at line 20 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_FUNCTION_LOG [2/2]
#define GAPI_FUNCTION_LOG (FUNCTION_NAME, ...)
Value:
    Logger::get().infoBlue("Entering GAPI function: " + \
            FUNCTION_CALL_STR(FUNCTION_NAME, __VA_ARGS__));
Definition at line 20 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_FUNCTION_NO_ARGS_LOG [1/2]
#define GAPI_FUNCTION_NO_ARGS_LOG (FUNCTION_NAME) do {} while (false)
Definition at line 21 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_FUNCTION_NO_ARGS_LOG [2/2]
#define GAPI_FUNCTION_NO_ARGS_LOG (FUNCTION_NAME) Logger::get().infoBlue("Entering " + std::string(FUNCTION_NAME));
Definition at line 21 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_PRINT_BUFFER_DATA [1/2]
#define GAPI_PRINT_BUFFER_DATA (TYPE, DATA, SIZE) do {} while (false)
Definition at line 23 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_PRINT_BUFFER_DATA [2/2]
#define GAPI_PRINT_BUFFER_DATA (TYPE, DATA, SIZE) printBufferData<TYPE>(DATA, SIZE)
Definition at line 23 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_PRINT_CODE [1/2]
#define GAPI_PRINT_CODE (CONTENT) do {} while (false)
Definition at line 18 of file concrete-apis/debugger/GAPIDebugger.h.
GAPI_PRINT_CODE [2/2]
#define GAPI_PRINT_CODE (CONTENT)
Value:
    LOG_BASIC(Logger::get().info("GAPI status:"); \
        CONTENT                  \
        )
Definition at line 18 of file concrete-apis/debugger/GAPIDebugger.h.
PRINT_GAPI_INIT [1/2]
#define PRINT_GAPI_INIT (name, version) do {} while (false)
Definition at line 19 of file concrete-apis/debugger/GAPIDebugger.h.
PRINT_GAPI_INIT [2/2]
#define PRINT_GAPI_INIT (name, version) GAPI_PRINT_CODE(printGAPIInit(name, version););
Definition at line 19 of file concrete-apis/debugger/GAPIDebugger.h.
Function Documentation
printBufferData()
template<typename BufferType > void printBufferData (const GLESC::GAPI::Void * data, GLESC::GAPI::Size size)
Definition at line 50 of file concrete-apis/debugger/GAPIDebugger.h.
{
    const auto *typedData = static_cast<const BufferType *>(data);
    size_t count = size / sizeof(BufferType); // Calculate how many elements are in the buffer
    // Determine the maximum width needed for alignment
    BufferType max_value = *std::max_element(typedData, typedData + count);
    int max_width = std::to_string(max_value).length();
    for (size_t i = 0; i < count; ++i) {
        // Use std::setw to set the width and std::setfill to fill with spaces
        std::cout << std::setw(max_width) << std::setfill(' ') << typedData[i] << " ";
        if (i % 8 == 7) std::cout << std::endl; // Print 8 elements per line for readability
    }
    std::cout << std::endl;
}
printGAPIInit()
void printGAPIInit (const std::string & GAPIName, const std::string & GAPIVersion) inline
Definition at line 66 of file concrete-apis/debugger/GAPIDebugger.h.
{
   Logger::get().importantSuccess(
           "Initializing Graphic Application Programming Interface (GAPI)");
   Logger::get().success("\t" + GAPIName + " version " + GAPIVersion);
}
References GLESC::Logger::get(), GLESC::Logger::importantSuccess(), and GLESC::Logger::success().