GLESC: GLESC::GAPI::Enums Namespace Reference
GLESC::GAPI::Enums Namespace Reference
Classes
struct PrimitiveType
Typedefs
template<Types T>
using PrimitiveType_t = typename PrimitiveType< T >::Type
Enumerations
enum class TypeCount {
Value = 1 , Vec2 = 2 , Vec3 = 3 , Vec4 = 4 ,
Mat2 = 4 , Mat3 = 9 , Mat4 = 16
}
Functions
static constexpr TypeCount getTypeCount (Types type)
static constexpr Types getTypePrimitiveType (Types type)
static constexpr TypeSize getTypeSize (Types type)
MAP_TYPE (Types::Bool, GLboolean)
MAP_TYPE (Types::Byte, GLbyte)
MAP_TYPE (Types::Double, GLdouble)
MAP_TYPE (Types::Float, GLfloat)
MAP_TYPE (Types::Int, GLint)
MAP_TYPE (Types::Mat2D, GLdouble)
MAP_TYPE (Types::Mat2F, GLfloat)
MAP_TYPE (Types::Mat3D, GLdouble)
MAP_TYPE (Types::Mat3F, GLfloat)
MAP_TYPE (Types::Mat4D, GLdouble)
MAP_TYPE (Types::Mat4F, GLfloat)
MAP_TYPE (Types::Short, GLshort)
MAP_TYPE (Types::UByte, GLubyte)
MAP_TYPE (Types::UInt, GLuint)
MAP_TYPE (Types::UShort, GLushort)
MAP_TYPE (Types::Vec2B, GLboolean)
MAP_TYPE (Types::Vec2D, GLdouble)
MAP_TYPE (Types::Vec2F, GLfloat)
MAP_TYPE (Types::Vec2I, GLint)
MAP_TYPE (Types::Vec2UI, GLuint)
MAP_TYPE (Types::Vec3B, GLboolean)
MAP_TYPE (Types::Vec3D, GLdouble)
MAP_TYPE (Types::Vec3F, GLfloat)
MAP_TYPE (Types::Vec3I, GLint)
MAP_TYPE (Types::Vec3UI, GLuint)
MAP_TYPE (Types::Vec4B, GLboolean)
MAP_TYPE (Types::Vec4D, GLdouble)
MAP_TYPE (Types::Vec4F, GLfloat)
MAP_TYPE (Types::Vec4I, GLint)
MAP_TYPE (Types::Vec4UI, GLuint)
std::string toString (BlendingParameters type)
Converts the blending parameters to string.
std::string toString (BufferTypes type)
Converts the buffer type to string.
std::string toString (BufferUsages type)
Converts the buffer usage to string.
std::string toString (Capabilities type)
Converts the capabilities to string.
std::string toString (ClearBits type)
Converts the buffer access to string.
std::string toString (CullingParameters type)
Converts the culling parameters to string.
std::string toString (DepthParameters type)
Converts the depth parameters to string.
std::string toString (PolygonModeParameters type)
Converts the polygon mode parameters to string.
std::string toString (PrimitiveTypes type)
Converts the primitive type to string.
std::string toString (ShaderTypes type)
Converts the shader type to string.
std::string toString (StencilParameters type)
Converts the shader type to string.
std::string toString (Texture::CPUBufferFormat format)
Converts CPU buffer format to string.
std::string toString (Texture::GPUBufferFormat internalFormat)
Converts internal format of the texture to string.
std::string toString (Texture::Types type)
Converts the texture type to string.
std::string toString (TypeCount typeCount)
Converts the type count to string.
std::string toString (Types type)
Converts the type to string.
Class Documentation
GLESC::GAPI::Enums::PrimitiveType
struct GLESC::GAPI::Enums::PrimitiveType
template<Types T>
struct GLESC::GAPI::Enums::PrimitiveType< T >
Definition at line 462 of file GapiEnums.h.
Typedef Documentation
PrimitiveType_t
template<Types T> using GLESC::GAPI::Enums::PrimitiveType_t = typedef typename PrimitiveType<T>::Type
Definition at line 459 of file GapiEnums.h.
Enumeration Type Documentation
TypeCount
enum class GLESC::GAPI::Enums::TypeCount strong
Enumerator
Value
Vec2
Vec3
Vec4
Mat2
Mat3
Mat4
Definition at line 14 of file GapiEnums.h.
{
        Value [[maybe_unused]] = 1,
        Vec2 [[maybe_unused]] = 2,
        Vec3 [[maybe_unused]] = 3,
        Vec4 [[maybe_unused]] = 4,
        Mat2 [[maybe_unused]] = 4,
        Mat3 [[maybe_unused]] = 9,
        Mat4 [[maybe_unused]] = 16,
    };
Function Documentation
getTypeCount()
static constexpr TypeCount GLESC::GAPI::Enums::getTypeCount (Types type) static constexpr
Definition at line 347 of file GapiEnums.h.
{
        switch (type) {
            case Types::Float:
            case Types::Double:
            case Types::Int:
            case Types::UInt:
            case Types::Bool:
            case Types::UByte:
            case Types::Byte:
            case Types::Short:
            case Types::UShort: return TypeCount::Value;
            case Types::Vec2F:
            case Types::Vec2D:
            case Types::Vec2I:
            case Types::Vec2UI:
            case Types::Vec2B: return TypeCount::Vec2;
            case Types::Vec3F:
            case Types::Vec3D:
            case Types::Vec3I:
            case Types::Vec3UI:
            case Types::Vec3B: return TypeCount::Vec3;
            case Types::Vec4F:
            case Types::Vec4I:
            case Types::Vec4UI:
            case Types::Vec4B: return TypeCount::Vec4;
            case Types::Mat2D:
            case Types::Mat2F: return TypeCount::Mat2;
            case Types::Mat3D:
            case Types::Mat3F: return TypeCount::Mat3;
            case Types::Mat4D:
            case Types::Mat4F: return TypeCount::Mat4;
            default: return TypeCount::Value;
        }
    }
References Mat2, Mat3, Mat4, Value, Vec2, Vec3, and Vec4.
Referenced by getTypePrimitiveType().
getTypePrimitiveType()
static constexpr Types GLESC::GAPI::Enums::getTypePrimitiveType (Types type) static constexpr
Definition at line 425 of file GapiEnums.h.
{
        if (getTypeCount(type) == TypeCount::Value) {
            return type;
        }
        switch (type) {
            case Types::Vec2F:
            case Types::Vec3F:
            case Types::Vec4F:
            case Types::Mat2F:
            case Types::Mat3F:
            case Types::Mat4F: return Types::Float;
            case Types::Vec2I:
            case Types::Vec3I:
            case Types::Vec4I: return Types::Int;
            case Types::Vec2UI:
            case Types::Vec3UI:
            case Types::Vec4UI: return Types::UInt;
            case Types::Vec2B:
            case Types::Vec3B:
            case Types::Vec4B: return Types::Bool;
            case Types::Vec2D:
            case Types::Vec3D:
            case Types::Vec4D:
            case Types::Mat2D:
            case Types::Mat3D:
            case Types::Mat4D: return Types::Double;
            default: return Types::Float;
        }
    }
References getTypeCount(), and Value.
getTypeSize()
static constexpr TypeSize GLESC::GAPI::Enums::getTypeSize (Types type) static constexpr
Definition at line 382 of file GapiEnums.h.
{
        switch (type) {
            case Types::Float: return TypeSize::Float;
            case Types::Double: return TypeSize::Double;
            case Types::Int: return TypeSize::Int;
            case Types::UInt: return TypeSize::UnsignedInt;
            case Types::Bool: return TypeSize::Bool;
            case Types::UByte: return TypeSize::UnsignedByte;
            case Types::Byte: return TypeSize::Byte;
            case Types::Short: return TypeSize::Short;
            case Types::UShort: return TypeSize::UnsignedShort;
            case Types::Vec2F: return TypeSize::Vec2F;
            case Types::Vec3F: return TypeSize::Vec3F;
            case Types::Vec4F: return TypeSize::Vec4F;
            case Types::Vec2D: return TypeSize::Vec2D;
            case Types::Vec3D: return TypeSize::Vec3D;
            case Types::Vec4D: return TypeSize::Vec4D;
            case Types::Vec2I: return TypeSize::Vec2I;
            case Types::Vec3I: return TypeSize::Vec3I;
            case Types::Vec4I: return TypeSize::Vec4I;
            case Types::Vec2UI: return TypeSize::Vec2UI;
            case Types::Vec3UI: return TypeSize::Vec3UI;
            case Types::Vec4UI: return TypeSize::Vec4UI;
            case Types::Vec2B: return TypeSize::Vec2B;
            case Types::Vec3B: return TypeSize::Vec3B;
            case Types::Vec4B: return TypeSize::Vec4B;
            case Types::Mat2F: return TypeSize::Mat2F;
            case Types::Mat3F: return TypeSize::Mat3F;
            case Types::Mat4F: return TypeSize::Mat4F;
            case Types::Mat2D: return TypeSize::Mat2D;
            case Types::Mat3D: return TypeSize::Mat3D;
            case Types::Mat4D: return TypeSize::Mat4D;
            default: return TypeSize::None;
        }
    }
MAP_TYPE() [1/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Bool , GLboolean)
MAP_TYPE() [2/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Byte , GLbyte)
MAP_TYPE() [3/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Double , GLdouble)
MAP_TYPE() [4/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Float , GLfloat)
MAP_TYPE() [5/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Int , GLint)
MAP_TYPE() [6/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat2D , GLdouble)
MAP_TYPE() [7/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat2F , GLfloat)
MAP_TYPE() [8/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat3D , GLdouble)
MAP_TYPE() [9/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat3F , GLfloat)
MAP_TYPE() [10/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat4D , GLdouble)
MAP_TYPE() [11/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Mat4F , GLfloat)
MAP_TYPE() [12/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Short , GLshort)
MAP_TYPE() [13/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::UByte , GLubyte)
MAP_TYPE() [14/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::UInt , GLuint)
MAP_TYPE() [15/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::UShort , GLushort)
MAP_TYPE() [16/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec2B , GLboolean)
MAP_TYPE() [17/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec2D , GLdouble)
MAP_TYPE() [18/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec2F , GLfloat)
MAP_TYPE() [19/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec2I , GLint)
MAP_TYPE() [20/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec2UI , GLuint)
MAP_TYPE() [21/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec3B , GLboolean)
MAP_TYPE() [22/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec3D , GLdouble)
MAP_TYPE() [23/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec3F , GLfloat)
MAP_TYPE() [24/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec3I , GLint)
MAP_TYPE() [25/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec3UI , GLuint)
MAP_TYPE() [26/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec4B , GLboolean)
MAP_TYPE() [27/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec4D , GLdouble)
MAP_TYPE() [28/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec4F , GLfloat)
MAP_TYPE() [29/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec4I , GLint)
MAP_TYPE() [30/30]
GLESC::GAPI::Enums::MAP_TYPE (Types::Vec4UI , GLuint)
toString() [1/16]
std::string GLESC::GAPI::Enums::toString (BlendingParameters type) inline
Converts the blending parameters to string.
Parameters
type
Returns
string representation of the blending parameters
Definition at line 252 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case BlendingParameters::Blending: return "Blending";
        case BlendingParameters::BlendEquationRGB: return "BlendEquationRGB";
        case BlendingParameters::BlendEquationAlpha: return "BlendEquationAlpha";
        case BlendingParameters::BlendDstRGB: return "BlendDstRGB";
        case BlendingParameters::BlendSrcRGB: return "BlendSrcRGB";
        case BlendingParameters::BlendDstAlpha: return "BlendDstAlpha";
        case BlendingParameters::BlendSrcAlpha: return "BlendSrcAlpha";
        case BlendingParameters::BlendColor: return "BlendColor";
        default: return "Invalid type";
        }
    }
toString() [2/16]
std::string GLESC::GAPI::Enums::toString (BufferTypes type) inline
Converts the buffer type to string.
Parameters
type
Returns
string representation of the buffer type
Definition at line 161 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case BufferTypes::Vertex: return "Vertex";
        case BufferTypes::Index: return "Index";
        default: return "Invalid type";
        }
    }
toString() [3/16]
std::string GLESC::GAPI::Enums::toString (BufferUsages type) inline
Converts the buffer usage to string.
Parameters
type
Returns
string representation of the buffer usage
Definition at line 173 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case BufferUsages::StaticDraw: return "StaticDraw";
        case BufferUsages::DynamicDraw: return "DynamicDraw";
        case BufferUsages::StreamDraw: return "StreamDraw";
        case BufferUsages::StaticRead: return "StaticRead";
        case BufferUsages::DynamicRead: return "DynamicRead";
        case BufferUsages::StreamRead: return "StreamRead";
        default: return "Invalid type";
        }
    }
toString() [4/16]
std::string GLESC::GAPI::Enums::toString (Capabilities type) inline
Converts the capabilities to string.
Parameters
type
Returns
string representation of the capabilities
Definition at line 307 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case Capabilities::DepthTest: return "DepthTest";
        case Capabilities::StencilTest: return "StencilTest";
        case Capabilities::Blending: return "Blending";
        case Capabilities::Culling: return "Culling";
        default: return "Invalid type";
        }
    }
toString() [5/16]
std::string GLESC::GAPI::Enums::toString (ClearBits type) inline
Converts the buffer access to string.
Parameters
type
Returns
string representation of the buffer access
Definition at line 189 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case ClearBits::Color: return "Color";
        case ClearBits::Depth: return "Depth";
        case ClearBits::Stencil: return "Stencil";
        default: return "Invalid type";
        }
    }
toString() [6/16]
std::string GLESC::GAPI::Enums::toString (CullingParameters type) inline
Converts the culling parameters to string.
Parameters
type
Returns
string representation of the culling parameters
Definition at line 270 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case CullingParameters::Culling: return "Culling";
        case CullingParameters::CullFaceMode: return "CullFaceMode";
        case CullingParameters::FrontFace: return "FrontFace";
        default: return "Invalid type";
        }
    }
toString() [7/16]
std::string GLESC::GAPI::Enums::toString (DepthParameters type) inline
Converts the depth parameters to string.
Parameters
type
Returns
string representation of the depth parameters
Definition at line 240 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case DepthParameters::DepthTest: return "DepthTest";
        case DepthParameters::DepthFunc: return "DepthFunc";
        default: return "Invalid type";
        }
    }
toString() [8/16]
std::string GLESC::GAPI::Enums::toString (PolygonModeParameters type) inline
Converts the polygon mode parameters to string.
Parameters
type
Returns
string representation of the polygon mode parameters
Definition at line 283 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case PolygonModeParameters::PolygonMode: return "PolygonMode";
        default: return "Invalid type";
        }
    }
toString() [9/16]
std::string GLESC::GAPI::Enums::toString (PrimitiveTypes type) inline
Converts the primitive type to string.
Parameters
type
Returns
string representation of the primitive type
Definition at line 294 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case PrimitiveTypes::Triangles: return "Triangles";
        case PrimitiveTypes::Lines: return "Lines";
        case PrimitiveTypes::Points: return "Points";
        default: return "Invalid type";
        }
    }
toString() [10/16]
std::string GLESC::GAPI::Enums::toString (ShaderTypes type) inline
Converts the shader type to string.
Parameters
type
Returns
string representation of the shader type
Definition at line 202 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case ShaderTypes::Vertex: return "Vertex";
        case ShaderTypes::Fragment: return "Fragment";
        default: return "Invalid type";
        }
    }
toString() [11/16]
std::string GLESC::GAPI::Enums::toString (StencilParameters type) inline
Converts the shader type to string.
Parameters
type
Returns
string representation of the shader type
Definition at line 214 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case StencilParameters::StencilTest: return "StencilTest";
        case StencilParameters::StencilFail: return "StencilFail";
        case StencilParameters::StencilFunc: return "StencilFunc";
        case StencilParameters::StencilRef: return "StencilRef";
        case StencilParameters::StencilValueMask: return "StencilValueMask";
        case StencilParameters::StencilWriteMask: return "StencilWriteMask";
        case StencilParameters::StencilClearValue: return "StencilClearValue";
        case StencilParameters::StencilPassDepthFail: return "StencilPassDepthFail";
        case StencilParameters::StencilPassDepthPass: return "StencilPassDepthPass";
        case StencilParameters::StencilBackFunc: return "StencilBackFunc";
        case StencilParameters::StencilBackFail: return "StencilBackFail";
        case StencilParameters::StencilBackPassDepthFail: return "StencilBackPassDepthFail";
        case StencilParameters::StencilBackPassDepthPass: return "StencilBackPassDepthPass";
        case StencilParameters::StencilBackRef: return "StencilBackRef";
        case StencilParameters::StencilBackValueMask: return "StencilBackValueMask";
        case StencilParameters::StencilBackWriteMask: return "StencilBackWriteMask";
        default: return "Invalid type";
        }
    }
toString() [12/16]
std::string GLESC::GAPI::Enums::toString (Texture::CPUBufferFormat format) inline
Converts CPU buffer format to string.
Parameters
format
Returns
string representation of the CPU buffer format
Definition at line 110 of file debugger/GAPIDebugger.h.
{
        switch (format) {
        case Texture::CPUBufferFormat::R: return "R";
        case Texture::CPUBufferFormat::RG: return "RG";
        case Texture::CPUBufferFormat::RGB: return "RGB";
        case Texture::CPUBufferFormat::RGBA: return "RGBA";
        case Texture::CPUBufferFormat::BGR: return "BGR";
        case Texture::CPUBufferFormat::BGRA: return "BGRA";
        case Texture::CPUBufferFormat::DepthComponent: return "DepthComponent";
        case Texture::CPUBufferFormat::DepthStencil: return "DepthStencil";
        default: return "Invalid type";
        }
    }
toString() [13/16]
std::string GLESC::GAPI::Enums::toString (Texture::GPUBufferFormat internalFormat) inline
Converts internal format of the texture to string.
Parameters
internalFormat
Returns
string representation of the internal format
Definition at line 30 of file debugger/GAPIDebugger.h.
{
        switch (internalFormat) {
        case Texture::GPUBufferFormat::R8: return "R8";
        case Texture::GPUBufferFormat::R8_SNORM: return "R8_SNORM";
        case Texture::GPUBufferFormat::R16: return "R16";
        case Texture::GPUBufferFormat::R16_SNORM: return "R16_SNORM";
        case Texture::GPUBufferFormat::RG8: return "RG8";
        case Texture::GPUBufferFormat::RG8_SNORM: return "RG8_SNORM";
        case Texture::GPUBufferFormat::RG16: return "RG16";
        case Texture::GPUBufferFormat::RG16_SNORM: return "RG16_SNORM";
        case Texture::GPUBufferFormat::R3_G3_B2: return "R3_G3_B2";
        case Texture::GPUBufferFormat::RGB: return "RGB";
        case Texture::GPUBufferFormat::RGBA: return "RGBA";
        case Texture::GPUBufferFormat::RGB4: return "RGB4";
        case Texture::GPUBufferFormat::RGB5: return "RGB5";
        case Texture::GPUBufferFormat::RGB8: return "RGB8";
        case Texture::GPUBufferFormat::RGB8_SNORM: return "RGB8_SNORM";
        case Texture::GPUBufferFormat::RGB10: return "RGB10";
        case Texture::GPUBufferFormat::RGB12: return "RGB12";
        case Texture::GPUBufferFormat::RGB16_SNORM: return "RGB16_SNORM";
        case Texture::GPUBufferFormat::RGBA2: return "RGBA2";
        case Texture::GPUBufferFormat::RGBA4: return "RGBA4";
        case Texture::GPUBufferFormat::RGB5_A1: return "RGB5_A1";
        case Texture::GPUBufferFormat::RGBA8: return "RGBA8";
        case Texture::GPUBufferFormat::RGBA8_SNORM: return "RGBA8_SNORM";
        case Texture::GPUBufferFormat::RGB10_A2: return "RGB10_A2";
        case Texture::GPUBufferFormat::RGB10_A2UI: return "RGB10_A2UI";
        case Texture::GPUBufferFormat::RGBA12: return "RGBA12";
        case Texture::GPUBufferFormat::RGBA16: return "RGBA16";
        case Texture::GPUBufferFormat::SRGB8: return "SRGB8";
        case Texture::GPUBufferFormat::SRGB8_ALPHA8: return "SRGB8_ALPHA8";
        case Texture::GPUBufferFormat::R16F: return "R16F";
        case Texture::GPUBufferFormat::RG16F: return "RG16F";
        case Texture::GPUBufferFormat::RGB16F: return "RGB16F";
        case Texture::GPUBufferFormat::RGBA16F: return "RGBA16F";
        case Texture::GPUBufferFormat::R32F: return "R32F";
        case Texture::GPUBufferFormat::RG32F: return "RG32F";
        case Texture::GPUBufferFormat::RGB32F: return "RGB32F";
        case Texture::GPUBufferFormat::RGBA32F: return "RGBA32F";
        case Texture::GPUBufferFormat::R11F_G11F_B10F: return "R11F_G11F_B10F";
        case Texture::GPUBufferFormat::RGB9_E5: return "RGB9_E5";
        case Texture::GPUBufferFormat::R8I: return "R8I";
        case Texture::GPUBufferFormat::R8UI: return "R8UI";
        case Texture::GPUBufferFormat::R16I: return "R16I";
        case Texture::GPUBufferFormat::R16UI: return "R16UI";
        case Texture::GPUBufferFormat::R32I: return "R32I";
        case Texture::GPUBufferFormat::R32UI: return "R32UI";
        case Texture::GPUBufferFormat::RG8I: return "RG8I";
        case Texture::GPUBufferFormat::RG8UI: return "RG8UI";
        case Texture::GPUBufferFormat::RG16I: return "RG16I";
        case Texture::GPUBufferFormat::RG16UI: return "RG16UI";
        case Texture::GPUBufferFormat::RG32I: return "RG32I";
        case Texture::GPUBufferFormat::RG32UI: return "RG32UI";
        case Texture::GPUBufferFormat::RGB8I: return "RGB8I";
        case Texture::GPUBufferFormat::RGB8UI: return "RGB8UI";
        case Texture::GPUBufferFormat::RGB16I: return "RGB16I";
        case Texture::GPUBufferFormat::RGB16UI: return "RGB16UI";
        case Texture::GPUBufferFormat::RGB32I: return "RGB32I";
        case Texture::GPUBufferFormat::RGB32UI: return "RGB32UI";
        case Texture::GPUBufferFormat::RGBA8I: return "RGBA8I";
        case Texture::GPUBufferFormat::RGBA8UI: return "RGBA8UI";
        case Texture::GPUBufferFormat::RGBA16I: return "RGBA16I";
        case Texture::GPUBufferFormat::RGBA16UI: return "RGBA16UI";
        case Texture::GPUBufferFormat::RGBA32I: return "RGBA32I";
        case Texture::GPUBufferFormat::RGBA32UI: return "RGBA32UI";
        case Texture::GPUBufferFormat::DEPTH_COMPONENT16: return "DEPTH_COMPONENT16";
        case Texture::GPUBufferFormat::DEPTH_COMPONENT24: return "DEPTH_COMPONENT24";
        case Texture::GPUBufferFormat::DEPTH_COMPONENT32F: return "DEPTH_COMPONENT32F";
        case Texture::GPUBufferFormat::DEPTH24_STENCIL8: return "DEPTH24_STENCIL8";
        case Texture::GPUBufferFormat::DEPTH32F_STENCIL8: return "DEPTH32F_STENCIL8";
        case Texture::GPUBufferFormat::STENCIL_INDEX8: return "STENCIL_INDEX8";
        default: return "Invalid type";
        }
    }
References GLESC::isIterable_v.
toString() [14/16]
std::string GLESC::GAPI::Enums::toString (Texture::Types type) inline
Converts the texture type to string.
Parameters
type
Returns
string representation of the texture type
Definition at line 321 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case Texture::Types::Texture2D: return "Texture2D";
        case Texture::Types::Texture3D: return "Texture3D";
        case Texture::Types::TextureCubeMap: return "TextureCubeMap";
        case Texture::Types::Texture2DArray: return "Texture2DArray";
        case Texture::Types::TextureCubeMapArray: return "TextureCubeMapArray";
        case Texture::Types::Texture2DMultisample: return "Texture2DMultisample";
        case Texture::Types::Texture2DMultisampleArray: return "Texture2DMultisampleArray";
        default: return "Invalid type";
        }
    }
toString() [15/16]
std::string GLESC::GAPI::Enums::toString (TypeCount typeCount) inline
Converts the type count to string.
Parameters
typeCount
Returns
string representation of the type count
Definition at line 21 of file debugger/GAPIDebugger.h.
{
        return std::to_string(static_cast<unsigned>(typeCount));
    }
References GLESC::isIterable_v.
Referenced by GLESC::GAPI::OpenGLAPI::getTextureColorFormat().
toString() [16/16]
std::string GLESC::GAPI::Enums::toString (Types type) inline
Converts the type to string.
Parameters
type
Returns
string representation of the type
Definition at line 128 of file debugger/GAPIDebugger.h.
{
        switch (type) {
        case Types::Float: return "Float";
        case Types::Int: return "Int";
        case Types::UInt: return "UInt";
        case Types::Bool: return "Bool";
        case Types::UByte: return "UByte";
        case Types::Byte: return "Byte";
        case Types::Short: return "Short";
        case Types::UShort: return "UShort";
        case Types::Vec2F: return "Vec2F";
        case Types::Vec3F: return "Vec3F";
        case Types::Vec4F: return "Vec4F";
        case Types::Vec2I: return "Vec2I";
        case Types::Vec3I: return "Vec3I";
        case Types::Vec4I: return "Vec4I";
        case Types::Vec2UI: return "Vec2UI";
        case Types::Vec3UI: return "Vec3UI";
        case Types::Vec4UI: return "Vec4UI";
        case Types::Vec2B: return "Vec2B";
        case Types::Vec3B: return "Vec3B";
        case Types::Vec4B: return "Vec4B";
        case Types::Mat2F: return "Mat2F";
        case Types::Mat3F: return "Mat3F";
        case Types::Mat4F: return "Mat4F";
        default: return "Invalid type";
        }
    }