GLESC: GLESC::Math Namespace Reference
GLESC::Math Namespace Reference
Classes
class BoundingVolume
A bounding volume is a geometric shape that encloses a set of points.
class Figure
Base class for all geometric figures.
class Line
class Matrix
Matrix class. Represents a matrix of N rows and M columns.
class MatrixAlgorithms
class MatrixMixedAlgorithms
class Plane
class Polyhedron
class PolyhedronFace
struct SelectSmallerFloatingType
Selects the smaller floating-point type between two types.
class Sphere
class Vector
class VectorAlgorithms
class VectorMixedAlgorithms
Typedefs
using Direction = Vec3F
Alias for the direction type, directions are 3D vectors.
using Distance = float
Alias for the distance type.
using FaceIndices = std::array< Index, 3 >
Alias for the face indices type, a face is defined by 3 indices.
using Index = unsigned int
Alias for any index type, no need for signed indices.
template<typename Type , std::size_t N, std::size_t M>
using MatrixData = std::array< MatrixRow< Type, M >, N >
Type alias for a matrix data.
template<typename Type , std::size_t M>
using MatrixRow = std::array< Type, M >
Type alias for a matrix row.
using Point = Vec3F
Alias for the point type, points are 3D vectors.
using Points = std::vector< Point >
Alias for the points type, a collection of points.
using QuadIndices = std::array< Index, 4 >
Alias for the quad indices type, a quad is defined by 4 indices.
template<typename Type , std::size_t N>
using VectorData = std::array< Type, N >
Type alias for a vector data.
using Volume = float
Alias for the volume type.
Functions
template<typename Type >
constexpr Type abs (const Type &value)
Calculates the absolute value of a number.
template<typename Type >
auto atan2 (const Type &value1, const Type &value2)
Calculates the arctangent of a value.
template<typename Type1 , typename Type2 , typename Type3 >
constexpr Type1 clamp (const Type1 &value, const Type2 &min, const Type3 &max)
Clamps a value between a minimum and maximum value.
template<typename Type >
auto cos (const Type &value)
Calculates the cosine of a value.
template<typename Type >
Type degrees (const Type &radians) noexcept
Converts radians to degrees.
template<typename Type >
constexpr auto epsilon () noexcept
Epsilon getter with precision of a given template type.
template<typename Type >
constexpr Type epsilon (Type valueParam)
Epsilon getter with precision of a given value.
template<typename LValueT , typename RValueT >
constexpr bool eq (const LValueT &left, const RValueT &right)
Compares two values for equality, calculates the epsilon automatically.
template<typename LValueT , typename RValueT >
constexpr bool eq (const LValueT &left, const RValueT &right, const double epsilon)
Compares two values for equality.
template<typename Type , Type min, Type max>
constexpr Type generateCompileTimeRandomNumber ()
Generates a compile time random number between min and max, specifically [min, max)
template<typename Type >
Type generateRandomNumber ()
Generates a random number with the widest range possible for the type.
template<typename Type , typename = std::enable_if_t<std::is_arithmetic_v<Type>>>
Type generateRandomNumber (Type min, Type max)
Generates a random number between min and max, specifically [min, max)
template<typename LValueT , typename RValueT >
constexpr bool gt (const LValueT &left, const RValueT &right)
Compares two values for greater than, calculates the epsilon automatically.
template<typename LValueT , typename RValueT >
constexpr bool gt (const LValueT &left, const RValueT &right, const double epsilon)
Compares two values for greater than.
template<typename LValueT , typename RValueT >
constexpr bool gte (const LValueT &left, const RValueT &right, const double epsilon)
Compares two values for greater than or equal.
template<typename Type , typename TypeFactor >
constexpr Type lerp (const Type &start, const Type &end, const TypeFactor &factor)
Linear interpolation between two values.
template<typename LValueT , typename RValueT >
constexpr bool lt (const LValueT &left, const RValueT &right)
Compares two values for less than, calculates the epsilon automatically.
template<typename LValueT , typename RValueT >
constexpr bool lt (const LValueT &left, const RValueT &right, const double epsilon)
Compares two values for less than.
template<typename LValueT , typename RValueT >
constexpr bool lte (const LValueT &left, const RValueT &right)
Compares two values for less than or equal, calculates the epsilon automatically.
template<typename LValueT , typename RValueT >
constexpr bool lte (const LValueT &left, const RValueT &right, const double epsilon)
Compares two values for less than or equal.
template<typename Type1 , typename Type2 >
constexpr auto max (const Type1 a, const Type2 b)
Calculates the max of two values.
template<typename Type1 , typename Type2 >
constexpr auto min (const Type1 a, const Type2 b)
Calculates the min of two values.
template<typename Type >
Type mod (const Type &value, const Type &divisor)
Calculates the square of a value.
template<typename LValueT , typename RValueT >
constexpr bool mte (const LValueT &left, const RValueT &right)
Compares two values for greater than or equal, calculates the epsilon automatically.
template<typename Type >
constexpr Type pi () noexcept
Pi getter with precision of a given template type.
template<typename Type >
Type radians (const Type &degrees) noexcept
Converts degrees to radians.
template<typename TypeX , typename TypeMin1 , typename TypeMax1 , typename TypeMin2 , typename TypeMax2 >
static TypeX remap (TypeX x, TypeMin1 min1, TypeMax1 max1, TypeMin2 min2, TypeMax2 max2)
Remaps a value from one range to another, including support for reverse mapping.
template<typename Type >
auto sin (const Type &value)
Calculates the sine of a value.
template<typename Type >
Type sqrt (const Type &value)
Calculates the square root of a value.
template<typename Type >
auto tan (const Type &value)
Calculates the tangent of a value.
template<typename Type >
bool tossCoinWithChance (Type chance)
Simulates a perfect coin toss with a given chance of success.
Variables
constexpr double DOUBLE_COMPARISON_EPSILON = 1e-10
The epsilon value for double comparison.
constexpr double EPSILON_MULTIPLIER_FOR_EQUALITY = 100
The epsilon multiplier for equality comparison.
constexpr float FLOAT_COMPARISON_EPSILON = 1e-6f
The epsilon value for floating point comparison.
constexpr long double PI = 3.14159265358979323846264338327950288419716939937510
The value of PI.
Class Documentation
GLESC::Math::SelectSmallerFloatingType
struct GLESC::Math::SelectSmallerFloatingType
template<typename T1, typename T2>
struct GLESC::Math::SelectSmallerFloatingType< T1, T2 >
Selects the smaller floating-point type between two types.
The function selects the smaller floating-point type between two types. If both types are floating-point, it selects the type with the smaller size. If only one type is floating-point, it selects that type.
Template Parameters
T1 The first type
T2 The second type
Returns
The smaller floating-point type between the two types
Definition at line 219 of file Math.h.
Class Members
typedef conditional_t< is_floating_point_v< T1 > &&is_floating_point_v< T2 >, conditional_t<(sizeof(T1)< sizeof(T2)), T1, T2 >, conditional_t< is_floating_point_v< T1 >, T1, T2 > > type
Typedef Documentation
Direction
using GLESC::Math::Direction = typedef Vec3F
Alias for the direction type, directions are 3D vectors.
Definition at line 30 of file GeometryTypes.h.
Distance
using GLESC::Math::Distance = typedef float
Alias for the distance type.
Definition at line 34 of file GeometryTypes.h.
FaceIndices
using GLESC::Math::FaceIndices = typedef std::array<Index, 3>
Alias for the face indices type, a face is defined by 3 indices.
Definition at line 42 of file GeometryTypes.h.
Index
using GLESC::Math::Index = typedef unsigned int
Alias for any index type, no need for signed indices.
Definition at line 38 of file GeometryTypes.h.
MatrixData
template<typename Type , std::size_t N, std::size_t M> using GLESC::Math::MatrixData = typedef std::array<MatrixRow<Type, M>, N>
Type alias for a matrix data.
Template Parameters
Type The type of the matrix elements
N The number of rows in the matrix
M The number of columns in the matrix
Definition at line 29 of file MatrixTypes.h.
MatrixRow
template<typename Type , std::size_t M> using GLESC::Math::MatrixRow = typedef std::array<Type, M>
Type alias for a matrix row.
Template Parameters
Type The type of the matrix elements
M The number of columns in the matrix
Definition at line 21 of file MatrixTypes.h.
Point
using GLESC::Math::Point = typedef Vec3F
Alias for the point type, points are 3D vectors.
Definition at line 22 of file GeometryTypes.h.
Points
using GLESC::Math::Points = typedef std::vector<Point>
Alias for the points type, a collection of points.
Definition at line 26 of file GeometryTypes.h.
QuadIndices
using GLESC::Math::QuadIndices = typedef std::array<Index, 4>
Alias for the quad indices type, a quad is defined by 4 indices.
Definition at line 46 of file GeometryTypes.h.
VectorData
template<typename Type , std::size_t N> using GLESC::Math::VectorData = typedef std::array<Type, N>
Type alias for a vector data.
We use a std::array to store the vector data contiguously in memory with a fixed size and minimum overhead.
Template Parameters
Type The type of the vector elements
N The number of elements in the vector
Definition at line 23 of file VectorTypes.h.
Volume
using GLESC::Math::Volume = typedef float
Alias for the volume type.
Definition at line 18 of file GeometryTypes.h.
Function Documentation
abs()
template<typename Type > constexpr Type GLESC::Math::abs (const Type & value) constexpr
Calculates the absolute value of a number.
The absolute value of a number is the value without its sign.
Template Parameters
Type The type of the value
Parameters
value The value to calculate the absolute value of
Returns
The absolute value of the number
Definition at line 164 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        if constexpr (std::is_floating_point_v<Type>) {
            return std::fabs(value);
        }
        else if constexpr (std::is_unsigned_v<Type>) {
            return value;
        }
        else if constexpr (std::is_arithmetic_v<Type> && std::is_signed_v<Type>) {
            return std::abs(value);
        }
        else {
            // For user-defined types, you might want to call a member function
            // or free function that computes the absolute value for that type.
            // For demonstration, let's assume T has a member function abs() that
            // computes the absolute value:
            return value.abs();
        }
    }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::VectorAlgorithms::abs(), GLESC::Math::VectorAlgorithms::areParallel(), epsilon(), generateRandomNumber(), GLESC::Math::VectorAlgorithms::getOrthogonal(), GLESC::Transform::Interpolator::interpolate(), GLESC::Math::Plane::intersects(), GLESC::Math::PolyhedronFace::intersects(), and GLESC::Transform::Interpolator::pushTransform().
atan2()
template<typename Type > auto GLESC::Math::atan2 (const Type & value1, const Type & value2)
Calculates the arctangent of a value.
The arctangent of a value is the angle whose tangent is the value.
Template Parameters
Type The type of the value
Parameters
value1 The value to calculate the arctangent of
value2 The value to calculate the arctangent of
Returns
The arctangent of the value
Definition at line 645 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        return std::atan2(value1, value2);
    }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::VectorAlgorithms::vectorToEuler().
clamp()
template<typename Type1 , typename Type2 , typename Type3 > constexpr Type1 GLESC::Math::clamp (const Type1 & value, const Type2 & min, const Type3 & max) constexpr
Clamps a value between a minimum and maximum value.
Clamp is a function that limits a value to a specific range. If the value is less than the minimum, it returns the minimum. If the value is greater than the maximum, it returns the maximum. Otherwise, it returns the value.
Template Parameters
Type1 The type of the value to clamp
Type2 The type of the minimum value
Type3 The type of the maximum value
Parameters
value The value to clamp
min The minimum value
max The maximum value
Returns
The clamped value
Definition at line 198 of file Math.h.
{
        if (value < min) {
            return min;
        }
        if (value > max) {
            return max;
        }
        return value;
    }
References GLESC::isIterable_v, max(), and min().
Referenced by GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::VectorAlgorithms::clampWithVectors(), Default::init(), GLESC::Math::Sphere::intersects(), and remap().
cos()
template<typename Type > auto GLESC::Math::cos (const Type & value)
Calculates the cosine of a value.
The cosine of an angle is the ratio of the length of the adjacent side to the length of the hypotenuse.
Template Parameters
Type The type of the value
Parameters
value The value to calculate the cosine of
Returns
The cosine of the value
Definition at line 604 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        return std::cos(value);
    }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrixForAxis(), GLESC::Math::VectorAlgorithms::makeForwardVector(), GLESC::Math::VectorAlgorithms::makeRightVector(), GLESC::Math::VectorAlgorithms::makeUpVector(), GLESC::Math::VectorAlgorithms::rotateVector3D(), and GLESC::Render::MeshFactory::sphere().
degrees()
template<typename Type > Type GLESC::Math::degrees (const Type & radians) noexcept
Converts radians to degrees.
The formula is degrees = radians * 180 / PI
Template Parameters
Type The type of the values
Parameters
radians The value in radians
Returns
The value in degrees
Definition at line 130 of file Math.h.
{
        S_ASSERT_TRUE(std::is_floating_point_v<Type>, "Type must be floating point");
        return radians * Type(180) / Type(PI);
    }
References GLESC::isIterable_v, PI, radians(), and S_ASSERT_TRUE.
Referenced by GLESC::Math::Vector< Type, N >::angleDegrees(), radians(), and GLESC::Math::Vector< Type, N >::toDegrees().
epsilon() [1/2]
template<typename Type > constexpr auto GLESC::Math::epsilon () constexpr noexcept
Epsilon getter with precision of a given template type.
Template Parameters
Type The type of the epsilon value
Returns
The value of epsilon with the precision of the given type
Definition at line 63 of file Math.h.
{
        using DecayedType = std::remove_const_t<std::remove_reference_t<Type>>;
        if constexpr (std::is_same_v<DecayedType, float>) {
            return FLOAT_COMPARISON_EPSILON;
        }
        else if constexpr (std::is_same_v<DecayedType, double>) {
            return DOUBLE_COMPARISON_EPSILON;
        }
        else if constexpr (std::is_integral_v<DecayedType>) {
            return 0;
        }
        else {
            // Handle other floating point types
            return DecayedType(1e-7);
        }
    }
References DOUBLE_COMPARISON_EPSILON, FLOAT_COMPARISON_EPSILON, and GLESC::isIterable_v.
Referenced by eq(), gt(), gte(), lt(), and lte().
epsilon() [2/2]
template<typename Type > constexpr Type GLESC::Math::epsilon (Type valueParam) constexpr
Epsilon getter with precision of a given value.
Template Parameters
Type The type of the epsilon value
Parameters
valueParam The value to calculate the epsilon from
Returns
The value of epsilon with the precision of the given value
Definition at line 87 of file Math.h.
{
        auto value = abs(valueParam);
        if (value < 1) return epsilon<Type>();
        return epsilon<Type>() * value;
    }
References abs(), and GLESC::isIterable_v.
eq() [1/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::eq (const LValueT & left, const RValueT & right) constexpr
Compares two values for equality, calculates the epsilon automatically.
The function compares two values for equality. If the values are floating-point, it uses a fixed epsilon value for comparison. If the values are not floating-point, it uses exact comparison.
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
Returns
True if the values are equal, false otherwise
Definition at line 365 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>,
                      "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Determine the type with the lower precision
            using LowerPrecisionFloatingType = typename SelectSmallerFloatingType<LValueT, RValueT>::type;
            // Define a fixed epsilon value
            constexpr LowerPrecisionFloatingType fixedEpsilon = Math::epsilon<LowerPrecisionFloatingType>(
                EPSILON_MULTIPLIER_FOR_EQUALITY);
            // Fixed epsilon comparison
            return std::abs(left - right) < fixedEpsilon;
        }
        else {
            // Exact comparison for non-floating-point types
            return left == right;
        }
    }
References EPSILON_MULTIPLIER_FOR_EQUALITY, and GLESC::isIterable_v.
eq() [2/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::eq (const LValueT & left, const RValueT & right, const double epsilon) constexpr
Compares two values for equality.
The function compares two values for equality. If the values are floating-point, it uses a fixed epsilon value for comparison. If the values are not floating-point, it uses exact comparison.
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
epsilon The epsilon value for floating-point comparison
Returns
True if the values are equal, false otherwise
Definition at line 241 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>,
                      "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Fixed epsilon comparison
            return std::abs(left - right) < epsilon;
        }
        else {
            // Exact comparison for non-floating-point types
            return left == right;
        }
    }
References epsilon(), and GLESC::isIterable_v.
Referenced by GLESC::Math::VectorAlgorithms::areOrthogonal(), GLESC::Math::VectorAlgorithms::areParallel(), GLESC::Math::VectorAlgorithms::eq(), gt(), gt(), gte(), GLESC::Math::Line::intersects(), GLESC::Math::Plane::intersects(), GLESC::Math::PolyhedronFace::intersects(), GLESC::Math::Plane::intersects(), GLESC::Math::PolyhedronFace::intersects(), GLESC::Math::Plane::intersects(), GLESC::Math::Line::intersects(), GLESC::Math::MatrixAlgorithms::isInvertible(), GLESC::Math::VectorAlgorithms::isMultipleOf(), GLESC::Math::VectorAlgorithms::isNormalized(), lt(), lt(), lte(), lte(), GLESC::Math::MatrixAlgorithms::matrixMatrixDiv(), mte(), GLESC::Math::Plane::normalize(), GLESC::Math::VectorAlgorithms::normalize(), GLESC::Math::Matrix< Type, N, M >::operator==(), GLESC::Math::Plane::operator==(), GLESC::Physics::CollisionManager::updateCollider(), and GLESC::Math::VectorAlgorithms::vectorToEuler().
generateCompileTimeRandomNumber()
template<typename Type , Type min, Type max> constexpr Type GLESC::Math::generateCompileTimeRandomNumber () constexpr
Generates a compile time random number between min and max, specifically [min, max)
this uses the TIME macro to generate a random number
Template Parameters
Type The type of the random number
min The minimum value of the random number
max The maximum value of the random number
Returns
Definition at line 716 of file Math.h.
{
        static_assert(min < max, "max must be greater than min");
        // Extracting compile time in hh:mm:ss format
        constexpr auto time = __TIME__;
        constexpr auto hour = (time[0] - '0') * 10 + (time[1] - '0');
        constexpr auto minute = (time[3] - '0') * 10 + (time[4] - '0');
        constexpr auto second = (time[6] - '0') * 10 + (time[7] - '0');
        // Calculating a pseudo-random seed from the current time
        constexpr unsigned seed = hour * 3600 + minute * 60 + second;
        // Parameters for the Linear Congruential Generator
        constexpr unsigned a = 1664525; // the multiplier
        constexpr unsigned c = 1013904223; // the increment
        // Modulus is the difference between max and min. Cast to Type to ensure same type arithmetic
        constexpr Type modulus = static_cast<Type>(max - min);
        // Generating the random number using the Linear Congruential Generator formula
        // Cast each part of the operation to Type to ensure the arithmetic is done in the correct type
        constexpr Type randomNumber = static_cast<Type>((a * seed + c) % modulus) + min;
        return randomNumber;
    }
References GLESC::isIterable_v, max(), and min().
generateRandomNumber() [1/2]
template<typename Type > Type GLESC::Math::generateRandomNumber ()
Generates a random number with the widest range possible for the type.
Template Parameters
Type The type of the random number
Returns
A random number of the given type
Definition at line 749 of file Math.h.
{
        // For other types, use the standard limits
        // The maximum range for the random number is
        // [std::numeric_limits<Type>::lowest()/2, std::numeric_limits<Type>::max()/2)
        return generateRandomNumber(std::numeric_limits<Type>::lowest() / 4,
                                    std::numeric_limits<Type>::max() / 4);
    }
References generateRandomNumber().
Referenced by GLESC::Render::Skybox::calculateAverageColor(), and generateRandomNumber().
generateRandomNumber() [2/2]
template<typename Type , typename = std::enable_if_t<std::is_arithmetic_v<Type>>> Type GLESC::Math::generateRandomNumber (Type min, Type max)
Generates a random number between min and max, specifically [min, max)
The random number is generated using the Mersenne Twister algorithm The min and max values parameters must follow the following rules:
(max - min) < std::numeric_limits<Type>::max()
max >= min
Template Parameters
Type The type of the random number
Parameters
min The minimum value of the random number
max The maximum value of the random number
Returns
A random number of the given type in the range [min, max)
Definition at line 663 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        D_ASSERT_TRUE(max >= min, "Max must be greater than min");
        D_ASSERT_TRUE((max + GLESC::Math::abs(min)) < std::numeric_limits<Type>::max(),
                      "(Max - min) must be less than the max value of the type");
        static std::random_device rd;
        static std::mt19937 mt(rd());
        // If the type is uint, we use the fast unsigned int type for the distribution
        if constexpr (std::is_unsigned_v<Type> && std::is_integral_v<Type>) {
            std::uniform_int_distribution<std::mt19937::result_type> dist(min, max);
            return dist(mt);
        }
        // If the type is int, we just use the int type for the int distribution
        else if constexpr (std::is_integral_v<Type>) {
            std::uniform_int_distribution<Type> dist(min, max);
            return dist(mt);
        }
        else if constexpr (std::is_floating_point_v<Type>) {
            // For other types (int, etc.), use the type directly
            std::uniform_real_distribution<Type> dist(min, max);
            return dist(mt);
        }
        else {
            D_ASSERT_TRUE(false, "Type not supported for random number generation");
        }
    }
References abs(), D_ASSERT_TRUE, GLESC::isIterable_v, max(), min(), and S_ASSERT_TRUE.
gt() [1/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::gt (const LValueT & left, const RValueT & right) constexpr
Compares two values for greater than, calculates the epsilon automatically.
The function compares two values for greater than. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
Returns
True if the left value is greater than the right value, false otherwise
Definition at line 460 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Determine the type with the lower precision
            using LowerPrecisionFloatingType = typename SelectSmallerFloatingType<LValueT, RValueT>::type;
            // Define a fixed epsilon value
            constexpr LowerPrecisionFloatingType fixedEpsilon = Math::epsilon<LowerPrecisionFloatingType>(
                EPSILON_MULTIPLIER_FOR_EQUALITY);
            // Use epsilon for floating-point comparison
            return (left > right) && !eq(left, right, fixedEpsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left > right;
        }
    }
References EPSILON_MULTIPLIER_FOR_EQUALITY, eq(), and GLESC::isIterable_v.
gt() [2/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::gt (const LValueT & left, const RValueT & right, const double epsilon) constexpr
Compares two values for greater than.
The function compares two values for greater than. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
epsilon The epsilon value for floating-point comparison
Returns
True if the left value is greater than the right value, false otherwise
Definition at line 315 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Use epsilon for floating-point comparison
            return (left > right) && !eq(left, right, epsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left > right;
        }
    }
References epsilon(), eq(), and GLESC::isIterable_v.
Referenced by GLESC::Physics::getAxisFree(), GLESC::Physics::PhysicsManager::handleCollisions(), and GLESC::Physics::isFrictionApplied().
gte()
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::gte (const LValueT & left, const RValueT & right, const double epsilon) constexpr
Compares two values for greater than or equal.
The function compares two values for greater than or equal. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
epsilon The epsilon value for floating-point comparison
Returns
True if the left value is greater than or equal to the right value, false otherwise
Definition at line 340 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Use epsilon for floating-point comparison
            return (left > right) || eq(left, right, epsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left >= right;
        }
    }
References epsilon(), eq(), and GLESC::isIterable_v.
lerp()
template<typename Type , typename TypeFactor > constexpr Type GLESC::Math::lerp (const Type & start, const Type & end, const TypeFactor & factor) constexpr
Linear interpolation between two values.
Linear interpolation (lerp) is a method of generating values that are between two other values.
Template Parameters
Type The type of the values
TypeFactor The type of the factor
Parameters
start The start value
end The end value
factor The factor of the interpolation
Returns
The interpolated value
Definition at line 106 of file Math.h.
{
        return start + (end - start) * factor;
    }
References GLESC::isIterable_v.
Referenced by GLESC::Math::VectorAlgorithms::lerp().
lt() [1/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::lt (const LValueT & left, const RValueT & right) constexpr
Compares two values for less than, calculates the epsilon automatically.
The function compares two values for less than. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
Returns
True if the left value is less than the right value, false otherwise
Definition at line 397 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Determine the type with the lower precision
            using LowerPrecisionFloatingType = typename SelectSmallerFloatingType<LValueT, RValueT>::type;
            // Define a fixed epsilon value
            constexpr LowerPrecisionFloatingType fixedEpsilon = Math::epsilon<LowerPrecisionFloatingType>(
                EPSILON_MULTIPLIER_FOR_EQUALITY);
            // Use epsilon for floating-point comparison
            return (left < right) && !eq(left, right, fixedEpsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left < right;
        }
    }
References EPSILON_MULTIPLIER_FOR_EQUALITY, eq(), and GLESC::isIterable_v.
lt() [2/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::lt (const LValueT & left, const RValueT & right, const double epsilon) constexpr
Compares two values for less than.
The function compares two values for less than. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
epsilon The epsilon value for floating-point comparison
Returns
True if the left value is less than the right value, false otherwise
Definition at line 266 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Use epsilon for floating-point comparison
            return (left < right) && !eq(left, right, epsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left < right;
        }
    }
References epsilon(), eq(), and GLESC::isIterable_v.
Referenced by GLESC::Physics::getAxisFree(), and GLESC::Physics::isFrictionApplied().
lte() [1/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::lte (const LValueT & left, const RValueT & right) constexpr
Compares two values for less than or equal, calculates the epsilon automatically.
The function compares two values for less than or equal. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
Returns
True if the left value is less than or equal to the right value, false otherwise
Definition at line 429 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Determine the type with the lower precision
            using LowerPrecisionFloatingType = typename SelectSmallerFloatingType<LValueT, RValueT>::type;
            // Define a fixed epsilon value
            constexpr LowerPrecisionFloatingType fixedEpsilon = Math::epsilon<LowerPrecisionFloatingType>(
                EPSILON_MULTIPLIER_FOR_EQUALITY);
            // Use epsilon for floating-point comparison
            return (left < right) || eq(left, right, fixedEpsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left <= right;
        }
    }
References EPSILON_MULTIPLIER_FOR_EQUALITY, eq(), and GLESC::isIterable_v.
lte() [2/2]
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::lte (const LValueT & left, const RValueT & right, const double epsilon) constexpr
Compares two values for less than or equal.
The function compares two values for less than or equal. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
epsilon The epsilon value for floating-point comparison
Returns
True if the left value is less than or equal to the right value, false otherwise
Definition at line 290 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Use epsilon for floating-point comparison
            return (left < right) || eq(left, right, epsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left <= right;
        }
    }
References epsilon(), eq(), and GLESC::isIterable_v.
max()
template<typename Type1 , typename Type2 > constexpr auto GLESC::Math::max (const Type1 a, const Type2 b) constexpr
Calculates the max of two values.
Template Parameters
Type1 The type of the first value.
Type2 The type of the second value.
Parameters
a The first value.
b The second value.
Returns
The max of the two values, promoted to the common type of the two input types.
Definition at line 534 of file Math.h.
{
        using CommonType = std::common_type_t<Type1, Type2>;
        return a > b ? static_cast<CommonType>(a) : static_cast<CommonType>(b);
    }
References GLESC::isIterable_v.
Referenced by GLESC::Math::BoundingVolume::BoundingVolume(), clamp(), GLESC::Math::Vector< Type, N >::clamp(), GLESC::Math::Vector< Type, N >::clamp(), GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::VectorAlgorithms::clampWithVectors(), generateCompileTimeRandomNumber(), generateRandomNumber(), GLESC::Math::PolyhedronFace::intersects(), and GLESC::Math::BoundingVolume::setVolume().
min()
template<typename Type1 , typename Type2 > constexpr auto GLESC::Math::min (const Type1 a, const Type2 b) constexpr
Calculates the min of two values.
Template Parameters
Type1 The type of the first value.
Type2 The type of the second value.
Parameters
a The first value.
b The second value.
Returns
The min of the two values, promoted to the common type of the two input types.
Definition at line 520 of file Math.h.
{
        using CommonType = std::common_type_t<Type1, Type2>;
        return a < b ? static_cast<CommonType>(a) : static_cast<CommonType>(b);
    }
References GLESC::isIterable_v.
Referenced by GLESC::Math::BoundingVolume::BoundingVolume(), clamp(), GLESC::Math::VectorAlgorithms::clampWithValues(), GLESC::Math::VectorAlgorithms::clampWithVectors(), generateCompileTimeRandomNumber(), generateRandomNumber(), GLESC::Transform::Interpolator::interpolate(), GLESC::Math::PolyhedronFace::intersects(), and GLESC::Math::BoundingVolume::setVolume().
mod()
template<typename Type > Type GLESC::Math::mod (const Type & value, const Type & divisor)
Calculates the square of a value.
Mod operation is the remainder of the division of one number by another.
Template Parameters
Type The type of the value
Parameters
value The value to square
Returns
The square of the value
Definition at line 143 of file Math.h.
{
        static_assert(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        if constexpr (std::is_integral_v<Type>) {
            // For integer types, use the modulo operator %
            return value % divisor;
        }
        else {
            // For floating-point types, use std::fmod
            return std::fmod(value, divisor);
        }
    }
References GLESC::isIterable_v.
Referenced by GLESC::Math::VectorAlgorithms::modWithValue(), and GLESC::Math::VectorAlgorithms::modWithVector().
mte()
template<typename LValueT , typename RValueT > constexpr bool GLESC::Math::mte (const LValueT & left, const RValueT & right) constexpr
Compares two values for greater than or equal, calculates the epsilon automatically.
The function compares two values for greater than or equal. Makes use of the eq function for floating-point types.
See also
eq
Template Parameters
LValueT The type of the left value
RValueT The type of the right value
Parameters
left The left value
right The right value
Returns
True if the left value is greater than or equal to the right value, false otherwise
Definition at line 491 of file Math.h.
{
        static_assert(std::is_arithmetic_v<LValueT> && std::is_arithmetic_v<RValueT>, "Types must be arithmetic");
        if constexpr (std::is_floating_point_v<LValueT> || std::is_floating_point_v<RValueT>) {
            // Determine the type with the lower precision
            using LowerPrecisionFloatingType = typename SelectSmallerFloatingType<LValueT, RValueT>::type;
            // Define a fixed epsilon value
            constexpr LowerPrecisionFloatingType fixedEpsilon = Math::epsilon<LowerPrecisionFloatingType>(
                EPSILON_MULTIPLIER_FOR_EQUALITY);
            // Use epsilon for floating-point comparison
            return (left > right) || eq(left, right, fixedEpsilon);
        }
        else {
            // Exact comparison for non-floating-point types
            return left >= right;
        }
    }
References EPSILON_MULTIPLIER_FOR_EQUALITY, eq(), and GLESC::isIterable_v.
pi()
template<typename Type > constexpr Type GLESC::Math::pi () constexpr noexcept
Pi getter with precision of a given template type.
Template Parameters
Type The type of the pi value
Returns
The value of pi with the precision of the given type
Definition at line 48 of file Math.h.
{
        if constexpr (std::is_floating_point<Type>::value) {
            return static_cast<Type>(PI);
        }
        else {
            return Type(3);
        }
    }
References GLESC::isIterable_v, and PI.
radians()
template<typename Type > Type GLESC::Math::radians (const Type & degrees) noexcept
Converts degrees to radians.
The formula is radians = degrees * PI / 180
Template Parameters
Type The type of the values
Parameters
degrees The value in degrees
Returns
The value in radians
Definition at line 118 of file Math.h.
{
        return degrees * Type(PI) / Type(180);
    }
References degrees(), GLESC::isIterable_v, and PI.
Referenced by GLESC::Math::MatrixAlgorithms::calculateProjectionMatrix(), degrees(), GLESC::Math::Matrix< Type, N, M >::makeProjectionMatrix(), and GLESC::Math::Vector< Type, N >::toRads().
remap()
template<typename TypeX , typename TypeMin1 , typename TypeMax1 , typename TypeMin2 , typename TypeMax2 > static TypeX GLESC::Math::remap (TypeX x, TypeMin1 min1, TypeMax1 max1, TypeMin2 min2, TypeMax2 max2) static
Remaps a value from one range to another, including support for reverse mapping.
Maps the value x from the range [min1, max1] to the range [min2, max2].
Template Parameters
TypeX The type of the value to be remapped.
TypeMin1 The type of the lower bound of the input range.
TypeMax1 The type of the upper bound of the input range.
TypeMin2 The type of the lower bound of the output range.
TypeMax2 The type of the upper bound of the output range.
Parameters
x The value to be remapped.
min1 The lower bound of the input range.
max1 The upper bound of the input range.
min2 The lower bound of the output range.
max2 The upper bound of the output range.
Returns
Remapped value.
Definition at line 557 of file Math.h.
{
        // Ensure the input value is clamped within the input range
        x = Math::clamp(x, min1, max1);
        // Calculate the proportion of x within the input range
        TypeX t = (x - min1) / (max1 - min1);
        // Map the proportion to the output range
        return min2 + t * (max2 - min2);
    }
References clamp(), and GLESC::isIterable_v.
sin()
template<typename Type > auto GLESC::Math::sin (const Type & value)
Calculates the sine of a value.
The sine of an angle is the ratio of the length of the opposite side to the length of the hypotenuse.
Template Parameters
Type The type of the value
Parameters
value The value to calculate the sine of
Returns
The sine of the value
Definition at line 617 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        return std::sin(value);
    }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::MatrixMixedAlgorithms::getRotate3DMatrixForAxis(), GLESC::Math::VectorAlgorithms::makeForwardVector(), GLESC::Math::VectorAlgorithms::makeRightVector(), GLESC::Math::VectorAlgorithms::makeUpVector(), GLESC::Math::VectorAlgorithms::rotateVector3D(), and GLESC::Render::MeshFactory::sphere().
sqrt()
template<typename Type > Type GLESC::Math::sqrt (const Type & value)
Calculates the square root of a value.
The square root of a number is a value that, when multiplied by itself, gives the original number.
Template Parameters
Type The type of the value
Parameters
value The value to calculate the square root of
Returns
The square root of the value
Definition at line 574 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        D_ASSERT_TRUE(value >= Type(0), "Value must be positive");
        Type result = Type();
        if constexpr (std::is_arithmetic_v<Type>) {
            if constexpr (std::is_integral_v<Type>) {
                return static_cast<Type>(std::round(std::sqrt(static_cast<double>(value))));
            }
            else {
                return static_cast<Type>(std::sqrt(value));
            }
        }
        else {
            // For user-defined types, you might want to call a member function
            // or free function that computes the square root for that type.
            // For demonstration, let's assume T has a member function sqrt() that
            // computes the square root:
            result = value.sqrt();
        }
        return result;
    }
References D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::PolyhedronFactory::Regular::dodeca(), GLESC::PolyhedronFactory::Regular::icos(), GLESC::Math::VectorAlgorithms::length(), GLESC::PolyhedronFactory::Regular::tetra(), GLESC::ResMng::Texture::TextureSurface::toString(), and GLESC::Math::VectorAlgorithms::vectorToEuler().
tan()
template<typename Type > auto GLESC::Math::tan (const Type & value)
Calculates the tangent of a value.
The tangent of an angle is the ratio of the length of the opposite side to the length of the adjacent side.
Template Parameters
Type The type of the value
Parameters
value The value to calculate the tangent of
Returns
The tangent of the value
Definition at line 631 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        return std::tan(value);
    }
References GLESC::isIterable_v, and S_ASSERT_TRUE.
Referenced by GLESC::Math::MatrixAlgorithms::perspective().
tossCoinWithChance()
template<typename Type > bool GLESC::Math::tossCoinWithChance (Type chance)
Simulates a perfect coin toss with a given chance of success.
The function returns true with the given chance of success, and false otherwise. Makes use of the generateRandomNumber function to generate a random number between 0 and 1.
See also
generateRandomNumber
Template Parameters
Type The type of the chance
Parameters
chance The chance of success
Returns
True with the given chance of success, false otherwise
Definition at line 701 of file Math.h.
{
        S_ASSERT_TRUE(std::is_arithmetic_v<Type>, "Type must be arithmetic");
        D_ASSERT_TRUE(chance >= 0.0f && chance <= 1.0f, "Chance must be between 0 and 1");
        return generateRandomNumber<float>(0.0f, 1.0f) < chance;
    }
References D_ASSERT_TRUE, GLESC::isIterable_v, and S_ASSERT_TRUE.
Variable Documentation
DOUBLE_COMPARISON_EPSILON
constexpr double GLESC::Math::DOUBLE_COMPARISON_EPSILON = 1e-10 constexpr
The epsilon value for double comparison.
it is 1e-10 because of the higher precision of double
Definition at line 30 of file Math.h.
Referenced by epsilon().
EPSILON_MULTIPLIER_FOR_EQUALITY
constexpr double GLESC::Math::EPSILON_MULTIPLIER_FOR_EQUALITY = 100 constexpr
The epsilon multiplier for equality comparison.
it is 100 because of the lower precision of float
Definition at line 35 of file Math.h.
Referenced by eq(), gt(), lt(), lte(), and mte().
FLOAT_COMPARISON_EPSILON
constexpr float GLESC::Math::FLOAT_COMPARISON_EPSILON = 1e-6f constexpr
The epsilon value for floating point comparison.
it is 1e-6 because of the lower precision of float
Definition at line 25 of file Math.h.
Referenced by epsilon().
PI
constexpr long double GLESC::Math::PI = 3.14159265358979323846264338327950288419716939937510 constexpr
The value of PI.
It is defined with 50 decimal numbers, just in case the precision is needed
Definition at line 40 of file Math.h.
Referenced by degrees(), GLESC::Math::VectorAlgorithms::makeRightVector(), pi(), and radians().