GLESC: GLESC::Physics Namespace Reference
GLESC::Physics Namespace Reference
Classes
class Collider
The collider class component for entities.
class CollisionInformation
class CollisionManager
class Physics
class PhysicsManager
Typedefs
using Acceleration = Vec3F
using AngularAcceleration = Vec3F
using AngularForce = Vec3F
using AngularVelocity = Vec3F
using AxisConstraints = std::array< std::array< bool, 2 >, 3 >
using Bounciness = float
using Force = Vec3F
using ForwardAcceleration = float
using ForwardForce = float
using ForwardVelocity = float
using Friction = float
using Mass = float
using Scalar = float
using Velocity = Vec3F
Functions
AxisConstraints getAxisFree (const Collider &collider)
Velocity getBouncingVelocity (const Velocity &velocity, const Vec3F &collisionNormal, float bounciness)
Velocity getVelocityWithFriction (const Physics &physics, const std::vector< Physics * > &physicsOfCollided)
bool isFrictionApplied (const Physics &physics, const AxisConstraints &freeAxis)
Typedef Documentation
Acceleration
using GLESC::Physics::Acceleration = typedef Vec3F
Definition at line 17 of file PhysicsTypes.h.
AngularAcceleration
using GLESC::Physics::AngularAcceleration = typedef Vec3F
Definition at line 24 of file PhysicsTypes.h.
AngularForce
using GLESC::Physics::AngularForce = typedef Vec3F
Definition at line 23 of file PhysicsTypes.h.
AngularVelocity
using GLESC::Physics::AngularVelocity = typedef Vec3F
Definition at line 22 of file PhysicsTypes.h.
AxisConstraints
using GLESC::Physics::AxisConstraints = typedef std::array<std::array<bool, 2>, 3>
Definition at line 61 of file PhysicsManager.cpp.
Bounciness
using GLESC::Physics::Bounciness = typedef float
Definition at line 19 of file PhysicsTypes.h.
Force
using GLESC::Physics::Force = typedef Vec3F
Definition at line 16 of file PhysicsTypes.h.
ForwardAcceleration
using GLESC::Physics::ForwardAcceleration = typedef float
Definition at line 28 of file PhysicsTypes.h.
ForwardForce
using GLESC::Physics::ForwardForce = typedef float
Definition at line 27 of file PhysicsTypes.h.
ForwardVelocity
using GLESC::Physics::ForwardVelocity = typedef float
Definition at line 26 of file PhysicsTypes.h.
Friction
using GLESC::Physics::Friction = typedef float
Definition at line 18 of file PhysicsTypes.h.
Mass
using GLESC::Physics::Mass = typedef float
Definition at line 14 of file PhysicsTypes.h.
Scalar
using GLESC::Physics::Scalar = typedef float
Definition at line 20 of file PhysicsTypes.h.
Velocity
using GLESC::Physics::Velocity = typedef Vec3F
Definition at line 15 of file PhysicsTypes.h.
Function Documentation
getAxisFree()
AxisConstraints GLESC::Physics::getAxisFree (const Collider & collider)
Definition at line 63 of file PhysicsManager.cpp.
{
        AxisConstraints isAxisFree = {{
            //   +     -    // Axis
            {true, true}, // X
            {true, true}, // Y
            {true, true} // Z
        }};
        for (const Vec3F& collisionDepth : collider.getCollisionInformation().getCollisionDepthForAxis()) {
            for (int i = 0; i < 3; ++i) {
                // Check if the collision depth is positive or negative
                isAxisFree[i][0] = isAxisFree[i][0] && !Math::gt(collisionDepth[i], 0.0f);
                isAxisFree[i][1] = isAxisFree[i][1] && !Math::lt(collisionDepth[i], 0.0f);
            }
        }
        return isAxisFree;
    }
References GLESC::Physics::CollisionInformation::getCollisionDepthForAxis(), GLESC::Physics::Collider::getCollisionInformation(), GLESC::Math::gt(), GLESC::isIterable_v, and GLESC::Math::lt().
Referenced by GLESC::Physics::PhysicsManager::handleCollisions().
getBouncingVelocity()
Velocity GLESC::Physics::getBouncingVelocity (const Velocity & velocity, const Vec3F & collisionNormal, float bounciness)
Definition at line 54 of file PhysicsManager.cpp.
{
        Velocity bouncingVelocity = velocity * bounciness;
        // Reflect, for bounciness
        bouncingVelocity = bouncingVelocity.reflect(collisionNormal);
        return bouncingVelocity;
    }
References GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::reflect().
Referenced by GLESC::Physics::PhysicsManager::handleCollisions().
getVelocityWithFriction()
Velocity GLESC::Physics::getVelocityWithFriction (const Physics & physics, const std::vector< Physics * > & physicsOfCollided)
Definition at line 81 of file PhysicsManager.cpp.
{
        Velocity velocityWithFriction = physics.getVelocity();
        for (auto otherPhysics : physicsOfCollided) {
            // Calculate the average friction coefficient between the two objects
            float frictionCoefficient = otherPhysics->getFriction() + physics.getFriction();
            // Calculate the friction force based on the velocity and friction coefficient
            Vec3F frictionForce = physics.getVelocity() * frictionCoefficient;
            // Apply the friction force to the total velocity
            velocityWithFriction -= frictionForce;
        }
        return velocityWithFriction;
    }
References GLESC::Physics::Physics::getFriction(), GLESC::Physics::Physics::getVelocity(), and GLESC::isIterable_v.
Referenced by GLESC::Physics::PhysicsManager::handleCollisions().
isFrictionApplied()
bool GLESC::Physics::isFrictionApplied (const Physics & physics, const AxisConstraints & freeAxis)
Definition at line 96 of file PhysicsManager.cpp.
{
        bool isFrictionApplied = true;
        for (int i = 0; i < 3; ++i) {
            isFrictionApplied = Math::gt(physics.getVelocity()[i], 0) && freeAxis[i][0] && isFrictionApplied;
            isFrictionApplied = Math::lt(physics.getVelocity()[i], 0) && freeAxis[i][1] && isFrictionApplied;
        }
        return isFrictionApplied;
    }
References GLESC::Physics::Physics::getVelocity(), GLESC::Math::gt(), isFrictionApplied(), GLESC::isIterable_v, and GLESC::Math::lt().
Referenced by GLESC::Physics::PhysicsManager::handleCollisions(), and isFrictionApplied().