GLESC: GLESC::PolyhedronFactory::Regular Namespace Reference
GLESC::PolyhedronFactory::Regular Namespace Reference
Functions
static GLESC::Math::Polyhedron cube ()
Regular polyhedron with 6 faces (cube, all faces are squares)
static GLESC::Math::Polyhedron dodeca ()
Regular polyhedron with 12 faces (dodecahedron, all faces are pentagons)
static GLESC::Math::Polyhedron icos ()
Regular polyhedron with 20 faces (icosahedron, all faces are triangles, looks like a 20 side dice in D&D)
static GLESC::Math::Polyhedron octa ()
Regular polyhedron with 8 faces (octahedron, all faces are triangles, looks like two pyramids glued together)
static GLESC::Math::Polyhedron tetra ()
Regular polyhedron with 4 faces (pyramid, all faces are triangles)
Function Documentation
cube()
Polyhedron GLESC::PolyhedronFactory::Regular::cube () static
Regular polyhedron with 6 faces (cube, all faces are squares)
Returns
A cube
Definition at line 37 of file PolyhedronFactory.cpp.
                      {
        return Common::rectangularCuboid(1, 1, 1);
    }
References GLESC::PolyhedronFactory::Common::rectangularCuboid().
dodeca()
Polyhedron GLESC::PolyhedronFactory::Regular::dodeca () static
Regular polyhedron with 12 faces (dodecahedron, all faces are pentagons)
Returns
A dodecahedron
Definition at line 64 of file PolyhedronFactory.cpp.
{
        Polyhedron dodecahedron;
        [[maybe_unused]] double phi = (1.0 + sqrt(5.0)) / 2.0;
        return dodecahedron;
    }
References GLESC::isIterable_v, and GLESC::Math::sqrt().
icos()
Polyhedron GLESC::PolyhedronFactory::Regular::icos () static
Regular polyhedron with 20 faces (icosahedron, all faces are triangles, looks like a 20 side dice in D&D)
Returns
An icosahedron
Definition at line 71 of file PolyhedronFactory.cpp.
                      {
        Polyhedron icosahedron;
        double phi = (1.0 + sqrt(5.0)) / 2.0;
        icosahedron.addVertex(Point{0, 1, phi});
        icosahedron.addVertex(Point{0, 1, -phi});
        icosahedron.addVertex(Point{0, -1, phi});
        icosahedron.addVertex(Point{0, -1, -phi});
        icosahedron.addVertex(Point{1, phi, 0});
        icosahedron.addVertex(Point{1, -phi, 0});
        icosahedron.addVertex(Point{-1, phi, 0});
        icosahedron.addVertex(Point{-1, -phi, 0});
        icosahedron.addVertex(Point{phi, 0, 1});
        icosahedron.addVertex(Point{phi, 0, -1});
        icosahedron.addVertex(Point{-phi, 0, 1});
        icosahedron.addVertex(Point{-phi, 0, -1});
        icosahedron.addFace({0, 4, 8});
        icosahedron.addFace({0, 4, 10});
        icosahedron.addFace({0, 5, 11});
        icosahedron.addFace({0, 5, 9});
        icosahedron.addFace({1, 6, 8});
        icosahedron.addFace({1, 6, 10});
        icosahedron.addFace({1, 7, 9});
        icosahedron.addFace({1, 7, 11});
        icosahedron.addFace({2, 4, 8});
        icosahedron.addFace({2, 4, 10});
        icosahedron.addFace({2, 5, 9});
        icosahedron.addFace({2, 5, 11});
        icosahedron.addFace({3, 6, 8});
        icosahedron.addFace({3, 6, 10});
        icosahedron.addFace({3, 7, 9});
        icosahedron.addFace({3, 7, 11});
        icosahedron.addFace({4, 8, 10});
        icosahedron.addFace({5, 9, 11});
        icosahedron.addFace({6, 8, 10});
        icosahedron.addFace({7, 9, 11});
        return icosahedron;
    }
References GLESC::Math::Polyhedron::addVertex(), GLESC::isIterable_v, and GLESC::Math::sqrt().
octa()
Polyhedron GLESC::PolyhedronFactory::Regular::octa () static
Regular polyhedron with 8 faces (octahedron, all faces are triangles, looks like two pyramids glued together)
Returns
An octahedron
Definition at line 41 of file PolyhedronFactory.cpp.
                      {
        Polyhedron octahedron;
        // Vertices
        octahedron.addVertex(Point{0, 0, 1});
        octahedron.addVertex(Point{0, 0, -1});
        octahedron.addVertex(Point{1, 0, 0});
        octahedron.addVertex(Point{-1, 0, 0});
        octahedron.addVertex(Point{0, 1, 0});
        octahedron.addVertex(Point{0, -1, 0});
        // Faces
        octahedron.addFace({0, 2, 4});
        octahedron.addFace({0, 4, 3});
        octahedron.addFace({0, 3, 5});
        octahedron.addFace({0, 5, 2});
        octahedron.addFace({1, 2, 5});
        octahedron.addFace({1, 5, 3});
        octahedron.addFace({1, 3, 4});
        octahedron.addFace({1, 4, 2});
        return octahedron;
    }
References GLESC::Math::Polyhedron::addVertex(), and GLESC::isIterable_v.
tetra()
Polyhedron GLESC::PolyhedronFactory::Regular::tetra () static
Regular polyhedron with 4 faces (pyramid, all faces are triangles)
Returns
A tetrahedron
Definition at line 17 of file PolyhedronFactory.cpp.
                       {
        Polyhedron tetrahedron;
        double sqrt2_3 = sqrt(2.0 / 3.0);
        double sqrt3_3 = sqrt(1.0 / 3.0);
        double sqrt6_3 = sqrt(2.0 / 9.0);
        // Vertices
        tetrahedron.addVertex(Point{0, 0, sqrt2_3});
        tetrahedron.addVertex(Point{2.0 / 3.0 * sqrt3_3, 0, -1 * sqrt6_3});
        tetrahedron.addVertex(Point{-sqrt3_3 / 3.0, 1 / sqrt3_3, -1 * sqrt6_3});
        tetrahedron.addVertex(Point{-sqrt3_3 / 3.0, -1 / sqrt3_3, -1 * sqrt6_3});
        // Faces
        tetrahedron.addFace({0, 1, 2});
        tetrahedron.addFace({0, 1, 3});
        tetrahedron.addFace({0, 2, 3});
        tetrahedron.addFace({1, 2, 3});
        return tetrahedron;
    }
References GLESC::isIterable_v, and GLESC::Math::sqrt().