GLESC: PolyhedronFactory::Common Namespace Reference
PolyhedronFactory::Common Namespace Reference
Functions
Polyhedron icosphere (int subdivisions)
Polyhedron prism (double radius, double height, unsigned int sides)
Polyhedron pyramid (double radius, double height, unsigned int baseSides)
Polyhedron rectangularCuboid (double width, double height, double depth)
Function Documentation
icosphere()
Polyhedron PolyhedronFactory::Common::icosphere (int subdivisions)
Definition at line 140 of file PolyhedronFactory.cpp.
{
        Polyhedron sphere;
        return sphere;
    }
prism()
Polyhedron PolyhedronFactory::Common::prism (double radius, double height, unsigned int sides)
Definition at line 134 of file PolyhedronFactory.cpp.
{
        Polyhedron prism;
        [[maybe_unused]] double angle = 2.0 * pi<double>() / sides;
        return prism;
    }
References prism().
Referenced by prism().
pyramid()
Polyhedron PolyhedronFactory::Common::pyramid (double radius, double height, unsigned int baseSides)
Definition at line 112 of file PolyhedronFactory.cpp.
{
        Polyhedron pyramid;
        return pyramid;
    }
References pyramid().
Referenced by pyramid().
rectangularCuboid()
Polyhedron PolyhedronFactory::Common::rectangularCuboid (double width, double height, double depth)
Definition at line 118 of file PolyhedronFactory.cpp.
{
        Polyhedron cuboid;
        // Front and back face vertices
        cuboid.addVertex(Point{-width / 2, -height / 2, depth / 2}); // 0
        cuboid.addVertex(Point{width / 2, -height / 2, depth / 2}); // 1
        cuboid.addVertex(Point{width / 2, height / 2, depth / 2}); // 2
        cuboid.addVertex(Point{-width / 2, height / 2, depth / 2}); // 3
        cuboid.addVertex(Point{-width / 2, -height / 2, -depth / 2}); // 4
        cuboid.addVertex(Point{width / 2, -height / 2, -depth / 2}); // 5
        cuboid.addVertex(Point{width / 2, height / 2, -depth / 2}); // 6
        cuboid.addVertex(Point{-width / 2, height / 2, -depth / 2}); // 7
        // Faces
        return cuboid;
    }
References GLESC::Math::Polyhedron::addVertex().