GLESC: GLESC::Render::ColorRgba Struct Reference
GLESC::Render::ColorRgba Struct Reference
Color in RGBA values (x = [0] = R, y = [1] = G, z = [2] = B, w = [3] = A)
#include <RendererTypes.h>
Public Member Functions
ColorRgba ()=default
ColorRgba (ColorRgb &other) noexcept
ColorRgba (ColorRgba &&other) noexcept=default
ColorRgba (const ColorRgb &other) noexcept
ColorRgba (const ColorRgba &other)=default
ColorRgba (float r, float g, float b, float a)
~ColorRgba ()=default
const float & getA () const
float & getAModifiable ()
float getANormalized () const
const float & getB () const
float & getBModifiable ()
float getBNormalized () const
const float & getG () const
float & getGModifiable ()
float getGNormalized () const
const float & getR () const
Vec4F getRGBAVec4FNormalized () const
float & getRModifiable ()
float getRNormalized () const
ColorRgba & operator= (ColorRgba &&other) noexcept=default
ColorRgba & operator= (const ColorRgba &other)=default
void setA (float aParam)
void setB (float bParam)
void setG (float gParam)
void setR (float rParam)
std::string toString () const
Public Member Functions inherited from GLESC::Math::Vector< Type, N >
constexpr Vector () noexcept
Default constructor.
template<typename... Args, typename = std::enable_if_t<(sizeof...(Args) == N)>>
constexpr Vector (Args &&... args) noexcept
Variadic constructor.
constexpr Vector (const Type(&list)[N]) noexcept
Array constructor.
constexpr Vector (const Vector &other) noexcept
Copy constructor.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &&other) noexcept
Move constructor, for vectors of different sizes.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &other) noexcept
Copy constructor.
constexpr Vector (const VectorData< Type, N > &values) noexcept
Copy constructor for VectorData.
constexpr Vector (Type values) noexcept
Fill constructor.
constexpr Vector (Vector &&other) noexcept
Move constructor.
constexpr Vector (VectorData< Type, N > &&values) noexcept
Move constructor for VectorData.
Vector abs () const noexcept
Returns the absolute value of the vector.
Type angle (const Vector &other) const
Gives the rads between two vectors.
Type angleDegrees (const Vector &other) const
Gives the angle between two vectors in degrees.
Vector clamp (const Vector &min, const Vector &max) const
Clamps the vector to a given range.
Vector clamp (Type min, Type max) const
Clamps the vector to a given range.
Vector< Type, 3 > cross (const Vector< Type, 3 > &other) const
Calculates the cross product of two vectors.
Vector< Type, N - 1 > dehomogenize () const
Dehomogenizes the vector.
Type distance (const Vector &other) const
Gives the distance between two vectors.
Type distanceSquared (const Vector &other) const
Gives the squared distance between two vectors.
Type dot (const Vector &rhs) const
Returns the dot product of two vectors.
const Type & get (size_t index) const
Returns the data of the vector given an index.
Vector getOrthogonal () const
Get an orthogonal (or perpendicular) vector.
Type getW () const
Returns the w (fourth) value of the vector.
const Type & getX () const
Returns the x (first) value of the vector.
Type getY () const
Returns the y (second) value of the vector.
Type getZ () const
Returns the z (third) value of the vector.
Vector< Type, N+1 > homogenize () const
Homogenizes the vector.
bool isCollinear (const std::vector< Vector< Type, 3 > > &points) const
Checks if the current vector is a scalar multiple of some vectors.
Type isHomogeneous () const
Checks if the vector is homogeneous.
bool isMultipleOf (const Vector &other) const
Checks if the current vector is a scalar multiple of another vector.
bool isNormalized () const
checks if the vector is normalized
bool isOrthogonal (const Vector &other) const
Checks if the vector is orthogonal to another vector.
bool isParallel (const Vector &other) const
Checks if the vector is parallel to another vector.
bool isZero () const
Checks if the vector is a zero vector.
Type length () const
Returns the length of the vector.
Type lengthSquared () const
Returns the squared length of the vector.
Vector lerp (const Vector &other, Type factor) const
Calculates the linear interpolation between two vectors using a factor.
Type magnitude () const
Returns the length of the vector.
Vector & makeForward (const Vector &rotation)
Returs the forward vector of a rotation.
Vector & makeRight (const Vector &rotation)
Returns the right vector of a rotation.
Vector & makeUp (const Vector &rotation)
Returns the up vector of a rotation.
Vector mod (Type divisor) const
Returns the mod of the vector given a divisor.
Vector mod (Vector divisors) const
Returns the mod of the vector given a vector of divisors.
Vector & normalize ()
Normalizes the vector.
Vector normalize () const
Normalizes the vector.
constexpr bool operator!= (const Vector &rhs) const
Inequality operator for vectors.
constexpr Vector operator* (const Vector &rhs) const
Overloads the '*' operator for vector multiplication.
constexpr Vector operator* (Type scalar) const
Overloads the '*' operator for scalar multiplication.
constexpr Vector operator*= (const Type scalar)
In-place multiplication with a scalar.
constexpr Vector operator*= (const Vector &rhs)
In-place multiplication with another vector.
constexpr Vector operator+ (const Type &scalar) const
Overloads the '+' operator for scalar addition.
constexpr Vector operator+ (const Vector &rhs) const
Overloads the '+' operator for vector addition.
constexpr Vector operator+= (const Vector &rhs)
In-place addition with another vector.
constexpr Vector operator+= (Type scalar)
In-place addition with a scalar.
constexpr Vector operator- () const
Overloads the unary '-' operator for negation.
constexpr Vector operator- (const Type &scalar) const
Overloads the '-' operator for scalar subtraction.
constexpr Vector operator- (const Vector &rhs) const
Overloads the '-' operator for vector subtraction.
constexpr Vector operator-= (const Type scalar)
In-place subtraction with a scalar.
constexpr Vector operator-= (const Vector &rhs)
In-place subtraction with another vector.
constexpr Vector operator/ (const Vector &rhs) const
Overloads the '/' operator for vector division.
constexpr Vector operator/ (Type scalar) const
Overloads the '/' operator for scalar division.
constexpr Vector operator/= (const Type scalar)
In-place division with a scalar.
constexpr Vector operator/= (const Vector &rhs)
In-place division with another vector.
constexpr bool operator< (const Vector &rhs) const
Less than operator for vectors.
constexpr bool operator<= (const Vector &rhs) const
Less than or equal to operator for vectors.
constexpr Vector & operator= (const Type(&list)[N]) noexcept
Array assignment operator.
constexpr Vector & operator= (const Vector &other) noexcept
Copy assignment operator.
constexpr Vector & operator= (Vector &&other) noexcept
Move assignment operator.
template<typename OtherType >
constexpr bool operator== (const Vector< OtherType, N > &rhs) const
Equality operator for vectors.
constexpr bool operator> (const Vector &rhs) const
Greater than operator for vectors.
constexpr bool operator>= (const Vector &rhs) const
Greater than or equal to operator for vectors.
Type & operator[] (size_t index)
Returns the data of the vector given an index.
const Type & operator[] (size_t index) const
Returns the data of the vector given an index, const version (read only)
Vector project (const Vector &other) const
Projects the vector onto another vector.
Vector & reflect (const Vector &normal)
Reflects the vector by a given normal, modifying the current vector.
Vector reflect (const Vector &normal) const
Reflects the vector by a given normal.
Vector< Type, 3 > & rotate (const Vector< Type, 3 > &rotation)
Rotates the vector by a given rotation.
Vector< Type, 3 > rotate (const Vector< Type, 3 > &rotation) const
Rotates the vector by a given rotation.
void set (size_t index, Type value)
Sets the data of the vector given an index.
void setW (Type value)
Sets the w (fourth) value of the vector.
void setX (Type value)
Sets the x (first) value of the vector.
void setY (Type value)
Sets the y (second) value of the vector.
void setZ (Type value)
Sets the z (third) value of the vector.
int size () const
Returns the size of the vector.
Type sum () const
Returns the sum of all the elements in the vector.
void swap (Vector &other) noexcept
Swaps the data of this vector with another vector.
Vector toDegrees () const
Converts the vector to degrees.
MatrixData< Type, N, 1 > toMatrix () const
Converts the vector to a single column matrix.
Vector toRads () const
Converts the vector to radians.
std::string toString () const
Converts the vector to string.
Vector & vectorToEulerRotation (const Vector &up)
Converts the vector to euler angles.
Vector vectorToEulerRotation (const Vector &up) const
Converts the vector to euler angles.
Type & w ()
Returns the w (fourth) value of the vector.
void w (Type value)
Sets the w (fourth) value of the vector.
Type & x ()
Returns the x (reference) value of the vector.
void x (Type value)
Sets the x (first) value of the vector.
Type & y ()
Returns the y (second) value of the vector.
void y (Type value)
Sets the y (second) value of the vector.
Type & z ()
Returns the z (third) value of the vector.
void z (Type value)
Sets the z (third) value of the vector.
Additional Inherited Members
Public Types inherited from GLESC::Math::Vector< Type, N >
using ValueType = Type
Public Attributes inherited from GLESC::Math::Vector< Type, N >
VectorData< Type, N > data
Data of the vector.
Detailed Description
Color in RGBA values (x = [0] = R, y = [1] = G, z = [2] = B, w = [3] = A)
Will store colors in the range of 0 to 255
Has minimum overhead as only validates in debug mode.
Contains a set of static colors for convenience. Examples: ColorRgba::Red, ColorRgba::Green, etc.
Inherits from Vec4F to allow for easy conversion to Vec4F, as many functions expect Vec4F
Definition at line 316 of file RendererTypes.h.
Constructor & Destructor Documentation
ColorRgba() [1/6]
GLESC::Render::ColorRgba::ColorRgba () default
ColorRgba() [2/6]
GLESC::Render::ColorRgba::ColorRgba (const ColorRgba & other) default
ColorRgba() [3/6]
ColorRgba::ColorRgba (ColorRgb & other) noexcept
Definition at line 22 of file RendererTypes.cpp.
{
    this->setR(other.getR());
    this->setG(other.getG());
    this->setB(other.getB());
    this->setA(1.0f);
}
ColorRgba() [4/6]
ColorRgba::ColorRgba (const ColorRgb & other) noexcept
Definition at line 29 of file RendererTypes.cpp.
{
    this->setR(other.getR());
    this->setG(other.getG());
    this->setB(other.getB());
    this->setA(1.0f);
}
ColorRgba() [5/6]
GLESC::Render::ColorRgba::ColorRgba (ColorRgba && other) default noexcept
~ColorRgba()
GLESC::Render::ColorRgba::~ColorRgba () default
ColorRgba() [6/6]
GLESC::Render::ColorRgba::ColorRgba (float r, float g, float b, float a) inline
Definition at line 333 of file RendererTypes.h.
{
            data[0] = r;
            data[1] = g;
            data[2] = b;
            data[3] = a;
        }
References GLESC::Math::Vector< Type, N >::data.
Member Function Documentation
getA()
const float & GLESC::Render::ColorRgba::getA () const inline
Definition at line 352 of file RendererTypes.h.
{
            return data[3];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString(), and GLESC::HUD::CrosshairHUD::windowContent().
getAModifiable()
float & GLESC::Render::ColorRgba::getAModifiable () inline
Definition at line 389 of file RendererTypes.h.
{
            return data[3];
        }
References GLESC::Math::Vector< Type, N >::data.
getANormalized()
float GLESC::Render::ColorRgba::getANormalized () const inline
Definition at line 368 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[3]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBAVec4FNormalized().
getB()
const float & GLESC::Render::ColorRgba::getB () const inline
Definition at line 348 of file RendererTypes.h.
{
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString(), and GLESC::HUD::CrosshairHUD::windowContent().
getBModifiable()
float & GLESC::Render::ColorRgba::getBModifiable () inline
Definition at line 385 of file RendererTypes.h.
{
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data.
getBNormalized()
float GLESC::Render::ColorRgba::getBNormalized () const inline
Definition at line 364 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[2]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBAVec4FNormalized().
getG()
const float & GLESC::Render::ColorRgba::getG () const inline
Definition at line 344 of file RendererTypes.h.
{
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString(), and GLESC::HUD::CrosshairHUD::windowContent().
getGModifiable()
float & GLESC::Render::ColorRgba::getGModifiable () inline
Definition at line 381 of file RendererTypes.h.
{
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data.
getGNormalized()
float GLESC::Render::ColorRgba::getGNormalized () const inline
Definition at line 360 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[1]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBAVec4FNormalized().
getR()
const float & GLESC::Render::ColorRgba::getR () const inline
Definition at line 340 of file RendererTypes.h.
{
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString(), and GLESC::HUD::CrosshairHUD::windowContent().
getRGBAVec4FNormalized()
Vec4F GLESC::Render::ColorRgba::getRGBAVec4FNormalized () const inline
Definition at line 372 of file RendererTypes.h.
{
            return {getRNormalized(), getGNormalized(), getBNormalized(), getANormalized()};
        }
References getANormalized(), getBNormalized(), getGNormalized(), and getRNormalized().
getRModifiable()
float & GLESC::Render::ColorRgba::getRModifiable () inline
Definition at line 377 of file RendererTypes.h.
{
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data.
getRNormalized()
float GLESC::Render::ColorRgba::getRNormalized () const inline
Definition at line 356 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[0]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBAVec4FNormalized().
operator=() [1/2]
ColorRgba & GLESC::Render::ColorRgba::operator= (ColorRgba && other) default noexcept
operator=() [2/2]
ColorRgba & GLESC::Render::ColorRgba::operator= (const ColorRgba & other) default
setA()
void GLESC::Render::ColorRgba::setA (float aParam) inline
Definition at line 408 of file RendererTypes.h.
{
            ColorFuncs::checkValue(aParam, "A");
            data[3] = aParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
setB()
void GLESC::Render::ColorRgba::setB (float bParam) inline
Definition at line 403 of file RendererTypes.h.
{
            ColorFuncs::checkValue(bParam, "B");
            data[2] = bParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
setG()
void GLESC::Render::ColorRgba::setG (float gParam) inline
Definition at line 398 of file RendererTypes.h.
{
            ColorFuncs::checkValue(gParam, "G");
            data[1] = gParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
setR()
void GLESC::Render::ColorRgba::setR (float rParam) inline
Definition at line 393 of file RendererTypes.h.
{
            ColorFuncs::checkValue(rParam, "R");
            data[0] = rParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
toString()
std::string GLESC::Render::ColorRgba::toString () const inline
Definition at line 413 of file RendererTypes.h.
{
            return "R:" + Stringer::toString(getR()) + " G:" + Stringer::toString(getG()) + " B:" +
                Stringer::toString(getB()) + " A:" + Stringer::toString(getA());
        }
References getA(), getB(), getG(), getR(), and GLESC::Stringer::toString().
The documentation for this struct was generated from the following files:
RendererTypes.h
RendererTypes.cpp