GLESC: GLESC::Transform::Interpolator Struct Reference
GLESC::Transform::Interpolator Struct Reference
Class that contains functions for interpolating between two transforms.
#include <Transform.h>
Public Member Functions
Interpolator ()=default
Transform interpolate (float alphaParam) const
Interpolates between the current and the last transform.
void pushTransform (const Transform &transform)
Pushes a new transform to the interpolator.
Private Attributes
Transform currentTransform {}
Transform lastTransform {}
Detailed Description
Class that contains functions for interpolating between two transforms.
This allows interpolating between two transforms to get a smooth transition between two states. It contains two transforms, the current and the last one. Once there is two transforms, the next time you call interpolate, it will return a transform that is between the two.
Definition at line 448 of file Transform.h.
Constructor & Destructor Documentation
Interpolator()
GLESC::Transform::Interpolator::Interpolator () default
Member Function Documentation
interpolate()
Transform Interpolator::interpolate (float alphaParam) const
Interpolates between the current and the last transform.
Parameters
alphaParam The alpha value of the interpolation (alpha is a value between 0 and 1 and represents the percentage of the interpolation).
Returns
The interpolated transform.
Definition at line 167 of file Transform.cpp.
{
    // If rotation difference is more than 180 degrees, don't interpolate
    if (Math::abs(lastTransform.getRotation().getX() - currentTransform.getRotation().getX()) > 180.0f ||
        Math::abs(lastTransform.getRotation().getY() - currentTransform.getRotation().getY()) > 180.0f ||
        Math::abs(lastTransform.getRotation().getZ() - currentTransform.getRotation().getZ()) > 180.0f) {
        return currentTransform;
    }
    // Clamp alpha to [0, 1]
    float alpha = Math::min(alphaParam, 1.0f);
    Transform interpolatedTransform;
    interpolatedTransform.setPosition(
        lastTransform.getPosition().lerp(currentTransform.getPosition(), alpha));
    interpolatedTransform.setRotation(
        lastTransform.getRotation().lerp(currentTransform.getRotation(), alpha));
    interpolatedTransform.setScale(
        lastTransform.getScale().lerp(currentTransform.getScale(), alpha));
    return interpolatedTransform;
}
References GLESC::Math::abs(), currentTransform, GLESC::Transform::Transform::getPosition(), GLESC::Transform::Transform::getRotation(), GLESC::Transform::Transform::getScale(), GLESC::Math::Vector< Type, N >::getX(), GLESC::Math::Vector< Type, N >::getY(), GLESC::Math::Vector< Type, N >::getZ(), GLESC::isIterable_v, lastTransform, GLESC::Math::Vector< Type, N >::lerp(), GLESC::Math::min(), and GLESC::Transform::Transform::setPosition().
pushTransform()
void Interpolator::pushTransform (const Transform & transform)
Pushes a new transform to the interpolator.
Parameters
transform The transform to push.
Definition at line 156 of file Transform.cpp.
{
    // Check if the transform has changed significantly
    if (Math::abs(transform.getPosition().length() - lastTransform.getPosition().length()) > 100.f) {
        lastTransform = transform;
        currentTransform = transform;
    }
    lastTransform = currentTransform;
    currentTransform = transform;
}
References GLESC::Math::abs(), currentTransform, GLESC::Transform::Transform::getPosition(), lastTransform, and GLESC::Math::Vector< Type, N >::length().
Member Data Documentation
currentTransform
Transform GLESC::Transform::Interpolator::currentTransform {} private
Definition at line 464 of file Transform.h.
{};
Referenced by interpolate(), and pushTransform().
lastTransform
Transform GLESC::Transform::Interpolator::lastTransform {} private
Definition at line 465 of file Transform.h.
{};
Referenced by interpolate(), and pushTransform().
The documentation for this struct was generated from the following files:
Transform.h
Transform.cpp