GLESC: GLESC::ECS::PhysicsComponent Struct Reference
GLESC::ECS::PhysicsComponent Struct Reference
#include <PhysicsComponent.h>
Public Member Functions
std::string getName () const override
void setDebuggingValues () override
Set the debugging values of the component.
void setUpdatedDebuggingValues () override
Set the updated debugging values of the component.
std::string toString () const override
Each component must have a toString function.
Public Member Functions inherited from GLESC::ECS::IComponent
virtual ~IComponent ()=default
std::vector< EntityStatsManager::Value > & getDebuggingValues ()
Get the debugging values of the component.
std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues ()
Get the updated debugging values of the component.
Public Attributes
Transform::Transform oldTransform
Physics::Physics physics
Additional Inherited Members
Protected Attributes inherited from GLESC::ECS::IComponent
std::vector< EntityStatsManager::Value > updatedValues
The updated debugging values of the component.
std::vector< EntityStatsManager::Value > values
The debugging values of the component.
Detailed Description
Definition at line 20 of file PhysicsComponent.h.
Member Function Documentation
getName()
std::string GLESC::ECS::PhysicsComponent::getName () const inline override virtual
Implements GLESC::ECS::IComponent.
Definition at line 29 of file PhysicsComponent.h.
{
            return "PhysicsComponent";
        }
setDebuggingValues()
void GLESC::ECS::PhysicsComponent::setDebuggingValues () inline override virtual
Set the debugging values of the component.
This function must be implemented by the derived classes. This function is used to set the specific debugging values of the component.
Returns
The specifc debugging values of the component
Implements GLESC::ECS::IComponent.
Definition at line 38 of file PhysicsComponent.h.
{
            for (auto& value : physics.getDebuggingValues()) {
                values.push_back(value);
            }
        }
References GLESC::Physics::Physics::getDebuggingValues(), GLESC::isIterable_v, physics, and GLESC::ECS::IComponent::values.
setUpdatedDebuggingValues()
void GLESC::ECS::PhysicsComponent::setUpdatedDebuggingValues () inline override virtual
Set the updated debugging values of the component.
This function can be implemented by the derived classes, but not always necessary. This function is used to set the specific updated debugging values of the component.
Returns
The specifc updated debugging values of the component
Reimplemented from GLESC::ECS::IComponent.
Definition at line 44 of file PhysicsComponent.h.
{
            for (auto& value : physics.getUpdatedDebuggingValues()) {
                updatedValues.push_back(value);
            }
        }
References EngineComponent::getUpdatedDebuggingValues(), GLESC::isIterable_v, physics, and GLESC::ECS::IComponent::updatedValues.
toString()
std::string GLESC::ECS::PhysicsComponent::toString () const inline override virtual
Each component must have a toString function.
This is needed because when we want to debug the content of the components, we need to be able to do it without knowing the specific type of the component. This is because we are using a vector of IComponents.
Returns
Implements GLESC::ECS::IComponent.
Definition at line 33 of file PhysicsComponent.h.
{
            return physics.toString();
        }
References physics, and GLESC::Physics::Physics::toString().
Member Data Documentation
oldTransform
Transform::Transform GLESC::ECS::PhysicsComponent::oldTransform
This transform is the old transform before applying the physics It can be used to change the behavior of the physics (such as collisions)
Definition at line 26 of file PhysicsComponent.h.
physics
Physics::Physics GLESC::ECS::PhysicsComponent::physics
Definition at line 21 of file PhysicsComponent.h.
Referenced by setDebuggingValues(), setUpdatedDebuggingValues(), and toString().
The documentation for this struct was generated from the following file:
PhysicsComponent.h