GLESC: GLESC::Render::LightPoint Struct Reference
GLESC::Render::LightPoint Struct Reference
#include <LightPoint.h>
Public Member Functions
LightPoint ()=default
const ColorRgb & getColor () const
std::vector< EntityStatsManager::Value > getDebuggingValues ()
float getIntensity () const
float getRadius () const
bool & isDirty () const
void setClean () const
void setColor (const ColorRgb &colorParam)
void setIntensity (float intensityParam)
void setRadius (float radiusParam)
std::string toString () const
Private Attributes
ColorRgb color {255.f, 255.f, 255.f}
bool dirty {true}
Intensity< float > intensity {1.0f}
float radius {10.0f}
Detailed Description
Definition at line 17 of file LightPoint.h.
Constructor & Destructor Documentation
LightPoint()
GLESC::Render::LightPoint::LightPoint () default
Member Function Documentation
getColor()
const ColorRgb & GLESC::Render::LightPoint::getColor () const inline
Definition at line 38 of file LightPoint.h.
{ return color; }
References color.
Referenced by GLESC::Render::Renderer::renderLights().
getDebuggingValues()
std::vector< EntityStatsManager::Value > GLESC::Render::LightPoint::getDebuggingValues ()
Definition at line 12 of file LightPoint.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value intensityValue;
    intensityValue.name = "Intensity";
    intensityValue.data = reinterpret_cast<void*>(&intensity.getModifiable());
    intensityValue.type = EntityStatsManager::ValueType::FLOAT;
    intensityValue.isModifiable = true;
    intensityValue.valueDirty = &dirty;
    intensityValue.usesSlider = true;
    values.push_back(intensityValue);
    EntityStatsManager::Value colorValue;
    colorValue.name = "Color";
    colorValue.data = reinterpret_cast<void*>(&color);
    colorValue.type = EntityStatsManager::ValueType::VEC3F;
    colorValue.isModifiable = true;
    colorValue.valueDirty = &dirty;
    colorValue.usesSlider = true;
    colorValue.min = 0.0f;
    colorValue.max = 255.0f;
    values.push_back(colorValue);
    EntityStatsManager::Value radiusValue;
    radiusValue.name = "Radius";
    radiusValue.data = reinterpret_cast<void*>(&radius);
    radiusValue.type = EntityStatsManager::ValueType::FLOAT;
    radiusValue.isModifiable = true;
    radiusValue.valueDirty = &dirty;
    radiusValue.usesSlider = true;
    radiusValue.min = 0.0f;
    radiusValue.max = 100.0f;
    values.push_back(radiusValue);
    return values;
}
References color, dirty, EntityStatsManager::FLOAT, GLESC::Render::Intensity< IntensityType >::getModifiable(), intensity, GLESC::isIterable_v, EntityStatsManager::Value::name, radius, and EntityStatsManager::VEC3F.
Referenced by GLESC::ECS::LightComponent::setDebuggingValues().
getIntensity()
float GLESC::Render::LightPoint::getIntensity () const inline
Definition at line 37 of file LightPoint.h.
{ return intensity.get(); }
References GLESC::Render::Intensity< IntensityType >::get(), and intensity.
Referenced by GLESC::Render::Renderer::renderLights().
getRadius()
float GLESC::Render::LightPoint::getRadius () const inline
Definition at line 39 of file LightPoint.h.
{ return radius; }
References radius.
Referenced by GLESC::Render::Renderer::renderLights().
isDirty()
bool & GLESC::Render::LightPoint::isDirty () const inline
Definition at line 42 of file LightPoint.h.
{ return dirty; }
References dirty.
Referenced by GLESC::Render::Renderer::renderLights().
setClean()
void GLESC::Render::LightPoint::setClean () const inline
Definition at line 43 of file LightPoint.h.
{ dirty = false; }
References dirty.
Referenced by GLESC::Render::Renderer::renderLights().
setColor()
void GLESC::Render::LightPoint::setColor (const ColorRgb & colorParam) inline
Definition at line 31 of file LightPoint.h.
{
            color = colorParam;
            dirty = true;
        }
References color, dirty, and GLESC::isIterable_v.
setIntensity()
void GLESC::Render::LightPoint::setIntensity (float intensityParam) inline
Definition at line 26 of file LightPoint.h.
{
            intensity.set(intensityParam);
            dirty = true;
        }
References dirty, intensity, GLESC::isIterable_v, and GLESC::Render::Intensity< IntensityType >::set().
setRadius()
void GLESC::Render::LightPoint::setRadius (float radiusParam) inline
Definition at line 21 of file LightPoint.h.
{
            radius = radiusParam;
            dirty = true;
        }
References dirty, GLESC::isIterable_v, and radius.
toString()
std::string GLESC::Render::LightPoint::toString () const
Definition at line 53 of file LightPoint.cpp.
{
    return "Intensity:" + intensity.toString() +
        " Color:" + color.toString() +
        " Radius:" + std::to_string(radius);
}
Referenced by GLESC::ECS::LightComponent::toString().
Member Data Documentation
color
ColorRgb GLESC::Render::LightPoint::color {255.f, 255.f, 255.f} private
Definition at line 50 of file LightPoint.h.
{255.f, 255.f, 255.f};
Referenced by getColor(), getDebuggingValues(), and setColor().
dirty
bool GLESC::Render::LightPoint::dirty {true} mutable private
Definition at line 52 of file LightPoint.h.
{true};
Referenced by getDebuggingValues(), isDirty(), setClean(), setColor(), setIntensity(), and setRadius().
intensity
Intensity<float> GLESC::Render::LightPoint::intensity {1.0f} private
Definition at line 49 of file LightPoint.h.
{1.0f};
Referenced by getDebuggingValues(), getIntensity(), and setIntensity().
radius
float GLESC::Render::LightPoint::radius {10.0f} private
Definition at line 51 of file LightPoint.h.
{10.0f};
Referenced by getDebuggingValues(), getRadius(), and setRadius().
The documentation for this struct was generated from the following files:
LightPoint.h
LightPoint.cpp