GLESC: GLESC::Render::ColorRgb Struct Reference
GLESC::Render::ColorRgb Struct Reference
Color in RGB values.
#include <RendererTypes.h>
Public Member Functions
ColorRgb ()=default
ColorRgb (ColorRgb &&other) noexcept=default
ColorRgb (ColorRgba &other) noexcept
ColorRgb (const ColorRgb &other)=default
ColorRgb (const ColorRgba &other) noexcept
ColorRgb (float r, float g, float b)
~ColorRgb ()=default
const float & getB () const
float getBNormalized () const
const float & getG () const
float getGNormalized () const
const float & getR () const
Vec3F getRGBVec3FNormalized () const
float getRNormalized () const
ColorRgb & operator= (ColorRgb &&other) noexcept=default
ColorRgb & operator= (const ColorRgb &other)=default
void setB (float bParam)
void setG (float gParam)
void setR (float rParam)
std::string toString () const
Public Member Functions inherited from GLESC::Math::Vector< Type, N >
constexpr Vector () noexcept
Default constructor.
template<typename... Args, typename = std::enable_if_t<(sizeof...(Args) == N)>>
constexpr Vector (Args &&... args) noexcept
Variadic constructor.
constexpr Vector (const Type(&list)[N]) noexcept
Array constructor.
constexpr Vector (const Vector &other) noexcept
Copy constructor.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &&other) noexcept
Move constructor, for vectors of different sizes.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &other) noexcept
Copy constructor.
constexpr Vector (const VectorData< Type, N > &values) noexcept
Copy constructor for VectorData.
constexpr Vector (Type values) noexcept
Fill constructor.
constexpr Vector (Vector &&other) noexcept
Move constructor.
constexpr Vector (VectorData< Type, N > &&values) noexcept
Move constructor for VectorData.
Vector abs () const noexcept
Returns the absolute value of the vector.
Type angle (const Vector &other) const
Gives the rads between two vectors.
Type angleDegrees (const Vector &other) const
Gives the angle between two vectors in degrees.
Vector clamp (const Vector &min, const Vector &max) const
Clamps the vector to a given range.
Vector clamp (Type min, Type max) const
Clamps the vector to a given range.
Vector< Type, 3 > cross (const Vector< Type, 3 > &other) const
Calculates the cross product of two vectors.
Vector< Type, N - 1 > dehomogenize () const
Dehomogenizes the vector.
Type distance (const Vector &other) const
Gives the distance between two vectors.
Type distanceSquared (const Vector &other) const
Gives the squared distance between two vectors.
Type dot (const Vector &rhs) const
Returns the dot product of two vectors.
const Type & get (size_t index) const
Returns the data of the vector given an index.
Vector getOrthogonal () const
Get an orthogonal (or perpendicular) vector.
Type getW () const
Returns the w (fourth) value of the vector.
const Type & getX () const
Returns the x (first) value of the vector.
Type getY () const
Returns the y (second) value of the vector.
Type getZ () const
Returns the z (third) value of the vector.
Vector< Type, N+1 > homogenize () const
Homogenizes the vector.
bool isCollinear (const std::vector< Vector< Type, 3 > > &points) const
Checks if the current vector is a scalar multiple of some vectors.
Type isHomogeneous () const
Checks if the vector is homogeneous.
bool isMultipleOf (const Vector &other) const
Checks if the current vector is a scalar multiple of another vector.
bool isNormalized () const
checks if the vector is normalized
bool isOrthogonal (const Vector &other) const
Checks if the vector is orthogonal to another vector.
bool isParallel (const Vector &other) const
Checks if the vector is parallel to another vector.
bool isZero () const
Checks if the vector is a zero vector.
Type length () const
Returns the length of the vector.
Type lengthSquared () const
Returns the squared length of the vector.
Vector lerp (const Vector &other, Type factor) const
Calculates the linear interpolation between two vectors using a factor.
Type magnitude () const
Returns the length of the vector.
Vector & makeForward (const Vector &rotation)
Returs the forward vector of a rotation.
Vector & makeRight (const Vector &rotation)
Returns the right vector of a rotation.
Vector & makeUp (const Vector &rotation)
Returns the up vector of a rotation.
Vector mod (Type divisor) const
Returns the mod of the vector given a divisor.
Vector mod (Vector divisors) const
Returns the mod of the vector given a vector of divisors.
Vector & normalize ()
Normalizes the vector.
Vector normalize () const
Normalizes the vector.
constexpr bool operator!= (const Vector &rhs) const
Inequality operator for vectors.
constexpr Vector operator* (const Vector &rhs) const
Overloads the '*' operator for vector multiplication.
constexpr Vector operator* (Type scalar) const
Overloads the '*' operator for scalar multiplication.
constexpr Vector operator*= (const Type scalar)
In-place multiplication with a scalar.
constexpr Vector operator*= (const Vector &rhs)
In-place multiplication with another vector.
constexpr Vector operator+ (const Type &scalar) const
Overloads the '+' operator for scalar addition.
constexpr Vector operator+ (const Vector &rhs) const
Overloads the '+' operator for vector addition.
constexpr Vector operator+= (const Vector &rhs)
In-place addition with another vector.
constexpr Vector operator+= (Type scalar)
In-place addition with a scalar.
constexpr Vector operator- () const
Overloads the unary '-' operator for negation.
constexpr Vector operator- (const Type &scalar) const
Overloads the '-' operator for scalar subtraction.
constexpr Vector operator- (const Vector &rhs) const
Overloads the '-' operator for vector subtraction.
constexpr Vector operator-= (const Type scalar)
In-place subtraction with a scalar.
constexpr Vector operator-= (const Vector &rhs)
In-place subtraction with another vector.
constexpr Vector operator/ (const Vector &rhs) const
Overloads the '/' operator for vector division.
constexpr Vector operator/ (Type scalar) const
Overloads the '/' operator for scalar division.
constexpr Vector operator/= (const Type scalar)
In-place division with a scalar.
constexpr Vector operator/= (const Vector &rhs)
In-place division with another vector.
constexpr bool operator< (const Vector &rhs) const
Less than operator for vectors.
constexpr bool operator<= (const Vector &rhs) const
Less than or equal to operator for vectors.
constexpr Vector & operator= (const Type(&list)[N]) noexcept
Array assignment operator.
constexpr Vector & operator= (const Vector &other) noexcept
Copy assignment operator.
constexpr Vector & operator= (Vector &&other) noexcept
Move assignment operator.
template<typename OtherType >
constexpr bool operator== (const Vector< OtherType, N > &rhs) const
Equality operator for vectors.
constexpr bool operator> (const Vector &rhs) const
Greater than operator for vectors.
constexpr bool operator>= (const Vector &rhs) const
Greater than or equal to operator for vectors.
Type & operator[] (size_t index)
Returns the data of the vector given an index.
const Type & operator[] (size_t index) const
Returns the data of the vector given an index, const version (read only)
Vector project (const Vector &other) const
Projects the vector onto another vector.
Vector & reflect (const Vector &normal)
Reflects the vector by a given normal, modifying the current vector.
Vector reflect (const Vector &normal) const
Reflects the vector by a given normal.
Vector< Type, 3 > & rotate (const Vector< Type, 3 > &rotation)
Rotates the vector by a given rotation.
Vector< Type, 3 > rotate (const Vector< Type, 3 > &rotation) const
Rotates the vector by a given rotation.
void set (size_t index, Type value)
Sets the data of the vector given an index.
void setW (Type value)
Sets the w (fourth) value of the vector.
void setX (Type value)
Sets the x (first) value of the vector.
void setY (Type value)
Sets the y (second) value of the vector.
void setZ (Type value)
Sets the z (third) value of the vector.
int size () const
Returns the size of the vector.
Type sum () const
Returns the sum of all the elements in the vector.
void swap (Vector &other) noexcept
Swaps the data of this vector with another vector.
Vector toDegrees () const
Converts the vector to degrees.
MatrixData< Type, N, 1 > toMatrix () const
Converts the vector to a single column matrix.
Vector toRads () const
Converts the vector to radians.
std::string toString () const
Converts the vector to string.
Vector & vectorToEulerRotation (const Vector &up)
Converts the vector to euler angles.
Vector vectorToEulerRotation (const Vector &up) const
Converts the vector to euler angles.
Type & w ()
Returns the w (fourth) value of the vector.
void w (Type value)
Sets the w (fourth) value of the vector.
Type & x ()
Returns the x (reference) value of the vector.
void x (Type value)
Sets the x (first) value of the vector.
Type & y ()
Returns the y (second) value of the vector.
void y (Type value)
Sets the y (second) value of the vector.
Type & z ()
Returns the z (third) value of the vector.
void z (Type value)
Sets the z (third) value of the vector.
Static Public Attributes
static const ColorRgb Black = ColorRgb(40.0f, 40.0f, 40.0f)
static const ColorRgb Blue = ColorRgb(30.0f, 144.0f, 255.0f)
static const ColorRgb Brown = ColorRgb(210.0f, 105.0f, 30.0f)
static const ColorRgb ClearSkin = ColorRgb(255.0f, 224.0f, 189.0f)
static const ColorRgb Cyan = ColorRgb(0.0f, 255.0f, 255.0f)
static const ColorRgb DarkBrown = ColorRgb(139.0f, 69.0f, 19.0f)
static const ColorRgb DarkGreen = ColorRgb(34.0f, 139.0f, 34.0f)
static const ColorRgb DarkGrey = ColorRgb(105.0f, 105.0f, 105.0f)
static const ColorRgb Green = ColorRgb(60.0f, 179.0f, 113.0f)
static const ColorRgb Grey = ColorRgb(169.0f, 169.0f, 169.0f)
static const ColorRgb LightGrey = ColorRgb(211.0f, 211.0f, 211.0f)
static const ColorRgb Magenta = ColorRgb(255.0f, 0.0f, 255.0f)
static const ColorRgb Orange = ColorRgb(255.0f, 165.0f, 0.0f)
static const ColorRgb Pink = ColorRgb(255.0f, 105.0f, 180.0f)
static const ColorRgb Purple = ColorRgb(138.0f, 43.0f, 226.0f)
static const ColorRgb Red = ColorRgb(220.0f, 20.0f, 60.0f)
static const ColorRgb White = ColorRgb(255.0f, 250.0f, 240.0f)
static const ColorRgb Yellow = ColorRgb(255.0f, 215.0f, 0.0f)
Additional Inherited Members
Public Types inherited from GLESC::Math::Vector< Type, N >
using ValueType = Type
Public Attributes inherited from GLESC::Math::Vector< Type, N >
VectorData< Type, N > data
Data of the vector.
Detailed Description
Color in RGB values.
Will store colors in the range of 0 to 255
Has minimum overhead as only validates in debug mode.
Contains a set of static colors for convenience. Examples: ColorRgb::Red, ColorRgb::Green, etc.
Inherits from Vec3F to allow for easy conversion to Vec3F, as many functions expect Vec3F
Definition at line 214 of file RendererTypes.h.
Constructor & Destructor Documentation
ColorRgb() [1/6]
GLESC::Render::ColorRgb::ColorRgb () default
ColorRgb() [2/6]
GLESC::Render::ColorRgb::ColorRgb (const ColorRgb & other) default
ColorRgb() [3/6]
ColorRgb::ColorRgb (ColorRgba & other) explicit noexcept
Definition at line 8 of file RendererTypes.cpp.
{
    this->setR(other.getR());
    this->setG(other.getG());
    this->setB(other.getB());
}
ColorRgb() [4/6]
ColorRgb::ColorRgb (const ColorRgba & other) explicit noexcept
Definition at line 3 of file RendererTypes.cpp.
{
    this->setR(other.getR());
    this->setG(other.getG());
    this->setB(other.getB());
}
ColorRgb() [5/6]
GLESC::Render::ColorRgb::ColorRgb (ColorRgb && other) default noexcept
~ColorRgb()
GLESC::Render::ColorRgb::~ColorRgb () default
ColorRgb() [6/6]
GLESC::Render::ColorRgb::ColorRgb (float r, float g, float b) inline
Definition at line 251 of file RendererTypes.h.
{
            data[0] = r;
            data[1] = g;
            data[2] = b;
        }
References GLESC::Math::Vector< Type, N >::data.
Member Function Documentation
getB()
const float & GLESC::Render::ColorRgb::getB () const inline
Definition at line 266 of file RendererTypes.h.
{
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
getBNormalized()
float GLESC::Render::ColorRgb::getBNormalized () const inline
Definition at line 278 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[2]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBVec3FNormalized().
getG()
const float & GLESC::Render::ColorRgb::getG () const inline
Definition at line 262 of file RendererTypes.h.
{
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
getGNormalized()
float GLESC::Render::ColorRgb::getGNormalized () const inline
Definition at line 274 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[1]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBVec3FNormalized().
getR()
const float & GLESC::Render::ColorRgb::getR () const inline
Definition at line 258 of file RendererTypes.h.
{
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
getRGBVec3FNormalized()
Vec3F GLESC::Render::ColorRgb::getRGBVec3FNormalized () const inline
Definition at line 297 of file RendererTypes.h.
{
            return {getRNormalized(), getGNormalized(), getBNormalized()};
        }
References getBNormalized(), getGNormalized(), and getRNormalized().
Referenced by GLESC::Render::Renderer::applyAmbientLight(), GLESC::Render::Renderer::applyMaterial(), and GLESC::Render::Renderer::renderLights().
getRNormalized()
float GLESC::Render::ColorRgb::getRNormalized () const inline
Definition at line 270 of file RendererTypes.h.
{
            return ColorFuncs::normalizeColorValue(data[0]);
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::Render::ColorFuncs::normalizeColorValue().
Referenced by getRGBVec3FNormalized().
operator=() [1/2]
ColorRgb & GLESC::Render::ColorRgb::operator= (ColorRgb && other) default noexcept
operator=() [2/2]
ColorRgb & GLESC::Render::ColorRgb::operator= (const ColorRgb & other) default
setB()
void GLESC::Render::ColorRgb::setB (float bParam) inline
Definition at line 292 of file RendererTypes.h.
{
            ColorFuncs::checkValue(bParam, "B");
            data[2] = bParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
setG()
void GLESC::Render::ColorRgb::setG (float gParam) inline
Definition at line 287 of file RendererTypes.h.
{
            ColorFuncs::checkValue(gParam, "G");
            data[1] = gParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
setR()
void GLESC::Render::ColorRgb::setR (float rParam) inline
Definition at line 282 of file RendererTypes.h.
{
            ColorFuncs::checkValue(rParam, "R");
            data[0] = rParam;
        }
References GLESC::Render::ColorFuncs::checkValue(), GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
toString()
std::string GLESC::Render::ColorRgb::toString () const inline
Definition at line 301 of file RendererTypes.h.
{
            return "R:" + Stringer::toString(getR()) + " G:" + Stringer::toString(getG()) + " B:" +
                Stringer::toString(getB());
        }
References getB(), getG(), getR(), and GLESC::Stringer::toString().
Referenced by GLESC::Render::Fog::toString().
Member Data Documentation
Black
const ColorRgb ColorRgb::Black = ColorRgb(40.0f, 40.0f, 40.0f) static
Definition at line 220 of file RendererTypes.h.
Blue
const ColorRgb ColorRgb::Blue = ColorRgb(30.0f, 144.0f, 255.0f) static
Definition at line 218 of file RendererTypes.h.
Brown
const ColorRgb ColorRgb::Brown = ColorRgb(210.0f, 105.0f, 30.0f) static
Definition at line 227 of file RendererTypes.h.
ClearSkin
const ColorRgb ColorRgb::ClearSkin = ColorRgb(255.0f, 224.0f, 189.0f) static
Definition at line 232 of file RendererTypes.h.
Cyan
const ColorRgb ColorRgb::Cyan = ColorRgb(0.0f, 255.0f, 255.0f) static
Definition at line 222 of file RendererTypes.h.
DarkBrown
const ColorRgb ColorRgb::DarkBrown = ColorRgb(139.0f, 69.0f, 19.0f) static
Definition at line 228 of file RendererTypes.h.
DarkGreen
const ColorRgb ColorRgb::DarkGreen = ColorRgb(34.0f, 139.0f, 34.0f) static
Definition at line 217 of file RendererTypes.h.
DarkGrey
const ColorRgb ColorRgb::DarkGrey = ColorRgb(105.0f, 105.0f, 105.0f) static
Definition at line 231 of file RendererTypes.h.
Green
const ColorRgb ColorRgb::Green = ColorRgb(60.0f, 179.0f, 113.0f) static
Definition at line 216 of file RendererTypes.h.
Grey
const ColorRgb ColorRgb::Grey = ColorRgb(169.0f, 169.0f, 169.0f) static
Definition at line 229 of file RendererTypes.h.
LightGrey
const ColorRgb ColorRgb::LightGrey = ColorRgb(211.0f, 211.0f, 211.0f) static
Definition at line 230 of file RendererTypes.h.
Magenta
const ColorRgb ColorRgb::Magenta = ColorRgb(255.0f, 0.0f, 255.0f) static
Definition at line 223 of file RendererTypes.h.
Orange
const ColorRgb ColorRgb::Orange = ColorRgb(255.0f, 165.0f, 0.0f) static
Definition at line 224 of file RendererTypes.h.
Pink
const ColorRgb ColorRgb::Pink = ColorRgb(255.0f, 105.0f, 180.0f) static
Definition at line 226 of file RendererTypes.h.
Purple
const ColorRgb ColorRgb::Purple = ColorRgb(138.0f, 43.0f, 226.0f) static
Definition at line 225 of file RendererTypes.h.
Red
const ColorRgb ColorRgb::Red = ColorRgb(220.0f, 20.0f, 60.0f) static
Definition at line 215 of file RendererTypes.h.
White
const ColorRgb ColorRgb::White = ColorRgb(255.0f, 250.0f, 240.0f) static
Definition at line 219 of file RendererTypes.h.
Yellow
const ColorRgb ColorRgb::Yellow = ColorRgb(255.0f, 215.0f, 0.0f) static
Definition at line 221 of file RendererTypes.h.
The documentation for this struct was generated from the following files:
RendererTypes.h
RendererTypes.cpp