GLESC: GLESC::Transform::Transform Struct Reference
GLESC::Transform::Transform Struct Reference
Struct that represents the position, rotation, and scale of an entity in the game world.
#include <Transform.h>
Public Member Functions
Transform ()
Transform (Position position, Rotation rotation, Scale scale)
Constructor that initializes the transform with the given position, rotation, and scale.
void addPosition (Axis axis, PosComp value)
Adds a position to the current position at the given axis.
void addPosition (const Position &position)
Adds a position to the current position.
void addRotation (const Rotation &rotation)
Adds a rotation to the current rotation.
void addRotation (RotationAxis axis, RotComp value)
Adds a rotation to the current rotation.
void addScale (Axis axis, ScaleComp value)
Adds a scale to the current scale.
void addScale (const Scale &scale)
Adds a scale to the current scale.
Math::Direction forward () const
Calculates the forward vector using the rotation.
std::vector< EntityStatsManager::Value > getDebuggingValues () override
Get the debugging values of the component.
Render::Model getModelMatrix () const
Returns the model matrix of the transform.
const Position & getPosition () const
const Rotation & getRotation () const
Render::RotateMat getRotationMatrix () const
Returns the rotation matrix of the transform.
const Scale & getScale () const
Render::ScaleMat getScaleMatrix () const
Returns the scale matrix of the transform.
Render::TranslateMat getTranslationMatrix () const
Returns the translation matrix of the transform.
bool operator== (const Transform &other) const
Compares two transforms for equality.
Math::Direction right () const
Calculates the right vector using the rotation.
void setPosition (Axis axis, PosComp value)
void setPosition (const Position &position)
void setRotation (const Rotation &rotation)
void setRotation (RotationAxis axis, RotComp value)
void setScale (Axis axis, ScaleComp value)
void setScale (const Scale &scale)
std::string toString () const override
Converts the transform to a string.
Math::Direction up () const
Calculates the up vector using the rotation.
Public Member Functions inherited from EngineComponent
virtual ~EngineComponent ()=default
const char * getOwnerName () const
Get the owner name of the component for debugging purposes.
virtual std::vector< EntityStatsManager::Value > getUpdatedDebuggingValues ()
Get the updated debugging values of the component.
void setOwnerName (const char *ownerName)
Set the owner name of the component for debugging purposes.
Static Public Attributes
static Math::Direction worldForward {Math::Direction(0.0f, 0.0f, 1.0f)}
static Math::Direction worldRight {Math::Direction(1.0f, 0.0f, 0.0f)}
static Math::Direction worldUp {Math::Direction(0.0f, 1.0f, 0.0f)}
Private Member Functions
Math::Direction calculateForward () const
Calculates the forward vector using the rotation.
Math::Direction calculateRight () const
Calculates the right vector using the rotation.
Math::Direction calculateUp () const
Calculates the up vector using the rotation.
Private Attributes
bool dirty = true
Math::Direction forwardDirection
The forward direction of the transform so we don't have to recalculate it every time.
bool modelDirty = true
Render::Model modelMat
The model matrix of the transform.
Position position = Position(0.0f, 0.0f, 0.0f)
The position of the transform.
Math::Direction rightDirection
The right direction of the transform so we don't have to recalculate it every time.
bool rotateDirty = true
Render::RotateMat rotateMat
The rotation matrix of the transform.
Rotation rotationDegrees = Rotation(0.0f, 0.0f, 0.0f)
The rotation of the transform.
Scale scale = Scale(1.0f, 1.0f, 1.0f)
The scale of the transform.
bool scaleDirty = true
Render::ScaleMat scaleMat
The scale matrix of the transform.
bool translateDirty = true
Render::TranslateMat translateMat
The translation matrix of the transform.
Math::Direction upDirection
The up direction of the transform so we don't have to recalculate it every time.
Detailed Description
Struct that represents the position, rotation, and scale of an entity in the game world.
This is the component of Transform, and allows the entity to exist in the game world.
Definition at line 45 of file Transform.h.
Constructor & Destructor Documentation
Transform() [1/2]
GLESC::Transform::Transform::Transform () inline
Definition at line 50 of file Transform.h.
                    {
            modelMat.makeModelMatrix(position, rotationDegrees.toRads(), scale);
        }
References GLESC::Math::Matrix< Type, N, M >::makeModelMatrix(), modelMat, position, rotationDegrees, scale, and GLESC::Math::Vector< Type, N >::toRads().
Transform() [2/2]
Transform::Transform (Position position, Rotation rotation, Scale scale)
Constructor that initializes the transform with the given position, rotation, and scale.
Parameters
position The position of the transform.
rotation The rotation of the transform.
scale The scale of the transform.
Definition at line 18 of file Transform.cpp.
                                                                      :
    position(std::move(position)),
    rotationDegrees(std::move(rotation)),
    scale(std::move(scale)) {
}
Member Function Documentation
addPosition() [1/2]
void GLESC::Transform::Transform::addPosition (Axis axis, PosComp value) inline
Adds a position to the current position at the given axis.
This facilitates adding positions at a given axis, without it it would look like this setPosition(getPosition() + Position(0.0f, 0.0f, value)); which is not very readable and is very verbose.
Parameters
axis The axis to add the position to.
value The value to add.
Definition at line 148 of file Transform.h.
{
            setPosition(axis, position.get(static_cast<int>(axis)) + value);
        }
References GLESC::Math::Vector< Type, N >::get(), GLESC::isIterable_v, position, and setPosition().
addPosition() [2/2]
void GLESC::Transform::Transform::addPosition (const Position & position) inline
Adds a position to the current position.
This facilitates adding positions. Without it adding would look like setPosition(getPosition() + position); which is not very readable. And addition is a very common operation.
Parameters
position The position to add.
Definition at line 114 of file Transform.h.
{
            setPosition(this->position + position);
        }
References position, and setPosition().
Referenced by GLESC::Physics::PhysicsManager::updateTransform().
addRotation() [1/2]
void GLESC::Transform::Transform::addRotation (const Rotation & rotation) inline
Adds a rotation to the current rotation.
This facilitates adding rotations. Without it adding would look like setRotation(getRotation() + rotation); which is not very readable. And addition is a very common operation.
Parameters
rotation The rotation to add.
Definition at line 125 of file Transform.h.
{
            setRotation(this->rotationDegrees + rotation);
        }
References rotationDegrees, and setRotation().
addRotation() [2/2]
void GLESC::Transform::Transform::addRotation (RotationAxis axis, RotComp value) inline
Adds a rotation to the current rotation.
This facilitates adding rotations at a given axis, without it it would look like this setRotation(getRotation() + Rotation(0.0f, 0.0f, value)); which is not very readable and is very verbose.
Parameters
axis The axis to add the rotation to. Rotation axis: RotationAxis::Pitch - x rotation RotationAxis::Yaw - y rotation RotationAxis::Roll - z rotation
value The value to add.
Definition at line 164 of file Transform.h.
{
            setRotation(axis, rotationDegrees.get(static_cast<int>(axis)) + value);
        }
References GLESC::Math::Vector< Type, N >::get(), GLESC::isIterable_v, rotationDegrees, and setRotation().
addScale() [1/2]
void GLESC::Transform::Transform::addScale (Axis axis, ScaleComp value) inline
Adds a scale to the current scale.
This facilitates adding scales at a given axis, without it it would look like this setScale(getScale() + Scale(0.0f, 0.0f, value)); which is not very readable and is very verbose.
Parameters
axis The axis to add the scale to.
value The value to add.
Definition at line 176 of file Transform.h.
{
            setScale(axis, scale.get(static_cast<int>(axis)) + value);
        }
References GLESC::Math::Vector< Type, N >::get(), GLESC::isIterable_v, scale, and setScale().
addScale() [2/2]
void GLESC::Transform::Transform::addScale (const Scale & scale) inline
Adds a scale to the current scale.
This facilitates adding scales. Without it adding would look like setScale(getScale() + scale); which is not very readable. And addition is a very common operation.
Parameters
scale The scale to add.
Definition at line 136 of file Transform.h.
{
            setScale(this->scale + scale);
        }
References scale, and setScale().
calculateForward()
GLESC::Math::Direction Transform::calculateForward () const private
Calculates the forward vector using the rotation.
This is a helper function for the forward function.
Returns
The forward vector.
Definition at line 43 of file Transform.cpp.
{
    return GLESC::Math::Direction().makeForward(rotationDegrees.toRads());
}
References GLESC::Math::Vector< Type, N >::makeForward(), rotationDegrees, and GLESC::Math::Vector< Type, N >::toRads().
Referenced by forward().
calculateRight()
GLESC::Math::Direction Transform::calculateRight () const private
Calculates the right vector using the rotation.
This is a helper function for the right function.
Returns
The right vector.
Definition at line 47 of file Transform.cpp.
{
    return GLESC::Math::Direction().makeRight(rotationDegrees.toRads());
}
References GLESC::Math::Vector< Type, N >::makeRight(), rotationDegrees, and GLESC::Math::Vector< Type, N >::toRads().
Referenced by right().
calculateUp()
GLESC::Math::Direction Transform::calculateUp () const private
Calculates the up vector using the rotation.
This is a helper function for the up function.
Returns
The up vector.
Definition at line 51 of file Transform.cpp.
{
    return GLESC::Math::Direction().makeUp(rotationDegrees.toRads());
}
References GLESC::Math::Vector< Type, N >::makeUp(), rotationDegrees, and GLESC::Math::Vector< Type, N >::toRads().
Referenced by up().
forward()
GLESC::Math::Direction Transform::forward () const
Calculates the forward vector using the rotation.
Returns
The forward vector
Definition at line 25 of file Transform.cpp.
{
    if (dirty)
        return calculateForward();
    return forwardDirection;
}
References calculateForward(), dirty, and forwardDirection.
Referenced by GLESC::EngineCamera::moveBackward(), and GLESC::EngineCamera::moveForward().
getDebuggingValues()
std::vector< EntityStatsManager::Value > Transform::getDebuggingValues () override virtual
Get the debugging values of the component.
This function can be overriden by the derived class to return the debugging values of the component It starts as an empty vector, so that the components that accumulates all the debugging values can add the debugging values of the component even if the component does not have any debugging values (adding an empty array)
Returns
A vector of debugging values
Reimplemented from EngineComponent.
Definition at line 187 of file Transform.cpp.
{
    std::vector<EntityStatsManager::Value> values;
    EntityStatsManager::Value positionValue;
    positionValue.name = "Position";
    positionValue.data = reinterpret_cast<void*>(&position);
    positionValue.valueDirty = &dirty;
    positionValue.type = EntityStatsManager::ValueType::VEC3F;
    positionValue.isModifiable = true;
    positionValue.usesSlider = false;
    values.push_back(positionValue);
    EntityStatsManager::Value rotationValue;
    rotationValue.name = "Rotation";
    rotationValue.data = reinterpret_cast<void*>(&rotationDegrees);
    positionValue.valueDirty = &dirty;
    rotationValue.type = EntityStatsManager::ValueType::VEC3F;
    rotationValue.isModifiable = true;
    rotationValue.usesSlider = true;
    rotationValue.min = -360.0f;
    rotationValue.max = 360.0f;
    values.push_back(rotationValue);
    EntityStatsManager::Value scaleValue;
    scaleValue.name = "Scale";
    scaleValue.data = reinterpret_cast<void*>(&scale);
    positionValue.valueDirty = &dirty;
    scaleValue.type = EntityStatsManager::ValueType::VEC3F;
    scaleValue.isModifiable = true;
    scaleValue.usesSlider = true;
    scaleValue.min = 0.1f; // Lower value crashes
    scaleValue.max = 100.0f;
    values.push_back(scaleValue);
    return values;
}
References dirty, GLESC::isIterable_v, EntityStatsManager::Value::name, position, rotationDegrees, scale, and EntityStatsManager::VEC3F.
Referenced by GLESC::ECS::TransformComponent::setDebuggingValues().
getModelMatrix()
Render::Model GLESC::Transform::Transform::getModelMatrix () const inline
Returns the model matrix of the transform.
Will not be recalculated if the transform has not changed as it is a heavy operation. It uses a dirty flag to check if the transform has changed.
Returns
The model matrix of the transform.
Definition at line 186 of file Transform.h.
{
            if (modelDirty) {
                modelMat.makeModelMatrix(position, rotationDegrees.toRads(), scale);
                modelDirty = false;
            }
            return modelMat;
        }
References GLESC::Math::Matrix< Type, N, M >::makeModelMatrix(), modelDirty, modelMat, position, rotationDegrees, scale, and GLESC::Math::Vector< Type, N >::toRads().
Referenced by GLESC::Transform::Transformer::transformBoundingVolume(), and GLESC::Transform::Transformer::transformMesh().
getPosition()
const Position & GLESC::Transform::Transform::getPosition () const inline
Definition at line 63 of file Transform.h.
{ return position; }
References position.
Referenced by GLESC::Render::Renderer::createViewMatrix(), GLESC::Transform::Interpolator::interpolate(), GLESC::Transform::Interpolator::pushTransform(), GLESC::Render::Renderer::render(), and GLESC::Engine::update().
getRotation()
const Rotation & GLESC::Transform::Transform::getRotation () const inline
Definition at line 64 of file Transform.h.
{ return rotationDegrees; }
References rotationDegrees.
Referenced by GLESC::Render::Renderer::createViewMatrix(), and GLESC::Transform::Interpolator::interpolate().
getRotationMatrix()
Render::RotateMat GLESC::Transform::Transform::getRotationMatrix () const inline
Returns the rotation matrix of the transform.
Will not be recalculated if the rotation has not changed as it is a heavy operation. It uses a dirty flag to check if the rotation has changed.
Returns
The rotation matrix of the transform.
Definition at line 214 of file Transform.h.
{
            if (rotateDirty) {
                rotateMat.makeRotationMatrix(rotationDegrees.toRads());
                rotateDirty = false;
            }
            return rotateMat;
        }
References GLESC::Math::Matrix< Type, N, M >::makeRotationMatrix(), rotateDirty, rotateMat, rotationDegrees, and GLESC::Math::Vector< Type, N >::toRads().
getScale()
const Scale & GLESC::Transform::Transform::getScale () const inline
Definition at line 65 of file Transform.h.
{ return scale; }
References scale.
Referenced by GLESC::Transform::Interpolator::interpolate().
getScaleMatrix()
Render::ScaleMat GLESC::Transform::Transform::getScaleMatrix () const inline
Returns the scale matrix of the transform.
Will not be recalculated if the scale has not changed as it is a heavy operation. It uses a dirty flag to check if the scale has changed.
Returns
The scale matrix of the transform.
Definition at line 228 of file Transform.h.
{
            if (scaleDirty) {
                scaleMat.makeScaleMatrix(scale);
                scaleDirty = false;
            }
            return scaleMat;
        }
References GLESC::Math::Matrix< Type, N, M >::makeScaleMatrix(), scale, scaleDirty, and scaleMat.
getTranslationMatrix()
Render::TranslateMat GLESC::Transform::Transform::getTranslationMatrix () const inline
Returns the translation matrix of the transform.
Will not be recalculated if the position has not changed as it is a heavy operation. It uses a dirty flag to check if the position has changed.
Returns
The translation matrix of the transform.
Definition at line 200 of file Transform.h.
{
            if (translateDirty) {
                translateMat.makeTranslationMatrix(position);
                translateDirty = false;
            }
            return translateMat;
        }
References GLESC::Math::Matrix< Type, N, M >::makeTranslationMatrix(), position, translateDirty, and translateMat.
Referenced by translateBV().
operator==()
bool Transform::operator== (const Transform & other) const
Compares two transforms for equality.
This is necessary as we need to store transforms in a set (when we interpolate them)
Parameters
other The other transform to compare to.
Returns
True if the transforms are equal, false otherwise.
Definition at line 56 of file Transform.cpp.
{
    return position == other.position && rotationDegrees == other.rotationDegrees && scale == other.scale;
}
References GLESC::isIterable_v, position, rotationDegrees, and scale.
right()
GLESC::Math::Direction Transform::right () const
Calculates the right vector using the rotation.
Returns
The right vector
Definition at line 31 of file Transform.cpp.
{
    if (dirty)
        return calculateRight();
    return rightDirection;
}
References calculateRight(), dirty, and rightDirection.
Referenced by GLESC::EngineCamera::moveLeft(), and GLESC::EngineCamera::moveRight().
setPosition() [1/2]
void GLESC::Transform::Transform::setPosition (Axis axis, PosComp value) inline
Definition at line 85 of file Transform.h.
{
            dirty = true;
            translateDirty = true;
            int index = static_cast<int>(axis);
            position.set(index, value);
        }
References dirty, GLESC::isIterable_v, position, GLESC::Math::Vector< Type, N >::set(), and translateDirty.
setPosition() [2/2]
void GLESC::Transform::Transform::setPosition (const Position & position) inline
Definition at line 67 of file Transform.h.
{
            dirty = true;
            translateDirty = true;
            this->position = position;
        }
References dirty, position, and translateDirty.
Referenced by addPosition(), addPosition(), GLESC::Physics::CollisionManager::checkAndUpdateColliderInformation(), and GLESC::Transform::Interpolator::interpolate().
setRotation() [1/2]
void GLESC::Transform::Transform::setRotation (const Rotation & rotation) inline
Definition at line 73 of file Transform.h.
{
            dirty = true;
            rotateDirty = true;
            this->rotationDegrees = rotation;
        }
References dirty, GLESC::isIterable_v, rotateDirty, and rotationDegrees.
Referenced by addRotation(), and addRotation().
setRotation() [2/2]
void GLESC::Transform::Transform::setRotation (RotationAxis axis, RotComp value) inline
Definition at line 92 of file Transform.h.
{
            dirty = true;
            rotateDirty = true;
            int index = static_cast<int>(axis);
            rotationDegrees.set(index, value);
        }
References dirty, GLESC::isIterable_v, rotateDirty, rotationDegrees, and GLESC::Math::Vector< Type, N >::set().
setScale() [1/2]
void GLESC::Transform::Transform::setScale (Axis axis, ScaleComp value) inline
Definition at line 99 of file Transform.h.
{
            dirty = true;
            scaleDirty = true;
            int index = static_cast<int>(axis);
            scale.set(index, value);
        }
References dirty, GLESC::isIterable_v, scale, scaleDirty, and GLESC::Math::Vector< Type, N >::set().
setScale() [2/2]
void GLESC::Transform::Transform::setScale (const Scale & scale) inline
Definition at line 79 of file Transform.h.
{
            dirty = true;
            scaleDirty = true;
            this->scale = scale;
        }
References dirty, scale, and scaleDirty.
Referenced by addScale(), and addScale().
toString()
std::string Transform::toString () const override virtual
Converts the transform to a string.
For debugging purposes.
Returns
The string representation of the transform.
Implements EngineComponent.
Definition at line 60 of file Transform.cpp.
{
    return "Position: " + position.toString() + "\n" +
        "Rotation: " + rotationDegrees.toString() + "\n" +
        "Scale: " + scale.toString();
}
References position, rotationDegrees, scale, and GLESC::Math::Vector< Type, N >::toString().
Referenced by GLESC::ECS::TransformComponent::toString().
up()
GLESC::Math::Direction Transform::up () const
Calculates the up vector using the rotation.
Returns
The up vector
Definition at line 37 of file Transform.cpp.
{
    if (dirty)
        return calculateUp();
    return forwardDirection;
}
References calculateUp(), dirty, and forwardDirection.
Member Data Documentation
dirty
bool GLESC::Transform::Transform::dirty = true mutable private
Definition at line 343 of file Transform.h.
Referenced by forward(), getDebuggingValues(), right(), setPosition(), setPosition(), setRotation(), setRotation(), setScale(), setScale(), and up().
forwardDirection
Math::Direction GLESC::Transform::Transform::forwardDirection private
The forward direction of the transform so we don't have to recalculate it every time.
Definition at line 307 of file Transform.h.
Referenced by forward(), and up().
modelDirty
bool GLESC::Transform::Transform::modelDirty = true mutable private
Definition at line 323 of file Transform.h.
Referenced by getModelMatrix().
modelMat
Render::Model GLESC::Transform::Transform::modelMat mutable private
The model matrix of the transform.
it is mutable so we can recalculate it directly in the const getter.
Definition at line 322 of file Transform.h.
Referenced by Transform(), and getModelMatrix().
position
Position GLESC::Transform::Transform::position = Position(0.0f, 0.0f, 0.0f) private
The position of the transform.
Definition at line 294 of file Transform.h.
Referenced by Transform(), addPosition(), addPosition(), getDebuggingValues(), getModelMatrix(), getPosition(), getTranslationMatrix(), operator==(), setPosition(), setPosition(), and toString().
rightDirection
Math::Direction GLESC::Transform::Transform::rightDirection private
The right direction of the transform so we don't have to recalculate it every time.
Definition at line 311 of file Transform.h.
Referenced by right().
rotateDirty
bool GLESC::Transform::Transform::rotateDirty = true mutable private
Definition at line 335 of file Transform.h.
Referenced by getRotationMatrix(), setRotation(), and setRotation().
rotateMat
Render::RotateMat GLESC::Transform::Transform::rotateMat mutable private
The rotation matrix of the transform.
it is mutable so we can recalculate it directly in the const getter.
Definition at line 334 of file Transform.h.
Referenced by getRotationMatrix().
rotationDegrees
Rotation GLESC::Transform::Transform::rotationDegrees = Rotation(0.0f, 0.0f, 0.0f) private
The rotation of the transform.
Definition at line 298 of file Transform.h.
Referenced by Transform(), addRotation(), addRotation(), calculateForward(), calculateRight(), calculateUp(), getDebuggingValues(), getModelMatrix(), getRotation(), getRotationMatrix(), operator==(), setRotation(), setRotation(), and toString().
scale
Scale GLESC::Transform::Transform::scale = Scale(1.0f, 1.0f, 1.0f) private
The scale of the transform.
Definition at line 302 of file Transform.h.
Referenced by Transform(), addScale(), addScale(), getDebuggingValues(), getModelMatrix(), getScale(), getScaleMatrix(), operator==(), setScale(), setScale(), and toString().
scaleDirty
bool GLESC::Transform::Transform::scaleDirty = true mutable private
Definition at line 341 of file Transform.h.
Referenced by getScaleMatrix(), setScale(), and setScale().
scaleMat
Render::ScaleMat GLESC::Transform::Transform::scaleMat mutable private
The scale matrix of the transform.
it is mutable so we can recalculate it directly in the const getter.
Definition at line 340 of file Transform.h.
Referenced by getScaleMatrix().
translateDirty
bool GLESC::Transform::Transform::translateDirty = true mutable private
Definition at line 329 of file Transform.h.
Referenced by getTranslationMatrix(), setPosition(), and setPosition().
translateMat
Render::TranslateMat GLESC::Transform::Transform::translateMat mutable private
The translation matrix of the transform.
it is mutable so we can recalculate it directly in the const getter.
Definition at line 328 of file Transform.h.
Referenced by getTranslationMatrix().
upDirection
Math::Direction GLESC::Transform::Transform::upDirection private
The up direction of the transform so we don't have to recalculate it every time.
Definition at line 315 of file Transform.h.
worldForward
GLESC::Math::Direction Transform::worldForward {Math::Direction(0.0f, 0.0f, 1.0f)} static
Definition at line 48 of file Transform.h.
worldRight
GLESC::Math::Direction Transform::worldRight {Math::Direction(1.0f, 0.0f, 0.0f)} static
Definition at line 47 of file Transform.h.
worldUp
GLESC::Math::Direction Transform::worldUp {Math::Direction(0.0f, 1.0f, 0.0f)} static
Definition at line 46 of file Transform.h.
Referenced by GLESC::EngineCamera::moveDown(), and GLESC::EngineCamera::moveUp().
The documentation for this struct was generated from the following files:
Transform.h
Transform.cpp