GLESC: GLESC::Render::ColorRgbNorm Struct Reference
GLESC::Render::ColorRgbNorm Struct Reference
Color in normalized values.
#include <RendererTypes.h>
Public Member Functions
ColorRgbNorm ()
ColorRgbNorm (const ColorRgb &colorRgb)
ColorRgbNorm (float r, float g, float b)
float getB () const
float getG () const
float getR () const
ColorRgbNorm & operator= (const ColorRgb &colorRgb)
ColorRgbNorm & operator= (const ColorRgbNorm &other)
bool operator== (const ColorRgbNorm &other) const
std::string toString () const
Public Member Functions inherited from GLESC::Math::Vector< Type, N >
constexpr Vector () noexcept
Default constructor.
template<typename... Args, typename = std::enable_if_t<(sizeof...(Args) == N)>>
constexpr Vector (Args &&... args) noexcept
Variadic constructor.
constexpr Vector (const Type(&list)[N]) noexcept
Array constructor.
constexpr Vector (const Vector &other) noexcept
Copy constructor.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &&other) noexcept
Move constructor, for vectors of different sizes.
template<size_t N2>
constexpr Vector (const Vector< Type, N2 > &other) noexcept
Copy constructor.
constexpr Vector (const VectorData< Type, N > &values) noexcept
Copy constructor for VectorData.
constexpr Vector (Type values) noexcept
Fill constructor.
constexpr Vector (Vector &&other) noexcept
Move constructor.
constexpr Vector (VectorData< Type, N > &&values) noexcept
Move constructor for VectorData.
Vector abs () const noexcept
Returns the absolute value of the vector.
Type angle (const Vector &other) const
Gives the rads between two vectors.
Type angleDegrees (const Vector &other) const
Gives the angle between two vectors in degrees.
Vector clamp (const Vector &min, const Vector &max) const
Clamps the vector to a given range.
Vector clamp (Type min, Type max) const
Clamps the vector to a given range.
Vector< Type, 3 > cross (const Vector< Type, 3 > &other) const
Calculates the cross product of two vectors.
Vector< Type, N - 1 > dehomogenize () const
Dehomogenizes the vector.
Type distance (const Vector &other) const
Gives the distance between two vectors.
Type distanceSquared (const Vector &other) const
Gives the squared distance between two vectors.
Type dot (const Vector &rhs) const
Returns the dot product of two vectors.
const Type & get (size_t index) const
Returns the data of the vector given an index.
Vector getOrthogonal () const
Get an orthogonal (or perpendicular) vector.
Type getW () const
Returns the w (fourth) value of the vector.
const Type & getX () const
Returns the x (first) value of the vector.
Type getY () const
Returns the y (second) value of the vector.
Type getZ () const
Returns the z (third) value of the vector.
Vector< Type, N+1 > homogenize () const
Homogenizes the vector.
bool isCollinear (const std::vector< Vector< Type, 3 > > &points) const
Checks if the current vector is a scalar multiple of some vectors.
Type isHomogeneous () const
Checks if the vector is homogeneous.
bool isMultipleOf (const Vector &other) const
Checks if the current vector is a scalar multiple of another vector.
bool isNormalized () const
checks if the vector is normalized
bool isOrthogonal (const Vector &other) const
Checks if the vector is orthogonal to another vector.
bool isParallel (const Vector &other) const
Checks if the vector is parallel to another vector.
bool isZero () const
Checks if the vector is a zero vector.
Type length () const
Returns the length of the vector.
Type lengthSquared () const
Returns the squared length of the vector.
Vector lerp (const Vector &other, Type factor) const
Calculates the linear interpolation between two vectors using a factor.
Type magnitude () const
Returns the length of the vector.
Vector & makeForward (const Vector &rotation)
Returs the forward vector of a rotation.
Vector & makeRight (const Vector &rotation)
Returns the right vector of a rotation.
Vector & makeUp (const Vector &rotation)
Returns the up vector of a rotation.
Vector mod (Type divisor) const
Returns the mod of the vector given a divisor.
Vector mod (Vector divisors) const
Returns the mod of the vector given a vector of divisors.
Vector & normalize ()
Normalizes the vector.
Vector normalize () const
Normalizes the vector.
constexpr bool operator!= (const Vector &rhs) const
Inequality operator for vectors.
constexpr Vector operator* (const Vector &rhs) const
Overloads the '*' operator for vector multiplication.
constexpr Vector operator* (Type scalar) const
Overloads the '*' operator for scalar multiplication.
constexpr Vector operator*= (const Type scalar)
In-place multiplication with a scalar.
constexpr Vector operator*= (const Vector &rhs)
In-place multiplication with another vector.
constexpr Vector operator+ (const Type &scalar) const
Overloads the '+' operator for scalar addition.
constexpr Vector operator+ (const Vector &rhs) const
Overloads the '+' operator for vector addition.
constexpr Vector operator+= (const Vector &rhs)
In-place addition with another vector.
constexpr Vector operator+= (Type scalar)
In-place addition with a scalar.
constexpr Vector operator- () const
Overloads the unary '-' operator for negation.
constexpr Vector operator- (const Type &scalar) const
Overloads the '-' operator for scalar subtraction.
constexpr Vector operator- (const Vector &rhs) const
Overloads the '-' operator for vector subtraction.
constexpr Vector operator-= (const Type scalar)
In-place subtraction with a scalar.
constexpr Vector operator-= (const Vector &rhs)
In-place subtraction with another vector.
constexpr Vector operator/ (const Vector &rhs) const
Overloads the '/' operator for vector division.
constexpr Vector operator/ (Type scalar) const
Overloads the '/' operator for scalar division.
constexpr Vector operator/= (const Type scalar)
In-place division with a scalar.
constexpr Vector operator/= (const Vector &rhs)
In-place division with another vector.
constexpr bool operator< (const Vector &rhs) const
Less than operator for vectors.
constexpr bool operator<= (const Vector &rhs) const
Less than or equal to operator for vectors.
constexpr Vector & operator= (const Type(&list)[N]) noexcept
Array assignment operator.
constexpr Vector & operator= (const Vector &other) noexcept
Copy assignment operator.
constexpr Vector & operator= (Vector &&other) noexcept
Move assignment operator.
template<typename OtherType >
constexpr bool operator== (const Vector< OtherType, N > &rhs) const
Equality operator for vectors.
constexpr bool operator> (const Vector &rhs) const
Greater than operator for vectors.
constexpr bool operator>= (const Vector &rhs) const
Greater than or equal to operator for vectors.
Type & operator[] (size_t index)
Returns the data of the vector given an index.
const Type & operator[] (size_t index) const
Returns the data of the vector given an index, const version (read only)
Vector project (const Vector &other) const
Projects the vector onto another vector.
Vector & reflect (const Vector &normal)
Reflects the vector by a given normal, modifying the current vector.
Vector reflect (const Vector &normal) const
Reflects the vector by a given normal.
Vector< Type, 3 > & rotate (const Vector< Type, 3 > &rotation)
Rotates the vector by a given rotation.
Vector< Type, 3 > rotate (const Vector< Type, 3 > &rotation) const
Rotates the vector by a given rotation.
void set (size_t index, Type value)
Sets the data of the vector given an index.
void setW (Type value)
Sets the w (fourth) value of the vector.
void setX (Type value)
Sets the x (first) value of the vector.
void setY (Type value)
Sets the y (second) value of the vector.
void setZ (Type value)
Sets the z (third) value of the vector.
int size () const
Returns the size of the vector.
Type sum () const
Returns the sum of all the elements in the vector.
void swap (Vector &other) noexcept
Swaps the data of this vector with another vector.
Vector toDegrees () const
Converts the vector to degrees.
MatrixData< Type, N, 1 > toMatrix () const
Converts the vector to a single column matrix.
Vector toRads () const
Converts the vector to radians.
std::string toString () const
Converts the vector to string.
Vector & vectorToEulerRotation (const Vector &up)
Converts the vector to euler angles.
Vector vectorToEulerRotation (const Vector &up) const
Converts the vector to euler angles.
Type & w ()
Returns the w (fourth) value of the vector.
void w (Type value)
Sets the w (fourth) value of the vector.
Type & x ()
Returns the x (reference) value of the vector.
void x (Type value)
Sets the x (first) value of the vector.
Type & y ()
Returns the y (second) value of the vector.
void y (Type value)
Sets the y (second) value of the vector.
Type & z ()
Returns the z (third) value of the vector.
void z (Type value)
Sets the z (third) value of the vector.
Additional Inherited Members
Public Types inherited from GLESC::Math::Vector< Type, N >
using ValueType = Type
Public Attributes inherited from GLESC::Math::Vector< Type, N >
VectorData< Type, N > data
Data of the vector.
Detailed Description
Color in normalized values.
This cannot be constructed on its own, must be constructed from a ColorRgb
Definition at line 425 of file RendererTypes.h.
Constructor & Destructor Documentation
ColorRgbNorm() [1/3]
GLESC::Render::ColorRgbNorm::ColorRgbNorm () inline
Definition at line 426 of file RendererTypes.h.
                       : Vec3F(0) {
        }
ColorRgbNorm() [2/3]
GLESC::Render::ColorRgbNorm::ColorRgbNorm (float r, float g, float b) inline explicit
Definition at line 441 of file RendererTypes.h.
{
            D_ASSERT_LESS_OR_EQUAL(r, 1.0f, "R must be less or equal than 1");
            D_ASSERT_GREATER_OR_EQUAL(r, 0.0f, "R must be greater or equal than 0");
            D_ASSERT_LESS_OR_EQUAL(g, 1.0f, "G must be less or equal than 1");
            D_ASSERT_GREATER_OR_EQUAL(g, 0.0f, "G must be greater or equal than 0");
            D_ASSERT_LESS_OR_EQUAL(b, 1.0f, "B must be less or equal than 1");
            D_ASSERT_GREATER_OR_EQUAL(b, 0.0f, "B must be greater or equal than 0");
            data[0] = r;
            data[1] = g;
            data[2] = b;
        }
References D_ASSERT_GREATER_OR_EQUAL, D_ASSERT_LESS_OR_EQUAL, and GLESC::Math::Vector< Type, N >::data.
ColorRgbNorm() [3/3]
GLESC::Render::ColorRgbNorm::ColorRgbNorm (const ColorRgb & colorRgb) inline explicit
Definition at line 454 of file RendererTypes.h.
{
            data[0] = colorRgb.getRNormalized();
            data[1] = colorRgb.getGNormalized();
            data[2] = colorRgb.getBNormalized();
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
Member Function Documentation
getB()
float GLESC::Render::ColorRgbNorm::getB () const inline
Definition at line 437 of file RendererTypes.h.
{
            return data[2];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
getG()
float GLESC::Render::ColorRgbNorm::getG () const inline
Definition at line 433 of file RendererTypes.h.
{
            return data[1];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
getR()
float GLESC::Render::ColorRgbNorm::getR () const inline
Definition at line 429 of file RendererTypes.h.
{
            return data[0];
        }
References GLESC::Math::Vector< Type, N >::data.
Referenced by toString().
operator=() [1/2]
ColorRgbNorm & GLESC::Render::ColorRgbNorm::operator= (const ColorRgb & colorRgb) inline
Definition at line 464 of file RendererTypes.h.
{
            data[0] = colorRgb.getRNormalized();
            data[1] = colorRgb.getGNormalized();
            data[2] = colorRgb.getBNormalized();
            return *this;
        }
References GLESC::Math::Vector< Type, N >::data, and GLESC::isIterable_v.
operator=() [2/2]
ColorRgbNorm & GLESC::Render::ColorRgbNorm::operator= (const ColorRgbNorm & other) inline
Definition at line 471 of file RendererTypes.h.
{
            Vec3F::operator=(other);
            return *this;
        }
References GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::operator=().
operator==()
bool GLESC::Render::ColorRgbNorm::operator== (const ColorRgbNorm & other) const inline
Definition at line 460 of file RendererTypes.h.
{
            return Vec3F::operator==(other);
        }
References GLESC::isIterable_v, and GLESC::Math::Vector< Type, N >::operator==().
toString()
std::string GLESC::Render::ColorRgbNorm::toString () const inline
Definition at line 476 of file RendererTypes.h.
{
            return "R:" + Stringer::toString(getR()) +
                " G:" + Stringer::toString(getG()) +
                " B:" + Stringer::toString(getB());
        }
References getB(), getG(), getR(), and GLESC::Stringer::toString().
The documentation for this struct was generated from the following file:
RendererTypes.h