if (WIN32)
  set(PLATFORM "__WINDOWS__")
  important_info("Compiling in Platform: Windows")
elseif (UNIX AND NOT APPLE)
  set(PLATFORM "__LINUX__")
  important_info("Compiling in Platform: Linux")
elseif (APPLE)
  set(PLATFORM "__APPLE__")
  important_info("Compiling in Platform: Apple")
endif ()