function(detect_platform)
  if (WIN32)
    set(PLATFORM "__WINDOWS__")
    important_info("Detected Platform: Windows")
  elseif (UNIX AND NOT APPLE)
    set(PLATFORM "__LINUX__")
    important_info("Detected Platform: Linux")
  elseif (APPLE)
    set(PLATFORM "__APPLE__")
    important_info("Detected Platform: Apple")
  endif ()
endfunction()